/**
 * Thinking Framework Registry — every visual and strategic model Shari can teach.
 */

import type { SparkKnowledgeEntry } from "./types";

function framework(
  partial: Omit<SparkKnowledgeEntry, "kind" | "sourceRegistry" | "explain"> & {
    when: string;
    who: string;
    how: string;
    related: readonly string[];
    nextSteps: readonly string[];
  },
): SparkKnowledgeEntry {
  return {
    ...partial,
    kind: "framework",
    sourceRegistry: "thinkingFrameworkRegistry",
    explain: {
      what: partial.description,
      why: partial.purpose,
      when: partial.when,
      who: partial.who,
      how: partial.how,
      related: partial.related,
      nextSteps: partial.nextSteps,
    },
  };
}

export const THINKING_FRAMEWORKS: readonly SparkKnowledgeEntry[] = [
  framework({
    id: "business-model-canvas",
    name: "Business Model Canvas",
    purpose: "See how the whole business fits together on one page.",
    description:
      "Nine building blocks — customers, value, channels, revenue, costs, and more.",
    triggers: ["business model canvas", "bmc", "business model"],
    aliases: ["bmc"],
    when: "Starting, pivoting, or explaining the business to someone else.",
    who: "Founders clarifying offers, teams aligning on strategy.",
    how: "Walk through each block conversationally — one at a time, not a form.",
    related: ["Lean Canvas", "Value Proposition Canvas", "Client Avatar"],
    nextSteps: ["Offer design", "Marketing plan", "Momentum project"],
  }),
  framework({
    id: "lean-canvas",
    name: "Lean Canvas",
    purpose: "Test a business idea quickly without a long plan.",
    description:
      "Problem, solution, unfair advantage, channels, revenue — startup-focused.",
    triggers: ["lean canvas", "lean startup canvas"],
    aliases: [],
    when: "Early-stage ideas, validating before heavy investment.",
    who: "Entrepreneurs with a hypothesis to test.",
    how: "Start with problem and customer — validate before filling every box.",
    related: ["Business Model Canvas", "SWOT", "Client Avatar"],
    nextSteps: ["Interview customers", "Build MVP", "Create offer"],
  }),
  framework({
    id: "value-proposition-canvas",
    name: "Value Proposition Canvas",
    purpose: "Match what you offer to what your customer actually needs.",
    description: "Customer profile on one side, value map on the other.",
    triggers: ["value proposition", "value prop canvas"],
    aliases: ["vpc"],
    when: "Messaging feels off, conversions are weak, or offer is unclear.",
    who: "Anyone refining an offer, sales page, or marketing message.",
    how: "Customer jobs, pains, gains first — then map how you relieve and create.",
    related: ["Client Avatar", "Business Model Canvas", "Marketing plan"],
    nextSteps: ["Rewrite offer", "Sales page", "Email sequence"],
  }),
  framework({
    id: "swot",
    name: "SWOT Analysis",
    purpose: "See strengths, weaknesses, opportunities, and threats clearly.",
    description: "Four-quadrant snapshot of internal and external factors.",
    triggers: ["swot", "strengths weaknesses", "swot analysis"],
    aliases: [],
    when: "Planning a pivot, launch, or annual strategy session.",
    who: "Decision-makers who need a honest landscape before committing.",
    how: "Strengths and weaknesses first — then look outward for opportunities.",
    related: ["Decision Matrix", "Roadmap", "Business plan"],
    nextSteps: ["Prioritize actions", "Quarterly plan", "Risk mitigation"],
  }),
  framework({
    id: "mind-map",
    name: "Mind Map",
    purpose: "See connections between ideas without linear order.",
    description: "Central idea with branches — visual brainstorming.",
    triggers: ["mind map", "mindmap", "brainstorm map"],
    aliases: [],
    when: "Brainstorming, untangling complexity, or planning content.",
    who: "Visual thinkers, ADHD brains, creative planners.",
    how: "Start with one central question — branch freely, organize later.",
    related: ["Concept Map", "Whiteboard", "Visual Thinking Studio"],
    nextSteps: ["Outline document", "Project plan", "Create draft"],
  }),
  framework({
    id: "concept-map",
    name: "Concept Map",
    purpose: "Show how concepts relate — learning and teaching.",
    description: "Labeled links between ideas — cause, supports, part of.",
    triggers: ["concept map", "knowledge map"],
    aliases: [],
    when: "Learning something new, teaching a team, or documenting systems.",
    who: "Learners, trainers, anyone building shared understanding.",
    how: "Name the core concept — link related ideas with relationship words.",
    related: ["Mind Map", "Process Map", "Knowledge Library"],
    nextSteps: ["SOP", "Training guide", "Course outline"],
  }),
  framework({
    id: "fishbone",
    name: "Fishbone Diagram",
    purpose: "Find root causes instead of treating symptoms.",
    description: "Ishikawa diagram — problem at the head, causes along the spine.",
    triggers: ["fishbone", "ishikawa", "root cause", "five whys"],
    aliases: ["cause and effect diagram"],
    when: "Something keeps going wrong and the obvious fix didn't work.",
    who: "Operations, quality improvement, troubleshooting teams.",
    how: "State the problem clearly — branch into people, process, tools, environment.",
    related: ["Five Whys", "Process Map", "SOP"],
    nextSteps: ["Fix root cause", "Update SOP", "Checklist"],
  }),
  framework({
    id: "decision-matrix",
    name: "Decision Matrix",
    purpose: "Compare options when gut feel isn't enough.",
    description: "Score choices against criteria that matter to you.",
    triggers: ["decision matrix", "compare options", "weighted decision"],
    aliases: ["decision grid"],
    when: "Two or more real options — hire, tool, direction, vendor.",
    who: "Slow decision-makers, high-stakes choices, teams needing alignment.",
    how: "Name criteria and weight them — score each option honestly.",
    related: ["Decision Tree", "SWOT", "Decision Compass"],
    nextSteps: ["Commit to choice", "Action plan", "Review date"],
  }),
  framework({
    id: "decision-tree",
    name: "Decision Tree",
    purpose: "Map choices and consequences before you commit.",
    description: "Branches for each decision point and likely outcome.",
    triggers: ["decision tree", "if then decision"],
    aliases: [],
    when: "Sequential decisions with uncertain outcomes.",
    who: "Strategists, product decisions, contingency planning.",
    how: "Start at today's decision — branch for each path and what follows.",
    related: ["Decision Matrix", "Roadmap", "Scenario planning"],
    nextSteps: ["Choose branch", "Set milestones", "Monitor signals"],
  }),
  framework({
    id: "roadmap",
    name: "Roadmap",
    purpose: "See where you're going and what comes first.",
    description: "Timeline of goals, milestones, and dependencies.",
    triggers: ["roadmap", "timeline", "quarterly plan"],
    aliases: ["project timeline"],
    when: "Launch planning, quarterly goals, multi-month projects.",
    who: "Founders, project leads, anyone juggling parallel work.",
    how: "Anchor on the outcome — work backward to milestones.",
    related: ["Momentum", "Project plan", "Marketing calendar"],
    nextSteps: ["Weekly plan", "Next actions", "Momentum project"],
  }),
  framework({
    id: "customer-journey",
    name: "Customer Journey Map",
    purpose: "Walk in your customer's shoes from first touch to loyalty.",
    description: "Stages, touchpoints, emotions, and gaps along the path.",
    triggers: ["customer journey", "journey map", "buyer journey"],
    aliases: [],
    when: "Improving experience, funnels, onboarding, or retention.",
    who: "Marketing, product, service businesses mapping client experience.",
    how: "Pick one avatar — map stages, what they think, feel, and need.",
    related: ["Client Avatar", "Funnel", "Value Proposition Canvas"],
    nextSteps: ["Fix friction points", "Content plan", "Email sequence"],
  }),
  framework({
    id: "client-avatar",
    name: "Client Avatar",
    purpose: "Know exactly who you're serving — not everyone.",
    description: "Ideal client profile — goals, pains, language, objections.",
    triggers: ["client avatar", "ideal client", "customer persona", "buyer persona"],
    aliases: ["persona", "icp"],
    when: "Messaging, offers, content, or ads feel generic.",
    who: "Anyone selling services, courses, or products to a specific person.",
    how: "One real person in mind — name them, know their Tuesday morning.",
    related: ["Value Proposition Canvas", "Marketing plan", "Email"],
    nextSteps: ["Offer refinement", "Sales page", "Content calendar"],
  }),
  framework({
    id: "process-map",
    name: "Process Map",
    purpose: "See how work actually flows — step by step.",
    description: "Visual workflow from start to finish with decision points.",
    triggers: ["process map", "workflow map", "flowchart"],
    aliases: ["workflow diagram"],
    when: "Documenting operations, onboarding a VA, or fixing bottlenecks.",
    who: "Operations, teams handing off work, SOP authors.",
    how: "Start where work enters — each step, handoff, and decision.",
    related: ["SOP", "Checklist", "Fishbone"],
    nextSteps: ["Write SOP", "Create checklist", "Train team"],
  }),
  framework({
    id: "whiteboard",
    name: "Whiteboard",
    purpose: "Think out loud visually — no structure required yet.",
    description: "Freeform canvas for sketches, notes, and spatial thinking.",
    triggers: ["whiteboard", "visual thinking", "sketch ideas"],
    aliases: [],
    when: "Ideas aren't linear yet, workshops, collaborative thinking.",
    who: "Visual thinkers, workshop facilitators, ADHD brains.",
    how: "Put everything on the board — cluster and name patterns later.",
    related: ["Mind Map", "Visual Thinking Studio", "Concept Map"],
    nextSteps: ["Organize into plan", "Create document", "Share with team"],
  }),
];

export function thinkingFrameworkById(
  id: string,
): SparkKnowledgeEntry | undefined {
  return THINKING_FRAMEWORKS.find((f) => f.id === id);
}
