import type { StrategyTypeContract } from "../types";

export const growthStrategyType: StrategyTypeContract = {
  id: "growth",
  name: "Growth Strategy",
  family: "customer_and_market",
  plainLanguageDescription:
    "Decide how — or whether — to grow by diagnosing the real bottleneck, not assuming more customers is always the answer.",
  useWhen: [
    "Growth feels stalled or uneven",
    "The business wants more customers or revenue",
    "Capacity may not support more demand",
    "Unsure whether the issue is awareness, offer, sales, or retention",
  ],
  doNotUseWhen: ["The real need is emotional recovery only"],
  entrySignals: [
    /\b(grow|growth|more customers|scale|expand|not growing|acquisition|leads|pipeline)\b/i,
  ],
  clarifyingQuestions: [
    "When you say growth, what would actually feel like progress?",
    "Is the real decision about more customers, more revenue, better retention, or something else?",
    "Which part feels stuck — awareness, positioning, offer, sales, retention, or capacity?",
  ],
  currentStateQuestions: [
    "What growth approaches have you already tried?",
    "Where does demand currently come from?",
    "If more people said yes tomorrow, could you deliver well?",
  ],
  directionQuestions: [
    "What kind of growth would still feel sustainable?",
    "What should not be sacrificed for growth?",
    "Would “don’t grow yet” be the honest answer this season?",
  ],
  optionPatterns: [
    "expand",
    "narrow",
    "protect_current_base",
    "improve",
    "stabilize",
    "test",
    "delay",
    "simplify",
  ],
  decisionCriteria: [
    "bottleneck diagnosis",
    "capacity",
    "retention",
    "unit economics",
    "focus",
    "timing",
  ],
  commonTradeoffs: [
    "acquisition vs retention",
    "speed vs delivery quality",
    "expansion vs focus",
    "referral systems vs paid reach",
  ],
  commonRisks: [
    "overpromising delivery",
    "chasing vanity growth",
    "growing into a capacity crisis",
    "fixing awareness when the offer is weak",
  ],
  commonAssumptions: [
    "more customers fix everything",
    "awareness is the only gap",
    "growth must happen now",
    "every channel should run at once",
  ],
  evidencePrompts: [
    "What evidence shows acquisition is the bottleneck?",
    "Where do people drop off today?",
    "What do retained customers say made them stay?",
  ],
  capacityChecks: [
    "If growth worked, could you deliver well?",
    "Would more demand create hidden maintenance you cannot carry?",
  ],
  experimentPatterns: [
    "Test one channel or segment before broad expansion",
    "Improve conversion on existing traffic before buying more attention",
    "Run a referral ask with happy customers for 30 days",
    "Stabilize delivery for one season before expanding",
  ],
  successSignals: [
    "Sustainable new demand",
    "Delivery stays steady",
    "Clearer diagnosis of the real bottleneck",
  ],
  reviewTriggers: ["Delivery strain", "Cash pressure", "Retention drop", "Lead quality falls"],
  recommendedChamberMembers: ["strategy", "marketing"],
  recommendedBoardRoles: ["strategy-director"],
  handoffDestinations: ["project", "create", "board", "business_estate"],
  adaptivePresentationNotes:
    "Do not default to expand; include stabilize / wait / don’t grow yet when capacity is tight.",
  qualityChecks: [
    "Capacity checked before expand",
    "Bottleneck named (not only “get more customers”)",
  ],
  decisionHeuristics: [
    {
      id: "diagnose_before_scale",
      rule: "Name the bottleneck before choosing a growth tactic.",
      when: "Member asks for more customers without diagnosing the funnel",
    },
    {
      id: "dont_grow_yet",
      rule: "“Don’t grow yet” is a valid strategic conclusion when capacity or offer is weak.",
      when: "Delivery is strained or the offer is unclear",
    },
    {
      id: "retention_before_acquisition",
      rule: "Fix leaky retention before pouring more acquisition.",
      when: "People leave soon after buying",
    },
    {
      id: "one_lever",
      rule: "Change one growth lever at a time so learning is clear.",
      when: "Many channels and offers are already active",
    },
  ],
  commonMistakes: [
    "Treating every growth problem as an awareness problem",
    "Scaling marketing into a broken offer",
    "Expanding before capacity can hold",
    "Ignoring referrals when happy customers already exist",
  ],
  warningSigns: [
    "Busy marketing, flat results",
    "Good conversations that do not convert",
    "New customers create chaos",
    "Churn offsets every acquisition win",
  ],
  problemDistinctions: [
    {
      id: "awareness",
      label: "Awareness problem",
      description: "The right people do not know you exist.",
      whenToSuspect: ["nobody knows", "no traffic", "invisible", "awareness", "reach"],
      preferredPatterns: ["test", "expand", "narrow"],
    },
    {
      id: "positioning",
      label: "Positioning problem",
      description: "People see you, but not clearly enough to choose you.",
      whenToSuspect: ["confused", "positioning", "look the same", "unclear difference"],
      preferredPatterns: ["reposition", "narrow", "improve"],
    },
    {
      id: "offer",
      label: "Offer problem",
      description: "Interest exists, but the offer does not earn a yes.",
      whenToSuspect: ["not converting", "hesitate", "offer", "package", "pricing feels off"],
      preferredPatterns: ["improve", "simplify", "test"],
    },
    {
      id: "sales",
      label: "Sales problem",
      description: "Interest is real, but conversations and closes are weak.",
      whenToSuspect: ["sales", "calls go nowhere", "pipeline", "follow up"],
      preferredPatterns: ["improve", "test", "stabilize"],
    },
    {
      id: "retention",
      label: "Retention problem",
      description: "Growth leaks because people do not stay.",
      whenToSuspect: ["churn", "retention", "cancel", "don’t stay", "leave after"],
      preferredPatterns: ["protect_current_base", "improve", "stabilize"],
    },
    {
      id: "capacity",
      label: "Capacity problem",
      description: "More demand would break delivery — don’t grow yet.",
      whenToSuspect: ["can’t keep up", "overwhelmed", "waitlist chaos", "capacity", "burned out"],
      preferredPatterns: ["stabilize", "simplify", "delay"],
    },
    {
      id: "referral",
      label: "Referral opportunity",
      description: "Happy customers may be an underused growth path.",
      whenToSuspect: ["referral", "word of mouth", "happy clients", "testimonials"],
      preferredPatterns: ["test", "improve", "protect_current_base"],
    },
    {
      id: "expansion_timing",
      label: "Expansion timing",
      description: "Growth may be right later, not this season.",
      whenToSuspect: ["not yet", "timing", "too soon", "after", "next year"],
      preferredPatterns: ["delay", "stabilize", "test"],
    },
  ],
  hiddenUnderlyingQuestions: [
    "Which bottleneck is real — awareness, positioning, offer, sales, retention, or capacity?",
    "If growth worked tomorrow, could delivery hold?",
    "Is “more customers” the goal, or more revenue, retention, or relief?",
    "Would not growing yet be the honest answer this season?",
  ],
  recommendationRules: [
    "Diagnose the bottleneck before recommending acquisition tactics.",
    "Prefer stabilize or delay when capacity is the constraint.",
    "Prefer retention repair before pouring more acquisition into a leaky base.",
    "“Do not grow yet” is a valid recommendation.",
  ],
  handoffBoundaries: [
    "Stay in Strategy until the growth bottleneck is named.",
    "Do not hand to Create/marketing execution while the diagnosis is still “more customers.”",
    "Project handoff only after a bounded growth experiment or direction is chosen.",
  ],
  guidingPrinciples: [
    "Do not default to “get more customers.”",
    "Sometimes the answer is: do not grow yet.",
    "Diagnose the bottleneck before choosing tactics.",
  ],
  version: 2,
};
