import type { StrategyTypeContract } from "../types";

export const offerStrategyType: StrategyTypeContract = {
  id: "offer",
  name: "Offer Strategy",
  family: "offers_and_innovation",
  plainLanguageDescription:
    "Clarify what you offer, to whom, and what should simplify, bundle, premium-ize, or retire — with delivery burden in view.",
  useWhen: [
    "The offer feels unclear or overloaded",
    "Considering a new offer, premium tier, or membership",
    "Current offer is not converting",
    "Delivery burden is rising with every sale",
  ],
  doNotUseWhen: ["Only need copy polish with no strategic change"],
  entrySignals: [
    /\b(offer|package|membership|program|product|bundl|premium offer|retire (an? )?offer|recurring)\b/i,
    /\b(launch an? |new offer|offer.?market)\b/i,
  ],
  clarifyingQuestions: [
    "What about the offer feels most important to decide?",
    "Are you deciding what to offer, who it is for, how it is packaged, or what to stop offering?",
    "Is the issue demand, clarity, delivery burden, or fit?",
  ],
  currentStateQuestions: [
    "What is working in the current offer?",
    "Where do people hesitate?",
    "What does delivering this offer actually cost you in time and energy?",
  ],
  directionQuestions: [
    "What should this offer make possible for the right person?",
    "What will you stop offering so this can be clear?",
    "Would a smaller, clearer offer beat a bigger one right now?",
  ],
  optionPatterns: [
    "simplify",
    "narrow",
    "reposition",
    "add_value",
    "test",
    "stop",
    "continue",
  ],
  decisionCriteria: [
    "offer-market fit",
    "clarity",
    "delivery burden",
    "differentiation",
    "recurring revenue fit",
    "customer outcomes",
  ],
  commonTradeoffs: [
    "breadth vs clarity",
    "premium vs accessible",
    "custom delivery vs scalable promise",
    "recurring revenue vs fulfillment load",
  ],
  commonRisks: [
    "overbuilding before demand",
    "confusing the market with too many offers",
    "retiring an offer that still funds the business",
    "premium pricing without premium outcomes",
  ],
  commonAssumptions: [
    "more features always help",
    "everyone wants the same offer",
    "a new offer will fix weak demand",
    "bundling always increases value",
  ],
  evidencePrompts: [
    "What have customers already said about the offer?",
    "Which outcomes do people actually get?",
    "Where does demand already exist without more building?",
  ],
  capacityChecks: [
    "Can you deliver this offer well at the volume you hope for?",
    "What hidden maintenance does this offer create?",
  ],
  experimentPatterns: [
    "Pilot one offer concept with a small audience",
    "Simplify one offer for 30 days and compare conversion",
    "Validate demand with a waitlist or pre-sell before building",
    "Test a premium add-on before redesigning the core offer",
  ],
  successSignals: [
    "Clearer yes/no from prospects",
    "Easier delivery",
    "Stronger outcomes stories",
  ],
  reviewTriggers: ["Conversion drops", "Delivery overload", "Support volume spikes"],
  recommendedChamberMembers: ["strategy", "innovation"],
  recommendedBoardRoles: ["strategy-director"],
  handoffDestinations: ["create", "project", "board"],
  adaptivePresentationNotes:
    "Keep options meaningfully different, not feature variants. Retiring an offer is valid.",
  qualityChecks: ["What not offering is named", "Delivery burden considered"],
  decisionHeuristics: [
    {
      id: "fit_before_features",
      rule: "Strengthen offer-market fit before adding features.",
      when: "Conversion is weak and the offer keeps growing",
    },
    {
      id: "simplify_first",
      rule: "Prefer simplification when prospects are confused.",
      when: "Too many packages or unclear outcomes",
    },
    {
      id: "validate_demand",
      rule: "Validate demand before building a heavy offer.",
      when: "New offer requires large creation effort",
    },
    {
      id: "retire_with_care",
      rule: "Retire offers that drain capacity or confuse the market — protect revenue transition.",
      when: "Legacy offers create support and messaging drag",
    },
  ],
  commonMistakes: [
    "Launching another offer instead of clarifying the main one",
    "Bundling without a clear outcome",
    "Ignoring delivery burden until burnout",
    "Chasing recurring revenue the business cannot fulfill",
  ],
  warningSigns: [
    "Prospects ask “which one is for me?” often",
    "Every sale creates custom exceptions",
    "Offers multiply faster than outcomes stories",
  ],
  problemDistinctions: [
    {
      id: "offer_market_fit",
      label: "Offer-market fit",
      description: "The offer may not match the people you are reaching.",
      whenToSuspect: ["wrong people", "not a fit", "they want something else"],
      preferredPatterns: ["narrow", "reposition", "test"],
    },
    {
      id: "simplification",
      label: "Simplification needed",
      description: "Clarity may matter more than adding options.",
      whenToSuspect: ["too many options", "confused", "simplify", "overwhelming"],
      preferredPatterns: ["simplify", "narrow", "stop"],
    },
    {
      id: "bundling",
      label: "Bundling / packaging",
      description: "Packaging may be the lever, not a brand-new offer.",
      whenToSuspect: ["bundle", "package", "tier", "include"],
      preferredPatterns: ["restructure_price", "simplify", "test"],
    },
    {
      id: "premium",
      label: "Premium offer",
      description: "A higher-touch or higher-price path may fit a smaller segment.",
      whenToSuspect: ["premium", "vip", "high touch", "done for you"],
      preferredPatterns: ["add_value", "narrow", "test"],
    },
    {
      id: "retire",
      label: "Retire an offer",
      description: "Stopping something may free capacity and clarity.",
      whenToSuspect: ["retire", "stop offering", "sunset", "kill"],
      preferredPatterns: ["stop", "simplify", "staged_transition"],
    },
    {
      id: "delivery_burden",
      label: "Delivery burden",
      description: "The offer may be strategically fine but operationally too heavy.",
      whenToSuspect: ["delivery", "can’t keep up", "custom every time", "support heavy"],
      preferredPatterns: ["simplify", "narrow", "stabilize"],
    },
  ],
  guidingPrinciples: [
    "Offer strategy includes what you will stop offering.",
    "Validate demand before heavy building.",
    "Customer outcomes beat feature lists.",
  ],
  version: 2,
};
