/**
 * Department → Knowledge Council mappings.
 * Each department declares purpose, sources, schools, disciplines, competencies.
 */

import type { BrainDepartment } from "../types";

type DeptCouncilSeed = Omit<
  BrainDepartment,
  "drawerIds" | "topicIds" | "coreCompetencyIds"
> & {
  competencySlugs: string[];
};

function dept(seed: DeptCouncilSeed): Omit<BrainDepartment, "drawerIds" | "topicIds"> {
  return {
    ...seed,
    coreCompetencyIds: seed.competencySlugs.map((s) => `comp-${s}`),
  };
}

/** Council metadata for all 44 Institute departments */
export const DEPARTMENT_COUNCIL_SEEDS: Omit<
  BrainDepartment,
  "drawerIds" | "topicIds"
>[] = [
  // Pillar I — Build Yourself
  dept({ id: "dept-entrepreneur-mindset", pillarId: "build_yourself", slug: "entrepreneur-mindset", name: "Entrepreneur Mindset", purpose: "Develop the identity, resilience, and orientation of a capable founder.", knowledgeSourceIds: ["src-mindset-research"], schoolOfThoughtIds: ["school-growth-mindset"], researchDisciplineIds: ["disc-adult-development", "disc-behavioral-psychology"], competencySlugs: ["entrepreneur-mindset", "self-trust"], sortOrder: 1 }),
  dept({ id: "dept-confidence-courage", pillarId: "build_yourself", slug: "confidence-courage", name: "Confidence & Courage", purpose: "Build confidence to act before feeling fully ready.", knowledgeSourceIds: ["src-mindset-research"], schoolOfThoughtIds: ["school-growth-mindset"], researchDisciplineIds: ["disc-adult-development", "disc-behavioral-psychology"], competencySlugs: ["confidence", "courage"], sortOrder: 2 }),
  dept({ id: "dept-adhd-entrepreneurship", pillarId: "build_yourself", slug: "adhd-entrepreneurship", name: "ADHD Entrepreneurship", purpose: "Design businesses that work with ADHD brains.", knowledgeSourceIds: ["src-ef-research"], schoolOfThoughtIds: ["school-adhd-friendly"], researchDisciplineIds: ["disc-executive-function-science", "disc-neuroscience"], competencySlugs: ["adhd-entrepreneurship", "executive-function"], sortOrder: 3 }),
  dept({ id: "dept-executive-function", pillarId: "build_yourself", slug: "executive-function", name: "Executive Function", purpose: "Strengthen planning, initiation, and follow-through.", knowledgeSourceIds: ["src-ef-research"], schoolOfThoughtIds: ["school-adhd-friendly"], researchDisciplineIds: ["disc-executive-function-science"], competencySlugs: ["executive-function", "planning", "prioritization", "focus"], sortOrder: 4 }),
  dept({ id: "dept-productivity-momentum", pillarId: "build_yourself", slug: "productivity-momentum", name: "Productivity & Momentum", purpose: "Create sustainable momentum without burnout.", knowledgeSourceIds: ["src-ef-research", "src-habit-science"], schoolOfThoughtIds: ["school-habit-architecture", "school-adhd-friendly"], researchDisciplineIds: ["disc-behavioral-psychology", "disc-habit-formation"], competencySlugs: ["productivity", "momentum"], sortOrder: 5 }),
  dept({ id: "dept-emotional-intelligence", pillarId: "build_yourself", slug: "emotional-intelligence", name: "Emotional Intelligence", purpose: "Regulate emotion and lead with empathy.", knowledgeSourceIds: ["src-communication-craft"], schoolOfThoughtIds: ["school-coaching-partnership"], researchDisciplineIds: ["disc-behavioral-psychology", "disc-organizational-psychology"], competencySlugs: ["emotional-intelligence", "self-awareness"], sortOrder: 6 }),
  dept({ id: "dept-habits-consistency", pillarId: "build_yourself", slug: "habits-consistency", name: "Habits & Consistency", purpose: "Build habits that compound capability.", knowledgeSourceIds: ["src-habit-science"], schoolOfThoughtIds: ["school-habit-architecture"], researchDisciplineIds: ["disc-habit-formation", "disc-behavioral-psychology"], competencySlugs: ["habits", "consistency"], sortOrder: 7 }),
  dept({ id: "dept-resilience-recovery", pillarId: "build_yourself", slug: "resilience-recovery", name: "Resilience & Recovery", purpose: "Recover capacity after hard seasons.", knowledgeSourceIds: ["src-mindset-research"], schoolOfThoughtIds: ["school-growth-mindset"], researchDisciplineIds: ["disc-adult-development"], competencySlugs: ["resilience", "recovery"], sortOrder: 8 }),
  dept({ id: "dept-focus-attention", pillarId: "build_yourself", slug: "focus-attention", name: "Focus & Attention", purpose: "Sustain attention on meaningful work.", knowledgeSourceIds: ["src-ef-research"], schoolOfThoughtIds: ["school-adhd-friendly"], researchDisciplineIds: ["disc-neuroscience", "disc-executive-function-science"], competencySlugs: ["focus"], sortOrder: 9 }),
  dept({ id: "dept-energy-management", pillarId: "build_yourself", slug: "energy-management", name: "Energy Management", purpose: "Match work to energy for decades of building.", knowledgeSourceIds: ["src-mindset-research"], schoolOfThoughtIds: ["school-growth-mindset"], researchDisciplineIds: ["disc-behavioral-psychology"], competencySlugs: ["energy-management"], sortOrder: 10 }),
  dept({ id: "dept-communication", pillarId: "build_yourself", slug: "communication", name: "Communication", purpose: "Communicate with clarity, listening, and influence.", knowledgeSourceIds: ["src-communication-craft"], schoolOfThoughtIds: ["school-coaching-partnership"], researchDisciplineIds: ["disc-communication-theory"], competencySlugs: ["communication", "listening", "boundaries", "negotiation", "networking"], sortOrder: 11 }),
  dept({ id: "dept-personal-leadership", pillarId: "build_yourself", slug: "personal-leadership", name: "Personal Leadership", purpose: "Lead yourself with values and purpose.", knowledgeSourceIds: ["src-leadership-canon"], schoolOfThoughtIds: ["school-servant-leadership"], researchDisciplineIds: ["disc-leadership-studies"], competencySlugs: ["personal-leadership", "influence", "purpose"], sortOrder: 12 }),
  // Pillar II — Build Your Business
  dept({ id: "dept-business-foundations", pillarId: "build_your_business", slug: "business-foundations", name: "Business Foundations", purpose: "Establish models, mission, and direction.", knowledgeSourceIds: ["src-strategic-canons"], schoolOfThoughtIds: ["school-positioning"], researchDisciplineIds: ["disc-entrepreneurship-studies", "disc-strategic-management"], competencySlugs: ["business-foundations", "business-planning", "mission-vision"], sortOrder: 1 }),
  dept({ id: "dept-strategy", pillarId: "build_your_business", slug: "strategy", name: "Strategy", purpose: "Choose where to play and how to win.", knowledgeSourceIds: ["src-strategic-canons", "src-offer-design"], schoolOfThoughtIds: ["school-positioning", "school-offer-ethics"], researchDisciplineIds: ["disc-strategic-management"], competencySlugs: ["business-strategy", "offers"], sortOrder: 2 }),
  dept({ id: "dept-marketing", pillarId: "build_your_business", slug: "marketing", name: "Marketing", purpose: "Reach, message, and grow demand ethically.", knowledgeSourceIds: ["src-pricing-traditions", "src-brand-lineages"], schoolOfThoughtIds: ["school-value-pricing", "school-positioning"], researchDisciplineIds: ["disc-marketing-science", "disc-behavioral-economics"], competencySlugs: ["marketing", "pricing", "messaging", "positioning", "copywriting", "storytelling"], sortOrder: 3 }),
  dept({ id: "dept-branding", pillarId: "build_your_business", slug: "branding", name: "Branding", purpose: "Build trust through coherent brand identity.", knowledgeSourceIds: ["src-brand-lineages"], schoolOfThoughtIds: ["school-positioning"], researchDisciplineIds: ["disc-brand-strategy"], competencySlugs: ["branding"], sortOrder: 4 }),
  dept({ id: "dept-sales", pillarId: "build_your_business", slug: "sales", name: "Sales", purpose: "Convert interest through ethical persuasion.", knowledgeSourceIds: ["src-sales-traditions"], schoolOfThoughtIds: ["school-ethical-sales"], researchDisciplineIds: ["disc-sales-methodology"], competencySlugs: ["sales"], sortOrder: 5 }),
  dept({ id: "dept-customer-experience", pillarId: "build_your_business", slug: "customer-experience", name: "Customer Experience", purpose: "Design journeys that retain and delight.", knowledgeSourceIds: ["src-customer-experience"], schoolOfThoughtIds: ["school-customer-centricity"], researchDisciplineIds: ["disc-design-thinking", "disc-marketing-science"], competencySlugs: ["customer-experience"], sortOrder: 6 }),
  dept({ id: "dept-finance", pillarId: "build_your_business", slug: "finance", name: "Finance", purpose: "Understand cash, profit, and forecasting.", knowledgeSourceIds: ["src-finance-foundations"], schoolOfThoughtIds: ["school-founder-finance"], researchDisciplineIds: ["disc-financial-management"], competencySlugs: ["finance", "cash-flow", "profitability"], sortOrder: 7 }),
  dept({ id: "dept-operations", pillarId: "build_your_business", slug: "operations", name: "Operations", purpose: "Deliver consistently as you grow.", knowledgeSourceIds: ["src-operations-canon"], schoolOfThoughtIds: ["school-lean-operations"], researchDisciplineIds: ["disc-operations-research"], competencySlugs: ["operations", "hiring", "delegation"], sortOrder: 8 }),
  dept({ id: "dept-systems", pillarId: "build_your_business", slug: "systems", name: "Systems", purpose: "Document and automate what repeats.", knowledgeSourceIds: ["src-systems-automation"], schoolOfThoughtIds: ["school-systems-thinking"], researchDisciplineIds: ["disc-systems-theory", "disc-operations-research"], competencySlugs: ["systems", "automation"], sortOrder: 9 }),
  dept({ id: "dept-project-management", pillarId: "build_your_business", slug: "project-management", name: "Project Management", purpose: "Finish meaningful work on realistic timelines.", knowledgeSourceIds: ["src-operations-canon", "src-ef-research"], schoolOfThoughtIds: ["school-lean-operations", "school-adhd-friendly"], researchDisciplineIds: ["disc-operations-research"], competencySlugs: ["project-management", "planning"], sortOrder: 10 }),
  dept({ id: "dept-ai-for-business", pillarId: "build_your_business", slug: "ai-for-business", name: "AI for Business", purpose: "Apply AI practically and ethically.", knowledgeSourceIds: ["src-ai-practice"], schoolOfThoughtIds: ["school-practical-ai"], researchDisciplineIds: ["disc-information-science", "disc-ethics"], competencySlugs: ["ai-for-business"], sortOrder: 11 }),
  dept({ id: "dept-business-growth", pillarId: "build_your_business", slug: "business-growth", name: "Business Growth", purpose: "Scale without breaking trust or quality.", knowledgeSourceIds: ["src-strategic-canons"], schoolOfThoughtIds: ["school-positioning"], researchDisciplineIds: ["disc-strategic-management", "disc-entrepreneurship-studies"], competencySlugs: ["business-growth", "scaling", "partnerships"], sortOrder: 12 }),
  dept({ id: "dept-legal-risk-awareness", pillarId: "build_your_business", slug: "legal-risk-awareness", name: "Legal & Risk Awareness", purpose: "High-level awareness — not legal advice.", knowledgeSourceIds: ["src-strategic-canons"], schoolOfThoughtIds: ["school-offer-ethics"], researchDisciplineIds: ["disc-ethics"], competencySlugs: ["legal-risk-awareness"], sortOrder: 13 }),
  // Pillar III — Build Your Thinking
  dept({ id: "dept-critical-thinking", pillarId: "build_your_thinking", slug: "critical-thinking", name: "Critical Thinking", purpose: "Think clearly and spot weak reasoning.", knowledgeSourceIds: ["src-critical-thinking"], schoolOfThoughtIds: ["school-clear-thinking"], researchDisciplineIds: ["disc-decision-science", "disc-information-science"], competencySlugs: ["critical-thinking", "pattern-recognition"], sortOrder: 1 }),
  dept({ id: "dept-strategic-thinking", pillarId: "build_your_thinking", slug: "strategic-thinking", name: "Strategic Thinking", purpose: "See second-order effects and scenarios.", knowledgeSourceIds: ["src-strategic-canons"], schoolOfThoughtIds: ["school-clear-thinking"], researchDisciplineIds: ["disc-strategic-management", "disc-systems-theory"], competencySlugs: ["strategic-thinking", "mental-models"], sortOrder: 2 }),
  dept({ id: "dept-systems-thinking", pillarId: "build_your_thinking", slug: "systems-thinking", name: "Systems Thinking", purpose: "Understand feedback loops and leverage.", knowledgeSourceIds: ["src-systems-automation"], schoolOfThoughtIds: ["school-systems-thinking"], researchDisciplineIds: ["disc-systems-theory"], competencySlugs: ["systems-thinking"], sortOrder: 3 }),
  dept({ id: "dept-creative-thinking", pillarId: "build_your_thinking", slug: "creative-thinking", name: "Creative Thinking", purpose: "Generate options before committing.", knowledgeSourceIds: ["src-creative-methods"], schoolOfThoughtIds: ["school-creative-entrepreneurship"], researchDisciplineIds: ["disc-design-thinking", "disc-innovation-studies"], competencySlugs: ["creative-thinking", "visual-thinking"], sortOrder: 4 }),
  dept({ id: "dept-decision-making", pillarId: "build_your_thinking", slug: "decision-making", name: "Decision Making", purpose: "Improve the quality of the next decision.", knowledgeSourceIds: ["src-critical-thinking"], schoolOfThoughtIds: ["school-clear-thinking"], researchDisciplineIds: ["disc-decision-science"], competencySlugs: ["decision-making"], sortOrder: 5 }),
  dept({ id: "dept-opportunity-recognition", pillarId: "build_your_thinking", slug: "opportunity-recognition", name: "Opportunity Recognition", purpose: "Spot viable opportunities early.", knowledgeSourceIds: ["src-innovation-practice"], schoolOfThoughtIds: ["school-experimentation"], researchDisciplineIds: ["disc-entrepreneurship-studies", "disc-innovation-studies"], competencySlugs: ["opportunity-recognition"], sortOrder: 6 }),
  dept({ id: "dept-problem-solving", pillarId: "build_your_thinking", slug: "problem-solving", name: "Problem Solving", purpose: "Solve root causes, not symptoms.", knowledgeSourceIds: ["src-critical-thinking", "src-creative-methods"], schoolOfThoughtIds: ["school-clear-thinking"], researchDisciplineIds: ["disc-design-thinking"], competencySlugs: ["problem-solving"], sortOrder: 7 }),
  dept({ id: "dept-learning-how-to-learn", pillarId: "build_your_thinking", slug: "learning-how-to-learn", name: "Learning How to Learn", purpose: "Acquire skills faster and retain them.", knowledgeSourceIds: ["src-learning-traditions"], schoolOfThoughtIds: ["school-capability-learning"], researchDisciplineIds: ["disc-learning-science"], competencySlugs: ["learning-science"], sortOrder: 8 }),
  dept({ id: "dept-research", pillarId: "build_your_thinking", slug: "research", name: "Research", purpose: "Gather evidence before big bets.", knowledgeSourceIds: ["src-critical-thinking"], schoolOfThoughtIds: ["school-clear-thinking"], researchDisciplineIds: ["disc-information-science"], competencySlugs: ["research"], sortOrder: 9 }),
  dept({ id: "dept-innovation", pillarId: "build_your_thinking", slug: "innovation", name: "Innovation", purpose: "Experiment and iterate in the market.", knowledgeSourceIds: ["src-innovation-practice"], schoolOfThoughtIds: ["school-experimentation"], researchDisciplineIds: ["disc-innovation-studies"], competencySlugs: ["innovation"], sortOrder: 10 }),
  // Pillar IV — Build Your Legacy
  dept({ id: "dept-leadership", pillarId: "build_your_legacy", slug: "leadership", name: "Leadership", purpose: "Develop people and culture.", knowledgeSourceIds: ["src-leadership-canon"], schoolOfThoughtIds: ["school-servant-leadership"], researchDisciplineIds: ["disc-leadership-studies", "disc-organizational-psychology"], competencySlugs: ["leadership", "culture"], sortOrder: 1 }),
  dept({ id: "dept-coaching", pillarId: "build_your_legacy", slug: "coaching", name: "Coaching", purpose: "Coach others toward their capability.", knowledgeSourceIds: ["src-coaching-lineages"], schoolOfThoughtIds: ["school-coaching-partnership"], researchDisciplineIds: ["disc-coaching-methodology"], competencySlugs: ["coaching", "consulting"], sortOrder: 2 }),
  dept({ id: "dept-mentoring", pillarId: "build_your_legacy", slug: "mentoring", name: "Mentoring", purpose: "Mentor with generosity and boundaries.", knowledgeSourceIds: ["src-coaching-lineages"], schoolOfThoughtIds: ["school-coaching-partnership"], researchDisciplineIds: ["disc-adult-development"], competencySlugs: ["mentoring"], sortOrder: 3 }),
  dept({ id: "dept-speaking", pillarId: "build_your_legacy", slug: "speaking", name: "Speaking", purpose: "Speak with calm authority.", knowledgeSourceIds: ["src-communication-craft", "src-content-craft"], schoolOfThoughtIds: ["school-teaching-authority"], researchDisciplineIds: ["disc-communication-theory"], competencySlugs: ["public-speaking"], sortOrder: 4 }),
  dept({ id: "dept-writing", pillarId: "build_your_legacy", slug: "writing", name: "Writing", purpose: "Write to clarify thinking and build trust.", knowledgeSourceIds: ["src-content-craft"], schoolOfThoughtIds: ["school-teaching-authority"], researchDisciplineIds: ["disc-communication-theory"], competencySlugs: ["writing", "content-creation"], sortOrder: 5 }),
  dept({ id: "dept-course-creation", pillarId: "build_your_legacy", slug: "course-creation", name: "Course Creation", purpose: "Design learning that changes capability.", knowledgeSourceIds: ["src-learning-traditions", "src-content-craft"], schoolOfThoughtIds: ["school-capability-learning", "school-teaching-authority"], researchDisciplineIds: ["disc-learning-science"], competencySlugs: ["course-creation", "teaching"], sortOrder: 6 }),
  dept({ id: "dept-community-building", pillarId: "build_your_legacy", slug: "community-building", name: "Community Building", purpose: "Build communities with safety and purpose.", knowledgeSourceIds: ["src-leadership-canon"], schoolOfThoughtIds: ["school-servant-leadership"], researchDisciplineIds: ["disc-organizational-psychology"], competencySlugs: ["community-building"], sortOrder: 7 }),
  dept({ id: "dept-thought-leadership", pillarId: "build_your_legacy", slug: "thought-leadership", name: "Thought Leadership", purpose: "Earn authority through service.", knowledgeSourceIds: ["src-content-craft"], schoolOfThoughtIds: ["school-teaching-authority"], researchDisciplineIds: ["disc-communication-theory"], competencySlugs: ["thought-leadership", "authority"], sortOrder: 8 }),
  dept({ id: "dept-legacy-building", pillarId: "build_your_legacy", slug: "legacy-building", name: "Legacy Building", purpose: "Build impact that outlasts quarterly metrics.", knowledgeSourceIds: ["src-legacy-impact"], schoolOfThoughtIds: ["school-legacy-building"], researchDisciplineIds: ["disc-adult-development", "disc-leadership-studies"], competencySlugs: ["legacy-building", "giving-back", "purpose"], sortOrder: 9 }),
];

export function getDepartmentCouncilSeed(
  departmentId: string,
): Omit<BrainDepartment, "drawerIds" | "topicIds"> | null {
  return DEPARTMENT_COUNCIL_SEEDS.find((d) => d.id === departmentId) ?? null;
}
