/**
 * Schools of Thought — synthesis lenses for Spark's unified teaching voice.
 * INTERNAL — members experience Spark, not a panel of experts.
 */

import type { SchoolOfThought } from "../types";

export const SCHOOLS_OF_THOUGHT: SchoolOfThought[] = [
  { id: "school-value-pricing", slug: "value-pricing", title: "Value-based pricing school", description: "Price reflects delivered value and buyer psychology.", synthesisKey: "council.school.value_pricing", sourceIds: ["src-pricing-traditions"], disciplineIds: ["disc-economics", "disc-behavioral-economics"], visibility: "internal" },
  { id: "school-ethical-sales", slug: "ethical-sales", title: "Ethical persuasion school", description: "Sales as discovery and service.", synthesisKey: "council.school.ethical_sales", sourceIds: ["src-sales-traditions"], disciplineIds: ["disc-sales-methodology"], visibility: "internal" },
  { id: "school-positioning", slug: "positioning", title: "Strategic positioning school", description: "Own a clear place in the customer's mind.", synthesisKey: "council.school.positioning", sourceIds: ["src-strategic-canons", "src-brand-lineages"], disciplineIds: ["disc-strategic-management", "disc-brand-strategy"], visibility: "internal" },
  { id: "school-customer-centricity", slug: "customer-centricity", title: "Customer-centricity school", description: "Design around real customer journeys.", synthesisKey: "council.school.customer_centric", sourceIds: ["src-customer-experience"], disciplineIds: ["disc-design-thinking"], visibility: "internal" },
  { id: "school-lean-operations", slug: "lean-operations", title: "Lean operations school", description: "Remove friction; improve throughput.", synthesisKey: "council.school.lean_ops", sourceIds: ["src-operations-canon"], disciplineIds: ["disc-operations-research"], visibility: "internal" },
  { id: "school-founder-finance", slug: "founder-finance", title: "Founder finance school", description: "Cash clarity over accounting complexity.", synthesisKey: "council.school.founder_finance", sourceIds: ["src-finance-foundations"], disciplineIds: ["disc-financial-management"], visibility: "internal" },
  { id: "school-systems-thinking", slug: "systems-thinking", title: "Business systems school", description: "Business as interconnected systems.", synthesisKey: "council.school.systems", sourceIds: ["src-systems-automation"], disciplineIds: ["disc-systems-theory"], visibility: "internal" },
  { id: "school-practical-ai", slug: "practical-ai", title: "Practical AI school", description: "AI augments judgment; member stays hero.", synthesisKey: "council.school.practical_ai", sourceIds: ["src-ai-practice"], disciplineIds: ["disc-ethics", "disc-information-science"], visibility: "internal" },
  { id: "school-adhd-friendly", slug: "adhd-friendly", title: "ADHD-friendly entrepreneurship school", description: "Design work for real brains.", synthesisKey: "council.school.adhd", sourceIds: ["src-ef-research"], disciplineIds: ["disc-executive-function-science", "disc-neuroscience"], visibility: "internal" },
  { id: "school-capability-learning", slug: "capability-learning", title: "Capability learning school", description: "Growth through practice, not information hoarding.", synthesisKey: "council.school.capability", sourceIds: ["src-learning-traditions"], disciplineIds: ["disc-learning-science"], visibility: "internal" },
  { id: "school-growth-mindset", slug: "growth-mindset", title: "Entrepreneurial growth school", description: "Identity and resilience through iteration.", synthesisKey: "council.school.growth_mindset", sourceIds: ["src-mindset-research"], disciplineIds: ["disc-adult-development"], visibility: "internal" },
  { id: "school-coaching-partnership", slug: "coaching-partnership", title: "Coaching partnership school", description: "Member owns decisions; guide asks and supports.", synthesisKey: "council.school.coaching", sourceIds: ["src-coaching-lineages"], disciplineIds: ["disc-coaching-methodology"], visibility: "internal" },
  { id: "school-servant-leadership", slug: "servant-leadership", title: "Steward leadership school", description: "Lead by developing others.", synthesisKey: "council.school.leadership", sourceIds: ["src-leadership-canon"], disciplineIds: ["disc-leadership-studies"], visibility: "internal" },
  { id: "school-clear-thinking", slug: "clear-thinking", title: "Clear thinking school", description: "Slow down to decide well.", synthesisKey: "council.school.clear_thinking", sourceIds: ["src-critical-thinking"], disciplineIds: ["disc-decision-science"], visibility: "internal" },
  { id: "school-creative-entrepreneurship", slug: "creative-entrepreneurship", title: "Creative entrepreneurship school", description: "Constraints spark better options.", synthesisKey: "council.school.creative", sourceIds: ["src-creative-methods"], disciplineIds: ["disc-design-thinking"], visibility: "internal" },
  { id: "school-experimentation", slug: "experimentation", title: "Experimentation school", description: "Test small; learn fast; decide with evidence.", synthesisKey: "council.school.experimentation", sourceIds: ["src-innovation-practice"], disciplineIds: ["disc-innovation-studies"], visibility: "internal" },
  { id: "school-habit-architecture", slug: "habit-architecture", title: "Habit architecture school", description: "Environment beats willpower.", synthesisKey: "council.school.habits", sourceIds: ["src-habit-science"], disciplineIds: ["disc-habit-formation"], visibility: "internal" },
  { id: "school-legacy-building", slug: "legacy-building", title: "Legacy building school", description: "Success includes what outlasts you.", synthesisKey: "council.school.legacy", sourceIds: ["src-legacy-impact"], disciplineIds: ["disc-adult-development"], visibility: "internal" },
  { id: "school-teaching-authority", slug: "teaching-authority", title: "Teaching authority school", description: "Authority through generous teaching.", synthesisKey: "council.school.authority", sourceIds: ["src-content-craft"], disciplineIds: ["disc-learning-science"], visibility: "internal" },
  { id: "school-offer-ethics", slug: "offer-ethics", title: "Ethical offer school", description: "Offers must deliver promised transformation.", synthesisKey: "council.school.offer_ethics", sourceIds: ["src-offer-design"], disciplineIds: ["disc-entrepreneurship-studies", "disc-ethics"], visibility: "internal" },
];
