export {
  runCoreMemory,
  buildMemoryProfile,
  confirmMemoryUpdate,
  deleteMemory,
  editMemory,
  exportMemory,
  getPendingProposal,
  proposeMemoryWrite,
  writeMemoryDirect,
  buildRecallDecision,
  contextBundleFromRecall,
  applyMemoryAging,
  detectConflict,
  detectConflicts,
  clearMemoryStore,
  clearPendingProposals,
} from "./memoryEngine";
export type {
  CoreMemoryInput,
  CoreMemoryResult,
  MemoryRecord,
  MemoryType,
  MemoryKey,
  MemoryConfidence,
  MemoryWriteProposal,
  MemoryConflict,
  MemoryRecallDecision,
  UserVisibleMemoryProfile,
  MemoryExport,
} from "./types";
