/**
 * Event Plan — domain Blueprint *definitions* only.
 * Registered through the Universal Blueprint registry (no private runtime).
 */

import type { BlueprintDefinition, BlueprintGroup } from "../../blueprints/types";
import { ALL_BLUEPRINT_DEPTH_MODES } from "../../blueprints/types";
import { EVENT_PLAN_WORK_TYPE_ID } from "@/lib/workTypeSchema/schemas/eventPlanMap";
import { EVENT_PLAN_MAP_GROUPS } from "./eventPlanMapGroups";

const EVENT_WORK = [EVENT_PLAN_WORK_TYPE_ID] as const;

type EventBlueprintSeed = Omit<
  BlueprintDefinition,
  "compatibleWorkTypeIds" | "supportedDepthModes" | "category"
> & {
  category?: BlueprintDefinition["category"];
};

/** Keep Event map groups that still contain sections on this Blueprint. */
function groupsForSections(
  sectionIds: readonly string[],
): BlueprintGroup[] {
  const set = new Set(sectionIds);
  return EVENT_PLAN_MAP_GROUPS.map((g) => ({
    ...g,
    sectionIds: g.sectionIds.filter((id) => set.has(id)),
  })).filter((g) => g.sectionIds.length > 0);
}

function eventBlueprint(seed: EventBlueprintSeed): BlueprintDefinition {
  const sectionIds = seed.sections.map((s) => s.id);
  return {
    ...seed,
    category: seed.category ?? "spark",
    compatibleWorkTypeIds: EVENT_WORK,
    supportedDepthModes: ALL_BLUEPRINT_DEPTH_MODES,
    groups: seed.groups ?? groupsForSections(sectionIds),
  };
}

const SHARED_HIDDEN = {
  id: "system_work_meta",
  title: "System",
  role: "hidden_system" as const,
};

export const EVENT_BLUEPRINT_BUSINESS_LUNCHEON = eventBlueprint({
  blueprintId: "bp-event-business-luncheon",
  version: "1.0.0",
  title: "Business Luncheon",
  description:
    "Plan a professional midday gathering with hosting, catering, and follow-up.",
  intendedUse: "Client hospitality, networking lunches, and partner briefings.",
  complexity: "moderate",
  sections: [
    { id: "event_type", title: "Event Type", role: "required", defaultValue: "Business Luncheon" },
    { id: "purpose", title: "Purpose", role: "required" },
    { id: "outcomes", title: "Outcomes", role: "required" },
    { id: "audience", title: "Audience", role: "required" },
    { id: "format", title: "Format", role: "required", defaultValue: "In-person lunch" },
    { id: "dates", title: "Date and Time", role: "required" },
    { id: "venue", title: "Venue", role: "required" },
    { id: "budget", title: "Budget", role: "required" },
    { id: "hospitality", title: "Food and Hospitality", role: "required" },
    { id: "communications", title: "Communication Plan", role: "required" },
    {
      id: "sponsors",
      title: "Sponsors",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "has_sponsors" },
    },
    {
      id: "post_event_follow_up",
      title: "Follow-Up",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "measurement",
      title: "Evaluation",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    SHARED_HIDDEN,
  ],
  defaultValues: {
    event_type: "Business Luncheon",
    format: "In-person lunch",
  },
  adaptiveQuestions: [
    {
      id: "q_purpose",
      prompt: "What is the main reason for this luncheon?",
      lowerFrictionPrompt: "What's this lunch for, in one line?",
      sectionId: "purpose",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["purpose"],
      materialChangeNextStep: true,
    },
    {
      id: "q_guest_count",
      prompt: "About how many guests are you expecting?",
      lowerFrictionPrompt: "Rough guest count?",
      sectionId: "audience",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["guest_count", "audience"],
      materialChangeNextStep: true,
    },
    {
      id: "q_dietary",
      prompt: "Any dietary needs or hospitality constraints we should plan for?",
      sectionId: "hospitality",
      requiredInModes: ["guided_build", "complete_planning"],
      dependencies: ["q_guest_count"],
      postponable: true,
      materialChangeNextStep: false,
    },
    {
      id: "q_sponsors",
      prompt: "Will this luncheon have sponsors?",
      sectionId: "sponsors",
      requiredInModes: ["complete_planning"],
      knownContextKeys: ["has_sponsors"],
      postponable: true,
      materialChangeNextStep: true,
      inferFromContext: { key: "has_sponsors", asAnswer: "yes" },
    },
  ],
  suggestedTasks: [
    { id: "t_confirm_venue", title: "Confirm venue and room setup", sectionId: "venue" },
    { id: "t_menu", title: "Finalize menu and dietary accommodations", sectionId: "hospitality" },
    { id: "t_invites", title: "Send invitations", sectionId: "communications", depthModes: ["guided_build", "complete_planning"] },
    { id: "t_followups", title: "Schedule thank-you follow-ups", sectionId: "post_event_follow_up", depthModes: ["complete_planning"] },
  ],
  suggestedMilestones: [
    { id: "m_invites_out", title: "Invitations sent" },
    { id: "m_final_headcount", title: "Final headcount locked", depthModes: ["guided_build", "complete_planning"] },
    { id: "m_day_of", title: "Day-of run-of-show ready", depthModes: ["complete_planning"] },
  ],
  commonlyForgottenItems: [
    "Dietary restrictions list",
    "Place cards / seating plan",
    "AV for brief remarks",
    "Parking or arrival instructions",
    "Thank-you notes within 48 hours",
  ],
  riskPrompts: [
    "What if the headcount drops sharply after the catering guarantee?",
    "Is there a backup host if the primary speaker cancels?",
  ],
  researchPrompts: [
    "Compare two nearby venues for noise level at lunch hour",
    "Typical per-person catering cost for this guest count",
  ],
  deliverables: [
    "Luncheon brief",
    "Invitation copy",
    "Day-of checklist",
    "Follow-up message draft",
  ],
  chamberRoutingRecommendations: ["events", "hospitality"],
  boardReviewRecommendations: ["Budget approval before catering deposit"],
  projectBridgeRecommendations: ["Bridge luncheon as a Project when invites go out"],
  cartographyRelationshipRecommendations: [
    { relationship: "supports", note: "Link to related client or partnership work" },
  ],
  completionCriteria: [
    "Purpose and outcomes clear",
    "Venue and date confirmed",
    "Hospitality plan covers dietary needs",
    "Follow-up owner assigned (Guided+)",
  ],
  certificationRules: ["event.foundation", "event.map", "event.focus"],
  domainExtensions: {
    peopleAndRoles: ["Host", "Emcee", "Catering contact", "Registration greeter"],
    budgetConsiderations: ["Venue minimum", "Per-person catering", "Gratuity", "Printed materials"],
    timelineRecommendations: [
      "4 weeks: hold venue",
      "2 weeks: invitations",
      "72 hours: final headcount",
      "Same day: follow-up queue",
    ],
    communications: ["Save-the-date", "Formal invite", "Day-before reminder", "Thank-you"],
    followUpRequirements: ["Thank-you within 48 hours", "Capture introductions made"],
  },
});

export const EVENT_BLUEPRINT_ONLINE_WORKSHOP = eventBlueprint({
  blueprintId: "bp-event-online-workshop",
  version: "1.0.0",
  title: "Online Workshop",
  description: "Design a live virtual workshop with platform, engagement, and follow-up.",
  intendedUse: "Remote teaching, masterclasses, and live cohort sessions.",
  complexity: "moderate",
  sections: [
    { id: "event_type", title: "Event Type", role: "required", defaultValue: "Online Workshop" },
    { id: "purpose", title: "Purpose", role: "required" },
    { id: "outcomes", title: "Outcomes", role: "required" },
    { id: "audience", title: "Audience", role: "required" },
    { id: "format", title: "Format", role: "required", defaultValue: "Online / live" },
    { id: "dates", title: "Date and Time", role: "required" },
    { id: "venue", title: "Online Platform", role: "required" },
    { id: "agenda", title: "Program and Agenda", role: "required" },
    { id: "technology", title: "Equipment and Technology", role: "required" },
    { id: "registration", title: "Registration", role: "required" },
    { id: "marketing", title: "Marketing", role: "optional", condition: { kind: "depth_at_least", mode: "guided_build" } },
    {
      id: "recording_plan",
      title: "Recording and Replay",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "will_record" },
    },
    { id: "post_event_follow_up", title: "Follow-Up", role: "optional", condition: { kind: "depth_at_least", mode: "guided_build" } },
    { id: "measurement", title: "Evaluation", role: "optional", condition: { kind: "depth_at_least", mode: "complete_planning" } },
    SHARED_HIDDEN,
  ],
  adaptiveQuestions: [
    {
      id: "q_purpose",
      prompt: "What should participants be able to do after this workshop?",
      lowerFrictionPrompt: "What should they walk away able to do?",
      sectionId: "outcomes",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["outcomes", "purpose"],
      materialChangeNextStep: true,
    },
    {
      id: "q_platform",
      prompt: "Which platform will you use (Zoom, Meet, etc.)?",
      sectionId: "venue",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["platform", "venue"],
      materialChangeNextStep: true,
    },
    {
      id: "q_record",
      prompt: "Will you record the session for replay?",
      sectionId: "recording_plan",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["will_record"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_tech_rehearsal",
      prompt: "When will you run a tech rehearsal?",
      sectionId: "technology",
      requiredInModes: ["complete_planning"],
      dependencies: ["q_platform"],
      postponable: true,
      materialChangeNextStep: false,
    },
  ],
  suggestedTasks: [
    { id: "t_platform", title: "Create workshop meeting link", sectionId: "venue" },
    { id: "t_agenda", title: "Draft timed agenda with breaks", sectionId: "agenda" },
    { id: "t_rehearsal", title: "Schedule tech rehearsal", sectionId: "technology", depthModes: ["complete_planning"] },
  ],
  suggestedMilestones: [
    { id: "m_reg_open", title: "Registration open" },
    { id: "m_rehearsal_done", title: "Tech rehearsal complete", depthModes: ["complete_planning"] },
  ],
  commonlyForgottenItems: [
    "Backup host account",
    "Waiting room / admit settings",
    "Captioning or accessibility options",
    "Breakout room plan",
    "Replay delivery permissions",
  ],
  riskPrompts: [
    "What if the host loses connection mid-session?",
    "How will you handle late joiners without derailing the agenda?",
  ],
  researchPrompts: [
    "Best engagement tools for this workshop length",
    "Accessibility checklist for the chosen platform",
  ],
  deliverables: ["Workshop outline", "Slide / workbook stub", "Registration page copy", "Follow-up email"],
  chamberRoutingRecommendations: ["events", "education"],
  boardReviewRecommendations: ["Confirm recording and privacy policy before marketing"],
  projectBridgeRecommendations: ["Bridge when registration opens"],
  cartographyRelationshipRecommendations: [
    { relationship: "related_to", note: "Link to curriculum or offer work" },
  ],
  completionCriteria: [
    "Outcomes defined",
    "Platform and time set",
    "Agenda timed",
    "Registration path ready",
  ],
  certificationRules: ["event.foundation", "event.map", "event.focus"],
  domainExtensions: {
    peopleAndRoles: ["Host", "Co-facilitator", "Tech support", "Chat moderator"],
    budgetConsiderations: ["Platform plan limits", "Paid ads", "Replay hosting"],
    timelineRecommendations: ["2 weeks: registration", "1 week: reminder sequence", "Day-before: tech check"],
    communications: ["Announcement", "Confirmation", "Reminder", "Replay + resources"],
    followUpRequirements: ["Send resources within 24 hours", "Collect feedback survey"],
  },
});

export const EVENT_BLUEPRINT_ONE_DAY_WORKSHOP = eventBlueprint({
  blueprintId: "bp-event-one-day-workshop",
  version: "1.0.0",
  title: "One-Day Workshop",
  description: "Plan a full-day in-person or hybrid workshop with agenda, logistics, and delivery.",
  intendedUse: "Intensive skill days, offsites, and facilitated working sessions.",
  complexity: "complex",
  sections: [
    { id: "event_type", title: "Event Type", role: "required", defaultValue: "One-Day Workshop" },
    { id: "purpose", title: "Purpose", role: "required" },
    { id: "outcomes", title: "Outcomes", role: "required" },
    { id: "audience", title: "Audience", role: "required" },
    { id: "format", title: "Format", role: "required" },
    { id: "dates", title: "Date and Time", role: "required" },
    { id: "venue", title: "Venue or Online Platform", role: "required" },
    { id: "budget", title: "Budget", role: "required" },
    { id: "agenda", title: "Program and Agenda", role: "required" },
    { id: "speakers", title: "Speakers and Facilitators", role: "required" },
    {
      id: "hospitality",
      title: "Food and Hospitality",
      role: "conditional",
      condition: {
        kind: "or",
        conditions: [
          { kind: "known_context_equals", key: "format", value: "in_person" },
          { kind: "question_equals", questionId: "q_format", value: "in_person" },
        ],
      },
    },
    { id: "supplies", title: "Supplies", role: "optional", condition: { kind: "depth_at_least", mode: "guided_build" } },
    { id: "run_of_show", title: "Run of Show", role: "optional", condition: { kind: "depth_at_least", mode: "complete_planning" } },
    { id: "post_event_follow_up", title: "Follow-Up", role: "optional", condition: { kind: "depth_at_least", mode: "guided_build" } },
    SHARED_HIDDEN,
  ],
  adaptiveQuestions: [
    {
      id: "q_purpose",
      prompt: "What transformation should this day create?",
      lowerFrictionPrompt: "What should be different by the end of the day?",
      sectionId: "purpose",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["purpose"],
      materialChangeNextStep: true,
    },
    {
      id: "q_format",
      prompt: "Is this in person, online, or hybrid?",
      sectionId: "format",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["format"],
      materialChangeNextStep: true,
    },
    {
      id: "q_facilitator",
      prompt: "Who is facilitating, and do they need a co-facilitator?",
      sectionId: "speakers",
      requiredInModes: ["guided_build", "complete_planning"],
      dependencies: ["q_purpose"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_materials",
      prompt: "What materials must be printed or shipped beforehand?",
      sectionId: "supplies",
      requiredInModes: ["complete_planning"],
      postponable: true,
      materialChangeNextStep: false,
    },
  ],
  suggestedTasks: [
    { id: "t_agenda_blocks", title: "Block the day into timed segments", sectionId: "agenda" },
    { id: "t_venue", title: "Confirm venue and room layout", sectionId: "venue" },
    { id: "t_ros", title: "Draft run of show", sectionId: "run_of_show", depthModes: ["complete_planning"] },
  ],
  suggestedMilestones: [
    { id: "m_agenda_locked", title: "Agenda locked" },
    { id: "m_materials_ready", title: "Materials ready", depthModes: ["complete_planning"] },
  ],
  commonlyForgottenItems: [
    "Break and lunch timing",
    "Name badges",
    "Parking and signage",
    "Backup facilitator",
    "End-of-day energy / closing ritual",
  ],
  riskPrompts: [
    "What if the room is too small for the final headcount?",
    "Where will you cut if the morning runs long?",
  ],
  researchPrompts: [
    "Facilitation patterns for full-day energy management",
    "Comparable workshop agendas for this outcome",
  ],
  deliverables: ["Day agenda", "Facilitator brief", "Participant prep note", "Follow-up packet"],
  chamberRoutingRecommendations: ["events", "education"],
  boardReviewRecommendations: ["Approve budget before venue deposit"],
  projectBridgeRecommendations: ["Bridge when first deposit is paid"],
  cartographyRelationshipRecommendations: [
    { relationship: "implements", note: "May implement a training or offer goal" },
  ],
  completionCriteria: [
    "Outcomes and agenda aligned",
    "Format and venue set",
    "Facilitator confirmed",
    "Follow-up plan exists (Guided+)",
  ],
  certificationRules: ["event.foundation", "event.map", "event.focus"],
  domainExtensions: {
    peopleAndRoles: ["Lead facilitator", "Assistant", "Logistics lead", "Registration"],
    budgetConsiderations: ["Venue", "Catering", "Materials", "Facilitator fee"],
    timelineRecommendations: ["6 weeks: hold date", "3 weeks: materials", "1 week: final roster"],
    communications: ["Invite", "Prep email", "Day-of logistics", "Thank-you + next step"],
    followUpRequirements: ["Send workbook/resources", "Collect NPS or qualitative feedback"],
  },
});

export const EVENT_BLUEPRINT_THREE_DAY_RETREAT = eventBlueprint({
  blueprintId: "bp-event-three-day-retreat",
  version: "1.0.0",
  title: "Three-Day Retreat",
  description: "Plan an immersive multi-day retreat with lodging, program, and care.",
  intendedUse: "Leadership retreats, immersive intensives, and restorative gatherings.",
  complexity: "complex",
  sections: [
    { id: "event_type", title: "Event Type", role: "required", defaultValue: "Three-Day Retreat" },
    { id: "purpose", title: "Purpose", role: "required" },
    { id: "outcomes", title: "Outcomes", role: "required" },
    { id: "audience", title: "Audience", role: "required" },
    { id: "format", title: "Format", role: "required", defaultValue: "In-person retreat" },
    { id: "dates", title: "Date and Time", role: "required" },
    { id: "venue", title: "Venue / Lodging", role: "required" },
    { id: "budget", title: "Budget", role: "required" },
    { id: "agenda", title: "Program and Agenda", role: "required" },
    { id: "hospitality", title: "Food and Hospitality", role: "required" },
    { id: "staff", title: "Team", role: "required" },
    { id: "safety", title: "Safety", role: "optional", condition: { kind: "depth_at_least", mode: "guided_build" } },
    { id: "contingencies", title: "Risk and Contingencies", role: "optional", condition: { kind: "depth_at_least", mode: "complete_planning" } },
    {
      id: "volunteers",
      title: "Volunteers and Team",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "needs_volunteers" },
    },
    { id: "post_event_follow_up", title: "Follow-Up", role: "optional", condition: { kind: "depth_at_least", mode: "guided_build" } },
    SHARED_HIDDEN,
  ],
  adaptiveQuestions: [
    {
      id: "q_purpose",
      prompt: "What is the heart of this retreat for participants?",
      lowerFrictionPrompt: "What's the heart of this retreat?",
      sectionId: "purpose",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["purpose"],
      materialChangeNextStep: true,
    },
    {
      id: "q_lodging",
      prompt: "Where will people sleep, and who books lodging?",
      sectionId: "venue",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["venue", "lodging"],
      materialChangeNextStep: true,
    },
    {
      id: "q_care",
      prompt: "What care, accessibility, or safety needs should shape the program?",
      sectionId: "safety",
      requiredInModes: ["guided_build", "complete_planning"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_volunteers",
      prompt: "Do you need volunteers beyond the core team?",
      sectionId: "volunteers",
      requiredInModes: ["complete_planning"],
      knownContextKeys: ["needs_volunteers"],
      postponable: true,
      materialChangeNextStep: true,
    },
  ],
  suggestedTasks: [
    { id: "t_hold_venue", title: "Hold lodging and meeting spaces", sectionId: "venue" },
    { id: "t_day_themes", title: "Name each day's theme", sectionId: "agenda" },
    { id: "t_safety", title: "Draft safety and emergency contacts", sectionId: "safety", depthModes: ["complete_planning"] },
  ],
  suggestedMilestones: [
    { id: "m_deposit", title: "Venue deposit paid" },
    { id: "m_roster", title: "Final roster locked", depthModes: ["guided_build", "complete_planning"] },
    { id: "m_pack_list", title: "Packing list sent", depthModes: ["complete_planning"] },
  ],
  commonlyForgottenItems: [
    "Quiet / rest options between sessions",
    "Dietary list per meal",
    "Travel day buffers",
    "Emergency contacts",
    "Integration / re-entry support after day three",
  ],
  riskPrompts: [
    "What is the cancellation and weather plan?",
    "Who holds medical / emergency information on-site?",
  ],
  researchPrompts: [
    "Retreat venue accessibility audit",
    "Typical staffing ratios for this group size",
  ],
  deliverables: ["Retreat overview", "Three-day agenda", "Packing list", "Care & safety brief", "Follow-up integration plan"],
  chamberRoutingRecommendations: ["events", "wellbeing"],
  boardReviewRecommendations: ["Board review of total budget and liability coverage"],
  projectBridgeRecommendations: ["Bridge as a Project at deposit"],
  cartographyRelationshipRecommendations: [
    { relationship: "part_of", note: "May sit under a larger leadership or offer program" },
  ],
  completionCriteria: [
    "Purpose and daily themes clear",
    "Lodging and meals planned",
    "Team roles assigned",
    "Safety plan present (Guided+)",
  ],
  certificationRules: ["event.foundation", "event.map", "event.focus", "event.continue"],
  domainExtensions: {
    peopleAndRoles: ["Retreat lead", "Care lead", "Logistics", "Facilitators", "On-call support"],
    budgetConsiderations: ["Lodging", "Meals", "Travel stipends", "Insurance", "Materials"],
    timelineRecommendations: ["12 weeks: venue", "6 weeks: invitations", "2 weeks: packing list", "1 week: final logistics"],
    communications: ["Invitation", "Prep packet", "Daily orientation notes", "Closing + integration"],
    followUpRequirements: ["Integration check-in within one week", "Photo / memory share with permission"],
  },
});

export const EVENT_BLUEPRINT_BOOK_SIGNING = eventBlueprint({
  blueprintId: "bp-event-book-signing",
  version: "1.0.0",
  title: "Book Signing",
  description: "Plan a book signing or launch appearance with inventory, flow, and promotion.",
  intendedUse: "Author appearances, bookstore events, and launch signings.",
  complexity: "simple",
  sections: [
    { id: "event_type", title: "Event Type", role: "required", defaultValue: "Book Signing" },
    { id: "purpose", title: "Purpose", role: "required" },
    { id: "audience", title: "Audience", role: "required" },
    { id: "dates", title: "Date and Time", role: "required" },
    { id: "venue", title: "Venue", role: "required" },
    { id: "marketing", title: "Marketing", role: "required" },
    { id: "swag", title: "Books and Materials", role: "required" },
    { id: "run_of_show", title: "Run of Show", role: "optional", condition: { kind: "depth_at_least", mode: "guided_build" } },
    {
      id: "sponsors",
      title: "Partners / Sponsors",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "has_partner" },
    },
    { id: "post_event_follow_up", title: "Follow-Up", role: "optional", condition: { kind: "depth_at_least", mode: "guided_build" } },
    SHARED_HIDDEN,
  ],
  adaptiveQuestions: [
    {
      id: "q_title",
      prompt: "Which book (or books) are you signing?",
      lowerFrictionPrompt: "Which book is this for?",
      sectionId: "purpose",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["book_title", "purpose"],
      materialChangeNextStep: true,
    },
    {
      id: "q_inventory",
      prompt: "How many copies will you bring, and who supplies them?",
      sectionId: "swag",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["inventory"],
      materialChangeNextStep: true,
    },
    {
      id: "q_partner",
      prompt: "Is a bookstore or partner hosting with you?",
      sectionId: "sponsors",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["has_partner"],
      postponable: true,
      materialChangeNextStep: true,
    },
  ],
  suggestedTasks: [
    { id: "t_inventory", title: "Confirm book inventory and pre-orders", sectionId: "swag" },
    { id: "t_promo", title: "Publish event listing", sectionId: "marketing" },
    { id: "t_table_flow", title: "Plan signing table flow", sectionId: "run_of_show", depthModes: ["guided_build", "complete_planning"] },
  ],
  suggestedMilestones: [
    { id: "m_listing_live", title: "Event listing live" },
    { id: "m_books_on_site", title: "Books confirmed on-site", depthModes: ["complete_planning"] },
  ],
  commonlyForgottenItems: [
    "Sharpie / pen kit",
    "Table sign with book title",
    "Payment / preorder pickup process",
    "Photo permission",
    "Spillover seating line management",
  ],
  riskPrompts: [
    "What if inventory sells out early?",
    "Who handles accessibility for the signing line?",
  ],
  researchPrompts: [
    "Comparable turnout for this venue and genre",
    "Local media / newsletter listing deadlines",
  ],
  deliverables: ["Event listing copy", "Inventory checklist", "Signing table run-of-show", "Thank-you / next-read note"],
  chamberRoutingRecommendations: ["events", "content"],
  boardReviewRecommendations: [],
  projectBridgeRecommendations: ["Bridge when listing goes live"],
  cartographyRelationshipRecommendations: [
    { relationship: "supports", note: "Supports book / content launch work" },
  ],
  completionCriteria: [
    "Book and date clear",
    "Venue confirmed",
    "Inventory plan set",
    "Promotion path started",
  ],
  certificationRules: ["event.foundation", "event.map"],
  domainExtensions: {
    peopleAndRoles: ["Author", "Host / bookseller", "Line helper", "Photographer (optional)"],
    budgetConsiderations: ["Venue fee", "Inventory", "Travel", "Promo boost"],
    timelineRecommendations: ["4 weeks: listing", "2 weeks: reminders", "Day-of: inventory check"],
    communications: ["Listing", "Social reminder", "Day-of story", "Thank-you"],
    followUpRequirements: ["Post event photos with permission", "Share purchase / review link"],
  },
});

/**
 * 126 — Networking Event Blueprint.
 * Spec ID `event.networking_event` (dotted form, same style as marketing_plan.simple).
 */
export const NETWORKING_EVENT_BLUEPRINT_ID = "event.networking_event" as const;

export const EVENT_BLUEPRINT_NETWORKING_EVENT = eventBlueprint({
  blueprintId: NETWORKING_EVENT_BLUEPRINT_ID,
  version: "1.0.0",
  title: "Networking Event",
  description:
    "Plan a purposeful networking event that creates meaningful, comfortable, useful connections — not just a room of people.",
  intendedUse:
    "Business mixers, community networking, member gatherings, industry meetups, facilitated introductions, and recurring connection series.",
  complexity: "moderate",
  sections: [
    {
      id: "event_type",
      title: "Event Type",
      role: "required",
      defaultValue: "Networking Event",
    },
    { id: "purpose", title: "Event Purpose", role: "required" },
    { id: "outcomes", title: "Connection Outcomes", role: "required" },
    { id: "audience", title: "People and Connection Goals", role: "required" },
    {
      id: "format",
      title: "Networking Format",
      role: "required",
      defaultValue: "Facilitated networking",
    },
    { id: "dates", title: "Date, Time, and Length", role: "required" },
    { id: "venue", title: "Setting and Venue", role: "required" },
    { id: "registration", title: "Capacity and Registration", role: "required" },
    {
      id: "attendee_experience",
      title: "Attendee Experience",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "agenda",
      title: "Connection Design and Agenda",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "run_of_show",
      title: "Run of Show",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "speakers",
      title: "Host and Facilitators",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "staff",
      title: "Staff and Roles",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "volunteers",
      title: "Volunteers",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "needs_volunteers" },
    },
    {
      id: "technology",
      title: "Virtual or Hybrid Experience",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "is_virtual_or_hybrid" },
    },
    {
      id: "hospitality",
      title: "Food, Beverage, and Hospitality",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "swag",
      title: "Name Badges and Identity Support",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    { id: "marketing", title: "Promotion and Invitations", role: "required" },
    {
      id: "communications",
      title: "Attendee Communications",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "sponsors",
      title: "Sponsors and Partners",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "has_sponsors" },
    },
    { id: "budget", title: "Budget", role: "required" },
    {
      id: "accessibility",
      title: "Accessibility, Inclusion, and Comfort",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "safety",
      title: "Safety",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "contingencies",
      title: "Risk and Contingencies",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "post_event_follow_up",
      title: "Follow-Up and Relationship Continuation",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "measurement",
      title: "Success Measures",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "archive_and_reuse",
      title: "Post-Event Review",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    SHARED_HIDDEN,
  ],
  defaultValues: {
    event_type: "Networking Event",
    format: "Facilitated networking",
  },
  adaptiveQuestions: [
    {
      id: "q_purpose",
      prompt:
        "Why does this networking event exist, and what kind of connections should result?",
      lowerFrictionPrompt: "What connections should this event create?",
      sectionId: "purpose",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["purpose", "connection_goals"],
      materialChangeNextStep: true,
    },
    {
      id: "q_who_meets",
      prompt: "Who should attend, and who should meet whom?",
      lowerFrictionPrompt: "Who should be in the room — and who should meet?",
      sectionId: "audience",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["audience", "attendee_mix"],
      materialChangeNextStep: true,
    },
    {
      id: "q_format",
      prompt:
        "Which networking format fits best — open mixer, facilitated, speed, table-based, matched, or networking plus content?",
      lowerFrictionPrompt: "Open mixer, facilitated, speed, or tables?",
      sectionId: "format",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["format", "networking_format"],
      materialChangeNextStep: true,
    },
    {
      id: "q_when_where",
      prompt: "When is it, how long, and is it in-person, virtual, or hybrid?",
      lowerFrictionPrompt: "When, how long, and where (or online)?",
      sectionId: "dates",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["dates", "is_virtual_or_hybrid"],
      materialChangeNextStep: true,
    },
    {
      id: "q_capacity",
      prompt: "What attendance target and capacity feel right?",
      lowerFrictionPrompt: "Rough attendance target?",
      sectionId: "registration",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["guest_count", "capacity"],
      materialChangeNextStep: true,
    },
    {
      id: "q_alone_support",
      prompt:
        "How will you support people arriving alone, shy attendees, or anyone who feels left out?",
      lowerFrictionPrompt: "How will alone or shy guests feel welcome?",
      sectionId: "attendee_experience",
      requiredInModes: ["guided_build", "complete_planning"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_prompts",
      prompt:
        "How will conversations begin — prompts, introductions, matching, or host help?",
      sectionId: "agenda",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["connection_prompts"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_hosts",
      prompt: "Who is hosting, and who will notice isolated guests?",
      lowerFrictionPrompt: "Who hosts — and watches for isolated guests?",
      sectionId: "speakers",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["host", "facilitators"],
      materialChangeNextStep: true,
    },
    {
      id: "q_virtual",
      prompt: "Is this virtual or hybrid (so we plan platform and breakouts)?",
      sectionId: "technology",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["is_virtual_or_hybrid"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_sponsors",
      prompt: "Are sponsors or partners involved?",
      sectionId: "sponsors",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["has_sponsors"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_accessibility",
      prompt:
        "What accessibility, sensory, or inclusion needs should shape invitations and the room?",
      sectionId: "accessibility",
      requiredInModes: ["guided_build", "complete_planning"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_follow_up",
      prompt:
        "How will people continue connections afterward — with consent and without pressure?",
      sectionId: "post_event_follow_up",
      requiredInModes: ["guided_build", "complete_planning"],
      postponable: true,
      materialChangeNextStep: false,
    },
  ],
  suggestedTasks: [
    {
      id: "t_purpose",
      title: "Write the connection purpose in one clear paragraph",
      sectionId: "purpose",
    },
    {
      id: "t_format",
      title: "Choose networking format and draft connection activities",
      sectionId: "format",
    },
    {
      id: "t_invite",
      title: "Draft invitation with accessibility and value of attending",
      sectionId: "marketing",
    },
    {
      id: "t_hosts",
      title: "Confirm hosts/facilitators and isolated-guest watchers",
      sectionId: "speakers",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "t_badges",
      title: "Design readable name badges / identity support",
      sectionId: "swag",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "t_run",
      title: "Approve run of show with transition times",
      sectionId: "run_of_show",
      depthModes: ["complete_planning"],
    },
    {
      id: "t_followup",
      title: "Prepare consent-based follow-up path",
      sectionId: "post_event_follow_up",
      depthModes: ["guided_build", "complete_planning"],
    },
  ],
  suggestedMilestones: [
    { id: "m_purpose", title: "Purpose and connection goals approved" },
    { id: "m_format", title: "Format selected" },
    { id: "m_venue", title: "Date and venue (or platform) confirmed" },
    { id: "m_registration", title: "Registration opened" },
    {
      id: "m_hosts",
      title: "Hosts and facilitators confirmed",
      depthModes: ["guided_build", "complete_planning"],
    },
    { id: "m_promo", title: "Promotion launched" },
    {
      id: "m_run",
      title: "Run of show approved",
      depthModes: ["complete_planning"],
    },
    { id: "m_delivered", title: "Event delivered" },
    {
      id: "m_followup",
      title: "Follow-up completed",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "m_review",
      title: "Post-event review completed",
      depthModes: ["complete_planning"],
    },
  ],
  commonlyForgottenItems: [
    "People arriving alone",
    "Unclear conversation prompts",
    "No graceful way to end a conversation",
    "Unreadable name badges",
    "Weak check-in flow",
    "No quiet space",
    "Poor acoustics",
    "No host assigned to isolated attendees",
    "No clear closing",
    "No follow-up consent",
    "Missing dietary accommodations",
    "No weather / venue backup plan",
    "No backup facilitator",
    "Unclear sponsor expectations",
    "Assuming everyone will show",
    "Accessibility missing from invitations",
    "Insufficient transition time",
    "No contact exchange process",
    "Unclear photography consent",
    "Activities that embarrass participants",
    "Forcing everyone to speak",
    "No evaluation of connection quality",
  ],
  riskPrompts: [
    "What if attendance is too low — or too high?",
    "How will you handle cliques and isolated guests?",
    "What if the format feels awkward mid-event?",
    "What is the plan for harassment or conflict?",
    "What if technology or the venue fails?",
  ],
  researchPrompts: [
    "Compare local venues for networking flow and acoustics",
    "Identify communities or partner organizations to invite",
    "Compare networking formats for this audience size",
    "Identify accessibility needs for this venue or platform",
    "Compare registration platforms and check-in options",
    "Review prior event feedback for connection quality",
    "Compare virtual networking platforms if hybrid",
    "Benchmark ticket pricing or free-event expectations",
  ],
  deliverables: [
    "Concise Networking Event Plan",
    "Complete Networking Event Plan",
    "One-page overview",
    "Run of show",
    "Host and facilitator guide",
    "Staff and volunteer plan",
    "Attendee communication schedule",
    "Invitation copy brief",
    "Venue checklist",
    "Equipment checklist",
    "Accessibility checklist",
    "Risk and contingency plan",
    "Budget view",
    "Follow-up plan",
    "Success-measure plan",
    "Post-event review",
    "Task list",
    "Milestone plan",
    "Printable event-day packet",
  ],
  chamberRoutingRecommendations: ["events", "marketing", "operations"],
  boardReviewRecommendations: [
    "event purpose",
    "audience mix",
    "budget",
    "risk",
    "accessibility",
    "strategic value",
  ],
  projectBridgeRecommendations: [
    "Bridge when registration opens or promotion launches",
  ],
  cartographyRelationshipRecommendations: [
    { relationship: "supports", note: "Supports community or relationship goals" },
    { relationship: "related_to", note: "May connect to a marketing plan or membership work" },
  ],
  completionCriteria: [
    "Purpose and connection goals clear",
    "Format chosen intentionally",
    "Date and setting set",
    "Registration / capacity plan exists",
    "Promotion path started",
    "Hosts know how to support alone/shy guests (Guided+)",
    "Follow-up path respects consent (Guided+)",
  ],
  certificationRules: [
    "event.foundation",
    "event.map",
    "event.focus",
    "event.continue",
  ],
  domainExtensions: {
    networkingFormats: [
      "Open mixer",
      "Facilitated networking",
      "Speed networking",
      "Table-based networking",
      "Matched networking",
      "Networking plus content",
      "Recurring networking series",
      "Hybrid networking",
    ],
    successModel:
      "Right people make useful, comfortable, respectful, actionable connections — attendance alone is not success.",
    peopleAndRoles: [
      "Event host",
      "Emcee",
      "Connection facilitators",
      "Greeters",
      "Check-in",
      "Floaters / isolated-guest watchers",
      "Accessibility support",
      "Technology support",
      "Sponsor liaison",
    ],
    budgetConsiderations: [
      "Venue",
      "Food and beverage",
      "Technology",
      "Registration tools",
      "Badges / printing",
      "Staffing",
      "Promotion",
      "Accessibility accommodations",
      "Contingency",
    ],
    timelineRecommendations: [
      "6 weeks: purpose, format, hold date",
      "4 weeks: invitations and registration",
      "2 weeks: host briefings and reminders",
      "1 week: final readiness and run of show",
      "Day-of: check-in, facilitation, closing",
      "48 hours after: consent-based follow-up",
    ],
    communications: [
      "Invitation with accessibility info",
      "Confirmation",
      "Reminders",
      "Day-of instructions",
      "Thank-you / follow-up with consent",
    ],
    followUpRequirements: [
      "Consent for contact exchange",
      "Promised introductions completed",
      "Feedback on connection quality",
      "Next gathering or community invite (optional)",
    ],
    anxietyReduction: [
      "Clear first interaction",
      "Opt-out from structured activities",
      "No forced physical contact or speaking",
      "Quiet area when possible",
      "Readable badges",
    ],
  },
});

/**
 * 127 — Workshop Event Blueprint (general Workshop).
 * Spec ID `event.workshop`. Distinct from Online Workshop / One-Day Workshop specialty BPs.
 */
export const WORKSHOP_EVENT_BLUEPRINT_ID = "event.workshop" as const;

export const EVENT_BLUEPRINT_WORKSHOP = eventBlueprint({
  blueprintId: WORKSHOP_EVENT_BLUEPRINT_ID,
  version: "1.0.0",
  title: "Workshop",
  description:
    "Design, prepare, facilitate, deliver, and follow up on a workshop that produces meaningful learning, participation, confidence, and practical next steps.",
  intendedUse:
    "Short, half-day, full-day, multi-session, in-person, virtual, hybrid, beginner, advanced, team, public, client, internal, paid, and free workshops.",
  complexity: "moderate",
  sections: [
    {
      id: "event_type",
      title: "Event Type",
      role: "required",
      defaultValue: "Workshop",
    },
    { id: "purpose", title: "Workshop Purpose", role: "required" },
    { id: "audience", title: "Participants", role: "required" },
    { id: "outcomes", title: "Learning and Work Outcomes", role: "required" },
    {
      id: "format",
      title: "Format and Delivery Model",
      role: "required",
      defaultValue: "Hands-on workshop",
    },
    { id: "dates", title: "Date, Time, Length, and Setting", role: "required" },
    { id: "venue", title: "Venue, Platform, or Room Design", role: "required" },
    { id: "agenda", title: "Agenda and Learning Flow", role: "required" },
    {
      id: "production",
      title: "Content Architecture",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "attendee_experience",
      title: "Activities, Practice, and Pacing",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "speakers",
      title: "Facilitation Approach",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "swag",
      title: "Participant Materials",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "run_of_show",
      title: "Facilitator Guide and Run of Show",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "registration",
      title: "Registration, Invitations, and Readiness",
      role: "required",
    },
    {
      id: "technology",
      title: "Virtual or Hybrid Design",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "is_virtual_or_hybrid" },
    },
    {
      id: "supplies",
      title: "Technology and Equipment",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "staff",
      title: "Staffing and Support",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "volunteers",
      title: "Volunteers",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "needs_volunteers" },
    },
    {
      id: "hospitality",
      title: "Food, Beverage, and Breaks",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    { id: "budget", title: "Budget and Pricing", role: "required" },
    {
      id: "revenue_pricing",
      title: "Ticket Pricing",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "is_paid" },
    },
    { id: "marketing", title: "Promotion and Messaging", role: "required" },
    {
      id: "communications",
      title: "Participant Communications",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "accessibility",
      title: "Accessibility and Inclusion",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "day_of_operations",
      title: "Day-of Operations",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "contingencies",
      title: "Risk and Contingency",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "post_event_follow_up",
      title: "Follow-Up and Implementation",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "measurement",
      title: "Evaluation and Evidence",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "archive_and_reuse",
      title: "Post-Workshop Review",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    SHARED_HIDDEN,
  ],
  defaultValues: {
    event_type: "Workshop",
    format: "Hands-on workshop",
  },
  adaptiveQuestions: [
    {
      id: "q_purpose",
      prompt:
        "Why does this workshop exist, and what should be different afterward?",
      lowerFrictionPrompt: "What should be different after this workshop?",
      sectionId: "purpose",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["purpose", "workshop_purpose"],
      materialChangeNextStep: true,
    },
    {
      id: "q_participants",
      prompt:
        "Who is this for — roles, experience level, and about how many people?",
      lowerFrictionPrompt: "Who is coming, and roughly how many?",
      sectionId: "audience",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["audience", "participants", "guest_count"],
      materialChangeNextStep: true,
    },
    {
      id: "q_outcomes",
      prompt:
        "What one to three learning or work outcomes should participants leave with?",
      lowerFrictionPrompt: "What should they understand, do, or finish?",
      sectionId: "outcomes",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["outcomes", "learning_outcomes"],
      materialChangeNextStep: true,
    },
    {
      id: "q_format",
      prompt:
        "What format fits — hands-on, facilitated working session, strategy, creative, peer-learning, virtual, or hybrid?",
      lowerFrictionPrompt: "Hands-on, working session, virtual, or hybrid?",
      sectionId: "format",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["format", "delivery_model", "is_virtual_or_hybrid"],
      materialChangeNextStep: true,
    },
    {
      id: "q_when_where",
      prompt: "When is it, how long, and where (or which platform)?",
      lowerFrictionPrompt: "When, how long, and where (or online)?",
      sectionId: "dates",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["dates", "venue", "is_virtual_or_hybrid"],
      materialChangeNextStep: true,
    },
    {
      id: "q_core_activity",
      prompt:
        "What is the one meaningful practice or activity participants must do?",
      lowerFrictionPrompt: "What will they practice or produce?",
      sectionId: "agenda",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["core_activity", "agenda"],
      materialChangeNextStep: true,
    },
    {
      id: "q_facilitation",
      prompt:
        "How will you balance teaching with practice, and support quiet or dominant participants?",
      lowerFrictionPrompt: "Teaching vs practice — and how will everyone participate?",
      sectionId: "speakers",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["facilitation", "facilitator"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_followup",
      prompt: "How will participants keep implementing after the workshop?",
      lowerFrictionPrompt: "What happens after — materials, reminders, support?",
      sectionId: "post_event_follow_up",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["follow_up", "implementation"],
      postponable: true,
      materialChangeNextStep: true,
    },
  ],
  suggestedTasks: [
    {
      id: "t_outcomes",
      title: "Write one to three clear learning or work outcomes",
      sectionId: "outcomes",
    },
    {
      id: "t_agenda",
      title: "Draft timed agenda with breaks and one core practice",
      sectionId: "agenda",
    },
    {
      id: "t_activity",
      title: "Design core activity with timing, materials, and debrief",
      sectionId: "attendee_experience",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "t_materials",
      title: "Prepare participant materials (workbook, slides, or worksheets)",
      sectionId: "swag",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "t_facilitator",
      title: "Complete facilitator guide and run of show",
      sectionId: "run_of_show",
      depthModes: ["complete_planning"],
    },
    {
      id: "t_invite",
      title: "Draft invitation with outcomes, accessibility, and expectations",
      sectionId: "marketing",
    },
    {
      id: "t_rehearsal",
      title: "Run technical or room rehearsal",
      sectionId: "technology",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "t_followup",
      title: "Prepare post-workshop materials and implementation path",
      sectionId: "post_event_follow_up",
      depthModes: ["guided_build", "complete_planning"],
    },
  ],
  suggestedMilestones: [
    { id: "m_purpose", title: "Workshop purpose approved" },
    { id: "m_participants", title: "Participant profile approved" },
    { id: "m_outcomes", title: "Outcomes approved" },
    { id: "m_format", title: "Format selected" },
    { id: "m_venue", title: "Date and venue (or platform) confirmed" },
    { id: "m_agenda", title: "Agenda approved" },
    {
      id: "m_activities",
      title: "Activities approved",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "m_facilitator_materials",
      title: "Facilitator materials complete",
      depthModes: ["complete_planning"],
    },
    {
      id: "m_participant_materials",
      title: "Participant materials complete",
      depthModes: ["guided_build", "complete_planning"],
    },
    { id: "m_registration", title: "Registration opened" },
    { id: "m_promo", title: "Promotion launched" },
    {
      id: "m_rehearsal",
      title: "Technical rehearsal complete",
      depthModes: ["complete_planning"],
    },
    {
      id: "m_readiness",
      title: "Final readiness review complete",
      depthModes: ["complete_planning"],
    },
    { id: "m_delivered", title: "Workshop delivered" },
    {
      id: "m_followup",
      title: "Follow-up completed",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "m_review",
      title: "Post-workshop review completed",
      depthModes: ["complete_planning"],
    },
  ],
  commonlyForgottenItems: [
    "Too many learning outcomes",
    "Unclear difference between teaching and practice",
    "No participant readiness check",
    "No time for questions",
    "No transition time",
    "Insufficient breaks",
    "Unreadable materials",
    "No accessible material version",
    "No backup activity",
    "No plan for dominant participants",
    "No support for quiet participants",
    "No debrief after activities",
    "No follow-up implementation support",
    "No backup technology",
    "No plan if the workshop runs long",
    "No facilitator guide",
    "No participant expectations",
    "No recording consent",
    "No virtual technical rehearsal",
    "No room reset plan",
    "No materials inventory",
    "No evaluation tied to outcomes",
    "No plan for different experience levels",
    "Activities that force disclosure",
    "No post-workshop resource delivery",
  ],
  riskPrompts: [
    "What if registration is too low — or too high?",
    "What if technology or the venue fails mid-session?",
    "What if an activity falls flat or runs long?",
    "How will you handle difficult group dynamics?",
    "What if the facilitator cannot attend?",
  ],
  researchPrompts: [
    "Compare workshop formats for these outcomes and group size",
    "Research participant needs and readiness for this topic",
    "Identify accessibility requirements for this venue or platform",
    "Compare venues or virtual platforms",
    "Benchmark workshop length for this depth of content",
    "Research pricing for similar workshops",
    "Compare registration tools",
    "Identify learning activities that fit these outcomes",
    "Review prior participant feedback",
    "Research facilitation methods for mixed experience levels",
  ],
  deliverables: [
    "Concise Workshop Plan",
    "Complete Workshop Plan",
    "One-page overview",
    "Detailed agenda",
    "Run of show",
    "Facilitator guide",
    "Co-facilitator guide",
    "Participant workbook brief",
    "Participant materials checklist",
    "Activity instructions",
    "Room setup plan",
    "Virtual production plan",
    "Equipment checklist",
    "Accessibility checklist",
    "Risk and contingency plan",
    "Budget view",
    "Promotion brief",
    "Registration communication schedule",
    "Follow-up plan",
    "Evaluation plan",
    "Post-workshop review",
    "Task list",
    "Milestone plan",
    "Printable workshop-day packet",
  ],
  chamberRoutingRecommendations: [
    "events",
    "learning",
    "content",
    "marketing",
    "project-management",
  ],
  boardReviewRecommendations: [
    "workshop purpose",
    "learning outcomes",
    "audience fit",
    "pricing and budget",
    "strategic value",
    "accessibility",
    "facilitator readiness",
    "implementation readiness",
  ],
  projectBridgeRecommendations: [
    "Bridge when registration opens, materials production starts, or promotion launches",
  ],
  cartographyRelationshipRecommendations: [
    {
      relationship: "supports",
      note: "Supports learning, business, or team development goals",
    },
    {
      relationship: "related_to",
      note: "May connect to a marketing plan, course, or content plan",
    },
    {
      relationship: "part_of",
      note: "May be part of a workshop series or program",
    },
  ],
  completionCriteria: [
    "Purpose and outcomes clear",
    "Participants defined",
    "Format and length set",
    "Core agenda with meaningful practice",
    "Date and setting (or platform) set",
    "Promotion or invitation path started",
    "Facilitation and materials ready (Guided+)",
    "Follow-up implementation path exists (Guided+)",
  ],
  certificationRules: [
    "event.foundation",
    "event.map",
    "event.focus",
    "event.continue",
  ],
  domainExtensions: {
    workshopFormats: [
      "Presentation-led workshop",
      "Hands-on workshop",
      "Facilitated working session",
      "Strategy workshop",
      "Planning workshop",
      "Creative workshop",
      "Peer-learning workshop",
      "Lab",
      "Clinic",
      "Intensive",
      "Multi-session series",
      "Virtual workshop",
      "Hybrid workshop",
    ],
    successModel:
      "Participants leave able to do something useful, with practice completed and a clear next step — content volume alone is not success.",
    peopleAndRoles: [
      "Lead facilitator",
      "Co-facilitator",
      "Producer",
      "Technical support",
      "Room host",
      "Registration support",
      "Materials support",
      "Accessibility support",
      "Timekeeper",
    ],
    budgetConsiderations: [
      "Venue or platform",
      "Facilitator",
      "Materials and printing",
      "Technology",
      "Food and beverage",
      "Promotion",
      "Accessibility accommodations",
      "Contingency",
    ],
    timelineRecommendations: [
      "4–6 weeks: purpose, outcomes, hold date",
      "3 weeks: agenda and activity design",
      "2 weeks: invitations and materials draft",
      "1 week: facilitator guide and reminders",
      "Day-before: tech or room check",
      "Day-of: delivery and close",
      "48 hours after: materials and follow-up",
    ],
    communications: [
      "Invitation with outcomes and accessibility info",
      "Confirmation and pre-work",
      "Reminders",
      "Day-of instructions",
      "Thank-you with resources and next steps",
    ],
    followUpRequirements: [
      "Promised materials delivered",
      "Action-plan or implementation support",
      "Feedback tied to outcomes",
      "Questions channel after the event",
    ],
    anxietyReduction: [
      "Clear outcomes and agenda upfront",
      "Opt-out or alternative for high-pressure activities",
      "No forced disclosure",
      "Predictable transitions and breaks",
      "Readable materials",
      "Quiet support for quiet participants",
    ],
  },
});

/**
 * 128 — Webinar Event Blueprint.
 * Spec ID `event.webinar`. Distinct from Online Workshop specialty BP.
 */
export const WEBINAR_EVENT_BLUEPRINT_ID = "event.webinar" as const;

export const EVENT_BLUEPRINT_WEBINAR = eventBlueprint({
  blueprintId: WEBINAR_EVENT_BLUEPRINT_ID,
  version: "1.0.0",
  title: "Webinar",
  description:
    "Plan and produce a webinar that creates understanding and action — engagement, clear CTA, production quality, accessibility, and useful replay — not just attendance.",
  intendedUse:
    "Live educational webinars, product demos, customer training, panels, Q&A, AMA, evergreen/replay-aware, free and paid webinars.",
  complexity: "moderate",
  sections: [
    {
      id: "event_type",
      title: "Event Type",
      role: "required",
      defaultValue: "Webinar",
    },
    { id: "purpose", title: "Webinar Purpose", role: "required" },
    { id: "audience", title: "Audience", role: "required" },
    { id: "outcomes", title: "Outcomes and Call to Action", role: "required" },
    {
      id: "format",
      title: "Webinar Format",
      role: "required",
      defaultValue: "Live educational webinar",
    },
    { id: "dates", title: "Date, Time, and Length", role: "required" },
    { id: "venue", title: "Platform and Access", role: "required" },
    {
      id: "registration",
      title: "Registration",
      role: "required",
    },
    {
      id: "marketing",
      title: "Landing Page and Messaging",
      role: "required",
    },
    { id: "agenda", title: "Agenda", role: "required" },
    {
      id: "production",
      title: "Slides and Content",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "attendee_experience",
      title: "Demonstrations, Polls, Q&A, and Chat",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "speakers",
      title: "Host and Moderator Roles",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "technology",
      title: "Technology Rehearsal",
      role: "required",
    },
    {
      id: "accessibility",
      title: "Accessibility",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "communications",
      title: "Reminder Sequence",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "day_of_operations",
      title: "Live Production",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "swag",
      title: "Recording and Replay",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "will_record" },
    },
    {
      id: "budget",
      title: "Budget",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "revenue_pricing",
      title: "Ticket Pricing",
      role: "conditional",
      condition: { kind: "known_context_truthy", key: "is_paid" },
    },
    {
      id: "staff",
      title: "Production Support Roles",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "contingencies",
      title: "Risk and Contingency",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "post_event_follow_up",
      title: "Follow-Up",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "guided_build" },
    },
    {
      id: "measurement",
      title: "Metrics",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    {
      id: "archive_and_reuse",
      title: "Post-Event Review",
      role: "optional",
      condition: { kind: "depth_at_least", mode: "complete_planning" },
    },
    SHARED_HIDDEN,
  ],
  defaultValues: {
    event_type: "Webinar",
    format: "Live educational webinar",
  },
  adaptiveQuestions: [
    {
      id: "q_purpose",
      prompt:
        "Why does this webinar exist, and what action should viewers take afterward?",
      lowerFrictionPrompt: "What should people do after the webinar?",
      sectionId: "purpose",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["purpose", "cta"],
      materialChangeNextStep: true,
    },
    {
      id: "q_audience",
      prompt: "Who is this webinar for, and what do they already know?",
      lowerFrictionPrompt: "Who is watching, and what do they already know?",
      sectionId: "audience",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["audience", "participants"],
      materialChangeNextStep: true,
    },
    {
      id: "q_outcomes",
      prompt:
        "What should attendees understand, and what is the one clear call to action?",
      lowerFrictionPrompt: "What should they understand — and what's the CTA?",
      sectionId: "outcomes",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["outcomes", "cta"],
      materialChangeNextStep: true,
    },
    {
      id: "q_format",
      prompt:
        "Which format fits — teaching, demo, interview, panel, AMA/Q&A, or workshop-style?",
      lowerFrictionPrompt: "Teaching, demo, panel, or Q&A?",
      sectionId: "format",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["format", "webinar_format"],
      materialChangeNextStep: true,
    },
    {
      id: "q_when_platform",
      prompt: "When is it, how long, and which platform will you use?",
      lowerFrictionPrompt: "When, how long, and which platform?",
      sectionId: "dates",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["dates", "platform", "venue"],
      materialChangeNextStep: true,
    },
    {
      id: "q_record",
      prompt: "Will you record for replay, and where will the replay live?",
      lowerFrictionPrompt: "Recording and replay — yes or no?",
      sectionId: "technology",
      requiredInModes: ["quick_start", "guided_build", "complete_planning"],
      knownContextKeys: ["will_record", "replay"],
      materialChangeNextStep: true,
    },
    {
      id: "q_moderator",
      prompt:
        "Who hosts, who moderates chat/Q&A, and what is the backup if someone drops?",
      lowerFrictionPrompt: "Host, moderator, and backup presenter?",
      sectionId: "speakers",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["host", "moderator"],
      postponable: true,
      materialChangeNextStep: true,
    },
    {
      id: "q_followup",
      prompt: "What happens after — thank-you, replay, resources, and next step?",
      lowerFrictionPrompt: "What do registrants get after the webinar?",
      sectionId: "post_event_follow_up",
      requiredInModes: ["guided_build", "complete_planning"],
      knownContextKeys: ["follow_up"],
      postponable: true,
      materialChangeNextStep: true,
    },
  ],
  suggestedTasks: [
    {
      id: "t_cta",
      title: "Write one clear call to action tied to outcomes",
      sectionId: "outcomes",
    },
    {
      id: "t_landing",
      title: "Draft landing page promise, outcomes, and registration CTA",
      sectionId: "marketing",
    },
    {
      id: "t_agenda",
      title: "Draft timed agenda with Q&A window",
      sectionId: "agenda",
    },
    {
      id: "t_rehearsal",
      title: "Schedule tech rehearsal (audio, screen share, recording)",
      sectionId: "technology",
    },
    {
      id: "t_moderator",
      title: "Confirm host, moderator, and backup presenter scripts",
      sectionId: "speakers",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "t_reminders",
      title: "Set registration confirmation and reminder sequence",
      sectionId: "communications",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "t_replay",
      title: "Prepare replay page and recording permissions copy",
      sectionId: "swag",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "t_followup",
      title: "Prepare post-webinar email with resources and CTA",
      sectionId: "post_event_follow_up",
      depthModes: ["guided_build", "complete_planning"],
    },
  ],
  suggestedMilestones: [
    { id: "m_purpose", title: "Purpose and CTA approved" },
    { id: "m_format", title: "Format selected" },
    { id: "m_platform", title: "Date and platform confirmed" },
    { id: "m_registration", title: "Registration opened" },
    { id: "m_landing", title: "Landing page live" },
    { id: "m_agenda", title: "Agenda approved" },
    {
      id: "m_content",
      title: "Slides and demos ready",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "m_roles",
      title: "Host and moderator confirmed",
      depthModes: ["guided_build", "complete_planning"],
    },
    { id: "m_rehearsal", title: "Tech rehearsal complete" },
    {
      id: "m_reminders",
      title: "Reminder sequence live",
      depthModes: ["guided_build", "complete_planning"],
    },
    { id: "m_delivered", title: "Webinar delivered" },
    {
      id: "m_replay",
      title: "Replay published",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "m_followup",
      title: "Follow-up completed",
      depthModes: ["guided_build", "complete_planning"],
    },
    {
      id: "m_review",
      title: "Post-event review completed",
      depthModes: ["complete_planning"],
    },
  ],
  commonlyForgottenItems: [
    "No tech rehearsal",
    "No backup presenter",
    "No backup internet",
    "Recording permissions unclear",
    "No captioning",
    "No moderator scripts",
    "Weak attendee reminders",
    "No replay page",
    "CTA not tested",
    "No audio checks",
    "Waiting room settings unreviewed",
    "No follow-up automation",
    "Chat/Q&A unmanaged",
    "Screen-share failure plan missing",
    "Late-joiner plan missing",
    "Accessibility missing from registration",
    "No engagement moments (polls or chat prompts)",
    "Replay delivery delayed",
  ],
  riskPrompts: [
    "What if the host loses connection mid-session?",
    "What if attendance is far below registration?",
    "What if recording fails?",
    "How will chat/Q&A stay calm under volume?",
    "What is the backup if the platform fails?",
  ],
  researchPrompts: [
    "Compare webinar platforms for this audience size",
    "Benchmark webinar length for this topic",
    "Research engagement tools (polls, Q&A, chat)",
    "Identify accessibility and captioning options",
    "Compare registration and reminder tools",
    "Research replay hosting and watch-time patterns",
    "Benchmark free vs paid webinar expectations",
    "Review prior webinar feedback for CTA clarity",
  ],
  deliverables: [
    "Concise Webinar Plan",
    "Complete Webinar Plan",
    "One-page overview",
    "Timed agenda",
    "Landing page brief",
    "Slide outline",
    "Host and moderator guide",
    "Tech rehearsal checklist",
    "Accessibility checklist",
    "Reminder sequence",
    "Live production rundown",
    "Recording and replay plan",
    "Follow-up email plan",
    "Metrics plan",
    "Post-event review",
    "Task list",
    "Milestone plan",
    "Printable webinar-day packet",
  ],
  chamberRoutingRecommendations: [
    "events",
    "learning",
    "marketing",
    "content",
    "presentations",
  ],
  boardReviewRecommendations: [
    "webinar purpose",
    "outcomes and CTA",
    "audience fit",
    "pricing",
    "accessibility",
    "strategic value",
    "production readiness",
  ],
  projectBridgeRecommendations: [
    "Bridge when registration opens, promotion launches, or replay production starts",
  ],
  cartographyRelationshipRecommendations: [
    {
      relationship: "supports",
      note: "Supports learning, offer, or customer education goals",
    },
    {
      relationship: "related_to",
      note: "May connect to a marketing plan or content plan",
    },
    {
      relationship: "informs",
      note: "Replay and metrics can inform future webinars",
    },
  ],
  completionCriteria: [
    "Purpose and CTA clear",
    "Audience defined",
    "Format and length set",
    "Platform and registration ready",
    "Agenda with engagement moments",
    "Tech rehearsal planned",
    "Host/moderator roles clear (Guided+)",
    "Follow-up and replay path exists (Guided+)",
  ],
  certificationRules: [
    "event.foundation",
    "event.map",
    "event.focus",
    "event.continue",
  ],
  domainExtensions: {
    webinarFormats: [
      "Teaching",
      "Product demo",
      "Customer training",
      "Interview",
      "Panel",
      "AMA / Q&A",
      "Workshop-style webinar",
      "Evergreen / replay-aware",
    ],
    successModel:
      "Viewers leave with understanding and a clear next action — registration and attendance alone are not success.",
    peopleAndRoles: [
      "Host / presenter",
      "Co-presenter",
      "Moderator",
      "Producer",
      "Tech support",
      "Chat support",
      "Backup presenter",
    ],
    budgetConsiderations: [
      "Platform plan",
      "Promotion",
      "Captioning",
      "Recording / replay hosting",
      "Paid ads",
      "Guest speaker",
      "Contingency",
    ],
    timelineRecommendations: [
      "3–4 weeks: purpose, CTA, hold date",
      "2 weeks: landing page and registration",
      "1 week: agenda, slides, reminder sequence",
      "48 hours: tech rehearsal",
      "Day-of: live production",
      "Same day / 24 hours: replay and follow-up",
    ],
    communications: [
      "Landing page",
      "Registration confirmation",
      "Reminders",
      "Day-of join instructions",
      "Thank-you with replay and CTA",
    ],
    followUpRequirements: [
      "Replay link when promised",
      "Resources delivered",
      "CTA path clear",
      "Feedback on usefulness",
    ],
    kpis: [
      "Registration",
      "Attendance",
      "Engagement",
      "Watch time",
      "CTA completion",
      "Replay usage",
      "Follow-up conversion",
    ],
    anxietyReduction: [
      "Clear join instructions",
      "Waiting room greeter",
      "Optional camera for attendees",
      "Captioning when possible",
      "Moderator handles chat pressure",
      "No forced speaking",
    ],
  },
});

/** All Event Spark Blueprints registered through the universal framework. */
export const EVENT_PLAN_BLUEPRINT_DEFINITIONS: readonly BlueprintDefinition[] = [
  EVENT_BLUEPRINT_BUSINESS_LUNCHEON,
  EVENT_BLUEPRINT_ONLINE_WORKSHOP,
  EVENT_BLUEPRINT_ONE_DAY_WORKSHOP,
  EVENT_BLUEPRINT_THREE_DAY_RETREAT,
  EVENT_BLUEPRINT_BOOK_SIGNING,
  EVENT_BLUEPRINT_NETWORKING_EVENT,
  EVENT_BLUEPRINT_WORKSHOP,
  EVENT_BLUEPRINT_WEBINAR,
];

export const EVENT_PLAN_BLUEPRINT_IDS = EVENT_PLAN_BLUEPRINT_DEFINITIONS.map(
  (b) => b.blueprintId,
) as readonly string[];
