import type { SectionIdeasCatalog } from "../../sectionRuntime/sectionIdeas";

/** Event Plan / Workshop domain ideas — section ids from eventPlanMap. */
export const EVENT_PLAN_SECTION_IDEAS: SectionIdeasCatalog = {
  purpose: [
    "Deepen relationships so people leave feeling known, not just informed.",
    "Launch a new offer with a calm weekend that builds trust first.",
    "Create a planning retreat where founders leave with one clear next step.",
    "Help people recover clarity after a busy season — without a lecture.",
    "Turn a stuck decision into a shared conversation with room to breathe.",
    "Celebrate progress and choose the next chapter together.",
  ],
  audience: [
    "Coaches building a signature retreat for their community.",
    "Founders in year one who want clarity without overwhelm.",
    "Members of an existing circle who are ready for something deeper.",
    "ADHD entrepreneurs who need spacious pacing and clear next steps.",
    "Small groups who already trust each other and want a focused day.",
    "People returning after a pause who need a gentle restart.",
  ],
  outcomes: [
    "Leave with a clear next offer and the confidence to share it.",
    "Reconnect with peers and practice one skill they’ll use Monday.",
    "Walk away with a simple plan they can actually keep.",
    "Make one decision they’ve been avoiding — with support nearby.",
    "Leave lighter: fewer open loops, one prioritized next move.",
    "Have language they can use when someone asks what they’re building.",
  ],
  agenda: [
    "Welcome → one deep session → break → practice → close with next steps.",
    "Arrive softly, one teaching block, peer coaching, then a closing circle.",
    "Morning clarity, afternoon build time, evening celebration of progress.",
    "Open with orientation, map the day, do the core work, then reflect aloud.",
    "Short teach → hands-on build → share → choose tomorrow’s first step.",
    "Warm arrival, decision workshop, quiet work block, grateful close.",
  ],
  event_type: [
    "An intimate in-person workshop with room for real conversation.",
    "A half-day virtual workshop people can join from anywhere.",
    "A hybrid gathering — core circle on-site, others joining online.",
    "A multi-day retreat with spacious mornings and focused afternoons.",
    "An evening salon: short, warm, and built for connection.",
    "A cohort series — same people, several sessions, one arc.",
  ],
  attendee_experience: [
    "People feel welcomed in the first five minutes and never left guessing what’s next.",
    "Every session has one clear takeaway and space to ask the quiet question.",
    "The day feels spacious — enough structure to help, enough breath to think.",
    "No one feels behind; pacing protects dignity and curiosity.",
    "Participants leave knowing who to talk to if they’re stuck later.",
    "The room feels like a place to think, not a place to perform.",
  ],
  dates: [
    "A spring weekend that gives people time to arrive and settle.",
    "A specific month you’re aiming for — even if the exact day is still open.",
    "Two date options so the group can choose what fits.",
    "A midweek half-day for people who can’t give up a weekend.",
    "A date with buffer before and after so travel isn’t frantic.",
    "Align with a natural season for your audience — not just the calendar.",
  ],
  venue: [
    "A calm rented room close to where your people already gather.",
    "Home-hosted if the circle is small and trust is already there.",
    "Virtual first — easiest to host while the offer takes shape.",
    "A nature-adjacent space that helps people breathe between sessions.",
    "A familiar community room so arrival feels easy.",
    "Somewhere with natural light and a place to move during breaks.",
  ],
  topic: [
    "One clear topic beats a broad list — name what this is really about.",
    "Focus on the decision people are stuck on, not every related idea.",
    "Choose the transformation, then let the title follow.",
    "Name the tension your people feel — then the relief you’ll offer.",
    "Keep the theme narrow enough to teach well in the time you have.",
    "Let the topic serve the outcome — not the other way around.",
  ],
  speakers: [
    "You as host, plus one guest who brings a complementary lens.",
    "Peer facilitators from inside the community — less stage, more circle.",
    "Keep it lean: one voice that holds the thread all day.",
    "Invite a member story instead of another expert slot.",
    "Co-host with someone who steadies logistics while you hold the room.",
    "No panel unless it truly serves conversation — prefer dialogue.",
  ],
};
