/**
 * Permanent platform rule — Creation Identity is three fields, never one:
 *
 * 1. originalRequest — raw member words; never mutates; never becomes the title
 * 2. workingIntent — internal routing label (e.g. "Create Checklist")
 * 3. humanWorkspaceTitle — member-facing name (e.g. "Client Onboarding Checklist")
 *
 * The workspace title must NEVER be generated by truncating / polishing the
 * raw chat message. Derive structure first, then name the work.
 */

import { isForceNewCreationRequest } from "@/lib/universalCreationEntrypoint/forceNewIntent";
import {
  isCreationMetaTitle,
  isUsableHumanTitle,
  stripCreationMetaPreamble,
} from "@/lib/activeWorkspaceRegistry/titleGuards";

export type CreationIdentity = {
  /** Exact member words — store as-is. */
  originalRequest: string;
  /** Internal routing intent — not shown as the workspace name. */
  workingIntent: string;
  /** Clean, human-readable workspace title. */
  humanWorkspaceTitle: string;
};

/** Concrete artifact nouns — most specific wins (last match preferred). */
const ARTIFACT_KIND_RE =
  /\b(checklist|workshop|retreat|webinar|conference|newsletter|proposal|sop|course|email|document|workbook|guide|playbook|agenda|template)\b/gi;

/** Topic adjectives — never treated as the artifact kind alone. */
const TOPIC_ONLY_WORDS =
  /\b(?:onboarding|client|customer|leadership|productivity|simple|system)\b/i;

const FOR_TOPIC_RE =
  /\b(?:for|about|on)\s+(?:a |an |the |my )?(?<topic>[a-z0-9][\w\s&/-]{2,48}?)(?:\s+(?:checklist|workshop|retreat|webinar|conference|newsletter|proposal|sop|course|email|document|workbook|guide|playbook|agenda|template))?\s*[.!]?\s*$/i;

/** True when a "title" is still chat prose, not a name. */
function looksLikeRawChatTitle(title: string): boolean {
  const t = title.trim();
  if (!t) return true;
  if (isCreationMetaTitle(t)) return true;
  if (/^(?:i want|i need|help me|can you|let'?s|please|start something)\b/i.test(t)) {
    return true;
  }
  if (t.split(/\s+/).length > 8) return true;
  if (/[.!?]$/.test(t) && t.split(/\s+/).length > 4) return true;
  return false;
}

function titleCase(phrase: string): string {
  return phrase
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => {
      if (/^(?:and|or|of|for|the|a|an|to|in|on)$/i.test(w)) {
        return w.toLowerCase();
      }
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    })
    .join(" ")
    .replace(/^\w/, (c) => c.toUpperCase());
}

/**
 * Prefer the most specific / terminal artifact noun in the text.
 * "client onboarding checklist" → checklist (not onboarding).
 */
/**
 * Intent Detection reads the member's words first.
 * `creationType` is fallback only when the request has no artifact noun —
 * never concatenated into the match string (catalog/Workshop must not peer-compete).
 */
function detectArtifactKind(
  text: string,
  creationType?: string | null,
): string {
  const matches = [...text.matchAll(ARTIFACT_KIND_RE)].map((m) =>
    m[1].toLowerCase(),
  );
  if (matches.length > 0) {
    // Prefer checklist / concrete deliverables over broader workshop/event nouns
    // when both appear (mis-routed Workshop + checklist request).
    if (matches.includes("checklist")) return "checklist";
    if (matches.includes("sop")) return "sop";
    if (matches.includes("newsletter")) return "newsletter";
    if (matches.includes("proposal")) return "proposal";
    if (matches.includes("email")) return "email";
    // Otherwise take the last concrete artifact noun in the phrase.
    return matches[matches.length - 1];
  }
  const type = (creationType || "").trim().toLowerCase();
  if (
    type &&
    type !== "creation" &&
    type !== "event plan" &&
    !TOPIC_ONLY_WORDS.test(type)
  ) {
    return type.replace(/\s+plan$/, "");
  }
  return "document";
}

/** Gathering / Event Plan kinds — Event Workspace may apply. */
const EVENT_CLASSIFICATION_KINDS = new Set([
  "event plan",
  "event",
  "workshop",
  "retreat",
  "webinar",
  "conference",
  "summit",
  "masterclass",
]);

/**
 * Document Classification types (Checklist, Newsletter, Document, …).
 * From this point forward Document Classification is the sole authority —
 * Event Workspace must never replace template, structure, title, or kind.
 */
export function isDocumentClassificationType(
  classificationType: string | null | undefined,
): boolean {
  const t = (classificationType || "").trim().toLowerCase();
  if (!t) return false;
  if (EVENT_CLASSIFICATION_KINDS.has(t)) return false;
  return true;
}

/** True only when classification permits Event Creation Workspace bind. */
export function mayApplyEventWorkspace(
  classificationType: string | null | undefined,
): boolean {
  const t = (classificationType || "").trim();
  if (!t) return true;
  return !isDocumentClassificationType(t);
}

function extractTopicPhrase(cleaned: string, kind: string): string | null {
  const lowerKind = kind.toLowerCase();
  const normalized = cleaned
    .replace(/,/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  // Prefer "... <topic> <kind>" near the end.
  const beforeKind = new RegExp(
    `\\b(?:a |an |the |my )?([a-z0-9][\\w\\s&/-]{2,40}?)\\s+${lowerKind}\\s*[.!?]?$`,
    "i",
  );
  const before = normalized.match(beforeKind);
  if (before?.[1]) {
    const topic = before[1]
      .replace(
        /^(?:brand new|separate|completely separate|project for|project)\s+/i,
        "",
      )
      .replace(/\b(?:brand new|completely|separate|project)\b/gi, " ")
      .replace(/\s+/g, " ")
      .trim();
    const tightened = topic
      .replace(/^(?:for|about|on)\s+(?:a |an |the |my )?/i, "")
      .trim();
    if (tightened.length >= 3 && !/^(?:for|project)\b/i.test(tightened)) {
      return tightened;
    }
  }

  const forMatch = normalized.match(FOR_TOPIC_RE);
  if (forMatch?.groups?.topic) {
    const topic = forMatch.groups.topic
      .replace(/^(?:brand new|separate|completely separate)\s+/i, "")
      .replace(/\s+/g, " ")
      .trim();
    if (topic.length >= 3 && !/^(?:project)\b/i.test(topic)) return topic;
  }

  const words = normalized
    .replace(/[?!.,;:]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(
      (w) =>
        w.length > 1 &&
        !/^(?:i|want|need|to|start|create|build|make|write|plan|design|project|completely|separate|new|brand|something|for|a|an|the|my|please|help|me)$/i.test(
          w,
        ),
    );
  if (words.length === 0) return null;
  const slice = words.slice(Math.max(0, words.length - 4));
  return slice.join(" ");
}

function buildWorkingIntent(kind: string): string {
  return `Create ${titleCase(kind)}`;
}

function topicAlreadyNamed(
  topicTitle: string,
  kindLabel: string,
): boolean {
  const t = topicTitle.toLowerCase();
  const k = kindLabel.toLowerCase();
  if (t.endsWith(k)) return true;
  // Topic already contains any concrete artifact noun — do not append another.
  if (
    /\b(checklist|workshop|retreat|webinar|newsletter|proposal|sop|course|email|document|workbook|guide|playbook|agenda)\b/i.test(
      topicTitle,
    )
  ) {
    return true;
  }
  return false;
}

function buildHumanTitle(
  topic: string | null,
  kind: string,
  creationType?: string | null,
): string {
  const kindLabel = titleCase(kind);
  if (topic) {
    const topicTitle = titleCase(topic);
    if (topicAlreadyNamed(topicTitle, kindLabel)) {
      return topicTitle;
    }
    const composed = `${topicTitle} ${kindLabel}`.replace(/\s+/g, " ").trim();
    if (isUsableHumanTitle(composed, creationType || kindLabel)) {
      return composed;
    }
    if (
      isUsableHumanTitle(topicTitle, creationType || kindLabel) &&
      !/\b(?:for|about|project)\b/i.test(topicTitle) &&
      topicTitle.split(/\s+/).length <= 6
    ) {
      return topicTitle;
    }
  }
  const type = (creationType || kindLabel).trim();
  if (type && !isCreationMetaTitle(type) && type.toLowerCase() !== "workshop") {
    return `Untitled ${titleCase(type.replace(/\s+plan$/i, ""))}`;
  }
  if (kind && kind !== "document") {
    return `Untitled ${kindLabel}`;
  }
  return "Untitled Work";
}

/**
 * Derive the three Creation Identity fields from a create entry.
 * Never returns the raw chat string as humanWorkspaceTitle.
 */
export function deriveCreationIdentity(input: {
  originalRequest: string;
  creationType?: string | null;
  /** Optional already-confirmed member title (rename / explicit / resume). */
  confirmedTitle?: string | null;
}): CreationIdentity {
  const originalRequest = input.originalRequest?.trim() || "";
  const creationType = input.creationType?.trim() || null;

  // Confirmed / resumed titles win as-is — never re-mash them.
  if (
    input.confirmedTitle &&
    isUsableHumanTitle(input.confirmedTitle, creationType) &&
    !looksLikeRawChatTitle(input.confirmedTitle)
  ) {
    // Intent Detection: member words + confirmed title only; creationType = fallback.
    const kind = detectArtifactKind(
      `${input.confirmedTitle} ${originalRequest}`.trim(),
      creationType,
    );
    return {
      originalRequest,
      workingIntent: buildWorkingIntent(kind),
      humanWorkspaceTitle: input.confirmedTitle.trim(),
    };
  }

  const structural = stripCreationMetaPreamble(originalRequest);
  // Intent Detection authority: originalRequest text only.
  // creationType is fallback inside detectArtifactKind when no noun is present.
  const kind = detectArtifactKind(structural, creationType);
  const topic = extractTopicPhrase(structural, kind);
  let humanWorkspaceTitle = buildHumanTitle(topic, kind, creationType);
  const workingIntent = buildWorkingIntent(kind);

  // Guard: never return chat prose or meta as the title.
  if (
    !humanWorkspaceTitle ||
    isCreationMetaTitle(humanWorkspaceTitle) ||
    looksLikeRawChatTitle(humanWorkspaceTitle) ||
    (originalRequest &&
      humanWorkspaceTitle.toLowerCase() === originalRequest.toLowerCase())
  ) {
    humanWorkspaceTitle = buildHumanTitle(topic, kind, creationType);
  }

  return {
    originalRequest,
    workingIntent,
    humanWorkspaceTitle,
  };
}

/** True when text looks like a force-new create request (for callers). */
export function isForceNewIdentityRequest(text: string): boolean {
  return isForceNewCreationRequest(text);
}

/**
 * Classification type from workingIntent — the single authoritative input
 * for template selection and workspace type.
 * "Create Checklist" → "Checklist"
 */
export function classificationTypeFromWorkingIntent(
  workingIntent: string | null | undefined,
): string {
  const raw = (workingIntent || "").trim();
  if (!raw) return "Document";
  const stripped = raw.replace(/^Create\s+/i, "").trim();
  return stripped || "Document";
}
