/**
 * 063 — Machine-readable Standard Implementation Traceability Matrix.
 * Reflects the repository, not intentions. Blank / NOT_RUN = real gap.
 */

import type {
  CrossEntryTraceRow,
  RequirementTraceRow,
  StandardMatrixRow,
} from "./types";

/** Master standards matrix — one row per governing standard (published IDs). */
export const MASTER_STANDARDS_MATRIX: readonly StandardMatrixRow[] = [
  {
    standardId: "045",
    capability: "Intent Routing",
    governingDoc:
      "docs/create-experience/standards/045_PLATFORM_INTENT_ROUTING_AND_CREATION_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/platformIntent/",
    unit: "PARTIAL",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PARTIAL",
    certification: "IN_IMPLEMENTATION",
    owner: null,
    notes: "Platform intent routing exists; full certification pending.",
  },
  {
    standardId: "046",
    capability: "Create Blueprints",
    governingDoc:
      "docs/create-experience/standards/046_CREATE_BLUEPRINT_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/platformIntent/",
    unit: "PARTIAL",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PARTIAL",
    certification: "IN_IMPLEMENTATION",
    owner: null,
    notes: "",
  },
  {
    standardId: "047",
    capability: "Asset Generation",
    governingDoc:
      "docs/create-experience/standards/047_CREATE_ECOSYSTEM_AND_ASSET_GENERATION_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/eventsIntelligence/eventAssetRegistry/",
    unit: "PARTIAL",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PARTIAL",
    certification: "IN_IMPLEMENTATION",
    owner: null,
    notes: "",
  },
  {
    standardId: "048",
    capability: "Creation Workspace",
    governingDoc:
      "docs/create-experience/standards/048_CREATION_WORKSPACE_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/eventCreationWorkspace/",
    unit: "PARTIAL",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PARTIAL",
    certification: "IN_IMPLEMENTATION",
    owner: null,
    notes: "",
  },
  {
    standardId: "049",
    capability: "Creation Ecosystem",
    governingDoc:
      "docs/create-experience/standards/049_CREATION_ECOSYSTEM_CONNECTION_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/creationEcosystem/",
    unit: "PARTIAL",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PARTIAL",
    certification: "IN_IMPLEMENTATION",
    owner: null,
    notes: "",
  },
  {
    standardId: "050",
    capability: "Ownership & Collaboration",
    governingDoc:
      "docs/create-experience/standards/050_CREATION_OWNERSHIP_AND_COLLABORATION_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/creationOwnership/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "creationOwnership.test.ts",
  },
  {
    standardId: "051",
    capability: "Universal Creation Engine",
    governingDoc:
      "docs/create-experience/standards/051_UNIVERSAL_CREATION_ENGINE_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/universalCreationEngine/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "universalCreationEngine.test.ts",
  },
  {
    standardId: "052A",
    capability: "Dynamic Section Assets",
    governingDoc:
      "docs/create-experience/standards/052A_DYNAMIC_SECTION_ASSET_REGISTRY_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/eventsIntelligence/eventAssetRegistry/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "",
  },
  {
    standardId: "053",
    capability: "Event Capability Registry",
    governingDoc:
      "docs/create-experience/standards/053_EVENT_CAPABILITY_REGISTRY_AND_DYNAMIC_SECTION_RUNTIME.md",
    implementationSpec: null,
    runtimePath: "lib/eventsIntelligence/eventCapabilityRegistry/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "",
  },
  {
    standardId: "054",
    capability: "Connected Asset Editor",
    governingDoc:
      "docs/create-experience/standards/054_CONNECTED_ASSET_EDITOR_FRAMEWORK.md",
    implementationSpec: null,
    runtimePath: "lib/connectedAssetEditor/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "",
  },
  {
    standardId: "055",
    capability: "Universal Entrypoints",
    governingDoc:
      "docs/create-experience/standards/055_UNIVERSAL_CREATION_ENTRYPOINT_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/universalCreationEntrypoint/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "Shari / Create / Projects wired; browser proof pending.",
  },
  {
    standardId: "056",
    capability: "Create Experience Redesign",
    governingDoc:
      "docs/create-experience/standards/056_CREATE_EXPERIENCE_REDESIGN_STANDARD.md",
    implementationSpec:
      "docs/create-experience/specs/056_CREATE_EXPERIENCE_IMPLEMENTATION_SPECIFICATION.md",
    runtimePath:
      "components/companion/CreateEstateEntrancePanel.tsx · lib/createEstate/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes:
      "NL primary entry; categories optional. Cert spec: docs/create-experience/specs/056_CREATE_EXPERIENCE_CERTIFICATION_SPECIFICATION.md",
  },
  {
    standardId: "057",
    capability: "Projects Active Work",
    governingDoc:
      "docs/create-experience/standards/057_PROJECTS_EXPERIENCE_AND_AUTOMATIC_WORKSPACE_STANDARD.md",
    implementationSpec: null,
    runtimePath:
      "lib/projects/activeWork/ · components/companion/projectHomes/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "Project Homes invisible; Continue Your Work.",
  },
  {
    standardId: "058",
    capability: "Platform Workspace Experience",
    governingDoc:
      "docs/create-experience/standards/058_PLATFORM_WORKSPACE_EXPERIENCE_STANDARD.md",
    implementationSpec: null,
    runtimePath:
      "components/companion/CreateEstateWorkingPanel.tsx · lib/discoveryToWorkspace/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "Current Focus + What We Know; never blank.",
  },
  {
    standardId: "059",
    capability: "Discovery → Workspace Transition",
    governingDoc:
      "docs/create-experience/standards/059_DISCOVERY_TO_WORKSPACE_TRANSITION_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/discoveryToWorkspace/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "Draft ID was 057 in some docs — published as 059.",
  },
  {
    standardId: "060",
    capability: "Intelligent Recommendation Engine",
    governingDoc:
      "docs/create-experience/standards/060_INTELLIGENT_RECOMMENDATION_ENGINE_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/intelligentRecommendation/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "1 primary · ≤3 secondary; dependency-aware.",
  },
  {
    standardId: "061",
    capability: "Universal Creation State Machine",
    governingDoc:
      "docs/create-experience/standards/061_UNIVERSAL_CREATION_STATE_MACHINE_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/universalCreationStateMachine/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "Shared lifecycle; recommendations adapt by state.",
  },
  {
    standardId: "062",
    capability: "Implementation & Certification",
    governingDoc:
      "docs/create-experience/standards/062_IMPLEMENTATION_AND_CERTIFICATION_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/createCertification/",
    unit: "PASS",
    integration: "NOT_APPLICABLE",
    browser: "NOT_RUN",
    accessibility: "NOT_APPLICABLE",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "Gates certification; production hardening mode.",
  },
  {
    standardId: "063",
    capability: "Traceability Matrix",
    governingDoc:
      "docs/create-experience/standards/063_STANDARD_IMPLEMENTATION_TRACEABILITY_MATRIX.md",
    implementationSpec: null,
    runtimePath: "lib/createCertification/traceabilityMatrix.ts",
    unit: "PASS",
    integration: "NOT_APPLICABLE",
    browser: "NOT_APPLICABLE",
    accessibility: "NOT_APPLICABLE",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "This matrix — machine-readable.",
  },
  {
    standardId: "064",
    capability: "Implementation Specification Template",
    governingDoc:
      "docs/create-experience/standards/064_IMPLEMENTATION_SPECIFICATION_TEMPLATE.md",
    implementationSpec:
      "docs/create-experience/standards/064_IMPLEMENTATION_SPECIFICATION_TEMPLATE.md",
    runtimePath: "lib/createCertification/artifactTemplates.ts",
    unit: "PASS",
    integration: "NOT_APPLICABLE",
    browser: "NOT_APPLICABLE",
    accessibility: "NOT_APPLICABLE",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "Copy per capability into docs/create-experience/specs/.",
  },
  {
    standardId: "065",
    capability: "Certification Test Specification Template",
    governingDoc:
      "docs/create-experience/standards/065_CERTIFICATION_TEST_SPECIFICATION_TEMPLATE.md",
    implementationSpec:
      "docs/create-experience/standards/065_CERTIFICATION_TEST_SPECIFICATION_TEMPLATE.md",
    runtimePath: "lib/createCertification/artifactTemplates.ts",
    unit: "PASS",
    integration: "NOT_APPLICABLE",
    browser: "NOT_APPLICABLE",
    accessibility: "NOT_APPLICABLE",
    regression: "PASS",
    certification: "TESTING",
    owner: null,
    notes: "Copy per capability; required before CERTIFIED.",
  },
  {
    standardId: "066",
    capability: "Single Experience Workspace",
    governingDoc:
      "docs/create-experience/standards/066_SINGLE_EXPERIENCE_WORKSPACE_STANDARD.md",
    implementationSpec:
      "docs/create-experience/HARDENING_066_RUNTIME_CURRENT_FOCUS.md",
    runtimePath: "lib/currentFocus/ · lib/singleExperienceWorkspace/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_RUN",
    regression: "PARTIAL",
    certification: "TESTING",
    owner: null,
    notes:
      "066-RUNTIME: Current Focus sole owner; is066OwnershipRuntimeComplete() true in unit gates. Browser B066 NOT_RUN — not CERTIFIED.",
  },
  {
    standardId: "067",
    capability: "Trust Contract",
    governingDoc:
      "docs/create-experience/standards/067_TRUST_CONTRACT_STANDARD.md",
    implementationSpec: null,
    runtimePath: "lib/trustContract/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_APPLICABLE",
    regression: "PARTIAL",
    certification: "TESTING",
    owner: null,
    notes:
      "Sprint 4: promise scrub + critical save falsehood fixed; open memory-claim audit remains.",
  },
  {
    standardId: "068",
    capability: "Creation Commit Coordinator",
    governingDoc:
      "docs/create-experience/standards/068_CREATION_COMMIT_COORDINATOR_STANDARD.md",
    implementationSpec:
      "docs/create-experience/ARCHITECTURE_CREATION_COMMIT_COORDINATOR.md",
    runtimePath: "lib/creationCommitCoordinator/",
    unit: "PASS",
    integration: "NOT_RUN",
    browser: "NOT_RUN",
    accessibility: "NOT_APPLICABLE",
    regression: "PARTIAL",
    certification: "IN_IMPLEMENTATION",
    owner: null,
    notes:
      "Pure gate defined; CPC Creation open path not yet wired (speaks before bind/mount).",
  },
  {
    standardId: "069",
    capability: "Trust Kernel",
    governingDoc:
      "docs/create-experience/standards/069_TRUST_KERNEL_STANDARD.md",
    implementationSpec:
      "docs/create-experience/HARDENING_SPRINT_T1_TRUST_KERNEL_EGRESS.md",
    runtimePath: "lib/trustKernel/",
    unit: "PASS",
    integration: "PARTIAL",
    browser: "NOT_RUN",
    accessibility: "NOT_APPLICABLE",
    regression: "PARTIAL",
    certification: "TESTING",
    owner: null,
    notes:
      "Sprint T1: sole egress wired for Universal Creation / Events open. Browser BT-T1 NOT_RUN — not CERTIFIED. Remaining non-UC emitters in HARDENING_SPRINT_T1 §11.",
  },
] as const;

/** Material requirement-level rows (expand over time — blank = gap). */
export const REQUIREMENT_TRACE_MATRIX: readonly RequirementTraceRow[] = [
  {
    requirementId: "055-R001",
    standardId: "055",
    requirement: "All entry points resolve to one Creation Record",
    implementationFile: "lib/universalCreationEntrypoint/",
    runtimeFunction: "resolveUniversalCreationEntrypoint",
    testFile: "lib/universalCreationEntrypoint/universalCreationEntrypoint.test.ts",
    testCase: "entry helpers share one resolver",
    evidence: "unit",
    status: "PASS",
    gap: "Browser proof across all front doors pending",
  },
  {
    requirementId: "055-R002",
    standardId: "055",
    requirement: "Existing work is checked before creation",
    implementationFile: "lib/universalCreationEntrypoint/existingWorkSearch.ts",
    runtimeFunction: "searchExistingCreationWork",
    testFile: "lib/universalCreationEntrypoint/universalCreationEntrypoint.test.ts",
    testCase: "existing work search",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
  {
    requirementId: "056-R001",
    standardId: "056",
    requirement: "Create uses natural-language input as primary entry",
    implementationFile: "components/companion/CreateEstateEntrancePanel.tsx",
    runtimeFunction: "onBeginCreate / resolveCreateBeginOutcome",
    testFile: "lib/createEstate/resolveCreateBeginOutcome.test.ts",
    testCase: "Begin open or clarify — never silent",
    evidence: "unit",
    status: "PASS",
    gap: "Browser proof pending",
  },
  {
    requirementId: "056-R002",
    standardId: "056",
    requirement: "Categories are optional browse only",
    implementationFile: "components/companion/CreateEstateEntrancePanel.tsx",
    runtimeFunction: "details browse for inspiration",
    testFile: "lib/createEstate/createEstateDestination.test.ts",
    testCase: "categories under details",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
  {
    requirementId: "056-R003",
    standardId: "056",
    requirement: "Continue Existing Work shows active workspaces first",
    implementationFile: "lib/createEstate/listActiveCreationWorkspaces.ts",
    runtimeFunction: "listActiveCreationWorkspaces",
    testFile: "lib/createEstate/listActiveCreationWorkspaces.test.ts",
    testCase: "active Creation Workspaces",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
  {
    requirementId: "059-R001",
    standardId: "059",
    requirement: "Discovery stops when enough is known",
    implementationFile: "lib/discoveryToWorkspace/eventTransition.ts",
    runtimeFunction: "isEventFoundationReady",
    testFile: "lib/discoveryToWorkspace/discoveryToWorkspace.test.ts",
    testCase: "never uses blank workspace openers after foundation",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
  {
    requirementId: "059-R002",
    standardId: "059",
    requirement: "Workspace never opens blank",
    implementationFile: "lib/eventCreationWorkspace/applyWorkspaceToCreateWorkflow.ts",
    runtimeFunction: "applyEventWorkspaceToCreateWorkflow",
    testFile: "lib/discoveryToWorkspace/discoveryToWorkspace.test.ts",
    testCase: "stamps Current Focus + What We Know",
    evidence: "unit",
    status: "PASS",
    gap: "Library J-001 PASS; authenticated browser still pending",
  },
  {
    requirementId: "059-R003",
    standardId: "059",
    requirement: "Known facts are not re-asked",
    implementationFile: "lib/eventsIntelligence/guideEventPlanning.ts",
    runtimeFunction: "continueReply",
    testFile: "lib/discoveryToWorkspace/discoveryToWorkspace.test.ts",
    testCase: "transition reply",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
  {
    requirementId: "060-R001",
    standardId: "060",
    requirement: "One primary recommendation is shown",
    implementationFile: "lib/intelligentRecommendation/rankAndLimit.ts",
    runtimeFunction: "rankAndLimitRecommendations",
    testFile: "lib/intelligentRecommendation/intelligentRecommendation.test.ts",
    testCase: "always provides one primary",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
  {
    requirementId: "060-R002",
    standardId: "060",
    requirement: "Recommendations respect dependencies",
    implementationFile: "lib/intelligentRecommendation/eventCandidates.ts",
    runtimeFunction: "collectEventRecommendationCandidates",
    testFile: "lib/intelligentRecommendation/intelligentRecommendation.test.ts",
    testCase: "dependency unlocking — agenda",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
  {
    requirementId: "061-R001",
    standardId: "061",
    requirement: "Every creation has a valid lifecycle state",
    implementationFile: "lib/universalCreationStateMachine/resolveFromEvent.ts",
    runtimeFunction: "resolveUniversalCreationStateFromEvent",
    testFile:
      "lib/universalCreationStateMachine/universalCreationStateMachine.test.ts",
    testCase: "begins in idea / discovery",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
  {
    requirementId: "061-R002",
    standardId: "061",
    requirement: "Reverse transitions are allowed and update recommendations",
    implementationFile: "lib/universalCreationStateMachine/transitions.ts",
    runtimeFunction: "isAllowedUniversalTransition",
    testFile:
      "lib/universalCreationStateMachine/universalCreationStateMachine.test.ts",
    testCase: "allows natural forward and reverse transitions",
    evidence: "unit",
    status: "PARTIAL",
    gap: "Readiness cascade on reverse not fully wired",
  },
  {
    requirementId: "062-R001",
    standardId: "062",
    requirement: "Certification cannot complete without required evidence",
    implementationFile: "lib/createCertification/assessCertification.ts",
    runtimeFunction: "canMarkCertified",
    testFile: "lib/createCertification/createCertification.test.ts",
    testCase: "blocks CERTIFIED without browser proof",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
  {
    requirementId: "063-R001",
    standardId: "063",
    requirement: "Every standard maps through the traceability chain",
    implementationFile: "lib/createCertification/traceabilityMatrix.ts",
    runtimeFunction: "MASTER_STANDARDS_MATRIX",
    testFile: "lib/createCertification/createCertification.test.ts",
    testCase: "matrix covers published standards",
    evidence: "unit",
    status: "PASS",
    gap: null,
  },
] as const;

export const CROSS_ENTRY_TRACE_MATRIX: readonly CrossEntryTraceRow[] = [
  {
    journey: "J-001 Shari → workshop → agenda → return",
    entryPoint: "Shari",
    canonicalRecord: "PASS",
    workspace: "PASS",
    contextPreserved: "PARTIAL",
    noDuplicate: "PASS",
    resume: "PARTIAL",
    browserProof: "NOT_RUN",
    status: "TESTING",
  },
  {
    journey: "J-002 Create NL → same Event Workspace",
    entryPoint: "Create",
    canonicalRecord: "PASS",
    workspace: "PASS",
    contextPreserved: "PARTIAL",
    noDuplicate: "PASS",
    resume: "PARTIAL",
    browserProof: "NOT_RUN",
    status: "TESTING",
  },
  {
    journey: "J-003 Projects Continue → same Event",
    entryPoint: "Projects",
    canonicalRecord: "PARTIAL",
    workspace: "PARTIAL",
    contextPreserved: "PARTIAL",
    noDuplicate: "PARTIAL",
    resume: "PARTIAL",
    browserProof: "NOT_RUN",
    status: "TESTING",
  },
  {
    journey: "J-004 Marketing → landing → existing Event",
    entryPoint: "Marketing",
    canonicalRecord: "PARTIAL",
    workspace: "PARTIAL",
    contextPreserved: "NOT_RUN",
    noDuplicate: "PARTIAL",
    resume: "NOT_RUN",
    browserProof: "NOT_RUN",
    status: "TESTING",
  },
  {
    journey: "J-005 Search → workshop → same workspace",
    entryPoint: "Search",
    canonicalRecord: "PASS",
    workspace: "PASS",
    contextPreserved: "PARTIAL",
    noDuplicate: "PASS",
    resume: "PARTIAL",
    browserProof: "NOT_RUN",
    status: "TESTING",
  },
  {
    journey: "J-006 Refresh / restart / restore",
    entryPoint: "Resume",
    canonicalRecord: "PARTIAL",
    workspace: "PARTIAL",
    contextPreserved: "PARTIAL",
    noDuplicate: "PASS",
    resume: "PARTIAL",
    browserProof: "NOT_RUN",
    status: "TESTING",
  },
  {
    journey: "J-007 150% zoom / keyboard / scroll",
    entryPoint: "Accessibility",
    canonicalRecord: "NOT_APPLICABLE",
    workspace: "PARTIAL",
    contextPreserved: "NOT_APPLICABLE",
    noDuplicate: "NOT_APPLICABLE",
    resume: "PARTIAL",
    browserProof: "NOT_RUN",
    status: "TESTING",
  },
  {
    journey: "J-008 Type change same record",
    entryPoint: "Type change",
    canonicalRecord: "PASS",
    workspace: "PASS",
    contextPreserved: "PASS",
    noDuplicate: "PASS",
    resume: "PARTIAL",
    browserProof: "NOT_RUN",
    status: "TESTING",
  },
  {
    journey: "TRUST Permanent release journey",
    entryPoint: "Trust",
    canonicalRecord: "NOT_RUN",
    workspace: "NOT_RUN",
    contextPreserved: "NOT_RUN",
    noDuplicate: "NOT_RUN",
    resume: "NOT_RUN",
    browserProof: "NOT_RUN",
    status: "NOT_STARTED",
  },
  {
    journey: "Open related asset from Cartography",
    entryPoint: "Cartography",
    canonicalRecord: "NOT_RUN",
    workspace: "NOT_RUN",
    contextPreserved: "NOT_RUN",
    noDuplicate: "NOT_RUN",
    resume: "NOT_RUN",
    browserProof: "NOT_RUN",
    status: "NOT_STARTED",
  },
  {
    journey: "Begin from Visual Thinking",
    entryPoint: "Visual Thinking",
    canonicalRecord: "NOT_RUN",
    workspace: "NOT_RUN",
    contextPreserved: "NOT_RUN",
    noDuplicate: "NOT_RUN",
    resume: "NOT_RUN",
    browserProof: "NOT_RUN",
    status: "NOT_STARTED",
  },
] as const;

export function getStandardMatrixRow(
  standardId: string,
): StandardMatrixRow | undefined {
  return MASTER_STANDARDS_MATRIX.find((r) => r.standardId === standardId);
}

export function listUncertifiedStandards(): StandardMatrixRow[] {
  return MASTER_STANDARDS_MATRIX.filter((r) => r.certification !== "CERTIFIED");
}

export function listTraceabilityGaps(): RequirementTraceRow[] {
  return REQUIREMENT_TRACE_MATRIX.filter(
    (r) =>
      r.status === "NOT_RUN" ||
      r.status === "FAIL" ||
      r.status === "PARTIAL" ||
      Boolean(r.gap),
  );
}

/** Hard rule: no row may claim CERTIFIED while browser is NOT_RUN. */
export function matrixHasInvalidCertificationClaims(): string[] {
  const errors: string[] = [];
  for (const row of MASTER_STANDARDS_MATRIX) {
    if (
      row.certification === "CERTIFIED" &&
      (row.browser === "NOT_RUN" || row.browser === "FAIL")
    ) {
      errors.push(
        `${row.standardId}: CERTIFIED is invalid while browser=${row.browser}`,
      );
    }
    if (
      row.certification === "CERTIFIED" &&
      (row.unit === "FAIL" || row.unit === "NOT_RUN")
    ) {
      errors.push(
        `${row.standardId}: CERTIFIED is invalid while unit=${row.unit}`,
      );
    }
  }
  return errors;
}
