/**
 * Canonical Event Asset Registry definitions.
 * One definition per asset type — never Retreat Confirmation Email vs Workshop Confirmation Email.
 */

import { defineEventAsset } from "./defineAsset";
import type { EventAssetDefinition } from "./types";

const ALL = { mode: "all" as const };
const IN_PERSONISH = {
  mode: "exclude" as const,
  eventTypes: ["webinar" as const],
};
const HAS_SPEAKERS = {
  mode: "include" as const,
  eventTypes: [
    "conference" as const,
    "panel" as const,
    "multi_day" as const,
    "retreat" as const,
    "workshop" as const,
    "custom" as const,
  ],
};

export const EVENT_ASSET_DEFINITIONS: readonly EventAssetDefinition[] = [
  defineEventAsset({
    assetTypeId: "event_plan",
    canonicalName: "Event Plan",
    userFacingName: "Event Plan",
    description: "Master planning document for the gathering.",
    purpose: "Hold purpose, audience, outcomes, and the living plan.",
    category: "foundation",
    lifecyclePhases: ["discovery", "viability", "strategy", "planning"],
    eventSections: ["purpose", "audience", "outcomes", "event_type"],
    applicableEventTypes: ALL,
    requiredLevel: "core",
    recommendationRules: [
      {
        id: "on-start",
        description: "Created when the Event Creation Workspace opens.",
        afterSignals: ["ecosystem_started"],
        priority: 1,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["project-management", "leadership"],
    suggestedBoardAdvisors: [],
    creationMode: "native_structured_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx", "markdown"],
    contextRequirements: ["event_type", "title"],
    optionalContext: ["purpose", "audience", "outcomes"],
    dependencies: [],
    relatedAssetTypeIds: ["event_budget", "event_timeline", "agenda"],
    mayGenerateProjectTasks: false,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["parent_creation", "hub"],
    readinessContribution: [
      { areaId: "foundation", areaLabel: "Foundation", weight: 1 },
    ],
    templateId: "tpl-event-plan",
    createAssetRegistryId: "asset-event-plan",
    aliases: ["master plan", "event overview"],
  }),

  defineEventAsset({
    assetTypeId: "event_budget",
    canonicalName: "Event Budget",
    userFacingName: "Budget",
    description: "Planned, committed, and spent amounts for the event.",
    purpose: "Keep financial decisions visible and revisable.",
    category: "finance",
    lifecyclePhases: ["viability", "planning", "preparation", "follow_up"],
    eventSections: ["budget"],
    applicableEventTypes: ALL,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-outcomes",
        description: "Suggest after outcomes or budget conversation.",
        afterSignals: ["outcomes", "budget"],
        requireContext: ["outcomes"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "finance",
    supportingChamberMembers: ["events", "project-management"],
    suggestedBoardAdvisors: ["financial-stewardship", "strategy-director"],
    creationMode: "native_table_editor",
    editableInPlatform: true,
    exportFormats: ["xlsx", "csv", "pdf"],
    contextRequirements: ["outcomes"],
    optionalContext: ["dates", "venue", "format"],
    dependencies: [],
    relatedAssetTypeIds: ["vendor_list", "sponsor_package", "event_timeline"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      {
        title: "Confirm budget categories",
        when: "on_create",
        sectionId: "budget",
      },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports", "depends_on"],
    readinessContribution: [
      { areaId: "operations", areaLabel: "Operations", weight: 0.8 },
    ],
    templateId: "tpl-event-budget",
    createAssetRegistryId: "asset-budget",
    aliases: ["budget worksheet", "event finances"],
  }),

  defineEventAsset({
    assetTypeId: "event_timeline",
    canonicalName: "Event Timeline",
    userFacingName: "Timeline",
    description: "Milestones from now through follow-up.",
    purpose: "Make timing visible without overwhelming the member.",
    category: "foundation",
    lifecyclePhases: ["viability", "planning", "preparation", "delivery"],
    eventSections: ["dates"],
    applicableEventTypes: ALL,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-dates",
        description: "Suggest once dates or season are known.",
        afterSignals: ["dates"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "project-management",
    supportingChamberMembers: ["events"],
    suggestedBoardAdvisors: ["operations-capacity"],
    creationMode: "native_timeline_builder",
    editableInPlatform: true,
    exportFormats: ["pdf", "ics", "xlsx"],
    contextRequirements: ["dates"],
    optionalContext: ["venue", "outcomes"],
    dependencies: [],
    relatedAssetTypeIds: ["run_of_show", "day_of_checklist"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      { title: "Set key milestones", when: "on_create", sectionId: "dates" },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["timeline"],
    readinessContribution: [
      { areaId: "foundation", areaLabel: "Foundation", weight: 0.6 },
    ],
    templateId: "tpl-event-timeline",
    createAssetRegistryId: "asset-timeline",
    aliases: ["milestones", "planning calendar"],
  }),

  defineEventAsset({
    assetTypeId: "venue_comparison",
    canonicalName: "Venue Comparison",
    userFacingName: "Venue Comparison",
    description: "Compare venue or platform options against experience needs.",
    purpose: "Choose space that serves the outcome.",
    category: "vendors_operations",
    lifecyclePhases: ["viability", "planning"],
    eventSections: ["venue", "format"],
    applicableEventTypes: IN_PERSONISH,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "before-venue-lock",
        description: "Useful while still choosing a venue.",
        afterSignals: ["format", "audience"],
        priority: 3,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["finance"],
    suggestedBoardAdvisors: [],
    creationMode: "native_table_editor",
    editableInPlatform: true,
    exportFormats: ["xlsx", "pdf"],
    contextRequirements: ["format", "audience"],
    optionalContext: ["budget", "dates"],
    dependencies: [],
    relatedAssetTypeIds: ["venue_contract_notes"],
    mayGenerateProjectTasks: false,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "operations", areaLabel: "Operations", weight: 0.4 },
    ],
    templateId: "tpl-venue-comparison",
    createAssetRegistryId: "asset-venue-comparison",
    aliases: ["venue options"],
  }),

  defineEventAsset({
    assetTypeId: "venue_contract_notes",
    canonicalName: "Venue Contract Notes",
    userFacingName: "Venue Notes",
    description: "Requirements, holds, and contract details for the selected venue.",
    purpose: "Keep venue commitments findable.",
    category: "vendors_operations",
    lifecyclePhases: ["planning", "preparation"],
    eventSections: ["venue"],
    applicableEventTypes: IN_PERSONISH,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-venue",
        description: "Suggest after venue is selected.",
        afterSignals: ["venue"],
        priority: 1,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["finance", "client-relationships"],
    suggestedBoardAdvisors: ["financial-stewardship"],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx"],
    contextRequirements: ["venue"],
    optionalContext: ["dates", "budget"],
    dependencies: [],
    relatedAssetTypeIds: ["event_timeline", "vendor_list"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      { title: "Confirm venue hold", when: "on_create", sectionId: "venue" },
    ],
    cartographyEligible: false,
    cartographyRelationshipTypes: [],
    readinessContribution: [
      { areaId: "operations", areaLabel: "Operations", weight: 0.5 },
    ],
    templateId: "tpl-venue-notes",
    createAssetRegistryId: "asset-venue-notes",
    aliases: ["venue timeline", "contract notes"],
  }),

  defineEventAsset({
    assetTypeId: "agenda",
    canonicalName: "Agenda",
    userFacingName: "Agenda",
    description: "High-level flow of the experience.",
    purpose: "Give the gathering a clear arc.",
    category: "program",
    lifecyclePhases: ["experience_design", "planning", "preparation"],
    eventSections: ["agenda"],
    applicableEventTypes: ALL,
    requiredLevel: "core",
    recommendationRules: [
      {
        id: "after-foundation",
        description: "Suggest after outcomes and dates take shape.",
        afterSignals: ["outcomes", "dates"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: [
      "content",
      "leadership",
      "project-management",
      "learning",
    ],
    suggestedBoardAdvisors: [],
    creationMode: "native_timeline_builder",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx", "markdown"],
    contextRequirements: ["outcomes"],
    optionalContext: ["dates", "audience", "format"],
    dependencies: [],
    relatedAssetTypeIds: [
      "session_plans",
      "attendee_workbook",
      "run_of_show",
      "presentation_deck",
    ],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      { title: "Draft agenda blocks", when: "on_create", sectionId: "agenda" },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["program_hub", "feeds"],
    readinessContribution: [
      { areaId: "learning_materials", areaLabel: "Learning Materials", weight: 0.7 },
    ],
    templateId: "tpl-agenda",
    createAssetRegistryId: "asset-agenda",
    aliases: ["program", "schedule overview"],
  }),

  defineEventAsset({
    assetTypeId: "session_plans",
    canonicalName: "Session Plans",
    userFacingName: "Session Plans",
    description: "Detailed plans for individual sessions or breakouts.",
    purpose: "Turn the agenda into facilitatable sessions.",
    category: "program",
    lifecyclePhases: ["experience_design", "planning", "preparation"],
    eventSections: ["agenda"],
    applicableEventTypes: {
      mode: "include",
      eventTypes: ["retreat", "workshop", "conference", "multi_day", "custom"],
    },
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-agenda",
        description: "Suggest once an agenda exists.",
        afterSignals: ["agenda"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["learning", "content"],
    suggestedBoardAdvisors: [],
    creationMode: "native_structured_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx"],
    contextRequirements: ["outcomes"],
    optionalContext: ["agenda", "audience"],
    dependencies: [
      { assetTypeId: "agenda", strength: "recommended" },
    ],
    relatedAssetTypeIds: ["attendee_workbook", "presentation_deck"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["depends_on", "feeds"],
    readinessContribution: [
      { areaId: "learning_materials", areaLabel: "Learning Materials", weight: 0.9 },
    ],
    templateId: "tpl-session-plans",
    createAssetRegistryId: "asset-session-plans",
    aliases: ["session outlines", "breakout plans"],
  }),

  defineEventAsset({
    assetTypeId: "attendee_workbook",
    canonicalName: "Attendee Workbook",
    userFacingName: "Workbook",
    description: "Participant workbook or journal for the experience.",
    purpose: "Give attendees a place to learn and reflect.",
    category: "program",
    lifecyclePhases: ["experience_design", "preparation"],
    eventSections: ["agenda", "attendee_experience"],
    applicableEventTypes: {
      mode: "include",
      eventTypes: ["retreat", "workshop", "conference", "multi_day", "custom"],
    },
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-agenda",
        description: "Suggest when the program is taking shape.",
        afterSignals: ["agenda", "outcomes"],
        priority: 3,
      },
    ],
    primaryChamberOwner: "content",
    supportingChamberMembers: ["events", "learning", "creative-studio"],
    suggestedBoardAdvisors: [],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx"],
    contextRequirements: ["outcomes", "audience"],
    optionalContext: ["agenda"],
    dependencies: [
      { assetTypeId: "agenda", strength: "recommended" },
    ],
    relatedAssetTypeIds: ["session_plans", "presentation_deck"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      {
        title: "Draft workbook exercises",
        when: "on_create",
        sectionId: "attendee_experience",
      },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports", "feeds"],
    readinessContribution: [
      { areaId: "learning_materials", areaLabel: "Learning Materials", weight: 1 },
    ],
    templateId: "tpl-attendee-workbook",
    createAssetRegistryId: null,
    aliases: ["participant workbook", "journal"],
  }),

  defineEventAsset({
    assetTypeId: "presentation_deck",
    canonicalName: "Presentation Deck",
    userFacingName: "Presentation",
    description: "Slides or visual presentation for sessions.",
    purpose: "Support delivery of key content.",
    category: "program",
    lifecyclePhases: ["preparation", "delivery"],
    eventSections: ["agenda", "speakers", "technology"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-sessions",
        description: "Suggest when sessions or speakers are defined.",
        afterSignals: ["agenda", "speakers"],
        priority: 4,
      },
    ],
    primaryChamberOwner: "creative-studio",
    supportingChamberMembers: ["content", "events", "presentations"],
    suggestedBoardAdvisors: [],
    creationMode: "native_presentation_builder",
    editableInPlatform: true,
    exportFormats: ["pptx", "pdf"],
    contextRequirements: ["outcomes"],
    optionalContext: ["agenda", "audience"],
    dependencies: [
      { assetTypeId: "agenda", strength: "soft" },
    ],
    relatedAssetTypeIds: ["session_plans", "attendee_workbook"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "learning_materials", areaLabel: "Learning Materials", weight: 0.5 },
    ],
    templateId: "tpl-presentation-deck",
    createAssetRegistryId: null,
    status: "experimental",
    aliases: ["slides", "deck"],
  }),

  defineEventAsset({
    assetTypeId: "registration_form",
    canonicalName: "Registration Form",
    userFacingName: "Registration Form",
    description: "Collect attendee sign-ups and essential details.",
    purpose: "Open a clear path for people to join.",
    category: "registration_attendance",
    lifecyclePhases: ["planning", "preparation", "delivery"],
    eventSections: ["registration"],
    applicableEventTypes: ALL,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-venue-dates",
        description: "Common next step after venue and dates.",
        afterSignals: ["venue", "dates"],
        priority: 1,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["content", "marketing", "systems"],
    suggestedBoardAdvisors: [],
    creationMode: "native_form_builder",
    editableInPlatform: true,
    exportFormats: ["pdf", "html", "json"],
    contextRequirements: ["title", "outcomes"],
    optionalContext: ["dates", "venue", "audience"],
    dependencies: [],
    relatedAssetTypeIds: [
      "registration_confirmation_email",
      "registration_reminder_email",
      "landing_page",
    ],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      {
        title: "Open registration",
        when: "on_approve",
        sectionId: "registration",
      },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["registration_hub", "feeds"],
    readinessContribution: [
      { areaId: "registration", areaLabel: "Registration", weight: 1 },
    ],
    templateId: "tpl-registration-form",
    createAssetRegistryId: "asset-registration-form",
    aliases: ["signup form", "RSVP form"],
  }),

  defineEventAsset({
    assetTypeId: "registration_confirmation_email",
    canonicalName: "Registration Confirmation Email",
    userFacingName: "Confirmation Email",
    description:
      "Confirms registration and sets expectations. One canonical definition for all event types.",
    purpose: "Reassure registrants and reduce no-shows from confusion.",
    category: "marketing_communications",
    lifecyclePhases: ["planning", "preparation", "delivery"],
    eventSections: ["registration", "communications"],
    applicableEventTypes: ALL,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-registration",
        description: "Suggest once registration is taking shape.",
        afterSignals: ["registration"],
        priority: 1,
      },
    ],
    primaryChamberOwner: "content",
    supportingChamberMembers: [
      "marketing",
      "events",
      "client-relationships",
    ],
    suggestedBoardAdvisors: [],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["html", "markdown", "pdf"],
    contextRequirements: ["title"],
    optionalContext: ["dates", "venue", "audience"],
    dependencies: [
      { assetTypeId: "registration_form", strength: "recommended" },
    ],
    relatedAssetTypeIds: [
      "registration_reminder_email",
      "welcome_guide",
      "thank_you_message",
    ],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: false,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "registration", areaLabel: "Registration", weight: 0.6 },
    ],
    templateId: "tpl-registration-confirmation-email",
    createAssetRegistryId: "asset-confirmation-email",
    aliases: [
      "confirmation email",
      "retreat confirmation email",
      "workshop confirmation email",
      "conference confirmation email",
      "webinar confirmation email",
    ],
  }),

  defineEventAsset({
    assetTypeId: "registration_reminder_email",
    canonicalName: "Registration Reminder Email",
    userFacingName: "Reminder Email",
    description: "Remind attendees before the event. Canonical across event types.",
    purpose: "Bring people back to the gathering at the right moment.",
    category: "marketing_communications",
    lifecyclePhases: ["preparation", "delivery"],
    eventSections: ["registration", "communications"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-registration-dates",
        description: "Suggest when registration and dates exist.",
        afterSignals: ["registration", "dates"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "content",
    supportingChamberMembers: ["marketing", "events"],
    suggestedBoardAdvisors: [],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["html", "markdown"],
    contextRequirements: ["dates", "title"],
    optionalContext: ["venue", "format"],
    dependencies: [
      { assetTypeId: "registration_form", strength: "recommended" },
    ],
    relatedAssetTypeIds: ["registration_confirmation_email", "packing_list"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      {
        title: "Schedule reminder send",
        when: "on_approve",
        sectionId: "communications",
      },
    ],
    cartographyEligible: false,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "registration", areaLabel: "Registration", weight: 0.4 },
    ],
    templateId: "tpl-registration-reminder-email",
    createAssetRegistryId: "asset-reminder-email",
    aliases: ["reminder email", "day-before email"],
  }),

  defineEventAsset({
    assetTypeId: "landing_page",
    canonicalName: "Event Landing Page",
    userFacingName: "Landing Page",
    description: "Public page that explains the event and invites registration.",
    purpose: "Give people one clear place to understand and join.",
    category: "marketing_communications",
    lifecyclePhases: ["planning", "preparation"],
    eventSections: ["marketing", "registration"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-outcomes-audience",
        description: "Suggest when purpose and audience are clear.",
        afterSignals: ["outcomes", "audience"],
        priority: 3,
      },
    ],
    primaryChamberOwner: "marketing",
    supportingChamberMembers: ["content", "events"],
    suggestedBoardAdvisors: [],
    creationMode: "native_structured_editor",
    editableInPlatform: true,
    exportFormats: ["html", "pdf", "markdown"],
    contextRequirements: ["title", "outcomes", "audience"],
    optionalContext: ["dates", "venue", "format"],
    dependencies: [
      { assetTypeId: "registration_form", strength: "soft" },
    ],
    relatedAssetTypeIds: [
      "registration_form",
      "marketing_email_sequence",
    ],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["marketing_hub", "feeds"],
    readinessContribution: [
      { areaId: "marketing", areaLabel: "Marketing", weight: 0.8 },
    ],
    templateId: "tpl-event-landing-page",
    createAssetRegistryId: null,
    aliases: ["event page", "registration page"],
  }),

  defineEventAsset({
    assetTypeId: "marketing_email_sequence",
    canonicalName: "Event Marketing Email Sequence",
    userFacingName: "Email Sequence",
    description: "Invitation and nurture emails for the event.",
    purpose: "Invite the right people without starting from scratch each time.",
    category: "marketing_communications",
    lifecyclePhases: ["planning", "preparation"],
    eventSections: ["marketing", "communications"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-landing",
        description: "Suggest when marketing or registration is underway.",
        afterSignals: ["registration", "marketing"],
        priority: 3,
      },
    ],
    primaryChamberOwner: "marketing",
    supportingChamberMembers: ["content", "events"],
    suggestedBoardAdvisors: [],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["html", "markdown"],
    contextRequirements: ["audience", "outcomes"],
    optionalContext: ["dates", "title"],
    dependencies: [],
    relatedAssetTypeIds: ["landing_page", "registration_form"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["feeds", "supports"],
    readinessContribution: [
      { areaId: "marketing", areaLabel: "Marketing", weight: 0.7 },
    ],
    templateId: "tpl-event-email-sequence",
    createAssetRegistryId: "asset-email-sequence",
    aliases: ["invite sequence", "nurture emails"],
  }),

  defineEventAsset({
    assetTypeId: "speaker_packet",
    canonicalName: "Speaker Packet",
    userFacingName: "Speaker Packet",
    description: "Information packet for speakers and facilitators.",
    purpose: "Brief speakers without repeating yourself.",
    category: "people_speakers",
    lifecyclePhases: ["planning", "preparation"],
    eventSections: ["speakers"],
    applicableEventTypes: HAS_SPEAKERS,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "when-speakers",
        description: "Suggest when inviting speakers.",
        afterSignals: ["speakers", "agenda"],
        priority: 1,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: [
      "content",
      "marketing",
      "client-relationships",
      "leadership",
    ],
    suggestedBoardAdvisors: [],
    creationMode: "native_structured_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx"],
    contextRequirements: ["outcomes", "title"],
    optionalContext: ["dates", "venue", "agenda"],
    dependencies: [
      { assetTypeId: "agenda", strength: "soft" },
    ],
    relatedAssetTypeIds: ["speaker_agreement", "speaker_bio", "presentation_deck"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      { title: "Send speaker packet", when: "on_approve", sectionId: "speakers" },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports", "feeds"],
    readinessContribution: [
      { areaId: "program", areaLabel: "Program", weight: 0.7 },
    ],
    templateId: "tpl-speaker-packet",
    createAssetRegistryId: "asset-speaker-packet",
    aliases: ["speaker information packet", "facilitator brief"],
  }),

  defineEventAsset({
    assetTypeId: "speaker_agreement",
    canonicalName: "Speaker Agreement",
    userFacingName: "Speaker Agreement",
    description: "Agreement covering expectations, logistics, and compensation.",
    purpose: "Clarify speaker commitments kindly and clearly.",
    category: "people_speakers",
    lifecyclePhases: ["planning", "preparation"],
    eventSections: ["speakers"],
    applicableEventTypes: HAS_SPEAKERS,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "when-speakers",
        description: "Suggest when speakers are being confirmed.",
        afterSignals: ["speakers"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["finance", "client-relationships"],
    suggestedBoardAdvisors: ["values-trust"],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx"],
    contextRequirements: ["title"],
    optionalContext: ["dates", "budget"],
    dependencies: [
      { assetTypeId: "speaker_packet", strength: "soft" },
    ],
    relatedAssetTypeIds: ["speaker_packet", "speaker_bio"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: false,
    cartographyRelationshipTypes: [],
    readinessContribution: [
      { areaId: "program", areaLabel: "Program", weight: 0.3 },
    ],
    templateId: "tpl-speaker-agreement",
    createAssetRegistryId: "asset-speaker-agreement",
    aliases: ["speaker contract"],
  }),

  defineEventAsset({
    assetTypeId: "speaker_bio",
    canonicalName: "Speaker Bio",
    userFacingName: "Speaker Bios",
    description: "Collected bios for programs, pages, and introductions.",
    purpose: "Introduce speakers without scrambling later.",
    category: "people_speakers",
    lifecyclePhases: ["planning", "preparation"],
    eventSections: ["speakers", "marketing"],
    applicableEventTypes: HAS_SPEAKERS,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "when-speakers",
        description: "Suggest when speakers are invited.",
        afterSignals: ["speakers"],
        priority: 3,
      },
    ],
    primaryChamberOwner: "content",
    supportingChamberMembers: ["events", "marketing"],
    suggestedBoardAdvisors: [],
    creationMode: "native_structured_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "markdown"],
    contextRequirements: [],
    optionalContext: ["speakers", "audience"],
    dependencies: [],
    relatedAssetTypeIds: ["speaker_packet", "landing_page"],
    mayGenerateProjectTasks: false,
    taskTemplates: [],
    cartographyEligible: false,
    cartographyRelationshipTypes: [],
    readinessContribution: [
      { areaId: "program", areaLabel: "Program", weight: 0.2 },
    ],
    templateId: "tpl-speaker-bio",
    createAssetRegistryId: null,
    aliases: ["bios", "speaker profiles"],
  }),

  defineEventAsset({
    assetTypeId: "vendor_list",
    canonicalName: "Vendor List",
    userFacingName: "Vendor Checklist",
    description: "Vendors, contacts, and status for the event.",
    purpose: "Keep vendor relationships organized.",
    category: "vendors_operations",
    lifecyclePhases: ["planning", "preparation", "delivery"],
    eventSections: ["vendors", "venue"],
    applicableEventTypes: IN_PERSONISH,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-venue",
        description: "Suggest after venue is selected.",
        afterSignals: ["venue"],
        priority: 1,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["finance", "project-management"],
    suggestedBoardAdvisors: ["operations-capacity"],
    creationMode: "native_table_editor",
    editableInPlatform: true,
    exportFormats: ["xlsx", "csv", "pdf"],
    contextRequirements: ["venue"],
    optionalContext: ["budget", "dates"],
    dependencies: [],
    relatedAssetTypeIds: ["vendor_brief", "event_budget"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      { title: "Confirm key vendors", when: "on_create", sectionId: "vendors" },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "operations", areaLabel: "Operations", weight: 0.6 },
    ],
    templateId: "tpl-vendor-list",
    createAssetRegistryId: "asset-vendor-list",
    aliases: ["vendor checklist", "vendor tracker"],
  }),

  defineEventAsset({
    assetTypeId: "vendor_brief",
    canonicalName: "Vendor Brief",
    userFacingName: "Vendor Brief",
    description: "Brief for a specific vendor covering scope and logistics.",
    purpose: "Tell vendors what success looks like.",
    category: "vendors_operations",
    lifecyclePhases: ["planning", "preparation"],
    eventSections: ["vendors"],
    applicableEventTypes: IN_PERSONISH,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "with-vendors",
        description: "Suggest when vendors are being engaged.",
        afterSignals: ["vendors", "venue"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["content", "finance"],
    suggestedBoardAdvisors: [],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx"],
    contextRequirements: ["title"],
    optionalContext: ["dates", "venue", "budget"],
    dependencies: [
      { assetTypeId: "vendor_list", strength: "soft" },
    ],
    relatedAssetTypeIds: ["vendor_list", "run_of_show"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: false,
    cartographyRelationshipTypes: [],
    readinessContribution: [
      { areaId: "operations", areaLabel: "Operations", weight: 0.3 },
    ],
    templateId: "tpl-vendor-brief",
    createAssetRegistryId: null,
    aliases: ["vendor agreement notes", "vendor scope"],
  }),

  defineEventAsset({
    assetTypeId: "volunteer_guide",
    canonicalName: "Volunteer Guide",
    userFacingName: "Volunteer Handbook",
    description: "Guide for volunteers covering roles, culture, and logistics.",
    purpose: "Help volunteers feel prepared and welcomed.",
    category: "staffing_volunteers",
    lifecyclePhases: ["planning", "preparation", "delivery"],
    eventSections: ["volunteers", "staff"],
    applicableEventTypes: {
      mode: "include",
      eventTypes: [
        "retreat",
        "conference",
        "church_community",
        "multi_day",
        "networking",
        "custom",
      ],
    },
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "when-volunteers",
        description: "Suggest when volunteers are part of the plan.",
        afterSignals: ["volunteers", "venue"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["people-culture", "content"],
    suggestedBoardAdvisors: ["values-trust"],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx"],
    contextRequirements: ["title"],
    optionalContext: ["venue", "dates", "agenda"],
    dependencies: [],
    relatedAssetTypeIds: ["volunteer_schedule", "run_of_show"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "staffing", areaLabel: "Staffing", weight: 0.8 },
    ],
    templateId: "tpl-volunteer-guide",
    createAssetRegistryId: "asset-volunteer-handbook",
    aliases: ["volunteer handbook", "volunteer packet"],
  }),

  defineEventAsset({
    assetTypeId: "volunteer_schedule",
    canonicalName: "Volunteer Schedule",
    userFacingName: "Volunteer Schedule",
    description: "Shifts and assignments for volunteers.",
    purpose: "Make coverage clear without chaos.",
    category: "staffing_volunteers",
    lifecyclePhases: ["preparation", "delivery"],
    eventSections: ["volunteers", "agenda"],
    applicableEventTypes: {
      mode: "include",
      eventTypes: [
        "retreat",
        "conference",
        "church_community",
        "multi_day",
        "custom",
      ],
    },
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-volunteers-agenda",
        description: "Suggest when volunteers and agenda exist.",
        afterSignals: ["volunteers", "agenda"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["project-management", "people-culture"],
    suggestedBoardAdvisors: ["operations-capacity"],
    creationMode: "native_table_editor",
    editableInPlatform: true,
    exportFormats: ["xlsx", "pdf"],
    contextRequirements: ["agenda"],
    optionalContext: ["volunteers", "dates"],
    dependencies: [
      { assetTypeId: "volunteer_guide", strength: "soft" },
      { assetTypeId: "agenda", strength: "recommended" },
    ],
    relatedAssetTypeIds: ["volunteer_guide", "run_of_show"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["depends_on"],
    readinessContribution: [
      { areaId: "staffing", areaLabel: "Staffing", weight: 0.6 },
    ],
    templateId: "tpl-volunteer-schedule",
    createAssetRegistryId: "asset-volunteer-schedule",
    aliases: ["shift schedule"],
  }),

  defineEventAsset({
    assetTypeId: "run_of_show",
    canonicalName: "Run of Show",
    userFacingName: "Run of Show",
    description: "Minute-by-minute production plan for delivery.",
    purpose: "Keep the day coordinated for the team.",
    category: "delivery_day_of",
    lifecyclePhases: ["preparation", "delivery"],
    eventSections: ["run_of_show", "production", "agenda"],
    applicableEventTypes: ALL,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-agenda-venue",
        description: "Suggest when agenda and venue are known.",
        afterSignals: ["agenda", "venue"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["project-management", "systems"],
    suggestedBoardAdvisors: ["operations-capacity"],
    creationMode: "native_timeline_builder",
    editableInPlatform: true,
    exportFormats: ["pdf", "xlsx"],
    contextRequirements: ["agenda"],
    optionalContext: ["venue", "technology", "speakers"],
    dependencies: [
      { assetTypeId: "agenda", strength: "recommended" },
    ],
    relatedAssetTypeIds: ["technology_plan", "day_of_checklist", "volunteer_schedule"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      {
        title: "Finalize run of show",
        when: "on_create",
        sectionId: "run_of_show",
      },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["delivery_hub", "depends_on"],
    readinessContribution: [
      { areaId: "delivery", areaLabel: "Delivery", weight: 1 },
    ],
    templateId: "tpl-run-of-show",
    createAssetRegistryId: "asset-run-of-show",
    aliases: ["show flow", "day-of timeline"],
  }),

  defineEventAsset({
    assetTypeId: "technology_plan",
    canonicalName: "Technology Plan",
    userFacingName: "Technology Plan",
    description: "AV, streaming, tools, and tech checklist.",
    purpose: "Prevent tech surprises on the day.",
    category: "technology_production",
    lifecyclePhases: ["planning", "preparation", "delivery"],
    eventSections: ["technology", "production"],
    applicableEventTypes: ALL,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-format-venue",
        description: "Suggest for virtual/hybrid or when tech is named.",
        afterSignals: ["technology", "venue", "format"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "systems",
    supportingChamberMembers: ["events", "presentations"],
    suggestedBoardAdvisors: ["technology-future"],
    creationMode: "native_checklist_builder",
    editableInPlatform: true,
    exportFormats: ["pdf", "xlsx", "markdown"],
    contextRequirements: ["format"],
    optionalContext: ["venue", "agenda"],
    dependencies: [],
    relatedAssetTypeIds: ["run_of_show", "presentation_deck"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      {
        title: "Confirm tech setup",
        when: "on_create",
        sectionId: "technology",
      },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "delivery", areaLabel: "Delivery", weight: 0.7 },
    ],
    templateId: "tpl-technology-plan",
    createAssetRegistryId: "asset-tech-checklist",
    aliases: ["tech checklist", "AV plan", "streaming plan"],
  }),

  defineEventAsset({
    assetTypeId: "accessibility_plan",
    canonicalName: "Accessibility Plan",
    userFacingName: "Accessibility Plan",
    description: "Access, inclusion, and accommodation plan.",
    purpose: "Make the gathering welcoming for more people.",
    category: "experience_hospitality",
    lifecyclePhases: ["planning", "preparation"],
    eventSections: ["accessibility", "audience", "venue"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-venue-audience",
        description: "Suggest after venue and audience are known.",
        afterSignals: ["venue", "audience"],
        priority: 3,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["wellness", "people-culture"],
    suggestedBoardAdvisors: ["values-trust"],
    creationMode: "native_checklist_builder",
    editableInPlatform: true,
    exportFormats: ["pdf", "markdown"],
    contextRequirements: ["audience"],
    optionalContext: ["venue", "format"],
    dependencies: [],
    relatedAssetTypeIds: ["welcome_guide", "registration_form"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "attendee_experience", areaLabel: "Attendee Experience", weight: 0.5 },
    ],
    templateId: "tpl-accessibility-plan",
    createAssetRegistryId: "asset-accessibility-plan",
    aliases: ["access plan", "inclusion plan"],
  }),

  defineEventAsset({
    assetTypeId: "emergency_plan",
    canonicalName: "Emergency Plan",
    userFacingName: "Emergency Plan",
    description: "Safety, contingencies, and emergency contacts.",
    purpose: "Be ready if something goes wrong.",
    category: "risk_safety",
    lifecyclePhases: ["planning", "preparation", "delivery"],
    eventSections: ["safety", "contingencies", "venue"],
    applicableEventTypes: IN_PERSONISH,
    requiredLevel: "conditional",
    recommendationRules: [
      {
        id: "after-venue",
        description: "Suggest after venue is selected.",
        afterSignals: ["venue"],
        priority: 3,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["project-management", "leadership"],
    suggestedBoardAdvisors: ["operations-capacity", "devils-advocate"],
    creationMode: "native_checklist_builder",
    editableInPlatform: true,
    exportFormats: ["pdf"],
    contextRequirements: ["venue"],
    optionalContext: ["dates", "staff"],
    dependencies: [],
    relatedAssetTypeIds: ["run_of_show", "day_of_checklist"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: false,
    cartographyRelationshipTypes: [],
    readinessContribution: [
      { areaId: "delivery", areaLabel: "Delivery", weight: 0.4 },
    ],
    templateId: "tpl-emergency-plan",
    createAssetRegistryId: "asset-emergency-plan",
    aliases: ["safety plan", "contingency plan"],
  }),

  defineEventAsset({
    assetTypeId: "welcome_guide",
    canonicalName: "Welcome Guide",
    userFacingName: "Welcome Guide",
    description: "Orient attendees before they arrive.",
    purpose: "Reduce arrival anxiety and unanswered questions.",
    category: "experience_hospitality",
    lifecyclePhases: ["preparation", "delivery"],
    eventSections: ["attendee_experience", "hospitality", "communications"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-venue-audience",
        description: "Suggest after venue and audience are known.",
        afterSignals: ["venue", "audience"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["content", "wellness"],
    suggestedBoardAdvisors: [],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx"],
    contextRequirements: ["title"],
    optionalContext: ["venue", "dates", "audience"],
    dependencies: [],
    relatedAssetTypeIds: ["packing_list", "registration_confirmation_email"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "attendee_experience", areaLabel: "Attendee Experience", weight: 0.7 },
    ],
    templateId: "tpl-welcome-guide",
    createAssetRegistryId: "asset-welcome-guide",
    aliases: ["attendee guide", "arrival guide"],
  }),

  defineEventAsset({
    assetTypeId: "packing_list",
    canonicalName: "Packing List",
    userFacingName: "Packing List",
    description: "What attendees should bring.",
    purpose: "Help people arrive prepared.",
    category: "experience_hospitality",
    lifecyclePhases: ["preparation"],
    eventSections: ["attendee_experience", "supplies"],
    applicableEventTypes: {
      mode: "include",
      eventTypes: ["retreat", "multi_day", "workshop", "conference", "custom"],
    },
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-venue-format",
        description: "Suggest for in-person / multi-day gatherings.",
        afterSignals: ["venue", "format"],
        priority: 3,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["content"],
    suggestedBoardAdvisors: [],
    creationMode: "native_checklist_builder",
    editableInPlatform: true,
    exportFormats: ["pdf", "markdown"],
    contextRequirements: ["format"],
    optionalContext: ["venue", "dates"],
    dependencies: [],
    relatedAssetTypeIds: ["welcome_guide"],
    mayGenerateProjectTasks: false,
    taskTemplates: [],
    cartographyEligible: false,
    cartographyRelationshipTypes: [],
    readinessContribution: [
      { areaId: "attendee_experience", areaLabel: "Attendee Experience", weight: 0.3 },
    ],
    templateId: "tpl-packing-list",
    createAssetRegistryId: "asset-packing-list",
    aliases: ["what to bring"],
  }),

  defineEventAsset({
    assetTypeId: "day_of_checklist",
    canonicalName: "Day-of Checklist",
    userFacingName: "Day-of Checklist",
    description: "Check-in, supplies, and day-of operational checklist.",
    purpose: "Keep delivery calm and complete.",
    category: "delivery_day_of",
    lifecyclePhases: ["preparation", "delivery"],
    eventSections: ["run_of_show", "supplies", "production"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "near-delivery",
        description: "Suggest as delivery approaches.",
        afterSignals: ["agenda", "venue"],
        priority: 3,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["project-management"],
    suggestedBoardAdvisors: ["operations-capacity"],
    creationMode: "native_checklist_builder",
    editableInPlatform: true,
    exportFormats: ["pdf", "markdown"],
    contextRequirements: [],
    optionalContext: ["venue", "agenda", "technology"],
    dependencies: [
      { assetTypeId: "run_of_show", strength: "soft" },
    ],
    relatedAssetTypeIds: ["run_of_show", "technology_plan"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: false,
    cartographyRelationshipTypes: [],
    readinessContribution: [
      { areaId: "delivery", areaLabel: "Delivery", weight: 0.5 },
    ],
    templateId: "tpl-day-of-checklist",
    createAssetRegistryId: "asset-checklist",
    aliases: ["check-in checklist", "supplies checklist"],
  }),

  defineEventAsset({
    assetTypeId: "feedback_survey",
    canonicalName: "Feedback Survey",
    userFacingName: "Feedback Survey",
    description: "Evaluation / feedback form for attendees.",
    purpose: "Learn what worked without losing the moment.",
    category: "follow_up_learning",
    lifecyclePhases: ["delivery", "follow_up", "debrief_reuse"],
    eventSections: ["measurement", "post_event_follow_up"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "near-close",
        description: "Suggest as the event nears delivery or close.",
        afterSignals: ["agenda", "follow_up"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["data-analytics", "content"],
    suggestedBoardAdvisors: [],
    creationMode: "native_form_builder",
    editableInPlatform: true,
    exportFormats: ["pdf", "csv", "html"],
    contextRequirements: ["outcomes"],
    optionalContext: ["audience"],
    dependencies: [],
    relatedAssetTypeIds: ["debrief_report", "thank_you_message"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      {
        title: "Send feedback survey",
        when: "on_approve",
        sectionId: "measurement",
      },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["feeds"],
    readinessContribution: [
      { areaId: "follow_up", areaLabel: "Follow-up", weight: 0.6 },
    ],
    templateId: "tpl-feedback-survey",
    createAssetRegistryId: null,
    aliases: ["evaluation form", "post-event survey"],
  }),

  defineEventAsset({
    assetTypeId: "thank_you_message",
    canonicalName: "Thank You Message",
    userFacingName: "Thank You Email",
    description: "Thank-you note to attendees, speakers, or partners.",
    purpose: "Close the relationship warmly.",
    category: "follow_up_learning",
    lifecyclePhases: ["follow_up", "breakdown_closure"],
    eventSections: ["post_event_follow_up", "communications"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-delivery",
        description: "Suggest after delivery or follow-up begins.",
        afterSignals: ["follow_up", "delivery"],
        priority: 1,
      },
    ],
    primaryChamberOwner: "content",
    supportingChamberMembers: ["events", "client-relationships", "marketing"],
    suggestedBoardAdvisors: [],
    creationMode: "native_rich_text_editor",
    editableInPlatform: true,
    exportFormats: ["html", "markdown"],
    contextRequirements: ["title"],
    optionalContext: ["outcomes", "audience"],
    dependencies: [],
    relatedAssetTypeIds: ["feedback_survey", "debrief_report"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: false,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "follow_up", areaLabel: "Follow-up", weight: 0.5 },
    ],
    templateId: "tpl-thank-you-message",
    createAssetRegistryId: "asset-thank-you-email",
    aliases: ["thank you email", "appreciation note"],
  }),

  defineEventAsset({
    assetTypeId: "debrief_report",
    canonicalName: "Debrief Report",
    userFacingName: "Debrief",
    description: "After-action notes, lessons, and reuse decisions.",
    purpose: "Capture wisdom so the next gathering starts wiser.",
    category: "follow_up_learning",
    lifecyclePhases: ["follow_up", "debrief_reuse"],
    eventSections: ["measurement", "archive_and_reuse", "post_event_follow_up"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-follow-up",
        description: "Suggest during follow-up and debrief.",
        afterSignals: ["follow_up", "debrief"],
        priority: 1,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["leadership", "project-management"],
    suggestedBoardAdvisors: ["strategy-director", "founder-advocate"],
    creationMode: "native_structured_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx", "markdown"],
    contextRequirements: ["outcomes"],
    optionalContext: ["audience", "budget"],
    dependencies: [
      { assetTypeId: "feedback_survey", strength: "soft" },
    ],
    relatedAssetTypeIds: ["archive_package", "feedback_survey"],
    mayGenerateProjectTasks: true,
    taskTemplates: [
      {
        title: "Complete event debrief",
        when: "on_create",
        sectionId: "measurement",
      },
    ],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["feeds", "archive"],
    readinessContribution: [
      { areaId: "follow_up", areaLabel: "Follow-up", weight: 0.8 },
    ],
    templateId: "tpl-debrief-report",
    createAssetRegistryId: "asset-debrief",
    aliases: ["lessons learned", "after-action report"],
  }),

  defineEventAsset({
    assetTypeId: "sponsor_package",
    canonicalName: "Sponsor Package",
    userFacingName: "Sponsor Package",
    description: "Sponsorship offerings and benefits.",
    purpose: "Invite partners with clarity.",
    category: "finance",
    lifecyclePhases: ["strategy", "planning"],
    eventSections: ["sponsors", "budget", "marketing"],
    applicableEventTypes: {
      mode: "include",
      eventTypes: ["conference", "multi_day", "networking", "launch", "custom"],
    },
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "when-sponsors",
        description: "Suggest when sponsors are in scope.",
        afterSignals: ["sponsors", "budget"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "marketing",
    supportingChamberMembers: ["finance", "events", "partnerships"],
    suggestedBoardAdvisors: ["financial-stewardship", "values-trust"],
    creationMode: "native_structured_editor",
    editableInPlatform: true,
    exportFormats: ["pdf", "docx"],
    contextRequirements: ["outcomes", "audience"],
    optionalContext: ["budget", "dates"],
    dependencies: [],
    relatedAssetTypeIds: ["event_budget", "landing_page"],
    mayGenerateProjectTasks: true,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["supports"],
    readinessContribution: [
      { areaId: "operations", areaLabel: "Operations", weight: 0.4 },
    ],
    templateId: "tpl-sponsor-package",
    createAssetRegistryId: "asset-sponsor-package",
    aliases: ["sponsorship deck", "partner package"],
  }),

  defineEventAsset({
    assetTypeId: "archive_package",
    canonicalName: "Event Archive",
    userFacingName: "Archive",
    description: "Archive package for reuse and history.",
    purpose: "Preserve what should live beyond this event.",
    category: "archive_reuse",
    lifecyclePhases: ["debrief_reuse"],
    eventSections: ["archive_and_reuse"],
    applicableEventTypes: ALL,
    requiredLevel: "optional",
    recommendationRules: [
      {
        id: "after-debrief",
        description: "Suggest after debrief.",
        afterSignals: ["debrief", "archive"],
        priority: 2,
      },
    ],
    primaryChamberOwner: "events",
    supportingChamberMembers: ["knowledge-management"],
    suggestedBoardAdvisors: [],
    creationMode: "reference_only",
    editableInPlatform: false,
    exportFormats: ["pdf", "json"],
    contextRequirements: [],
    optionalContext: ["outcomes"],
    dependencies: [
      { assetTypeId: "debrief_report", strength: "soft" },
    ],
    relatedAssetTypeIds: ["debrief_report", "event_plan"],
    mayGenerateProjectTasks: false,
    taskTemplates: [],
    cartographyEligible: true,
    cartographyRelationshipTypes: ["archive"],
    readinessContribution: [
      { areaId: "follow_up", areaLabel: "Follow-up", weight: 0.3 },
    ],
    templateId: "tpl-event-archive",
    createAssetRegistryId: "asset-archive",
    aliases: ["event archive", "reuse package"],
  }),
];
