/**
 * Canonical place records — synced from SPARK_ESTATE_CANONICAL_REGISTRY.md.
 * @internal Import via canonicalEstateRegistry.ts only.
 */

import type { CanonicalEstatePlace } from "./canonicalEstateRegistryTypes";

export const CANONICAL_ESTATE_PLACES: readonly CanonicalEstatePlace[] = [
  // —— Living Places ——
  {
    id: "welcome-home",
    officialName: "Welcome Home™",
    category: "living-place",
    primaryFeeling: "Belonging, warmth, orientation, hope",
    backgroundImage: null,
    aliases: [
      "welcome home",
      "go home",
      "take me home",
      "back home",
      "I'm home",
    ],
    arrivalBehavior: "threshold",
    conversationStyle: "open-presence",
    permanentObjects: [
      "Front entry",
      "Coat hooks",
      "Soft light",
      "Guidebook™ on side table",
      "Folded Estate Map™ (corner, optional)",
    ],
    seasonalObjects: [
      "Wreath (Christmas)",
      "Porch lanterns (winter)",
      "Spring planters",
    ],
    interactiveObjects: ["Map (folded)", "Guidebook", "Continue conversation"],
    relatedPlaces: ["sunroom", "gardens", "greenhouse", "main-hallway"],
    status: "needs-asset",
    suggestionProfiles: ["orient", "uncertain"],
    expansionNotes:
      "Kinsey at threshold (optional); evening porch light; never dashboard tiles",
  },
  {
    id: "sunroom",
    officialName: "Sunroom",
    category: "living-place",
    primaryFeeling: "Warmth, belonging, unhurried welcome",
    backgroundImage: "/backgrounds/sunroom-background.png",
    aliases: ["sunroom", "welcome room", "Shari's sunroom"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: [
      "Shari's chair",
      "Pond view",
      "Spark mugs",
      "Plants in light",
    ],
    seasonalObjects: ["Brighter morning wash (summer)", "Frost on glass (winter)"],
    interactiveObjects: [
      "Letter from Shari (first visits, optional)",
      "Conversation",
    ],
    relatedPlaces: ["welcome-home", "seat-at-pond"],
    status: "live",
    expansionNotes: "Voice welcome optional; never product explainer",
  },
  {
    id: "conservatory",
    officialName: "The Conservatory™",
    category: "living-place",
    primaryFeeling: "Restoration, clarity, gentle thinking",
    backgroundImage: "/backgrounds/butterfly-conservatory.webp",
    aliases: [
      "conservatory",
      "the conservatory",
      "quiet glass room",
      "butterfly conservatory",
      "the butterfly conservatory",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Glass walls", "Butterflies", "Garden views", "Bench"],
    seasonalObjects: ["Rain on glass (spring)", "Dusk glow (autumn)"],
    interactiveObjects: [
      "Ambience toggle",
      "Journal nearby (walk to Journal™ if asked)",
    ],
    relatedPlaces: ["clear-my-mind", "journal", "peaceful-places"],
    status: "planned",
    suggestionProfiles: ["overwhelmed", "think"],
    expansionNotes:
      "Shares atmosphere with Clear My Mind™ — distinct purpose; never merge IDs",
  },
  {
    id: "coffee-house",
    officialName: "Coffee House™",
    category: "living-place",
    primaryFeeling: "Warmth, ease, gentle company",
    backgroundImage: "/backgrounds/coffee-house-background.png",
    aliases: [
      "coffee house",
      "coffee shop",
      "let's get coffee",
      "cozy cafe",
      "cafe",
      "the cafe",
      "café",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "open-presence",
    permanentObjects: ["Counter", "Mugs with Spark flame", "Small tables"],
    seasonalObjects: [
      "Pumpkin spice warmth (autumn)",
      "Iced drinks visible (summer)",
    ],
    interactiveObjects: ["Mug", "Conversation"],
    relatedPlaces: ["peaceful-places", "journal", "welcome-home"],
    status: "partial",
    expansionNotes: "Never turns rest into task list",
  },
  {
    id: "tea-room",
    officialName: "Tea Room™",
    category: "living-place",
    primaryFeeling: "Stillness, ritual, gentle hospitality",
    backgroundImage: "/backgrounds/tea-room-background.png",
    aliases: ["tea room", "let's have tea"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Tea service", "Low table", "Soft chairs"],
    seasonalObjects: ["Autumn tea settings", "Quiet Christmas ribbon"],
    interactiveObjects: ["Tea set", "Conversation"],
    relatedPlaces: ["coffee-house", "journal"],
    status: "future",
    expansionNotes: "Ship only when art passes Image Bible",
  },
  {
    id: "music-room",
    officialName: "Music Room™",
    category: "living-place",
    primaryFeeling: "Focus, warmth, creative calm",
    backgroundImage: "/backgrounds/music-room-background.png",
    aliases: ["music room", "piano", "play music", "I want music"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Piano", "Sheet music", "Comfortable seating"],
    seasonalObjects: ["Evening lamp (winter)", "Open windows (summer)"],
    interactiveObjects: ["Piano audio", "Ambience toggle"],
    relatedPlaces: ["peaceful-places", "coffee-house"],
    status: "partial",
    expansionNotes: "Distinct from Peaceful Places™ hub",
  },
  {
    id: "greenhouse",
    officialName: "Greenhouse™",
    category: "living-place",
    primaryFeeling: "Hopeful, patient, safe emergence",
    backgroundImage: "/backgrounds/greenhouse-background.png",
    aliases: ["greenhouse", "the greenhouse", "plant an idea"],
    arrivalBehavior: "presence-only",
    conversationStyle: "open-presence",
    permanentObjects: [
      "Potting benches",
      "Seed trays",
      "Watering can",
      "Glass walls",
      "Kinsey asleep (intentional)",
    ],
    seasonalObjects: [
      "Birdsong (spring)",
      "Frost on glass (winter)",
      "Amber autumn light",
    ],
    interactiveObjects: ["Garden journal on bench", "Path door to gardens"],
    relatedPlaces: [
      "gardens",
      "seeds-planted",
      "garden-path",
      "apple-orchard",
    ],
    status: "live",
    suggestionProfiles: ["quiet", "stressed", "orient"],
    expansionNotes:
      "Link to Seeds Planted™ via conversation only; bible/rooms/The Greenhouse.md",
  },
  {
    id: "gardens",
    officialName: "The Gardens™",
    category: "living-place",
    primaryFeeling: "Growth, peace, natural rhythm",
    backgroundImage: "/backgrounds/celebration-garden-room-background.png",
    aliases: [
      "gardens",
      "the gardens",
      "walk in the garden",
      "outside",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Paths", "Plantings", "Benches", "Seasonal flowers"],
    seasonalObjects: [
      "Spring blooms",
      "Autumn leaves",
      "Snow-quiet beds (winter)",
    ],
    interactiveObjects: ["Walk paths", "Sit on bench", "Conversation"],
    relatedPlaces: [
      "garden-bench",
      "garden-path",
      "celebration-room",
      "greenhouse",
    ],
    status: "needs-asset",
    suggestionProfiles: ["celebrate"],
    expansionNotes: "Celebration Room™ is the ritual destination — see celebration-room",
  },
  {
    id: "garden-bench",
    officialName: "Garden Bench",
    category: "living-place",
    primaryFeeling: "Pause, unhurried reflection",
    backgroundImage: null,
    aliases: ["garden bench", "sit outside", "bench in the garden"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Wooden bench", "Surrounding plantings"],
    seasonalObjects: ["Blossom overhead (spring)", "Fallen leaves (autumn)"],
    interactiveObjects: ["Sit", "Silence valid"],
    relatedPlaces: ["gardens", "greenhouse"],
    status: "planned",
    expansionNotes: "May be thirty seconds or an hour",
  },
  {
    id: "apple-orchard",
    officialName: "Apple Orchard™",
    category: "living-place",
    primaryFeeling: "Possibility, freshness, gentle abundance",
    backgroundImage: "/backgrounds/apple-orchard-background.png",
    aliases: ["apple orchard", "the orchard"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Trees", "Ladder (optional)", "Basket"],
    seasonalObjects: ["Blossom (spring)", "Harvest (autumn)"],
    interactiveObjects: ["Walk rows", "Conversation"],
    relatedPlaces: ["greenhouse", "window-seat", "garden-path"],
    status: "future",
    suggestionProfiles: ["reflective"],
    expansionNotes: "Window seat overlooks orchard",
  },
  {
    id: "back-deck",
    officialName: "Back Deck",
    category: "living-place",
    primaryFeeling: "Evening air, ease, conversation",
    backgroundImage: null,
    aliases: ["back deck", "sit outside", "evening air"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Railings", "Chairs", "View to yard"],
    seasonalObjects: ["Summer evening", "Autumn sweaters weather"],
    interactiveObjects: ["Sit", "Conversation"],
    relatedPlaces: ["porch-swing", "gardens"],
    status: "planned",
    suggestionProfiles: ["quiet", "overwhelmed", "rest"],
    expansionNotes: "Summer affinity per Seasonal Guide",
  },
  {
    id: "porch-swing",
    officialName: "Porch Swing",
    category: "living-place",
    primaryFeeling: "Slow rhythm, unhurried talk",
    backgroundImage: null,
    aliases: ["porch swing", "swing on the porch"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Swing", "Porch lanterns"],
    seasonalObjects: ["Lantern flicker (evening)", "Fireflies (summer)"],
    interactiveObjects: ["Swing motion (subtle)", "Conversation"],
    relatedPlaces: ["back-deck", "welcome-home"],
    status: "planned",
    suggestionProfiles: ["rest"],
    expansionNotes: "Estate Light Flicker on lanterns",
  },
  {
    id: "peaceful-places",
    officialName: "Peaceful Places™",
    category: "living-place",
    primaryFeeling: "Calm, safety, restoration, breath",
    backgroundImage: "/backgrounds/peaceful-places/woodland-pathway.png",
    aliases: [
      "peaceful places",
      "I need calm",
      "help me breathe",
      "quiet place",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "calm-restoration",
    permanentObjects: [
      "Woodland path",
      "Pond edge",
      "Calm destinations (hub)",
    ],
    seasonalObjects: ["Mist on pond", "Rain ambience"],
    interactiveObjects: [
      "Soundscape destinations (pond, woodland)",
      "Ambience toggle",
    ],
    relatedPlaces: [
      "seat-at-pond",
      "woodland-path",
      "music-room",
      "coffee-house",
    ],
    status: "needs-asset",
    expansionNotes: "Hub for dock, woodland, coffee nook — not a feature menu",
  },
  {
    id: "seat-at-pond",
    officialName: "Seat at Pond / Dock",
    category: "living-place",
    primaryFeeling: "Still water, breath, rest",
    backgroundImage: "/backgrounds/seat-at-pond-background.png",
    aliases: ["dock", "pond", "sit by the water"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Dock or bench", "Still water"],
    seasonalObjects: ["Mist (autumn)", "Dragonflies (summer)"],
    interactiveObjects: ["Water ambience"],
    relatedPlaces: ["peaceful-places", "sunroom"],
    status: "needs-asset",
    expansionNotes: "Sub-place of Peaceful Places™",
  },
  {
    id: "reading-nook",
    officialName: "Reading Nook",
    category: "living-place",
    primaryFeeling: "Peaceful, timeless, unhurried",
    backgroundImage: "/backgrounds/reading-nook-background.png",
    aliases: [
      "reading nook",
      "the reading nook",
      "nook under the stairs",
      "sit under the stairs",
      "under the stairs",
      "quiet read",
      "arched window nook",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Chair beneath staircase", "Lamp", "Small table"],
    seasonalObjects: ["Blanket (winter)", "Open window (summer)"],
    interactiveObjects: ["Book on table (optional)", "Conversation"],
    relatedPlaces: ["library", "main-staircase"],
    status: "needs-asset",
    suggestionProfiles: [
      "quiet",
      "stressed",
      "overwhelmed",
      "reflective",
      "think",
      "rest",
      "uncertain",
      "orient",
    ],
    expansionNotes: "Adjacent to Library™ — different category",
  },
  {
    id: "window-seat",
    officialName: "Window Seat",
    category: "living-place",
    primaryFeeling: "Lookout, rest, quiet companionship",
    backgroundImage: null,
    aliases: [
      "window seat",
      "sit by the window",
      "reading nook by the window",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Cushioned seat", "Orchard or garden view"],
    seasonalObjects: ["Snow on pane", "Blossom view"],
    interactiveObjects: ["Look out", "Conversation"],
    relatedPlaces: ["apple-orchard", "reading-nook"],
    status: "planned",
    expansionNotes: "Overlooks Apple Orchard™",
  },

  // —— Destination Places ——
  {
    id: "library",
    officialName: "The Library™",
    category: "destination",
    primaryFeeling: "Curiosity, timelessness, intellectual warmth",
    backgroundImage: "/backgrounds/reading-nook-background.png",
    aliases: ["library", "the library", "story library", "read something"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "discovery-dialogue",
    permanentObjects: [
      "Shelves",
      "Ladder",
      "Volumes",
      "Ribbon markers",
      "Accomplishments Book™ shelf",
    ],
    seasonalObjects: ["Hearth nearby (winter)", "Open windows (summer)"],
    interactiveObjects: ["Pull a volume", "Read", "Discuss with Shari"],
    relatedPlaces: [
      "reading-nook",
      "momentum-institute",
      "accomplishments-shelf",
    ],
    status: "needs-asset",
    suggestionProfiles: ["learn"],
    expansionNotes: "Never merge with Momentum Institute™",
  },
  {
    id: "momentum-institute",
    officialName: "Momentum Institute™",
    category: "destination",
    primaryFeeling: "Discovery, prestige, earned capability",
    backgroundImage: "/backgrounds/the-momentum-institute-background.webp",
    aliases: [
      "momentum institute",
      "the momentum institute",
      "the institute",
      "go to the institute",
      "entrepreneur development center",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "discovery-dialogue",
    permanentObjects: [
      "Drawer wall",
      "Brass hardware",
      "Index cards",
      "Study tables",
    ],
    seasonalObjects: [
      "Subtle light shift",
      "Quiet holiday garland (Christmas)",
    ],
    interactiveObjects: [
      "Open drawer",
      "Knowledge Cards™",
      "File to Cabinet (permission)",
    ],
    relatedPlaces: ["institute-cabinet", "library", "observatory"],
    status: "needs-asset",
    suggestionProfiles: ["learn", "curious"],
    expansionNotes: "Not school; not LMS panels; Bible Ch. 12–14",
  },
  {
    id: "clear-my-mind",
    officialName: "Clear My Mind™",
    category: "destination",
    primaryFeeling: "Relief, lightness, mental spaciousness",
    backgroundImage: "/backgrounds/butterfly-conservatory.webp",
    aliases: ["clear my mind", "clear my head", "brain dump"],
    arrivalBehavior: "presence-only",
    conversationStyle: "quiet-capture",
    permanentObjects: ["Capture surface (diegetic pad/glass)", "Calm glass light"],
    seasonalObjects: ["Rain on glass"],
    interactiveObjects: ["Continuous capture", "Share to Shari"],
    relatedPlaces: ["conservatory", "peaceful-places", "journal"],
    status: "needs-asset",
    expansionNotes:
      "Capture ≠ organize; organize workflow stays inside Clear My Mind (non-canon product label: My Thoughts)",
  },
  {
    id: "creative-studio",
    officialName: "Creative Studio™",
    category: "destination",
    primaryFeeling: "Creative calm, possibility, craft",
    backgroundImage: "/backgrounds/creative-studio-background.webp",
    aliases: ["creative studio", "the studio", "make something"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "creative-collaboration",
    permanentObjects: ["Worktable", "Pens (black/gold)", "Journals", "Tools"],
    seasonalObjects: ["Natural light shift"],
    interactiveObjects: ["Draft workspace (permission before show)"],
    relatedPlaces: ["portfolio", "momentum-institute", "momentum-builder"],
    status: "needs-asset",
    suggestionProfiles: ["creative"],
    expansionNotes: "Spec 106 permission before drafts",
  },
  {
    id: "observatory",
    officialName: "Observatory™",
    category: "destination",
    primaryFeeling: "Wonder, foresight, calm curiosity",
    backgroundImage: null,
    aliases: ["observatory", "research tower", "what's emerging"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "research-companion",
    permanentObjects: ["Telescope", "Horizon windows", "Curated stacks"],
    seasonalObjects: ["Clear winter skies", "Summer haze"],
    interactiveObjects: ["Research findings (3–5, conversational)"],
    relatedPlaces: ["momentum-institute", "creative-studio", "decision-compass"],
    status: "needs-asset",
    suggestionProfiles: ["learn", "curious"],
    expansionNotes: "Never dump information",
  },
  {
    id: "stables",
    officialName: "The Stables™",
    category: "destination",
    primaryFeeling: "Safe, grounded, calm, capable",
    backgroundImage: "/backgrounds/spark-estate-stables-background.webp",
    aliases: ["stables", "the stables", "I need confidence"],
    arrivalBehavior: "presence-only",
    conversationStyle: "coaching",
    permanentObjects: [
      "Stalls",
      "Brass",
      "Hay warmth",
      "Metaphor horses (no gamification)",
    ],
    seasonalObjects: ["Open doors (summer)", "Cozy lamps (winter)"],
    interactiveObjects: [
      "Stables experiences (coaching stories) — conversation-first",
    ],
    relatedPlaces: ["decision-compass", "evidence-vault", "growth-profile"],
    status: "live",
    expansionNotes: "Horse is metaphor; never lectures",
  },
  {
    id: "game-room",
    officialName: "Game Room™",
    category: "destination",
    primaryFeeling: "Playfulness, relief, light momentum",
    backgroundImage: "/backgrounds/focus-my-brain-games-background.png",
    aliases: ["game room", "let's play", "brain break", "exercise room", "the exercise room"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "playful-reset",
    permanentObjects: ["Table", "Playful objects", "Comfortable chaos"],
    seasonalObjects: ["Subtle holiday game (Christmas)"],
    interactiveObjects: ["Momentum builders", "Quick recharge"],
    relatedPlaces: ["momentum-builder", "peaceful-places"],
    status: "needs-asset",
    expansionNotes: "Never gamify self-worth",
  },
  {
    id: "momentum-builder",
    officialName: "Momentum Builder™",
    category: "destination",
    primaryFeeling: "Honest momentum, hope, forward motion",
    backgroundImage: null,
    aliases: [
      "momentum builder",
      "help me get moving",
      "I'm stuck",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "coaching",
    permanentObjects: ["Planning table", "Lamp", "Single clear surface"],
    seasonalObjects: ["Morning light bias"],
    interactiveObjects: ["One next step workspace (conversation-led)"],
    relatedPlaces: ["decision-compass", "game-room", "goals-projects"],
    status: "needs-asset",
    expansionNotes: "Never guilt",
  },
  {
    id: "decision-compass",
    officialName: "Decision Compass™",
    category: "destination",
    primaryFeeling: "Steadiness, clarity, ownership",
    backgroundImage: null,
    aliases: [
      "decision compass",
      "help me decide",
      "stuck between options",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "decision-facilitation",
    permanentObjects: ["Compass motif (diegetic)", "Writing surface"],
    seasonalObjects: [],
    interactiveObjects: ["Options exploration", "Member owns decision"],
    relatedPlaces: ["momentum-builder", "stables", "observatory"],
    status: "live",
    expansionNotes: "T-008 ownership always",
  },
  {
    id: "journal",
    officialName: "Journal™",
    category: "destination",
    primaryFeeling: "Privacy, honesty, gentle self-awareness",
    backgroundImage: "/backgrounds/gazebo-libjournal-background.png",
    aliases: [
      "journal",
      "my journal",
      "reflect on this week",
      "gazebo",
      "the gazebo",
      "gazebo journal",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "reflective-writing",
    permanentObjects: ["Gazebo or writing desk", "Leather journal", "Pen"],
    seasonalObjects: ["Garden growth around gazebo"],
    interactiveObjects: ["Write", "Voice-to-text", "Mic"],
    relatedPlaces: ["evidence-vault", "coffee-house", "gardens"],
    status: "needs-asset",
    suggestionProfiles: ["reflective", "think"],
    expansionNotes: "/backgrounds/journal-background.png alternate plate",
  },
  {
    id: "evidence-vault",
    officialName: "Evidence Vault™",
    category: "destination",
    primaryFeeling: "Confidence, proof, self-trust",
    backgroundImage: "/backgrounds/evidence-vault-background.png",
    aliases: [
      "evidence vault",
      "proof of growth",
      "proof",
      "impact stories",
      "people I helped",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Vault latch", "Shelves", "Warm lamp"],
    seasonalObjects: [],
    interactiveObjects: [
      "Add memory of win",
      "Open shelf entry (conversation-led)",
    ],
    relatedPlaces: ["journal", "growth-profile", "portfolio"],
    status: "needs-asset",
    expansionNotes: "Retire evidence-bank vocabulary",
  },
  {
    id: "portfolio",
    officialName: "Portfolio™",
    category: "destination",
    primaryFeeling: "Pride, craft, continuity",
    backgroundImage: "/backgrounds/accomplishments-room-background.png",
    aliases: ["portfolio", "my portfolio", "what I've built"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Folio on desk", "Project artifacts"],
    seasonalObjects: [],
    interactiveObjects: ["Open folio", "Review work with Shari"],
    relatedPlaces: ["creative-studio", "evidence-vault", "goals-projects"],
    status: "live",
    suggestionProfiles: ["creative"],
    expansionNotes: "Never file-table dashboard",
  },
  {
    id: "goals-projects",
    officialName: "Goals & Projects™",
    category: "destination",
    primaryFeeling: "Direction, ownership, honest ambition",
    backgroundImage: null,
    aliases: [
      "goals and projects",
      "my projects",
      "what am I building",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "coaching",
    permanentObjects: ["Project board (diegetic, calm)", "Desk"],
    seasonalObjects: [],
    interactiveObjects: ["Review projects", "Shape goals"],
    relatedPlaces: ["portfolio", "momentum-builder", "greenhouse"],
    status: "live",
    expansionNotes: "No surveillance language",
  },
  {
    id: "celebration-room",
    officialName: "Celebration Room™",
    category: "destination",
    primaryFeeling: "Joyful, quiet, honored",
    backgroundImage: "/backgrounds/celebration-garden-background 1.webp",
    aliases: [
      "celebration room",
      "the celebration room",
      "celebration garden",
      "celebration",
      "accomplishments",
      "wins",
      "mark this moment",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "celebration-ritual",
    permanentObjects: [
      "Flowers",
      "Chalkboard",
      "Handwritten notes",
      "The Bell (permission)",
    ],
    seasonalObjects: ["Seasonal blooms", "Modest Christmas lights"],
    interactiveObjects: [
      "Ring bell",
      "Leave note",
      "Quiet ritual — not popup card",
    ],
    relatedPlaces: ["gardens", "accomplishments-shelf"],
    status: "needs-asset",
    suggestionProfiles: ["celebrate"],
    expansionNotes: "Accomplishments Book™ volume may be added here",
  },

  // —— Collections ——
  {
    id: "institute-cabinet",
    officialName: "My Institute Cabinet™",
    category: "collection",
    primaryFeeling: "Trust, filed wisdom, easy return",
    backgroundImage: null,
    aliases: [
      "institute cabinet",
      "my cabinet",
      "what I saved from the institute",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Filing drawers", "Brass labels", "Index tabs"],
    seasonalObjects: [],
    interactiveObjects: ["Open filed card", "Discuss saved topic"],
    relatedPlaces: ["momentum-institute", "growth-profile"],
    status: "live",
    expansionNotes: "Not duplicate lesson bodies",
  },
  {
    id: "seeds-planted",
    officialName: "Seeds Planted™",
    category: "collection",
    primaryFeeling: "Hope, emergence, gentle growth",
    backgroundImage: null,
    aliases: ["seeds planted", "my spark cards", "planted seeds"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Seed packets", "Labeled stakes", "Starter pots"],
    seasonalObjects: ["Spring planting emphasis"],
    interactiveObjects: ["Browse Spark Cards / early ideas"],
    relatedPlaces: ["greenhouse", "apple-orchard", "momentum-institute"],
    status: "planned",
    expansionNotes: "Linked from Greenhouse™ via conversation",
  },
  {
    id: "growth-profile",
    officialName: "Growth Profile™",
    category: "collection",
    primaryFeeling: "Quiet pride, earned capability",
    backgroundImage: "/backgrounds/greenhouse-background.png",
    aliases: ["growth profile", "how am I growing", "my capabilities"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "personal-continuity",
    permanentObjects: ["Growth ledger", "Timeline markers"],
    seasonalObjects: [],
    interactiveObjects: [
      "Review capability growth (quiet, not dashboard)",
    ],
    relatedPlaces: ["momentum-institute", "evidence-vault", "stables"],
    status: "live",
    expansionNotes: "Not the Greenhouse — shared art only",
  },
  {
    id: "my-estate",
    officialName: "My Estate™",
    category: "collection",
    primaryFeeling: "Ownership, continuity, belonging",
    backgroundImage: "/backgrounds/spark-estate-photo-background.png",
    aliases: ["my estate", "estate profile"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "personal-continuity",
    permanentObjects: ["Personal estate photo", "Mementos"],
    seasonalObjects: ["Photo may reflect season (subtle)"],
    interactiveObjects: ["Preferences (conversation-led)", "Profile"],
    relatedPlaces: ["growth-profile", "institute-cabinet", "evidence-vault"],
    status: "live",
    expansionNotes: "Not a settings app with wallpaper",
  },
  {
    id: "accomplishments-shelf",
    officialName: "Accomplishments Book™ (Library shelf)",
    category: "collection",
    primaryFeeling: "Honored story, legacy",
    backgroundImage: null,
    aliases: [
      "accomplishments book",
      "my accomplishments book",
      "the accomplishments book",
      "show me my accomplishments",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "celebration-ritual",
    permanentObjects: ["Volumes on shelf", "Ribbon markers"],
    seasonalObjects: ["New volume binding (quiet)"],
    interactiveObjects: [
      "Open volume",
      "Read story",
      "Add chapter (permission)",
    ],
    relatedPlaces: ["library", "celebration-room"],
    status: "planned",
    suggestionProfiles: ["celebrate"],
    expansionNotes: "Bible Ch. 17; pairs with Bell in celebration-room",
  },

  // —— Transition Spaces ——
  {
    id: "main-hallway",
    officialName: "Main Hallway",
    category: "transition-space",
    primaryFeeling: "Belonging, flow, quiet",
    backgroundImage: null,
    aliases: ["hallway", "down the hall"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Art", "Runner rug", "Soft lamps"],
    seasonalObjects: ["Holiday garland (subtle)"],
    interactiveObjects: [],
    relatedPlaces: ["welcome-home", "main-staircase", "library"],
    status: "planned",
    expansionNotes: "Never blocks with menus",
  },
  {
    id: "main-staircase",
    officialName: "Main Staircase",
    category: "transition-space",
    primaryFeeling: "Vertical calm, discovery",
    backgroundImage: "/backgrounds/stairway-reading-nook-background.png",
    aliases: ["stairs", "up the stairs", "main staircase", "stairway reading nook"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Stairs", "Landing", "Reading nook below"],
    seasonalObjects: [],
    interactiveObjects: ["Pause on landing"],
    relatedPlaces: ["reading-nook", "library", "main-hallway"],
    status: "partial",
    expansionNotes: "Connects to Reading Nook",
  },
  {
    id: "front-drive",
    officialName: "Front Drive",
    category: "transition-space",
    primaryFeeling: "Arrival, anticipation",
    backgroundImage: null,
    aliases: ["drive up", "arriving"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Drive", "Trees", "Porch light"],
    seasonalObjects: ["Snow", "Autumn leaves"],
    interactiveObjects: [],
    relatedPlaces: ["welcome-home"],
    status: "planned",
    expansionNotes: "Cinematic optional; skippable",
  },
  {
    id: "garden-path",
    officialName: "Garden Path",
    category: "transition-space",
    primaryFeeling: "Movement, seasonal air",
    backgroundImage: null,
    aliases: ["garden path", "walk with me"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Gravel or stone path", "Plantings"],
    seasonalObjects: ["Full seasonal guide"],
    interactiveObjects: ["Walk"],
    relatedPlaces: [
      "gardens",
      "greenhouse",
      "apple-orchard",
      "celebration-room",
    ],
    status: "partial",
    suggestionProfiles: ["stressed"],
    expansionNotes: "Orchard ↔ greenhouse ↔ celebration",
  },
  {
    id: "woodland-path",
    officialName: "Woodland Path",
    category: "transition-space",
    primaryFeeling: "Calm approach, anticipation",
    backgroundImage: "/backgrounds/discovery -room-background.png",
    aliases: ["woodland path", "into the trees"],
    arrivalBehavior: "pass-through",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Trees", "Filtered light"],
    seasonalObjects: ["Mud and mist (autumn)", "Bird song (spring)"],
    interactiveObjects: ["Walk into Peaceful Places™"],
    relatedPlaces: ["peaceful-places", "seat-at-pond"],
    status: "needs-asset",
    expansionNotes: "Entry to Peaceful Places™",
  },
  {
    id: "balcony",
    officialName: "Balcony",
    category: "transition-space",
    primaryFeeling: "Overlook, pause",
    backgroundImage: null,
    aliases: ["balcony", "overlook"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Railing", "Chairs"],
    seasonalObjects: ["Seasonal light on gardens"],
    interactiveObjects: ["Look out"],
    relatedPlaces: ["gardens", "main-staircase"],
    status: "planned",
    expansionNotes: "Evening affinity",
  },
  {
    id: "bridge",
    officialName: "Garden Bridge",
    category: "transition-space",
    primaryFeeling: "Crossing, gentle discovery",
    backgroundImage: null,
    aliases: ["bridge", "over the stream"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Wooden bridge", "Stream below"],
    seasonalObjects: [],
    interactiveObjects: ["Cross"],
    relatedPlaces: ["garden-path", "gardens"],
    status: "future",
    expansionNotes: "Section 02 — future grounds",
  },
] as const;
