/**
 * Canonical place records — synced from SPARK_ESTATE_CANONICAL_REGISTRY.md.
 * @internal Import via canonicalEstateRegistry.ts only.
 */

import type { CanonicalEstatePlace } from "./canonicalEstateRegistryTypes";

export const CANONICAL_ESTATE_PLACES: readonly CanonicalEstatePlace[] = [
  // —— Living Places ——
  {
    id: "welcome-home",
    officialName: "Welcome Home™",
    category: "living-place",
    primaryFeeling: "Belonging, warmth, orientation, hope",
    backgroundImage: null,
    aliases: [
      "welcome home",
      "go home",
      "take me home",
      "back home",
      "I'm home",
    ],
    arrivalBehavior: "threshold",
    conversationStyle: "open-presence",
    permanentObjects: [
      "Front entry",
      "Coat hooks",
      "Soft light",
      "Guidebook™ on side table",
      "Folded Estate Map™ (corner, optional)",
    ],
    seasonalObjects: [
      "Wreath (Christmas)",
      "Porch lanterns (winter)",
      "Spring planters",
    ],
    interactiveObjects: ["Map (folded)", "Guidebook", "Continue conversation"],
    relatedPlaces: ["sunroom", "gardens", "greenhouse", "main-hallway"],
    status: "needs-asset",
    suggestionProfiles: ["orient", "uncertain"],
    expansionNotes:
      "Kinsey at threshold (optional); evening porch light; never dashboard tiles",
  },
  {
    id: "sunroom",
    officialName: "Sunroom",
    category: "living-place",
    primaryFeeling: "Warmth, belonging, unhurried welcome",
    backgroundImage: "/backgrounds/sunroom-background.png",
    aliases: ["sunroom", "welcome room", "Shari's sunroom"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: [
      "Shari's chair",
      "Pond view",
      "Spark mugs",
      "Plants in light",
    ],
    seasonalObjects: ["Brighter morning wash (summer)", "Frost on glass (winter)"],
    interactiveObjects: [
      "Letter from Shari (first visits, optional)",
      "Conversation",
    ],
    relatedPlaces: ["welcome-home", "seat-at-pond"],
    status: "live",
    expansionNotes: "Voice welcome optional; never product explainer",
  },
  {
    id: "conservatory",
    officialName: "The Ocean Conservatory™",
    category: "living-place",
    primaryFeeling: "Stillness, clarity, peaceful sanctuary",
    backgroundImage: "/backgrounds/the-ocean-conservatory-background.png",
    aliases: [
      "conservatory",
      "the conservatory",
      "ocean conservatory",
      "the ocean conservatory",
      "ocean aquarium",
      "the ocean aquarium",
      "aquarium",
      "the aquarium",
      "quiet glass room",
      "butterfly conservatory",
      "the butterfly conservatory",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: [
      "Living wall of water",
      "Reef fish",
      "Reclining chairs",
      "Soft underwater light",
    ],
    seasonalObjects: ["Rain on glass (spring)", "Dusk glow (autumn)"],
    interactiveObjects: [
      "Ambience toggle",
      "Calming instrumental music",
      "Journal nearby (walk to Journal™ if asked)",
    ],
    relatedPlaces: ["clear-my-mind", "journal", "peaceful-places"],
    status: "planned",
    suggestionProfiles: ["overwhelmed", "think", "quiet", "reflective", "rest"],
    expansionNotes:
      "Shares atmosphere with Clear My Mind™ — distinct purpose; never merge IDs",
  },
  {
    id: "coffee-house",
    officialName: "Coffee House™",
    category: "living-place",
    primaryFeeling: "Warmth, ease, gentle company",
    backgroundImage: "/backgrounds/room-coffee-house-background.png",
    aliases: [
      "coffee house",
      "coffee shop",
      "let's get coffee",
      "cozy cafe",
      "cafe",
      "the cafe",
      "café",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "open-presence",
    permanentObjects: ["Counter", "Mugs with Spark flame", "Small tables"],
    seasonalObjects: [
      "Pumpkin spice warmth (autumn)",
      "Iced drinks visible (summer)",
    ],
    interactiveObjects: ["Mug", "Conversation"],
    relatedPlaces: ["peaceful-places", "journal", "welcome-home"],
    status: "partial",
    expansionNotes: "Never turns rest into task list",
  },
  {
    id: "tea-room",
    officialName: "Tea Room™",
    category: "living-place",
    primaryFeeling: "Stillness, ritual, gentle hospitality",
    backgroundImage: "/backgrounds/tea-room-background.webp",
    aliases: ["tea room", "let's have tea"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Tea service", "Low table", "Soft chairs"],
    seasonalObjects: ["Autumn tea settings", "Quiet Christmas ribbon"],
    interactiveObjects: ["Tea set", "Conversation"],
    relatedPlaces: ["coffee-house", "journal"],
    status: "future",
    expansionNotes: "Ship only when art passes Image Bible",
  },
  {
    id: "music-room",
    officialName: "Music Room™",
    category: "living-place",
    primaryFeeling: "Focus, warmth, creative calm",
    backgroundImage: "/backgrounds/music-room-background.png",
    aliases: ["music room", "piano", "play music", "I want music"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Piano", "Sheet music", "Comfortable seating"],
    seasonalObjects: ["Evening lamp (winter)", "Open windows (summer)"],
    interactiveObjects: ["Piano audio", "Ambience toggle"],
    relatedPlaces: ["peaceful-places", "coffee-house"],
    status: "partial",
    expansionNotes: "Distinct from Peaceful Places™ hub",
  },
  {
    id: "greenhouse",
    officialName: "Greenhouse™",
    category: "living-place",
    primaryFeeling: "Hopeful, patient, safe emergence",
    backgroundImage: "/backgrounds/greenhouse-background.png",
    aliases: [
      "greenhouse",
      "the greenhouse",
      "working greenhouse",
      "the working greenhouse",
      "plant an idea",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "open-presence",
    permanentObjects: [
      "Potting benches",
      "Seed trays",
      "Watering can",
      "Glass walls",
      "Kinsey asleep (intentional)",
    ],
    seasonalObjects: [
      "Birdsong (spring)",
      "Frost on glass (winter)",
      "Amber autumn light",
    ],
    interactiveObjects: ["Garden journal on bench", "Path door to gardens"],
    relatedPlaces: [
      "gardens",
      "seeds-planted",
      "garden-path",
      "apple-orchard",
    ],
    status: "live",
    suggestionProfiles: ["quiet", "stressed", "orient"],
    expansionNotes:
      "Link to Seeds Planted™ via conversation only; bible/rooms/The Greenhouse.md",
  },
  {
    id: "gardens",
    officialName: "The Gardens™",
    category: "living-place",
    primaryFeeling: "Growth, peace, natural rhythm",
    backgroundImage: "/backgrounds/space-celebration-garden-background.png",
    aliases: [
      "gardens",
      "the gardens",
      "celebration garden",
      "the celebration garden",
      "walk in the garden",
      "outside",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Paths", "Plantings", "Benches", "Seasonal flowers"],
    seasonalObjects: [
      "Spring blooms",
      "Autumn leaves",
      "Snow-quiet beds (winter)",
    ],
    interactiveObjects: ["Walk paths", "Sit on bench", "Conversation"],
    relatedPlaces: [
      "garden-bench",
      "garden-path",
      "celebration-room",
      "greenhouse",
    ],
    status: "needs-asset",
    suggestionProfiles: ["celebrate"],
    expansionNotes: "Celebration Room™ is the ritual destination — see celebration-room",
  },
  {
    id: "garden-bench",
    officialName: "Garden Bench",
    category: "living-place",
    primaryFeeling: "Pause, unhurried reflection",
    backgroundImage: null,
    aliases: ["garden bench", "sit outside", "bench in the garden"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Wooden bench", "Surrounding plantings"],
    seasonalObjects: ["Blossom overhead (spring)", "Fallen leaves (autumn)"],
    interactiveObjects: ["Sit", "Silence valid"],
    relatedPlaces: ["gardens", "greenhouse"],
    status: "planned",
    expansionNotes: "May be thirty seconds or an hour",
  },
  {
    id: "apple-orchard",
    officialName: "Apple Orchard™",
    category: "living-place",
    primaryFeeling: "Possibility, freshness, gentle abundance",
    backgroundImage: "/backgrounds/space-apple-orchard-background.webp",
    aliases: ["apple orchard", "the orchard"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Trees", "Ladder (optional)", "Basket"],
    seasonalObjects: ["Blossom (spring)", "Harvest (autumn)"],
    interactiveObjects: ["Walk rows", "Conversation"],
    relatedPlaces: ["greenhouse", "window-seat", "garden-path"],
    status: "future",
    suggestionProfiles: ["reflective"],
    expansionNotes: "Window seat overlooks orchard",
  },
  {
    id: "back-deck",
    officialName: "Back Deck",
    category: "living-place",
    primaryFeeling: "Evening air, ease, conversation",
    backgroundImage: null,
    aliases: ["back deck", "sit outside", "evening air"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Railings", "Chairs", "View to yard"],
    seasonalObjects: ["Summer evening", "Autumn sweaters weather"],
    interactiveObjects: ["Sit", "Conversation"],
    relatedPlaces: ["porch-swing", "gardens"],
    status: "planned",
    suggestionProfiles: ["quiet", "overwhelmed", "rest"],
    expansionNotes: "Summer affinity per Seasonal Guide",
  },
  {
    id: "porch-swing",
    officialName: "Porch Swing",
    category: "living-place",
    primaryFeeling: "Slow rhythm, unhurried talk",
    backgroundImage: null,
    aliases: ["porch swing", "swing on the porch"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Swing", "Porch lanterns"],
    seasonalObjects: ["Lantern flicker (evening)", "Fireflies (summer)"],
    interactiveObjects: ["Swing motion (subtle)", "Conversation"],
    relatedPlaces: ["back-deck", "welcome-home"],
    status: "planned",
    suggestionProfiles: ["rest"],
    expansionNotes: "Estate Light Flicker on lanterns",
  },
  {
    id: "the-swing-beneath-the-oak",
    officialName: "The Swing Beneath the Oak™",
    category: "living-place",
    primaryFeeling: "Rest, remembrance, gentle stillness",
    backgroundImage: "/backgrounds/tree-swing-background.png",
    aliases: [
      "swing beneath the oak",
      "the swing beneath the oak",
      "oak swing",
      "tree swing",
      "memory swing",
      "reflection swing",
      "swing by the water",
      "swing at the creek",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "calm-restoration",
    permanentObjects: [
      "Old oak tree",
      "Swing",
      "Quiet water view",
      "Carved heart in bark (SW loves RH)",
    ],
    seasonalObjects: [
      "Light dancing on water",
      "Autumn leaves on the oak",
    ],
    interactiveObjects: [
      "Gentle swing motion",
      "Soft instrumental music",
      "Quiet conversation",
    ],
    relatedPlaces: [
      "seat-at-pond",
      "woodland-path",
      "peaceful-places",
      "reflection-pond",
      "porch-swing",
    ],
    status: "planned",
    suggestionProfiles: ["rest", "reflective", "quiet", "overwhelmed"],
    expansionNotes:
      "Signature restoration place — presence only; no create/decide agenda",
  },
  {
    id: "peaceful-places",
    officialName: "Peaceful Places™",
    category: "living-place",
    primaryFeeling: "Calm, safety, restoration, breath",
    backgroundImage: "/backgrounds/peaceful-places/woodland-pathway.png",
    aliases: [
      "peaceful places",
      "I need calm",
      "help me breathe",
      "quiet place",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "calm-restoration",
    permanentObjects: [
      "Woodland path",
      "Pond edge",
      "Calm destinations (hub)",
    ],
    seasonalObjects: ["Mist on pond", "Rain ambience"],
    interactiveObjects: [
      "Soundscape destinations (pond, woodland)",
      "Ambience toggle",
    ],
    relatedPlaces: [
      "seat-at-pond",
      "woodland-path",
      "music-room",
      "coffee-house",
    ],
    status: "needs-asset",
    expansionNotes: "Hub for dock, woodland, coffee nook — not a feature menu",
  },
  {
    id: "seat-at-pond",
    officialName: "Seat at Pond / Dock",
    category: "living-place",
    primaryFeeling: "Still water, breath, rest",
    backgroundImage: "/backgrounds/water-seat-at-pond-background.png",
    aliases: ["dock", "pond", "sit by the water"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Dock or bench", "Still water"],
    seasonalObjects: ["Mist (autumn)", "Dragonflies (summer)"],
    interactiveObjects: ["Water ambience"],
    relatedPlaces: ["peaceful-places", "sunroom"],
    status: "needs-asset",
    expansionNotes: "Sub-place of Peaceful Places™",
  },
  {
    id: "reading-nook",
    officialName: "Reading Nook",
    category: "living-place",
    primaryFeeling: "Peaceful, timeless, unhurried",
    backgroundImage: "/backgrounds/reading-nook-window background.png",
    aliases: [
      "reading nook",
      "the reading nook",
      "nook under the stairs",
      "sit under the stairs",
      "under the stairs",
      "quiet read",
      "arched window nook",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Chair beneath staircase", "Lamp", "Small table"],
    seasonalObjects: ["Blanket (winter)", "Open window (summer)"],
    interactiveObjects: ["Book on table (optional)", "Conversation"],
    relatedPlaces: ["library", "main-staircase"],
    status: "needs-asset",
    suggestionProfiles: [
      "quiet",
      "stressed",
      "overwhelmed",
      "reflective",
      "think",
      "rest",
      "uncertain",
      "orient",
    ],
    expansionNotes: "Adjacent to Library™ — different category",
  },
  {
    id: "personal-deck",
    officialName: "Personal Deck™",
    category: "living-place",
    primaryFeeling: "Fireside ease, private conversation, evening air",
    backgroundImage: "/backgrounds/fireside-deck-background.PNG",
    aliases: [
      "personal deck",
      "the personal deck",
      "my deck",
      "private balcony",
      "the private balcony",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Deck chairs", "Fire pit or lanterns", "Railings"],
    seasonalObjects: ["Summer evenings", "Autumn sweaters weather"],
    interactiveObjects: ["Sit", "Conversation"],
    relatedPlaces: ["fireside-deck", "back-deck", "porch-swing", "seat-at-pond"],
    status: "needs-asset",
    suggestionProfiles: ["quiet", "rest", "reflective"],
    expansionNotes: "Private deck — distinct from Back Deck™",
  },
  {
    id: "estate-kitchen",
    officialName: "Estate Kitchen™",
    category: "living-place",
    primaryFeeling: "Warmth, nourishment, belonging",
    backgroundImage: "/backgrounds/kitchen-background.png",
    aliases: [
      "kitchen",
      "the kitchen",
      "estate kitchen",
      "the estate kitchen",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Hearth or range", "Wooden table", "Copper and linen"],
    seasonalObjects: ["Holiday baking warmth", "Summer open windows"],
    interactiveObjects: ["Sit at the table", "Conversation"],
    relatedPlaces: ["welcome-home", "tea-room"],
    status: "needs-asset",
    suggestionProfiles: ["rest", "quiet"],
    expansionNotes: "Living place — conversation continues; not a workflow kitchen",
  },
  {
    id: "spark-estate",
    officialName: "Spark Estate™",
    category: "living-place",
    primaryFeeling: "Wonder, belonging, arrival on the grounds",
    backgroundImage: "/backgrounds/spark-estate-photo-background.png",
    aliases: [
      "spark estate",
      "the spark estate",
      "front estate",
      "the front estate",
      "estate grounds",
      "the estate grounds",
    ],
    arrivalBehavior: "threshold",
    conversationStyle: "open-presence",
    permanentObjects: ["Manor approach", "Gardens", "Drive"],
    seasonalObjects: ["Seasonal light on grounds"],
    interactiveObjects: ["Walk the grounds", "Conversation"],
    relatedPlaces: ["welcome-home", "gardens", "estate-gardens"],
    status: "partial",
    suggestionProfiles: ["orient"],
    expansionNotes: "Front grounds — not a dashboard map",
  },
  {
    id: "dining-room",
    officialName: "Dining Room™",
    category: "living-place",
    primaryFeeling: "Gathered warmth, hospitality, unhurried meals",
    backgroundImage: "/backgrounds/room-dining-room-background.png",
    aliases: ["dining room", "the dining room"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Long table", "Candles", "Sideboard"],
    seasonalObjects: ["Holiday settings", "Summer open windows"],
    interactiveObjects: ["Sit", "Conversation"],
    relatedPlaces: ["estate-kitchen", "tea-room", "welcome-home"],
    status: "needs-asset",
    suggestionProfiles: ["rest", "quiet"],
    expansionNotes: "Living place — conversation first",
  },
  {
    id: "summer-terrace",
    officialName: "Summer Terrace™",
    category: "living-place",
    primaryFeeling: "Sun-warmed ease, water nearby, summer air",
    backgroundImage: "/backgrounds/water-swimming-pool-private-background.png",
    aliases: [
      "summer terrace",
      "the summer terrace",
      "swimming pool",
      "the swimming pool",
      "the pool",
      "pool",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Terrace seating", "Pool edge", "Umbrellas"],
    seasonalObjects: ["High summer light", "Evening lanterns"],
    interactiveObjects: ["Sit", "Conversation"],
    relatedPlaces: ["grand-terrace", "lakeside-verandah", "reflection-pond"],
    status: "partial",
    suggestionProfiles: ["rest", "quiet"],
    expansionNotes: "Pool terrace plate — distinct from Seat at the Pond™ dock",
  },
  {
    id: "grand-terrace",
    officialName: "Grand Terrace™",
    category: "living-place",
    primaryFeeling: "Open air, vista, unhurried perspective",
    backgroundImage: "/backgrounds/grand-estate-background.png",
    aliases: ["grand terrace", "the grand terrace"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Stone terrace", "Wide view", "Planters"],
    seasonalObjects: ["Seasonal light shift"],
    interactiveObjects: ["Look out", "Conversation"],
    relatedPlaces: ["summer-terrace", "estate-gardens", "spark-estate"],
    status: "needs-asset",
    suggestionProfiles: ["rest", "reflective"],
    expansionNotes: "Distinct from Summer Terrace™ pool edge",
  },
  {
    id: "lakeside-verandah",
    officialName: "Lakeside Verandah™",
    category: "living-place",
    primaryFeeling: "Breeze, water rhythm, sheltered outlook",
    backgroundImage: "/backgrounds/water-lakeside-deck-verandah-background.png",
    aliases: [
      "lakeside verandah",
      "the lakeside verandah",
      "lakeside veranda",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Verandah rail", "Lake view", "Wicker seating"],
    seasonalObjects: ["Summer haze", "Autumn stillness"],
    interactiveObjects: ["Sit", "Conversation"],
    relatedPlaces: ["lakeside-hammock", "reflection-pond", "seat-at-pond"],
    status: "needs-asset",
    suggestionProfiles: ["quiet", "rest"],
    expansionNotes: "Distinct from Seat at the Pond™ dock",
  },
  {
    id: "lakeside-hammock",
    officialName: "Lakeside Hammock™",
    category: "living-place",
    primaryFeeling: "Drift, ease, gentle restoration",
    backgroundImage: "/backgrounds/water-lakeside-hammock-background.png",
    aliases: ["lakeside hammock", "the lakeside hammock"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Hammock", "Shade trees", "Lake glimpses"],
    seasonalObjects: ["Summer breeze", "Quiet winter light"],
    interactiveObjects: ["Rest", "Conversation"],
    relatedPlaces: ["lakeside-verandah", "reflection-pond", "peaceful-places"],
    status: "needs-asset",
    suggestionProfiles: ["rest", "overwhelmed"],
    expansionNotes: "Restoration — not a task space",
  },
  {
    id: "reflection-pond",
    officialName: "Reflection Pond™",
    category: "living-place",
    primaryFeeling: "Still water, contemplation, gentle nature",
    backgroundImage: "/backgrounds/water-seat-at-pond-background.png",
    aliases: [
      "reflection pond",
      "the reflection pond",
      "visit the reflection pond",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Still pond", "Stones", "Reeds"],
    seasonalObjects: ["Mist (autumn)", "Dragonflies (summer)"],
    interactiveObjects: ["Sit nearby", "Conversation"],
    relatedPlaces: ["seat-at-pond", "lakeside-verandah", "garden-path"],
    status: "needs-asset",
    suggestionProfiles: ["reflective", "quiet"],
    expansionNotes: "Distinct from Seat at the Pond™ activity dock",
  },
  {
    id: "fireside-deck",
    officialName: "Fireside Deck™",
    category: "living-place",
    primaryFeeling: "Firelight, evening ease, gathered warmth",
    backgroundImage: "/backgrounds/fireside-deck-background.PNG",
    aliases: ["fireside deck", "the fireside deck"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Fire pit", "Deck chairs", "Lanterns"],
    seasonalObjects: ["Summer evenings", "Autumn firelight"],
    interactiveObjects: ["Sit", "Conversation"],
    relatedPlaces: ["personal-deck", "back-deck", "porch-swing"],
    status: "needs-asset",
    suggestionProfiles: ["rest", "reflective"],
    expansionNotes: "Distinct from Personal Deck™ private balcony",
  },
  {
    id: "estate-gardens",
    officialName: "Estate Gardens™",
    category: "living-place",
    primaryFeeling: "Grounds, paths, cultivated beauty",
    backgroundImage: "/backgrounds/place-estate-gardens-background.png",
    aliases: [
      "estate gardens",
      "the estate gardens",
      "estate garden",
      "the estate garden",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Garden paths", "Beds", "Gates"],
    seasonalObjects: ["Spring bloom", "Autumn color"],
    interactiveObjects: ["Walk", "Conversation"],
    relatedPlaces: ["gardens", "garden-path", "apple-orchard"],
    status: "needs-asset",
    suggestionProfiles: ["quiet", "orient"],
    expansionNotes: "Distinct from Celebration Garden™ wins collection",
  },
  {
    id: "stairway-reading-nook",
    officialName: "Stairway Reading Nook™",
    category: "living-place",
    primaryFeeling: "Hush, tucked-away read, staircase light",
    backgroundImage: "/backgrounds/reading-nook-under-stairway-background.png",
    aliases: [
      "stairway reading nook",
      "the stairway reading nook",
      "stairs reading nook",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Bench under stairs", "Lamp", "Book stack"],
    seasonalObjects: ["Cozy blanket (winter)"],
    interactiveObjects: ["Read", "Conversation"],
    relatedPlaces: ["reading-nook", "main-staircase", "library"],
    status: "partial",
    suggestionProfiles: ["quiet", "think"],
    expansionNotes: "Distinct from Reading Nook™ arched window",
  },
  {
    id: "window-seat",
    officialName: "Window Seat",
    category: "living-place",
    primaryFeeling: "Lookout, rest, quiet companionship",
    backgroundImage: null,
    aliases: [
      "window seat",
      "sit by the window",
      "reading nook by the window",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "open-presence",
    permanentObjects: ["Cushioned seat", "Orchard or garden view"],
    seasonalObjects: ["Snow on pane", "Blossom view"],
    interactiveObjects: ["Look out", "Conversation"],
    relatedPlaces: ["apple-orchard", "reading-nook"],
    status: "planned",
    expansionNotes: "Overlooks Apple Orchard™",
  },

  // —— Destination Places ——
  {
    id: "library",
    officialName: "The Library™",
    category: "destination",
    primaryFeeling: "Curiosity, timelessness, intellectual warmth",
    backgroundImage: "/backgrounds/room-library-estate-background.png",
    aliases: [
      "library",
      "the library",
      "estate library",
      "the estate library",
      "story library",
      "read something",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "discovery-dialogue",
    permanentObjects: [
      "Shelves",
      "Ladder",
      "Volumes",
      "Ribbon markers",
      "Accomplishments Book™ shelf",
    ],
    seasonalObjects: ["Hearth nearby (winter)", "Open windows (summer)"],
    interactiveObjects: ["Pull a volume", "Read", "Discuss with Shari"],
    relatedPlaces: [
      "reading-nook",
      "momentum-institute",
      "accomplishments-shelf",
    ],
    status: "needs-asset",
    suggestionProfiles: ["learn"],
    expansionNotes: "Never merge with Momentum Institute™",
  },
  {
    id: "personal-library",
    officialName: "Personal Library",
    category: "destination",
    primaryFeeling: "Quiet ownership, reading at your own pace",
    backgroundImage: "/backgrounds/room-library-personal-background.png",
    aliases: ["personal library", "the personal library", "my library"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "discovery-dialogue",
    permanentObjects: ["Your shelves", "Reading chair", "Quiet lamp"],
    seasonalObjects: ["Rain on windows (spring)", "Firelight (winter)"],
    interactiveObjects: ["Pull a volume", "Read", "Discuss with Shari"],
    relatedPlaces: ["library", "reading-nook"],
    status: "needs-asset",
    suggestionProfiles: ["quiet", "reflective", "learn"],
    expansionNotes: "Distinct from Estate Library™ shared shelves",
  },
  {
    id: "momentum-institute",
    officialName: "Momentum Institute™",
    category: "destination",
    primaryFeeling: "Discovery, prestige, earned capability",
    backgroundImage: "/backgrounds/the-momentum-institute-background.png",
    aliases: [
      "momentum institute",
      "the momentum institute",
      "the institute",
      "go to the institute",
      "entrepreneur development center",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "discovery-dialogue",
    permanentObjects: [
      "Drawer wall",
      "Brass hardware",
      "Index cards",
      "Study tables",
    ],
    seasonalObjects: [
      "Subtle light shift",
      "Quiet holiday garland (Christmas)",
    ],
    interactiveObjects: [
      "Open drawer",
      "Knowledge Cards™",
      "File to Cabinet (permission)",
    ],
    relatedPlaces: ["institute-cabinet", "library", "observatory"],
    status: "needs-asset",
    suggestionProfiles: ["learn", "curious"],
    expansionNotes: "Not school; not LMS panels; Bible Ch. 12–14",
  },
  {
    id: "study-hall",
    officialName: "Study Hall™",
    category: "destination",
    primaryFeeling: "Quiet focus, hush, earned capability",
    backgroundImage: "/backgrounds/study-hall-background.png",
    aliases: [
      "study hall",
      "the study hall",
      "classroom",
      "the classroom",
      "lecture hall",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "discovery-dialogue",
    permanentObjects: ["Study tables", "Lamps", "Quiet shelves"],
    seasonalObjects: ["Winter hearth nearby", "Summer open windows"],
    interactiveObjects: ["Study", "Conversation with Shari"],
    relatedPlaces: ["momentum-institute", "library", "momentum-room"],
    status: "needs-asset",
    suggestionProfiles: ["learn", "think"],
    expansionNotes: "Adjacent to Momentum Institute™ — quieter study hush",
  },
  {
    id: "momentum-room",
    officialName: "Momentum Room™",
    category: "destination",
    primaryFeeling: "Forward motion, clarity, gathered energy",
    backgroundImage: "/backgrounds/study-hall-background.png",
    aliases: [
      "momentum room",
      "the momentum room",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "coaching",
    permanentObjects: ["Round table", "Warm light", "Open space"],
    seasonalObjects: ["Seasonal light shift"],
    interactiveObjects: ["Think together", "Plan forward"],
    relatedPlaces: ["momentum-institute", "study-hall", "momentum-builder"],
    status: "needs-asset",
    suggestionProfiles: ["think", "orient"],
    expansionNotes: "Distinct from Momentum Institute™ drawers and Momentum Builder™ planning",
  },
  {
    id: "discovery-room",
    officialName: "Discovery Room™",
    category: "destination",
    primaryFeeling: "Curiosity, emergence, quiet research",
    backgroundImage: "/backgrounds/room-discovery-room-background.png",
    aliases: ["discovery room", "the discovery room"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "research-companion",
    permanentObjects: ["Curated stacks", "Soft lamps", "Writing surface"],
    seasonalObjects: ["Seasonal light shift"],
    interactiveObjects: ["Explore findings", "Conversation"],
    relatedPlaces: ["observatory", "momentum-institute", "library"],
    status: "needs-asset",
    suggestionProfiles: ["curious", "learn"],
    expansionNotes: "Distinct from Observatory™ horizon research",
  },
  {
    id: "art-studio",
    officialName: "Art Studio™",
    category: "destination",
    primaryFeeling: "Craft, color, creative possibility",
    backgroundImage: "/backgrounds/room-create-studio-background.png",
    aliases: ["art studio", "the art studio", "artist studio"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "creative-collaboration",
    permanentObjects: ["Easel", "Paints", "Natural light"],
    seasonalObjects: ["Seasonal light shift"],
    interactiveObjects: ["Draft workspace (permission before show)"],
    relatedPlaces: ["creative-studio", "portfolio", "strategy-studio"],
    status: "needs-asset",
    suggestionProfiles: ["creative"],
    expansionNotes: "Distinct from Creative Studio™ writing craft",
  },
  {
    id: "strategy-studio",
    officialName: "Strategy Studio™",
    category: "destination",
    primaryFeeling: "Clarity, deliberate thinking, forward planning",
    backgroundImage: "/backgrounds/strategy-studio-workroom-background.png",
    aliases: ["strategy studio", "the strategy studio"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "coaching",
    permanentObjects: ["Worktable", "Maps", "Markers"],
    seasonalObjects: [],
    interactiveObjects: ["Think together", "Plan forward"],
    relatedPlaces: ["round-table", "momentum-room", "goals-projects"],
    status: "needs-asset",
    suggestionProfiles: ["think", "orient"],
    expansionNotes: "Distinct from Momentum Room™ energy and Round Table™ decisions",
  },
  {
    id: "round-table",
    officialName: "Round Table™",
    category: "destination",
    primaryFeeling: "Gathered judgment, ownership, honest debate",
    backgroundImage: "/backgrounds/round-table-boardroom-background.png",
    aliases: [
      "round table",
      "the round table",
      "boardroom",
      "the boardroom",
      "board room",
      "the board room",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "decision-facilitation",
    permanentObjects: ["Round table", "Chairs", "Warm light"],
    seasonalObjects: [],
    interactiveObjects: ["Decide together", "Conversation"],
    relatedPlaces: ["strategy-studio", "decision-compass", "goals-projects"],
    status: "needs-asset",
    suggestionProfiles: ["think"],
    expansionNotes: "Boardroom plate — not a software meeting room",
  },
  {
    id: "gallery-of-firsts",
    officialName: "Hall of Accomplishments™",
    category: "destination",
    primaryFeeling: "Pride, lineage, quiet celebration",
    backgroundImage: "/backgrounds/gallery-background.png",
    aliases: [
      "hall of accomplishments",
      "the hall of accomplishments",
      "gallery of firsts",
      "the gallery of firsts",
      "hall of achievements",
      "accomplishments hall",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Gallery walls", "First milestones", "Soft light"],
    seasonalObjects: [],
    interactiveObjects: ["Browse accomplishments", "Conversation"],
    relatedPlaces: ["portfolio", "accomplishments-shelf", "celebration-room"],
    status: "needs-asset",
    suggestionProfiles: ["reflective"],
    expansionNotes: "Distinct from Portfolio™ folio and Celebration Hall™",
  },
  {
    id: "clear-my-mind",
    officialName: "Clear My Mind™",
    category: "destination",
    primaryFeeling: "Relief, lightness, mental spaciousness",
    backgroundImage: "/backgrounds/sunroom-background.png",
    aliases: [
      "clear my mind",
      "clear my mind sunroom",
      "clear my head",
      "brain dump",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "quiet-capture",
    permanentObjects: ["Capture surface (diegetic pad/glass)", "Calm glass light"],
    seasonalObjects: ["Rain on glass"],
    interactiveObjects: ["Continuous capture", "Share to Shari"],
    relatedPlaces: ["conservatory", "peaceful-places", "journal"],
    status: "needs-asset",
    expansionNotes:
      "Capture ≠ organize; organize workflow stays inside Clear My Mind (non-canon product label: My Thoughts)",
  },
  {
    id: "creative-studio",
    officialName: "Create",
    category: "destination",
    primaryFeeling: "Creative calm, possibility, craft",
    backgroundImage: "/backgrounds/room-create-studio-background.png",
    aliases: [
      "create",
      "create experience",
      "creative studio",
      "the creative studio",
      "make something",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "creative-collaboration",
    permanentObjects: ["Worktable", "Pens (black/gold)", "Journals", "Tools"],
    seasonalObjects: ["Natural light shift"],
    interactiveObjects: ["Draft workspace (permission before show)"],
    relatedPlaces: ["portfolio", "momentum-institute", "momentum-builder"],
    status: "needs-asset",
    suggestionProfiles: ["creative"],
    expansionNotes: "Spec 106 permission before drafts",
  },
  {
    id: "observatory",
    officialName: "Observatory™",
    category: "destination",
    primaryFeeling: "Wonder, foresight, calm curiosity",
    backgroundImage: null,
    aliases: ["observatory", "research tower", "what's emerging"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "research-companion",
    permanentObjects: ["Telescope", "Horizon windows", "Curated stacks"],
    seasonalObjects: ["Clear winter skies", "Summer haze"],
    interactiveObjects: ["Research findings (3–5, conversational)"],
    relatedPlaces: ["momentum-institute", "creative-studio", "decision-compass", "observatory-telescope-window", "observatory-fireplace"],
    status: "needs-asset",
    suggestionProfiles: ["learn", "curious"],
    routeType: "room",
    purpose: "Look ahead — research, horizon, and what is emerging",
    availableActions: ["research", "look out", "sit by the fire", "telescope"],
    expansionNotes: "Never dump information",
  },
  {
    id: "stables",
    officialName: "The Stables™",
    category: "destination",
    primaryFeeling: "Safe, grounded, calm, capable",
    backgroundImage: "/backgrounds/spark-estate-stables-background.png",
    aliases: [
      "stables",
      "the stables",
      "spark stables",
      "the spark stables",
      "stable",
      "the stable",
      "I need confidence",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "coaching",
    permanentObjects: [
      "Stalls",
      "Brass",
      "Hay warmth",
      "Metaphor horses (no gamification)",
    ],
    seasonalObjects: ["Open doors (summer)", "Cozy lamps (winter)"],
    interactiveObjects: [
      "Stables experiences (coaching stories) — conversation-first",
    ],
    relatedPlaces: ["decision-compass", "evidence-vault", "growth-profile"],
    status: "live",
    expansionNotes: "Horse is metaphor; never lectures",
  },
  {
    id: "game-room",
    officialName: "Game Room™",
    category: "destination",
    primaryFeeling: "Playfulness, relief, light momentum",
    backgroundImage: "/backgrounds/game-room-%20background.webp",
    aliases: ["game room", "let's play", "brain break", "exercise room", "the exercise room"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "playful-reset",
    permanentObjects: ["Table", "Playful objects", "Comfortable chaos"],
    seasonalObjects: ["Subtle holiday game (Christmas)"],
    interactiveObjects: ["Momentum builders", "Quick recharge"],
    relatedPlaces: ["momentum-builder", "peaceful-places"],
    status: "needs-asset",
    expansionNotes: "Never gamify self-worth",
  },
  {
    id: "momentum-builder",
    officialName: "Momentum Builder™",
    category: "destination",
    primaryFeeling: "Honest momentum, hope, forward motion",
    backgroundImage: null,
    aliases: [
      "momentum builder",
      "help me get moving",
      "I'm stuck",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "coaching",
    permanentObjects: ["Planning table", "Lamp", "Single clear surface"],
    seasonalObjects: ["Morning light bias"],
    interactiveObjects: ["One next step workspace (conversation-led)"],
    relatedPlaces: ["decision-compass", "game-room", "goals-projects"],
    status: "needs-asset",
    expansionNotes: "Never guilt",
  },
  {
    id: "decision-compass",
    officialName: "Decision Compass™",
    category: "destination",
    primaryFeeling: "Steadiness, clarity, ownership",
    backgroundImage: null,
    aliases: [
      "decision compass",
      "the decision compass",
      "writing room",
      "the writing room",
      "help me decide",
      "stuck between options",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "decision-facilitation",
    permanentObjects: ["Compass motif (diegetic)", "Writing surface"],
    seasonalObjects: [],
    interactiveObjects: ["Options exploration", "Member owns decision"],
    relatedPlaces: ["momentum-builder", "stables", "observatory"],
    status: "live",
    expansionNotes: "T-008 ownership always",
  },
  {
    id: "journal",
    officialName: "Journal™",
    category: "destination",
    primaryFeeling: "Privacy, honesty, gentle self-awareness",
    backgroundImage: "/backgrounds/gazebo-journal-background.png",
    aliases: [
      "journal",
      "my journal",
      "reflect on this week",
      "journal gazebo",
      "the journal gazebo",
      "gazebo",
      "the gazebo",
      "gazebo journal",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "reflective-writing",
    permanentObjects: ["Gazebo or writing desk", "Leather journal", "Pen"],
    seasonalObjects: ["Garden growth around gazebo"],
    interactiveObjects: ["Write", "Voice-to-text", "Mic"],
    relatedPlaces: ["evidence-vault", "coffee-house", "gardens"],
    status: "needs-asset",
    suggestionProfiles: ["reflective", "think"],
    expansionNotes: "/backgrounds/gazebo-journal-background.png alternate plate",
  },
  {
    id: "evidence-vault",
    officialName: "Evidence Vault™",
    category: "destination",
    primaryFeeling: "Confidence, proof, self-trust",
    backgroundImage: "/backgrounds/evidence-vault-background.png",
    aliases: [
      "evidence vault",
      "proof of growth",
      "proof",
      "impact stories",
      "people I helped",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Vault latch", "Shelves", "Warm lamp"],
    seasonalObjects: [],
    interactiveObjects: [
      "Add memory of win",
      "Open shelf entry (conversation-led)",
    ],
    relatedPlaces: ["journal", "growth-profile", "portfolio"],
    status: "needs-asset",
    expansionNotes: "Retire evidence-bank vocabulary",
  },
  {
    id: "portfolio",
    officialName: "Portfolio™",
    category: "destination",
    primaryFeeling: "Pride, craft, continuity",
    backgroundImage: "/backgrounds/accomplisments-room-background.png",
    aliases: ["portfolio", "my portfolio", "what I've built"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Folio on desk", "Project artifacts"],
    seasonalObjects: [],
    interactiveObjects: ["Open folio", "Review work with Shari"],
    relatedPlaces: ["creative-studio", "evidence-vault", "goals-projects"],
    status: "live",
    suggestionProfiles: ["creative"],
    expansionNotes: "Never file-table dashboard",
  },
  {
    id: "goals-projects",
    officialName: "Goals & Projects™",
    category: "destination",
    primaryFeeling: "Direction, ownership, honest ambition",
    backgroundImage: null,
    aliases: [
      "goals and projects",
      "my projects",
      "what am I building",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "coaching",
    permanentObjects: ["Project board (diegetic, calm)", "Desk"],
    seasonalObjects: [],
    interactiveObjects: ["Review projects", "Shape goals"],
    relatedPlaces: ["portfolio", "momentum-builder", "greenhouse"],
    status: "live",
    expansionNotes: "No surveillance language",
  },
  {
    id: "celebration-room",
    officialName: "Celebration Room™",
    category: "destination",
    primaryFeeling: "Joyful, quiet, honored",
    backgroundImage: "/backgrounds/room-celebration-hall-background.png",
    aliases: [
      "celebration room",
      "the celebration room",
      "celebration hall",
      "the celebration hall",
      "celebration",
      "accomplishments",
      "mark this moment",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "celebration-ritual",
    permanentObjects: [
      "Flowers",
      "Chalkboard",
      "Handwritten notes",
      "The Bell (permission)",
    ],
    seasonalObjects: ["Seasonal blooms", "Modest Christmas lights"],
    interactiveObjects: [
      "Ring bell",
      "Leave note",
      "Quiet ritual — not popup card",
    ],
    relatedPlaces: ["gardens", "accomplishments-shelf"],
    status: "needs-asset",
    suggestionProfiles: ["celebrate"],
    expansionNotes: "Accomplishments Book™ volume may be added here",
  },

  // —— Collections ——
  {
    id: "institute-cabinet",
    officialName: "My Institute Cabinet™",
    category: "collection",
    primaryFeeling: "Trust, filed wisdom, easy return",
    backgroundImage: null,
    aliases: [
      "institute cabinet",
      "my cabinet",
      "what I saved from the institute",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Filing drawers", "Brass labels", "Index tabs"],
    seasonalObjects: [],
    interactiveObjects: ["Open filed card", "Discuss saved topic"],
    relatedPlaces: ["momentum-institute", "growth-profile"],
    status: "live",
    expansionNotes: "Not duplicate lesson bodies",
  },
  {
    id: "seeds-planted",
    officialName: "Seeds Planted™",
    category: "collection",
    primaryFeeling: "Hope, emergence, gentle growth",
    backgroundImage: null,
    aliases: ["seeds planted", "my spark cards", "planted seeds"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Seed packets", "Labeled stakes", "Starter pots"],
    seasonalObjects: ["Spring planting emphasis"],
    interactiveObjects: ["Browse Spark Cards / early ideas"],
    relatedPlaces: ["greenhouse", "apple-orchard", "momentum-institute"],
    status: "planned",
    expansionNotes: "Linked from Greenhouse™ via conversation",
  },
  {
    id: "growth-profile",
    officialName: "Growth Profile™",
    category: "collection",
    primaryFeeling: "Quiet pride, earned capability",
    backgroundImage: "/backgrounds/greenhouse-background.png",
    aliases: ["growth profile", "how am I growing", "my capabilities"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "personal-continuity",
    permanentObjects: ["Growth ledger", "Timeline markers"],
    seasonalObjects: [],
    interactiveObjects: [
      "Review capability growth (quiet, not dashboard)",
    ],
    relatedPlaces: ["momentum-institute", "evidence-vault", "stables"],
    status: "live",
    expansionNotes: "Not the Greenhouse — shared art only",
  },
  {
    id: "my-estate",
    officialName: "My Estate™",
    category: "collection",
    primaryFeeling: "Ownership, continuity, belonging",
    backgroundImage: "/backgrounds/spark-estate-photo-background.png",
    aliases: ["my estate", "estate profile"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "personal-continuity",
    permanentObjects: ["Personal estate photo", "Mementos"],
    seasonalObjects: ["Photo may reflect season (subtle)"],
    interactiveObjects: ["Preferences (conversation-led)", "Profile"],
    relatedPlaces: ["growth-profile", "institute-cabinet", "evidence-vault"],
    status: "live",
    expansionNotes: "Not a settings app with wallpaper",
  },
  {
    id: "accomplishments-shelf",
    officialName: "Accomplishments Book™ (Library shelf)",
    category: "collection",
    primaryFeeling: "Honored story, legacy",
    backgroundImage: null,
    aliases: [
      "accomplishments book",
      "my accomplishments book",
      "the accomplishments book",
      "show me my accomplishments",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "celebration-ritual",
    permanentObjects: ["Volumes on shelf", "Ribbon markers"],
    seasonalObjects: ["New volume binding (quiet)"],
    interactiveObjects: [
      "Open volume",
      "Read story",
      "Add chapter (permission)",
    ],
    relatedPlaces: ["library", "celebration-room"],
    status: "planned",
    suggestionProfiles: ["celebrate"],
    expansionNotes: "Bible Ch. 17; pairs with Bell in celebration-room",
  },

  // —— Transition Spaces ——
  {
    id: "main-hallway",
    officialName: "Main Hallway",
    category: "transition-space",
    primaryFeeling: "Belonging, flow, quiet",
    backgroundImage: null,
    aliases: ["hallway", "down the hall"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Art", "Runner rug", "Soft lamps"],
    seasonalObjects: ["Holiday garland (subtle)"],
    interactiveObjects: [],
    relatedPlaces: ["welcome-home", "main-staircase", "library"],
    status: "planned",
    expansionNotes: "Never blocks with menus",
  },
  {
    id: "main-staircase",
    officialName: "Main Staircase",
    category: "transition-space",
    primaryFeeling: "Vertical calm, discovery",
    backgroundImage: "/backgrounds/reading-nook-under-stairway-background.png",
    aliases: ["stairs", "up the stairs", "main staircase", "stairway reading nook"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Stairs", "Landing", "Reading nook below"],
    seasonalObjects: [],
    interactiveObjects: ["Pause on landing"],
    relatedPlaces: ["reading-nook", "library", "main-hallway"],
    status: "partial",
    expansionNotes: "Connects to Reading Nook",
  },
  {
    id: "front-drive",
    officialName: "Front Drive",
    category: "transition-space",
    primaryFeeling: "Arrival, anticipation",
    backgroundImage: null,
    aliases: ["drive up", "arriving"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Drive", "Trees", "Porch light"],
    seasonalObjects: ["Snow", "Autumn leaves"],
    interactiveObjects: [],
    relatedPlaces: ["welcome-home"],
    status: "planned",
    expansionNotes: "Cinematic optional; skippable",
  },
  {
    id: "garden-path",
    officialName: "Garden Path",
    category: "transition-space",
    primaryFeeling: "Movement, seasonal air",
    backgroundImage: null,
    aliases: ["garden path", "walk with me"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Gravel or stone path", "Plantings"],
    seasonalObjects: ["Full seasonal guide"],
    interactiveObjects: ["Walk"],
    relatedPlaces: [
      "gardens",
      "greenhouse",
      "apple-orchard",
      "celebration-room",
    ],
    status: "partial",
    suggestionProfiles: ["stressed"],
    expansionNotes: "Orchard ↔ greenhouse ↔ celebration",
  },
  {
    id: "woodland-path",
    officialName: "Woodland Path",
    category: "transition-space",
    primaryFeeling: "Calm approach, anticipation",
    backgroundImage: "/backgrounds/peaceful-places/woodland-pathway.png",
    aliases: ["woodland path", "into the trees"],
    arrivalBehavior: "pass-through",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Trees", "Filtered light"],
    seasonalObjects: ["Mud and mist (autumn)", "Bird song (spring)"],
    interactiveObjects: ["Walk into Peaceful Places™"],
    relatedPlaces: ["peaceful-places", "seat-at-pond"],
    status: "needs-asset",
    expansionNotes: "Entry to Peaceful Places™",
  },
  {
    id: "balcony",
    officialName: "Balcony",
    category: "transition-space",
    primaryFeeling: "Overlook, pause",
    backgroundImage: null,
    aliases: ["balcony", "overlook"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Railing", "Chairs"],
    seasonalObjects: ["Seasonal light on gardens"],
    interactiveObjects: ["Look out"],
    relatedPlaces: ["gardens", "main-staircase"],
    status: "planned",
    expansionNotes: "Evening affinity",
  },
  {
    id: "bridge",
    officialName: "Garden Bridge",
    category: "transition-space",
    primaryFeeling: "Crossing, gentle discovery",
    backgroundImage: null,
    aliases: ["bridge", "over the stream"],
    arrivalBehavior: "pass-through",
    conversationStyle: "open-presence",
    permanentObjects: ["Wooden bridge", "Stream below"],
    seasonalObjects: [],
    interactiveObjects: ["Cross"],
    relatedPlaces: ["garden-path", "gardens"],
    status: "future",
    expansionNotes: "Section 02 — future grounds",
  },
] as const;
