/**
 * Canonical sub-rooms, objects, and nested experiences — synced to routing map.
 * @internal Import via canonicalEstateRegistry.ts only.
 */

import type { CanonicalEstatePlace } from "./canonicalEstateRegistryTypes";

/** Possibility House™, Legacy Room™, Observatory subspaces, Reflection Tree™ */
export const CANONICAL_ESTATE_SUBPLACES: readonly CanonicalEstatePlace[] = [
  // —— Possibility House™ ——
  {
    id: "house-possibility-outside",
    officialName: "Possibility House",
    category: "destination",
    primaryFeeling: "Wonder, gentle curiosity, open futures",
    backgroundImage: null,
    aliases: [
      "possibility house",
      "the possibility house",
      "house of possibility",
    ],
    arrivalBehavior: "threshold",
    conversationStyle: "discovery-dialogue",
    permanentObjects: ["Front steps", "Warm light in windows", "Garden path"],
    seasonalObjects: ["Fireflies (summer)", "Frost on railings (winter)"],
    interactiveObjects: ["Enter the studio", "Discovery Chest", "Curiosity Cabinet"],
    relatedPlaces: [
      "house-possibility-staircase",
      "house-possibility-studio",
      "house-possibility-reflection-desk",
      "house-possibility-observatory",
      "house-possibility-telescope-deck",
      "house-possibility-cabinet-of-chapters",
      "house-possibility-discovery-chest",
      "house-possibility-legacy-room",
      "creative-studio",
    ],
    status: "planned",
    routeType: "room",
    purpose: "Explore what might be — futures, ideas, and gentle curiosity",
    availableActions: ["enter", "explore", "sit outside"],
    suggestionProfiles: ["curious", "creative"],
  },
  {
    id: "house-possibility-studio",
    officialName: "Possibility Studio",
    category: "destination",
    primaryFeeling: "Creative calm, open canvas",
    backgroundImage: null,
    aliases: ["possibility studio", "the possibility studio", "studio in the possibility house"],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "creative-collaboration",
    permanentObjects: ["Work table", "Soft northern light", "Pin board"],
    seasonalObjects: [],
    interactiveObjects: ["Dream Wall", "Sketch", "Talk through an idea"],
    relatedPlaces: ["house-possibility-outside", "house-possibility-dream-wall"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "house-possibility-outside",
    purpose: "Quiet making and thinking about what could be",
    availableActions: ["create", "reflect", "return outside"],
  },
  {
    id: "house-possibility-dream-wall",
    officialName: "Dream Wall",
    category: "destination",
    primaryFeeling: "Hope, possibility pinned gently",
    backgroundImage: null,
    aliases: ["dream wall", "the dream wall", "possibility dream wall"],
    arrivalBehavior: "object-invitation",
    conversationStyle: "reflective-writing",
    permanentObjects: ["Pinned hopes", "Soft pins", "Warm lamp"],
    seasonalObjects: [],
    interactiveObjects: ["Add a dream", "Read what is pinned"],
    relatedPlaces: ["house-possibility-studio"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "house-possibility-outside",
    purpose: "See and tend the ideas you are growing toward",
    availableActions: ["view", "add", "return to studio"],
  },
  {
    id: "house-possibility-telescope-deck",
    officialName: "Telescope Deck",
    category: "destination",
    primaryFeeling: "Wide horizon, quiet wonder",
    backgroundImage: null,
    aliases: [
      "telescope deck",
      "the telescope deck",
      "possibility house telescope",
      "deck telescope",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "open-presence",
    permanentObjects: ["Brass telescope", "Deck railing", "Evening sky"],
    seasonalObjects: ["Clear winter stars", "Summer haze"],
    interactiveObjects: ["Look out", "Sit on the deck"],
    relatedPlaces: ["house-possibility-outside", "observatory"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "house-possibility-outside",
    purpose: "Look outward — calm curiosity without urgency",
    availableActions: ["look", "sit", "enjoy the view"],
    suggestionProfiles: ["curious", "rest"],
  },
  {
    id: "house-possibility-discovery-chest",
    officialName: "Discovery Chest",
    category: "collection",
    primaryFeeling: "Delight, surprise, gentle treasure",
    backgroundImage: null,
    aliases: [
      "discovery chest",
      "the discovery chest",
      "show me the discovery chest",
      "open the discovery chest",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "discovery-dialogue",
    permanentObjects: ["Brass latch", "Soft lining", "Folded notes"],
    seasonalObjects: [],
    interactiveObjects: ["Open the chest", "Browse discoveries"],
    relatedPlaces: ["house-possibility-outside", "house-possibility-curiosity-cabinet"],
    status: "planned",
    routeType: "object",
    parentPlaceId: "house-possibility-outside",
    purpose: "Find saved sparks, ideas, and gentle surprises",
    availableActions: ["open", "show", "browse"],
  },
  {
    id: "house-possibility-curiosity-cabinet",
    officialName: "Curiosity Cabinet",
    category: "collection",
    primaryFeeling: "Wonder, small treasures, patient looking",
    backgroundImage: null,
    aliases: [
      "curiosity cabinet",
      "the curiosity cabinet",
      "open the curiosity cabinet",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "discovery-dialogue",
    permanentObjects: ["Glass doors", "Small drawers", "Labels in pencil"],
    seasonalObjects: [],
    interactiveObjects: ["Open a drawer", "Examine a find"],
    relatedPlaces: ["house-possibility-outside", "house-possibility-discovery-chest"],
    status: "planned",
    routeType: "object",
    parentPlaceId: "house-possibility-outside",
    purpose: "Browse curiosities saved over time",
    availableActions: ["open", "show", "examine"],
  },
  {
    id: "house-possibility-window-nook",
    officialName: "Window Nook",
    category: "living-place",
    primaryFeeling: "Soft light, unhurried pause",
    backgroundImage: null,
    aliases: ["window nook", "the window nook", "possibility house window nook"],
    arrivalBehavior: "presence-only",
    conversationStyle: "open-presence",
    permanentObjects: ["Cushioned seat", "Garden view", "Throw blanket"],
    seasonalObjects: ["Rain on glass (spring)"],
    interactiveObjects: ["Sit", "Look out", "Enjoy the Estate"],
    relatedPlaces: ["house-possibility-outside", "reading-nook"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "house-possibility-outside",
    purpose: "Rest by the window without needing to do anything",
    availableActions: ["sit", "enjoy the view", "hide chat"],
    suggestionProfiles: ["rest", "quiet"],
  },
  {
    id: "house-possibility-staircase",
    officialName: "Possibility Staircase",
    category: "destination",
    primaryFeeling: "Upward curiosity, soft light, unhurried ascent",
    backgroundImage: null,
    aliases: [
      "possibility staircase",
      "the possibility staircase",
      "staircase in the possibility house",
      "treehouse staircase",
      "the treehouse staircase",
    ],
    arrivalBehavior: "ambient-crossfade",
    conversationStyle: "discovery-dialogue",
    permanentObjects: ["Curved steps", "Window light", "Reading nook landing"],
    seasonalObjects: [],
    interactiveObjects: ["Climb slowly", "Pause at the window nook"],
    relatedPlaces: ["house-possibility-outside", "house-possibility-window-nook", "house-possibility-studio"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "house-possibility-outside",
    purpose: "Move between floors with wonder — not hurry",
    availableActions: ["explore", "sit in the nook", "continue upward"],
    suggestionProfiles: ["curious", "reflective"],
  },
  {
    id: "house-possibility-reflection-desk",
    officialName: "Reflection Desk",
    category: "destination",
    primaryFeeling: "Still thinking, ink and quiet, honest looking back",
    backgroundImage: null,
    aliases: [
      "reflection desk",
      "the reflection desk",
      "possibility reflection desk",
      "treehouse reflection desk",
      "desk in the possibility house",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "reflective-writing",
    permanentObjects: ["Writing desk", "Soft lamp", "Open journal"],
    seasonalObjects: [],
    interactiveObjects: ["Write a reflection", "Review what matters"],
    relatedPlaces: ["house-possibility-outside", "house-possibility-observatory"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "house-possibility-outside",
    purpose: "Pause and reflect on what you are becoming",
    availableActions: ["write", "reflect", "sit quietly"],
    suggestionProfiles: ["reflective", "quiet"],
  },
  {
    id: "house-possibility-observatory",
    officialName: "Possibility Observatory",
    category: "destination",
    primaryFeeling: "Wide horizon, night sky wonder, perspective",
    backgroundImage: null,
    aliases: [
      "possibility observatory",
      "the possibility observatory",
      "treehouse observatory",
      "observatory in the possibility house",
      "the treehouse observatory",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "open-presence",
    permanentObjects: ["Great window", "Telescope", "Star charts"],
    seasonalObjects: ["Clear winter stars"],
    interactiveObjects: ["Look out", "Study the horizon"],
    relatedPlaces: ["house-possibility-outside", "house-possibility-telescope-deck", "observatory"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "house-possibility-outside",
    purpose: "See farther — calm curiosity from the Treehouse",
    availableActions: ["look", "sit", "enjoy the view"],
    suggestionProfiles: ["curious", "rest", "learn"],
  },
  {
    id: "house-possibility-cabinet-of-chapters",
    officialName: "Cabinet of Chapters",
    category: "collection",
    primaryFeeling: "Archive, lineage, honored milestones",
    backgroundImage: null,
    aliases: [
      "cabinet of chapters",
      "the cabinet of chapters",
      "open the cabinet of chapters",
      "show me the cabinet of chapters",
      "possibility cabinet of chapters",
      "treehouse cabinet of chapters",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Glass doors", "Chapter volumes", "Brass pulls"],
    seasonalObjects: [],
    interactiveObjects: ["Open the cabinet", "Browse chapters", "Add a chapter"],
    relatedPlaces: ["house-possibility-outside", "house-possibility-legacy-room", "house-possibility-discovery-chest"],
    status: "planned",
    routeType: "object",
    parentPlaceId: "house-possibility-outside",
    purpose: "Browse the chapters of your Treehouse journey",
    availableActions: ["open", "show", "browse", "add"],
  },
  {
    id: "house-possibility-legacy-room",
    officialName: "Legacy Room",
    category: "destination",
    primaryFeeling: "Honored story, continuity, quiet pride",
    backgroundImage: null,
    aliases: [
      "legacy room",
      "the legacy room",
      "possibility legacy room",
      "treehouse legacy room",
      "legacy room in the possibility house",
    ],
    arrivalBehavior: "threshold",
    conversationStyle: "reflective-writing",
    permanentObjects: ["Fireplace glow", "Framed moments", "Open doors"],
    seasonalObjects: [],
    interactiveObjects: ["Reflect on your story", "Browse legacy", "Sit by the fire"],
    relatedPlaces: ["house-possibility-outside", "house-possibility-cabinet-of-chapters"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "house-possibility-outside",
    purpose: "Honor the story you are building in the Treehouse",
    availableActions: ["reflect", "browse", "sit quietly"],
    suggestionProfiles: ["reflective", "celebrate"],
  },
  // —— Legacy Room™ (main Estate wing) ——
  {
    id: "legacy-room-main",
    officialName: "Legacy Room",
    category: "destination",
    primaryFeeling: "Honored story, continuity, quiet pride",
    backgroundImage: null,
    aliases: [
      "main estate legacy room",
      "estate legacy room",
    ],
    arrivalBehavior: "threshold",
    conversationStyle: "reflective-writing",
    permanentObjects: ["Fireplace glow", "Framed moments", "Writing desk"],
    seasonalObjects: ["Holiday garland (winter)"],
    interactiveObjects: ["Legacy Desk", "Cabinet of Chapters", "Reflection Corner"],
    relatedPlaces: [
      "legacy-room-legacy-desk",
      "legacy-room-cabinet-of-chapters",
      "accomplishments-shelf",
    ],
    status: "planned",
    routeType: "room",
    purpose: "Honor the story you are building — past, present, and what continues",
    availableActions: ["reflect", "write", "browse legacy"],
    suggestionProfiles: ["reflective", "celebrate"],
  },
  {
    id: "legacy-room-reflection-corner",
    officialName: "Reflection Corner",
    category: "living-place",
    primaryFeeling: "Stillness, gratitude, gentle looking back",
    backgroundImage: null,
    aliases: [
      "reflection corner",
      "the reflection corner",
      "legacy reflection corner",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Armchair", "Side table", "Soft lamp"],
    seasonalObjects: [],
    interactiveObjects: ["Sit", "Reflect quietly"],
    relatedPlaces: ["legacy-room-main"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "legacy-room-main",
    purpose: "Pause and reflect without producing anything",
    availableActions: ["sit", "reflect", "enjoy the room"],
    suggestionProfiles: ["reflective", "rest"],
  },
  {
    id: "legacy-room-legacy-desk",
    officialName: "Legacy Desk",
    category: "destination",
    primaryFeeling: "Continuity, authorship, honored craft",
    backgroundImage: null,
    aliases: [
      "legacy desk",
      "the legacy desk",
      "go to the legacy desk",
      "take me to the legacy desk",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "reflective-writing",
    permanentObjects: ["Inkwell", "Leather blotter", "Family photos"],
    seasonalObjects: [],
    interactiveObjects: ["Write", "Review drafts", "Save a note"],
    relatedPlaces: ["legacy-room-main", "legacy-room-cabinet-of-chapters"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "legacy-room-main",
    purpose: "Write and tend the story you want to leave behind",
    availableActions: ["write", "review", "save"],
  },
  {
    id: "legacy-room-cabinet-of-chapters",
    officialName: "Cabinet of Chapters",
    category: "collection",
    primaryFeeling: "Archive, lineage, honored milestones",
    backgroundImage: null,
    aliases: [
      "legacy room cabinet of chapters",
      "cabinet in the legacy room",
      "main estate cabinet of chapters",
    ],
    arrivalBehavior: "object-invitation",
    conversationStyle: "archive-browsing",
    permanentObjects: ["Glass doors", "Chapter volumes", "Brass pulls"],
    seasonalObjects: [],
    interactiveObjects: ["Open the cabinet", "Browse chapters", "Add a chapter"],
    relatedPlaces: ["legacy-room-main", "accomplishments-shelf", "library"],
    status: "planned",
    routeType: "object",
    parentPlaceId: "legacy-room-main",
    purpose: "Browse the chapters of your journey — wins, pivots, and growth",
    availableActions: ["open", "show", "browse", "add"],
  },
  // —— Observatory subspaces ——
  {
    id: "observatory-telescope-window",
    officialName: "Telescope Window",
    category: "destination",
    primaryFeeling: "Focused wonder, night sky, quiet study",
    backgroundImage: null,
    aliases: [
      "telescope window",
      "the telescope window",
      "observatory telescope",
      "inside the observatory",
      "observatory inside",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "research-companion",
    permanentObjects: ["Brass telescope", "Star charts", "Reading chair"],
    seasonalObjects: [],
    interactiveObjects: ["Look through the telescope", "Study charts"],
    relatedPlaces: ["observatory", "observatory-fireplace"],
    status: "needs-asset",
    routeType: "subspace",
    parentPlaceId: "observatory",
    sceneViewId: "day-inside",
    purpose: "Study the horizon through the telescope",
    availableActions: ["look", "study", "sit"],
    suggestionProfiles: ["learn", "curious"],
  },
  {
    id: "observatory-fireplace",
    officialName: "Observatory Fireplace",
    category: "living-place",
    primaryFeeling: "Warmth, unhurried thinking, ember calm",
    backgroundImage: null,
    aliases: [
      "observatory fireplace",
      "the observatory fireplace",
      "fireplace in the observatory",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Stone hearth", "Low flames", "Wingback chair"],
    seasonalObjects: ["Extra logs (winter)"],
    interactiveObjects: ["Sit by the fire", "Think quietly"],
    relatedPlaces: ["observatory", "observatory-telescope-window"],
    status: "planned",
    routeType: "subspace",
    parentPlaceId: "observatory",
    purpose: "Think by the fire without a research agenda",
    availableActions: ["sit", "warm up", "enjoy the room"],
    suggestionProfiles: ["think", "rest"],
  },
  // —— Reflection Tree™ ——
  {
    id: "reflection-tree-main",
    officialName: "Reflection Tree",
    category: "living-place",
    primaryFeeling: "Rooted calm, seasonal wisdom, gentle perspective",
    backgroundImage: null,
    aliases: [
      "reflection tree",
      "the reflection tree",
      "take me to the reflection tree",
    ],
    arrivalBehavior: "presence-only",
    conversationStyle: "calm-restoration",
    permanentObjects: ["Old oak", "Bench under branches", "Fallen leaves"],
    seasonalObjects: ["Spring buds", "Autumn gold", "Winter bare branches"],
    interactiveObjects: ["Sit under the tree", "Journal nearby", "Enjoy the Estate"],
    relatedPlaces: ["reflection-pond", "gardens", "seat-at-pond"],
    status: "planned",
    routeType: "room",
    purpose: "Reflect outdoors under a tree that has seen many seasons",
    availableActions: ["sit", "reflect", "journal", "enjoy the view"],
    suggestionProfiles: ["reflective", "quiet", "rest"],
  },
];
