/**
 * Spark Estate — member-facing alias catalog (single source for navigation phrases).
 * Sync aliases into `canonicalEstatePlaces.ts` when adding new canonical places.
 *
 * @deprecated Legacy adapter — aliases now derive from
 * `docs/estate/ESTATE_PLACE_MASTER_MANIFEST.json`. Kept until manifest runtime verified.
 */

import type { AppSection } from "@/lib/companionUi";
import type { EstateRoomType } from "./types";

export type EstateRoomAliasSpec = {
  roomId: string;
  officialName: string;
  aliases: readonly string[];
  route: AppSection | null;
  roomType: EstateRoomType;
  invitationCatalogId?: string;
};

/** Longest phrases first within each room — registry sorts globally by length. */
export const ESTATE_ROOM_ALIAS_CATALOG: readonly EstateRoomAliasSpec[] = [
  {
    roomId: "welcome-home",
    officialName: "Welcome Home",
    aliases: [
      "welcome home",
      "welcome room",
      "the welcome room",
      "take me home",
      "go home",
    ],
    route: "welcome-room",
    roomType: "welcome",
  },
  {
    roomId: "spark-estate",
    officialName: "Spark Estate",
    aliases: [
      "spark estate",
      "the spark estate",
      "front estate",
      "the front estate",
      "the estate grounds",
      "estate grounds",
    ],
    route: "home",
    roomType: "welcome",
  },
  {
    roomId: "sunroom",
    officialName: "Sunroom",
    aliases: [
      "sunroom",
      "the sunroom",
      "shari's sunroom",
      "sun room",
      "sunny room",
      "glass room",
      "morning room",
    ],
    route: "welcome-room",
    roomType: "welcome",
  },
  {
    roomId: "conservatory",
    officialName: "The Conservatory",
    aliases: [
      "ocean conservatory",
      "the ocean conservatory",
      "ocean aquarium",
      "the ocean aquarium",
      "aquarium",
      "the aquarium",
      "aquarium room",
      "the aquarium room",
      "conservatory",
      "the conservatory",
      "conservatory room",
      "quiet glass room",
      "the quiet glass room",
    ],
    route: null,
    roomType: "reflection",
  },
  {
    roomId: "clear-my-mind",
    officialName: "Clear My Mind",
    aliases: [
      "clear my mind sunroom",
      "clear my mind",
      "clear my head",
      "brain dump",
    ],
    route: "brain-dump",
    roomType: "reflection",
  },
  {
    roomId: "destination-gallery",
    officialName: "Destination Gallery",
    aliases: [
      "destination gallery",
      "the destination gallery",
      "send this somewhere",
      "where should i send this",
      "where would you like me to send this",
    ],
    route: "destination-gallery",
    roomType: "planning",
  },
  {
    roomId: "butterfly-house",
    officialName: "Butterfly House",
    aliases: ["butterfly house", "the butterfly house", "butterfly conservatory", "the butterfly conservatory", "butterfly garden", "the butterfly garden"],
    route: "focus",
    roomType: "reflection",
  },
  {
    roomId: "coffee-house",
    officialName: "Coffee House",
    aliases: [
      "coffee house",
      "the coffee house",
      "coffee shop",
      "the coffee shop",
      "cozy cafe",
      "cafe",
      "the cafe",
      "café",
      "the café",
    ],
    route: "focus-audio",
    roomType: "restoration",
  },
  {
    roomId: "tea-room",
    officialName: "Tea Room",
    aliases: ["tea room", "the tea room"],
    route: "focus-audio",
    roomType: "restoration",
  },
  {
    roomId: "dining-room",
    officialName: "Dining Room",
    aliases: ["dining room", "the dining room"],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "estate-kitchen",
    officialName: "Estate Kitchen",
    aliases: [
      "estate kitchen",
      "the estate kitchen",
      "kitchen",
      "the kitchen",
    ],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "music-room",
    officialName: "Music Room",
    aliases: ["music room", "the music room"],
    route: "focus-audio",
    roomType: "restoration",
  },
  {
    roomId: "summer-terrace",
    officialName: "Summer Terrace",
    aliases: [
      "swimming pool",
      "the swimming pool",
      "summer terrace",
      "the summer terrace",
      "the pool",
      "pool",
    ],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "grand-terrace",
    officialName: "Grand Terrace",
    aliases: ["grand terrace", "the grand terrace"],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "lakeside-verandah",
    officialName: "Lakeside Verandah",
    aliases: ["lakeside verandah", "the lakeside verandah", "lakeside veranda", "by the lake", "lake view", "lakeside"],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "lakeside-hammock",
    officialName: "Lakeside Hammock",
    aliases: [
      "lakeside hammock",
      "the lakeside hammock",
      "hammock by the lake",
      "rest by the lake",
    ],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "seat-at-pond",
    officialName: "Seat at Pond / Dock",
    aliases: [
      "seat at the pond",
      "seat at pond",
      "sit by the water",
      "the dock",
      "dock",
      "pond",
      "the pond",
      "reflection pond",
      "the reflection pond",
      "pond seat",
      "quiet pond",
      "pond dock",
      "peaceful water",
      "stream bench",
      "the stream",
    ],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "fireside-deck",
    officialName: "Fireside Deck",
    aliases: [
      "fireside deck",
      "the fireside deck",
      "back deck",
      "the back deck",
      "sit outside",
      "evening air",
    ],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "personal-deck",
    officialName: "Personal Deck",
    aliases: [
      "personal deck",
      "the personal deck",
      "my deck",
      "private balcony",
      "the private balcony",
    ],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "balcony",
    officialName: "Private Balcony",
    aliases: ["balcony", "the balcony", "overlook"],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "porch-swing",
    officialName: "Porch Swing",
    aliases: ["porch swing", "the porch swing", "swing on the porch"],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "the-swing-beneath-the-oak",
    officialName: "The Swing Beneath the Oak",
    aliases: [
      "swing beneath the oak",
      "the swing beneath the oak",
      "oak swing",
      "tree swing",
      "memory swing",
      "the swing",
      "swing",
    ],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "apple-orchard",
    officialName: "Apple Orchard",
    aliases: ["apple orchard", "the apple orchard", "orchard", "the orchard"],
    route: "home",
    roomType: "nature",
  },
  {
    roomId: "estate-gardens",
    officialName: "Estate Gardens",
    aliases: [
      "estate gardens",
      "the estate gardens",
      "estate garden",
      "the estate garden",
    ],
    route: "home",
    roomType: "nature",
  },
  {
    roomId: "gardens",
    officialName: "Celebration Garden",
    aliases: [
      "celebration garden",
      "the celebration garden",
      "gardens",
      "the gardens",
      "garden",
      "the garden",
    ],
    route: "home",
    roomType: "nature",
  },
  {
    roomId: "greenhouse",
    officialName: "Greenhouse",
    aliases: [
      "working greenhouse",
      "the working greenhouse",
      "greenhouse",
      "the greenhouse",
    ],
    route: null,
    roomType: "nature",
  },
  {
    roomId: "garden-bench",
    officialName: "Garden Bench",
    aliases: ["garden bench", "the garden bench", "bench in the garden"],
    route: "home",
    roomType: "nature",
  },
  {
    roomId: "reading-nook",
    officialName: "Reading Nook",
    aliases: [
      "reading nook",
      "the reading nook",
      "quiet read",
      "arched window nook",
    ],
    route: "home",
    roomType: "reflection",
  },
  {
    roomId: "stairway-reading-nook",
    officialName: "Stairway Reading Nook",
    aliases: [
      "stairway reading nook",
      "the stairway reading nook",
      "stairs reading nook",
      "reading nook under the stairs",
      "nook under the stairs",
      "sit under the stairs",
      "under the stairs",
    ],
    route: "home",
    roomType: "reflection",
  },
  {
    roomId: "window-seat",
    officialName: "Window Seat",
    aliases: [
      "window seat",
      "the window seat",
      "sit by the window",
      "reading nook by the window",
    ],
    route: "home",
    roomType: "reflection",
  },
  {
    roomId: "library",
    officialName: "The Library",
    aliases: [
      "estate library",
      "the estate library",
      "achievement library",
      "story library",
      "library",
      "the library",
      "read something",
    ],
    route: "growth-library",
    roomType: "learning",
  },
  {
    roomId: "personal-library",
    officialName: "Personal Library",
    aliases: ["personal library", "the personal library", "my library"],
    route: "growth-library",
    roomType: "learning",
  },
  {
    roomId: "momentum-institute",
    officialName: "Momentum Institute",
    aliases: [
      "momentum institute",
      "the momentum institute",
      "momentum chamber",
      "the momentum chamber",
      "spark chamber of momentum",
      "chamber of momentum",
      "entrepreneur development center",
      "institute",
      "the institute",
    ],
    route: "chamber-of-momentum",
    roomType: "learning",
  },
  {
    roomId: "study-hall",
    officialName: "Study Hall",
    aliases: [
      "study hall",
      "the study hall",
      "classroom",
      "the classroom",
      "lecture hall",
    ],
    route: "chamber-of-momentum",
    roomType: "learning",
  },
  {
    roomId: "momentum-room",
    officialName: "Momentum Room",
    aliases: ["momentum room", "the momentum room"],
    route: "chamber-of-momentum",
    roomType: "planning",
  },
  {
    roomId: "discovery-room",
    officialName: "Discovery Room",
    aliases: ["discovery room", "the discovery room"],
    route: "home",
    roomType: "research",
  },
  {
    roomId: "observatory",
    officialName: "Observatory",
    aliases: [
      "observatory",
      "the observatory",
      "research tower",
      "what's emerging",
    ],
    route: "grow-observatory",
    roomType: "research",
  },
  {
    roomId: "creative-studio",
    officialName: "Create",
    aliases: [
      "create",
      "create experience",
      "creative studio",
      "the creative studio",
      "make something",
    ],
    route: "content-generator",
    roomType: "creation",
  },
  {
    roomId: "art-studio",
    officialName: "Art Studio",
    aliases: ["art studio", "the art studio", "artist studio"],
    route: "content-generator",
    roomType: "creation",
  },
  {
    roomId: "strategy-studio",
    officialName: "Strategy Studio",
    aliases: ["strategy studio", "the strategy studio"],
    route: "content-generator",
    roomType: "planning",
  },
  {
    roomId: "round-table",
    officialName: "Round Table",
    aliases: [
      "round table",
      "the round table",
      "boardroom",
      "the boardroom",
      "board room",
      "the board room",
    ],
    route: "boardroom",
    roomType: "planning",
  },
  {
    roomId: "journal",
    officialName: "Journal Gazebo",
    aliases: [
      "journal gazebo",
      "the journal gazebo",
      "gazebo journal",
      "growth journal",
      "journal",
      "the journal",
      "my journal",
      "gazebo",
      "the gazebo",
    ],
    route: "growth-journal",
    roomType: "reflection",
  },
  {
    roomId: "stables",
    officialName: "The Stables",
    aliases: [
      "spark stables",
      "the spark stables",
      "stables",
      "the stables",
      "stable",
      "the stable",
    ],
    route: "stables",
    roomType: "reflection",
  },
  {
    roomId: "game-room",
    officialName: "Game Room",
    aliases: [
      "game room",
      "the game room",
      "exercise room",
      "the exercise room",
    ],
    route: "quick-recharge",
    roomType: "play",
  },
  {
    roomId: "evidence-vault",
    officialName: "Evidence Vault",
    aliases: [
      "evidence vault",
      "the evidence vault",
      "my evidence vault",
      "evidence bank",
      "the evidence bank",
      "proof i can do this",
      "show me proof",
      "show me proof i can do this",
      "i need encouragement",
      "remind me what i've done",
      "remind me what i have done",
      "remind me who i am",
    ],
    route: "evidence-bank",
    roomType: "archive",
  },
  {
    roomId: "gallery-of-firsts",
    officialName: "Gallery",
    aliases: [
      "gallery of firsts",
      "the gallery of firsts",
      "gallery",
      "the gallery",
    ],
    /** Gallery ≠ Hall of Accomplishments — scene presence until exhibit UI */
    route: "home",
    roomType: "archive",
  },
  {
    roomId: "accomplishments-shelf",
    officialName: "Accomplishments Shelf",
    aliases: [
      "accomplishments shelf",
      "accomplishments book",
      "my accomplishments book",
      "the accomplishments book",
    ],
    route: "growth-library",
    roomType: "archive",
  },
  {
    roomId: "celebration-room",
    officialName: "Celebration Room",
    aliases: [
      "celebration hall",
      "the celebration hall",
      "celebration room",
      "the celebration room",
    ],
    route: "growth-reports",
    roomType: "archive",
  },
  {
    roomId: "portfolio",
    officialName: "Hall of Accomplishments",
    aliases: [
      "hall of accomplishments",
      "the hall of accomplishments",
      "my hall of accomplishments",
      "hall of achievements",
      "accomplishments hall",
      "my accomplishments",
      "show my accomplishments",
      "open hall of accomplishments",
      "open my hall of accomplishments",
      "portfolio",
      "my portfolio",
    ],
    route: "growth-portfolio",
    roomType: "archive",
  },
  {
    roomId: "decision-compass",
    officialName: "Decision Compass",
    aliases: [
      "decision compass",
      "the decision compass",
      "writing room",
      "the writing room",
    ],
    route: "decision-compass",
    roomType: "planning",
  },
  {
    roomId: "momentum-builder",
    officialName: "Momentum Builder",
    aliases: ["momentum builder", "the momentum builder", "plan my day"],
    route: "momentum-builder",
    roomType: "planning",
  },
  {
    roomId: "goals-projects",
    officialName: "Goals & Projects",
    aliases: [
      "goals and projects",
      "goals & projects",
      "my projects",
      "goals projects",
    ],
    route: "projects",
    roomType: "planning",
  },
  {
    roomId: "peaceful-places",
    officialName: "Peaceful Moments",
    aliases: [
      "peaceful moments",
      "peaceful moment",
      "peaceful places",
      "peaceful place",
      "pleasure places",
      "pleasure place",
    ],
    route: "focus-audio",
    roomType: "restoration",
  },
  {
    roomId: "estate-soundscapes",
    officialName: "Estate Soundscapes",
    aliases: [
      "estate soundscapes",
      "soundscapes",
      "soundscape",
      "take me to soundscapes",
      "focus music",
      "focus sounds",
      "calming sounds",
      "relaxing music",
      "play focus music",
      "play something peaceful",
      "i want music",
      "play music",
    ],
    route: "focus-audio",
    roomType: "restoration",
  },
  {
    roomId: "main-hallway",
    officialName: "Main Hallway",
    aliases: ["main hallway", "the main hallway", "hallway", "the hallway"],
    route: "home",
    roomType: "reflection",
  },
  {
    roomId: "main-staircase",
    officialName: "Main Staircase",
    aliases: ["main staircase", "the main staircase", "stairway", "the stairway"],
    route: "home",
    roomType: "reflection",
  },
  {
    roomId: "front-drive",
    officialName: "Front Drive",
    aliases: ["front drive", "the front drive", "driveway", "the driveway"],
    route: "home",
    roomType: "reflection",
  },
  {
    roomId: "garden-path",
    officialName: "Garden Path",
    aliases: ["garden path", "the garden path", "walk with me"],
    route: "home",
    roomType: "nature",
  },
  {
    roomId: "woodland-path",
    officialName: "Woodland Path",
    aliases: ["woodland path", "the woodland path", "into the trees"],
    route: "home",
    roomType: "nature",
  },
  {
    roomId: "bridge",
    officialName: "Garden Bridge",
    aliases: ["garden bridge", "the garden bridge", "bridge", "the bridge", "over the stream"],
    route: "home",
    roomType: "nature",
  },
  {
    roomId: "my-estate",
    officialName: "My Estate",
    aliases: ["my estate", "estate profile"],
    route: null,
    roomType: "profile",
  },
  {
    roomId: "institute-cabinet",
    officialName: "My Institute Cabinet",
    aliases: ["institute cabinet", "my institute cabinet", "my cabinet"],
    route: null,
    roomType: "archive",
  },
  {
    roomId: "seeds-planted",
    officialName: "Seeds Planted",
    aliases: ["seeds planted", "planted seeds", "spark cards", "my spark cards"],
    route: "grow-spark-cards",
    roomType: "archive",
  },
  {
    roomId: "growth-profile",
    officialName: "Growth Profile",
    aliases: ["growth profile", "my growth profile"],
    route: null,
    roomType: "profile",
  },
  /**
   * Explore Estate destinationId override — `momentum-institute` already owns
   * the spoken aliases ("chamber of momentum" etc.). This entry only lets a
   * direct-navigation call using the runtime id `chamber-of-momentum` resolve
   * (Explore Estate / Wander card select uses this id, not the legacy one).
   * @see lib/estateMap/exploreEstateDestinations.ts DESTINATION_ID_OVERRIDES
   */
  {
    roomId: "chamber-of-momentum",
    officialName: "Chamber of Momentum",
    aliases: ["chamber-of-momentum"],
    route: "chamber-of-momentum",
    roomType: "learning",
  },
  {
    roomId: "cartographers-studio",
    officialName: "Visual Thinking Studio",
    aliases: [
      "visual thinking studio",
      "visual thinking",
      "cartography",
      "cartographers studio",
      "cartographer's studio",
      "cartographer studio",
      "the cartographer's studio",
    ],
    route: "visual-focus",
    roomType: "research",
  },
  {
    roomId: "horizon-point",
    officialName: "Horizon Point",
    aliases: ["horizon point", "the horizon point"],
    route: "home",
    roomType: "nature",
  },
  {
    roomId: "estate-back-deck",
    officialName: "Estate Back Deck",
    aliases: ["estate back deck", "the estate back deck", "back deck"],
    route: "home",
    roomType: "restoration",
  },
  {
    roomId: "back-fireside-deck-rain",
    officialName: "Back Fireside Deck Rain",
    aliases: [
      "back fireside deck rain",
      "rainy fireside deck",
      "fireside deck in the rain",
    ],
    route: "home",
    roomType: "restoration",
  },
] as const;
