/**
 * Estate Room Registry™ — **legacy runtime catalog** (27 walkable rooms).
 *
 * @deprecated **Not authoritative.** Phase B: `canonicalEstateRegistry.ts` is the single
 * source of truth for place identity. This file will be **replaced later** — keep for routing,
 * UI, and intelligence adapters until Phase C+ migration.
 *
 * @see lib/estate/canonicalEstateRegistry.ts
 * @see docs/estate/SPARK_ESTATE_CANONICAL_REGISTRY.md
 * @see docs/estate/PHASE_B_RUNTIME_REGISTRY_REPORT.md
 */

import type { EstateRoomDefinition } from "./types";
import { ESTATE_ROOM_BG } from "./estateRoomAssets";

/** Room plate assets referenced in code but not yet in public/backgrounds — see intendedBackgroundImage. */
const NEEDS_ASSET = "image-ready-needs-asset" as const;

export const ESTATE_ROOM_REGISTRY: readonly EstateRoomDefinition[] = [
  {
    id: "welcome-home",
    name: "Welcome Home",
    trademark: "Welcome Home™",
    route: "home",
    routes: ["welcome-room", "today"],
    backgroundImage: null,
    intendedBackgroundImage: "/backgrounds/welcome-home-background.png",
    estateRegistryId: "welcome-home",
    homesteadRoomId: "living-room",
    roomType: "welcome",
    purpose: "Estate arrival — every conversation can begin here with continuity, not a blank app.",
    emotionalFeeling: "Belonging, warmth, orientation, hope",
    whatMembersDo: "Arrive, continue where they left off, talk with Shari, choose what matters today.",
    whatShariDoes: "Greets without pressure, remembers context, offers one gentle next step — never a dashboard.",
    whenToRecommend: [
      "member returns after absence",
      "needs orientation without overwhelm",
      "conversation should stay primary",
    ],
    relatedRoomIds: ["coffee-house", "peaceful-places", "momentum-builder"],
    navigationPhrases: [
      "welcome home",
      "go home",
      "take me home",
      "back to welcome home",
    ],
    estateIntelligenceExamples: [
      "I just got here — where should I start?",
      "Let's pick up where we left off.",
    ],
    status: NEEDS_ASSET,
  },
  {
    id: "conservatory",
    name: "The Conservatory",
    trademark: "The Conservatory™",
    route: null,
    routes: ["brain-dump"],
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.butterflyConservatory,
    estateRegistryId: "conservatory",
    roomType: "reflection",
    purpose: "Restoration, clarity, gentle thinking — garden glass and unhurried reflection.",
    emotionalFeeling: "Restoration, clarity, gentle thinking",
    whatMembersDo:
      "Clear their mind, journal, visit Peaceful Places™, or talk with Shari — nothing required.",
    whatShariDoes:
      "Thinks alongside — never rushes to solutions; holds space for understanding.",
    whenToRecommend: [
      "member wants restoration or clarity",
      "gentle thinking without a productivity agenda",
      "needs a beautiful thinking atmosphere",
    ],
    relatedRoomIds: ["clear-my-mind", "journal", "peaceful-places"],
    navigationPhrases: [
      "conservatory",
      "the conservatory",
      "take me to the conservatory",
    ],
    estateIntelligenceExamples: [
      "I need to think this through in a quiet place.",
    ],
    status: "planned",
  },
  {
    id: "library",
    name: "The Library",
    trademark: "The Library™",
    route: "growth-library",
    routes: ["how-do-i"],
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.library,
    homesteadRoomId: "library",
    roomType: "learning",
    purpose: "Quiet reading and story — wisdom on the shelves, not a course catalog.",
    emotionalFeeling: "Curiosity, timelessness, intellectual warmth",
    whatMembersDo: "Browse stories, how-to guidance, and growth library content.",
    whatShariDoes: "Suggests what might help — never assigns reading lists.",
    whenToRecommend: [
      "member wants stories or how-to without Institute depth",
      "gentle learning outside drawer wall",
    ],
    relatedRoomIds: ["momentum-institute", "observatory"],
    navigationPhrases: ["library", "the library", "story library"],
    estateIntelligenceExamples: ["I want to read something inspiring."],
    status: NEEDS_ASSET,
  },
  {
    id: "momentum-institute",
    name: "The Momentum Institute",
    trademark: "Momentum Institute™",
    route: "momentum-institute",
    routes: [],
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.momentumInstitute,
    estateRegistryId: "momentum-institute",
    homesteadRoomId: "library",
    roomType: "learning",
    purpose: "Entrepreneur Development Center — drawer wall, Knowledge Cards™, capability growth.",
    emotionalFeeling: "Discovery, prestige, curiosity, earned capability",
    whatMembersDo: "Open drawers, explore index cards, learn, reflect, apply, save to cabinet.",
    whatShariDoes:
      "Knows every drawer; may say 'I have just the drawer for that' and open the right collection.",
    whenToRecommend: [
      "learn pricing, marketing, leadership, executive function",
      "build entrepreneurial capability",
      "imposter syndrome, confidence, networking skills",
    ],
    relatedRoomIds: ["institute-cabinet", "growth-profile", "observatory"],
    navigationPhrases: [
      "momentum institute",
      "the institute",
      "open the institute",
      "entrepreneur development center",
    ],
    estateIntelligenceExamples: [
      "I want to learn pricing.",
      "Teach me about marketing.",
      "Help me with confidence as an entrepreneur.",
    ],
    status: NEEDS_ASSET,
  },
  {
    id: "coffee-house",
    name: "The Coffee House",
    trademark: "Coffee House™",
    route: null,
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.coffeeHouse,
    estateRegistryId: "coffee-house",
    roomType: "restoration",
    purpose: "Warm reflective pause — conversation, debrief, celebrate without productivity pressure.",
    emotionalFeeling: "Warmth, ease, gentle company",
    whatMembersDo: "Pause, debrief, reflect, enjoy quiet conversation energy.",
    whatShariDoes: "Offers warmth and presence — never turns rest into a task list.",
    whenToRecommend: [
      "need a breather",
      "want coffee-shop energy",
      "debrief after something hard or good",
    ],
    relatedRoomIds: ["peaceful-places", "journal", "welcome-home"],
    navigationPhrases: [
      "coffee house",
      "coffee shop",
      "cozy cafe",
      "let's get coffee",
    ],
    estateIntelligenceExamples: [
      "I want coffee and conversation.",
      "I need a break somewhere warm.",
    ],
    status: "partial",
  },
  {
    id: "creative-studio",
    name: "Create",
    trademark: "Create",
    route: "content-generator",
    backgroundImage: null,
    intendedBackgroundImage: "/backgrounds/room-create-studio-background.png",
    estateRegistryId: "creative-studio",
    roomType: "creation",
    purpose: "Bring ideas to life — writing, design, brainstorming, and building with Spark beside you.",
    emotionalFeeling: "Creative calm, possibility, craft",
    whatMembersDo: "Write, build workshops, draft content, collaborate on assets.",
    whatShariDoes: "Creates with permission — drafts stay hidden until the member is ready.",
    whenToRecommend: [
      "write a newsletter",
      "build a workshop",
      "create content",
      "make something real",
    ],
    relatedRoomIds: ["momentum-institute", "portfolio", "momentum-builder"],
    navigationPhrases: ["creative studio", "the studio", "open the studio"],
    estateIntelligenceExamples: [
      "I want to write a newsletter.",
      "Help me build a workshop.",
    ],
    status: NEEDS_ASSET,
  },
  {
    id: "observatory",
    name: "The Observatory",
    trademark: "Observatory™",
    route: "grow-observatory",
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.observatory,
    estateRegistryId: "observatory",
    roomType: "research",
    purpose: "Curated research on AI, business, technology, and innovation — explore before you commit.",
    emotionalFeeling: "Wonder, foresight, calm curiosity",
    whatMembersDo: "Explore trends, tools, and ideas worth attention.",
    whatShariDoes: "Surfaces what matters — never dumps information.",
    whenToRecommend: [
      "research AI tools",
      "what's emerging in my industry",
      "explore before deciding",
    ],
    relatedRoomIds: ["momentum-institute", "creative-studio", "decision-compass"],
    navigationPhrases: ["observatory", "the observatory", "research tower"],
    estateIntelligenceExamples: [
      "I want to research AI tools.",
      "What's new in business technology?",
    ],
    status: NEEDS_ASSET,
  },
  {
    id: "music-room",
    name: "The Music Room",
    trademark: "Music Room™",
    route: "focus-audio",
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.musicRoom,
    roomType: "restoration",
    purpose: "Gentle focus through music — think alongside sound without performance pressure.",
    emotionalFeeling: "Focus, warmth, creative calm",
    whatMembersDo: "Listen, focus, restore attention with piano and ambient music.",
    whatShariDoes: "May suggest the Music Room or a Peaceful Place — member chooses.",
    whenToRecommend: ["I want music", "need focus music", "play piano while I work"],
    relatedRoomIds: ["peaceful-places", "coffee-house"],
    navigationPhrases: [
      "music room",
      "the music room",
      "take me to the music room",
      "go to the music room",
      "play music",
      "want music",
      "i want music",
    ],
    estateIntelligenceExamples: [
      "I want music while I think.",
      "Take me somewhere with a piano.",
    ],
    status: "partial",
  },
  {
    id: "tea-room",
    name: "The Tea Room",
    trademark: "Tea Room™",
    route: null,
    backgroundImage: null,
    roomType: "restoration",
    purpose: "Unhurried conversation and ceremony — a softer pause than the Coffee House.",
    emotionalFeeling: "Stillness, ritual, gentle hospitality",
    whatMembersDo: "Pause, reflect, enjoy unhurried conversation.",
    whatShariDoes: "Offers quiet hospitality — when this room ships.",
    whenToRecommend: ["need stillness", "tea and talk", "quiet ceremony"],
    relatedRoomIds: ["coffee-house", "peaceful-places", "journal"],
    navigationPhrases: ["tea room", "the tea room", "let's have tea"],
    estateIntelligenceExamples: ["I want to visit the Tea Room."],
    status: "future",
  },
  {
    id: "game-room",
    name: "The Game Room",
    trademark: "Game Room™",
    route: "games",
    routes: ["activities", "quick-recharge"],
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.gameRoom,
    homesteadRoomId: "game-room",
    roomType: "play",
    purpose: "Momentum Builders and playful recharge — movement without guilt.",
    emotionalFeeling: "Playfulness, relief, light momentum",
    whatMembersDo: "Play recharge games, quick resets, momentum builders.",
    whatShariDoes: "Suggests play when rest disguised as stuck — never gamifies self-worth.",
    whenToRecommend: [
      "need a brain break",
      "quick recharge",
      "stuck and need something light",
    ],
    relatedRoomIds: ["peaceful-places", "momentum-builder"],
    navigationPhrases: ["game room", "the game room", "let's play"],
    estateIntelligenceExamples: ["I need a quick game break."],
    status: NEEDS_ASSET,
  },
  {
    id: "gardens",
    name: "The Gardens",
    trademark: "The Gardens™",
    route: "wins-this-week",
    routes: ["focus-audio", "breathe"],
    backgroundImage: null,
    intendedBackgroundImage: "/backgrounds/space-celebration-garden-background.png",
    roomType: "nature",
    purpose: "Outdoor restoration — celebration, reflection, and garden pathways across the Estate.",
    emotionalFeeling: "Growth, peace, celebration, natural rhythm",
    whatMembersDo: "Celebrate wins, walk pathways, restore in garden destinations.",
    whatShariDoes: "May invite a garden stroll when reflection or celebration fits.",
    whenToRecommend: [
      "celebrate a win",
      "need nature",
      "walk in the garden",
      "reflection outdoors",
    ],
    relatedRoomIds: ["apple-orchard", "peaceful-places", "journal"],
    navigationPhrases: [
      "gardens",
      "the gardens",
      "visit the gardens",
      "reflection garden",
      "celebration garden",
    ],
    estateIntelligenceExamples: [
      "Let's visit the Gardens.",
      "I want to celebrate outside.",
    ],
    status: NEEDS_ASSET,
  },
  {
    id: "greenhouse",
    name: "The Greenhouse",
    trademark: "Greenhouse™",
    route: null,
    routes: ["growth-greenhouse"],
    backgroundImage: ESTATE_ROOM_BG.greenhouse,
    intendedBackgroundImage: ESTATE_ROOM_BG.greenhouse,
    roomType: "nature",
    purpose: "This is where possibilities begin — nurture ideas before anything is rushed.",
    emotionalFeeling: "Possibility, patience, safe emergence",
    whatMembersDo:
      "Plant ideas, nurture seedlings, visit Seeds Planted™ — Kinsey asleep nearby signals this is a safe place.",
    whatShariDoes:
      "Helps ideas take shape at their own pace — never rushes harvest.",
    whenToRecommend: [
      "develop a new idea",
      "grow a concept",
      "plant a seed",
      "explore possibilities",
    ],
    relatedRoomIds: ["seeds-planted", "gardens", "goals-projects", "portfolio"],
    navigationPhrases: ["greenhouse", "the greenhouse", "visit the greenhouse"],
    estateIntelligenceExamples: ["Take me to the Greenhouse."],
    status: "live",
  },
  {
    id: "stables",
    name: "The Stables",
    trademark: "The Stables™",
    route: "stables",
    backgroundImage: ESTATE_ROOM_BG.stables,
    roomType: "restoration",
    purpose:
      "Develop leadership, trust, confidence, and calm through stories, analogies, reflection, and coaching — the horse is metaphor.",
    emotionalFeeling: "Safe, grounded, calm, present, confident, capable",
    whatMembersDo:
      "Choose a Stables experience, reflect, take small confidence steps, save insights when ready.",
    whatShariDoes:
      "Speaks slower and warmer — stories and coaching, not lectures. May say: Let's spend a few minutes at the Stables™.",
    whenToRecommend: [
      "nervous",
      "lack confidence",
      "afraid to raise prices",
      "avoiding networking",
      "afraid of speaking",
      "don't trust myself",
      "second guessing",
      "afraid of rejection",
    ],
    relatedRoomIds: [
      "momentum-institute",
      "decision-compass",
      "creative-studio",
      "journal",
      "evidence-vault",
      "growth-profile",
    ],
    navigationPhrases: [
      "stables",
      "the stables",
      "take me to the stables",
      "go to the stables",
    ],
    estateIntelligenceExamples: [
      "I want to go to the Stables.",
      "I'm nervous.",
      "I don't trust myself.",
      "I'm afraid to raise my prices.",
    ],
    status: "live",
  },
  {
    id: "apple-orchard",
    name: "Apple Orchard",
    trademark: "Apple Orchard™",
    route: null,
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.appleOrchard,
    roomType: "nature",
    purpose: "Fresh ideas and possibility — harvest thinking in an open orchard.",
    emotionalFeeling: "Possibility, freshness, gentle abundance",
    whatMembersDo: "Explore ideas, celebrate planting seeds of thought (map destination today).",
    whatShariDoes: "May say 'Let's head to the Apple Orchard' when ideation wants air and light.",
    whenToRecommend: [
      "fresh ideas",
      "want the orchard",
      "something new is growing",
    ],
    relatedRoomIds: ["gardens", "seeds-planted", "momentum-institute"],
    navigationPhrases: [
      "apple orchard",
      "the orchard",
      "take me to the apple orchard",
    ],
    estateIntelligenceExamples: ["I want to go to the Apple Orchard."],
    status: "future",
  },
  {
    id: "sunroom",
    name: "Sunroom",
    trademark: "Sunroom",
    route: "welcome-room",
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.sunroom,
    roomType: "restoration",
    purpose: "Shari's welcome — quiet hello overlooking the pond.",
    emotionalFeeling: "Warmth, belonging, unhurried welcome",
    whatMembersDo: "Meet Shari, hear why Spark exists, pause without agenda.",
    whatShariDoes: "Welcomes personally — voice and letter when ready.",
    whenToRecommend: ["meet shari", "welcome room", "sunroom"],
    relatedRoomIds: ["welcome-home"],
    navigationPhrases: [
      "sunroom",
      "the sunroom",
      "welcome room",
      "shari's sunroom",
    ],
    estateIntelligenceExamples: ["Take me to the sunroom."],
    status: "live",
  },
  {
    id: "peaceful-places",
    name: "Peaceful Places",
    trademark: "Peaceful Places™",
    route: "focus-audio",
    routes: ["breathe"],
    backgroundImage: null,
    intendedBackgroundImage: "/backgrounds/peaceful-places/woodland-pathway.png",
    estateRegistryId: "peaceful-places",
    homesteadRoomId: "peaceful-places",
    roomType: "restoration",
    purpose: "Immersive calm destinations — soundscapes, warmth, restoration without leaving Spark.",
    emotionalFeeling: "Calm, safety, restoration, breath",
    whatMembersDo: "Choose a destination, listen, breathe, restore focus or peace.",
    whatShariDoes: "Suggests a place when calm helps — always optional.",
    whenToRecommend: [
      "need calm",
      "anxious or overwhelmed",
      "want ambient sound",
      "restore focus",
    ],
    relatedRoomIds: ["music-room", "coffee-house", "clear-my-mind"],
    navigationPhrases: [
      "peaceful places",
      "peaceful place",
      "show me peaceful places",
      "I need calm",
    ],
    estateIntelligenceExamples: [
      "I need a peaceful place.",
      "Help me calm down.",
    ],
    status: NEEDS_ASSET,
  },
  {
    id: "clear-my-mind",
    name: "Clear My Mind",
    trademark: "Clear My Mind™",
    route: "brain-dump",
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.butterflyConservatory,
    estateRegistryId: "clear-my-mind",
    roomType: "reflection",
    purpose: "Continuous thought capture — empty the head without organizing pressure.",
    emotionalFeeling: "Relief, lightness, mental spaciousness",
    whatMembersDo: "Unload thoughts, brain dump, capture without finishing anything.",
    whatShariDoes: "Listens first — organizes quietly later; never forces My Thoughts.",
    whenToRecommend: [
      "clear my head",
      "too much in my mind",
      "brain dump",
      "scattered thoughts",
    ],
    relatedRoomIds: ["conservatory", "journal", "peaceful-places"],
    navigationPhrases: [
      "clear my mind",
      "clear my head",
      "brain dump",
    ],
    estateIntelligenceExamples: [
      "I need to clear my head.",
      "Everything is jumbled in my mind.",
    ],
    status: NEEDS_ASSET,
  },
  {
    id: "decision-compass",
    name: "Decision Compass",
    trademark: "Decision Compass™",
    route: "decision-compass",
    backgroundImage: null,
    estateRegistryId: "decision-compass",
    roomType: "planning",
    purpose: "Think through decisions with clarity — options, values, and next steps without pressure.",
    emotionalFeeling: "Steadiness, clarity, ownership",
    whatMembersDo: "Explore options, name tradeoffs, decide with Shari's facilitation.",
    whatShariDoes: "Illuminates choices — member owns the decision.",
    whenToRecommend: [
      "stuck between options",
      "big decision",
      "think through a decision",
      "which path should I take",
    ],
    relatedRoomIds: ["momentum-builder", "observatory", "journal"],
    navigationPhrases: [
      "decision compass",
      "open decision compass",
      "help me decide",
    ],
    estateIntelligenceExamples: [
      "I want to think through a decision.",
      "I can't choose between these options.",
    ],
    status: "live",
  },
  {
    id: "momentum-builder",
    name: "Momentum Builder",
    trademark: "Momentum Builder™",
    route: "momentum-builder",
    routes: ["grow-momentum-builders"],
    backgroundImage: null,
    intendedBackgroundImage: ESTATE_ROOM_BG.momentumBuilder,
    estateRegistryId: "momentum-builder",
    roomType: "planning",
    purpose: "Coaching conversation in a planning studio — one meaningful next step from overwhelm.",
    emotionalFeeling: "Momentum, hope, honest forward motion",
    whatMembersDo: "Name what's hard today, choose one next step, build momentum.",
    whatShariDoes: "Coaches without guilt — 'What's making today difficult?'",
    whenToRecommend: [
      "overwhelmed",
      "stuck",
      "what should I do today",
      "can't get started",
    ],
    relatedRoomIds: ["decision-compass", "creative-studio", "game-room"],
    navigationPhrases: ["momentum builder", "help me get moving"],
    estateIntelligenceExamples: [
      "I'm overwhelmed and don't know where to start.",
    ],
    status: NEEDS_ASSET,
  },
  {
    id: "journal",
    name: "Journal Gazebo",
    trademark: "Journal Gazebo™",
    route: "growth-journal",
    backgroundImage: null,
    intendedBackgroundImage: "/backgrounds/gazebo-journal-background.png",
    estateRegistryId: "growth-journal",
    menuActionId: "journal",
    roomType: "reflection",
    purpose: "Private reflection — insights, wins, and lessons without performance.",
    emotionalFeeling: "Privacy, honesty, gentle self-awareness",
    whatMembersDo: "Write reflections, capture growth moments, process the week.",
    whatShariDoes: "Honors privacy — may invite journaling, never surveils.",
    whenToRecommend: [
      "want to journal",
      "need to reflect",
      "process what happened",
    ],
    relatedRoomIds: ["evidence-vault", "growth-profile", "coffee-house"],
    navigationPhrases: ["journal", "my journal", "open journal", "want to journal"],
    estateIntelligenceExamples: ["I want to journal.", "Help me reflect on this week."],
    status: NEEDS_ASSET,
  },
  {
    id: "my-estate",
    name: "My Estate",
    trademark: "My Estate™",
    route: null,
    menuActionId: "estate-profile",
    overlayId: "profile",
    backgroundImage: ESTATE_ROOM_BG.sparkEstatePhoto,
    intendedBackgroundImage: ESTATE_ROOM_BG.sparkEstatePhoto,
    roomType: "profile",
    purpose: "Personal growth record across the Estate — profile, preferences, and your places.",
    emotionalFeeling: "Ownership, continuity, belonging",
    whatMembersDo: "Review profile, preferences, and personal estate destinations via the global menu.",
    whatShariDoes: "Remembers who you are — never reduces you to settings screens.",
    whenToRecommend: ["update my profile", "my estate", "personal settings"],
    relatedRoomIds: [
      "growth-profile",
      "institute-cabinet",
      "evidence-vault",
      "portfolio",
      "journal",
    ],
    navigationPhrases: ["my estate", "estate profile", "your estate"],
    estateIntelligenceExamples: ["Show me My Estate."],
    status: "live",
  },
  {
    id: "institute-cabinet",
    name: "My Institute Cabinet",
    trademark: "My Institute Cabinet™",
    route: null,
    menuActionId: "institute-cabinet",
    overlayId: "institute-cabinet",
    backgroundImage: null,
    roomType: "archive",
    purpose: "Saved Knowledge Cards™ and Institute references — filed for easy return.",
    emotionalFeeling: "Trust, organization without folders",
    whatMembersDo: "Save cards from the Institute, revisit filed lessons.",
    whatShariDoes:
      "Asks 'Would you like me to file this in your My Institute Cabinet™?' — permission first.",
    whenToRecommend: ["save this lesson", "find what I saved", "institute cabinet"],
    relatedRoomIds: ["momentum-institute", "growth-profile"],
    navigationPhrases: ["institute cabinet", "my institute cabinet", "open my cabinet"],
    estateIntelligenceExamples: ["Show my Institute Cabinet."],
    status: "live",
  },
  {
    id: "evidence-vault",
    name: "Evidence Vault",
    trademark: "Evidence Vault™",
    route: "evidence-bank",
    menuActionId: "evidence-vault",
    backgroundImage: null,
    intendedBackgroundImage: "/backgrounds/evidence-vault-background.png",
    estateRegistryId: "evidence-bank",
    roomType: "archive",
    purpose: "Proof of growth for harder days — wins and evidence preserved with dignity.",
    emotionalFeeling: "Confidence, proof, self-trust",
    whatMembersDo: "Collect wins, review evidence, remember progress.",
    whatShariDoes: "Surfaces evidence when confidence wavers — never as a scorecard.",
    whenToRecommend: [
      "imposter syndrome",
      "forgot how far I've come",
      "collect wins",
    ],
    relatedRoomIds: ["journal", "growth-profile", "portfolio"],
    navigationPhrases: ["evidence vault", "my wins", "proof of growth"],
    estateIntelligenceExamples: ["I need to remember what I've accomplished."],
    status: NEEDS_ASSET,
  },
  {
    id: "portfolio",
    name: "Achievement Library",
    trademark: "Achievement Library™",
    route: "growth-portfolio",
    menuActionId: "portfolio",
    backgroundImage: ESTATE_ROOM_BG.portfolio,
    intendedBackgroundImage: ESTATE_ROOM_BG.portfolio,
    roomType: "archive",
    purpose: "Creative work and projects — what you've built, in one thoughtful place.",
    emotionalFeeling: "Pride, craft, continuity",
    whatMembersDo: "Review creative work, projects, and growth artifacts.",
    whatShariDoes: "Connects work to story — never reduces portfolio to a file list.",
    whenToRecommend: ["show my work", "what have I built", "my portfolio"],
    relatedRoomIds: ["creative-studio", "goals-projects", "evidence-vault"],
    navigationPhrases: ["portfolio", "my portfolio", "open portfolio"],
    estateIntelligenceExamples: ["Show my Portfolio."],
    status: NEEDS_ASSET,
  },
  {
    id: "seeds-planted",
    name: "Seeds Planted",
    trademark: "Seeds Planted™",
    route: "grow-spark-cards",
    menuActionId: "seeds-planted",
    backgroundImage: null,
    estateRegistryId: "knowledge-cards",
    roomType: "archive",
    purpose: "Spark Cards™ and ideas taking root — wisdom captured before it becomes a project.",
    emotionalFeeling: "Hope, emergence, gentle growth",
    whatMembersDo: "Browse Spark Cards, ideas planted, early insights.",
    whatShariDoes: "Notices seeds that may be ready to nurture — never rushes harvest.",
    whenToRecommend: ["spark cards", "ideas I saved", "seeds I planted"],
    relatedRoomIds: ["momentum-institute", "apple-orchard", "goals-projects"],
    navigationPhrases: ["seeds planted", "my spark cards", "planted seeds"],
    estateIntelligenceExamples: ["Show my Seeds Planted."],
    status: "planned",
  },
  {
    id: "goals-projects",
    name: "Goals & Projects",
    trademark: "Goals & Projects™",
    route: "projects",
    menuActionId: "goals-projects",
    backgroundImage: null,
    roomType: "planning",
    purpose: "What you are building toward — projects and goals without surveillance.",
    emotionalFeeling: "Direction, ownership, honest ambition",
    whatMembersDo: "Review and shape projects, connect work to goals.",
    whatShariDoes: "Helps clarify direction — never guilt-trips about unfinished lists.",
    whenToRecommend: ["my projects", "goals", "what am I building"],
    relatedRoomIds: ["momentum-builder", "portfolio", "decision-compass"],
    navigationPhrases: ["goals and projects", "my projects", "goals & projects"],
    estateIntelligenceExamples: ["Show my Goals and Projects."],
    status: "live",
  },
  {
    id: "growth-profile",
    name: "Growth Profile",
    trademark: "Growth Profile™",
    route: null,
    menuActionId: "growth-profile",
    overlayId: "growth-profile",
    backgroundImage: ESTATE_ROOM_BG.greenhouse,
    intendedBackgroundImage: ESTATE_ROOM_BG.greenhouse,
    roomType: "profile",
    purpose:
      "Capabilities earned through learning, reflection, application, and return — not consumption alone.",
    emotionalFeeling: "Quiet pride, earned capability, trajectory",
    whatMembersDo: "See competency growth, timeline, and Institute progress.",
    whatShariDoes: "Updates quietly — growth is earned through use, not badges.",
    whenToRecommend: [
      "how am I growing",
      "my capabilities",
      "growth profile",
    ],
    relatedRoomIds: ["momentum-institute", "evidence-vault", "journal"],
    navigationPhrases: ["growth profile", "my growth profile", "show my growth"],
    estateIntelligenceExamples: ["How am I growing as an entrepreneur?"],
    status: "live",
  },
] as const;

const BY_ID = new Map(ESTATE_ROOM_REGISTRY.map((room) => [room.id, room]));

const BY_REGISTRY_ID = new Map(
  ESTATE_ROOM_REGISTRY.filter((room) => room.estateRegistryId).map((room) => [
    room.estateRegistryId!,
    room,
  ]),
);

export function getEstateRoomById(id: string): EstateRoomDefinition | null {
  return BY_ID.get(id) ?? BY_REGISTRY_ID.get(id) ?? null;
}

export function listEstateRooms(): readonly EstateRoomDefinition[] {
  return ESTATE_ROOM_REGISTRY;
}

export function listEstateRoomsByStatus(
  status: EstateRoomDefinition["status"],
): readonly EstateRoomDefinition[] {
  return ESTATE_ROOM_REGISTRY.filter((room) => room.status === status);
}

const ROUTE_STATUS_PRIORITY: Record<
  EstateRoomDefinition["status"],
  number
> = {
  live: 5,
  partial: 4,
  "image-ready-needs-asset": 3,
  planned: 2,
  future: 1,
};

export function getEstateRoomForRoute(
  section: string,
): EstateRoomDefinition | null {
  const matches = ESTATE_ROOM_REGISTRY.filter(
    (room) =>
      room.route === section ||
      room.routes?.includes(section as EstateRoomDefinition["route"] & string),
  );
  if (matches.length === 0) return null;
  if (matches.length === 1) return matches[0] ?? null;

  return (
    [...matches].sort(
      (a, b) =>
        ROUTE_STATUS_PRIORITY[b.status] - ROUTE_STATUS_PRIORITY[a.status],
    )[0] ?? null
  );
}
