import { BUSINESS_BOOKS, CREATIVE_BOOKS, FRIDAY_BOOKS, RECOVERY_BOOKS } from "./bookSets";
import type { HospitalityScenePreset } from "./types";
import { COMPANION_PRESENCE_WELCOME_IMAGE_ID } from "@/lib/companionPresenceLibrary";

export const HOSPITALITY_SCENE_PRESETS: HospitalityScenePreset[] = [
  {
    id: "iowa-spring-morning",
    label: "Iowa Spring Morning",
    description: "Fresh green, tulips, birds, soft curtains",
    season: "spring",
    weather: "clear",
    lighting: "morning",
    timeOfDay: "morning",
    atmosphere: "Fresh Iowa morning — window open, world waking",
    greeting: "Good morning, Shari.",
    invite: "I'm here for you. What's on your mind today?",
    companionImageId: COMPANION_PRESENCE_WELCOME_IMAGE_ID,
    hospitality: ["coffee", "tulips"],
    motion: [
      "sunlight",
      "foliage",
      "curtains",
    ],
    books: CREATIVE_BOOKS.slice(0, 3),
    audio: ["birds", "wind-chimes"],
    warmth: 42,
  },
  {
    id: "cozy-rainy-tuesday",
    label: "Cozy Rainy Tuesday",
    description: "Rain on glass, tea, lamp, fireplace, soft thunder",
    season: "autumn",
    weather: "rain",
    lighting: "afternoon",
    timeOfDay: "afternoon",
    atmosphere: "Rainy Tuesday — lamp on, kettle warm",
    greeting: "We'll take today one step at a time.",
    invite: "Stay as long as you need.",
    companionImageId: COMPANION_PRESENCE_WELCOME_IMAGE_ID,
    hospitality: ["tea-set", "journal"],
    motion: ["rain", "lamplight", "curtains", "thunder"],
    books: RECOVERY_BOOKS.slice(0, 4),
    audio: ["rain", "fireplace", "thunder"],
    warmth: 58,
  },
  {
    id: "iowa-autumn-afternoon",
    label: "Iowa Autumn Afternoon",
    description: "Golden leaves, cider, blanket, warm sun",
    season: "autumn",
    weather: "clear",
    lighting: "golden-hour",
    timeOfDay: "afternoon",
    atmosphere: "Golden Iowa afternoon — leaves drifting outside",
    greeting: "It's always good to see you.",
    invite: "What feels possible this afternoon?",
    companionImageId: COMPANION_PRESENCE_WELCOME_IMAGE_ID,
    hospitality: ["cider", "blanket", "cookies"],
    motion: ["sunlight", "leaves", "foliage", "curtains"],
    books: BUSINESS_BOOKS.slice(0, 3),
    audio: ["wind"],
    warmth: 62,
  },
  {
    id: "winter-snow",
    label: "Winter Snow",
    description: "Snow falling, cardinal, steam, fireplace",
    season: "winter",
    weather: "snow",
    lighting: "evening",
    timeOfDay: "evening",
    atmosphere: "Iowa winter — come in from the cold",
    greeting: "Come in from the cold.",
    invite: "The room is warm. Take your time.",
    companionImageId: "shari-evening-winddown",
    hospitality: ["coffee", "blanket"],
    motion: ["snow", "lamplight", "curtains"],
    books: RECOVERY_BOOKS.slice(0, 3),
    audio: ["fireplace", "wind"],
    warmth: 72,
  },
  {
    id: "birthday",
    label: "Birthday",
    description: "Flowers, cake, handwritten card, single candle",
    season: "spring",
    weather: "clear",
    lighting: "golden-hour",
    timeOfDay: "afternoon",
    atmosphere: "Celebration — quietly prepared",
    greeting: "Happy Birthday.",
    invite: "I'm really glad we get to celebrate today.",
    companionImageId: COMPANION_PRESENCE_WELCOME_IMAGE_ID,
    hospitality: ["flowers", "cake", "birthday-card"],
    motion: ["sunlight"],
    books: ["Today Counts Too", "Finished Is Beautiful", "Tiny Wins"],
    audio: ["wind-chimes"],
    warmth: 55,
  },
  {
    id: "vacation-countdown",
    label: "Vacation Countdown",
    description: "Travel guide, suitcase, sunny morning coffee",
    season: "summer",
    weather: "clear",
    lighting: "morning",
    timeOfDay: "morning",
    atmosphere: "Adventure approaching — three mornings away",
    greeting: "Only three mornings until your adventure.",
    invite: "What are you most looking forward to?",
    companionImageId: "shari-coffee-cup",
    hospitality: ["travel-guide", "suitcase", "coffee"],
    motion: ["sunlight", "clouds"],
    books: ["Ideas Worth Keeping", "Permission to Begin"],
    audio: ["birds", "clock"],
    warmth: 48,
  },
  {
    id: "recovery-day",
    label: "Recovery Day",
    description: "Quiet room, tea, rain, softer light, minimal motion",
    season: "spring",
    weather: "rain",
    lighting: "afternoon",
    timeOfDay: "afternoon",
    atmosphere: "Gentle recovery — no rush",
    greeting: "We'll keep today gentle.",
    invite: "There's no hurry here.",
    companionImageId: "shari-evening-winddown",
    hospitality: ["tea-set"],
    motion: ["rain", "lamplight", "curtains"],
    books: RECOVERY_BOOKS,
    audio: ["rain"],
    warmth: 52,
  },
  {
    id: "friday-celebration",
    label: "Friday Celebration",
    description: "Fresh flowers, journal, bright sunshine",
    season: "summer",
    weather: "clear",
    lighting: "golden-hour",
    timeOfDay: "afternoon",
    atmosphere: "Friday light — you made it through the week",
    greeting: "You made it through the week.",
    invite: "What deserves a quiet moment of recognition?",
    companionImageId: COMPANION_PRESENCE_WELCOME_IMAGE_ID,
    hospitality: ["flowers", "journal", "cookies"],
    motion: ["sunlight", "butterflies", "foliage"],
    books: FRIDAY_BOOKS,
    audio: ["birds", "wind-chimes"],
    warmth: 60,
  },
];

export function presetById(id: string): HospitalityScenePreset | undefined {
  return HOSPITALITY_SCENE_PRESETS.find((scene) => scene.id === id);
}
