/**
 * Estate Capability Registry — every capability Spark can fulfill.
 * Single source of truth for routing, menus, and conversation hints.
 */

import type { EstateCapability, EstateCapabilityCategory } from "./intelligenceTypes";

function cap(
  partial: EstateCapability & { category: EstateCapabilityCategory },
): EstateCapability {
  return {
    immediateNavigate: true,
    ...partial,
  };
}

const RESEARCH: EstateCapability[] = [
  cap({
    id: "research.known",
    name: "Quick answers",
    category: "research",
    triggers: [
      "explain",
      "what is",
      "what are",
      "teach me about",
      "define",
      "how does",
      "swot",
      "adhd",
      "branding",
    ],
    experienceId: "think",
    spaceId: "study-hall",
    toolId: "momentum-institute",
    expertIds: ["research-analyst", "executive-coach"],
    researchLevel: 1,
    immediateNavigate: false,
  }),
  cap({
    id: "research.current",
    name: "Current research",
    category: "research",
    triggers: [
      "research",
      "look up",
      "find out",
      "latest",
      "newest",
      "recent",
      "current",
      "trending",
      "ai tools",
      "regulations",
      "this year",
    ],
    experienceId: "think",
    spaceId: "study-hall",
    toolId: "momentum-institute",
    expertIds: ["research-analyst", "technology-expert"],
    researchLevel: 2,
  }),
  cap({
    id: "research.deep",
    name: "Deep research",
    category: "research",
    triggers: [
      "compare",
      "versus",
      " vs ",
      "market report",
      "comprehensive",
      "in-depth",
      "multiple sources",
      "summarize",
      "analysis of",
      "evaluate options",
    ],
    experienceId: "think",
    spaceId: "study-hall",
    toolId: "momentum-institute",
    expertIds: ["research-analyst", "business-strategist"],
    researchLevel: 3,
  }),
  cap({
    id: "research.monitor",
    name: "Ongoing monitoring",
    category: "research",
    triggers: [
      "watch",
      "monitor",
      "notify me",
      "keep me posted",
      "track updates",
      "alert me",
    ],
    experienceId: "think",
    spaceId: "study-hall",
    toolId: "momentum-institute",
    expertIds: ["research-analyst", "technology-expert"],
    researchLevel: 4,
    immediateNavigate: false,
  }),
];

const CREATE: EstateCapability[] = [
  cap({
    id: "create.email",
    name: "Email",
    category: "create",
    triggers: ["email", "e-mail", "write an email", "draft email"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["copywriter"],
  }),
  cap({
    id: "create.newsletter",
    name: "Newsletter",
    category: "create",
    triggers: ["newsletter"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["copywriter", "marketing-expert"],
  }),
  cap({
    id: "create.sop",
    name: "SOP",
    category: "create",
    triggers: ["sop", "standard operating", "procedure"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["instructional-designer"],
  }),
  cap({
    id: "create.proposal",
    name: "Proposal",
    category: "create",
    triggers: ["proposal"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["copywriter", "sales-expert"],
  }),
  cap({
    id: "create.blog",
    name: "Blog",
    category: "create",
    triggers: ["blog", "blog post", "article"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["copywriter"],
  }),
  cap({
    id: "create.social",
    name: "Social Posts",
    category: "create",
    triggers: ["social post", "social media", "instagram", "linkedin post"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["copywriter", "marketing-expert"],
  }),
  cap({
    id: "create.presentation",
    name: "Presentation",
    category: "create",
    triggers: ["presentation", "slides", "deck"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["writing-coach"],
  }),
  cap({
    id: "create.image",
    name: "AI Images",
    category: "create",
    triggers: ["ai image", "generate image", "create image", "picture"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["graphic-design-advisor"],
  }),
  cap({
    id: "create.mindmap",
    name: "Mind Map",
    category: "create",
    triggers: [
      "mind map",
      "mindmap",
      "too many ideas",
      "all over the place",
      "scattered ideas",
      "organize my thoughts",
    ],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "visual-focus",
    expertIds: ["writing-coach", "adhd-coach"],
  }),
  cap({
    id: "create.whiteboard",
    name: "Whiteboards",
    category: "create",
    triggers: ["whiteboard", "brainstorm"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["writing-coach", "business-strategist"],
  }),
  cap({
    id: "create.template",
    name: "Templates",
    category: "create",
    triggers: ["template"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["instructional-designer"],
  }),
  cap({
    id: "create.longform",
    name: "Long-form Writing",
    category: "create",
    triggers: [
      "book",
      "chapter",
      "long form",
      "script",
      "develop ideas first",
      "writing room",
    ],
    experienceId: "create",
    spaceId: "decision-compass",
    toolId: "content-generator",
    expertIds: ["writing-coach"],
  }),
  cap({
    id: "create.general",
    name: "Create",
    category: "create",
    triggers: ["write", "draft", "create", "build", "make", "design"],
    experienceId: "create",
    spaceId: "creative-studio",
    toolId: "content-generator",
    expertIds: ["copywriter", "writing-coach"],
  }),
];

const MOMENTUM: EstateCapability[] = [
  cap({
    id: "momentum.projects",
    name: "Projects",
    category: "momentum",
    triggers: ["active project", "my projects", "project status"],
    experienceId: "momentum",
    spaceId: "goals-projects",
    toolId: "projects",
    expertIds: ["project-manager"],
  }),
  cap({
    id: "momentum.marketing",
    name: "Marketing Plan",
    category: "momentum",
    triggers: ["marketing plan", "marketing strategy"],
    experienceId: "momentum",
    spaceId: "goals-projects",
    toolId: "projects",
    expertIds: ["marketing-expert", "business-strategist"],
  }),
  cap({
    id: "momentum.weekly",
    name: "Weekly Planning",
    category: "momentum",
    triggers: ["weekly plan", "plan my week", "this week"],
    experienceId: "momentum",
    spaceId: "goals-projects",
    toolId: "plan-my-day",
    expertIds: ["productivity-specialist", "project-manager"],
  }),
  cap({
    id: "momentum.goals",
    name: "Goals",
    category: "momentum",
    triggers: ["goal", "goals", "quarterly"],
    experienceId: "momentum",
    spaceId: "goals-projects",
    toolId: "projects",
    expertIds: ["executive-coach", "project-manager"],
  }),
  cap({
    id: "momentum.roadmap",
    name: "Roadmap",
    category: "momentum",
    triggers: ["roadmap", "milestone", "action plan"],
    experienceId: "momentum",
    spaceId: "goals-projects",
    toolId: "projects",
    expertIds: ["project-manager", "business-strategist"],
  }),
  cap({
    id: "momentum.general",
    name: "Momentum",
    category: "momentum",
    triggers: ["move forward", "get it done", "launch plan", "business plan"],
    experienceId: "momentum",
    spaceId: "goals-projects",
    toolId: "projects",
    expertIds: ["business-strategist", "marketing-expert", "project-manager"],
  }),
];

const FOCUS: EstateCapability[] = [
  cap({
    id: "focus.session",
    name: "Focus Session",
    category: "focus",
    triggers: ["need to focus", "help me focus", "focus session", "concentrate"],
    experienceId: "focus",
    spaceId: "focus-studio",
    toolId: "focus",
    expertIds: ["adhd-coach", "productivity-specialist"],
  }),
  cap({
    id: "focus.pomodoro",
    name: "Pomodoro",
    category: "focus",
    triggers: ["pomodoro", "25 minute", "timer"],
    experienceId: "focus",
    spaceId: "focus-studio",
    toolId: "focus-timer",
    expertIds: ["productivity-specialist"],
  }),
  cap({
    id: "focus.deepwork",
    name: "Deep Work",
    category: "focus",
    triggers: ["deep work"],
    experienceId: "focus",
    spaceId: "focus-studio",
    toolId: "focus",
    expertIds: ["adhd-coach", "productivity-specialist"],
  }),
];

const RESTORE: EstateCapability[] = [
  cap({
    id: "restore.calm",
    name: "Calm & Breathe",
    category: "restore",
    triggers: [
      "breathe",
      "meditat",
      "calm down",
      "need to calm",
      "anxious",
      "overwhelm",
      "relax",
      "reset",
    ],
    experienceId: "restore",
    spaceId: "sunroom",
    toolId: "focus-audio",
    expertIds: ["adhd-coach"],
  }),
  cap({
    id: "restore.music",
    name: "Relaxation Music",
    category: "restore",
    triggers: ["music", "soundscape", "listen", "ambient"],
    experienceId: "restore",
    spaceId: "music-room",
    toolId: "focus-audio",
    expertIds: ["adhd-coach"],
  }),
  cap({
    id: "restore.clearmind",
    name: "Clear My Mind",
    category: "restore",
    triggers: ["clear my mind", "brain dump", "scattered thoughts"],
    experienceId: "restore",
    spaceId: "clear-my-mind",
    toolId: "brain-dump",
    expertIds: ["adhd-coach"],
  }),
];

const JOURNAL: EstateCapability[] = [
  cap({
    id: "journal.reflect",
    name: "Reflection",
    category: "journal",
    triggers: ["journal", "reflect", "gratitude", "pray", "prayer"],
    experienceId: "journal",
    spaceId: "journal",
    toolId: "growth-journal",
    expertIds: ["writing-coach", "career-advisor"],
    immediateNavigate: false,
  }),
];

const BUSINESS: EstateCapability[] = [
  cap({
    id: "business.strategy",
    name: "Business Strategy",
    category: "business",
    triggers: [
      "build my business",
      "my business",
      "business strategy",
      "client avatar",
      "ideal client",
    ],
    experienceId: "business",
    spaceId: "round-table",
    toolId: "client-avatars",
    expertIds: ["business-strategist", "marketing-expert", "sales-expert"],
  }),
  cap({
    id: "business.funnel",
    name: "Funnels",
    category: "business",
    triggers: ["funnel", "crm", "sales pipeline", "pricing", "offer"],
    experienceId: "business",
    spaceId: "round-table",
    toolId: "playbook",
    expertIds: ["sales-expert", "marketing-expert"],
  }),
];

const LEARN: EstateCapability[] = [
  cap({
    id: "learn.thinkers",
    name: "Great Thinkers",
    category: "learn",
    triggers: ["great thinkers", "study hall", "course"],
    experienceId: "think",
    spaceId: "study-hall",
    toolId: "momentum-institute",
    expertIds: ["research-analyst", "executive-coach"],
  }),
];

export const ESTATE_CAPABILITIES: readonly EstateCapability[] = [
  ...RESEARCH,
  ...CREATE,
  ...MOMENTUM,
  ...FOCUS,
  ...RESTORE,
  ...JOURNAL,
  ...BUSINESS,
  ...LEARN,
];

const BY_ID = new Map<string, EstateCapability>(
  ESTATE_CAPABILITIES.map((c) => [c.id, c]),
);

export function estateCapabilityById(id: string): EstateCapability | undefined {
  return BY_ID.get(id);
}

export function estateCapabilitiesByCategory(
  category: EstateCapabilityCategory,
): EstateCapability[] {
  return ESTATE_CAPABILITIES.filter((c) => c.category === category);
}
