/**
 * Estate Brain™ — authoritative knowledge registry (internal, not member UI).
 *
 * Every experience and navigable space appears exactly once.
 * @see docs/estate/ESTATE_REGISTRY.md
 */

import type { EstateKnowledgeEntry } from "./types";

const CREATE: EstateKnowledgeEntry = {
  id: "create",
  kind: "experience",
  name: "Create",
  purpose: "Bring ideas to life.",
  description:
    "Making and drafting — emails, documents, visuals, templates, and new project shells.",
  experienceId: "create",
  spaceId: "creative-studio",
  primarySection: "content-generator",
  capabilities: [
    "Email",
    "Newsletter",
    "SOP",
    "Proposal",
    "Social Posts",
    "Blog",
    "Images",
    "Mind Maps",
    "Whiteboards",
    "Presentations",
    "Templates",
    "Vision Boards",
    "Brainstorm",
    "New Project",
  ],
  suggestedActivities: [
    "Write an email",
    "Draft a newsletter",
    "Build an SOP",
    "Design a presentation",
    "Brainstorm ideas",
  ],
  tools: [
    "Email",
    "Newsletter",
    "SOP",
    "Proposal",
    "Social Post",
    "Blog Article",
    "Presentation",
    "Template",
    "Mind Map",
    "Whiteboard",
    "AI Image",
    "Vision Board",
    "Brainstorm",
    "New Project",
  ],
  relatedSpaceIds: [
    "goals-projects",
    "art-studio",
    "round-table",
    "momentum-builder",
  ],
  triggers: [
    "email",
    "write",
    "create",
    "draft",
    "design",
    "newsletter",
    "proposal",
    "sop",
    "brainstorm",
    "blog",
    "social post",
    "mind map",
    "whiteboard",
    "presentation",
    "template",
    "bring to life",
    "make something",
  ],
  aliases: ["create studio", "creative studio", "documents"],
  defaultGreeting: "What would you like to bring to life today?",
  nextSuggestions: ["Momentum", "Boardroom", "Art Studio"],
  userNeeds: ["creative", "business"],
};

const MOMENTUM: EstateKnowledgeEntry = {
  id: "momentum",
  kind: "experience",
  name: "Momentum",
  purpose: "Move work forward.",
  description:
    "Execution — active projects, planning, goals, roadmaps, and business growth momentum.",
  experienceId: "momentum",
  spaceId: "goals-projects",
  primarySection: "projects",
  capabilities: [
    "Projects",
    "Marketing",
    "Goals",
    "Planning",
    "Roadmaps",
    "Weekly Planning",
    "Quarterly Planning",
    "Business Growth",
    "Milestones",
    "Next Actions",
  ],
  suggestedActivities: [
    "Review active projects",
    "Plan the week",
    "Set quarterly goals",
    "Map a launch",
  ],
  tools: [
    "Active Projects",
    "Marketing Plan",
    "Weekly Planning",
    "Quarterly Planning",
    "Goals",
    "Roadmap",
    "Milestones",
    "Next Actions",
    "Business Building",
  ],
  relatedSpaceIds: [
    "creative-studio",
    "round-table",
    "study-hall",
    "momentum-builder",
  ],
  triggers: [
    "project",
    "launch",
    "goal",
    "plan",
    "marketing",
    "strategy",
    "roadmap",
    "milestone",
    "move forward",
    "weekly plan",
    "quarterly",
    "action plan",
    "get it done",
    "active project",
  ],
  aliases: ["momentum room", "momentum builder", "goals and projects"],
  defaultGreeting: "What are we moving forward today?",
  nextSuggestions: ["Create", "Boardroom", "Study Hall"],
  userNeeds: ["business", "overwhelmed"],
};

const FOCUS: EstateKnowledgeEntry = {
  id: "focus",
  kind: "experience",
  name: "Focus",
  purpose: "Get into a productive state.",
  description: "Concentration — timers, deep work, body doubling, and focus music.",
  experienceId: "focus",
  spaceId: "focus-studio",
  primarySection: "focus",
  capabilities: [
    "Pomodoro",
    "Deep Work",
    "Body Doubling",
    "Focus Music",
    "Focus Timer",
    "Resume Last Task",
  ],
  suggestedActivities: [
    "25-minute focus session",
    "Body double together",
    "Play focus music",
  ],
  tools: [
    "Focus Session",
    "Pomodoro",
    "Deep Work",
    "Body Doubling",
    "Focus Music",
    "Focus Timer",
  ],
  relatedSpaceIds: ["peaceful-places", "coffee-house", "music-room"],
  triggers: [
    "focus",
    "concentrate",
    "pomodoro",
    "deep work",
    "body double",
    "distraction",
    "focus music",
    "focus timer",
    "can't concentrate",
  ],
  aliases: ["focus room", "focus studio"],
  defaultGreeting: "What would help you concentrate?",
  nextSuggestions: ["Momentum", "Restore"],
  userNeeds: ["focus"],
};

const RESTORE: EstateKnowledgeEntry = {
  id: "restore",
  kind: "experience",
  name: "Restore",
  purpose: "Calm the nervous system.",
  description:
    "Restoration — breathing, meditation, soundscapes, and peaceful places.",
  experienceId: "restore",
  spaceId: "peaceful-places",
  primarySection: "focus-audio",
  capabilities: [
    "Breathing",
    "Meditation",
    "Grounding",
    "Soundscapes",
    "Nature Walk",
    "Relaxation",
    "Mindfulness",
  ],
  suggestedActivities: [
    "Take a breath",
    "Listen to soundscapes",
    "Ground for a minute",
  ],
  tools: ["Breathing", "Meditation", "Grounding", "Soundscapes", "Mindfulness"],
  relatedSpaceIds: [
    "clear-my-mind",
    "coffee-house",
    "lakeside-hammock",
    "sunroom",
    "journal",
  ],
  triggers: [
    "breathe",
    "breathing",
    "meditat",
    "calm",
    "anxious",
    "overwhelm",
    "relax",
    "soundscape",
    "grounding",
    "mindful",
    "peaceful",
    "rest",
  ],
  aliases: ["restore", "calm", "peaceful places"],
  defaultGreeting: "What kind of calm would help most?",
  nextSuggestions: ["Journal", "Momentum", "Focus"],
  userNeeds: ["overwhelmed", "anxious", "stressed", "calm", "rest"],
};

const THINK: EstateKnowledgeEntry = {
  id: "think",
  kind: "experience",
  name: "Think",
  purpose: "Work through ideas.",
  description: "Decisions, research, learning, and study with Great Thinkers.",
  experienceId: "think",
  spaceId: "decision-compass",
  primarySection: "decision-compass",
  capabilities: [
    "Decision Compass",
    "Pros and Cons",
    "SWOT",
    "Research",
    "Great Thinkers",
    "Courses",
    "Notes",
  ],
  suggestedActivities: [
    "Work through a decision",
    "Research a topic",
    "Study with Great Thinkers",
  ],
  tools: [
    "Decision Compass",
    "Pros & Cons",
    "SWOT",
    "Research",
    "Great Thinkers",
    "Study",
    "Learning",
  ],
  relatedSpaceIds: ["study-hall", "library", "observatory", "round-table"],
  triggers: [
    "decide",
    "decision",
    "help me decide",
    "pros and cons",
    "swot",
    "research",
    "learn",
    "study",
    "thinkers",
    "stuck between",
    "can't decide",
  ],
  aliases: ["learn", "study hall", "decision compass"],
  defaultGreeting: "What are we working through?",
  nextSuggestions: ["Momentum", "Create", "Boardroom"],
  userNeeds: ["decide", "learn"],
};

const JOURNAL: EstateKnowledgeEntry = {
  id: "journal",
  kind: "experience",
  name: "Journal",
  purpose: "Capture life.",
  description: "Reflection, gratitude, prayer, accomplishments, and memories.",
  experienceId: "journal",
  spaceId: "journal",
  primarySection: "growth-journal",
  capabilities: [
    "Journals",
    "Reflection",
    "Prayer",
    "Gratitude",
    "Accomplishments",
    "Memories",
  ],
  suggestedActivities: [
    "Reflect on today",
    "Write gratitude",
    "Capture an accomplishment",
    "Prayer journal",
  ],
  tools: [
    "Personal Journal",
    "Gratitude",
    "Prayer",
    "Accomplishments",
    "Reflection",
    "Memories",
  ],
  relatedSpaceIds: ["library", "reading-nook", "gardens", "evidence-vault"],
  triggers: [
    "journal",
    "gratitude",
    "pray",
    "prayer",
    "reflect",
    "capture",
    "memories",
    "write in my journal",
    "accomplishment",
  ],
  aliases: ["journal gazebo", "growth journal"],
  defaultGreeting: "What would you like to capture today?",
  nextSuggestions: ["Library", "Garden", "Grow"],
  userNeeds: ["reflective"],
};

const GROW: EstateKnowledgeEntry = {
  id: "grow",
  kind: "experience",
  name: "Grow",
  purpose: "Notice personal development.",
  description:
    "Evidence, accomplishments, growth profile, and timeline — quiet celebration.",
  experienceId: "grow",
  spaceId: "evidence-vault",
  primarySection: "evidence-bank",
  capabilities: [
    "Evidence Vault",
    "Hall of Accomplishments",
    "Growth Profile",
    "Timeline",
    "Seeds Planted",
  ],
  suggestedActivities: [
    "Review evidence",
    "Record an accomplishment",
    "See your growth timeline",
  ],
  tools: [
    "Evidence Vault",
    "Hall of Accomplishments",
    "Growth Profile",
    "Institute Cabinet",
    "Seeds Planted",
    "Timeline",
  ],
  relatedSpaceIds: ["celebration-room", "greenhouse", "portfolio", "journal"],
  triggers: [
    "accomplishment",
    "evidence",
    "growth profile",
    "timeline",
    "celebrate",
    "finished a project",
    "hall of accomplishments",
  ],
  aliases: ["evidence vault", "celebrate growth"],
  defaultGreeting: "What growth feels worth noticing?",
  nextSuggestions: ["Journal", "Celebrate", "Momentum"],
  userNeeds: ["celebrate", "reflective"],
};

const PLAY: EstateKnowledgeEntry = {
  id: "play",
  kind: "experience",
  name: "Play",
  purpose: "Recharge creativity.",
  description: "Games, music, art, and conservatory — light and restorative fun.",
  experienceId: "play",
  spaceId: "game-room",
  primarySection: "games",
  capabilities: ["Games", "Music Room", "Art Studio", "Ocean Conservatory"],
  suggestedActivities: ["Play a game", "Visit the ocean conservatory", "Make art"],
  tools: ["Games", "Art Studio", "Music Room", "Ocean Conservatory"],
  relatedSpaceIds: ["art-studio", "conservatory", "music-room", "celebration-room"],
  triggers: [
    "play",
    "game",
    "fun",
    "music room",
    "art studio",
    "conservatory",
    "recharge",
  ],
  aliases: ["game room", "play room"],
  defaultGreeting: "What sounds fun right now?",
  nextSuggestions: ["Create", "Restore"],
  userNeeds: ["play", "rest"],
};

const BUSINESS: EstateKnowledgeEntry = {
  id: "business",
  kind: "experience",
  name: "Business",
  purpose: "Run and grow the business.",
  description:
    "Boardroom — strategy, avatars, offers, funnels, CRM, and operations.",
  experienceId: "business",
  spaceId: "round-table",
  primarySection: "client-avatars",
  capabilities: [
    "Client Avatars",
    "Products",
    "Services",
    "Offers",
    "Pricing",
    "Funnels",
    "CRM",
    "Marketing Calendar",
    "Sales",
    "Launches",
    "Analytics",
    "Content Library",
    "SOP Library",
  ],
  suggestedActivities: [
    "Define ideal client",
    "Shape an offer",
    "Map a funnel",
    "Review marketing calendar",
  ],
  tools: [
    "Client Avatar",
    "Products",
    "Offers",
    "Pricing",
    "Funnels",
    "CRM",
    "Marketing Calendar",
    "Sales",
    "Launches",
    "Analytics",
  ],
  relatedSpaceIds: [
    "creative-studio",
    "goals-projects",
    "study-hall",
    "momentum-builder",
  ],
  triggers: [
    "business",
    "client avatar",
    "ideal client",
    "crm",
    "funnel",
    "pricing",
    "offer",
    "marketing calendar",
    "sales",
    "launch plan",
    "build my business",
    "boardroom",
    "round table",
  ],
  aliases: ["boardroom", "business center", "round table"],
  defaultGreeting: "What part of the business needs you?",
  nextSuggestions: ["Momentum", "Create", "Study Hall"],
  userNeeds: ["business"],
};

const EXPLORE: EstateKnowledgeEntry = {
  id: "explore",
  kind: "experience",
  name: "Explore",
  purpose: "Wander the Estate.",
  description: "Map, guidebook, seasonal discovery, and visit another room.",
  experienceId: "explore",
  spaceId: "welcome-home",
  primarySection: "home",
  capabilities: [
    "Estate Map",
    "Visit Another Room",
    "Guidebook",
    "Seasonal Events",
    "Hidden Discoveries",
  ],
  suggestedActivities: [
    "Show the estate map",
    "Visit another room",
    "Browse the guidebook",
  ],
  tools: ["Estate Map", "Visit Another Room", "Estate Guide", "Guidebook"],
  relatedSpaceIds: ["library", "homestead", "gardens"],
  triggers: [
    "estate map",
    "visit another room",
    "wander",
    "explore",
    "guidebook",
    "show me the estate",
    "discover",
    "where can i go",
  ],
  aliases: ["homestead", "welcome home", "map"],
  defaultGreeting: "Where should we wander?",
  nextSuggestions: ["Restore", "Create", "Journal"],
  userNeeds: ["orient"],
};

/** Individual spaces — extend experiences with physical places */
const SPACES: EstateKnowledgeEntry[] = [
  {
    id: "clear-my-mind",
    kind: "space",
    name: "Clear My Mind",
    purpose: "Empty a crowded head.",
    description: "Continuous thought capture — one item at a time, no pressure.",
    experienceId: "restore",
    spaceId: "clear-my-mind",
    primarySection: "brain-dump",
    capabilities: ["Brain dump", "Thought capture", "Mental unload"],
    suggestedActivities: ["Dump what's on your mind", "Clear scattered thoughts"],
    tools: ["Brain Dump", "Thought Capture"],
    relatedSpaceIds: ["peaceful-places", "momentum-builder", "journal"],
    triggers: [
      "clear my mind",
      "brain dump",
      "scattered thoughts",
      "crowded head",
      "jumbled",
      "clear thoughts",
    ],
    aliases: ["clear my mind sunroom", "brain dump"],
    defaultGreeting: "What's on your mind?",
    nextSuggestions: ["Momentum", "Restore", "Journal"],
    userNeeds: ["overwhelmed", "anxious"],
  },
  {
    id: "coffee-house",
    kind: "space",
    name: "Coffee House",
    purpose: "Warm focus or gentle calm.",
    description: "Café atmosphere — good for light work or a soft reset.",
    experienceId: "restore",
    spaceId: "coffee-house",
    capabilities: ["Ambient café", "Light focus", "Warm calm"],
    suggestedActivities: ["Sit with a warm drink", "Soft background focus"],
    tools: ["Soundscapes", "Ambient Audio"],
    relatedSpaceIds: ["peaceful-places", "library", "focus-studio"],
    triggers: ["coffee house", "cafe", "coffee", "warm drink"],
    aliases: ["café", "coffee shop"],
    defaultGreeting: "Want to settle in here for a bit?",
    nextSuggestions: ["Focus", "Create", "Library"],
    userNeeds: ["calm", "focus", "rest"],
  },
  {
    id: "lakeside-hammock",
    kind: "space",
    name: "Lakeside Hammock",
    purpose: "Deep rest.",
    description: "Outdoor stillness — for when the body needs to stop.",
    experienceId: "restore",
    spaceId: "lakeside-hammock",
    capabilities: ["Rest", "Nature calm", "Stillness"],
    suggestedActivities: ["Rest by the water", "Let the mind drift"],
    tools: ["Soundscapes", "Nature Audio"],
    relatedSpaceIds: ["peaceful-places", "gardens", "porch-swing"],
    triggers: ["hammock", "lakeside", "lake", "rest outside", "stillness"],
    aliases: ["hammock", "by the lake"],
    defaultGreeting: "Want to rest here a while?",
    nextSuggestions: ["Journal", "Restore"],
    userNeeds: ["rest", "overwhelmed", "stressed"],
  },
  {
    id: "sunroom",
    kind: "space",
    name: "Sunroom",
    purpose: "Gentle daylight calm.",
    description: "Bright, peaceful indoor light — breathing and grounding.",
    experienceId: "restore",
    spaceId: "sunroom",
    capabilities: ["Breathing", "Grounding", "Daylight calm"],
    suggestedActivities: ["Breathe in the light", "Ground for a minute"],
    tools: ["Breathing", "Grounding"],
    relatedSpaceIds: ["clear-my-mind", "peaceful-places", "journal"],
    triggers: ["sunroom", "sun room", "daylight", "bright calm"],
    aliases: ["sun room"],
    defaultGreeting: "What kind of calm would help?",
    nextSuggestions: ["Clear My Mind", "Journal"],
    userNeeds: ["calm", "anxious", "overwhelmed"],
  },
  {
    id: "study-hall",
    kind: "space",
    name: "Study Hall",
    purpose: "Learn and research.",
    description: "Courses, Great Thinkers, and structured learning.",
    experienceId: "think",
    spaceId: "study-hall",
    primarySection: "momentum-institute",
    capabilities: ["Courses", "Great Thinkers", "Research", "Notes"],
    suggestedActivities: ["Study a topic", "Learn from Great Thinkers"],
    tools: ["Great Thinkers", "Courses", "Research", "Notes"],
    relatedSpaceIds: ["library", "observatory", "decision-compass"],
    triggers: ["study hall", "course", "learn", "institute", "great thinkers"],
    aliases: ["momentum institute", "learn"],
    defaultGreeting: "What would you like to learn today?",
    nextSuggestions: ["Think", "Momentum", "Library"],
    userNeeds: ["learn"],
  },
  {
    id: "round-table",
    kind: "space",
    name: "Boardroom",
    purpose: "Business headquarters.",
    description: "Strategy, offers, avatars, and operating decisions.",
    experienceId: "business",
    spaceId: "round-table",
    primarySection: "client-avatars",
    capabilities: BUSINESS.capabilities,
    suggestedActivities: BUSINESS.suggestedActivities,
    tools: BUSINESS.tools,
    relatedSpaceIds: BUSINESS.relatedSpaceIds,
    triggers: BUSINESS.triggers,
    aliases: ["boardroom", "round table", "business center"],
    defaultGreeting: BUSINESS.defaultGreeting,
    nextSuggestions: BUSINESS.nextSuggestions,
    userNeeds: ["business"],
  },
  {
    id: "art-studio",
    kind: "space",
    name: "Art Studio",
    purpose: "Visual creativity.",
    description: "Art-making and image creation — ties to Create and Grow.",
    experienceId: "play",
    spaceId: "art-studio",
    capabilities: ["Art", "Images", "Visual creation"],
    suggestedActivities: ["Make art", "Create an image"],
    tools: ["Art Studio", "AI Image"],
    relatedSpaceIds: ["creative-studio", "portfolio", "conservatory"],
    triggers: ["art studio", "make art", "draw", "paint", "visual art"],
    aliases: ["art room"],
    defaultGreeting: "What would you like to make?",
    nextSuggestions: ["Create", "Gallery", "Conservatory"],
    userNeeds: ["creative", "play"],
  },
  {
    id: "music-room",
    kind: "space",
    name: "Music Room",
    purpose: "Sound and inspiration.",
    description: "Music for focus, calm, or creative recharge.",
    experienceId: "play",
    spaceId: "music-room",
    capabilities: ["Music", "Focus audio", "Inspiration"],
    suggestedActivities: ["Listen", "Play focus music"],
    tools: ["Focus Music", "Ambient Audio"],
    relatedSpaceIds: ["focus-studio", "peaceful-places", "conservatory"],
    triggers: ["music room", "play music", "listen", "focus music"],
    aliases: ["music"],
    defaultGreeting: "What kind of sound would help?",
    nextSuggestions: ["Focus", "Restore", "Play"],
    userNeeds: ["focus", "play", "calm"],
  },
  {
    id: "library",
    kind: "space",
    name: "Library",
    purpose: "Quiet knowledge and reading.",
    description: "Research companion, volumes, and reflective reading.",
    experienceId: "think",
    spaceId: "library",
    capabilities: ["Reading", "Research", "Reference volumes"],
    suggestedActivities: ["Browse volumes", "Research quietly"],
    tools: ["Research", "Library Volumes"],
    relatedSpaceIds: ["reading-nook", "study-hall", "journal"],
    triggers: ["library", "read", "volumes", "books", "research quietly"],
    aliases: ["the library"],
    defaultGreeting: "What would you like to explore here?",
    nextSuggestions: ["Study Hall", "Journal", "Think"],
    userNeeds: ["learn", "reflective"],
  },
  {
    id: "reading-nook",
    kind: "space",
    name: "Reading Nook",
    purpose: "Personal quiet reading.",
    description: "Small, intimate reading — not the full Library.",
    experienceId: "journal",
    spaceId: "reading-nook",
    capabilities: ["Reading", "Quiet reflection"],
    suggestedActivities: ["Read quietly", "Reflect"],
    tools: ["Reading"],
    relatedSpaceIds: ["library", "journal", "porch-swing"],
    triggers: ["reading nook", "quiet read", "curl up with a book"],
    aliases: ["nook"],
    defaultGreeting: "Want to settle in with something to read?",
    nextSuggestions: ["Journal", "Library"],
    userNeeds: ["reflective", "rest"],
  },
];

export const ESTATE_BRAIN_ENTRIES: readonly EstateKnowledgeEntry[] = [
  CREATE,
  MOMENTUM,
  FOCUS,
  RESTORE,
  THINK,
  JOURNAL,
  GROW,
  PLAY,
  BUSINESS,
  EXPLORE,
  ...SPACES,
];

const BY_ID = new Map<string, EstateKnowledgeEntry>(
  ESTATE_BRAIN_ENTRIES.map((e) => [e.id, e]),
);

const BY_SPACE_ID = new Map<string, EstateKnowledgeEntry>();
for (const entry of ESTATE_BRAIN_ENTRIES) {
  BY_SPACE_ID.set(entry.spaceId, entry);
  if (entry.kind === "experience") {
    BY_SPACE_ID.set(entry.id, entry);
  }
}

export function estateBrainEntryById(id: string): EstateKnowledgeEntry | undefined {
  return BY_ID.get(id) ?? BY_SPACE_ID.get(id);
}

export function estateBrainEntryBySpaceId(
  spaceId: string,
): EstateKnowledgeEntry | undefined {
  return BY_SPACE_ID.get(spaceId);
}

export function allEstateBrainEntries(): readonly EstateKnowledgeEntry[] {
  return ESTATE_BRAIN_ENTRIES;
}

export function estateBrainExperiences(): EstateKnowledgeEntry[] {
  return ESTATE_BRAIN_ENTRIES.filter((e) => e.kind === "experience");
}

export function estateBrainSpaces(): EstateKnowledgeEntry[] {
  return ESTATE_BRAIN_ENTRIES.filter((e) => e.kind === "space");
}
