/**
 * Estate Registry™ — planned / partial catalog entries (awareness only in V1).
 * Matcher uses live entries only; these register Estate scope for future phases.
 */

import type { EstateRegistryEntry } from "../types";

export const WELCOME_HOME_ENTRY: EstateRegistryEntry = {
  id: "welcome-home",
  name: "Welcome Home",
  category: "room",
  purpose: "Estate Concierge — every conversation begins here.",
  memberDescription: "Welcome Home is where we pick up — never starting over.",
  primarySection: "home",
  objectId: "welcome-home",
  keywords: ["welcome", "home", "hello", "hi"],
  problemsSolved: ["orientation", "continuity"],
  outcomes: ["feel welcomed", "know where to begin"],
  journeyRole: "think",
  status: "live",
};

export const PLANNED_ESTATE_CATALOG: readonly EstateRegistryEntry[] = [
  {
    id: "conservatory",
    name: "Conservatory™",
    category: "room",
    purpose: "Think it through — planning and reflection atmosphere.",
    memberDescription: "The Conservatory is where we think things through together.",
    primarySection: "brain-dump",
    keywords: ["conservatory", "think through"],
    problemsSolved: ["need thinking space"],
    outcomes: ["clearer thinking"],
    journeyRole: "think",
    status: "planned",
  },
  {
    id: "business-mastery-minutes",
    name: "Business Mastery Minutes™",
    category: "knowledge",
    purpose: "Short applied business lessons.",
    memberDescription: "Business Mastery Minutes™ — practical lessons in minutes.",
    keywords: ["business mastery", "mastery minute"],
    problemsSolved: ["quick learning"],
    outcomes: ["applied insight"],
    journeyRole: "learn",
    relatedEntryIds: ["library"],
    status: "planned",
  },
  {
    id: "knowledge-cards",
    name: "Knowledge Cards",
    category: "collection",
    purpose: "Spark Cards — personalized entrepreneurial wisdom.",
    memberDescription: "Knowledge Cards meet you where you are in the business.",
    primarySection: "grow-spark-cards",
    objectId: "spark-cards",
    keywords: ["spark card", "knowledge card"],
    problemsSolved: ["bite-sized learning"],
    outcomes: ["actionable wisdom"],
    journeyRole: "learn",
    status: "planned",
  },
  {
    id: "templates-library",
    name: "Templates",
    category: "template",
    purpose: "Reusable business templates and artifacts.",
    memberDescription: "Templates when you want a proven starting point.",
    primarySection: "templates-library",
    keywords: ["template", "templates"],
    problemsSolved: ["blank page"],
    outcomes: ["faster creation"],
    journeyRole: "create",
    status: "planned",
  },
  {
    id: "client-avatar",
    name: "Client Avatar",
    category: "tool",
    purpose: "Ideal client clarity and messaging.",
    memberDescription: "Client Avatar work when you need to know who you serve.",
    primarySection: "client-avatars",
    keywords: ["client avatar", "ideal client"],
    problemsSolved: ["audience clarity"],
    outcomes: ["clearer messaging"],
    journeyRole: "plan",
    status: "planned",
  },
  {
    id: "evidence-bank",
    name: "Evidence Bank",
    category: "collection",
    purpose: "Wins and proof collected over time.",
    memberDescription: "Evidence Bank holds what you've already accomplished.",
    primarySection: "evidence-bank",
    keywords: ["evidence", "wins bank"],
    problemsSolved: ["forgetting progress"],
    outcomes: ["confidence from proof"],
    journeyRole: "reflect",
    status: "planned",
  },
  {
    id: "business-profile",
    name: "Business Profile",
    category: "tool",
    purpose: "Living business context for Spark.",
    memberDescription: "Your business profile — so Spark knows what you're building.",
    primarySection: "business-profile",
    keywords: ["business profile"],
    problemsSolved: ["re-explaining business"],
    outcomes: ["personalized guidance"],
    journeyRole: "plan",
    status: "planned",
  },
  {
    id: "stables",
    name: "The Stables™",
    category: "room",
    purpose: "Gentle confidence restoration — fear, doubt, and second-guessing.",
    memberDescription:
      "The Stables™ is where we rebuild courage without performance pressure.",
    primarySection: "stables",
    keywords: ["stables", "confidence", "courage", "nervous"],
    problemsSolved: ["fear", "self-doubt", "pricing anxiety"],
    outcomes: ["restored confidence", "honest next step"],
    journeyRole: "recover",
    status: "live",
  },
] as const;
