import type { SectionIdeasCatalog } from "../../sectionRuntime/sectionIdeas";

/** Facebook Community domain ideas — section ids from facebookCommunityMap. */
export const FACEBOOK_COMMUNITY_SECTION_IDEAS: SectionIdeasCatalog = {
  purpose_and_audience: [
    "A place for people who want support around one shared season of growth.",
    "Members should know in one sentence who belongs — and who will feel at home.",
    "Lead with belonging and clarity, not content volume.",
    "Serve people who want practical kindness more than performance.",
    "Name the season of life this community holds gently.",
    "Make it obvious why someone would return next week.",
  ],
  positioning_and_promise: [
    "Promise a tone: kind, practical, and free of performance pressure.",
    "Name what members can expect weekly — and what you won’t do.",
    "Keep the promise small enough to keep when life gets busy.",
    "Stand for calm progress — not hustle theater.",
    "Be clear about moderation so people feel safe.",
    "Promise presence over perfection.",
  ],
  naming_and_tagline: [
    "A name that sounds like a place people return to — not a product SKU.",
    "Tagline: who it’s for + the feeling they’ll get.",
    "Say it out loud — if it feels stiff, soften the words.",
    "Choose warmth over cleverness when they conflict.",
    "Make the name easy to say in a conversation.",
    "Avoid insider jargon in the first five words.",
  ],
  membership_questions_and_rules: [
    "Three house rules in plain language — kindness, relevance, no spam.",
    "Ask two questions that help you welcome people by name and need.",
    "Make it easy to know what’s welcome before someone posts.",
    "Invite people to share the hope that brought them.",
    "Keep rules short enough to read on a phone screen.",
    "Protect the room: clear consequences without harsh language.",
  ],
  welcome_and_onboarding: [
    "A warm first post that tells newcomers where to begin.",
    "Pin one ‘start here’ note so people never feel lost.",
    "Invite one small intro: name, hope, and what brought them.",
    "Greet people by name in the first day when you can.",
    "Point to one first win they can get in under ten minutes.",
    "Make onboarding feel like hospitality, not a checklist.",
  ],
  content_pillars_and_programming: [
    "Three pillars you can sustain — teach, celebrate, connect.",
    "Mix welcome, teaching, and celebration so the feed feels alive.",
    "Batch ideas once, then show up calmly through the week.",
    "Leave room for member-led conversation every week.",
    "Repeat helpful themes — familiarity builds trust.",
    "Protect quiet weeks: a lighter rhythm still counts.",
  ],
  content_calendar: [
    "Two steady posts a week beats seven you can’t sustain.",
    "Leave room for real conversation — not every slot needs a broadcast.",
    "Plan the first two weeks before you open the door wide.",
    "Schedule prompts, not performances.",
    "Align posts with member energy — mornings or midweek often work.",
    "Keep a rainy-day prompt list for low-energy days.",
  ],
  launch_plan: [
    "Invite from warm circles first — trust travels with people.",
    "One clear ‘why join’ line for shares and announcements.",
    "Open softly: guidelines, welcome, then a gentle first prompt.",
    "Seed early conversation with a few trusted members.",
    "Don’t rush growth until the welcome still feels personal.",
    "Celebrate the first week of belonging, not the member count.",
  ],
  growth_and_referral: [
    "Grow only as fast as you can still greet newcomers kindly.",
    "Ask happy members to invite one person who fits — not everyone.",
    "A simple share sentence beats a complicated funnel.",
    "Quality of conversation over size of the group.",
    "Invite seasons: open windows, then tend the room.",
    "Thank referrers in ways that feel human, not transactional.",
  ],
  project_handoff: [
    "List the operating rhythm Projects should carry next.",
    "Name the owner of replies, moderation, and weekly prompts.",
    "Hand off the promise — not a duplicate of the whole Create workspace.",
    "Document the weekly cadence in plain language.",
    "Note what must stay founder-owned versus what can be delegated.",
    "Capture the tone so handoff doesn’t sound like software.",
  ],
};
