import type { CompanionPlace, CompanionPlaceId } from "../types";

/** Companion Place Library — every permanent place in the homestead. */
export const COMPANION_PLACE_LIBRARY: CompanionPlace[] = [
  {
    id: "living-room",
    name: "Living Room",
    purpose: "First welcome, daily return, quiet conversation",
    emotionalPromise: "I've been expecting you.",
    hospitalityStyle: "warm-host",
    lightingProfile: "morning-to-evening warmth, window-led",
    signatureObjectId: "spark-mug",
    soundProfile: "soft birds, distant wind, optional wind chimes",
    motionProfile: "sunlight drift, curtain sway, foliage outside",
    conversationCadence: "warm-host",
    transitionAnimation: "fade-through-light",
    shariPresenceLevel: "full",
    userLeavesFeeling: "Welcomed, steadier, not alone",
    available: true,
  },
  {
    id: "window-seat",
    name: "Window Seat",
    purpose: "Reflection, heavy feelings, listening without fixing",
    emotionalPromise: "You don't have to carry this alone.",
    hospitalityStyle: "quiet-listener",
    lightingProfile: "soft side light, rain-muted",
    signatureObjectId: "window-blanket",
    soundProfile: "rain, distant wind, silence",
    motionProfile: "rain on glass, curtain drift",
    conversationCadence: "quiet-listener",
    transitionAnimation: "slow-drift-in",
    shariPresenceLevel: "nearby",
    userLeavesFeeling: "Held, less alone with hard thoughts",
    available: false,
  },
  {
    id: "kitchen-table",
    name: "Kitchen Table",
    purpose: "Morning start, tea, gentle planning",
    emotionalPromise: "We'll take today one bite at a time.",
    hospitalityStyle: "warm-host",
    lightingProfile: "early morning, steam-warm",
    signatureObjectId: "tea-set",
    soundProfile: "kettle, morning birds",
    motionProfile: "steam, soft sunlight",
    conversationCadence: "warm-host",
    transitionAnimation: "steam-rise",
    shariPresenceLevel: "full",
    userLeavesFeeling: "Nourished, ready to begin gently",
    available: false,
  },
  {
    id: "planning-table",
    name: "Planning Table",
    purpose: "Morning clarity — decide what today needs, without pressure",
    emotionalPromise: "My day suddenly feels more manageable.",
    hospitalityStyle: "gentle-guide",
    lightingProfile: "golden morning, bright afternoon, warm lamp evening",
    signatureObjectId: "leather-planner",
    soundProfile: "morning birds, soft breeze, Iowa quiet",
    motionProfile: "curtains, leaves, birds at feeder, coffee steam",
    conversationCadence: "gentle-guide",
    transitionAnimation: "page-turn",
    shariPresenceLevel: "ambient",
    userLeavesFeeling:
      "Clearer — not because everything changed, because everything became clearer",
    available: false,
  },
  {
    id: "business-office",
    name: "Business Office",
    purpose: "Strategy, decisions, professional focus",
    emotionalPromise: "We'll find the next honest step.",
    hospitalityStyle: "gentle-guide",
    lightingProfile: "afternoon clarity",
    signatureObjectId: "vision-board",
    soundProfile: "quiet focus, distant city hush",
    motionProfile: "minimal — lamp steady",
    conversationCadence: "gentle-guide",
    transitionAnimation: "door-open",
    shariPresenceLevel: "nearby",
    userLeavesFeeling: "Capable, oriented, less stuck",
    available: false,
  },
  {
    id: "creative-studio",
    name: "Creative Studio",
    purpose: "Ideas, making, playful exploration",
    emotionalPromise: "Your ideas deserve room to breathe.",
    hospitalityStyle: "creative-partner",
    lightingProfile: "golden hour, color-forward",
    signatureObjectId: "sketchbook",
    soundProfile: "light music optional, creative hush",
    motionProfile: "butterflies outside, light shift",
    conversationCadence: "creative-partner",
    transitionAnimation: "color-bloom",
    shariPresenceLevel: "nearby",
    userLeavesFeeling: "Inspired, permission to play",
    available: false,
  },
  {
    id: "workshop",
    name: "Workshop",
    purpose: "Building, crafts, hands-on projects",
    emotionalPromise: "We'll figure out the next piece together.",
    hospitalityStyle: "creative-partner",
    lightingProfile: "practical warm work light",
    signatureObjectId: "workbench",
    soundProfile: "tools at rest, soft ambient",
    motionProfile: "dust motes, lamp glow",
    conversationCadence: "creative-partner",
    transitionAnimation: "bench-settle",
    shariPresenceLevel: "nearby",
    userLeavesFeeling: "Capable of making progress",
    available: false,
  },
  {
    id: "focus-studio",
    name: "Visual Thinking Studio",
    purpose: "Visual Thinking home — mapping, planning, and charting a path forward",
    emotionalPromise: "I'll help you see this clearly.",
    hospitalityStyle: "thoughtful-companion",
    lightingProfile: "warm daylight, brass picture lights",
    signatureObjectId: "timer-candle",
    soundProfile: "quiet study hush",
    motionProfile: "minimal — map light and paper stillness",
    conversationCadence: "collaborative",
    transitionAnimation: "still-enter",
    shariPresenceLevel: "nearby",
    userLeavesFeeling: "Clearer direction — able to chart the next step",
    available: true,
  },
  {
    id: "sunroom-over-pond",
    name: "Sunroom Over The Pond",
    purpose: "Focus My Brain — attention regulation and cognitive grounding",
    emotionalPromise: "My mind slows down here without trying.",
    hospitalityStyle: "thoughtful-companion",
    lightingProfile: "filtered sunroom light, water reflections",
    signatureObjectId: "pond-anchor",
    soundProfile: "soft flowing water — continuous, never loud",
    motionProfile: "water flow, goldfish, lily drift, plant sway",
    conversationCadence: "minimal",
    transitionAnimation: "water-settle",
    shariPresenceLevel: "nearby",
    userLeavesFeeling:
      "Mentally slower in a good way — able to stay with one thought",
    available: false,
  },
  {
    id: "reading-nook",
    name: "Reading Nook",
    purpose: "Books, reflection, saved ideas",
    emotionalPromise: "Nothing important gets lost.",
    hospitalityStyle: "quiet-listener",
    lightingProfile: "lamp pool, evening soft",
    signatureObjectId: "reading-lamp",
    soundProfile: "page silence, rain optional",
    motionProfile: "lamp glow, curtain still",
    conversationCadence: "quiet-listener",
    transitionAnimation: "lamp-on",
    shariPresenceLevel: "ambient",
    userLeavesFeeling: "Thoughts honored and kept safe",
    available: false,
  },
  {
    id: "garden",
    name: "Garden",
    purpose: "Seasonal grounding, gentle perspective",
    emotionalPromise: "Notice what's blooming.",
    hospitalityStyle: "thoughtful-companion",
    lightingProfile: "outdoor morning to golden hour",
    signatureObjectId: "wildflowers",
    soundProfile: "birds, breeze, bees",
    motionProfile: "foliage, butterflies, leaves",
    conversationCadence: "thoughtful-companion",
    transitionAnimation: "path-forward",
    shariPresenceLevel: "ambient",
    userLeavesFeeling: "Grounded, part of something larger",
    available: false,
  },
  {
    id: "garden-path",
    name: "Garden Path",
    purpose: "Walking thoughts, gentle movement",
    emotionalPromise: "We can take the long way today.",
    hospitalityStyle: "thoughtful-companion",
    lightingProfile: "dappled outdoor light",
    signatureObjectId: "garden-basket",
    soundProfile: "footsteps, birds, wind",
    motionProfile: "leaves, birds, path light",
    conversationCadence: "thoughtful-companion",
    transitionAnimation: "walk-in",
    shariPresenceLevel: "ambient",
    userLeavesFeeling: "Unhurried, thoughts sorting themselves",
    available: false,
  },
  {
    id: "greenhouse",
    name: "Greenhouse",
    purpose: "Growth, nurturing long projects",
    emotionalPromise: "Some things grow slowly — that's allowed.",
    hospitalityStyle: "thoughtful-companion",
    lightingProfile: "diffused glass light",
    signatureObjectId: "seedling-tray",
    soundProfile: "humid quiet, water drip",
    motionProfile: "condensation, soft growth",
    conversationCadence: "thoughtful-companion",
    transitionAnimation: "glass-glow",
    shariPresenceLevel: "ambient",
    userLeavesFeeling: "Patient hope for what's growing",
    available: false,
  },
  {
    id: "back-deck",
    name: "Back Deck",
    purpose: "End of day, wind-down, reflection",
    emotionalPromise: "We can let today end gently.",
    hospitalityStyle: "reflective-friend",
    lightingProfile: "evening, golden to night",
    signatureObjectId: "rocking-chair",
    soundProfile: "crickets, wind, distant chimes",
    motionProfile: "fireflies, curtain, lamp",
    conversationCadence: "reflective-friend",
    transitionAnimation: "sunset-settle",
    shariPresenceLevel: "nearby",
    userLeavesFeeling: "Released from the day",
    available: false,
  },
  {
    id: "fire-circle",
    name: "Fire Circle",
    purpose: "Celebration, storytelling, warmth",
    emotionalPromise: "Your wins deserve warmth.",
    hospitalityStyle: "celebratory",
    lightingProfile: "fire-lit evening",
    signatureObjectId: "fire-pit",
    soundProfile: "fire crackle, night sounds",
    motionProfile: "fire flicker, ember drift",
    conversationCadence: "warm-host",
    transitionAnimation: "ember-rise",
    shariPresenceLevel: "full",
    userLeavesFeeling: "Celebrated, connected",
    available: false,
  },
  {
    id: "library",
    name: "Library",
    purpose: "Deep reference, saved work, learning",
    emotionalPromise: "What you've learned stays here.",
    hospitalityStyle: "quiet-listener",
    lightingProfile: "study lamp, afternoon calm",
    signatureObjectId: "book-ladder",
    soundProfile: "library hush",
    motionProfile: "dust in sunbeam",
    conversationCadence: "quiet-listener",
    transitionAnimation: "shelf-glide",
    shariPresenceLevel: "ambient",
    userLeavesFeeling: "Knowledge organized, accessible",
    available: false,
  },
  {
    id: "front-porch",
    name: "Front Porch",
    purpose: "Arrival, transition between world and home",
    emotionalPromise: "You made it home.",
    hospitalityStyle: "warm-host",
    lightingProfile: "porch light, twilight",
    signatureObjectId: "welcome-mat",
    soundProfile: "distant neighborhood, wind chime",
    motionProfile: "swing sway, flag soft",
    conversationCadence: "warm-host",
    transitionAnimation: "porch-step",
    shariPresenceLevel: "nearby",
    userLeavesFeeling: "Transitioned, safe to exhale",
    available: false,
  },
  {
    id: "barn",
    name: "Barn",
    purpose: "Big projects, storage, long-horizon work",
    emotionalPromise: "Big work can live here without crowding today.",
    hospitalityStyle: "gentle-guide",
    lightingProfile: "practical barn light",
    signatureObjectId: "project-board",
    soundProfile: "barn quiet, wind through boards",
    motionProfile: "light through slats",
    conversationCadence: "gentle-guide",
    transitionAnimation: "barn-door",
    shariPresenceLevel: "ambient",
    userLeavesFeeling: "Projects have a home",
    available: false,
  },
  {
    id: "outlook-point",
    name: "Outlook Point",
    purpose: "Perspective, vision, long view",
    emotionalPromise: "From here you can see further.",
    hospitalityStyle: "reflective-friend",
    lightingProfile: "open sky, horizon light",
    signatureObjectId: "bench-at-edge",
    soundProfile: "wide wind, distant birds",
    motionProfile: "cloud drift, grass sway",
    conversationCadence: "reflective-friend",
    transitionAnimation: "horizon-reveal",
    shariPresenceLevel: "ambient",
    userLeavesFeeling: "Perspective restored",
    available: false,
  },
  {
    id: "adventure-room",
    name: "Adventure Room",
    purpose: "Vacation countdown, travel dreams, exploration",
    emotionalPromise: "Adventure is approaching — quietly prepared.",
    hospitalityStyle: "celebratory",
    lightingProfile: "bright morning anticipation",
    signatureObjectId: "travel-guide",
    soundProfile: "birds, clock, map rustle",
    motionProfile: "sunlight, clouds",
    conversationCadence: "warm-host",
    transitionAnimation: "map-unfold",
    shariPresenceLevel: "full",
    userLeavesFeeling: "Excited, prepared, not frantic",
    available: false,
  },
  {
    id: "future-wings",
    name: "Future Wings",
    purpose: "Vision, launches, what comes next",
    emotionalPromise: "What you're building has room to grow.",
    hospitalityStyle: "celebratory",
    lightingProfile: "forward light, dawn energy",
    signatureObjectId: "blueprint-scroll",
    soundProfile: "quiet anticipation",
    motionProfile: "light rays, soft shimmer",
    conversationCadence: "gentle-guide",
    transitionAnimation: "wing-open",
    shariPresenceLevel: "nearby",
    userLeavesFeeling: "Hopeful about what's ahead",
    available: false,
  },
];

export function placeById(id: CompanionPlaceId): CompanionPlace {
  return (
    COMPANION_PLACE_LIBRARY.find((place) => place.id === id) ??
    COMPANION_PLACE_LIBRARY[0]!
  );
}

export function availablePlaces(): CompanionPlace[] {
  return COMPANION_PLACE_LIBRARY.filter((place) => place.available);
}
