/**
 * Dual-read migration seam — bridge legacy catalog / parent types → registry.
 *
 * Purpose: migration support only.
 * Does NOT bless launchability as readiness.
 * Does NOT generate ready records from all catalog labels.
 */

import type { CreateCatalogItem } from "@/lib/createCatalogData";
import type { CreateParentType } from "@/lib/createEstate/createParentTypes";
import {
  CREATION_REGISTRY_SEED_ITEMS,
  getCreationRegistrySeedItem,
} from "./items.seed";
import type { CreationRegistryItem } from "./types";

const LEGACY_PARENT_TO_REGISTRY: Record<string, string> = {
  event: "event_plan",
  "marketing-plan": "marketing_plan",
  "business-plan": "business_plan",
  "facebook-community": "facebook_community",
};

function unverifiedProvisional(
  partial: Omit<
    CreationRegistryItem,
    | "routeVerified"
    | "saveVerified"
    | "reopenVerified"
    | "printVerified"
    | "exportVerified"
    | "projectHandoffVerified"
    | "requiredActionsVerified"
    | "lifecycleStatus"
  > & {
    lifecycleStatus?: CreationRegistryItem["lifecycleStatus"];
  },
): CreationRegistryItem {
  return {
    ...partial,
    lifecycleStatus: partial.lifecycleStatus ?? "needs-audit",
    routeVerified: false,
    saveVerified: false,
    reopenVerified: false,
    printVerified: false,
    exportVerified: false,
    projectHandoffVerified: false,
    requiredActionsVerified: false,
  };
}

/**
 * Look up a seeded registry item by legacy member-facing label / search term.
 * Returns undefined when the label is not among the foundation seeds.
 */
export function findRegistryItemByLegacyLabel(
  label: string,
): CreationRegistryItem | undefined {
  const needle = label.trim().toLowerCase();
  if (!needle) return undefined;

  for (const item of CREATION_REGISTRY_SEED_ITEMS) {
    if (item.name.toLowerCase() === needle) return item;
    if (item.singularLabel.toLowerCase() === needle) return item;
    if (item.legacyCatalogLabels?.some((l) => l.toLowerCase() === needle)) {
      return item;
    }
    if (item.searchTerms.some((t) => t.toLowerCase() === needle)) {
      return item;
    }
  }
  return undefined;
}

/**
 * Map a Browse parent type into a registry item.
 * Known guided parents return the canonical seed (still unverified).
 * Unknown parents become provisional needs-audit records — never ready.
 */
export function registryItemFromParentType(
  parent: CreateParentType,
): CreationRegistryItem {
  const seededId = LEGACY_PARENT_TO_REGISTRY[parent.id];
  if (seededId) {
    const seeded = getCreationRegistrySeedItem(seededId);
    if (seeded) return seeded;
  }

  const byLabel = findRegistryItemByLegacyLabel(parent.label);
  if (byLabel) return byLabel;

  for (const catalogLabel of parent.catalogLabels) {
    const hit = findRegistryItemByLegacyLabel(catalogLabel);
    if (hit) return hit;
  }

  return unverifiedProvisional({
    id: `legacy_parent_${parent.id}`,
    name: parent.label,
    singularLabel: parent.label,
    // Provisional park under Develop Ideas until a real migration maps them.
    categoryId: "develop_ideas",
    subcategoryId: "unmigrated_legacy",
    shortDescription: parent.hint,
    userOutcome: parent.hint,
    searchTerms: [parent.label, ...parent.catalogLabels].map((s) =>
      s.toLowerCase(),
    ),
    relevantBusinessTypes: [],
    audienceSensitivity: "none",
    supportsMultipleAvatars: false,
    helpfulBusinessProfileFields: [],
    minimumContextQuestions: [],
    relatedCreationIds: [],
    usuallyCreatedTogetherIds: [],
    canBecomeProject: false,
    recommendedChamberMemberIds: [],
    recommendedMapTypes: [],
    recommendedBoardRoles: [],
    builderType: "guided-conversation",
    route: `create/legacy/parent/${parent.id}`,
    priority: "later",
    lifecycleStatus: "needs-audit",
    owner: "legacy-create-parent-types",
    implementationNotes: [
      "Provisional adapter record — not a blessed registry migration.",
      "Launchability in Browse must not be treated as readiness.",
    ],
    auditNotes: [
      "Generated by registryItemFromParentType; subcategory may be placeholder.",
    ],
    legacyParentTypeId: parent.id,
    legacyCatalogLabels: [...parent.catalogLabels],
  });
}

/**
 * Map a legacy catalog item into a registry item.
 * Seeded labels return the canonical seed; others are provisional needs-audit.
 * Never sets ready / verification from catalog presence alone.
 */
export function registryItemFromCatalogItem(
  item: CreateCatalogItem,
): CreationRegistryItem {
  const seeded = findRegistryItemByLegacyLabel(item.label);
  if (seeded) return seeded;

  return unverifiedProvisional({
    id: `legacy_catalog_${slugify(item.label)}`,
    name: item.label,
    singularLabel: item.label,
    categoryId: "develop_ideas",
    subcategoryId: "unmigrated_legacy",
    shortDescription: `Legacy catalog entry: ${item.label}`,
    userOutcome: `Open legacy Create flow for ${item.label}`,
    searchTerms: [
      item.label.toLowerCase(),
      ...(item.matchTerms ?? []).map((t) => t.toLowerCase()),
    ],
    relevantBusinessTypes: [],
    audienceSensitivity: "none",
    supportsMultipleAvatars: false,
    helpfulBusinessProfileFields: [],
    minimumContextQuestions: [],
    relatedCreationIds: [],
    usuallyCreatedTogetherIds: [],
    canBecomeProject: false,
    recommendedChamberMemberIds: [],
    recommendedMapTypes: [],
    recommendedBoardRoles: [],
    builderType: "guided-conversation",
    route: item.route
      ? `create/legacy/route/${item.route}`
      : `create/legacy/catalog/${slugify(item.label)}`,
    priority: "later",
    lifecycleStatus: "needs-audit",
    owner: "legacy-create-catalog",
    implementationNotes: [
      "Provisional adapter record from CREATE_CATALOG.",
      "Catalog launchability is not registry readiness.",
    ],
    auditNotes: ["Generated by registryItemFromCatalogItem."],
    legacyCatalogLabels: [item.label],
  });
}

function slugify(label: string): string {
  return label
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}
