/**
 * 047 — Shared Create Asset Registry
 * One definition per asset. Blueprints reference; never duplicate templates.
 */

import type { CreateAssetDefinition } from "./types";

export const CREATE_ASSET_REGISTRY: readonly CreateAssetDefinition[] = [
  {
    id: "asset-event-plan",
    name: "Event Plan",
    purpose: "Master plan for the gathering.",
    templateId: "tpl-event-plan",
    editable: true,
    defaultRequired: true,
    dependencyAssetIds: [],
    unlockSignals: ["ecosystem_started"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["project-management", "leadership"],
    boardAdvisorIds: [],
    projectWorkMode: "reference_only",
    cartographyEligible: true,
    completionHint: "Purpose, audience, outcomes, and format are named.",
  },
  {
    id: "asset-budget",
    name: "Budget Worksheet",
    purpose: "Track planned, committed, and spent amounts.",
    templateId: "tpl-budget",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["outcomes", "viability", "budget"],
    primaryChamberMemberId: "finance",
    supportingChamberMemberIds: ["events", "project-management"],
    boardAdvisorIds: ["finance", "strategy"],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Categories and a working total exist.",
  },
  {
    id: "asset-timeline",
    name: "Timeline",
    purpose: "Milestones from now through follow-up.",
    templateId: "tpl-timeline",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["dates", "venue", "outcomes"],
    primaryChamberMemberId: "project-management",
    supportingChamberMemberIds: ["events"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Key milestones have dates.",
  },
  {
    id: "asset-venue-comparison",
    name: "Venue Comparison",
    purpose: "Compare venue options against experience needs.",
    templateId: "tpl-venue-comparison",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["format", "audience"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["finance"],
    boardAdvisorIds: [],
    projectWorkMode: "none",
    cartographyEligible: true,
    completionHint: "At least two options or a selected venue noted.",
  },
  {
    id: "asset-venue-notes",
    name: "Venue Contract Notes",
    purpose: "Capture requirements, holds, and contract details.",
    templateId: "tpl-venue-notes",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["venue"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["finance", "client-relationships"],
    boardAdvisorIds: ["finance"],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: false,
    completionHint: "Selected venue and critical terms are recorded.",
  },
  {
    id: "asset-registration-form",
    name: "Registration Form",
    purpose: "Collect attendee sign-ups.",
    templateId: "tpl-registration-form",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["venue", "dates", "outcomes"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["content", "marketing", "systems"],
    boardAdvisorIds: [],
    projectWorkMode: "required_tasks",
    cartographyEligible: true,
    completionHint: "Fields and open/close timing are defined.",
  },
  {
    id: "asset-confirmation-email",
    name: "Confirmation Email",
    purpose: "Confirm registration and set expectations.",
    templateId: "tpl-confirmation-email",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: ["asset-registration-form"],
    unlockSignals: ["registration"],
    primaryChamberMemberId: "content",
    supportingChamberMemberIds: ["marketing", "events", "client-relationships"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: false,
    completionHint: "Subject and body are ready to send.",
  },
  {
    id: "asset-reminder-email",
    name: "Reminder Email",
    purpose: "Remind attendees before the event.",
    templateId: "tpl-reminder-email",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: ["asset-registration-form"],
    unlockSignals: ["registration", "dates"],
    primaryChamberMemberId: "content",
    supportingChamberMemberIds: ["marketing", "events"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: false,
    completionHint: "Send timing and body are set.",
  },
  {
    id: "asset-welcome-guide",
    name: "Welcome Guide",
    purpose: "Orient attendees before they arrive.",
    templateId: "tpl-welcome-guide",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["venue", "dates", "audience"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["content", "wellness"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Arrival, what to bring, and first-hour flow are clear.",
  },
  {
    id: "asset-packing-list",
    name: "Packing List",
    purpose: "Help attendees prepare for the gathering.",
    templateId: "tpl-packing-list",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["venue", "format"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["content"],
    boardAdvisorIds: [],
    projectWorkMode: "none",
    cartographyEligible: false,
    completionHint: "Must-bring items are listed.",
  },
  {
    id: "asset-agenda",
    name: "Agenda",
    purpose: "High-level flow of the experience.",
    templateId: "tpl-agenda",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["outcomes", "dates"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["content", "leadership"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Blocks of time map to the outcome.",
  },
  {
    id: "asset-session-plans",
    name: "Session Plans",
    purpose: "Detail each session or block.",
    templateId: "tpl-session-plans",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: ["asset-agenda"],
    unlockSignals: ["agenda"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["content", "learning", "leadership"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Each session has an outcome and owner.",
  },
  {
    id: "asset-speaker-packet",
    name: "Speaker Information Packet",
    purpose: "Give speakers everything they need to prepare.",
    templateId: "tpl-speaker-packet",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: ["asset-agenda"],
    unlockSignals: ["speakers", "agenda"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: [
      "content",
      "marketing",
      "client-relationships",
      "leadership",
    ],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Logistics, brief, and deadlines are included.",
  },
  {
    id: "asset-speaker-agreement",
    name: "Speaker Agreement",
    purpose: "Confirm expectations and terms with speakers.",
    templateId: "tpl-speaker-agreement",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: ["asset-speaker-packet"],
    unlockSignals: ["speakers"],
    primaryChamberMemberId: "client-relationships",
    supportingChamberMemberIds: ["events", "finance"],
    boardAdvisorIds: ["finance"],
    projectWorkMode: "required_tasks",
    cartographyEligible: false,
    completionHint: "Terms are written and ready to share.",
  },
  {
    id: "asset-vendor-list",
    name: "Vendor Checklist",
    purpose: "Track vendors and what each must deliver.",
    templateId: "tpl-vendor-list",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["venue", "budget"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["finance", "project-management"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Critical vendors are named with status.",
  },
  {
    id: "asset-volunteer-handbook",
    name: "Volunteer Handbook",
    purpose: "Orient volunteers to roles and care standards.",
    templateId: "tpl-volunteer-handbook",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["volunteers", "venue"],
    primaryChamberMemberId: "leadership",
    supportingChamberMemberIds: ["events", "people-culture"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Roles, schedule basics, and contact path exist.",
  },
  {
    id: "asset-volunteer-schedule",
    name: "Volunteer Schedule",
    purpose: "Assign people to shifts and stations.",
    templateId: "tpl-volunteer-schedule",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: ["asset-volunteer-handbook"],
    unlockSignals: ["volunteers", "agenda"],
    primaryChamberMemberId: "leadership",
    supportingChamberMemberIds: ["events", "project-management"],
    boardAdvisorIds: [],
    projectWorkMode: "required_tasks",
    cartographyEligible: true,
    completionHint: "Shifts cover critical moments.",
  },
  {
    id: "asset-run-of-show",
    name: "Run of Show",
    purpose: "Minute-by-minute production guide for the day.",
    templateId: "tpl-run-of-show",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: ["asset-agenda"],
    unlockSignals: ["agenda", "venue"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["presentations", "systems"],
    boardAdvisorIds: [],
    projectWorkMode: "required_tasks",
    cartographyEligible: true,
    completionHint: "Cues, owners, and backups are listed.",
  },
  {
    id: "asset-tech-checklist",
    name: "Technology Checklist",
    purpose: "Confirm tech and AV readiness.",
    templateId: "tpl-tech-checklist",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["venue", "format", "technology"],
    primaryChamberMemberId: "systems",
    supportingChamberMemberIds: ["events", "ai-technology"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Critical tech items are tested or owned.",
  },
  {
    id: "asset-accessibility-plan",
    name: "Accessibility Plan",
    purpose: "Make the experience reachable for everyone who should attend.",
    templateId: "tpl-accessibility-plan",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["venue", "audience"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["wellness", "leadership"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Access needs and accommodations are named.",
  },
  {
    id: "asset-emergency-plan",
    name: "Emergency Plan",
    purpose: "Protect people if something goes wrong.",
    templateId: "tpl-emergency-plan",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["venue"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["leadership", "wellness"],
    boardAdvisorIds: ["strategy"],
    projectWorkMode: "required_tasks",
    cartographyEligible: false,
    completionHint: "Contacts and escalation path are clear.",
  },
  {
    id: "asset-thank-you-email",
    name: "Thank You Email",
    purpose: "Close the loop with attendees after the event.",
    templateId: "tpl-thank-you-email",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["follow_up", "delivery"],
    primaryChamberMemberId: "content",
    supportingChamberMemberIds: ["marketing", "events", "client-relationships"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: false,
    completionHint: "Message and send window are ready.",
  },
  {
    id: "asset-debrief",
    name: "Debrief",
    purpose: "Capture what worked and what to change.",
    templateId: "tpl-debrief",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["follow_up", "delivery", "debrief"],
    primaryChamberMemberId: "events",
    supportingChamberMemberIds: ["leadership", "project-management"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Wins, misses, and next decisions are written.",
  },
  {
    id: "asset-archive",
    name: "Archive",
    purpose: "Store reusable materials for the next gathering.",
    templateId: "tpl-archive",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: ["asset-debrief"],
    unlockSignals: ["debrief", "archive"],
    primaryChamberMemberId: "knowledge-management",
    supportingChamberMemberIds: ["events"],
    boardAdvisorIds: [],
    projectWorkMode: "reference_only",
    cartographyEligible: true,
    completionHint: "Key assets are linked and findable.",
  },
  {
    id: "asset-sponsor-package",
    name: "Sponsor Package",
    purpose: "Invite and fulfill sponsors.",
    templateId: "tpl-sponsor-package",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["sponsors", "budget", "outcomes"],
    primaryChamberMemberId: "marketing",
    supportingChamberMemberIds: ["events", "finance", "partnerships"],
    boardAdvisorIds: ["finance", "marketing", "strategy"],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Offer levels and benefits are clear.",
  },
  {
    id: "asset-email-sequence",
    name: "Email Sequence",
    purpose: "A reusable multi-email journey.",
    templateId: "tpl-email-sequence",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["marketing", "registration", "launch"],
    primaryChamberMemberId: "marketing",
    supportingChamberMemberIds: ["content", "events"],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: true,
    completionHint: "Sequence purpose and first emails exist.",
  },
  {
    id: "asset-checklist",
    name: "Checklist",
    purpose: "Generic actionable checklist template.",
    templateId: "tpl-checklist",
    editable: true,
    defaultRequired: false,
    dependencyAssetIds: [],
    unlockSignals: ["preparation"],
    primaryChamberMemberId: "project-management",
    supportingChamberMemberIds: [],
    boardAdvisorIds: [],
    projectWorkMode: "suggested_tasks",
    cartographyEligible: false,
    completionHint: "Items are listed and owned.",
  },
];

const BY_ID = new Map(CREATE_ASSET_REGISTRY.map((a) => [a.id, a]));

export function getCreateAssetById(id: string): CreateAssetDefinition | null {
  return BY_ID.get(id) ?? null;
}

export function listCreateAssets(): readonly CreateAssetDefinition[] {
  return CREATE_ASSET_REGISTRY;
}

export function assertAssetRegistryIntegrity(): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const a of CREATE_ASSET_REGISTRY) {
    if (ids.has(a.id)) errors.push(`Duplicate asset id: ${a.id}`);
    ids.add(a.id);
    for (const dep of a.dependencyAssetIds) {
      if (!BY_ID.has(dep)) errors.push(`${a.id} missing dependency ${dep}`);
    }
  }
  return errors;
}
