import type { LivingBorderElement, LivingBorderElementId } from "./types";

export const LIVING_BORDER_ELEMENT_REGISTRY: Record<
  LivingBorderElementId,
  LivingBorderElement
> = {
  "curtain-left": {
    id: "curtain-left",
    label: "Curtains",
    zone: "left",
    cssClass: "companion-living-border__curtain companion-living-border__curtain--left",
    mayAnimate: true,
    mayEvolve: true,
    isPlaceholder: true,
  },
  "curtain-right": {
    id: "curtain-right",
    label: "Curtains",
    zone: "right",
    cssClass: "companion-living-border__curtain companion-living-border__curtain--right",
    mayAnimate: true,
    mayEvolve: true,
    isPlaceholder: true,
  },
  trees: {
    id: "trees",
    label: "Trees",
    zone: "right",
    cssClass: "companion-living-border__trees",
    mayAnimate: true,
    mayEvolve: true,
    isPlaceholder: true,
  },
  bird: {
    id: "bird",
    label: "Bird",
    zone: "right",
    cssClass: "companion-living-border__bird",
    mayAnimate: true,
    mayEvolve: true,
  },
  steam: {
    id: "steam",
    label: "Steam from mug",
    zone: "right",
    cssClass: "companion-living-border__steam",
    mayAnimate: true,
    mayEvolve: true,
  },
  candle: {
    id: "candle",
    label: "Candle",
    zone: "left",
    cssClass: "companion-living-border__candle",
    mayAnimate: true,
    mayEvolve: true,
  },
  "lamp-glow": {
    id: "lamp-glow",
    label: "Lamp glow",
    zone: "left",
    cssClass: "companion-living-border__lamp-glow",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  bookshelf: {
    id: "bookshelf",
    label: "Bookshelf",
    zone: "left",
    cssClass: "companion-living-border__bookshelf",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  blanket: {
    id: "blanket",
    label: "Blanket",
    zone: "bottom",
    cssClass: "companion-living-border__blanket",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  window: {
    id: "window",
    label: "Window",
    zone: "right",
    cssClass: "companion-living-border__trees",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  flowers: {
    id: "flowers",
    label: "Fresh flowers",
    zone: "right",
    cssClass: "companion-living-border__trees",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  "bird-feeder": {
    id: "bird-feeder",
    label: "Bird feeder",
    zone: "right",
    cssClass: "companion-living-border__bird",
    mayAnimate: true,
    mayEvolve: true,
  },
  "coffee-mug": {
    id: "coffee-mug",
    label: "Coffee mug",
    zone: "right",
    cssClass: "companion-living-border__steam",
    mayAnimate: true,
    mayEvolve: true,
  },
  kinsey: {
    id: "kinsey",
    label: "Kinsey",
    zone: "bottom",
    cssClass: "companion-living-border__blanket",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  aquarium: {
    id: "aquarium",
    label: "Aquarium bubbles",
    zone: "left",
    cssClass: "companion-living-border__lamp-glow",
    mayAnimate: true,
    mayEvolve: false,
    isPlaceholder: true,
  },
  planner: {
    id: "planner",
    label: "Planner",
    zone: "bottom",
    cssClass: "companion-living-border__bookshelf",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  "craft-shelves": {
    id: "craft-shelves",
    label: "Craft shelves",
    zone: "left",
    cssClass: "companion-living-border__bookshelf",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  landscape: {
    id: "landscape",
    label: "Outdoor landscape",
    zone: "right",
    cssClass: "companion-living-border__trees",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  rain: {
    id: "rain",
    label: "Rain on glass",
    zone: "top",
    cssClass: "companion-living-border__steam",
    mayAnimate: true,
    mayEvolve: true,
  },
  snow: {
    id: "snow",
    label: "Snow outside",
    zone: "top",
    cssClass: "companion-living-border__trees",
    mayAnimate: false,
    mayEvolve: true,
    isPlaceholder: true,
  },
  "pond-water": {
    id: "pond-water",
    label: "Flowing pond water",
    zone: "bottom",
    cssClass: "companion-living-border__pond-water",
    mayAnimate: true,
    mayEvolve: false,
  },
  goldfish: {
    id: "goldfish",
    label: "Goldfish",
    zone: "bottom",
    cssClass: "companion-living-border__goldfish",
    mayAnimate: true,
    mayEvolve: true,
  },
  "water-lilies": {
    id: "water-lilies",
    label: "Water lilies",
    zone: "bottom",
    cssClass: "companion-living-border__water-lilies",
    mayAnimate: true,
    mayEvolve: true,
  },
  "pergola-vines": {
    id: "pergola-vines",
    label: "Pergola vines",
    zone: "top",
    cssClass: "companion-living-border__pergola-vines",
    mayAnimate: true,
    mayEvolve: true,
  },
};

export function borderElement(id: LivingBorderElementId): LivingBorderElement {
  return LIVING_BORDER_ELEMENT_REGISTRY[id];
}
