export {
  COMPANION_LIVING_BORDER_CLASS,
  COMPANION_PROTECTED_ZONE_CLASS,
  COMPANION_WORKSPACE_FROSTED_CLASS,
  COMPANION_WORKSPACE_HEADER_CLASS,
  COMPANION_WORKSPACE_PAGE_CLASS,
} from "./tokens";
