/**
 * Leaf data only — no imports from Create runtime (avoids circular deps).
 * Business Plan section map (201–224 handmade / service / creator / organizing).
 */

import type { WorkTypeMapSectionDef } from "../types";

export const BUSINESS_PLAN_MAP_SECTIONS: readonly WorkTypeMapSectionDef[] = [
  { id: "purpose_vision", title: "Business Vision" },
  { id: "products_offers", title: "Products and Offers" },
  { id: "customers_audience", title: "Customers and Audience" },
  { id: "positioning", title: "Positioning" },
  { id: "pricing", title: "Pricing" },
  { id: "inventory", title: "Inventory" },
  { id: "booth_design", title: "Booth Design" },
  { id: "show_discovery", title: "Show Discovery" },
  { id: "jury_applications", title: "Jury Applications" },
  { id: "annual_calendar", title: "Annual Calendar" },
  { id: "travel_logistics", title: "Travel and Logistics" },
  { id: "packing_loading", title: "Packing and Vehicle Loading" },
  { id: "pos_checkout", title: "POS and Checkout" },
  { id: "lead_capture", title: "Lead Capture and Email Growth" },
  { id: "customer_relationships", title: "Customer Relationships" },
  { id: "vendor_documents", title: "Vendor Documents" },
  { id: "restocking_seasonal", title: "Restocking and Seasonal Planning" },
  { id: "shop_setup", title: "Shop Setup" },
  { id: "branding", title: "Branding" },
  { id: "photography", title: "Photography" },
  { id: "listings_seo", title: "Listings, Keywords, and SEO" },
  { id: "marketplaces", title: "Marketplaces and Channels" },
  { id: "shipping_packaging", title: "Shipping and Packaging" },
  { id: "customer_service", title: "Customer Service" },
  { id: "reviews_reputation", title: "Reviews and Reputation" },
  { id: "ads", title: "Ads" },
  { id: "email_marketing", title: "Email Marketing" },
  { id: "social_pinterest", title: "Social and Pinterest" },
  { id: "launches_promotions", title: "Launches and Promotions" },
  { id: "seasonal_planning", title: "Seasonal Planning" },
  { id: "automation", title: "Automation" },
  { id: "shot_lists", title: "Shot Lists" },
  { id: "lighting", title: "Lighting" },
  { id: "backgrounds", title: "Backgrounds" },
  { id: "styling", title: "Styling" },
  { id: "lifestyle_images", title: "Lifestyle Images" },
  { id: "video_clips", title: "Video Clips" },
  { id: "editing_workflow", title: "Editing Workflow" },
  { id: "image_organization", title: "Image Organization" },
  { id: "accessibility_alt_text", title: "Accessibility and Alt Text" },
  { id: "marketplace_image_requirements", title: "Marketplace Image Requirements" },
  { id: "cost_of_goods", title: "Cost of Goods" },
  { id: "labor_cost", title: "Labor" },
  { id: "overhead", title: "Overhead" },
  { id: "profit_margin", title: "Profit Margin" },
  { id: "inventory_forecasting", title: "Inventory Forecasting" },
  { id: "bundles", title: "Bundles" },
  { id: "seasonal_stock", title: "Seasonal Stock" },
  { id: "reorder_points", title: "Reorder Points" },
  { id: "best_sellers", title: "Best Sellers" },
  { id: "dead_inventory", title: "Dead Inventory" },
  { id: "collection_planning", title: "Collection Planning" },
  { id: "production_schedule", title: "Production Schedule" },
  { id: "launch_timeline", title: "Launch Timeline" },
  { id: "seasonal_campaigns", title: "Seasonal Campaigns" },
  { id: "expenses_taxes", title: "Expenses and Taxes" },
  { id: "profitability", title: "Profitability" },
  { id: "analytics", title: "Analytics" },
  { id: "linked_event_work", title: "Linked Event and Campaign Work" },
  { id: "next_actions", title: "Next Actions" },
  { id: "review_rhythm", title: "Review Rhythm" },
  { id: "post_show_review", title: "Post-Show Review" },
  // 207–210 Service & Expert
  { id: "audience_buyer_architecture", title: "Audience and Buyer Architecture" },
  { id: "signature_talk_portfolio", title: "Signature Talk Portfolio" },
  { id: "speaking_offers", title: "Speaking Offers" },
  { id: "speaker_marketing", title: "Speaker Marketing" },
  { id: "booking_pipeline", title: "Booking Pipeline" },
  { id: "speaker_proposal", title: "Speaker Proposal" },
  { id: "event_preparation", title: "Event Preparation" },
  { id: "delivery_experience", title: "Delivery and Experience" },
  { id: "post_event_followup", title: "Post-Event Follow-Up" },
  { id: "speaker_operations", title: "Speaker Operations" },
  { id: "client_fit", title: "Client Fit" },
  { id: "coaching_offers", title: "Coaching Offers" },
  { id: "coaching_framework", title: "Coaching Framework" },
  { id: "coaching_marketing", title: "Coaching Marketing" },
  { id: "discovery_enrollment", title: "Discovery and Enrollment" },
  { id: "coaching_onboarding", title: "Coaching Onboarding" },
  { id: "coaching_delivery", title: "Coaching Delivery" },
  { id: "completion_renewal", title: "Completion and Renewal" },
  { id: "coaching_operations", title: "Coaching Operations" },
  { id: "service_architecture", title: "Service Architecture" },
  { id: "diagnostic_method", title: "Diagnostic Method" },
  { id: "lead_generation", title: "Lead Generation" },
  { id: "qualification_discovery", title: "Qualification and Discovery" },
  { id: "proposal_contract", title: "Proposal and Contract" },
  { id: "engagement_kickoff", title: "Engagement Kickoff" },
  { id: "consulting_delivery", title: "Consulting Delivery" },
  { id: "client_communication", title: "Client Communication" },
  { id: "outcomes_closeout", title: "Outcomes and Closeout" },
  { id: "consulting_operations", title: "Consulting Operations" },
  { id: "service_menu", title: "Service Menu" },
  { id: "client_acquisition", title: "Client Acquisition" },
  { id: "inquiry_qualification", title: "Inquiry and Qualification" },
  { id: "estimate_proposal", title: "Estimate and Proposal" },
  { id: "service_onboarding", title: "Service Onboarding" },
  { id: "delivery_workflow", title: "Delivery Workflow" },
  { id: "change_issue_management", title: "Change and Issue Management" },
  { id: "completion_payment", title: "Completion and Payment" },
  { id: "followup_retention", title: "Follow-Up and Retention" },
  { id: "service_operations", title: "Service Operations" },
  // 211–214 Creator & Knowledge
  { id: "reader_market_architecture", title: "Reader and Market Architecture" },
  { id: "book_portfolio_strategy", title: "Book Portfolio Strategy" },
  { id: "publishing_path", title: "Publishing Path" },
  { id: "book_development_workflow", title: "Book Development Workflow" },
  { id: "author_platform", title: "Author Platform" },
  { id: "book_marketing", title: "Book Marketing" },
  { id: "sales_distribution", title: "Sales and Distribution" },
  { id: "book_to_business", title: "Book-to-Business Expansion" },
  { id: "author_operations", title: "Author Operations" },
  { id: "learner_demand_validation", title: "Learner and Demand Validation" },
  { id: "course_model", title: "Course Model" },
  { id: "learning_outcomes", title: "Learning Outcomes" },
  { id: "curriculum_sequence", title: "Curriculum and Sequence" },
  { id: "content_production", title: "Course Content Production" },
  { id: "student_experience", title: "Student Experience" },
  { id: "course_enrollment", title: "Course Enrollment" },
  { id: "course_delivery_ops", title: "Course Delivery Operations" },
  { id: "course_measurement", title: "Course Measurement" },
  { id: "course_portfolio_growth", title: "Course Portfolio Growth" },
  { id: "member_profile_fit", title: "Member Profile and Fit" },
  { id: "membership_model", title: "Membership Model" },
  { id: "value_architecture", title: "Value Architecture" },
  { id: "member_onboarding", title: "Member Onboarding" },
  { id: "membership_rhythm", title: "Membership Rhythm" },
  { id: "community_health", title: "Community Health" },
  { id: "retention_renewal", title: "Retention and Renewal" },
  { id: "membership_growth", title: "Membership Growth" },
  { id: "membership_operations", title: "Membership Operations" },
  { id: "membership_measurement", title: "Membership Measurement" },
  { id: "creator_audience", title: "Creator Audience" },
  { id: "content_pillars", title: "Content Pillars" },
  { id: "platform_strategy", title: "Platform Strategy" },
  { id: "content_production_system", title: "Content Production System" },
  { id: "audience_growth", title: "Audience Growth" },
  { id: "trust_relationship", title: "Trust and Relationship" },
  { id: "creator_monetization", title: "Creator Monetization" },
  { id: "sponsorship_partnerships", title: "Sponsorship and Partnerships" },
  { id: "creator_analytics", title: "Creator Analytics" },
  { id: "content_asset_library", title: "Content Asset Library" },
  { id: "creator_operations", title: "Creator Operations" },
  // 219–224 Professional Organizing
  { id: "organizing_clients", title: "Organizing Clients" },
  { id: "organizing_services", title: "Organizing Services" },
  { id: "organizing_inquiry", title: "Organizing Inquiry" },
  { id: "organizing_assessment", title: "Organizing Assessment" },
  { id: "organizing_proposal", title: "Organizing Proposal" },
  { id: "organizing_delivery", title: "Organizing Delivery" },
  { id: "organizing_maintenance", title: "Organizing Maintenance" },
  { id: "organizing_privacy", title: "Organizing Privacy and Safety" },
  { id: "organizing_growth", title: "Organizing Growth" },
  { id: "organizing_operations", title: "Organizing Operations" },
  { id: "space_users", title: "Space Users" },
  { id: "current_state_space", title: "Current-State Space Map" },
  { id: "sort_decide", title: "Sort and Decide" },
  { id: "space_design", title: "Space Design" },
  { id: "labels_containers", title: "Labels and Containers" },
  { id: "accessibility_flow", title: "Accessibility and Flow" },
  { id: "maintenance_space", title: "Space Maintenance" },
  { id: "info_inventory", title: "Information Inventory" },
  { id: "naming_structure", title: "Naming and Structure" },
  { id: "retrieval_rules", title: "Retrieval Rules" },
  { id: "permissions_archives", title: "Permissions and Archives" },
  { id: "email_notes_photos", title: "Email Notes and Photos" },
  { id: "digital_maintenance", title: "Digital Maintenance" },
  { id: "workflow_map", title: "Workflow Map" },
  { id: "roles_handoffs", title: "Roles and Handoffs" },
  { id: "sop_design", title: "SOP Design" },
  { id: "recurring_rhythms", title: "Recurring Rhythms" },
  { id: "visibility_ops", title: "Operational Visibility" },
  { id: "ops_maintenance", title: "Procedure Maintenance" },
  { id: "priority_structure", title: "Priority Structure" },
  { id: "initiative_map", title: "Initiative Map" },
  { id: "decision_log_org", title: "Decision Visibility" },
  { id: "meeting_rhythms", title: "Meeting Rhythms" },
  { id: "alignment_load", title: "Alignment and Load" },
  { id: "management_cadence", title: "Management Cadence" },
];

export const BUSINESS_PLAN_DEFAULT_FOCUS: readonly string[] = [
  "purpose_vision",
  "products_offers",
  "customers_audience",
  "pricing",
  "next_actions",
  "profitability",
];

export const BUSINESS_PLAN_WORK_TYPE_ID = "business_plan" as const;
