import type { GraphNodeKind, GraphRelationshipKind } from "../types";

export const GRAPH_NODE_KIND_LABELS: Record<GraphNodeKind, string> = {
  mission: "Mission",
  research: "Research",
  "research-question": "Research Question",
  finding: "Finding",
  pattern: "Pattern",
  opportunity: "Opportunity",
  risk: "Risk",
  decision: "Decision",
  "executive-question": "Executive Question",
  "executive-brief": "Executive Brief",
  workshop: "Workshop",
  course: "Course",
  product: "Product",
  feature: "Feature",
  "listening-room": "Listening Room",
  content: "Content",
  newsletter: "Newsletter",
  blog: "Blog",
  podcast: "Podcast",
  video: "Video",
  "lead-magnet": "Lead Magnet",
  campaign: "Campaign",
  "ghl-funnel": "GoHighLevel Funnel",
  automation: "Automation",
  "customer-feedback": "Customer Feedback",
  "companion-conversation": "Companion Conversation",
  "founder-journal": "Founder Journal",
  "lesson-learned": "Lesson Learned",
  success: "Success",
  failure: "Failure",
  "team-member": "Team Member",
  project: "Project",
  "roadmap-item": "Roadmap Item",
  "analytics-event": "Analytics Event",
  "ai-development": "AI Development",
  competitor: "Competitor",
  technology: "Technology",
  book: "Book",
  article: "Article",
  "research-paper": "Research Paper",
};

export const GRAPH_RELATIONSHIP_KIND_LABELS: Record<GraphRelationshipKind, string> = {
  supports: "Supports",
  created_from: "Created From",
  inspired_by: "Inspired By",
  answers: "Answers",
  solves: "Solves",
  improves: "Improves",
  blocks: "Blocks",
  duplicates: "Duplicates",
  extends: "Extends",
  references: "References",
  belongs_to: "Belongs To",
  generated: "Generated",
  requires: "Requires",
  launched_with: "Launched With",
  marketed_by: "Marketed By",
  validated_by: "Validated By",
  contradicted_by: "Contradicted By",
  superseded_by: "Superseded By",
  learned_from: "Learned From",
  remembered_from: "Remembered From",
  linked_to: "Linked To",
  related_to: "Related To",
};
