/**
 * Rich purpose profile overrides — judgment layer only.
 * Unlisted places receive derived profiles from the knowledge registry.
 */

import type { EstatePurposeProfile } from "../types";

export const ESTATE_PURPOSE_PROFILE_OVERRIDES: Readonly<
  Partial<Record<string, Omit<EstatePurposeProfile, "placeId" | "displayName">>>
> = {
  conservatory: {
    purpose: "Mental reset — stillness beneath living water",
    primaryFeeling: "Wonder",
    secondaryFeelings: ["Stillness", "Peace", "Clarity"],
    energyLevel: "low",
    idealActivities: [
      "Reading",
      "Reflection",
      "Meditation",
      "Listening",
      "Relaxing",
    ],
    conversationStyle: "quiet",
    recommendedVisitMinutes: { min: 10, max: 30 },
    bestFor: [
      "Stress",
      "Burnout",
      "Decision fatigue",
      "Mental reset",
      "Overwhelm",
    ],
    notRecommendedFor: [
      "High-energy brainstorming",
      "Urgent planning",
      "Fast execution",
    ],
    relatedPlaceIds: [
      "reflection-pond",
      "journal",
      "reading-nook",
      "library",
      "peaceful-places",
    ],
    musicRecommendations: [
      "Calming instrumental",
      "Peaceful Places soundscapes",
    ],
    featureRecommendations: ["focus-audio", "breathe"],
    discoveryLevel: "gentle",
  },
  "reflection-pond": {
    purpose: "Quiet reflection beside still water",
    primaryFeeling: "Calm",
    secondaryFeelings: ["Perspective", "Softness"],
    energyLevel: "low",
    idealActivities: ["Reflection", "Journaling", "Breathing", "Thinking"],
    conversationStyle: "gentle",
    recommendedVisitMinutes: { min: 10, max: 45 },
    bestFor: ["Overwhelm", "Big decisions", "Needing perspective"],
    notRecommendedFor: ["High-energy collaboration", "Loud celebration"],
    relatedPlaceIds: ["conservatory", "journal", "seat-at-pond"],
    musicRecommendations: ["Nature sounds", "Peaceful Places"],
    featureRecommendations: ["breathe"],
    discoveryLevel: "familiar",
  },
  library: {
    purpose: "Quiet knowledge and unhurried reading",
    primaryFeeling: "Curiosity",
    secondaryFeelings: ["Focus", "Depth"],
    energyLevel: "medium",
    idealActivities: ["Reading", "Research", "Study", "Reflection"],
    conversationStyle: "research-companion",
    recommendedVisitMinutes: { min: 20, max: 90 },
    bestFor: ["Learning", "Research", "Deep reading"],
    notRecommendedFor: ["Quick brain dump", "Physical rest"],
    relatedPlaceIds: ["reading-nook", "study-hall", "personal-library"],
    musicRecommendations: ["Library hush", "Gallery ambience"],
    featureRecommendations: ["focus"],
    discoveryLevel: "featured",
  },
  "reading-nook": {
    purpose: "Intimate reading — one chair, one page",
    primaryFeeling: "Cozy focus",
    secondaryFeelings: ["Safety", "Quiet"],
    energyLevel: "low",
    idealActivities: ["Reading", "Quiet reflection", "Light journaling"],
    conversationStyle: "quiet",
    recommendedVisitMinutes: { min: 15, max: 60 },
    bestFor: ["Personal reading", "Introverted focus", "Gentle rest"],
    notRecommendedFor: ["Group strategy", "Loud collaboration"],
    relatedPlaceIds: ["library", "stairway-reading-nook", "journal"],
    musicRecommendations: ["Evening hearth", "Soft focus audio"],
    featureRecommendations: ["focus-audio"],
    discoveryLevel: "familiar",
  },
  observatory: {
    purpose: "Big-picture thinking under open sky",
    primaryFeeling: "Perspective",
    secondaryFeelings: ["Wonder", "Clarity"],
    energyLevel: "medium",
    idealActivities: ["Thinking", "Decision-making", "Stargazing", "Planning"],
    conversationStyle: "decision-facilitation",
    recommendedVisitMinutes: { min: 15, max: 45 },
    bestFor: ["Important decisions", "Strategic thinking", "Feeling stuck"],
    notRecommendedFor: ["Detailed drafting", "Overwhelmed shutdown"],
    relatedPlaceIds: [
      "decision-compass",
      "round-table",
      "house-possibility-observatory",
    ],
    musicRecommendations: ["Gallery hush"],
    featureRecommendations: ["strategies"],
    discoveryLevel: "familiar",
  },
  greenhouse: {
    purpose: "Gentle growth — plant ideas in calm light",
    primaryFeeling: "Hope",
    secondaryFeelings: ["Warmth", "Patience"],
    energyLevel: "low",
    idealActivities: ["Reflection", "Light planning", "Reading", "Breathing"],
    conversationStyle: "coaching",
    recommendedVisitMinutes: { min: 10, max: 40 },
    bestFor: ["Recovery", "Soft reset", "Planting new ideas"],
    notRecommendedFor: ["Urgent deadlines", "Heavy celebration"],
    relatedPlaceIds: ["conservatory", "gardens", "journal"],
    musicRecommendations: ["Greenhouse birdsong"],
    featureRecommendations: ["breathe", "clear-my-mind"],
    discoveryLevel: "featured",
  },
  journal: {
    purpose: "Outdoor writing and honest reflection",
    primaryFeeling: "Air and clarity",
    secondaryFeelings: ["Peace", "Honesty"],
    energyLevel: "low",
    idealActivities: ["Journaling", "Reflection", "Thinking", "Breathing"],
    conversationStyle: "reflective-writing",
    recommendedVisitMinutes: { min: 10, max: 45 },
    bestFor: ["Processing feelings", "Decision clarity", "Quiet writing"],
    notRecommendedFor: ["Team meetings", "Fast execution"],
    relatedPlaceIds: ["reflection-pond", "conservatory", "reading-nook"],
    musicRecommendations: ["Garden fountain", "Nature hush"],
    featureRecommendations: ["clear-my-mind"],
    discoveryLevel: "familiar",
  },
  "coffee-house": {
    purpose: "Warm focus with gentle café energy",
    primaryFeeling: "Belonging",
    secondaryFeelings: ["Warmth", "Light focus"],
    energyLevel: "medium",
    idealActivities: ["Light work", "Conversation", "Thinking", "Reading"],
    conversationStyle: "open-presence",
    recommendedVisitMinutes: { min: 15, max: 60 },
    bestFor: ["Soft focus", "Thinking aloud", "Gentle momentum"],
    notRecommendedFor: ["Deep overwhelm shutdown", "Silent meditation"],
    relatedPlaceIds: ["tea-room", "library", "reading-nook"],
    musicRecommendations: ["Café ambience"],
    featureRecommendations: ["focus", "focus-audio"],
    discoveryLevel: "featured",
  },
  "music-room": {
    purpose: "Sound for focus, calm, or creative recharge",
    primaryFeeling: "Inspiration",
    secondaryFeelings: ["Rhythm", "Calm"],
    energyLevel: "medium",
    idealActivities: ["Listening", "Focus work", "Creative warm-up"],
    conversationStyle: "open-presence",
    recommendedVisitMinutes: { min: 10, max: 45 },
    bestFor: ["Focus music", "Creative energy", "Listening room feel"],
    notRecommendedFor: ["Silent reflection", "Heavy writing"],
    relatedPlaceIds: ["peaceful-places", "conservatory", "creative-studio"],
    musicRecommendations: ["Focus music", "Piano loft ambience"],
    featureRecommendations: ["focus-audio", "focus-session"],
    discoveryLevel: "familiar",
  },
  "clear-my-mind": {
    purpose: "Empty a crowded head safely",
    primaryFeeling: "Relief",
    secondaryFeelings: ["Release", "Space"],
    energyLevel: "low",
    idealActivities: ["Brain dump", "Thought capture", "Mental unload"],
    conversationStyle: "quiet-capture",
    recommendedVisitMinutes: { min: 5, max: 30 },
    bestFor: ["Overwhelm", "Scattered thoughts", "Mental clutter"],
    notRecommendedFor: ["Polished drafting", "Celebration"],
    relatedPlaceIds: ["sunroom", "conservatory", "peaceful-places"],
    musicRecommendations: ["Soft restoration audio"],
    featureRecommendations: ["clear-my-mind", "brain-parking-lot"],
    discoveryLevel: "featured",
  },
  "decision-compass": {
    purpose: "When a choice feels heavy",
    primaryFeeling: "Clarity",
    secondaryFeelings: ["Steadiness", "Direction"],
    energyLevel: "medium",
    idealActivities: ["Decision-making", "Weighing options", "Writing"],
    conversationStyle: "decision-facilitation",
    recommendedVisitMinutes: { min: 20, max: 60 },
    bestFor: ["Hard choices", "Strategy forks", "Priority clarity"],
    notRecommendedFor: ["Pure rest", "Celebration"],
    relatedPlaceIds: ["round-table", "observatory", "strategy-studio"],
    musicRecommendations: [],
    featureRecommendations: ["strategies"],
    discoveryLevel: "gentle",
  },
  "round-table": {
    purpose: "Business headquarters — strategy and operating decisions",
    primaryFeeling: "Authority",
    secondaryFeelings: ["Focus", "Momentum"],
    energyLevel: "high",
    idealActivities: ["Strategy", "Planning", "Business decisions"],
    conversationStyle: "decision-facilitation",
    recommendedVisitMinutes: { min: 30, max: 120 },
    bestFor: ["Business planning", "Offers", "Operating decisions"],
    notRecommendedFor: ["Burnout recovery", "Silent meditation"],
    relatedPlaceIds: ["strategy-studio", "goals-projects", "decision-compass"],
    musicRecommendations: [],
    featureRecommendations: ["projects", "create"],
    discoveryLevel: "familiar",
  },
  "house-possibility-outside": {
    purpose: "Wonder and discovery at the Treehouse threshold",
    primaryFeeling: "Curiosity",
    secondaryFeelings: ["Possibility", "Playfulness"],
    energyLevel: "medium",
    idealActivities: ["Exploration", "Discovery", "Reflection"],
    conversationStyle: "discovery-dialogue",
    recommendedVisitMinutes: { min: 15, max: 60 },
    bestFor: ["Curiosity", "Legacy thinking", "Creative wonder"],
    notRecommendedFor: ["Urgent execution", "Overwhelm shutdown"],
    relatedPlaceIds: [
      "house-possibility-discovery-chest",
      "house-possibility-legacy-room",
      "house-possibility-observatory",
    ],
    musicRecommendations: [],
    featureRecommendations: [],
    discoveryLevel: "hidden",
  },
};
