import type { SectionIdeasCatalog } from "../../sectionRuntime/sectionIdeas";

/** Marketing Plan domain ideas — section ids from marketingPlanMap. */
export const MARKETING_PLAN_SECTION_IDEAS: SectionIdeasCatalog = {
  purpose_outcome: [
    "Help the right people feel seen — and know the next step without a sales pitch.",
    "Create steady visibility that supports one clear offer this season.",
    "Build trust before the ask, so interest feels natural instead of forced.",
    "Make it easier for warm people to say yes without a long funnel.",
    "Protect your energy: fewer channels, clearer message, calmer rhythm.",
    "Turn quiet interest into conversations you actually want to have.",
  ],
  business_offer: [
    "Name the offer in one sentence: who it’s for and what changes.",
    "Keep one primary offer in focus; supporting products can wait.",
    "Describe the result people hire you for — not every feature you deliver.",
    "Make the first yes small enough to try without fear.",
    "Clarify what’s included so people don’t have to guess.",
    "Pair the offer with the season of life it serves.",
  ],
  people_to_reach: [
    "Start with people who already trust you a little — warm is easier than cold.",
    "Describe one real person you’d love to help next month.",
    "Name the problem they whisper about, not the title on their LinkedIn.",
    "Who is ready now — not who might be ready someday.",
    "Find the people already gathering where you can show up calmly.",
    "Write to one person; publish for many.",
  ],
  current_situation: [
    "What’s already working enough to build on — even if it’s small.",
    "Where energy leaks: too many channels, unclear message, or no rhythm.",
    "One constraint that must shape the plan (time, budget, or capacity).",
    "What you’ve tried that taught you something useful.",
    "Where warm interest already exists — even if it’s quiet.",
    "What you refuse to do this season so the plan stays human.",
  ],
  positioning_message: [
    "A simple line: for [people] who want [outcome] without [pain].",
    "Say what you stand for — and what you gently refuse to do.",
    "Make the message short enough to remember after one read.",
    "Lead with relief, not features.",
    "Use language your best client already uses.",
    "If a neighbor wouldn’t get it, rewrite it once more.",
  ],
  marketing_goals: [
    "One visibility goal and one relationship goal for the next 90 days.",
    "A number you can feel proud of even if it’s modest.",
    "Prefer consistency over a burst you can’t sustain.",
    "Measure conversations and clarity — not vanity.",
    "Choose a goal that still works on a low-energy week.",
    "Define ‘enough’ before you start chasing more.",
  ],
  channels: [
    "Two channels you’ll show up in weekly — not every platform at once.",
    "Meet people where they already gather; don’t invent a new square.",
    "Pair one owned channel (email/list) with one discovery channel.",
    "Pick the channel you can keep when life gets busy.",
    "Use conversation spaces before broadcast spaces when trust is thin.",
    "Retire one channel so the remaining ones get your best attention.",
  ],
  content_approach: [
    "Teach one useful idea, then invite one gentle next step.",
    "Reuse a single story across formats instead of inventing new ones daily.",
    "Write like a letter to one person, then publish.",
    "Batch once, show up calmly through the week.",
    "Share process and progress — not only polished outcomes.",
    "End most pieces with a question that invites a real reply.",
  ],
  next_actions: [
    "Three actions you can finish this week without new tools.",
    "One conversation, one piece of content, one list touch.",
    "Schedule the smallest step first so momentum has somewhere to land.",
    "Write the message before you pick the graphics.",
    "Ask one warm person for a conversation this week.",
    "Block one quiet hour for the work that actually moves people.",
  ],
  measures: [
    "Track one leading signal (replies, clicks, conversations) — not vanity.",
    "Decide what ‘enough’ looks like before you start measuring.",
    "Review monthly: keep, tweak, or stop — no shame in stopping.",
    "Notice energy cost alongside results.",
    "Celebrate relationship warmth as a real metric.",
    "If a number doesn’t guide a decision, stop tracking it.",
  ],
};
