import type { AdvisoryMember, AdvisoryMemberId } from "../types";

function member(
  partial: AdvisoryMember,
): AdvisoryMember {
  return partial;
}

export const ADVISORY_BOARD_MEMBERS: AdvisoryMember[] = [
  member({
    id: "ceo",
    name: "CEO",
    role: "Chief Executive",
    expertise: ["Vision", "Market positioning", "Strategic bets", "Capital allocation"],
    decisionStyle: "Decisive when evidence aligns; defers when mission clarity is low.",
    primaryConcerns: ["Strategic coherence", "Member trust", "Sustainable growth"],
    strengths: ["Seeing the whole board", "Saying no to distraction"],
    typicalQuestions: [
      "Does this strengthen our core promise?",
      "What are we not building if we choose this?",
    ],
    sampleRecommendations: [
      "Protect the mission chain before opening new surfaces.",
      "One bold bet beats five polite experiments.",
    ],
  }),
  member({
    id: "visionary",
    name: "Visionary",
    role: "Long-Range Vision",
    expertise: ["Ten-year estate", "Category creation", "Transformation narrative"],
    decisionStyle: "Imagines futures first; grounds in member dignity.",
    primaryConcerns: ["Spark Feeling™", "Belonging", "Timeless beauty"],
    strengths: ["Naming what members will feel before we build it"],
    typicalQuestions: ["Will someone want to stay here in five years?"],
    sampleRecommendations: ["Beauty before information — always."],
  }),
  member({
    id: "strategist",
    name: "Strategist",
    role: "Executive Strategy",
    expertise: ["Roadmaps", "Trade-offs", "Mission sequencing"],
    decisionStyle: "Maps dependencies; prefers explicit kill criteria.",
    primaryConcerns: ["Fragmentation", "Competing priorities", "Mission drift"],
    strengths: ["Mission chains", "Executive Strategy Center thinking"],
    typicalQuestions: ["What must be true before the next phase?"],
    sampleRecommendations: ["Sequence: re-entry → workshop → content → revenue."],
  }),
  member({
    id: "product-manager",
    name: "Product Manager",
    role: "Product",
    expertise: ["Member outcomes", "Scope control", "Release discipline"],
    decisionStyle: "Evidence-led; hates feature menus.",
    primaryConcerns: ["Cognitive load", "Capability parity across rooms"],
    strengths: ["Translating pain into shippable slices"],
    typicalQuestions: ["What is the smallest proof that helps a member tomorrow?"],
    sampleRecommendations: ["Ship one listening scene before a second workspace."],
  }),
  member({
    id: "marketing-director",
    name: "Marketing Director",
    role: "Marketing",
    expertise: ["Demand generation", "Nurture", "Brand voice", "Campaign timing"],
    decisionStyle: "Narrative-first; rejects hype.",
    primaryConcerns: ["Message-market fit", "Gentle Restart alignment"],
    strengths: ["Connecting missions to PostCraft and GHL"],
    typicalQuestions: ["What story makes the member feel safe to return?"],
    sampleRecommendations: ["Campaign waits until the estate moment is real."],
  }),
  member({
    id: "sales-director",
    name: "Sales Director",
    role: "Revenue",
    expertise: ["Offer ladder", "Conversion", "Workshop-to-course path"],
    decisionStyle: "Trust-based selling; permission before pitch.",
    primaryConcerns: ["Ethical urgency", "Offer clarity"],
    strengths: ["Workshop as proof before course investment"],
    typicalQuestions: ["Where does revenue naturally follow transformation?"],
    sampleRecommendations: ["Validate with one cohort before scaling price."],
  }),
  member({
    id: "customer-experience",
    name: "Customer Experience",
    role: "Member Experience",
    expertise: ["Onboarding", "Support themes", "Return journeys"],
    decisionStyle: "Member voice is authority; watches drop-off.",
    primaryConcerns: ["First session trust", "Absence without shame"],
    strengths: ["Hospitality language", "Recovery flows"],
    typicalQuestions: ["How does a tired member experience this on day one?"],
    sampleRecommendations: ["Conversation-first arrival — no workspace quiz."],
  }),
  member({
    id: "adhd-expert",
    name: "ADHD Expert",
    role: "ADHD Entrepreneurship",
    expertise: ["Executive function", "Interruption recovery", "Realistic pacing"],
    decisionStyle: "Assumes variable energy; rejects shame framing.",
    primaryConcerns: ["Restart friction", "Decision fatigue", "Overwhelm"],
    strengths: ["Naming the hidden churn moment after interruption"],
    typicalQuestions: ["Does this reduce guilt about being away?"],
    sampleRecommendations: ["Calm re-entry before productivity prompts."],
  }),
  member({
    id: "behavioral-psychology",
    name: "Behavioral Psychology",
    role: "Behavior & Motivation",
    expertise: ["Habit design", "Permission", "Identity-safe nudges"],
    decisionStyle: "Observes patterns; never labels the person.",
    primaryConcerns: ["Surveillance feeling", "Toxic positivity"],
    strengths: ["Steady belonging without streaks"],
    typicalQuestions: ["Will this feel like care or tracking?"],
    sampleRecommendations: ["Celebrate return, not attendance."],
  }),
  member({
    id: "learning-designer",
    name: "Learning Designer",
    role: "Learning Experience",
    expertise: ["Workshops", "Micro-learning", "Scaffolded depth"],
    decisionStyle: "Progressive disclosure; one concept per beat.",
    primaryConcerns: ["Overload in live sessions", "Async dignity"],
    strengths: ["Workshop → micro-lesson → course ladder"],
    typicalQuestions: ["Can an overwhelmed brain hold this in one sitting?"],
    sampleRecommendations: ["Decision Fatigue workshop before full course."],
  }),
  member({
    id: "technology-advisor",
    name: "Technology Advisor",
    role: "Technology",
    expertise: ["Architecture", "Integration cost", "Maintainability"],
    decisionStyle: "Compose don't duplicate; intelligence-ready hooks.",
    primaryConcerns: ["Fragmented services", "UI leakage into intelligence"],
    strengths: ["Mission composer patterns", "Sample-first bridges"],
    typicalQuestions: ["Does this belong in SPARK or Founder?"],
    sampleRecommendations: ["Extend mission composer — no new dashboard."],
  }),
  member({
    id: "ai-advisor",
    name: "AI Advisor",
    role: "AI & Companion Integrity",
    expertise: ["Human voice", "Trust boundaries", "Invisible intelligence"],
    decisionStyle: "Relationship over impressiveness; observation mode discipline.",
    primaryConcerns: ["Generic AI drift", "Fabricated certainty"],
    strengths: ["Shari test", "Rule of Three for prompt changes"],
    typicalQuestions: ["Would Shari say this on the porch?"],
    sampleRecommendations: ["Voice capture only with explicit trust design."],
  }),
  member({
    id: "operations",
    name: "Operations",
    role: "Operations",
    expertise: ["Team capacity", "Approvals", "Delivery rhythm"],
    decisionStyle: "Surfaces blockers; protects Izna's focus.",
    primaryConcerns: ["Approval queues", "SOP gaps", "Scope creep"],
    strengths: ["One clear deliverable per assignee"],
    typicalQuestions: ["What blocks shipping this week?"],
    sampleRecommendations: ["Mission templates reduce repeated assembly work."],
  }),
  member({
    id: "finance",
    name: "Finance",
    role: "Finance",
    expertise: ["Unit economics", "Runway", "ROI framing"],
    decisionStyle: "Patient capital; rejects vanity metrics.",
    primaryConcerns: ["Revenue timing", "Build cost vs member LTV"],
    strengths: ["Sizing opportunities without pressure language"],
    typicalQuestions: ["When does revenue follow trust — not precede it?"],
    sampleRecommendations: ["Gentle Restart nurture after estate proof."],
  }),
  member({
    id: "community-builder",
    name: "Community Builder",
    role: "Community",
    expertise: ["Belonging", "Guilds", "Member stories"],
    decisionStyle: "Relationship density over member count.",
    primaryConcerns: ["Isolation", "Performative engagement"],
    strengths: ["Quiet celebration", "Listening as community act"],
    typicalQuestions: ["Does this make members feel less alone?"],
    sampleRecommendations: ["Listening Rooms as shared ritual, not content feed."],
  }),
  member({
    id: "creative-director",
    name: "Creative Director",
    role: "Creative",
    expertise: ["Estate aesthetic", "PostCraft tone", "Visual calm"],
    decisionStyle: "Photograph test; rejects busy UI.",
    primaryConcerns: ["Gamification", "Software chrome on glass"],
    strengths: ["Estate as hero", "Frosted conversation discipline"],
    typicalQuestions: ["Could this frame hang on a wall?"],
    sampleRecommendations: ["One scene, one feeling — then expand."],
  }),
  member({
    id: "research-analyst",
    name: "Research Analyst",
    role: "Research",
    expertise: ["Trend synthesis", "Evidence quality", "Competitive context"],
    decisionStyle: "Separates signal from anecdote; cites sources.",
    primaryConcerns: ["Single-conversation overfitting"],
    strengths: ["ADHD entrepreneur trend reports", "SPARK pattern validation"],
    typicalQuestions: ["How many independent signals support this?"],
    sampleRecommendations: ["Rule of Three before architecture changes."],
  }),
  member({
    id: "accessibility-expert",
    name: "Accessibility Expert",
    role: "Accessibility & Inclusion",
    expertise: ["EF access", "Voice", "Readable calm UI", "Reduced motion"],
    decisionStyle: "Inclusive by default; tests edge energy states.",
    primaryConcerns: ["Thin fonts on glass", "Motion without opt-out"],
    strengths: ["Voice as accessibility, not gimmick"],
    typicalQuestions: ["Who is excluded if we ship only the happy path?"],
    sampleRecommendations: ["Large type, calm motion, voice optional."],
  }),
];

const MEMBER_BY_ID = new Map(ADVISORY_BOARD_MEMBERS.map((m) => [m.id, m]));

export function getBoardMemberDefinition(id: AdvisoryMemberId): AdvisoryMember | undefined {
  return MEMBER_BY_ID.get(id);
}

export function listBoardMemberDefinitions(): AdvisoryMember[] {
  return [...ADVISORY_BOARD_MEMBERS];
}
