/**
 * Real ADHD Business Scenario Library — expanded validation transcripts.
 */

import type { ValidationScenario } from "./companionValidationFramework";
import { SALES_SCORECARD_THRESHOLDS } from "./companionSalesIntelligence";
import { VISIBILITY_SCORECARD_THRESHOLDS } from "./companionVisibilityIntelligence";
import { MONEY_SCORECARD_THRESHOLDS } from "./companionMoneyIntelligence";
import { DELEGATION_SCORECARD_THRESHOLDS } from "./companionDelegationIntelligence";
import { LAUNCH_SCORECARD_THRESHOLDS } from "./companionLaunchIntelligence";

const SCENARIO_THRESHOLDS = {
  understanding: 75,
  trust: 75,
  confidence: 70,
  momentum: 70,
  action: 80,
  routing: 70,
  overanalysis: 80,
  adhdAlignment: 80,
} as const;

/** Original 5 foundation scenarios (updated with categories + thresholds). */
export const FOUNDATION_SCENARIOS: ValidationScenario[] = [
  {
    id: "launch-avoidance",
    label: "Launch Avoidance",
    category: "surface_vs_actual",
    description:
      'User says "I just need to tweak my website first" — detect avoidance, move toward launch.',
    turns: [
      { role: "user", content: "I need to launch my coaching offer this week" },
      { role: "assistant", content: "What's the first launch step?" },
      { role: "user", content: "Post the sales page and open enrollment" },
      { role: "assistant", content: "What is blocking that?" },
      { role: "user", content: "I just need to tweak my website first" },
    ],
    lastUserMessage: "I just need to tweak my website first",
    emotionalState: "stuck",
    expectedSurfaceIntent: /tweak.*website/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "launch_move",
      multiTurnPattern: null,
      momentumActive: false,
      shouldDeferRouting: false,
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["ignores_surface_actual_gap", "too_many_questions"],
    },
  },
  {
    id: "planning-addiction-loop",
    label: "Planning Addiction",
    category: "operations_systems",
    description:
      "User spends many turns creating systems — detect loop, stop planning, move to execution.",
    turns: [
      { role: "user", content: "I need to launch my newsletter" },
      { role: "assistant", content: "What's the first piece?" },
      { role: "user", content: "Maybe I should outline it better first" },
      { role: "assistant", content: "What would the outline include?" },
      { role: "user", content: "I need a system for organizing the sections" },
      { role: "assistant", content: "Tell me more." },
      { role: "user", content: "Let me make a checklist before I start writing" },
      { role: "assistant", content: "What goes on the checklist?" },
      { role: "user", content: "I should map out the content calendar too" },
      { role: "assistant", content: "What cadence?" },
      { role: "user", content: "Maybe I need a better folder structure first" },
      { role: "assistant", content: "How would you organize it?" },
      { role: "user", content: "I could build a Notion template before sending issue one" },
      { role: "assistant", content: "What sections?" },
      { role: "user", content: "I need to plan the welcome sequence too" },
      { role: "assistant", content: "What emails?" },
      { role: "user", content: "Let me outline the first three issues before I write anything" },
      { role: "assistant", content: "What topics?" },
      { role: "user", content: "I should organize my research links first" },
      { role: "assistant", content: "Where are they now?" },
      { role: "user", content: "Maybe one more checklist and then I'll start" },
    ],
    lastUserMessage: "Maybe one more checklist and then I'll start",
    emotionalState: "stuck",
    expectedSurfaceIntent: /checklist/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      multiTurnPattern: "planning_addiction",
      shouldDeferRouting: true,
      shouldSuppressDiscovery: true,
      maxAssistantQuestions: 10,
      recommendedEnd: "decision",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["too_many_questions", "adds_overwhelm"],
    },
  },
  {
    id: "shiny-object-syndrome",
    label: "Shiny Object Syndrome",
    category: "decisions",
    description:
      "User changes direction 4 times — notice drift, reconnect to original goal.",
    turns: [
      { role: "user", content: "I'm trying to grow my coaching business" },
      { role: "assistant", content: "What's the focus?" },
      { role: "user", content: "Or maybe a membership instead" },
      { role: "assistant", content: "What draws you?" },
      { role: "user", content: "What about a workshop series too?" },
      { role: "assistant", content: "Lots of directions." },
      { role: "user", content: "Actually maybe I should launch a podcast" },
      { role: "assistant", content: "Interesting." },
      { role: "user", content: "Can you give me more options to consider?" },
    ],
    lastUserMessage: "Can you give me more options to consider?",
    emotionalState: "unclear",
    expectedSurfaceIntent: /more options/i,
    expectations: {
      intuitiveSignal: "drift",
      actualNeed: "reconnect_goal",
      multiTurnPattern: "idea_explosion",
      shouldDeferRouting: true,
      recommendedEnd: "decision",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["adds_overwhelm", "generic_advice"],
    },
  },
  {
    id: "overwhelm-competing-tasks",
    label: "Overwhelm",
    category: "energy_recovery",
    description:
      "User has many competing tasks — reduce complexity, do not add options.",
    turns: [
      { role: "user", content: "I have 40 things on my list and can't focus" },
      { role: "assistant", content: "That's a lot." },
      { role: "user", content: "Client work, content, admin, launch prep, emails, taxes" },
      { role: "assistant", content: "What feels most urgent?" },
      { role: "user", content: "Everything feels scattered and my head is full" },
      { role: "assistant", content: "Too much at once." },
      { role: "user", content: "So many things and I can't keep up with all of it" },
    ],
    lastUserMessage: "So many things and I can't keep up with all of it",
    emotionalState: "overwhelmed",
    expectedSurfaceIntent: /keep up/i,
    expectations: {
      actualNeed: "reduce_complexity",
      multiTurnPattern: "overwhelm_from_volume",
      shouldDeferRouting: true,
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["adds_overwhelm"],
    },
  },
  {
    id: "momentum-creating",
    label: "Momentum",
    category: "energy_recovery",
    description:
      "User is actively creating — avoid interruption, protect flow.",
    turns: [
      { role: "user", content: "I'm writing the sales page draft" },
      { role: "assistant", content: "Nice — keep going." },
      { role: "user", content: "I'm on a roll and just finished the first section" },
      { role: "assistant", content: "What's next?" },
      { role: "user", content: "Don't interrupt — I'm in the flow and making progress" },
    ],
    lastUserMessage: "Don't interrupt — I'm in the flow and making progress",
    emotionalState: "focused",
    expectedSurfaceIntent: /flow/i,
    expectations: {
      intuitiveSignal: "momentum",
      actualNeed: "protect_flow",
      multiTurnPattern: null,
      momentumActive: true,
      shouldDeferRouting: true,
      recommendedEnd: "continue_execution",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["routes_too_early", "too_many_questions"],
    },
  },
];

/** 19 expanded scenarios across ADHD business categories. */
export const EXPANDED_SCENARIOS: ValidationScenario[] = [
  {
    id: "revenue-pricing-paralysis",
    label: "Pricing Paralysis",
    category: "revenue_sales",
    description:
      "User keeps saying they need to think about pricing more — confidence and decision, not endless frameworks.",
    turns: [
      { role: "user", content: "I need to price my coaching package" },
      { role: "assistant", content: "What feels hard?" },
      { role: "user", content: "I don't think my offer is ready to price yet" },
      { role: "assistant", content: "What would ready mean?" },
      { role: "user", content: "I still need to think about pricing more before I decide" },
    ],
    lastUserMessage: "I still need to think about pricing more before I decide",
    emotionalState: "stuck",
    expectedSurfaceIntent: /think about pricing/i,
    expectations: {
      intuitiveSignal: "hesitation",
      actualNeed: "make_decision",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["generic_advice", "too_many_questions"],
    },
  },
  {
    id: "revenue-lead-follow-up",
    label: "Lead Follow-Up Avoidance",
    category: "revenue_sales",
    description:
      "User has leads but delays follow-up — avoidance, not a sales strategy lecture.",
    turns: [
      { role: "user", content: "I have three warm leads from last week" },
      { role: "assistant", content: "What's next with them?" },
      { role: "user", content: "I keep putting off sending the follow-up email" },
      { role: "assistant", content: "What makes it hard?" },
      { role: "user", content: "I don't want to seem pushy so I've been delaying it" },
    ],
    lastUserMessage: "I don't want to seem pushy so I've been delaying it",
    emotionalState: "stuck",
    expectedSurfaceIntent: /delaying/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "revenue-fear-of-selling",
    label: "Fear of Selling",
    category: "revenue_sales",
    description:
      "User wants clients but avoids outreach — name discomfort, one low-pressure action.",
    turns: [
      { role: "user", content: "I really need more clients this month" },
      { role: "assistant", content: "What's one way to reach people?" },
      { role: "user", content: "I know I should do outreach but I'm scared to reach out" },
      { role: "assistant", content: "What feels scary?" },
      { role: "user", content: "Afraid they'll think I'm annoying if I message them" },
    ],
    lastUserMessage: "Afraid they'll think I'm annoying if I message them",
    emotionalState: "emotional",
    expectedSurfaceIntent: /annoying/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["generic_advice", "unfiltered_traditional_advice"],
    },
  },
  {
    id: "content-paralysis",
    label: "Content Paralysis",
    category: "content_marketing",
    description:
      "User keeps rewriting instead of posting — perfectionism, publish good enough.",
    turns: [
      { role: "user", content: "I want to post about my offer today" },
      { role: "assistant", content: "What's stopping you?" },
      { role: "user", content: "It's not ready yet" },
      { role: "assistant", content: "What would ready look like?" },
      { role: "user", content: "I've rewritten it four times and still don't want it to sound wrong" },
    ],
    lastUserMessage: "I've rewritten it four times and still don't want it to sound wrong",
    emotionalState: "stuck",
    expectedSurfaceIntent: /rewritten/i,
    expectations: {
      actualNeed: "start_execution",
      multiTurnPattern: "perfectionism_as_preparation",
      shouldDeferRouting: true,
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["too_many_questions"],
    },
  },
  {
    id: "content-too-many-ideas",
    label: "Too Many Content Ideas",
    category: "content_marketing",
    description:
      "User has many post ideas and asks for more — prioritize, don't ideate.",
    turns: [
      { role: "user", content: "I have ten post ideas and can't pick one" },
      { role: "assistant", content: "Which pulls you most?" },
      { role: "user", content: "Or maybe a carousel, or a video, or a thread" },
      { role: "assistant", content: "Lots of formats." },
      { role: "user", content: "Can you give me more content ideas to choose from?" },
    ],
    lastUserMessage: "Can you give me more content ideas to choose from?",
    emotionalState: "unclear",
    expectedSurfaceIntent: /more content ideas/i,
    expectations: {
      intuitiveSignal: "drift",
      actualNeed: "reconnect_goal",
      multiTurnPattern: "idea_explosion",
      shouldDeferRouting: true,
      recommendedEnd: "decision",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["adds_overwhelm"],
    },
  },
  {
    id: "content-marketing-offer-confusion",
    label: "Marketing Problem That Is Really Offer Confusion",
    category: "content_marketing",
    description:
      "User asks for marketing help — unclear offer is the real blocker.",
    turns: [
      { role: "user", content: "I need marketing help for my business" },
      { role: "assistant", content: "What are you selling?" },
      { role: "user", content: "I'm not totally sure who it's for yet" },
      { role: "assistant", content: "Tell me more." },
      { role: "user", content: "I need a marketing strategy but I can't explain my offer clearly" },
    ],
    lastUserMessage: "I need a marketing strategy but I can't explain my offer clearly",
    emotionalState: "unclear",
    expectedSurfaceIntent: /marketing strategy/i,
    expectations: {
      intuitiveSignal: "hesitation",
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["generic_advice", "ignores_surface_actual_gap"],
    },
  },
  {
    id: "ops-tool-hopping",
    label: "Tool Hopping",
    category: "operations_systems",
    description:
      "User wants another app — execution friction, use existing system first.",
    turns: [
      { role: "user", content: "My project tasks are in Asana" },
      { role: "assistant", content: "What's not working?" },
      { role: "user", content: "Maybe I need a better tool for this" },
      { role: "assistant", content: "What would it solve?" },
      { role: "user", content: "Is there an app that would organize this better? I want to try Notion instead" },
    ],
    lastUserMessage: "Is there an app that would organize this better? I want to try Notion instead",
    emotionalState: "stuck",
    expectedSurfaceIntent: /Notion/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "ops-rebuilding-systems",
    label: "Rebuilding Systems Instead Of Using Them",
    category: "operations_systems",
    description:
      "User keeps redesigning workflows — stop redesign, move to execution.",
    turns: [
      { role: "user", content: "I need to send client onboarding emails" },
      { role: "assistant", content: "What's blocking that?" },
      { role: "user", content: "I should redo my onboarding workflow first" },
      { role: "assistant", content: "What's wrong with it?" },
      { role: "user", content: "Let me map out a better system before I email anyone" },
    ],
    lastUserMessage: "Let me map out a better system before I email anyone",
    emotionalState: "stuck",
    expectedSurfaceIntent: /map out.*system/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["too_many_questions"],
    },
  },
  {
    id: "client-difficult-conversation",
    label: "Difficult Client Conversation Avoidance",
    category: "client_work",
    description:
      "User delays responding to a client — help one clear response, not relationship overanalysis.",
    turns: [
      { role: "user", content: "A client sent a frustrated message yesterday" },
      { role: "assistant", content: "Have you replied?" },
      { role: "user", content: "I've been putting off responding because I dread opening it" },
      { role: "assistant", content: "What's the worry?" },
      { role: "user", content: "Hard to face it — I keep avoiding the reply" },
    ],
    lastUserMessage: "Hard to face it — I keep avoiding the reply",
    emotionalState: "emotional",
    expectedSurfaceIntent: /avoiding the reply/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["too_many_questions", "generic_advice"],
    },
  },
  {
    id: "client-scope-creep",
    label: "Scope Creep / Saying Yes Too Much",
    category: "client_work",
    description:
      "User overwhelmed by client demands — boundaries, one draft response.",
    turns: [
      { role: "user", content: "My client keeps adding requests outside our agreement" },
      { role: "assistant", content: "How much has piled up?" },
      { role: "user", content: "Too much — I said yes to everything and now I'm drowning" },
      { role: "assistant", content: "That's heavy." },
      { role: "user", content: "So many extra asks and I can't keep up with all of it" },
    ],
    lastUserMessage: "So many extra asks and I can't keep up with all of it",
    emotionalState: "overwhelmed",
    expectedSurfaceIntent: /keep up/i,
    expectations: {
      actualNeed: "reduce_complexity",
      multiTurnPattern: "overwhelm_from_volume",
      shouldDeferRouting: true,
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["adds_overwhelm"],
    },
  },
  {
    id: "energy-burnout-spiral",
    label: "Burnout Spiral",
    category: "energy_recovery",
    description:
      "User feels behind, tired, ashamed — tiny stabilizing step, not a big plan.",
    turns: [
      { role: "user", content: "I'm so tired and behind on everything" },
      { role: "assistant", content: "That's a lot." },
      { role: "user", content: "I feel ashamed I didn't get more done this week" },
      { role: "assistant", content: "Heavy week." },
      { role: "user", content: "I'm burned out and everything feels like too much" },
    ],
    lastUserMessage: "I'm burned out and everything feels like too much",
    emotionalState: "emotional",
    expectedSurfaceIntent: /burned out/i,
    expectations: {
      actualNeed: "reduce_complexity",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["adds_overwhelm", "generic_advice"],
    },
  },
  {
    id: "energy-monday-start",
    label: "Monday Start Problem",
    category: "energy_recovery",
    description:
      "User cannot start the week — gentle first action, not full weekly plan.",
    turns: [
      { role: "user", content: "It's Monday and I can't make myself start" },
      { role: "assistant", content: "What's on your mind?" },
      { role: "user", content: "So much to do and I don't know where to begin" },
      { role: "assistant", content: "Overwhelming start." },
      { role: "user", content: "I probably should plan the whole week but I can't start" },
    ],
    lastUserMessage: "I probably should plan the whole week but I can't start",
    emotionalState: "stuck",
    expectedSurfaceIntent: /plan the whole week/i,
    expectations: {
      intuitiveSignal: "hesitation",
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["adds_overwhelm"],
    },
  },
  {
    id: "energy-hyperfocus-crash",
    label: "Hyperfocus Crash",
    category: "energy_recovery",
    description:
      "User was on a roll then stopped — re-entry without shame.",
    turns: [
      { role: "user", content: "I was on a roll writing yesterday" },
      { role: "assistant", content: "Nice progress." },
      { role: "user", content: "Then I crashed and didn't touch it today" },
      { role: "assistant", content: "That happens." },
      { role: "user", content: "I feel bad I stopped — hard to get back into it" },
    ],
    lastUserMessage: "I feel bad I stopped — hard to get back into it",
    emotionalState: "emotional",
    expectedSurfaceIntent: /get back into/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["resets_after_agreement"],
    },
  },
  {
    id: "decision-offer-a-vs-b",
    label: "Offer A vs Offer B",
    category: "decisions",
    description:
      "User keeps comparing options — decision acceleration, not endless research.",
    turns: [
      { role: "user", content: "I can't decide between Offer A and Offer B" },
      { role: "assistant", content: "What matters most?" },
      { role: "user", content: "Offer A is faster revenue but Offer B fits my values better" },
      { role: "assistant", content: "Both have tradeoffs." },
      { role: "user", content: "I still can't decide — should I keep researching?" },
    ],
    lastUserMessage: "I still can't decide — should I keep researching?",
    emotionalState: "unclear",
    expectedSurfaceIntent: /decide/i,
    expectations: {
      actualNeed: "make_decision",
      recommendedEnd: "decision",
      shouldSuppressDiscovery: true,
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["too_many_questions"],
    },
  },
  {
    id: "decision-niche-pivot",
    label: "Niche Pivot Anxiety",
    category: "decisions",
    description:
      "User wants to change niche again — reconnect to goal, no encouragement to pivot.",
    turns: [
      { role: "user", content: "I'm building a business for overwhelmed founders" },
      { role: "assistant", content: "What's the focus?" },
      { role: "user", content: "Or maybe I should target coaches instead" },
      { role: "assistant", content: "What draws you?" },
      { role: "user", content: "Actually maybe I should pivot to a completely different niche" },
    ],
    lastUserMessage: "Actually maybe I should pivot to a completely different niche",
    emotionalState: "unclear",
    expectedSurfaceIntent: /pivot/i,
    expectations: {
      intuitiveSignal: "drift",
      actualNeed: "reconnect_goal",
      multiTurnPattern: "idea_explosion",
      shouldDeferRouting: true,
      recommendedEnd: "decision",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["adds_overwhelm"],
    },
  },
  {
    id: "followthrough-yes-then-disappears",
    label: "User Says Yes Then Disappears",
    category: "follow_through",
    description:
      "User agreed to a plan, returns days later — resume thread, no reset, no scolding.",
    turns: [
      { role: "user", content: "I need to send my proposal by Friday" },
      { role: "assistant", content: "Want to draft the first section together?" },
      { role: "user", content: "Yes, let's do it" },
      { role: "assistant", content: "Great — what's the first line?" },
      { role: "user", content: "Hey I'm back — sorry I disappeared for a few days" },
    ],
    lastUserMessage: "Hey I'm back — sorry I disappeared for a few days",
    emotionalState: "unclear",
    expectedSurfaceIntent: /back/i,
    expectations: {
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["resets_after_agreement"],
    },
  },
  {
    id: "followthrough-repeated-goal",
    label: "Repeating Same Goal For Weeks",
    category: "follow_through",
    description:
      "User keeps returning to same unfinished goal — detect loop, smallest action.",
    turns: [
      { role: "user", content: "I still need to launch my workshop" },
      { role: "assistant", content: "What's blocking it?" },
      { role: "user", content: "Same goal as last time — I haven't started" },
      { role: "assistant", content: "What's the smallest step?" },
      { role: "user", content: "I keep saying I'll launch my workshop but never do" },
    ],
    lastUserMessage: "I keep saying I'll launch my workshop but never do",
    emotionalState: "stuck",
    expectedSurfaceIntent: /launch my workshop/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "launch_move",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["misses_adhd_friction"],
    },
  },
  {
    id: "surface-website-redesign",
    label: "Website Request Is Really Launch Avoidance",
    category: "surface_vs_actual",
    description:
      "User wants to redesign website before launch — check if truly blocking, move toward launch.",
    turns: [
      { role: "user", content: "I want to launch my course next month" },
      { role: "assistant", content: "What's the first step?" },
      { role: "user", content: "Open enrollment and start selling" },
      { role: "assistant", content: "What's in the way?" },
      { role: "user", content: "I need to redesign my website before I can launch" },
    ],
    lastUserMessage: "I need to redesign my website before I can launch",
    emotionalState: "stuck",
    expectedSurfaceIntent: /redesign.*website/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "launch_move",
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["ignores_surface_actual_gap"],
    },
  },
  {
    id: "surface-course-collecting",
    label: "Course Collecting",
    category: "surface_vs_actual",
    description:
      "User wants another course — preparation loop, use what they already know.",
    turns: [
      { role: "user", content: "I want to start my consulting business" },
      { role: "assistant", content: "What's first?" },
      { role: "user", content: "I should research more examples first" },
      { role: "assistant", content: "What are you looking for?" },
      { role: "user", content: "Maybe I need another course before I feel ready to start" },
    ],
    lastUserMessage: "Maybe I need another course before I feel ready to start",
    emotionalState: "stuck",
    expectedSurfaceIntent: /another course/i,
    expectations: {
      intuitiveSignal: "hesitation",
      actualNeed: "start_execution",
      multiTurnPattern: "perfectionism_as_preparation",
      shouldDeferRouting: true,
      recommendedEnd: "next_step",
      minScorecard: { ...SCENARIO_THRESHOLDS },
      failureConditions: ["generic_advice"],
    },
  },
];

const S = SALES_SCORECARD_THRESHOLDS;

/** Sales Conversations — ADHD Entrepreneur Behavioral Framework™ */
export const SALES_SCENARIOS: ValidationScenario[] = [
  {
    id: "sales-discovery-call-avoidance",
    label: "Discovery Call Avoidance",
    category: "sales_conversations",
    salesStage: "discovery_preparation",
    description:
      "User keeps putting off the call — fear of rejection, not a sales strategy lecture.",
    turns: [
      { role: "user", content: "I have prospects I should be calling" },
      { role: "assistant", content: "What's stopping you?" },
      { role: "user", content: "I know I should make the call but I keep putting it off" },
    ],
    lastUserMessage: "I know I should make the call but I keep putting it off",
    emotionalState: "stuck",
    expectedSurfaceIntent: /make the call/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...S },
      failureConditions: ["generic_advice", "too_many_questions", "unfiltered_traditional_advice"],
    },
  },
  {
    id: "sales-discovery-call-preparation",
    label: "Discovery Call Preparation",
    category: "sales_conversations",
    salesStage: "discovery_preparation",
    description:
      "User has a discovery call tomorrow — light prep, not a giant script.",
    turns: [
      { role: "user", content: "I have a discovery call tomorrow" },
      { role: "assistant", content: "What do you want from it?" },
      { role: "user", content: "I want to feel ready but not overprepare" },
    ],
    lastUserMessage: "I want to feel ready but not overprepare",
    emotionalState: "unclear",
    expectedSurfaceIntent: /ready/i,
    expectations: {
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...S },
      failureConditions: ["adds_overwhelm", "generic_advice"],
    },
  },
  {
    id: "sales-discovery-overexplaining",
    label: "Discovery Call Overexplaining",
    category: "sales_conversations",
    salesStage: "discovery_execution",
    description: "User talks the whole time — shift to listening and curiosity.",
    turns: [
      { role: "user", content: "My discovery calls feel like lectures" },
      { role: "assistant", content: "What happens?" },
      { role: "user", content: "I end up talking the whole time instead of listening" },
    ],
    lastUserMessage: "I end up talking the whole time instead of listening",
    emotionalState: "stuck",
    expectedSurfaceIntent: /talking the whole time/i,
    expectations: {
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...S },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "sales-pricing-freeze",
    label: "Pricing Freeze",
    category: "sales_conversations",
    salesStage: "confidence_recovery",
    description: "User froze when asked price — confidence and value clarity.",
    turns: [
      { role: "user", content: "I was on a sales call today" },
      { role: "assistant", content: "How did it go?" },
      { role: "user", content: "They asked my price and I froze" },
    ],
    lastUserMessage: "They asked my price and I froze",
    emotionalState: "emotional",
    expectedSurfaceIntent: /froze/i,
    expectations: {
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...S },
      failureConditions: ["generic_advice", "unfiltered_traditional_advice"],
    },
  },
  {
    id: "sales-objection-too-expensive",
    label: "Objection: Too Expensive",
    category: "sales_conversations",
    salesStage: "objection_handling",
    description: "Prospect said too expensive — one practical next response.",
    turns: [
      { role: "user", content: "I sent a proposal after our discovery call" },
      { role: "assistant", content: "Any response?" },
      { role: "user", content: "They said it's too expensive" },
    ],
    lastUserMessage: "They said it's too expensive",
    emotionalState: "stuck",
    expectedSurfaceIntent: /too expensive/i,
    expectations: {
      actualNeed: "make_decision",
      recommendedEnd: "decision",
      minScorecard: { ...S },
      failureConditions: ["generic_advice", "unfiltered_traditional_advice"],
    },
  },
  {
    id: "sales-objection-need-to-think",
    label: "Objection: Need To Think About It",
    category: "sales_conversations",
    salesStage: "objection_handling",
    description: "Prospect wants to think — follow-up plan, no pressure tactics.",
    turns: [
      { role: "user", content: "The discovery call went okay" },
      { role: "assistant", content: "What's next?" },
      { role: "user", content: "They want to think about it" },
    ],
    lastUserMessage: "They want to think about it",
    emotionalState: "unclear",
    expectedSurfaceIntent: /think about it/i,
    expectations: {
      actualNeed: "make_decision",
      recommendedEnd: "decision",
      minScorecard: { ...S },
      failureConditions: ["unfiltered_traditional_advice"],
    },
  },
  {
    id: "sales-objection-talk-to-spouse",
    label: "Objection: Need To Talk To Spouse",
    category: "sales_conversations",
    salesStage: "objection_handling",
    description: "Prospect needs spouse buy-in — clarify info and follow-up.",
    turns: [
      { role: "user", content: "Good call but no commitment yet" },
      { role: "assistant", content: "What did they say?" },
      { role: "user", content: "They need to talk to their spouse first" },
    ],
    lastUserMessage: "They need to talk to their spouse first",
    emotionalState: "unclear",
    expectedSurfaceIntent: /spouse/i,
    expectations: {
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...S },
      failureConditions: ["too_many_questions"],
    },
  },
  {
    id: "sales-no-call-to-action",
    label: "No Call To Action",
    category: "sales_conversations",
    salesStage: "call_to_action",
    description: "Call went great but no next step — closing support.",
    turns: [
      { role: "user", content: "I just got off a discovery call" },
      { role: "assistant", content: "How was it?" },
      { role: "user", content: "The call went great but I didn't ask for a next step" },
    ],
    lastUserMessage: "The call went great but I didn't ask for a next step",
    emotionalState: "unclear",
    expectedSurfaceIntent: /call went great/i,
    expectations: {
      actualNeed: "make_decision",
      recommendedEnd: "decision",
      minScorecard: { ...S },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "sales-follow-up-avoidance",
    label: "Sales Follow-Up Avoidance",
    category: "sales_conversations",
    salesStage: "follow_up",
    description: "Interested prospect, no follow-up — one simple message.",
    turns: [
      { role: "user", content: "Had a great discovery call last week" },
      { role: "assistant", content: "Did you follow up?" },
      { role: "user", content: "They seemed interested but I never followed up" },
    ],
    lastUserMessage: "They seemed interested but I never followed up",
    emotionalState: "stuck",
    expectedSurfaceIntent: /never followed up/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...S },
      failureConditions: ["generic_advice", "unfiltered_traditional_advice"],
    },
  },
  {
    id: "sales-undercharging",
    label: "Undercharging",
    category: "sales_conversations",
    salesStage: "confidence_recovery",
    description: "User quoted below desired price — confidence without shame.",
    turns: [
      { role: "user", content: "I quoted on a call today" },
      { role: "assistant", content: "How do you feel about it?" },
      { role: "user", content: "I quoted less than I wanted to" },
    ],
    lastUserMessage: "I quoted less than I wanted to",
    emotionalState: "emotional",
    expectedSurfaceIntent: /quoted less/i,
    expectations: {
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...S },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "sales-post-call-shame",
    label: "Post-Call Shame Spiral",
    category: "sales_conversations",
    salesStage: "confidence_recovery",
    description: "User thinks they messed up — recover confidence, no shame loop.",
    turns: [
      { role: "user", content: "I just finished a sales call" },
      { role: "assistant", content: "How do you think it went?" },
      { role: "user", content: "I messed up the call" },
    ],
    lastUserMessage: "I messed up the call",
    emotionalState: "emotional",
    expectedSurfaceIntent: /messed up/i,
    expectations: {
      intuitiveSignal: "discouragement",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...S },
      failureConditions: ["generic_advice"],
    },
  },
];

const V = VISIBILITY_SCORECARD_THRESHOLDS;

/** Visibility & Marketing Confidence — ADHD Entrepreneur Behavioral Framework™ */
export const VISIBILITY_SCENARIOS: ValidationScenario[] = [
  {
    id: "visibility-video-avoidance",
    label: "Video Avoidance",
    category: "visibility_marketing",
    description:
      "User keeps putting off videos — visibility fear and perfectionism, not a content strategy lecture.",
    turns: [
      { role: "user", content: "I know I should be marketing more" },
      { role: "assistant", content: "What format feels most useful?" },
      { role: "user", content: "I know I should make videos but I keep putting it off" },
    ],
    lastUserMessage: "I know I should make videos but I keep putting it off",
    emotionalState: "stuck",
    expectedSurfaceIntent: /make videos/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["unfiltered_traditional_advice", "too_many_questions"],
    },
  },
  {
    id: "visibility-camera-perfectionism",
    label: "Camera Perfectionism",
    category: "visibility_marketing",
    description:
      "User re-recorded many times — define good enough to publish, not endless improvement.",
    turns: [
      { role: "user", content: "I'm trying to post a video this week" },
      { role: "assistant", content: "How's recording going?" },
      { role: "user", content: "I recorded it 17 times and still don't like it" },
    ],
    lastUserMessage: "I recorded it 17 times and still don't like it",
    emotionalState: "stuck",
    expectedSurfaceIntent: /recorded it/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "visibility-posting-obsession",
    label: "Posting Then Obsessing",
    category: "visibility_marketing",
    description:
      "User checks likes and comments — validation seeking, reconnect to purpose.",
    turns: [
      { role: "user", content: "I finally posted yesterday" },
      { role: "assistant", content: "How did it feel?" },
      { role: "user", content: "I keep checking likes and comments" },
    ],
    lastUserMessage: "I keep checking likes and comments",
    emotionalState: "emotional",
    expectedSurfaceIntent: /checking likes/i,
    expectations: {
      intuitiveSignal: "hesitation",
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "visibility-inconsistent-posting",
    label: "Inconsistent Posting",
    category: "visibility_marketing",
    description:
      "User posts then disappears — sustainability rhythm, not aggressive content calendar.",
    turns: [
      { role: "user", content: "I want to be more visible online" },
      { role: "assistant", content: "What have you tried?" },
      { role: "user", content: "I post for a few days then disappear" },
    ],
    lastUserMessage: "I post for a few days then disappear",
    emotionalState: "stuck",
    expectedSurfaceIntent: /post for a few days/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["unfiltered_traditional_advice"],
    },
  },
  {
    id: "visibility-fear-negative-comments",
    label: "Fear Of Negative Comments",
    category: "visibility_marketing",
    description:
      "User fears disagreement — rejection sensitivity, normalize discomfort without excessive reassurance.",
    turns: [
      { role: "user", content: "I want to share my opinion more" },
      { role: "assistant", content: "What's holding you back?" },
      { role: "user", content: "What if people disagree with me?" },
    ],
    lastUserMessage: "What if people disagree with me?",
    emotionalState: "emotional",
    expectedSurfaceIntent: /disagree/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "visibility-webinar-fear",
    label: "Webinar Visibility Fear",
    category: "visibility_marketing",
    description:
      "User fears empty room — move toward promotion and delivery, not endless planning.",
    turns: [
      { role: "user", content: "I want to teach a webinar on my topic" },
      { role: "assistant", content: "What's the next step?" },
      { role: "user", content: "I want to teach a webinar but nobody will show up" },
    ],
    lastUserMessage: "I want to teach a webinar but nobody will show up",
    emotionalState: "stuck",
    expectedSurfaceIntent: /webinar/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["too_many_questions", "unfiltered_traditional_advice"],
    },
  },
  {
    id: "visibility-public-speaking",
    label: "Public Speaking Anxiety",
    category: "visibility_marketing",
    description:
      "User terrified of speaking — confidence support, reduce overwhelm, audience impact.",
    turns: [
      { role: "user", content: "I got invited to speak at an event" },
      { role: "assistant", content: "How are you feeling about it?" },
      { role: "user", content: "I've been asked to speak but I'm terrified" },
    ],
    lastUserMessage: "I've been asked to speak but I'm terrified",
    emotionalState: "emotional",
    expectedSurfaceIntent: /speak/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "visibility-brand-first",
    label: "Better Brand First",
    category: "visibility_marketing",
    description:
      "User wants better brand before posting — launch avoidance disguised as branding.",
    turns: [
      { role: "user", content: "I need to start posting content" },
      { role: "assistant", content: "What's stopping you?" },
      { role: "user", content: "I need a better brand before I start posting" },
    ],
    lastUserMessage: "I need a better brand before I start posting",
    emotionalState: "stuck",
    expectedSurfaceIntent: /better brand/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "launch_move",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["ignores_surface_actual_gap", "unfiltered_traditional_advice"],
    },
  },
  {
    id: "visibility-content-perfectionism",
    label: "Content Perfectionism",
    category: "visibility_marketing",
    description: "Post isn't ready — define publish-ready, prevent endless editing.",
    turns: [
      { role: "user", content: "I'm working on a LinkedIn post" },
      { role: "assistant", content: "When will you publish?" },
      { role: "user", content: "This post isn't quite ready" },
    ],
    lastUserMessage: "This post isn't quite ready",
    emotionalState: "stuck",
    expectedSurfaceIntent: /isn'?t quite ready/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "visibility-disappearing-after-post",
    label: "Disappearing After Posting",
    category: "visibility_marketing",
    description:
      "User posted once and vanished — visibility hangover, gentle re-entry without shame.",
    turns: [
      { role: "user", content: "I tried posting last month" },
      { role: "assistant", content: "What happened after?" },
      { role: "user", content: "I posted once and vanished" },
    ],
    lastUserMessage: "I posted once and vanished",
    emotionalState: "emotional",
    expectedSurfaceIntent: /posted once/i,
    expectations: {
      intuitiveSignal: "discouragement",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "visibility-comparison-spiral",
    label: "Comparison Spiral",
    category: "visibility_marketing",
    description:
      "User compares to others — ground in evidence, personal progress, no motivational clichés.",
    turns: [
      { role: "user", content: "I'm trying to grow my audience" },
      { role: "assistant", content: "How's it going?" },
      { role: "user", content: "Everyone else is doing better than me" },
    ],
    lastUserMessage: "Everyone else is doing better than me",
    emotionalState: "emotional",
    expectedSurfaceIntent: /everyone else/i,
    expectations: {
      intuitiveSignal: "discouragement",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "visibility-low-engagement",
    label: "Low Engagement Discouragement",
    category: "visibility_marketing",
    description:
      "User worked hard, no response — separate effort from results, protect momentum.",
    turns: [
      { role: "user", content: "I spent hours on that post" },
      { role: "assistant", content: "How did it land?" },
      { role: "user", content: "I worked hard on this and nobody responded" },
    ],
    lastUserMessage: "I worked hard on this and nobody responded",
    emotionalState: "emotional",
    expectedSurfaceIntent: /nobody responded/i,
    expectations: {
      intuitiveSignal: "discouragement",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
];

const B = MONEY_SCORECARD_THRESHOLDS;
const D = DELEGATION_SCORECARD_THRESHOLDS;
const L = LAUNCH_SCORECARD_THRESHOLDS;

/** Money Intelligence™ — financial avoidance, pricing, revenue stress */
export const MONEY_SCENARIOS: ValidationScenario[] = [
  {
    id: "money-avoid-look-at-numbers",
    label: "Avoid Looking At Numbers",
    category: "money_intelligence",
    description:
      "User avoids revenue review — financial avoidance, one small step not a planning project.",
    turns: [
      { role: "user", content: "I should probably check how the business is doing" },
      { role: "assistant", content: "What feels hard about that?" },
      { role: "user", content: "I haven't looked at my revenue in months" },
    ],
    lastUserMessage: "I haven't looked at my revenue in months",
    emotionalState: "stuck",
    expectedSurfaceIntent: /revenue/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...B },
      failureConditions: ["unfiltered_traditional_advice", "generic_advice"],
    },
  },
  {
    id: "money-raising-prices",
    label: "Raising Prices",
    category: "money_intelligence",
    description:
      "User considers raising rates — confidence and value, not complex pricing models.",
    turns: [
      { role: "user", content: "My coaching package has been the same price for a year" },
      { role: "assistant", content: "Thinking about changing it?" },
      { role: "user", content: "I think I need to raise my rates" },
    ],
    lastUserMessage: "I think I need to raise my rates",
    emotionalState: "unclear",
    expectedSurfaceIntent: /raise my rates/i,
    expectations: {
      intuitiveSignal: "hesitation",
      actualNeed: "make_decision",
      recommendedEnd: "next_step",
      minScorecard: { ...B },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "money-pricing-guilt",
    label: "Pricing Guilt",
    category: "money_intelligence",
    description: "User feels guilty charging — worthiness and confidence, not shame.",
    turns: [
      { role: "user", content: "A client asked for my price" },
      { role: "assistant", content: "How did that feel?" },
      { role: "user", content: "I feel bad charging that much" },
    ],
    lastUserMessage: "I feel bad charging that much",
    emotionalState: "emotional",
    expectedSurfaceIntent: /charging/i,
    expectations: {
      intuitiveSignal: "hesitation",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...B },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "money-inconsistent-revenue",
    label: "Inconsistent Revenue Stress",
    category: "money_intelligence",
    description:
      "Slow month — emotional regulation and controllable actions, not identity collapse.",
    turns: [
      { role: "user", content: "I'm reviewing my business finances" },
      { role: "assistant", content: "How's it looking?" },
      { role: "user", content: "This month is terrible" },
    ],
    lastUserMessage: "This month is terrible",
    emotionalState: "emotional",
    expectedSurfaceIntent: /terrible/i,
    expectations: {
      intuitiveSignal: "discouragement",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...B },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "money-avoidance-loop",
    label: "Money Avoidance Loop",
    category: "money_intelligence",
    description: "User avoids invoices — smallest possible financial action.",
    turns: [
      { role: "user", content: "I need to get my books in order" },
      { role: "assistant", content: "What's stuck?" },
      { role: "user", content: "I keep putting off sending invoices" },
    ],
    lastUserMessage: "I keep putting off sending invoices",
    emotionalState: "stuck",
    expectedSurfaceIntent: /invoices/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...B },
      failureConditions: ["unfiltered_traditional_advice"],
    },
  },
];

/** Delegation Intelligence™ */
export const DELEGATION_SCENARIOS: ValidationScenario[] = [
  {
    id: "delegation-first-va-resistance",
    label: "First VA Resistance",
    category: "delegation_intelligence",
    description: "Explaining takes too long — control concerns, one low-risk task.",
    turns: [
      { role: "user", content: "I'm thinking about hiring a VA" },
      { role: "assistant", content: "What's holding you back?" },
      { role: "user", content: "It takes longer to explain than to do it myself" },
    ],
    lastUserMessage: "It takes longer to explain than to do it myself",
    emotionalState: "stuck",
    expectedSurfaceIntent: /longer to explain/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "make_decision",
      recommendedEnd: "next_step",
      minScorecard: { ...D },
      failureConditions: ["generic_advice", "unfiltered_traditional_advice"],
    },
  },
  {
    id: "delegation-do-it-myself",
    label: "I'll Just Do It Myself",
    category: "delegation_intelligence",
    description: "Faster to do it alone — challenge assumption, find one delegation opportunity.",
    turns: [
      { role: "user", content: "My inbox is overwhelming" },
      { role: "assistant", content: "Could anyone help?" },
      { role: "user", content: "It's faster if I do it" },
    ],
    lastUserMessage: "It's faster if I do it",
    emotionalState: "overwhelmed",
    expectedSurfaceIntent: /faster if i do/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "make_decision",
      recommendedEnd: "next_step",
      minScorecard: { ...D },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "delegation-micromanagement",
    label: "Micromanagement Pattern",
    category: "delegation_intelligence",
    description: "No one does it right — acceptable outcomes, not perfection.",
    turns: [
      { role: "user", content: "I tried delegating email triage" },
      { role: "assistant", content: "How did it go?" },
      { role: "user", content: "No one does it right" },
    ],
    lastUserMessage: "No one does it right",
    emotionalState: "emotional",
    expectedSurfaceIntent: /no one does it right/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "reduce_complexity",
      recommendedEnd: "next_step",
      minScorecard: { ...D },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "delegation-failure-recovery",
    label: "Delegation Failure Recovery",
    category: "delegation_intelligence",
    description: "Bad delegation experience — trust repair, don't abandon delegation entirely.",
    turns: [
      { role: "user", content: "I handed off social media last month" },
      { role: "assistant", content: "What happened?" },
      { role: "user", content: "I delegated and it went badly" },
    ],
    lastUserMessage: "I delegated and it went badly",
    emotionalState: "emotional",
    expectedSurfaceIntent: /went badly/i,
    expectations: {
      intuitiveSignal: "discouragement",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...D },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "delegation-team-communication",
    label: "Team Communication Avoidance",
    category: "delegation_intelligence",
    description: "Avoiding expectation conversations — draft communication, reduce resistance.",
    turns: [
      { role: "user", content: "My contractor keeps missing the mark" },
      { role: "assistant", content: "Have you clarified what you need?" },
      { role: "user", content: "I don't know how to tell them what I want" },
    ],
    lastUserMessage: "I don't know how to tell them what I want",
    emotionalState: "stuck",
    expectedSurfaceIntent: /tell them what i want/i,
    expectations: {
      intuitiveSignal: "hesitation",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...D },
      failureConditions: ["generic_advice"],
    },
  },
];

/** Launch Intelligence™ */
export const LAUNCH_SCENARIOS: ValidationScenario[] = [
  {
    id: "launch-delay-almost-ready",
    label: "Launch Delay",
    category: "launch_intelligence",
    description: "Almost ready — test if blockers are real, move toward launch.",
    turns: [
      { role: "user", content: "My course launch is this month" },
      { role: "assistant", content: "What's left?" },
      { role: "user", content: "I'm almost ready to launch but not quite" },
    ],
    lastUserMessage: "I'm almost ready to launch but not quite",
    emotionalState: "stuck",
    expectedSurfaceIntent: /almost ready/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "launch_move",
      recommendedEnd: "next_step",
      minScorecard: { ...L },
      failureConditions: ["ignores_surface_actual_gap"],
    },
  },
  {
    id: "launch-one-more-improvement",
    label: "One More Improvement",
    category: "launch_intelligence",
    description: "Just one more thing — perfectionism, define launch-ready.",
    turns: [
      { role: "user", content: "I want to open enrollment Friday" },
      { role: "assistant", content: "What's in the way?" },
      { role: "user", content: "Just one more thing before I launch" },
    ],
    lastUserMessage: "Just one more thing before I launch",
    emotionalState: "stuck",
    expectedSurfaceIntent: /one more thing/i,
    expectations: {
      intuitiveSignal: "avoidance",
      actualNeed: "launch_move",
      recommendedEnd: "next_step",
      minScorecard: { ...L },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "launch-panic-nobody-buys",
    label: "Launch Panic",
    category: "launch_intelligence",
    description: "Fear nobody buys — confidence and expectation management.",
    turns: [
      { role: "user", content: "Launch day is tomorrow" },
      { role: "assistant", content: "How are you feeling?" },
      { role: "user", content: "What if nobody buys?" },
    ],
    lastUserMessage: "What if nobody buys?",
    emotionalState: "emotional",
    expectedSurfaceIntent: /nobody buys/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...L },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "launch-post-launch-crash",
    label: "Post-Launch Crash",
    category: "launch_intelligence",
    description: "After launch confusion — protect confidence, re-entry path.",
    turns: [
      { role: "user", content: "We launched the offer yesterday" },
      { role: "assistant", content: "How did it go?" },
      { role: "user", content: "I don't know what to do now" },
    ],
    lastUserMessage: "I don't know what to do now",
    emotionalState: "unclear",
    expectedSurfaceIntent: /what to do now/i,
    expectations: {
      intuitiveSignal: "hesitation",
      actualNeed: "clarify_direction",
      recommendedEnd: "next_step",
      minScorecard: { ...L },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "launch-abandonment-reentry",
    label: "Launch Abandonment Re-Entry",
    category: "launch_intelligence",
    description: "Disappeared mid-launch — no-shame resume thread.",
    turns: [
      { role: "user", content: "I was launching my membership last week" },
      { role: "assistant", content: "Where did you leave off?" },
      { role: "user", content: "Sorry I disappeared during the launch" },
    ],
    lastUserMessage: "Sorry I disappeared during the launch",
    emotionalState: "emotional",
    expectedSurfaceIntent: /disappeared/i,
    expectations: {
      intuitiveSignal: "discouragement",
      actualNeed: "start_execution",
      recommendedEnd: "next_step",
      minScorecard: { ...L },
      failureConditions: ["generic_advice"],
    },
  },
];

/** Additional visibility scenarios — fear of being seen, imposter, hangover regret */
export const VISIBILITY_EXPANSION_SCENARIOS: ValidationScenario[] = [
  {
    id: "visibility-fear-being-seen",
    label: "Fear Of Being Seen",
    category: "visibility_marketing",
    description: "User fears being watched — reduce scope, increase safety.",
    turns: [
      { role: "user", content: "I want to go live with my offer" },
      { role: "assistant", content: "What feels risky?" },
      { role: "user", content: "I don't want people watching me" },
    ],
    lastUserMessage: "I don't want people watching me",
    emotionalState: "emotional",
    expectedSurfaceIntent: /watching me/i,
    expectations: {
      intuitiveSignal: "resistance",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "visibility-expert-imposter",
    label: "Expert Imposter Syndrome",
    category: "visibility_marketing",
    description: "Who am I to teach — reconnect to expertise, not generic motivation.",
    turns: [
      { role: "user", content: "I'm planning a workshop" },
      { role: "assistant", content: "What's the topic?" },
      { role: "user", content: "Who am I to teach this?" },
    ],
    lastUserMessage: "Who am I to teach this?",
    emotionalState: "emotional",
    expectedSurfaceIntent: /who am i to teach/i,
    expectations: {
      intuitiveSignal: "discouragement",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
  {
    id: "visibility-hangover-regret",
    label: "Visibility Hangover Regret",
    category: "visibility_marketing",
    description: "Posted and regrets it — normalize discomfort, support continued visibility.",
    turns: [
      { role: "user", content: "I finally posted yesterday" },
      { role: "assistant", content: "How do you feel today?" },
      { role: "user", content: "I posted and now I regret it" },
    ],
    lastUserMessage: "I posted and now I regret it",
    emotionalState: "emotional",
    expectedSurfaceIntent: /regret/i,
    expectations: {
      intuitiveSignal: "discouragement",
      actualNeed: "build_confidence",
      recommendedEnd: "next_step",
      minScorecard: { ...V },
      failureConditions: ["generic_advice"],
    },
  },
];

export const ALL_VALIDATION_SCENARIOS: ValidationScenario[] = [
  ...FOUNDATION_SCENARIOS,
  ...EXPANDED_SCENARIOS,
  ...SALES_SCENARIOS,
  ...VISIBILITY_SCENARIOS,
  ...VISIBILITY_EXPANSION_SCENARIOS,
  ...MONEY_SCENARIOS,
  ...DELEGATION_SCENARIOS,
  ...LAUNCH_SCENARIOS,
];
