import type { HowDoIHelpArticle } from "./howDoIHelpTypes";
import { visualThinkingToolHelpTips } from "./visualFocus/studioCards";
import {
  CHAT_WORKSPACE_NAV_MODEL,
  NEW_CHAT_INSTRUCTION,
  NEW_DAYS_CHAT_INSTRUCTION,
  TOP_NAV_COMPANION_WORKSPACES,
} from "./chatWorkspaceHelpContent";

/** Full help library — search indexes every article. */
export const HOW_DO_I_HELP_ARTICLES: HowDoIHelpArticle[] = [
  // —— Getting Started ——
  {
    id: "first-5-minutes",
    categoryId: "getting-started",
    title: "First 5 Minutes",
    emoji: "⏱️",
    whatItIs: "The fastest way to orient yourself without reading everything.",
    whenToUse: "Brand-new to the ecosystem — right after login.",
    workflow: [
      "Read the Core Workflow box at the top of How Do I.",
      `Top bar: ${TOP_NAV_COMPANION_WORKSPACES}, plus Chat Workspace (💬) for conversation context.`,
      "Open Clear My Mind (🧠) and capture what's on your mind.",
      "Open Chat and tell the Companion what you need today.",
      "Pick one main area from the cards below when you are ready.",
    ],
    tips: ["You do not need to set up everything on day one."],
    keywords: ["start", "new", "begin", "first time", "onboarding"],
    openSection: "brain-dump",
    openLabel: "Open Clear My Mind",
  },
  {
    id: "your-first-day",
    categoryId: "getting-started",
    title: "Your First Day",
    emoji: "🌅",
    whatItIs: "A gentle first-day path through capture, plan, and one small win.",
    whenToUse: "Your first real working session in the app.",
    workflow: [
      "Capture thoughts in Clear My Mind.",
      "Move one idea into a Project if it needs multiple steps.",
      "Add one task to Plan My Day.",
      "Log a win at the end — even opening the app counts.",
    ],
    tips: ["One completed step beats a perfect plan."],
    keywords: ["first day", "day one", "getting started"],
    openSection: "plan-my-day",
    openLabel: "Open Plan My Day",
  },
  {
    id: "your-first-week",
    categoryId: "getting-started",
    title: "Your First Week",
    emoji: "📆",
    whatItIs: "How the pieces connect over a few days of real use.",
    whenToUse: "After your first day — when you want the bigger picture.",
    workflow: [
      "Use Clear My Mind daily for mental clutter.",
      "Keep one active Project with a clear next action.",
      "Try Create for one business asset you actually need.",
      "Review Wins This Week on Friday — or open 🌱 Growth for wins, evidence, and highlights.",
    ],
    tips: ["The ecosystem grows with you — add tools only when they help."],
    keywords: ["first week", "week one", "onboarding"],
    openSection: "my-work",
    openLabel: "Open My Work",
  },
  {
    id: "meet-your-companion",
    categoryId: "getting-started",
    title: "Meet Your Companion",
    emoji: "💬",
    whatItIs:
      "Shari — your ADHD business companion. She helps you think, clarify, and choose your next step.",
    whenToUse: "When you want to understand who you are talking to and what to expect.",
    workflow: [
      "Open Chat and say hello in plain language.",
      "Share what is on your mind — no perfect prompt needed.",
      "Let her ask clarifying questions before any tool opens.",
      "You stay in control — nothing changes in your workspace without your yes.",
    ],
    tips: [
      "The Companion is a thinking partner, not a task bot.",
    ],
    keywords: ["companion", "shari", "chat", "meet", "who"],
    askPrompt: "I'm new — help me understand how you work as my companion.",
  },
  {
    id: "how-the-ecosystem-works",
    categoryId: "getting-started",
    title: "How The Ecosystem Works",
    emoji: "🌐",
    whatItIs:
      "A connected set of workspaces — capture, plan, create, work, and grow — with Chat beside you.",
    whenToUse: "When you want the big picture without reading every feature.",
    workflow: [
      "Capture thoughts in Clear My Mind.",
      "Move important ideas into Projects.",
      "Use Create to build business assets.",
      "Schedule work in Plan My Day.",
      "Save finished work in My Work.",
      "Track progress in 🌱 Growth.",
    ],
    tips: [
      "You do not need every area on day one — start where friction is lowest.",
    ],
    keywords: ["ecosystem", "how it works", "overview", "workflow"],
    openSection: "brain-dump",
    openLabel: "Open Clear My Mind",
  },
  {
    id: "understanding-the-main-areas",
    categoryId: "getting-started",
    title: "Understanding The Main Areas",
    emoji: "🗺️",
    whatItIs:
      "A map of the major destinations — Daily Use, Growth, and Resources — so you know where to go.",
    whenToUse: "When you are unsure which section fits what you need.",
    workflow: [
      "Sidebar: Chat, Focus, Create, Growth, My Work, How Do I.",
      `Top bar companion workspaces: ${TOP_NAV_COMPANION_WORKSPACES}.`,
      "Chat Workspace (💬) — New Chat or New Day's Chat when you need a fresh conversation or fresh daily start.",
      "Create: New Draft, Start From Template, Snippet, Audience Profile, Resume Draft.",
      "My Work: Search, Continue Working, Browse (Created Content, Projects, libraries, Archive).",
      "Growth: My Wins, Evidence Bank, My Highlights, My Journey.",
      "Open How Do I → Main Areas anytime for how each one works.",
    ],
    tips: ["Chat can help you pick — you do not have to memorize the map."],
    keywords: ["main areas", "sections", "map", "where to go"],
    openSection: "how-do-i",
    openLabel: "Browse Main Areas",
  },
  {
    id: "frequently-asked-questions",
    categoryId: "getting-started",
    title: "Frequently Asked Questions",
    emoji: "❓",
    whatItIs: "Quick answers to the questions new users ask most.",
    whenToUse: "When something feels confusing before you dive in.",
    workflow: [
      "How is this different from ChatGPT? — Built for ADHD business owners with memory, workspaces, and an ecosystem.",
      "Do I need setup first? — No. Capture a thought or chat — value first.",
      "Will tools open without me? — No. You confirm before anything opens.",
      "Where should I start? — Clear My Mind or Chat. Both are safe first steps.",
      "How do I start fresh? — Chat Workspace → New Chat (conversation only) or New Day's Chat (new day + Plan My Day reset).",
      "How does memory work? — Business context you provide shapes guidance — you stay in control.",
    ],
    tips: ["Search Help at the top of How Do I finds any topic instantly."],
    keywords: ["faq", "questions", "help", "new user"],
    askPrompt: "I'm new — what should I know first?",
  },

  // —— Conversation ——
  {
    id: "chat-companion",
    categoryId: "conversation",
    title: "Conversations",
    emoji: "💬",
    whatItIs: "The front door — talk through what is happening and get guidance.",
    whenToUse: "When you are not sure which tool to open first.",
    workflow: [
      "Type what is on your mind in plain language.",
      "Let the Companion clarify before recommending a tool.",
      "Say yes or no before anything opens in your workspace.",
      "Return to chat anytime — it stays beside your work.",
    ],
    tips: ["Conversation first. Tools second. You confirm before routing."],
    keywords: ["chat", "companion", "talk", "shari", "conversation"],
    askPrompt: "Help me figure out what to work on today.",
  },
  {
    id: "how-conversation-works",
    categoryId: "conversation",
    title: "How Conversation Works",
    emoji: "🔄",
    whatItIs: "Understand → clarify → optional tool offer → you choose.",
    whenToUse: "When you wonder why the Companion asks questions before opening tools.",
    workflow: [
      "Turn 1: the Companion understands your situation.",
      "Turn 2+: it may offer Brain Dump, Focus, Create, or another tool.",
      "You tap Yes to open or No to keep talking.",
      "Nothing auto-opens without your confirmation.",
    ],
    tips: ["This protects you from being routed somewhere you did not want."],
    keywords: ["how chat works", "routing", "tool offer", "confirm"],
    askPrompt: "Explain how conversation and tool recommendations work.",
  },
  {
    id: "voice-conversations",
    categoryId: "conversation",
    title: "Voice",
    emoji: "🎤",
    whatItIs: "Talk instead of type when writing feels like friction.",
    whenToUse: "Hands busy, low typing energy, or thoughts come faster aloud.",
    workflow: [
      "Tap the microphone in Chat or Clear My Mind.",
      "Speak naturally — no script needed.",
      "Review what was captured before saving.",
      "Edit or route thoughts the same as typed capture.",
    ],
    tips: ["Voice is capture and conversation — you still approve what stays."],
    keywords: ["voice", "microphone", "speak", "dictation"],
    openSection: "brain-dump",
    openLabel: "Open Clear My Mind",
  },
  {
    id: "memory",
    categoryId: "conversation",
    title: "Memory",
    emoji: "🧩",
    whatItIs: "Context the Companion remembers to personalize guidance — not hidden automation.",
    whenToUse: "When you want responses that fit your business and patterns.",
    workflow: [
      "Update Business Profile and Client Avatars when context changes.",
      "The Companion uses this to tailor suggestions — not to act for you.",
      "Review Profile settings if recommendations feel off.",
      "You can always override in conversation.",
    ],
    tips: ["Memory supports thinking — it does not replace your decisions."],
    keywords: ["memory", "remember", "context", "profile"],
    openSection: "business-profile",
    openLabel: "Open Business Profile",
  },
  {
    id: "adaptive-learning",
    categoryId: "conversation",
    title: "Adaptive Learning",
    emoji: "📊",
    whatItIs: "Patterns the app notices about how you work — observations, not grades.",
    whenToUse: "When you want insight into focus times, overload triggers, or momentum.",
    workflow: [
      "Use the app naturally over a few sessions.",
      "Check Progress and companion discoveries when offered.",
      "Treat insights as prompts, not rules.",
      "Adjust your plan based on what actually helps you.",
    ],
    tips: ["Observations support you — they do not judge you."],
    keywords: ["adaptive", "learning", "patterns", "insights"],
    openSection: "progress",
    openLabel: "Open Progress",
  },
  {
    id: "workspace-vs-chat",
    categoryId: "conversation",
    title: "Workspace vs Chat",
    emoji: "◧",
    whatItIs: "Chat thinks with you; workspaces hold what you choose to build.",
    whenToUse: "When you are confused about split screen or what opens where.",
    workflow: [
      "Chat stays on the left for conversation and guidance.",
      "Workspaces open on the right — Projects, Create, Plan My Day, etc.",
      "You open a workspace by choosing to — not by surprise.",
      "Close or switch workspaces without losing chat context.",
    ],
    tips: ["Chat = thinking partner. Workspace = your owned work surface."],
    keywords: ["workspace", "split", "panel", "beside", "chat vs"],
    askPrompt: "What is the difference between chat and workspace panels?",
  },
  {
    id: "chat-workspace",
    categoryId: "conversation",
    title: "Chat Workspace",
    emoji: "💬",
    featured: true,
    whatItIs: CHAT_WORKSPACE_NAV_MODEL,
    whenToUse:
      "When you want a fresh conversation or a fresh daily start without losing projects, memory, or goals.",
    workflow: [
      `Top bar: ${TOP_NAV_COMPANION_WORKSPACES} open companion workspaces.`,
      "Chat Workspace ▼ manages the conversation you are in right now.",
      `${NEW_CHAT_INSTRUCTION.label} — ${NEW_CHAT_INSTRUCTION.summary} Use when: "${NEW_CHAT_INSTRUCTION.useWhen}"`,
      `${NEW_DAYS_CHAT_INSTRUCTION.label} — ${NEW_DAYS_CHAT_INSTRUCTION.summary} Use when: "${NEW_DAYS_CHAT_INSTRUCTION.useWhen}"`,
      `${NEW_DAYS_CHAT_INSTRUCTION.label} also: ${NEW_DAYS_CHAT_INSTRUCTION.behavior.slice(0, 3).join("; ")}.`,
    ],
    tips: [
      "New Chat when the thread feels done but today's plan still fits.",
      "New Day's Chat when you are starting a new day and want a clean daily workspace.",
      "Neither option deletes your projects, memory, or Founder Intelligence learning.",
    ],
    keywords: [
      "chat workspace",
      "new chat",
      "new day's chat",
      "fresh conversation",
      "reset",
      "context",
      "day options",
      "start over",
    ],
    askPrompt: "Explain Chat Workspace, New Chat, and New Day's Chat.",
  },

  // —— Focus & Momentum ——
  {
    id: "focus-sessions",
    categoryId: "focus-momentum",
    title: "Focus",
    emoji: "⏱️",
    whatItIs: "Timed work with intention — timer, audio, and breathing when needed.",
    whenToUse: "You know what to do but cannot seem to start.",
    workflow: [
      "Open Focus from the sidebar.",
      "Name one task — everything else waits.",
      "Pick a timer, audio, or breathing reset.",
      "Work until the session ends — then decide what's next.",
    ],
    tips: ["One task per session. Seriously — one."],
    keywords: ["focus", "session", "timer", "pomodoro", "deep work"],
    openSection: "focus",
    openLabel: "Open Focus",
  },
  {
    id: "momentum-blocks",
    categoryId: "focus-momentum",
    title: "Momentum Blocks",
    emoji: "🧱",
    whatItIs: "Gentle time intentions — Momentum Appointments on your calendar.",
    whenToUse: "When you want structure without rigid deadlines.",
    workflow: [
      "Open Momentum Appointments (Time Block).",
      "Name one intention and pick 15–45 minutes.",
      "Start when ready — check in with How did it go?",
      "Made progress counts as success.",
    ],
    tips: ["Flexible timing is a feature, not a failure."],
    keywords: ["momentum", "appointment", "time block", "calendar"],
    openSection: "time-block",
    openLabel: "Open Momentum Appointments",
  },
  {
    id: "energy-matching",
    categoryId: "focus-momentum",
    title: "Energy Matching",
    emoji: "⚡",
    whatItIs: "Tune today's plan to how you actually feel.",
    whenToUse: "Morning check-in, burnout, or when the plan no longer fits.",
    workflow: [
      "Open Today's Reality from the top bar (🌤️) or tell Chat your energy level.",
      "Accept a lighter plan or one priority shift.",
      "Move heavy tasks to a better window in Plan My Day.",
      "Protect recovery — it is part of productivity.",
    ],
    tips: ["Matching energy prevents the shame spiral."],
    keywords: ["energy", "adjust", "capacity", "burnout", "tired"],
    openSection: "energy",
    openLabel: "Open Today's Reality",
  },
  {
    id: "overwhelm-recovery",
    categoryId: "focus-momentum",
    title: "Overwhelm Recovery",
    emoji: "🌊",
    whatItIs: "Step-by-step resets when everything feels like too much.",
    whenToUse: "Frozen, scattered, or emotionally overloaded.",
    workflow: [
      "Open Focus → I Need Support or tell Chat you are overwhelmed.",
      "Pick a support flow that matches how you feel.",
      "Follow one small step at a time — pause anytime.",
      "Return to Clear My Mind when ready to externalize thoughts.",
    ],
    tips: ["Recovery first. Planning second."],
    keywords: ["overwhelm", "overwhelmed", "too much", "reset", "support"],
    openSection: "focus",
    openLabel: "Open Focus",
  },
  {
    id: "restarting-after-falling-behind",
    categoryId: "focus-momentum",
    title: "Restarting After Falling Behind",
    emoji: "🔁",
    whatItIs: "A shame-free path back in after time away or missed plans.",
    whenToUse: "Guilt about backlog, missed days, or abandoned projects.",
    workflow: [
      `Use Chat Workspace → ${NEW_CHAT_INSTRUCTION.label} if yesterday's conversation is haunting you.`,
      "Dump the mental load in Clear My Mind — no sorting.",
      "Pick one tiny next action in Plan My Day.",
      "Log one win for showing up again.",
    ],
    tips: ["Restarting is a skill. You are practicing it right now."],
    keywords: ["restart", "behind", "catch up", "guilt", "return"],
    openSection: "plan-my-day",
    openLabel: "Open Plan My Day",
  },

  // —— Planning (featured: plan-my-day) ——
  {
    id: "plan-my-day",
    categoryId: "planning",
    title: "Plan My Day",
    emoji: "📅",
    featured: true,
    whatItIs:
      "A daily decision workspace — decide what is realistic for today based on your energy, time, and capacity. Not a task manager or long-term planner.",
    whenToUse:
      "When you need to answer: what fits today's reality? Pull from Clear My Mind, Projects, yesterday's unfinished work, or new ideas — then choose what matters most today.",
    workflow: [
      "Add a task above the board — then decide which column it belongs in.",
      "Work the board: Considering Today → Today's Focus → In Progress.",
      "Tap ✓ to complete — items archive to progress history and leave the board.",
      "Defer or remove what does not belong today.",
      "Update Today's Reality via Today's Reality in the top bar when your capacity shifts.",
      "When starting a new day, use Chat Workspace → New Day's Chat — this workspace is intentionally temporary.",
    ],
    tips: [
      "The goal is not to do everything — it is to identify what matters most today.",
      "Today's Reality shows as a compact summary in Plan My Day — use Today's Reality in the top bar when your capacity shifts.",
      "Kanban: Considering Today → Today's Focus → In Progress — no permanent Done column.",
    ],
    keywords: ["plan", "day", "today", "realistic", "capacity", "kanban", "daily"],
    openSection: "plan-my-day",
    openLabel: "Open Plan My Day",
  },
  {
    id: "visual-focus",
    categoryId: "planning",
    title: "Visual Thinking",
    emoji: "💡",
    featured: true,
    whatItIs:
      "A visual thinking studio — understand, explore, connect, decide, and strategize. The insight is the product, not the file.",
    whenToUse:
      "When linear lists fail and you need to see relationships, paths, or patterns — not when you need today's task list.",
    workflow: [
      "Open Visual Thinking from the sidebar.",
      "Pick a card that matches what you're figuring out — each shows what it is, when to use it, and what you'll receive.",
      "Build your map, then Generate for visuals, insights, recommendations, and next steps.",
      "Continue Thinking resumes active work (up to 3 maps). Save intentionally when something is worth keeping.",
      "Pinned favorites live in Other → Saved — not on the studio dashboard.",
      "Use Work With Shari when you're not sure which thinking style fits.",
    ],
    tips: visualThinkingToolHelpTips(),
    keywords: [
      "visual thinking",
      "mind map",
      "decision tree",
      "relationship map",
      "business canvas",
      "strategy map",
      "project map",
      "visual kanban",
      "studio",
      "continue thinking",
    ],
    openSection: "visual-focus",
    openLabel: "Open Visual Thinking",
  },
  {
    id: "momentum-appointments",
    categoryId: "planning",
    title: "Momentum Appointments",
    emoji: "🗓️",
    whatItIs: "Named windows for one intention — gentle, not punitive.",
    whenToUse: "When a task needs a time home on your calendar.",
    workflow: [
      "Name what you are moving forward.",
      "Pick duration and optional time of day.",
      "Link to a project if helpful.",
      "Check in when done — partial progress counts.",
    ],
    tips: ["Every outcome counts — done, partial, or not today."],
    keywords: ["appointment", "momentum", "schedule", "calendar"],
    openSection: "time-block",
    openLabel: "Open Momentum Appointments",
  },
  {
    id: "time-blocking",
    categoryId: "planning",
    title: "Time Blocking",
    emoji: "🕐",
    whatItIs: "Assign tasks to time on your day — see the load visually.",
    whenToUse: "When floating tasks need a when, not just a what.",
    workflow: [
      "Add items to Plan My Day or Time Bank.",
      "Assign blocks to morning, afternoon, or specific times.",
      "Adjust when reality shifts — drag, don't guilt.",
      "Start a focus session from a block when ready.",
    ],
    tips: ["Blocks are intentions, not contracts with yourself."],
    keywords: ["time block", "blocking", "calendar", "schedule"],
    openSection: "time-block",
    openLabel: "Open Calendar",
  },
  {
    id: "ready-when-you-are",
    categoryId: "planning",
    title: "Ready When You Are",
    emoji: "✋",
    whatItIs: "Flexible items that wait until you have capacity — no fixed clock.",
    whenToUse: "Low predictability days or when rigid timing backfires.",
    workflow: [
      "Add tasks without forcing a time.",
      "Use list view to pick one when ready.",
      "Move to Doing only when you choose to start.",
      "Park without deleting — it stays available.",
    ],
    tips: ["Readiness is valid planning data."],
    keywords: ["flexible", "ready", "when you are", "no pressure"],
    openSection: "plan-my-day",
    openLabel: "Open Plan My Day",
  },
  {
    id: "kanban-planning",
    categoryId: "planning",
    title: "Kanban Planning",
    emoji: "📋",
    whatItIs:
      "Considering Today → Today's Focus → In Progress — complete to archive. No permanent Done column.",
    whenToUse: "When you want to see today's decision flow without turning the board into storage.",
    workflow: [
      "Open Plan My Day and switch to Kanban view.",
      "Considering Today — ideas still on your radar.",
      "Today's Focus — what matters most today.",
      "In Progress — what you are actively doing.",
      "Tap ✓ to complete — items archive to progress history and leave the board.",
    ],
    tips: [
      "Use Chat Workspace → New Day's Chat when starting a fresh day — this board is intentionally temporary.",
      "Dragging counts as executive function support.",
    ],
    keywords: ["kanban", "columns", "doing", "complete", "board", "daily"],
    openSection: "plan-my-day",
    openLabel: "Open Plan My Day",
  },

  // —— Create ——
  {
    id: "create-overview",
    categoryId: "create",
    title: "Create",
    emoji: "✍️",
    featured: true,
    whatItIs: "Build business assets through guided conversation — you choose what gets saved.",
    whenToUse: "When you need a draft and want help thinking it through first.",
    workflow: [
      "Open Create from the sidebar.",
      "Choose New Draft, Start From Template, Snippet, Audience Profile, or Resume Draft.",
      "Answer one question at a time with Shari beside you.",
      "Review the plan before generating.",
      "Save to My Work when it feels right.",
    ],
    tips: ["Nothing lands in your workspace until you choose."],
    keywords: ["create", "content", "draft", "build"],
    openSection: "content-generator",
    openLabel: "Open Create",
  },
  {
    id: "create-documents",
    categoryId: "create",
    title: "Create Documents",
    emoji: "📄",
    whatItIs: "Proposals, one-pagers, briefs, and business documents.",
    whenToUse: "When you need a structured doc, not a blank page.",
    workflow: [
      "Open Create → pick document type.",
      "Answer questions about audience and goal.",
      "Generate when ready — edit freely after.",
      "Export or save to My Work.",
    ],
    tips: ["Start with who it is for, not perfect wording."],
    keywords: ["document", "proposal", "brief", "one pager"],
    openSection: "content-generator",
    openLabel: "Open Create",
  },
  {
    id: "create-workshops",
    categoryId: "create",
    title: "Create Workshops",
    emoji: "🎓",
    whatItIs: "Workshop outlines, agendas, and participant materials.",
    whenToUse: "Planning a live session, webinar, or training.",
    workflow: [
      "Open Create → Workshop.",
      "Describe outcome and audience.",
      "Build section by section in conversation.",
      "Save and refine in your workspace.",
    ],
    tips: ["Outline first — slides and details can come later."],
    keywords: ["workshop", "webinar", "training", "session"],
    openSection: "content-generator",
    openLabel: "Open Create",
    askPrompt: "Help me plan a workshop — one question at a time.",
  },
  {
    id: "create-sops",
    categoryId: "create",
    title: "Create SOPs",
    emoji: "📋",
    whatItIs: "Standard operating procedures — repeatable how-we-do-this docs.",
    whenToUse: "When you repeat the same process and want it documented.",
    workflow: [
      "Open Create → SOP.",
      "Walk through steps as you actually do them.",
      "Generate a draft checklist or procedure.",
      "Save to My Work or link to a Project.",
    ],
    tips: ["Messy real steps beat idealized fantasy SOPs."],
    keywords: ["sop", "procedure", "process", "checklist"],
    openSection: "content-generator",
    openLabel: "Open Create",
  },
  {
    id: "create-marketing-plans",
    categoryId: "create",
    title: "Create Marketing Plans",
    emoji: "📣",
    whatItIs: "Campaign and marketing plans built with your constraints.",
    whenToUse: "Launching, promoting, or resetting marketing direction.",
    workflow: [
      "Open Create or Strategies → Business Strategies.",
      "Name the offer and audience.",
      "Break into phases you can actually execute.",
      "Save plan to My Work or a Project.",
    ],
    tips: ["A small plan you use beats a giant plan you avoid."],
    keywords: ["marketing plan", "campaign", "launch", "promotion"],
    openSection: "content-generator",
    openLabel: "Open Create",
  },
  {
    id: "create-landing-pages",
    categoryId: "create",
    title: "Create Landing Pages",
    emoji: "🌐",
    whatItIs: "Landing page copy and structure — headline to CTA.",
    whenToUse: "New offer, lead magnet, or sales page needed.",
    workflow: [
      "Open Create → landing page or sales page.",
      "Clarify one offer and one audience.",
      "Draft sections — hero, benefits, CTA.",
      "Edit and export when you approve the copy.",
    ],
    tips: ["One page, one offer, one action."],
    keywords: ["landing page", "sales page", "website copy"],
    openSection: "content-generator",
    openLabel: "Open Create",
  },
  {
    id: "create-email-sequences",
    categoryId: "create",
    title: "Create Email Sequences",
    emoji: "✉️",
    whatItIs: "Email series — welcome, nurture, launch, or follow-up.",
    whenToUse: "Building automated or manual email flows.",
    workflow: [
      "Open Create → email sequence.",
      "Define the journey and number of emails.",
      "Draft one email at a time — approve each.",
      "Save to My Work or Snippets for reuse.",
    ],
    tips: ["Use Snippets for subject lines and hooks."],
    keywords: ["email", "sequence", "nurture", "newsletter"],
    openSection: "content-generator",
    openLabel: "Open Create",
  },
  {
    id: "create-courses",
    categoryId: "create",
    title: "Create Courses",
    emoji: "🎬",
    whatItIs: "Course outlines, modules, and lesson plans.",
    whenToUse: "Building a course, membership, or curriculum.",
    workflow: [
      "Open Create → course or curriculum.",
      "Define transformation and modules.",
      "Fill modules one at a time.",
      "Link to a Project for long builds.",
    ],
    tips: ["Module outlines before filming or writing lessons."],
    keywords: ["course", "curriculum", "modules", "lessons"],
    openSection: "content-generator",
    openLabel: "Open Create",
  },

  // —— Business Growth ——
  {
    id: "marketing",
    categoryId: "business-growth",
    title: "Marketing",
    emoji: "📣",
    whatItIs: "Visibility and messaging for what you sell.",
    whenToUse: "Growing awareness, launches, or consistent presence.",
    workflow: [
      "Clarify offer and audience in Chat or Client Avatars.",
      "Use Create for campaigns and content.",
      "Save frameworks in Strategies.",
      "Track wins when you ship — not only when it goes viral.",
    ],
    tips: ["Consistency beats perfection in marketing."],
    keywords: ["marketing", "promote", "visibility", "audience"],
    openSection: "content-generator",
    openLabel: "Open Create",
  },
  {
    id: "content-creation",
    categoryId: "business-growth",
    title: "Content Creation",
    emoji: "📝",
    whatItIs: "Posts, articles, videos scripts, and reusable content.",
    whenToUse: "Showing up online without starting from zero each time.",
    workflow: [
      "Use Snippets for hooks and CTAs.",
      "Use Create for full drafts.",
      "Save templates for formats you repeat.",
      "Batch in Plan My Day when energy allows.",
    ],
    tips: ["Repurpose one idea across formats — save brain power."],
    keywords: ["content", "post", "social", "blog", "video"],
    openSection: "content-generator",
    openLabel: "Open Create",
  },
  {
    id: "sales",
    categoryId: "business-growth",
    title: "Sales",
    emoji: "🤝",
    whatItIs: "Conversations, proposals, and follow-up that close work.",
    whenToUse: "Active deals, proposals, or client conversations.",
    workflow: [
      "Capture follow-ups in Clear My Mind.",
      "Use Create for proposals and emails.",
      "Track deals in Projects.",
      "Schedule momentum appointments for sales blocks.",
    ],
    tips: ["Follow-up is a system — not a personality trait."],
    keywords: ["sales", "client", "proposal", "deal", "follow up"],
    openSection: "projects",
    openLabel: "Open Projects",
  },
  {
    id: "lead-generation",
    categoryId: "business-growth",
    title: "Lead Generation",
    emoji: "🧲",
    whatItIs: "Attracting and capturing people interested in your offer.",
    whenToUse: "Building pipeline or launching lead magnets.",
    workflow: [
      "Define ideal client in Client Avatars.",
      "Create lead magnet or landing page in Create.",
      "Plan outreach blocks in Plan My Day.",
      "Route leads into Projects for follow-up.",
    ],
    tips: ["One clear lead path beats five half-built funnels."],
    keywords: ["leads", "lead gen", "funnel", "prospect"],
    openSection: "client-avatars",
    openLabel: "Open Client Avatars",
  },
  {
    id: "visibility",
    categoryId: "business-growth",
    title: "Visibility",
    emoji: "👁️",
    whatItIs: "Being seen by the right people — without burning out.",
    whenToUse: "Hiding too much or inconsistent public presence.",
    workflow: [
      "Pick one visibility channel for this month.",
      "Plan small content blocks — not daily heroics.",
      "Use Strategies for recurring visibility habits.",
      "Log wins when you show up, not only when it blows up.",
    ],
    tips: ["Visible and sustainable beats visible and exhausted."],
    keywords: ["visibility", "seen", "audience", "presence"],
    openSection: "playbook",
    openLabel: "Open Strategies",
  },
  {
    id: "networking",
    categoryId: "business-growth",
    title: "Networking",
    emoji: "🔗",
    whatItIs: "Relationships that support your business — follow-up included.",
    whenToUse: "Events, collaborations, or reconnecting with contacts.",
    workflow: [
      "Capture names and context in Clear My Mind.",
      "Create follow-up emails in Create.",
      "Schedule momentum appointments for outreach.",
      "Link conversations to Projects when ongoing.",
    ],
    tips: ["One genuine follow-up beats collecting business cards."],
    keywords: ["network", "networking", "connections", "referral"],
    openSection: "brain-dump",
    openLabel: "Open Clear My Mind",
  },

  // —— Workspace (featured items) ——
  {
    id: "projects",
    categoryId: "workspace",
    title: "Projects",
    emoji: "📁",
    featured: true,
    whatItIs: "Multi-step work in one place — tasks, notes, files, next actions.",
    whenToUse: "Work that lasts more than one session.",
    workflow: [
      "Create or open a project.",
      "Add one clear next action.",
      "Expand only the section you need.",
      "Schedule time or open Create when ready.",
    ],
    tips: ["One next action beats a long list."],
    keywords: ["project", "projects"],
    openSection: "projects",
    openLabel: "Open Projects",
  },
  {
    id: "clear-my-mind",
    categoryId: "workspace",
    title: "Clear My Mind",
    emoji: "🧠",
    featured: true,
    whatItIs:
      "A safe brain dump — capture what's in your head without organizing first, then see everything safely held.",
    whenToUse: "When your head feels full, noisy, or overwhelming.",
    workflow: [
      "Open Clear My Mind from the top navigation (🧠).",
      "Capture — add thoughts; separate with commas. Messy is fine.",
      "If Smart Split is offered, choose Separate Them or Keep As Entered.",
      "Tap See what's held — Everything is held, grouped into clusters.",
      "Expand a cluster → View thoughts → select a thought for actions when ready.",
      "Add More Thoughts anytime to continue the same session.",
    ],
    tips: [
      "Relief before action — clusters reassure first; you choose when to see thoughts.",
      "Thought actions include Mark Done, Schedule, Move to Project, and Keep Here.",
    ],
    keywords: ["clear", "mind", "brain dump", "thoughts", "capture", "held"],
    openSection: "brain-dump",
    openLabel: "Open Clear My Mind",
  },
  {
    id: "strategies",
    categoryId: "workspace",
    title: "Strategies",
    emoji: "🎯",
    featured: true,
    whatItIs: "ADHD techniques and business playbooks you reuse.",
    whenToUse: "Recurring challenges — procrastination, scope creep, marketing rhythm.",
    workflow: [
      "Open Strategies from My Work → Browse, or start from Create.",
      "Pick ADHD or Business strategies.",
      "Apply step by step or save your own.",
      "Connect to Projects when ready to execute.",
    ],
    tips: ["Name what works — future-you will thank you."],
    keywords: ["strategy", "strategies", "playbook"],
    openSection: "playbook",
    openLabel: "Open Strategies",
  },
  {
    id: "templates",
    categoryId: "workspace",
    title: "Templates",
    emoji: "📚",
    featured: true,
    whatItIs: "Reusable frameworks — starting points, not finished docs.",
    whenToUse: "Repeated formats — emails, SOPs, launches.",
    workflow: [
      "Open Templates from Create → Start From Template, or My Work → Browse.",
      "Pick a match.",
      "Build With Shari to adapt — agree before drafting.",
      "Save versions you reuse.",
    ],
    tips: ["Templates save setup time, not thinking time."],
    keywords: ["template", "templates"],
    openSection: "templates-library",
    openLabel: "Open Templates",
  },
  {
    id: "snippets",
    categoryId: "workspace",
    title: "Snippets",
    emoji: "📝",
    featured: true,
    whatItIs: "Small reusable copy blocks — hooks, CTAs, lines you repeat.",
    whenToUse: "Quick copy without a full Create session.",
    workflow: [
      "Open Snippets from Create → Start From Snippet, or My Work → Browse.",
      "Generate or write lines.",
      "Save what you like.",
      "Copy or expand in Create.",
    ],
    tips: ["Snippets are lightweight — use them liberally."],
    keywords: ["snippet", "snippets"],
    openSection: "snippets",
    openLabel: "Open Snippets",
  },
  {
    id: "blueprints",
    categoryId: "workspace",
    title: "Blueprints",
    emoji: "🗺️",
    whatItIs: "Structured starting maps for launches, offers, and systems — like templates with a bigger arc.",
    whenToUse: "Multi-step builds where you want the skeleton before the draft.",
    workflow: [
      "Browse Templates or Strategies for blueprint-style frameworks.",
      "Open in Create when you want to fill it in.",
      "Link to a Project for the full build.",
      "Save finished blueprints to My Work.",
    ],
    tips: ["Blueprints are scaffolds — you still own every word."],
    keywords: ["blueprint", "framework", "map", "launch plan"],
    openSection: "templates-library",
    openLabel: "Open Templates",
  },
  {
    id: "saved-work",
    categoryId: "workspace",
    title: "Created Content",
    emoji: "📂",
    whatItIs: "Finished and in-progress drafts — SOPs, emails, workshops, plans.",
    whenToUse: "Finding something you already built.",
    workflow: [
      "Open My Work → Browse My Work → Created Content.",
      "Search or browse by type.",
      "Open in Create to continue editing.",
      "Export when ready to use outside the app.",
    ],
    tips: ["Created Content is your library — not a junk drawer."],
    keywords: ["saved", "saved work", "created content", "drafts", "library"],
    openSection: "saved-work",
    openLabel: "Open Created Content",
  },
  {
    id: "my-work",
    categoryId: "workspace",
    title: "My Work",
    emoji: "💼",
    featured: true,
    whatItIs:
      "One home for everything in progress, saved, and recent — organized into Continue Working and Browse My Work.",
    whenToUse: "Resume work or see the full picture.",
    workflow: [
      "Open My Work from the sidebar (🏠 — beside Growth and How Do I).",
      "Search Everything to find any project, draft, strategy, or archive item.",
      "Continue Working — favorites, recently active, and resume items.",
      "Browse My Work — Created Content, Projects, Snippets, Strategies, Templates, and Archive.",
    ],
    tips: ["My Work is visibility — not another inbox."],
    keywords: ["my work", "home", "resume", "browse", "archive", "search"],
    openSection: "my-work",
    openLabel: "Open My Work",
  },
  {
    id: "my-work-archive",
    categoryId: "workspace",
    title: "My Work Archive",
    emoji: "🗄️",
    whatItIs:
      "Finished or older work — archived saved content, completed projects, and retired templates.",
    whenToUse: "When you need something you finished or archived earlier.",
    workflow: [
      "Open My Work → Browse My Work → Archive.",
      "Browse archived saved work and completed projects.",
      "Open an item to review or continue if needed.",
    ],
    tips: ["Archive keeps finished work out of the way without deleting it."],
    keywords: ["archive", "archived", "completed", "old work", "my work archive"],
    openSection: "my-work",
    openLabel: "Open My Work",
  },

  // —— Personal Growth ——
  {
    id: "growth-center",
    categoryId: "personal-growth",
    title: "Growth Center",
    emoji: "🌱",
    featured: true,
    whatItIs:
      "Your hub for progress, impact, highlights, and story — four areas you open from navigation cards, plus Growth Inbox and Growth Reports.",
    whenToUse:
      "When you want the big picture of how you are growing — not just today's tasks.",
    workflow: [
      "Open Growth from the sidebar (🌱 — beside Create and My Work).",
      "Open Wins, Evidence Bank, My Highlights, or My Journey from the hub cards.",
      "Check Growth Inbox for moments the app noticed — save where they belong or dismiss.",
      "Tap 📖 Growth Reports to build a printable or downloadable combined report.",
    ],
    tips: [
      "Why it matters: reviewing progress trains pattern recognition and self-awareness — you see momentum you would otherwise forget.",
      "Nothing moves without your review — Growth Inbox protects you from auto-logging.",
      "Support first: celebrate small wins before analyzing trends.",
    ],
    keywords: [
      "growth",
      "growth center",
      "growth hub",
      "inbox",
      "cognitive growth",
      "progress",
      "pillars",
    ],
    openSection: "growth",
    openLabel: "Open Growth Center",
  },
  {
    id: "wins-this-week",
    categoryId: "personal-growth",
    title: "Wins This Week",
    emoji: "🏆",
    featured: true,
    whatItIs:
      "Confirmed progress for this week — encouragement without performance pressure. Wins capture what happened; Evidence Bank captures why it mattered.",
    whenToUse:
      "Friday reflection, low-motivation days, or when you need proof you are moving forward.",
    workflow: [
      "Open Wins This Week from 🌱 Growth or the Growth cross-links.",
      "Review the activity summary for the current week (auto-collected from your work).",
      "Check Growth Inbox on the Growth hub — edit, then Save as Win, or dismiss what does not count.",
      "Attach images or files to a saved win with Attach on the win card.",
      "Tap Save to Evidence when you want the deeper impact story for a win.",
      "Use Archive filters (week, month, quarter, year) and search to browse past wins.",
      "Tap 🖨 Print in the header to print your wins view.",
      "Glance at Previous weeks for archived activity summaries.",
    ],
    tips: [
      "Why wins matter: noticing forward motion builds reflection and confidence — your brain learns to see momentum, not only gaps.",
      "Small steps count — including showing up, starting, or finishing one hard thing.",
      "Wins are facts (what happened). Evidence is meaning (why it mattered). My Highlights is recognition (praise and accomplishments).",
    ],
    keywords: [
      "wins",
      "week",
      "weekly",
      "weekly wins",
      "win",
      "growth inbox",
      "cognitive growth",
      "reflection",
      "print wins",
    ],
    openSection: "wins-this-week",
    openLabel: "Open Wins This Week",
  },
  {
    id: "evidence-bank",
    categoryId: "personal-growth",
    title: "Evidence Bank",
    emoji: "📈",
    featured: true,
    whatItIs:
      "Proof that your work created impact, solved problems, and moved things forward — not a gratitude journal or resume.",
    whenToUse:
      "When imposter syndrome shows up, you need facts for a decision, or you want to remember why your work mattered.",
    workflow: [
      "Open Evidence Bank from 🌱 Growth.",
      "Tap Add evidence — or route from Growth Inbox (Save as Evidence) or a win (Save to Evidence).",
      "Pick a category: Business Growth, Client Impact, Personal Growth, Health & Wellbeing, Courage, or Problem Solving.",
      "Fill what happened and why it mattered — what improved, who benefited, what this proves.",
      "Attach screenshots, certificates, or documents per entry (Attach on an expanded entry).",
      "Edit, Print, or Export individual entries from the entry actions.",
      "Use Archive filters and search to review proof over time.",
      "Tap 🖨 Print in the header to print your evidence list.",
    ],
    tips: [
      "Why evidence matters: capturing impact strengthens pattern recognition and decision-making — you build a library of proof for pricing, pitching, and hard choices.",
      "Core question: What changed because of what I did?",
      "Good evidence names the fact, the impact, and who benefited — e.g. \"Client signed after I simplified the proposal — they said clarity was the deciding factor.\"",
      "Separate from wins (what happened) and My Highlights (praise and accomplishments about you).",
    ],
    keywords: [
      "evidence",
      "proof",
      "bank",
      "accomplish",
      "impact",
      "decision making",
      "pattern recognition",
      "cognitive growth",
      "print evidence",
      "export",
      "attach",
    ],
    openSection: "evidence-bank",
    openLabel: "Open Evidence Bank",
  },
  {
    id: "my-highlights",
    categoryId: "personal-growth",
    title: "My Highlights",
    emoji: "🌟",
    whatItIs:
      "A collection of accomplishments, expertise, recognition, praise, credentials, testimonials, awards, and meaningful moments — recognizing what you have achieved, not \"building confidence.\"",
    whenToUse:
      "When praise arrives, you earn a credential, or you want to remember strengths and recognition later.",
    workflow: [
      "Open My Highlights from 🌱 Growth (🌟 card).",
      "Quick Save — paste a compliment, testimonial, or praise with no long form.",
      "Add full item — title, category, source, date, description, link, and attachments.",
      "Categories include Testimonials, Praise & Compliments, Credentials, Certifications, Awards, Accomplishments, Client Results, Success Stories, Speaking Engagements, Media Features, and Personal Achievements.",
      "⭐ Mark most meaningful on entries you want to find fast.",
      "Filter by type or search title, description, and source.",
      "Route from Growth Inbox with Add to My Highlights.",
      "Tap 🖨 Print to print your highlights view.",
    ],
    tips: [
      "Why highlights matter: preserving recognition helps you remember reality when self-doubt appears — this is about accomplishments, not ego.",
      "Belongs here: testimonials, praise, credentials, certifications, awards, speaking, media, client results, and personal achievements.",
      "Not Evidence Bank (impact on others) and not My Journey (life story and lessons).",
    ],
    keywords: [
      "highlights",
      "my highlights",
      "testimonials",
      "praise",
      "credentials",
      "certifications",
      "awards",
      "accomplishments",
      "recognition",
      "speaking",
      "media",
      "client results",
      "cognitive growth",
    ],
    openSection: "confidence-vault",
    openLabel: "Open My Highlights",
  },
  {
    id: "my-journey",
    categoryId: "personal-growth",
    title: "My Journey",
    emoji: "🌿",
    whatItIs:
      "Your personal and professional story — experiences, lessons, milestones, and wisdom. Not a resume.",
    whenToUse:
      "When something shaped you, you learned a lesson, or you want to preserve meaning over time.",
    workflow: [
      "Open My Journey from 🌱 Growth.",
      "Add an entry — title, category, life chapter, and what happened.",
      "Fill what you learned, how it shaped you, and any wisdom to keep.",
      "Attach photos, letters, certificates, or links.",
      "Browse Timeline or Chapters view to see your story unfold.",
      "Filter by milestones, lessons, career, business, education, or wisdom.",
      "Save weekly reflection answers from Growth Center to Journey when offered.",
      "Route from Growth Inbox with Save as Journey.",
    ],
    tips: [
      "Why capturing growth matters: reflection and meaning-making strengthen self-awareness and learning from experience.",
      "Journey holds who you are becoming. Evidence holds impact you created. Highlights hold recognition you received.",
      "Life chapters (Early Life, Career, ADHD Discovery, Current Season, etc.) help you find perspective later.",
    ],
    keywords: [
      "journey",
      "my journey",
      "milestones",
      "lessons learned",
      "life chapters",
      "personal growth",
      "business growth",
      "wisdom",
      "story",
      "reflection",
      "cognitive growth",
    ],
    openSection: "my-journey",
    openLabel: "Open My Journey",
  },
  {
    id: "growth-reports",
    categoryId: "personal-growth",
    title: "Reports",
    emoji: "📊",
    whatItIs:
      "Printable and downloadable reports that combine wins, evidence, highlights, journey, reflections, photos, and files for a date range you choose.",
    whenToUse:
      "Weekly reviews, monthly check-ins, annual accomplishments, or sharing progress with a coach, partner, or future you.",
    workflow: [
      "Open 🌱 Growth and tap 📖 Growth Reports.",
      "Pick report type: Weekly, Monthly, Quarterly, Annual, or Custom Date Range.",
      "For custom, set From and To dates.",
      "Choose what to include — wins, evidence, highlights, journey, photos, files, testimonials, certifications, reflections.",
      "Pick report style: Summary or Detailed (Storybook and Visual styles include full narrative now; richer styling coming soon).",
      "Tap Generate Growth Report — opens in a new tab for Print or Save as PDF.",
      "Or tap Download HTML to save the report file and print to PDF anytime.",
    ],
    tips: [
      "Why reviewing progress matters: seeing weeks or months together reveals patterns your day-to-day brain misses.",
      "Weekly defaults are light (wins + evidence + highlights + journey). Annual includes testimonials, certifications, and reflections.",
      "PDF export per-entry is coming soon — Growth Reports are the full combined export today.",
    ],
    keywords: [
      "growth reports",
      "growth report",
      "print report",
      "pdf",
      "weekly report",
      "monthly report",
      "annual report",
      "custom date",
      "storybook",
      "visual report",
      "export",
    ],
    openSection: "growth",
    openLabel: "Open Growth Reports",
  },
  {
    id: "celebrating-progress",
    categoryId: "personal-growth",
    title: "Celebrating Progress",
    emoji: "🎉",
    whatItIs: "Acknowledging forward motion — not only finished outcomes.",
    whenToUse: "After completing something or end of week.",
    workflow: [
      "Log a win via Growth Inbox or Wins This Week.",
      "Tell Chat if you want acknowledgment.",
      "Review Evidence Bank or My Highlights when doubting yourself.",
      "Plan a small reward that actually restores you.",
    ],
    tips: [
      "Celebration trains your brain to try again — part of cognitive growth through reflection.",
    ],
    keywords: ["celebrate", "progress", "win", "acknowledge"],
    openSection: "wins-this-week",
    openLabel: "Open Wins This Week",
  },
  {
    id: "confidence-building",
    categoryId: "personal-growth",
    title: "Confidence Building",
    emoji: "💪",
    whatItIs:
      "Using evidence, highlights, and small wins to counter self-doubt — grounded in facts, not affirmations.",
    whenToUse: "Pricing conversations, launches, or comparison traps.",
    workflow: [
      "Review Evidence Bank before hard tasks — what impact you have created.",
      "Open My Highlights — testimonials, praise, and accomplishments you have saved.",
      "List three recent wins from Wins This Week — any size.",
      "Use Client Avatars to anchor who you help.",
      "Take one visible action — send, post, or ship small.",
    ],
    tips: ["Confidence follows action more often than the reverse."],
    keywords: ["confidence", "imposter", "doubt", "self esteem"],
    askPrompt: "Help me build confidence for something I am avoiding.",
  },
  {
    id: "tracking-growth",
    categoryId: "personal-growth",
    title: "Tracking Growth",
    emoji: "📈",
    whatItIs: "Seeing patterns over weeks — not daily scorekeeping.",
    whenToUse: "Monthly reviews or planning the next chapter.",
    workflow: [
      "Open 🌱 Growth for the snapshot across all four pillars.",
      "Review Wins This Week history and Evidence Bank trends.",
      "Browse My Journey chapters for lessons and milestones.",
      "Use 📖 Growth Reports for monthly or annual reviews.",
      "Adjust Plan My Day based on what actually happened.",
    ],
    tips: [
      "Trends matter more than any single day — reviewing progress is a thinking skill.",
    ],
    keywords: ["growth", "track", "progress", "review", "growth reports", "cognitive growth"],
    openSection: "growth",
    openLabel: "Open Growth Center",
  },

  // —— ADHD Support ——
  {
    id: "adhd-strategies",
    categoryId: "adhd-support",
    title: "ADHD Strategies",
    emoji: "🧩",
    whatItIs: "Techniques for executive function — use in the moment.",
    whenToUse: "Stuck, scattered, avoiding, or cannot initiate.",
    workflow: [
      "Open Strategies → ADHD Strategies.",
      "Pick a match for right now.",
      "Follow steps — pause if overwhelmed.",
      "Save strategies that work for you.",
    ],
    tips: ["Strategies are tools, not moral fixes."],
    keywords: ["adhd", "strategy", "executive function"],
    openSection: "playbook",
    openLabel: "Open ADHD Strategies",
  },
  {
    id: "executive-function",
    categoryId: "adhd-support",
    title: "Executive Function",
    emoji: "🎛️",
    whatItIs: "Support for planning, prioritizing, starting, and finishing.",
    whenToUse: "When knowing what to do is not the same as doing it.",
    workflow: [
      "Externalize in Clear My Mind.",
      "Pick one next action in Plan My Day.",
      "Use Focus Sessions to start.",
      "Use Strategies for recurring EF gaps.",
    ],
    tips: ["External structure is a legitimate accommodation."],
    keywords: ["executive function", "ef", "planning", "initiate"],
    openSection: "playbook",
    openLabel: "Open Strategies",
  },
  {
    id: "adhd-overwhelm",
    categoryId: "adhd-support",
    title: "Overwhelm",
    emoji: "🌊",
    whatItIs: "When input exceeds capacity — nervous system first.",
    whenToUse: "Shutdown, panic, or cannot pick one thing.",
    workflow: [
      "Stop adding tasks.",
      "Open support flow or breathe reset.",
      "Dump thoughts without sorting.",
      "Choose one microscopic next step only.",
    ],
    tips: ["Overwhelm is a signal — not a character flaw."],
    keywords: ["overwhelm", "shutdown", "flooded"],
    openSection: "focus",
    openLabel: "Open Focus",
  },
  {
    id: "task-initiation",
    categoryId: "adhd-support",
    title: "Task Initiation",
    emoji: "🚦",
    whatItIs: "Getting started when the task feels sticky or boring.",
    whenToUse: "Staring at the task, tab switching, or productive procrastination.",
    workflow: [
      "Shrink the task to a 2-minute first step.",
      "Start a Focus Session — timer only.",
      "Body double or focus audio if helpful.",
      "Log a win for starting — not only finishing.",
    ],
    tips: ["Starting is a separate skill from finishing."],
    keywords: ["start", "initiation", "procrastinate", "stuck"],
    openSection: "focus",
    openLabel: "Open Focus",
  },
  {
    id: "motivation",
    categoryId: "adhd-support",
    title: "Motivation",
    emoji: "🔥",
    whatItIs: "Working with interest-based nervous systems — not against them.",
    whenToUse: "Boring tasks, low dopamine, or need momentum.",
    workflow: [
      "Pair boring tasks with interest — music, timer, reward.",
      "Use Spin The Wheel or games for low-stakes picks.",
      "Connect task to a Client Avatar or real person.",
      "Celebrate completion in Wins This Week.",
    ],
    tips: ["Interest, urgency, novelty, and challenge are levers — use them."],
    keywords: ["motivation", "dopamine", "boring", "interest"],
    openSection: "games",
    openLabel: "Open Momentum Games",
  },
  {
    id: "planning-problems",
    categoryId: "adhd-support",
    title: "Planning Problems",
    emoji: "🗓️",
    whatItIs: "When plans feel imaginary or impossible to follow.",
    whenToUse: "Overplanning, underplanning, or plans that collapse by noon.",
    workflow: [
      "Plan My Day with fewer items.",
      "Use list view — one thing visible.",
      "Open Visual Focus when you need to think spatially.",
      "Match plan to energy via Today's Reality.",
      "Park the rest without guilt.",
    ],
    tips: ["A plan you follow beats a plan you admire."],
    keywords: ["planning", "plan", "schedule problems"],
    openSection: "plan-my-day",
    openLabel: "Open Plan My Day",
  },
  {
    id: "time-blindness",
    categoryId: "adhd-support",
    title: "Time Blindness",
    emoji: "⏳",
    whatItIs: "Making time visible when now and not-now are the only zones.",
    whenToUse: "Late starts, missed blocks, or surprise at the clock.",
    workflow: [
      "Use timers and Momentum Appointments.",
      "Put blocks on Plan My Day timeline view.",
      "Set reminders for transitions.",
      "Build buffer time — always.",
    ],
    tips: ["Visible time is an accommodation, not cheating."],
    keywords: ["time blindness", "late", "timers", "reminders"],
    openSection: "time-block",
    openLabel: "Open Calendar",
  },
  {
    id: "perfectionism",
    categoryId: "adhd-support",
    title: "Perfectionism",
    emoji: "✨",
    whatItIs: "When good enough never feels allowed — and nothing ships.",
    whenToUse: "Endless editing, avoiding publish, or all-or-nothing thinking.",
    workflow: [
      "Define done in one sentence before starting.",
      "Create a draft version on purpose — label it V1.",
      "Set a timer for good enough.",
      "Ship small — log the win.",
    ],
    tips: ["Published beats perfect in business."],
    keywords: ["perfectionism", "perfect", "ship", "good enough"],
    askPrompt: "Help me ship something I am over-editing.",
  },

  // —— Decisions ——
  {
    id: "decision-compass",
    categoryId: "decisions",
    title: "Decision Compass",
    emoji: "🧭",
    whatItIs: "Structured decision support — compare options without spinning.",
    whenToUse: "Stuck between choices or weighing tradeoffs.",
    workflow: [
      "Open Decision Compass.",
      "Name the decision plainly.",
      "Work through steps — pause anytime.",
      "Choose a next action you can take.",
    ],
    tips: ["Stopping mid-way is fine — answers are saved."],
    keywords: ["decision", "compass", "choose", "decide"],
    openActivityId: "decision-compass",
    openLabel: "Open Decision Compass",
    askPrompt: "Help me work through a decision — one question at a time.",
  },
  {
    id: "comparing-options",
    categoryId: "decisions",
    title: "Comparing Options",
    emoji: "⚖️",
    whatItIs: "Side-by-side thinking without analysis paralysis.",
    whenToUse: "Two or more paths and fear of choosing wrong.",
    workflow: [
      "List options in Decision Compass or Chat.",
      "Note tradeoffs — what you gain and give up.",
      "Set a decision deadline.",
      "Pick good enough and move one step.",
    ],
    tips: ["Most decisions are reversible — act accordingly."],
    keywords: ["compare", "options", "versus", "tradeoff"],
    openActivityId: "decision-compass",
    openLabel: "Open Decision Compass",
  },
  {
    id: "making-choices",
    categoryId: "decisions",
    title: "Making Choices",
    emoji: "✅",
    whatItIs: "Closing the loop — from thinking to a committed next step.",
    whenToUse: "You have enough info but keep re-opening the decision.",
    workflow: [
      "Ask: what is the smallest choice I can make now?",
      "Write the choice in a Project or Plan My Day.",
      "Tell Chat your decision for accountability if wanted.",
      "Act before re-litigating.",
    ],
    tips: ["Action creates information — waiting often does not."],
    keywords: ["choice", "choose", "commit", "decide"],
    openActivityId: "decision-compass",
    openLabel: "Open Decision Compass",
  },
  {
    id: "getting-unstuck",
    categoryId: "decisions",
    title: "Getting Unstuck",
    emoji: "🔓",
    whatItIs: "Breaking decision or action paralysis.",
    whenToUse: "Spinning, avoiding, or cycling the same thoughts.",
    workflow: [
      "Externalize the loop in Clear My Mind.",
      "Use Decision Compass or Chat for one clarifying question.",
      "Pick one 5-minute action — any direction.",
      "Review after acting — adjust with new info.",
    ],
    tips: ["Movement unsticks thinking faster than more thinking."],
    keywords: ["unstuck", "stuck", "paralysis", "spinning"],
    openSection: "brain-dump",
    openLabel: "Open Clear My Mind",
  },

  // —— Personalization ——
  {
    id: "account-settings",
    categoryId: "personalization",
    title: "Account & Settings",
    emoji: "👤",
    whatItIs: "Your login, profile, and account basics.",
    whenToUse: "When you need to update who you are in the app or manage your account.",
    workflow: [
      "Open Settings from the ⋯ menu.",
      "Review Profile and account details.",
      "Update email or password when needed.",
      "Changes save automatically.",
    ],
    tips: ["Account settings are separate from how the Companion talks to you."],
    keywords: ["account", "login", "profile", "email", "password"],
    openSection: "settings",
    openLabel: "Open Settings",
  },
  {
    id: "notifications",
    categoryId: "personalization",
    title: "Notifications",
    emoji: "🔔",
    whatItIs: "How and when the app reaches out — kept calm by design.",
    whenToUse: "When reminders feel too much or too little.",
    workflow: [
      "Open Settings.",
      "Review notification preferences.",
      "Turn off anything that adds pressure.",
      "Keep only what genuinely helps you return.",
    ],
    tips: ["Fewer nudges often work better for ADHD brains."],
    keywords: ["notifications", "reminders", "alerts", "nudges"],
    openSection: "settings",
    openLabel: "Open Settings",
  },
  {
    id: "personalization",
    categoryId: "personalization",
    title: "Personalization",
    emoji: "✨",
    whatItIs: "Appearance, colors, layout, and how the ecosystem feels to you.",
    whenToUse: "When the default look feels noisy or you want a calmer workspace.",
    workflow: [
      "Open Settings → Appearance.",
      "Try Adaptive Colors, Category colors, or Minimal.",
      "Adjust accent color for buttons and highlights.",
      "Save — area identity colors stay consistent for recognition.",
    ],
    tips: ["Personalization is comfort, not performance scoring."],
    keywords: ["personalize", "appearance", "colors", "layout", "theme"],
    openSettingsSection: "appearance",
    openLabel: "Open Appearance",
  },
  {
    id: "subscription",
    categoryId: "personalization",
    title: "Subscription",
    emoji: "💳",
    whatItIs: "Your plan, billing, and membership.",
    whenToUse: "When you need to review or change your subscription.",
    workflow: [
      "Open Settings.",
      "Find Subscription or Billing.",
      "Review your current plan.",
      "Contact support if something looks wrong.",
    ],
    tips: ["Your work stays yours — subscription only affects access."],
    keywords: ["subscription", "billing", "plan", "payment", "membership"],
    openSection: "settings",
    openLabel: "Open Settings",
  },
  {
    id: "privacy",
    categoryId: "conversation",
    title: "Privacy",
    emoji: "🔒",
    whatItIs: "What stays yours, what the Companion remembers, and what you control.",
    whenToUse: "When you want clarity before sharing business details.",
    workflow: [
      "Your workspace content belongs to you.",
      "Memory uses context you provide — update or remove in Settings.",
      "Nothing is shared without your action.",
      "Ask Chat directly if you want something forgotten.",
    ],
    tips: ["You can always work at the level of detail you are comfortable with."],
    keywords: ["privacy", "data", "security", "safe", "trust"],
    openSection: "settings",
    openLabel: "Open Settings",
  },
  {
    id: "cognitive-growth",
    categoryId: "personal-growth",
    title: "Cognitive Growth",
    emoji: "🧠",
    whatItIs:
      "Building confidence through reflection — wins, evidence, highlights, and story over time.",
    whenToUse: "When you want to understand why Growth matters beyond a checklist.",
    workflow: [
      "Record wins when something goes well — even small.",
      "Save evidence when you can prove impact.",
      "Add highlights when you want to remember your value.",
      "Review monthly with Growth Reports.",
    ],
    tips: [
      "Reflection trains your brain to notice progress — that is the cognitive growth loop.",
    ],
    keywords: ["cognitive growth", "reflection", "confidence", "growth mindset"],
    openSection: "growth",
    openLabel: "Open Growth",
  },
  {
    id: "ecosystem-search",
    categoryId: "workspace",
    title: "Search",
    emoji: "🔍",
    whatItIs: "Find areas, help articles, strategies, and tools from one search box.",
    whenToUse: "When you know what you want but not where it lives.",
    workflow: [
      "Use Search Help at the top of How Do I.",
      "Type a feature name, area, or question.",
      "Pick a result — help articles open right here without leaving.",
      "Use area results to jump to a workspace when you are ready.",
    ],
    tips: ["Search opens the right dropdown and article for help topics."],
    keywords: ["search", "find", "lookup", "help search"],
    openSection: "how-do-i",
    openLabel: "Open How Do I",
  },
  {
    id: "growth-uploads",
    categoryId: "personal-growth",
    title: "Uploads",
    emoji: "📎",
    whatItIs: "Attach files and images to wins, evidence, highlights, and journey entries.",
    whenToUse: "When proof lives in a screenshot, PDF, or photo.",
    workflow: [
      "Open a Growth area — Wins, Evidence, My Highlights, or My Journey.",
      "Use Attach File or Upload Image in the header or on an entry.",
      "Preview attachments before printing or reporting.",
      "Growth Reports can include your uploads in combined exports.",
    ],
    tips: ["A photo of a thank-you email counts as evidence."],
    keywords: ["upload", "attach", "file", "image", "photo", "pdf"],
    openSection: "growth",
    openLabel: "Open Growth",
  },
  {
    id: "client-avatars",
    categoryId: "personalization",
    title: "Audience Profile",
    emoji: "👥",
    featured: true,
    whatItIs: "Who you help — so messaging and Create stay personal.",
    whenToUse: "Generic content or new offer positioning.",
    workflow: [
      "Open Create → Audience Profile.",
      "Define your ideal client step by step.",
      "Set a primary audience for generation.",
      "Edit as your offer evolves.",
    ],
    tips: ["Write for one person — many will still relate."],
    keywords: ["avatar", "client", "audience", "audience profile"],
    openSection: "client-avatars",
    openLabel: "Open Audience Profile",
  },
  {
    id: "settings-personalization",
    categoryId: "personalization",
    title: "Settings",
    emoji: "⚙️",
    featured: true,
    whatItIs: "Appearance, profile, business context, and preferences.",
    whenToUse: "Setup, visual overwhelm, or updating your context.",
    workflow: [
      "Open Settings from the header.",
      "Adjust appearance and profile.",
      "Update Business Profile for better suggestions.",
      "Save — nothing else changes until you act.",
    ],
    tips: ["Personalization improves guidance — it does not automate your work."],
    keywords: ["settings", "personalize", "setup"],
    openSection: "settings",
    openLabel: "Open Settings",
  },
  {
    id: "adaptive-colors",
    categoryId: "personalization",
    title: "Adaptive Colors",
    emoji: "🎨",
    whatItIs: "Interface colors that shift with context — support, focus, celebration.",
    whenToUse: "When you want mood-matched visuals.",
    workflow: [
      "Open Settings → Appearance.",
      "Choose Adaptive Colors.",
      "Preview and save.",
      "Switch to Category or Minimal if preferred.",
    ],
    tips: ["Colors are comfort — pick what reduces noise for you."],
    keywords: ["adaptive", "colors", "appearance", "dynamic"],
    openSettingsSection: "appearance",
    openLabel: "Open Appearance",
  },
  {
    id: "language-settings",
    categoryId: "personalization",
    title: "Language Settings",
    emoji: "🌐",
    whatItIs: "How the Companion communicates — tone and language preferences.",
    whenToUse: "When phrasing feels off or you want a different voice.",
    workflow: [
      "Open Settings.",
      "Review language and communication preferences.",
      "Tell Chat directly how you want to be spoken to.",
      "Save changes you want to keep.",
    ],
    tips: ["You can always ask Chat to adjust tone in the moment."],
    keywords: ["language", "tone", "communication"],
    openSection: "settings",
    openLabel: "Open Settings",
  },
  {
    id: "roman-urdu",
    categoryId: "personalization",
    title: "Roman Urdu",
    emoji: "🇵🇰",
    whatItIs: "Conversation and content in Roman Urdu when that is how you think best.",
    whenToUse: "Bilingual workflow or more natural expression in Urdu.",
    workflow: [
      "Tell Chat you prefer Roman Urdu.",
      "Use voice or text in the language that flows.",
      "Create drafts bilingual if your audience needs both.",
      "Save snippets in either language.",
    ],
    tips: ["Use the language that lowers friction — not the one that impresses."],
    keywords: ["urdu", "roman urdu", "bilingual", "language"],
    askPrompt: "Please communicate with me in Roman Urdu when I ask.",
  },
  {
    id: "accessibility",
    categoryId: "personalization",
    title: "Accessibility",
    emoji: "♿",
    whatItIs: "Readable text, touch targets, and calmer layouts.",
    whenToUse: "Visual strain, motor differences, or sensory overload.",
    workflow: [
      "Open Settings → Appearance.",
      "Try Minimal colors for less visual noise.",
      "Use voice input when typing is hard.",
      "Ask Chat to summarize long content.",
    ],
    tips: ["Accessibility features are productivity features."],
    keywords: ["accessibility", "readable", "a11y", "contrast"],
    openSettingsSection: "appearance",
    openLabel: "Open Appearance",
  },
  {
    id: "voice-preferences",
    categoryId: "personalization",
    title: "Voice Preferences",
    emoji: "🔊",
    whatItIs: "How you use voice — input, output, and when to type instead.",
    whenToUse: "Setting up voice workflow or reducing typing load.",
    workflow: [
      "Use mic in Chat or Clear My Mind.",
      "Review transcripts before saving.",
      "Combine voice capture with written editing.",
      "Adjust when voice feels faster vs clearer.",
    ],
    tips: ["Voice for speed — text for precision."],
    keywords: ["voice", "speech", "microphone", "audio"],
    openSection: "brain-dump",
    openLabel: "Open Clear My Mind",
  },
  {
    id: "views-layouts",
    categoryId: "personalization",
    title: "Views & Layouts",
    emoji: "🖼️",
    whatItIs: "Plan My Day views, split chat/workspace, and how panels arrange.",
    whenToUse: "When the default layout fights your brain.",
    workflow: [
      "Try List, Kanban, Timeline, or Cards in Plan My Day.",
      "Open Visual Focus for mind maps and spatial thinking.",
      "Use split mode — chat plus workspace.",
      "Collapse sections you are not using.",
      "Return to How Do I when lost.",
    ],
    tips: ["Layout is a tool — change it without guilt."],
    keywords: ["view", "layout", "kanban", "split", "visual"],
    openSection: "plan-my-day",
    openLabel: "Open Plan My Day",
  },
];
