import type { GrowthDomainContract } from "./growthDomainContract";

/**
 * Expert Growth Strategy Intelligence pack — Phase 4C.
 * Consumed by the shared judgment engine via StrategyTypeContract bridge.
 * Growth is useful only when it strengthens the business without undermining
 * delivery, trust, sustainability, focus, or founder capacity.
 */
export const growthDomainIntelligence: GrowthDomainContract = {
  id: "growth",
  name: "Growth Strategy",
  description:
    "Decide how — or whether — to grow by diagnosing the real constraint, not assuming more customers or marketing is always the answer.",
  useWhen: [
    "Growth feels stalled, uneven, or unclear",
    "The business wants more customers or revenue",
    "Unsure whether acquisition, retention, pricing, offers, or capacity matter most",
    "Considering expansion, new markets, new offers, or hiring to grow",
    "Asking how fast to grow — or whether to stay small",
    "Wondering what is holding growth back",
    "Feeling pressure to grow without a clear reason",
  ],
  avoidWhen: [
    "The real need is only emotional recovery (Talk It Out first)",
    "Need is a finished marketing campaign with the growth decision already made",
    "Need is detailed cash-flow forecasting without a growth question (Finance)",
    "Need is only writing launch copy after direction is clear (Create)",
  ],
  entrySignals: [
    /\b(grow|growth|more customers|more revenue|scale|expand|not growing|stopped growing|acquisition|leads|pipeline|how (do|can) i grow)\b/i,
    /\b(ready to scale|stay small|narrow before|holding back growth|grow fast|another market|another offer)\b/i,
    /\b(referrals?|retention|repeat (purchase|business)|partnership.*grow|hire.*(grow|growth))\b/i,
  ],
  possibleUnderlyingQuestions: [
    "Is awareness too low — or is the audience poorly defined?",
    "Is positioning or the offer unclear?",
    "Are qualified leads failing to convert?",
    "Are current customers leaving too quickly?",
    "Is revenue per customer too low?",
    "Are referrals underused?",
    "Does the business have capacity for more demand?",
    "Would fewer higher-value customers fit better?",
    "Is cash timing the real issue disguised as a growth ask?",
    "Has the founder reached a delivery ceiling?",
    "Is this a normal plateau rather than failure?",
    "Does the business need refinement rather than expansion?",
    "Is growth still the right goal this season?",
    "Would maintaining the current size serve the founder better?",
    "Is hiring required — or would simplification free capacity?",
  ],
  requiredContext: [
    "what “growth” would change if it worked",
    "whether the pain is customers, revenue, retention, capacity, or something else",
    "current delivery and founder capacity for more demand",
    "what already brings customers or revenue today",
  ],
  optionalContext: [
    "conversion and inquiry patterns",
    "retention and churn signals",
    "channel performance",
    "offer mix and average customer value",
    "margin and cash pressure",
    "why growth feels urgent now",
    "personal or seasonal constraints",
  ],
  importantContext: [
    "desired outcome of growth",
    "current demand sources",
    "capacity to deliver more",
    "retention health",
    "what has already been tried",
  ],
  commonFacts: [
    "Where new customers currently come from",
    "Whether delivery is already strained",
    "Whether retention is stable or leaking",
    "Whether more than one offer is active",
    "Whether growth is a stated goal or an assumed obligation",
  ],
  commonObservations: [
    "Inquiries arrive but rarely convert",
    "Social attention rises while sales stay flat",
    "New customers create delivery chaos",
    "Churn offsets acquisition wins",
    "Many offers are half-built and few are strong",
    "The founder feels they “should” grow",
  ],
  commonInterpretations: [
    "More customers will fix revenue",
    "Marketing is always the missing piece",
    "A plateau means the business is failing",
    "Rapid growth is always healthier",
    "Expansion is better than focus",
    "Social engagement proves demand",
  ],
  commonAssumptions: [
    "More customers fix everything",
    "More revenue means healthier growth",
    "Marketing is always the answer",
    "Rapid growth is always desirable",
    "Every business should scale",
    "The founder has capacity for more demand",
    "Acquisition matters more than retention",
    "Expansion is better than focus",
    "Awareness is the only gap",
    "Every channel should run at once",
    "Hiring is required before any growth",
    "One successful campaign proves a growth system",
    "Staying small means lack of ambition",
  ],
  commonUnknowns: [
    "Which constraint is primary right now",
    "Whether demand would hold after a focused test",
    "Whether current customers would refer",
    "Whether capacity can absorb even limited growth",
    "Whether the growth goal still fits the founder’s life",
  ],
  commonConcerns: [
    "Fear of falling behind",
    "Fear of missing opportunities",
    "Fear that staying small is wrong",
    "Fear of growing into burnout",
    "Fear of choosing the wrong market or offer",
  ],
  commonOpportunities: [
    "Strengthen retention before acquisition",
    "Grow through referrals from satisfied customers",
    "Narrow to one customer group",
    "Increase value per customer rather than volume",
    "Stabilize delivery before expanding demand",
    "Test one channel or segment with a clear boundary",
    "Maintain current size intentionally",
    "Simplify offers so growth has room later",
  ],
  commonConstraints: [
    "Founder delivery bandwidth",
    "Team or support capacity",
    "Cash available for experiments",
    "Quality standards that must not slip",
    "Focus across too many offers already",
  ],
  evidencePrompts: [
    "What evidence shows acquisition is the bottleneck — not retention, offer, or capacity?",
    "Where do people drop off today?",
    "What do retained customers say made them stay?",
    "If more people said yes tomorrow, could you deliver well?",
    "Which signals are confirmed results, and which are excitement or fear?",
  ],
  heuristics: [
    "Diagnose the growth constraint before choosing the growth tactic.",
    "More customers are not useful when delivery cannot support them.",
    "Retaining strong customers may be more valuable than constantly replacing them.",
    "Growth should improve the business, not merely increase activity.",
    "Revenue growth that reduces profit, quality, or capacity may be unhealthy.",
    "Growth through focus can be stronger than growth through expansion.",
    "A clear offer for a narrower audience may outperform a broad offer for everyone.",
    "Existing customers are often the best source of evidence about future growth.",
    "Growth channels should be evaluated by customer quality and sustainability, not only volume.",
    "Every new offer creates delivery and maintenance obligations.",
    "A business may need operational stability before demand growth.",
    "Growth should not depend on the founder consistently working at maximum capacity.",
    "A plateau may signal a constraint, a normal phase, or a need for refinement — not necessarily failure.",
    "Growth can come from better value, retention, pricing, focus, or efficiency — not only customer acquisition.",
    "Maintaining the current size is valid when it best serves the founder’s goals.",
    "If the key growth assumption can be tested cheaply, test before expanding.",
  ],
  warningSigns: [
    "Busy marketing, flat results",
    "Good conversations that do not convert",
    "New customers create chaos",
    "Churn offsets every acquisition win",
    "Social growth without sales growth",
    "Many new offers started, few completed",
    "Pressure to grow without a named outcome",
  ],
  readinessAreas: [
    "offer clarity",
    "demonstrated demand",
    "customer outcomes",
    "delivery reliability",
    "operational consistency",
    "financial capacity",
    "team capacity",
    "founder capacity",
    "support capacity",
    "quality control",
    "customer experience",
    "retention",
    "repeatable acquisition",
    "adequate margins",
    "systems and processes",
    "decision-making bandwidth",
    "recovery and buffer capacity",
  ],
  readinessConclusions: [
    "ready_for_focused_growth",
    "ready_for_limited_experiment",
    "ready_to_improve_retention_first",
    "ready_to_strengthen_positioning_first",
    "ready_to_stabilize_delivery_first",
    "ready_to_simplify_before_growing",
    "needs_more_evidence",
    "current_scale_appropriate",
    "growth_not_immediate_priority",
  ],
  diagnosisAreas: [
    "awareness",
    "audience_fit",
    "positioning",
    "offer_relevance",
    "pricing",
    "trust",
    "lead_quality",
    "lead_volume",
    "conversion",
    "retention",
    "repeat_purchase",
    "referrals",
    "customer_outcomes",
    "delivery_capacity",
    "operational_capacity",
    "founder_capacity",
    "team_capacity",
    "financial_capacity",
    "channel_effectiveness",
    "market_timing",
    "competitive_pressure",
    "seasonality",
    "business_model_fit",
  ],
  growthTypesSupported: [
    "customer_growth",
    "revenue_growth",
    "profit_growth",
    "retention_growth",
    "repeat_purchase_growth",
    "referral_growth",
    "audience_growth",
    "market_share_growth",
    "offer_expansion",
    "geographic_expansion",
    "channel_expansion",
    "capacity_growth",
    "team_growth",
    "partnership_led_growth",
    "recurring_revenue_growth",
    "customer_value_growth",
    "operational_maturity",
    "strategic_simplification",
  ],
  constraintCategories: [
    "demand_constraint",
    "audience_constraint",
    "positioning_constraint",
    "offer_constraint",
    "trust_constraint",
    "sales_constraint",
    "retention_constraint",
    "pricing_constraint",
    "delivery_constraint",
    "founder_capacity_constraint",
    "team_constraint",
    "financial_constraint",
    "channel_constraint",
    "operational_constraint",
    "focus_constraint",
    "evidence_constraint",
  ],
  capacityChecks: [
    "If growth worked tomorrow, could you deliver well?",
    "Would more demand create hidden maintenance you cannot carry?",
    "Does growth depend on you working at maximum capacity forever?",
    "Would quality, trust, or support slip if volume rose?",
    "Is buffer capacity available for experiments without breaking current customers?",
  ],
  optionPatterns: [
    "narrow",
    "improve",
    "protect_current_base",
    "stabilize",
    "test",
    "expand",
    "simplify",
    "delay",
    "pause",
    "stop",
    "maintain_current_direction",
    "increase_price",
    "add_value",
    "partner",
    "delegate",
  ],
  strategicOptionPatterns: [
    "Strengthen the current offer before expanding",
    "Focus on a narrower customer group",
    "Improve retention before acquisition",
    "Increase value per customer",
    "Increase prices rather than volume",
    "Grow through referrals",
    "Grow through partnerships",
    "Test one new acquisition channel",
    "Improve conversion of existing leads",
    "Simplify the customer journey",
    "Create a recurring-revenue path",
    "Expand the strongest offer",
    "Retire weak offers and focus resources",
    "Build delivery capacity before increasing demand",
    "Hire or delegate selectively",
    "Standardize delivery",
    "Stage growth over time",
    "Enter a new segment through a pilot",
    "Maintain the current size",
    "Stabilize before growing",
    "Pause expansion",
    "Stop an unproductive growth effort",
  ],
  growthPathCategories: [
    "acquire more customers",
    "retain more customers",
    "increase customer value",
    "improve conversion",
    "expand the offer",
    "expand the market",
    "strengthen referrals",
    "strengthen partnerships",
    "increase delivery capacity",
    "simplify and focus",
    "stabilize",
    "maintain current size",
  ],
  tradeoffDimensions: [
    "revenue",
    "profit",
    "customer quality",
    "speed",
    "acquisition cost",
    "retention",
    "founder time",
    "founder energy",
    "delivery quality",
    "customer trust",
    "operational complexity",
    "team burden",
    "focus",
    "support burden",
    "cash requirements",
    "channel dependence",
    "brand clarity",
    "flexibility",
    "learning",
    "sustainability",
    "maintenance",
    "risk concentration",
  ],
  opportunityCostPrompts: [
    "Which current work would receive less attention?",
    "Which offer would be neglected?",
    "What quality might be at risk?",
    "What investment would be delayed?",
    "What personal capacity would be consumed?",
    "What future flexibility would be reduced?",
    "What becomes possible by declining this growth path?",
    "Would growth crowd out stabilization, recovery, or simplification?",
  ],
  riskPatterns: [
    "Growing demand beyond delivery capacity",
    "Declining customer experience",
    "Founder burnout",
    "Team overload",
    "Weak margins despite higher volume",
    "Cash-flow strain",
    "Increasing complexity",
    "Poor-fit customers",
    "Channel dependence",
    "Customer concentration",
    "Growth hiding retention problems",
    "New offers distracting from strong existing offers",
    "Premature hiring",
    "Loss of strategic focus",
    "Expanding before validating",
    "Rapid growth followed by instability",
  ],
  reversibilityGuidance: [
    "Easily reversible: testing one referral process",
    "Easily reversible: trying one channel for a fixed period",
    "Easily reversible: piloting a focused offer",
    "Easily reversible: interviewing a new customer segment",
    "Easily reversible: running a limited retention experiment",
    "Easily reversible: narrowing a campaign temporarily",
    "Moderately reversible: increasing marketing investment",
    "Moderately reversible: adding a contractor",
    "Moderately reversible: launching a new offer",
    "Moderately reversible: entering a secondary customer segment",
    "Moderately reversible: adding a recurring option",
    "Moderately reversible: increasing delivery capacity",
    "Difficult to reverse: hiring a larger permanent team",
    "Difficult to reverse: opening a physical location",
    "Difficult to reverse: entering a major long-term partnership",
    "Difficult to reverse: expanding into a new geographic market",
    "Difficult to reverse: changing the core business model",
    "Difficult to reverse: building substantial infrastructure",
    "Difficult to reverse: repositioning the entire company",
    "Difficult to reverse: committing to large fixed costs",
  ],
  experimentPatterns: [
    "Test one channel or segment before broad expansion",
    "Improve conversion on existing traffic before buying more attention",
    "Run a referral ask with happy customers for 30 days",
    "Stabilize delivery for one season before expanding",
    "Tailor the current offer to one defined segment for 30 days",
    "Improve one retention touchpoint and track renewals",
    "Present one limited offer before building full delivery",
    "Limit new customers temporarily and observe quality and energy",
  ],
  experimentBlueprints: [
    {
      id: "referral_experiment",
      name: "Referral experiment",
      assumption:
        "Satisfied customers will introduce qualified prospects when asked clearly.",
      strategicQuestion: "Can referrals produce better-fit growth than new acquisition?",
      action: "Ask a defined group of satisfied customers for introductions.",
      scope: "A bounded set of current customers only",
      durationOrReview: "After a fixed number of requests or 30 days",
      evidence: ["response rate", "customer fit", "conversion"],
      successSignal: "Qualified introductions that convert without delivery strain.",
      stopSignal: "Poor-fit leads, awkward asks, or no useful learning.",
      capacityLimit: "Do not accept more new customers than delivery can hold.",
      nextDecision: "Whether to systematize referrals, refine the ask, or choose another path.",
      typicalReversibility: "easily_reversible",
    },
    {
      id: "narrow_market_experiment",
      name: "Narrow-market experiment",
      assumption:
        "A clearer offer for one segment will outperform a broad message for everyone.",
      strategicQuestion: "Does focus unlock demand better than broader reach?",
      action: "Tailor the current offer to one defined customer segment.",
      scope: "One segment; messaging and demand test only",
      durationOrReview: "30 days",
      evidence: ["interest quality", "conversion", "clarity of conversations"],
      successSignal: "Stronger conversations and better-fit interest.",
      stopSignal: "Confusion increases or the segment shows weak demand.",
      capacityLimit: "Do not build a second full offer while testing.",
      nextDecision: "Narrow permanently, refine the segment, or return to a broader path.",
      typicalReversibility: "easily_reversible",
    },
    {
      id: "retention_experiment",
      name: "Retention experiment",
      assumption:
        "Improving one customer-experience point will reduce churn more than adding leads.",
      strategicQuestion: "Is retention the higher-leverage growth move?",
      action: "Improve one point in the customer experience.",
      scope: "One touchpoint for current customers",
      durationOrReview: "One renewal or engagement cycle",
      evidence: ["renewal", "repeat purchase", "engagement", "complaints"],
      successSignal: "Retention or repeat purchase improves without added chaos.",
      stopSignal: "No change and no clearer diagnosis after the cycle.",
      capacityLimit: "Do not launch a full acquisition push during the test.",
      nextDecision: "Keep improving retention, combine with acquisition, or revise the offer.",
      typicalReversibility: "easily_reversible",
    },
    {
      id: "offer_demand_experiment",
      name: "Offer-demand experiment",
      assumption:
        "Qualified interest can be tested before full delivery is built.",
      strategicQuestion: "Is there real demand for this growth path before we expand?",
      action: "Present one limited offer before building full delivery.",
      scope: "Limited audience; pre-commitment or waitlist interest",
      durationOrReview: "Until a small set of qualified responses or 30 days",
      evidence: ["qualified interest", "commitments", "questions asked"],
      successSignal: "Enough qualified interest to justify next investment.",
      stopSignal: "Weak interest or interest that would break capacity.",
      capacityLimit: "Do not promise delivery you cannot support.",
      nextDecision: "Build, reshape, delay, or stop the offer path.",
      typicalReversibility: "easily_reversible",
    },
    {
      id: "conversion_experiment",
      name: "Conversion experiment",
      assumption:
        "Improving one decision point will grow results without more traffic.",
      strategicQuestion: "Is conversion the constraint rather than awareness?",
      action: "Improve one decision point in the sales journey.",
      scope: "One step only — not a full funnel rebuild",
      durationOrReview: "After a defined number of prospects or 30 days",
      evidence: ["conversion rate", "objection patterns", "deal quality"],
      successSignal: "Conversion improves with acceptable customer fit.",
      stopSignal: "No learning, or conversion rises while fit worsens.",
      capacityLimit: "Keep delivery promises unchanged during the test.",
      nextDecision: "Keep the change, test another step, or revisit the offer.",
      typicalReversibility: "moderately_reversible",
    },
    {
      id: "partnership_experiment",
      name: "Partnership experiment",
      assumption:
        "One bounded partner activity can reveal whether partnership-led growth fits.",
      strategicQuestion: "Can partnerships produce quality growth without overload?",
      action: "Run one co-hosted or referral activity with a partner.",
      scope: "One activity with clear roles and end date",
      durationOrReview: "After the activity and follow-through window",
      evidence: ["lead quality", "fit", "workload", "follow-through"],
      successSignal: "Good-fit leads with manageable workload.",
      stopSignal: "Poor fit, uneven follow-through, or unsustainable load.",
      capacityLimit: "One partnership experiment at a time.",
      nextDecision: "Deepen, redesign, or decline partnership growth.",
      typicalReversibility: "moderately_reversible",
    },
    {
      id: "capacity_experiment",
      name: "Capacity experiment",
      assumption:
        "Limiting new customers will reveal whether quality and energy recover.",
      strategicQuestion: "Is capacity the real constraint on healthy growth?",
      action: "Limit new customers temporarily.",
      scope: "New intake only; current customers continue",
      durationOrReview: "2–4 weeks or one delivery cycle",
      evidence: ["delivery quality", "energy", "operational load", "customer experience"],
      successSignal: "Quality and capacity stabilize with clearer priorities.",
      stopSignal: "Cash harm without learning, or chaos continues unchanged.",
      capacityLimit: "Define a hard maximum for new starts.",
      nextDecision: "Stabilize longer, raise prices, simplify, or grow carefully.",
      typicalReversibility: "easily_reversible",
    },
    {
      id: "channel_experiment",
      name: "Channel experiment",
      assumption:
        "One bounded channel test can show quality of customers, not only lead volume.",
      strategicQuestion: "Does this channel create sustainable, good-fit demand?",
      action: "Test one acquisition channel with a clear time and cost boundary.",
      scope: "One channel only",
      durationOrReview: "Fixed period and budget",
      evidence: ["lead quality", "conversion", "delivery fit", "cost vs value"],
      successSignal: "Good-fit customers within cost and capacity limits.",
      stopSignal: "High volume of poor-fit leads or costs beyond value.",
      capacityLimit: "Stop when delivery or budget bound is hit.",
      nextDecision: "Scale the channel, change it, or stop.",
      typicalReversibility: "easily_reversible",
    },
  ],
  successSignals: [
    "More qualified customers",
    "Improved retention",
    "Improved customer outcomes",
    "Stronger conversion",
    "Increased average customer value",
    "Healthier margins",
    "Stable delivery quality",
    "Manageable support burden",
    "Founder capacity remains sustainable",
    "Referral quality improves",
    "Customer fit improves",
    "Fewer offers produce stronger results",
    "Growth does not increase harmful complexity",
    "The business retains strategic focus",
  ],
  stopSignals: [
    "Quality declines",
    "Customer complaints increase",
    "Delivery delays grow",
    "Founder health or capacity deteriorates",
    "Team overload becomes persistent",
    "Acquisition costs rise beyond value",
    "Customer fit worsens",
    "Retention declines",
    "Margin deteriorates",
    "Support burden overwhelms gains",
    "Channel results are low quality",
    "New offer distracts from the core business",
    "Growth creates excessive complexity",
    "The experiment does not answer the strategic question",
    "Cash demands exceed safe capacity",
  ],
  reviewTriggers: [
    "Delivery capacity changes",
    "Retention changes",
    "Customer demand shifts",
    "A major channel weakens",
    "An experiment ends",
    "Customer quality changes",
    "Margins change",
    "The founder’s capacity changes",
    "Team capacity changes",
    "The business reaches a planned threshold",
    "A new offer becomes material",
    "A major customer is gained or lost",
    "Market conditions shift",
    "Growth begins affecting customer experience",
    "The current growth goal no longer fits the founder’s priorities",
  ],
  recommendedPerspectives: ["strategy", "customer", "operations", "finance"],
  recommendedDestinations: [
    "project",
    "create",
    "board",
    "business_estate",
    "execution_manager",
    "talk_it_out",
  ],
  possibleSecondaryDomains: [
    "pricing",
    "offer",
    "market_customer",
    "capacity_focus",
    "hiring_delegation",
    "partnership",
    "business_direction",
  ],
  routingBoundaries: [
    {
      owner: "growth_strategy",
      owns:
        "Growth type, constraint diagnosis, readiness, path comparison, trade-offs, experiments, recommendation",
      when: "A strategic growth question is open",
    },
    {
      owner: "marketing",
      owns: "Campaigns, content strategy, channel execution, lead-generation implementation, public messaging",
      when: "Strategic direction is clear enough to execute",
    },
    {
      owner: "finance",
      destinationId: "business_estate",
      owns: "Growth forecasts, cash-flow, acquisition economics, margin analysis, investment affordability",
      when: "Numbers need precise modeling after direction emerges",
    },
    {
      owner: "offer",
      owns: "Detailed offer architecture, packaging, offer development, offer retirement design",
      when: "Offer design is the material next need",
    },
    {
      owner: "customer_and_market",
      owns: "Deeper segmentation, positioning, customer research, market choice",
      when: "Market or customer definition needs deeper work",
    },
    {
      owner: "capacity_and_focus",
      owns: "Priority reduction, workload design, overcommitment, active-work limits",
      when: "Capacity or focus is the binding constraint",
    },
    {
      owner: "hiring_and_delegation",
      owns: "Role design, delegation preparation, hiring decisions, management readiness",
      when: "Growth truly depends on people capacity",
    },
    {
      owner: "projects",
      destinationId: "project",
      owns: "Implementation planning after a growth direction is chosen",
      when: "Execution needs coordination",
    },
    {
      owner: "execution_manager",
      destinationId: "execution_manager",
      owns: "Sequencing and follow-through",
      when: "A chosen path needs sustained execution",
    },
    {
      owner: "board",
      destinationId: "board",
      owns: "High-impact growth decisions — risk, finance, customer, founder capacity, challenge",
      when: "Impact is high or reversibility is low",
    },
    {
      owner: "talk_it_out",
      destinationId: "talk_it_out",
      owns: "Fear of success, comparison, pressure to grow, identity or emotional conflict",
      when: "Emotion is blocking clear judgment",
    },
    {
      owner: "create",
      destinationId: "create",
      owns: "Pages, scripts, and offer documents after strategic direction",
      when: "Artifacts are needed after the choice",
    },
  ],
  adaptivePresentationNotes:
    "Fewer Choices: one leading path and up to two alternatives. One Step at a Time: one constraint or path at a time. Summary First: state the likely growth constraint first. More Structure: compact growth-path comparison. Let Me Talk Freely: describe what feels stalled before narrowing. Give Me Examples: one relevant example. Big Picture: diagnose → choose path → test → review. Never reduce reasoning quality. Never default to expand or Marketing tactics. Maintain-current-size and stabilize-first remain valid.",
  qualityChecks: [
    "Acquisition is not assumed by default",
    "Marketing handoff is not automatic",
    "Capacity checked before expand",
    "Bottleneck named (not only “get more customers”)",
    "Maintain current size is allowed",
    "Stabilize-first is allowed",
    "Retention-first is allowed when retention leaks",
    "Revenue alone is not treated as sufficient success",
    "Social engagement is not treated as buying evidence",
    "Recommendation is never marked as confirmed decision",
    "≤3 meaningfully different options — not channel tactics",
    "Do not grow yet is a valid conclusion",
  ],
  maintenanceNotes: [
    "Deepen from live Growth conversations — Rule of Three before prompt changes.",
    "Do not grow into a second growth engine.",
    "Keep OptionPatternId and Reversibility unions canonical.",
    "Next domain after certification: Offer Strategy (separate milestone).",
    "When adding constraint nuance, prefer helpers in growthIntelligence.ts.",
  ],
  strategyTypeBridge: {
    name: "Growth Strategy",
    family: "customer_and_market",
    plainLanguageDescription:
      "Decide how — or whether — to grow by diagnosing the real bottleneck, not assuming more customers is always the answer.",
    useWhen: [
      "Growth feels stalled or uneven",
      "The business wants more customers or revenue",
      "Capacity may not support more demand",
      "Unsure whether the issue is awareness, offer, sales, or retention",
      "Considering expansion, new markets, or whether to stay small",
    ],
    doNotUseWhen: [
      "The real need is emotional recovery only",
      "Need is only campaign execution with the growth decision already made",
    ],
    entrySignals: [
      /\b(grow|growth|more customers|more revenue|scale|expand|not growing|stopped growing|acquisition|leads|pipeline|how (do|can) i grow)\b/i,
      /\b(ready to scale|stay small|narrow before|holding back growth|grow fast|another market|another offer)\b/i,
      /\b(referrals?|retention|repeat (purchase|business)|partnership.*grow|hire.*(grow|growth))\b/i,
    ],
    clarifyingQuestions: [
      "When you say growth, what would actually feel like progress?",
      "Is the real decision about more customers, more revenue, better retention, or something else?",
      "Which part feels stuck — awareness, positioning, offer, sales, retention, or capacity?",
    ],
    currentStateQuestions: [
      "What growth approaches have you already tried?",
      "Where does demand currently come from?",
      "If more people said yes tomorrow, could you deliver well?",
    ],
    directionQuestions: [
      "What kind of growth would still feel sustainable?",
      "What should not be sacrificed for growth?",
      "Would “don’t grow yet” be the honest answer this season?",
    ],
    optionPatterns: [
      "expand",
      "narrow",
      "protect_current_base",
      "improve",
      "stabilize",
      "test",
      "delay",
      "simplify",
      "pause",
      "stop",
      "maintain_current_direction",
      "add_value",
      "partner",
      "delegate",
    ],
    decisionCriteria: [
      "bottleneck diagnosis",
      "capacity",
      "retention",
      "unit economics",
      "focus",
      "timing",
      "founder sustainability",
      "evidence quality",
    ],
    commonTradeoffs: [
      "acquisition vs retention",
      "speed vs delivery quality",
      "expansion vs focus",
      "referral systems vs paid reach",
      "volume vs customer value",
      "growth vs founder capacity",
    ],
    commonRisks: [
      "overpromising delivery",
      "chasing vanity growth",
      "growing into a capacity crisis",
      "fixing awareness when the offer is weak",
      "growth hiding retention problems",
    ],
    commonAssumptions: [
      "more customers fix everything",
      "awareness is the only gap",
      "growth must happen now",
      "every channel should run at once",
      "marketing is always the answer",
      "staying small means lack of ambition",
    ],
    evidencePrompts: [
      "What evidence shows acquisition is the bottleneck?",
      "Where do people drop off today?",
      "What do retained customers say made them stay?",
      "Which signals are confirmed results versus excitement or fear?",
    ],
    capacityChecks: [
      "If growth worked, could you deliver well?",
      "Would more demand create hidden maintenance you cannot carry?",
      "Does growth require you at maximum capacity forever?",
    ],
    experimentPatterns: [
      "Test one channel or segment before broad expansion",
      "Improve conversion on existing traffic before buying more attention",
      "Run a referral ask with happy customers for 30 days",
      "Stabilize delivery for one season before expanding",
      "Limit new customers temporarily and observe quality",
    ],
    successSignals: [
      "Sustainable new demand",
      "Delivery stays steady",
      "Clearer diagnosis of the real bottleneck",
      "Better-fit customers",
      "Retention holds or improves",
    ],
    reviewTriggers: [
      "Delivery strain",
      "Cash pressure",
      "Retention drop",
      "Lead quality falls",
      "Experiment end",
      "Founder capacity changes",
    ],
    recommendedChamberMembers: ["strategy", "marketing"],
    recommendedBoardRoles: ["strategy-director", "growth-opportunity"],
    handoffDestinations: [
      "project",
      "create",
      "board",
      "business_estate",
      "execution_manager",
      "talk_it_out",
    ],
    adaptivePresentationNotes:
      "Do not default to expand; include stabilize / wait / don’t grow yet when capacity is tight. Adaptive Companion changes presentation, not reasoning quality.",
    qualityChecks: [
      "Capacity checked before expand",
      "Bottleneck named (not only “get more customers”)",
      "Maintain current size allowed",
      "No automatic Marketing handoff",
      "Revenue alone not sufficient success",
    ],
    decisionHeuristics: [
      {
        id: "diagnose_before_scale",
        rule: "Name the bottleneck before choosing a growth tactic.",
        when: "Member asks for more customers without diagnosing the funnel",
      },
      {
        id: "dont_grow_yet",
        rule: "“Don’t grow yet” is a valid strategic conclusion when capacity or offer is weak.",
        when: "Delivery is strained or the offer is unclear",
      },
      {
        id: "retention_before_acquisition",
        rule: "Fix leaky retention before pouring more acquisition.",
        when: "People leave soon after buying",
      },
      {
        id: "one_lever",
        rule: "Change one growth lever at a time so learning is clear.",
        when: "Many channels and offers are already active",
      },
      {
        id: "maintain_size_valid",
        rule: "Maintaining the current size is a valid strategy — not lack of ambition.",
        when: "Pressure to grow conflicts with capacity, quality, or values",
      },
      {
        id: "focus_before_expand",
        rule: "Strengthen or narrow before launching many new offers.",
        when: "Multiple new offers are proposed as the growth plan",
      },
      {
        id: "quality_over_volume",
        rule: "Evaluate channels by customer quality and sustainability, not only volume.",
        when: "Lead volume is rising but results are weak",
      },
    ],
    hiddenUnderlyingQuestions: [
      "Which bottleneck is real — awareness, positioning, offer, sales, retention, or capacity?",
      "If growth worked tomorrow, could delivery hold?",
      "Is “more customers” the goal, or more revenue, retention, or relief?",
      "Would not growing yet be the honest answer this season?",
      "Would maintaining the current size serve the founder better?",
    ],
    recommendationRules: [
      "Diagnose the bottleneck before recommending acquisition tactics.",
      "Prefer stabilize or delay when capacity is the constraint.",
      "Prefer retention repair before pouring more acquisition into a leaky base.",
      "“Do not grow yet” is a valid recommendation.",
      "Maintaining current size is a valid strategic option.",
      "Do not hand to Marketing while the diagnosis is still only “more customers.”",
      "Recommendation is never the confirmed decision.",
    ],
    handoffBoundaries: [
      "Stay in Strategy until the growth bottleneck is named.",
      "Do not hand to Create/marketing execution while the diagnosis is still “more customers.”",
      "Finance/Business Estate for forecasts and acquisition economics after direction emerges.",
      "Offer / Customer and Market / Capacity / Hiring only when that domain is material.",
      "Project handoff only after a bounded growth experiment or direction is chosen.",
      "Board for high-impact or difficult-to-reverse growth choices.",
      "Talk It Out when pressure, comparison, or identity conflict blocks judgment.",
    ],
    commonMistakes: [
      "Treating every growth problem as an awareness problem",
      "Scaling marketing into a broken offer",
      "Expanding before capacity can hold",
      "Ignoring referrals when happy customers already exist",
      "Launching several new offers at once",
      "Treating social engagement as buying demand",
      "Framing “stay small” as failure",
    ],
    warningSigns: [
      "Busy marketing, flat results",
      "Good conversations that do not convert",
      "New customers create chaos",
      "Churn offsets every acquisition win",
      "Social growth without business growth",
    ],
    problemDistinctions: [
      {
        id: "awareness",
        label: "Awareness problem",
        description: "The right people do not know you exist.",
        whenToSuspect: ["nobody knows", "no traffic", "invisible", "awareness", "reach"],
        preferredPatterns: ["test", "expand", "narrow"],
      },
      {
        id: "positioning",
        label: "Positioning problem",
        description: "People see you, but not clearly enough to choose you.",
        whenToSuspect: ["confused", "positioning", "look the same", "unclear difference"],
        preferredPatterns: ["reposition", "narrow", "improve"],
      },
      {
        id: "offer",
        label: "Offer problem",
        description: "Interest exists, but the offer does not earn a yes.",
        whenToSuspect: ["not converting", "hesitate", "offer", "package", "pricing feels off"],
        preferredPatterns: ["improve", "simplify", "test"],
      },
      {
        id: "sales",
        label: "Sales problem",
        description: "Interest is real, but conversations and closes are weak.",
        whenToSuspect: ["sales", "calls go nowhere", "pipeline", "follow up"],
        preferredPatterns: ["improve", "test", "stabilize"],
      },
      {
        id: "retention",
        label: "Retention problem",
        description: "Growth leaks because people do not stay.",
        whenToSuspect: ["churn", "retention", "cancel", "don’t stay", "leave after", "do not stay"],
        preferredPatterns: ["protect_current_base", "improve", "stabilize"],
      },
      {
        id: "capacity",
        label: "Capacity problem",
        description: "More demand would break delivery — don’t grow yet.",
        whenToSuspect: ["can’t keep up", "cannot keep up", "overwhelmed", "waitlist chaos", "capacity", "burned out"],
        preferredPatterns: ["stabilize", "simplify", "delay"],
      },
      {
        id: "referral",
        label: "Referral opportunity",
        description: "Happy customers may be an underused growth path.",
        whenToSuspect: ["referral", "word of mouth", "happy clients", "testimonials"],
        preferredPatterns: ["test", "improve", "protect_current_base"],
      },
      {
        id: "expansion_timing",
        label: "Expansion timing",
        description: "Growth may be right later, not this season.",
        whenToSuspect: ["not yet", "timing", "too soon", "after", "next year", "stabilize first"],
        preferredPatterns: ["delay", "stabilize", "test"],
      },
      {
        id: "focus",
        label: "Focus constraint",
        description: "Too many offers or paths dilute growth energy.",
        whenToSuspect: ["three new offers", "many offers", "too many", "launch everything"],
        preferredPatterns: ["narrow", "simplify", "stabilize"],
      },
      {
        id: "maintain_size",
        label: "Maintain current size",
        description: "Staying the current size may be the wise strategy.",
        whenToSuspect: ["stay small", "don’t want bigger", "do not want a bigger", "feel like i should"],
        preferredPatterns: ["maintain_current_direction", "stabilize", "protect_current_base"],
      },
    ],
    guidingPrinciples: [
      "Do not default to “get more customers.”",
      "Sometimes the answer is: do not grow yet.",
      "Diagnose the bottleneck before choosing tactics.",
      "Maintaining the current size is a valid strategic choice.",
      "Growth that harms delivery, trust, or capacity is not healthy growth.",
    ],
  },
  version: 2,
};
