import { buildExecutivePriority } from "../priorities/executivePriorities";
import type { ExecutiveCategory, ExecutiveQuestionDefinition } from "../types";

function q(
  partial: Omit<ExecutiveQuestionDefinition, "priority" | "tags"> & {
    priorityLevel?: ExecutiveQuestionDefinition["priority"]["level"];
    tags?: string[];
  },
): ExecutiveQuestionDefinition {
  const {
    priorityLevel = "medium",
    tags = [],
    ...rest
  } = partial;
  return {
    ...rest,
    tags,
    priority: buildExecutivePriority({ level: priorityLevel }),
  };
}

const PRODUCT: ExecutiveQuestionDefinition[] = [
  q({
    id: "product-build-next",
    category: "product",
    title: "What should we build next?",
    purpose: "Align product investment with member outcomes and strategic missions.",
    businessValue: "Prevents scattered builds; focuses executive energy on highest-impact work.",
    whoBenefits: "Members experiencing less friction; Shari with clearer build conviction.",
    requiredEvidence: ["Customer demand", "Mission alignment", "Research trends", "Competitive gaps"],
    possibleSources: ["spark", "mission", "research", "customer-feedback", "roadmap"],
    relatedMissionIds: ["listening-rooms", "companion", "estate"],
    relatedProducts: ["founder", "companion", "estate"],
    priorityLevel: "critical",
    sampleAnswerId: "ans-product-build-next",
    nextActionHints: ["Continue current mission", "Review roadmap", "Validate with member signal"],
    tags: ["roadmap", "build"],
  }),
  q({
    id: "product-improve-next",
    category: "product",
    title: "What should we improve?",
    purpose: "Surface refinement opportunities before new scope.",
    businessValue: "Compound trust by fixing what members already use.",
    whoBenefits: "Existing members; team with fewer support loops.",
    requiredEvidence: ["Usage friction", "Support themes", "Completion rates"],
    possibleSources: ["spark", "analytics", "customer-feedback", "companion"],
    relatedMissionIds: ["companion", "founder-studio"],
    relatedProducts: ["companion", "founder"],
    priorityLevel: "high",
    nextActionHints: ["Pick one improvement", "Ship calm fix", "Measure relief"],
    tags: ["improvement"],
  }),
  q({
    id: "product-simplify",
    category: "product",
    title: "What should we simplify?",
    purpose: "Reduce cognitive load across the ecosystem.",
    businessValue: "Executive function support is the product; simplicity protects it.",
    whoBenefits: "ADHD entrepreneurs; every team shipping surface area.",
    requiredEvidence: ["Decision fatigue signals", "Abandonment patterns", "Founder observations"],
    possibleSources: ["spark", "flame", "customer-feedback", "mission"],
    relatedMissionIds: ["founder-studio", "companion"],
    relatedProducts: ["founder", "companion"],
    priorityLevel: "high",
    nextActionHints: ["Remove one choice", "Merge duplicate flows"],
    tags: ["simplicity", "ef"],
  }),
  q({
    id: "product-greatest-impact",
    category: "product",
    title: "What feature has the greatest impact?",
    purpose: "Rank initiatives by transformation, not activity.",
    businessValue: "Protects mission focus from interesting distractions.",
    whoBenefits: "Members whose next decision improves; Shari's calendar.",
    requiredEvidence: ["Impact scoring", "Mission progress", "Member stories"],
    possibleSources: ["spark", "fire", "mission", "analytics"],
    relatedMissionIds: ["listening-rooms", "companion"],
    relatedProducts: ["founder", "companion"],
    priorityLevel: "high",
    sampleAnswerId: "ans-product-greatest-impact",
    nextActionHints: ["Confirm with FIRE priority", "Stay on mission"],
    tags: ["impact"],
  }),
];

const CUSTOMERS: ExecutiveQuestionDefinition[] = [
  q({
    id: "customers-adhd-struggles",
    category: "customers",
    title: "What are ADHD entrepreneurs struggling with?",
    purpose: "Ground product and content in lived member reality.",
    businessValue: "Keeps Spark honest — built for real brains, not generic productivity.",
    whoBenefits: "Members who feel seen; content that lands.",
    requiredEvidence: ["Conversation themes", "Support patterns", "Workshop feedback"],
    possibleSources: ["companion", "customer-feedback", "spark", "research"],
    relatedMissionIds: ["companion", "workshop-series"],
    relatedProducts: ["companion", "postcraft"],
    priorityLevel: "critical",
    sampleAnswerId: "ans-customers-adhd-struggles",
    nextActionHints: ["Capture in Decision Vault", "Feed PostCraft themes"],
    tags: ["member-voice"],
  }),
  q({
    id: "customers-questions-increasing",
    category: "customers",
    title: "What questions are increasing?",
    purpose: "Detect emerging needs before they become crises.",
    businessValue: "Early signal for content, workshops, and companion coaching.",
    whoBenefits: "Members getting answers sooner.",
    requiredEvidence: ["Search trends", "Companion transcripts", "Community asks"],
    possibleSources: ["companion", "analytics", "spark"],
    relatedMissionIds: ["companion", "postcraft"],
    relatedProducts: ["companion"],
    priorityLevel: "high",
    nextActionHints: ["Draft FAQ or workshop outline"],
    tags: ["signals"],
  }),
  q({
    id: "customers-frustrations-repeating",
    category: "customers",
    title: "What frustrations keep repeating?",
    purpose: "Find systemic friction worth fixing once.",
    businessValue: "Stops treating symptoms; builds durable trust.",
    whoBenefits: "Members; support load decreases.",
    requiredEvidence: ["Repeated tickets", "Pattern observations", "Churn risk"],
    possibleSources: ["spark", "customer-feedback", "analytics"],
    relatedMissionIds: ["companion", "estate"],
    relatedProducts: ["companion", "founder"],
    priorityLevel: "high",
    nextActionHints: ["Log decision", "Assign fix owner"],
    tags: ["friction"],
  }),
  q({
    id: "customers-delight",
    category: "customers",
    title: "What would delight members?",
    purpose: "Balance recovery work with moments of surprise and belonging.",
    businessValue: "Delight compounds retention without gamification.",
    whoBenefits: "Members; brand warmth.",
    requiredEvidence: ["Success stories", "Unmet wishes", "Estate moments"],
    possibleSources: ["flame", "customer-feedback", "companion"],
    relatedMissionIds: ["estate", "listening-rooms"],
    relatedProducts: ["companion", "estate"],
    priorityLevel: "medium",
    nextActionHints: ["One quiet celebration", "Note in Memory"],
    tags: ["delight"],
  }),
];

const CONTENT: ExecutiveQuestionDefinition[] = [
  q({
    id: "content-create-next",
    category: "content",
    title: "What content should we create?",
    purpose: "Connect editorial calendar to member outcomes.",
    businessValue: "Content traces to missions — not vanity publishing.",
    whoBenefits: "Members; PostCraft pipeline; GHL nurture.",
    requiredEvidence: ["Member requests", "Search trends", "Mission gaps"],
    possibleSources: ["postcraft", "spark", "customer-feedback", "mission"],
    relatedMissionIds: ["postcraft", "marketing-launch", "listening-rooms"],
    relatedProducts: ["postcraft", "ghl"],
    priorityLevel: "high",
    sampleAnswerId: "ans-content-create-next",
    nextActionHints: ["Draft in PostCraft", "Align to Gentle Restart"],
    tags: ["content"],
  }),
  q({
    id: "content-stories",
    category: "content",
    title: "What stories should we tell?",
    purpose: "Human narratives that strengthen belonging.",
    businessValue: "Stories sell transformation, not features.",
    whoBenefits: "Members; marketing authenticity.",
    requiredEvidence: ["Member wins", "Founder journey", "Workshop moments"],
    possibleSources: ["flame", "customer-feedback", "postcraft"],
    relatedMissionIds: ["workshop-series", "companion"],
    relatedProducts: ["postcraft"],
    priorityLevel: "medium",
    nextActionHints: ["Interview one member", "Outline story arc"],
    tags: ["story"],
  }),
  q({
    id: "content-workshop",
    category: "content",
    title: "What workshop should we build?",
    purpose: "Design live experiences that feed the offer ladder.",
    businessValue: "Workshops create cohort momentum and content reuse.",
    whoBenefits: "Members; revenue pipeline.",
    requiredEvidence: ["Demand signals", "Curriculum gaps", "Past workshop NPS"],
    possibleSources: ["research", "customer-feedback", "spark"],
    relatedMissionIds: ["workshop-series"],
    relatedProducts: ["postcraft"],
    priorityLevel: "medium",
    nextActionHints: ["Sketch session arc", "Check team capacity"],
    tags: ["workshop"],
  }),
  q({
    id: "content-course",
    category: "content",
    title: "What course should we create?",
    purpose: "Package durable learning from proven workshops.",
    businessValue: "Scales transformation without losing warmth.",
    whoBenefits: "Members who need async depth.",
    requiredEvidence: ["Workshop replay data", "Completion patterns", "Offer fit"],
    possibleSources: ["analytics", "research", "mission"],
    relatedMissionIds: ["workshop-series"],
    relatedProducts: ["postcraft", "ghl"],
    priorityLevel: "low",
    nextActionHints: ["Validate workshop first"],
    tags: ["course"],
  }),
];

const BUSINESS: ExecutiveQuestionDefinition[] = [
  q({
    id: "business-invest-time",
    category: "business",
    title: "Where should we invest time?",
    purpose: "Executive calendar aligned to strategic value.",
    businessValue: "Time is the scarcest asset — missions make it visible.",
    whoBenefits: "Shari; team clarity.",
    requiredEvidence: ["Mission progress", "Revenue leverage", "Founder energy"],
    possibleSources: ["fire", "mission", "flame"],
    relatedMissionIds: ["listening-rooms", "founder-studio"],
    relatedProducts: ["founder"],
    priorityLevel: "critical",
    nextActionHints: ["Pick one mission block", "Defer the rest"],
    tags: ["time"],
  }),
  q({
    id: "business-automate",
    category: "business",
    title: "What should we automate?",
    purpose: "Automate repetition — never relationship.",
    businessValue: "Frees creative capacity without surveillance feel.",
    whoBenefits: "Team; members (faster follow-through).",
    requiredEvidence: ["Repeated manual tasks", "Error rates", "GHL gaps"],
    possibleSources: ["team-hub", "ghl", "analytics"],
    relatedMissionIds: ["marketing-launch"],
    relatedProducts: ["ghl", "team-hub"],
    priorityLevel: "medium",
    nextActionHints: ["Document SOP", "Draft automation spec"],
    tags: ["automation"],
  }),
  q({
    id: "business-deserves-attention",
    category: "business",
    title: "What deserves attention?",
    purpose: "Separate signal from noise in a growing ecosystem.",
    businessValue: "Prevents executive overwhelm.",
    whoBenefits: "Shari; aligned team.",
    requiredEvidence: ["FIRE alerts", "SPARK patterns", "Pending decisions"],
    possibleSources: ["fire", "spark", "decision-vault"],
    relatedMissionIds: ["founder-studio"],
    relatedProducts: ["founder"],
    priorityLevel: "high",
    nextActionHints: ["Review Decision Vault", "One decision today"],
    tags: ["attention"],
  }),
  q({
    id: "business-opportunity-growing",
    category: "business",
    title: "What opportunity is growing?",
    purpose: "Catch momentum before it fades.",
    businessValue: "Revenue and impact from timely moves.",
    whoBenefits: "Members; business growth.",
    requiredEvidence: ["SPARK opportunities", "Market signals", "Member demand"],
    possibleSources: ["spark", "fire", "analytics"],
    relatedMissionIds: ["marketing-launch", "listening-rooms"],
    relatedProducts: ["founder", "postcraft"],
    priorityLevel: "high",
    sampleAnswerId: "ans-business-opportunity-growing",
    nextActionHints: ["Size the opportunity", "Mission link check"],
    tags: ["opportunity"],
  }),
];

const TECHNOLOGY: ExecutiveQuestionDefinition[] = [
  q({
    id: "technology-ai-changes",
    category: "technology",
    title: "What AI changes matter?",
    purpose: "Adopt technology that reduces friction — not impresses.",
    businessValue: "Protects companion relationship from generic AI drift.",
    whoBenefits: "Members who need human warmth with quiet intelligence.",
    requiredEvidence: ["Capability shifts", "Member trust impact", "Build cost"],
    possibleSources: ["spark", "research", "roadmap"],
    relatedMissionIds: ["companion", "founder-studio"],
    relatedProducts: ["companion", "founder"],
    priorityLevel: "medium",
    nextActionHints: ["Observation only", "No prompt churn"],
    tags: ["ai"],
  }),
  q({
    id: "technology-products-launched",
    category: "technology",
    title: "What products launched?",
    purpose: "Stay aware without reactive rebuilding.",
    businessValue: "Competitive context for positioning — not feature envy.",
    whoBenefits: "Strategic clarity.",
    requiredEvidence: ["Market scans", "Analyst notes"],
    possibleSources: ["research", "spark"],
    relatedMissionIds: [],
    relatedProducts: ["founder"],
    priorityLevel: "low",
    nextActionHints: ["Note in research library"],
    tags: ["market"],
  }),
  q({
    id: "technology-reduces-friction",
    category: "technology",
    title: "What technology reduces friction?",
    purpose: "Tools that serve executive function, not fight it.",
    businessValue: "Every integration must pass the Member Wins test.",
    whoBenefits: "Members; operations.",
    requiredEvidence: ["Integration ROI", "EF impact", "Support reduction"],
    possibleSources: ["analytics", "team-hub", "ghl"],
    relatedMissionIds: ["founder-studio"],
    relatedProducts: ["founder", "ghl"],
    priorityLevel: "medium",
    nextActionHints: ["Pilot small", "Measure relief"],
    tags: ["friction"],
  }),
];

const FOUNDER: ExecutiveQuestionDefinition[] = [
  q({
    id: "founder-attention-today",
    category: "founder",
    title: "What deserves my attention today?",
    purpose: "Daily executive orientation without module hunting.",
    businessValue: "One calm answer replaces dashboard scanning.",
    whoBenefits: "Shari's focus and confidence.",
    requiredEvidence: ["Today's mission", "FIRE brief", "Pending decisions"],
    possibleSources: ["fire", "mission", "flame", "decision-vault"],
    relatedMissionIds: ["listening-rooms", "founder-studio"],
    relatedProducts: ["founder"],
    priorityLevel: "critical",
    sampleAnswerId: "ans-founder-attention-today",
    nextActionHints: ["Open mission workspace", "One primary action"],
    tags: ["today", "founder"],
  }),
  q({
    id: "founder-decision-waiting",
    category: "founder",
    title: "What decision is waiting?",
    purpose: "Surface decisions before they become drag.",
    businessValue: "Decision Vault stays alive — not archival.",
    whoBenefits: "Shari; team waiting on clarity.",
    requiredEvidence: ["Decision Vault", "Team blockers", "Mission gates"],
    possibleSources: ["decision-vault", "team-hub", "mission"],
    relatedMissionIds: ["listening-rooms", "workshop-series"],
    relatedProducts: ["founder", "team-hub"],
    priorityLevel: "high",
    sampleAnswerId: "ans-founder-decision-waiting",
    nextActionHints: ["Review Decision Vault", "Schedule 15-minute decide"],
    tags: ["decision"],
  }),
  q({
    id: "founder-can-wait",
    category: "founder",
    title: "What can safely wait?",
    purpose: "Permission to defer without guilt.",
    businessValue: "Protects executive function and recovery.",
    whoBenefits: "Shari; realistic team expectations.",
    requiredEvidence: ["Low-priority signals", "Non-blocking work"],
    possibleSources: ["fire", "spark", "flame"],
    relatedMissionIds: [],
    relatedProducts: ["founder"],
    priorityLevel: "medium",
    nextActionHints: ["Park in can-wait list", "Revisit weekly"],
    tags: ["recovery"],
  }),
  q({
    id: "founder-mission-forward",
    category: "founder",
    title: "What mission should move forward?",
    purpose: "Mission-first progress over scattered tasks.",
    businessValue: "Aligns ecosystem around building, not browsing.",
    whoBenefits: "Every product tied to a mission.",
    requiredEvidence: ["Mission progress", "Blockers", "Strategic value"],
    possibleSources: ["mission", "fire", "spark"],
    relatedMissionIds: ["listening-rooms", "companion", "postcraft"],
    relatedProducts: ["founder"],
    priorityLevel: "critical",
    sampleAnswerId: "ans-founder-mission-forward",
    nextActionHints: ["Switch mission focus", "Continue building"],
    tags: ["mission"],
  }),
];

const MARKETING: ExecutiveQuestionDefinition[] = [
  q({
    id: "marketing-campaign-launch",
    category: "marketing",
    title: "What campaign should launch?",
    purpose: "Launch campaigns tied to missions and member readiness.",
    businessValue: "Revenue aligned to transformation, not hype.",
    whoBenefits: "Members re-entering; pipeline health.",
    requiredEvidence: ["GHL readiness", "Content assets", "SPARK restart pattern"],
    possibleSources: ["ghl", "postcraft", "spark", "mission"],
    relatedMissionIds: ["marketing-launch", "listening-rooms"],
    relatedProducts: ["postcraft", "ghl"],
    priorityLevel: "high",
    nextActionHints: ["Approve nurture draft", "Set launch window"],
    tags: ["campaign"],
  }),
  q({
    id: "marketing-newsletter",
    category: "marketing",
    title: "What newsletter should we write?",
    purpose: "Editorial that serves members between visits.",
    businessValue: "Relationship continuity without pressure.",
    whoBenefits: "List members; brand trust.",
    requiredEvidence: ["Member themes", "PostCraft drafts", "Workshop hooks"],
    possibleSources: ["postcraft", "customer-feedback", "spark"],
    relatedMissionIds: ["postcraft"],
    relatedProducts: ["postcraft"],
    priorityLevel: "medium",
    nextActionHints: ["Pick one theme", "Draft in PostCraft"],
    tags: ["newsletter"],
  }),
  q({
    id: "marketing-lead-magnet",
    category: "marketing",
    title: "What lead magnet should we create?",
    purpose: "Ethical entry points that demonstrate value.",
    businessValue: "List growth without manipulative urgency.",
    whoBenefits: "Prospects; nurture sequences.",
    requiredEvidence: ["Search demand", "Workshop clips", "Member FAQs"],
    possibleSources: ["analytics", "postcraft", "research"],
    relatedMissionIds: ["marketing-launch"],
    relatedProducts: ["postcraft", "ghl"],
    priorityLevel: "medium",
    nextActionHints: ["Outline magnet", "Link to GHL funnel"],
    tags: ["lead-magnet"],
  }),
  q({
    id: "marketing-webinar",
    category: "marketing",
    title: "What webinar should we build?",
    purpose: "Live teaching that feeds workshops and courses.",
    businessValue: "High-trust conversion path.",
    whoBenefits: "Attendees; offer ladder.",
    requiredEvidence: ["Topic demand", "Calendar capacity", "Past attendance"],
    possibleSources: ["customer-feedback", "research", "analytics"],
    relatedMissionIds: ["workshop-series"],
    relatedProducts: ["postcraft", "ghl"],
    priorityLevel: "low",
    nextActionHints: ["Validate with waitlist"],
    tags: ["webinar"],
  }),
];

const TEAM: ExecutiveQuestionDefinition[] = [
  q({
    id: "team-izna-work",
    category: "team",
    title: "What should Izna work on?",
    purpose: "Clear team priorities aligned to missions.",
    businessValue: "Reduces context switching and approval loops.",
    whoBenefits: "Izna; faster shipping.",
    requiredEvidence: ["Team hub tasks", "Mission needs", "Pending approvals"],
    possibleSources: ["team-hub", "mission", "postcraft"],
    relatedMissionIds: ["postcraft", "workshop-series"],
    relatedProducts: ["team-hub", "postcraft"],
    priorityLevel: "high",
    sampleAnswerId: "ans-team-izna-work",
    nextActionHints: ["Assign in Team Hub", "One clear deliverable"],
    tags: ["team"],
  }),
  q({
    id: "team-approvals-waiting",
    category: "team",
    title: "What approvals are waiting?",
    purpose: "Unblock team without surprise publishes.",
    businessValue: "Permission-first culture at scale.",
    whoBenefits: "Team velocity; brand safety.",
    requiredEvidence: ["Approval queue", "Content drafts", "Workshop materials"],
    possibleSources: ["team-hub", "postcraft"],
    relatedMissionIds: ["postcraft", "workshop-series"],
    relatedProducts: ["team-hub", "postcraft"],
    priorityLevel: "high",
    nextActionHints: ["Review one approval", "Delegate if safe"],
    tags: ["approval"],
  }),
  q({
    id: "team-project-blocked",
    category: "team",
    title: "What project is blocked?",
    purpose: "Surface blockers before deadlines slip.",
    businessValue: "Executive intervention only where needed.",
    whoBenefits: "Team; mission timelines.",
    requiredEvidence: ["Blocker notes", "Dependencies", "Decision gaps"],
    possibleSources: ["team-hub", "decision-vault", "mission"],
    relatedMissionIds: ["marketing-launch"],
    relatedProducts: ["team-hub", "founder"],
    priorityLevel: "medium",
    nextActionHints: ["Unblock or reschedule", "Log decision"],
    tags: ["blocked"],
  }),
];

export const EXECUTIVE_QUESTION_CATALOG: ExecutiveQuestionDefinition[] = [
  ...PRODUCT,
  ...CUSTOMERS,
  ...CONTENT,
  ...BUSINESS,
  ...TECHNOLOGY,
  ...FOUNDER,
  ...MARKETING,
  ...TEAM,
];

export const EXECUTIVE_CATEGORY_LABELS: Record<ExecutiveCategory, string> = {
  product: "Product",
  customers: "Customers",
  content: "Content",
  business: "Business",
  technology: "Technology",
  founder: "Founder",
  marketing: "Marketing",
  team: "Team",
};

export function getCatalogQuestion(id: string): ExecutiveQuestionDefinition | undefined {
  return EXECUTIVE_QUESTION_CATALOG.find((q) => q.id === id);
}

export function listCatalogByCategory(category: ExecutiveCategory): ExecutiveQuestionDefinition[] {
  return EXECUTIVE_QUESTION_CATALOG.filter((q) => q.category === category);
}
