/**
 * Cartographer's Studio public exports.
 */

export {
  CARTOGRAPHERS_STUDIO_BACKGROUND,
  CARTOGRAPHERS_STUDIO_PLACE_ID,
  CARTOGRAPHERS_STUDIO_OFFICIAL_NAME,
  CARTOGRAPHERS_ATLAS_SAVE_LINE,
  CARTOGRAPHERS_RETURN_TO_ESTATE,
  CARTOGRAPHERS_RESUME_PREVIOUS,
  CARTOGRAPHERS_CONTINUE_MAPPING,
  CARTOGRAPHERS_HELP,
  CARTOGRAPHERS_BROWSE_MAP_TYPES,
  CARTOGRAPHERS_EXIT,
  CARTOGRAPHERS_UPDATE_MAP,
  CARTOGRAPHERS_ASK_SHARI,
} from "./media";

export {
  CARTOGRAPHERS_FRAMED_MAPS,
  CARTOGRAPHERS_ROOM_INTRO,
  CARTOGRAPHERS_ATLAS_TEASER,
  getFramedMapById,
  wallSelectableFramedMaps,
  type CartographersFramedMap,
  type CartographersFramedMapId,
} from "./framedMaps";

export {
  CARTOGRAPHY_MAP_REGISTRY,
  productionWallMaps,
  namingMatrixRow,
  assertMindMapNamingConsistent,
  assertAllWallMapsActiveAndNamed,
  canonicalMapName,
  getCartographyMapDefinition,
  getCartographyMapDefinitionByMode,
  visualFocusModeForWallMap,
  type CartographyMapRegistryEntry,
  type CartographyProductionStatus,
} from "./mapRegistry";

export {
  CARTOGRAPHY_MAP_DEFINITIONS,
  activeCartographyMaps,
  type CartographyMapDefinition,
  type CartographyStepDefinition,
} from "./mapDefinitions";

export {
  cartographyWallMaps,
  CARTOGRAPHY_WALL_HOTSPOTS,
  wallMapsInDisplayOrder,
  wallMapsForRow,
  getWallMapById,
  assertWallMapRegistryComplete,
  type CartographyWallMap,
  type CartographyWallMapId,
  type CartographyWallRow,
} from "./wallMaps";

export {
  CARTOGRAPHERS_ATLAS_ENTRIES,
  CARTOGRAPHERS_ATLAS_INTRO,
  getAtlasEntry,
  type CartographersAtlasEntry,
} from "./atlas";

export {
  detectsVisualBeginnerUnsure,
  formatVisualBeginnerChoiceMessage,
  parseVisualBeginnerChoice,
  isVisualBeginnerChoiceMessage,
  VISUAL_BEGINNER_CHOICE_LINE,
  type VisualBeginnerChoice,
} from "./visualBeginnerChoice";

export {
  CARTOGRAPHERS_WELCOME_TITLE,
  CARTOGRAPHERS_WELCOME_SUBTITLE,
  CARTOGRAPHERS_WELCOME_BODY,
  CARTOGRAPHERS_WELCOME_BEGIN_HEADING,
  CARTOGRAPHERS_WELCOME_TELL_SPARK,
  CARTOGRAPHERS_WELCOME_CLICK_FRAME,
  CARTOGRAPHERS_WELCOME_ABOUT_HEADING,
  CARTOGRAPHERS_WELCOME_MAP_BLURBS,
  CARTOGRAPHERS_WELCOME_FOOTER,
  CARTOGRAPHERS_WELCOME_REQUEST_EVENT,
  hasDismissedCartographersWelcome,
  dismissCartographersWelcome,
  requestCartographersWelcome,
} from "./welcome";

export {
  VISUAL_THINKING_STUDIO_TITLE,
  VISUAL_THINKING_STUDIO_SUPPORTING,
  VISUAL_THINKING_REQUEST_PLACEHOLDER,
  VISUAL_THINKING_DEPTH_QUESTION,
  VISUAL_THINKING_DEPTH_CHOICES,
  VISUAL_THINKING_USER_LED_PROMPT,
  VISUAL_THINKING_RESEARCH_PROMPT,
  createVisualThinkingRequest,
  applyRequestText,
  applyHelpDepth,
  applyUserControl,
  confirmRecommendation,
  detectHelpDepth,
  detectRequestedOutput,
  detectProvisionalIntent,
  detectUserControl,
  detectsDeclinesMap,
  detectsWantsVisualAlso,
  detectsUserLedVisual,
  recommendOutputs,
  visibleDepthChoices,
  shouldShowRequestFirstExperience,
  saveVisualThinkingRequestDraft,
  loadVisualThinkingRequestDraft,
  clearVisualThinkingRequestDraft,
  type VisualThinkingRequest,
  type VisualThinkingProvisionalIntent,
  type VisualThinkingHelpDepth,
  type VisualThinkingOutputForm,
  type VisualThinkingEntryPath,
  type VisualThinkingRequestStatus,
  type VisualThinkingUserControl,
  type VisualThinkingDepthChoice,
} from "./visualThinkingRequest";

export {
  interpretVisualThinkingUnderstanding,
  projectUnderstandingPreview,
  applyUnderstandingCorrection,
  syncRequestFromUnderstanding,
  understandingOutputToRequestForm,
  detectCreationMode,
  detectKnowledgeLevel,
  inferPrimaryGoal,
  inferCognitiveTasks,
  inferSuccessDefinition,
  assessResearchNeed,
  outputLabel,
  type VisualThinkingUnderstanding,
  type VisualThinkingPrimaryGoal,
  type VisualThinkingCognitiveTask,
  type VisualThinkingKnowledgeLevel,
  type VisualThinkingCreationMode,
  type VisualThinkingResearchNeed,
  type VisualThinkingPrimaryExperience,
  type VisualThinkingUnderstandingOutput,
  type VisualThinkingConfidence,
  type VisualThinkingUnderstandingStatus,
  type VisualThinkingPreviewProjection,
  type UnderstandingCorrection,
} from "./visualThinkingUnderstanding";

export {
  orchestrateVisualThinkingExperience,
  applyExperiencePlanOverride,
  projectExperiencePlanPreview,
  selectPrimaryExperience,
  selectResearchPosition,
  selectInteractionStyle,
  mapUnderstandingOutputToDeliverable,
  deliverableLabel,
  experienceLabel,
  convertibleDeliverables,
  visibleSupportingDeliverables,
  experiencePlanHonorsUnderstandingExclusions,
  type VisualThinkingExperiencePlan,
  type VisualThinkingOrchestratorExperience,
  type VisualThinkingDeliverable,
  type VisualThinkingGenerationStage,
  type VisualThinkingResearchPosition,
  type VisualThinkingInteractionStyle,
  type VisualThinkingEditingCapability,
  type VisualThinkingHandoffTarget,
  type VisualThinkingPlanOverrides,
  type ExperiencePlanOverride,
  type ExperiencePlanPreviewProjection,
} from "./visualThinkingExperienceOrchestrator";

export {
  createGenerationRun,
  executeGenerationRun,
  startGenerationFromConfirmedPlan,
  applyBlockEdit,
  transformBlock,
  simplifyDeliverable,
  deepenDeliverable,
  getPrimaryDeliverable,
  getSupportingDeliverables,
  projectGenerationStatus,
  saveGenerationBundle,
  loadGenerationBundle,
  clearGenerationBundle,
  replaceDeliverableInBundle,
  generationEngineConsumesPlanOnly,
  type VisualThinkingGenerationRun,
  type VisualThinkingGeneratedDeliverable,
  type VisualThinkingContentBlock,
  type VisualThinkingGenerationBundle,
  type VisualThinkingGenerationContext,
  type VisualThinkingVisualShell,
  type VisualThinkingGenerationRunStatus,
  type BlockEdit,
  type SectionTransform,
} from "./visualThinkingGenerationEngine";

export {
  planVisualThinkingKnowledge,
  assembleVisualThinkingKnowledgePackage,
  prepareVisualThinkingKnowledge,
  buildGenerationHandoff,
  applyKnowledgeGapAnswer,
  nextFocusedKnowledgeQuestion,
  projectKnowledgePreparationStatus,
  knowledgeHandoffToGenerationContext,
  knowledgeBehaviorForCreationMode,
  detectKnowledgeConflicts,
  saveKnowledgeBundle,
  loadKnowledgeBundle,
  clearKnowledgeBundle,
  knowledgeEngineConsumesUpstreamOnly,
  type VisualThinkingKnowledgePlan,
  type VisualThinkingKnowledgePackage,
  type VisualThinkingKnowledgeItem,
  type VisualThinkingKnowledgeSourceReference,
  type VisualThinkingKnowledgeGap,
  type VisualThinkingKnowledgeConflict,
  type VisualThinkingKnowledgeUncertainty,
  type VisualThinkingKnowledgeBundle,
  type VisualThinkingGenerationHandoff,
  type VisualThinkingKnowledgeReadiness,
} from "./visualThinkingKnowledgeIntelligence";

export {
  planVisualThinkingPresentation,
  applyPresentationOverride,
  evaluatePresentationEligibility,
  listPresentationEligibilities,
  collectPresentationStructureSignals,
  visibleAlternatePresentations,
  projectPresentationWorkspace,
  projectVisibleBlocks,
  resolveSplitViewMode,
  presentationLabel,
  recommendVisualStructure,
  recommendWrittenTreatment,
  selectInformationDensity,
  selectProgressiveDisclosure,
  densityPreservesContentDepth,
  presentationEngineConsumesUpstreamOnly,
  savePresentationPlan,
  loadPresentationPlan,
  clearPresentationPlan,
  type VisualThinkingPresentationPlan,
  type VisualThinkingPresentationType,
  type VisualThinkingPresentationInput,
  type VisualThinkingPresentationWorkspaceProjection,
  type VisualThinkingInformationDensity,
  type VisualThinkingProgressiveDisclosure,
  type VisualThinkingVisualStructure,
  type VisualThinkingWrittenTreatment,
  type PresentationOverride,
} from "./visualThinkingPresentationIntelligence";
