/**
 * Cartographer's Studio public exports.
 */

export {
  CARTOGRAPHERS_STUDIO_BACKGROUND,
  CARTOGRAPHERS_STUDIO_PLACE_ID,
  CARTOGRAPHERS_STUDIO_OFFICIAL_NAME,
  VISUAL_THINKING_STUDIO_OFFICIAL_NAME,
  VISUAL_THINKING_RETURN_TO_STUDIO,
  VISUAL_THINKING_PREVIOUS_WORK_LABEL,
  CARTOGRAPHERS_ATLAS_SAVE_LINE,
  CARTOGRAPHERS_RETURN_TO_ESTATE,
  CARTOGRAPHERS_RESUME_PREVIOUS,
  CARTOGRAPHERS_CONTINUE_MAPPING,
  CARTOGRAPHERS_HELP,
  CARTOGRAPHERS_BROWSE_MAP_TYPES,
  CARTOGRAPHERS_EXIT,
  CARTOGRAPHERS_UPDATE_MAP,
  CARTOGRAPHERS_ASK_SHARI,
} from "./media";

export {
  CARTOGRAPHERS_FRAMED_MAPS,
  CARTOGRAPHERS_ROOM_INTRO,
  CARTOGRAPHERS_ATLAS_TEASER,
  getFramedMapById,
  wallSelectableFramedMaps,
  type CartographersFramedMap,
  type CartographersFramedMapId,
} from "./framedMaps";

export {
  CARTOGRAPHY_MAP_REGISTRY,
  productionWallMaps,
  namingMatrixRow,
  assertMindMapNamingConsistent,
  assertAllWallMapsActiveAndNamed,
  canonicalMapName,
  getCartographyMapDefinition,
  getCartographyMapDefinitionByMode,
  visualFocusModeForWallMap,
  type CartographyMapRegistryEntry,
  type CartographyProductionStatus,
} from "./mapRegistry";

export {
  CARTOGRAPHY_MAP_DEFINITIONS,
  activeCartographyMaps,
  type CartographyMapDefinition,
  type CartographyStepDefinition,
} from "./mapDefinitions";

export {
  cartographyWallMaps,
  CARTOGRAPHY_WALL_HOTSPOTS,
  wallMapsInDisplayOrder,
  wallMapsForRow,
  getWallMapById,
  assertWallMapRegistryComplete,
  type CartographyWallMap,
  type CartographyWallMapId,
  type CartographyWallRow,
} from "./wallMaps";

export {
  CARTOGRAPHERS_ATLAS_ENTRIES,
  CARTOGRAPHERS_ATLAS_INTRO,
  getAtlasEntry,
  type CartographersAtlasEntry,
} from "./atlas";

export {
  detectsVisualBeginnerUnsure,
  formatVisualBeginnerChoiceMessage,
  parseVisualBeginnerChoice,
  isVisualBeginnerChoiceMessage,
  VISUAL_BEGINNER_CHOICE_LINE,
  type VisualBeginnerChoice,
} from "./visualBeginnerChoice";

export {
  CARTOGRAPHERS_WELCOME_TITLE,
  CARTOGRAPHERS_WELCOME_SUBTITLE,
  CARTOGRAPHERS_WELCOME_BODY,
  CARTOGRAPHERS_WELCOME_BEGIN_HEADING,
  CARTOGRAPHERS_WELCOME_TELL_SPARK,
  CARTOGRAPHERS_WELCOME_CLICK_FRAME,
  CARTOGRAPHERS_WELCOME_ABOUT_HEADING,
  CARTOGRAPHERS_WELCOME_MAP_BLURBS,
  CARTOGRAPHERS_WELCOME_FOOTER,
  CARTOGRAPHERS_WELCOME_REQUEST_EVENT,
  hasDismissedCartographersWelcome,
  dismissCartographersWelcome,
  requestCartographersWelcome,
} from "./welcome";

export {
  VISUAL_THINKING_STUDIO_TITLE,
  VISUAL_THINKING_STUDIO_SUPPORTING,
  VISUAL_THINKING_REQUEST_PLACEHOLDER,
  VISUAL_THINKING_DEPTH_QUESTION,
  VISUAL_THINKING_DEPTH_CHOICES,
  VISUAL_THINKING_USER_LED_PROMPT,
  VISUAL_THINKING_RESEARCH_PROMPT,
  createVisualThinkingRequest,
  applyRequestText,
  applyHelpDepth,
  applyUserControl,
  confirmRecommendation,
  detectHelpDepth,
  detectRequestedOutput,
  detectProvisionalIntent,
  detectUserControl,
  detectsDeclinesMap,
  detectsWantsVisualAlso,
  detectsUserLedVisual,
  recommendOutputs,
  visibleDepthChoices,
  shouldShowRequestFirstExperience,
  saveVisualThinkingRequestDraft,
  loadVisualThinkingRequestDraft,
  clearVisualThinkingRequestDraft,
  type VisualThinkingRequest,
  type VisualThinkingProvisionalIntent,
  type VisualThinkingHelpDepth,
  type VisualThinkingOutputForm,
  type VisualThinkingEntryPath,
  type VisualThinkingRequestStatus,
  type VisualThinkingUserControl,
  type VisualThinkingDepthChoice,
} from "./visualThinkingRequest";

export {
  interpretVisualThinkingUnderstanding,
  projectUnderstandingPreview,
  applyUnderstandingCorrection,
  syncRequestFromUnderstanding,
  understandingOutputToRequestForm,
  detectCreationMode,
  detectKnowledgeLevel,
  inferPrimaryGoal,
  inferCognitiveTasks,
  inferSuccessDefinition,
  assessResearchNeed,
  outputLabel,
  type VisualThinkingUnderstanding,
  type VisualThinkingPrimaryGoal,
  type VisualThinkingCognitiveTask,
  type VisualThinkingKnowledgeLevel,
  type VisualThinkingCreationMode,
  type VisualThinkingResearchNeed,
  type VisualThinkingPrimaryExperience,
  type VisualThinkingUnderstandingOutput,
  type VisualThinkingConfidence,
  type VisualThinkingUnderstandingStatus,
  type VisualThinkingPreviewProjection,
  type UnderstandingCorrection,
} from "./visualThinkingUnderstanding";

export {
  orchestrateVisualThinkingExperience,
  applyExperiencePlanOverride,
  projectExperiencePlanPreview,
  selectPrimaryExperience,
  selectResearchPosition,
  selectInteractionStyle,
  mapUnderstandingOutputToDeliverable,
  deliverableLabel,
  experienceLabel,
  convertibleDeliverables,
  visibleSupportingDeliverables,
  experiencePlanHonorsUnderstandingExclusions,
  type VisualThinkingExperiencePlan,
  type VisualThinkingOrchestratorExperience,
  type VisualThinkingDeliverable,
  type VisualThinkingGenerationStage,
  type VisualThinkingResearchPosition,
  type VisualThinkingInteractionStyle,
  type VisualThinkingEditingCapability,
  type VisualThinkingHandoffTarget,
  type VisualThinkingPlanOverrides,
  type ExperiencePlanOverride,
  type ExperiencePlanPreviewProjection,
} from "./visualThinkingExperienceOrchestrator";

export {
  createGenerationRun,
  executeGenerationRun,
  startGenerationFromConfirmedPlan,
  applyBlockEdit,
  transformBlock,
  simplifyDeliverable,
  deepenDeliverable,
  getPrimaryDeliverable,
  getSupportingDeliverables,
  projectGenerationStatus,
  saveGenerationBundle,
  loadGenerationBundle,
  clearGenerationBundle,
  replaceDeliverableInBundle,
  generationEngineConsumesPlanOnly,
  type VisualThinkingGenerationRun,
  type VisualThinkingGeneratedDeliverable,
  type VisualThinkingContentBlock,
  type VisualThinkingGenerationBundle,
  type VisualThinkingGenerationContext,
  type VisualThinkingVisualShell,
  type VisualThinkingGenerationRunStatus,
  type BlockEdit,
  type SectionTransform,
} from "./visualThinkingGenerationEngine";

export {
  assessRequestAuthorization,
  inferCreationModeFromRequest,
  inferDetailLevelFromRequest,
  assessClarificationNecessity,
  resolveKnowledgeGap,
  assessScopedReadiness,
  buildAutomaticContinuationPlan,
  assessGeneratedResultSubstance,
  buildInstructionalGenerationMaterial,
  enrichHandoffWithInstructionalMaterial,
  type VisualThinkingRequestAuthorization,
  type VisualThinkingClarificationAssessment,
  type VisualThinkingGapResolutionDecision,
  type VisualThinkingScopedReadiness,
  type VisualThinkingAutomaticContinuationPlan,
  type VisualThinkingResultSubstanceAssessment,
} from "./visualThinkingGenerateFirst";

export {
  planVisualThinkingKnowledge,
  assembleVisualThinkingKnowledgePackage,
  prepareVisualThinkingKnowledge,
  buildGenerationHandoff,
  applyKnowledgeGapAnswer,
  nextFocusedKnowledgeQuestion,
  projectKnowledgePreparationStatus,
  knowledgeHandoffToGenerationContext,
  knowledgeBehaviorForCreationMode,
  detectKnowledgeConflicts,
  saveKnowledgeBundle,
  loadKnowledgeBundle,
  clearKnowledgeBundle,
  knowledgeEngineConsumesUpstreamOnly,
  type VisualThinkingKnowledgePlan,
  type VisualThinkingKnowledgePackage,
  type VisualThinkingKnowledgeItem,
  type VisualThinkingKnowledgeSourceReference,
  type VisualThinkingKnowledgeGap,
  type VisualThinkingKnowledgeConflict,
  type VisualThinkingKnowledgeUncertainty,
  type VisualThinkingKnowledgeBundle,
  type VisualThinkingGenerationHandoff,
  type VisualThinkingKnowledgeReadiness,
} from "./visualThinkingKnowledgeIntelligence";

export {
  planVisualThinkingPresentation,
  applyPresentationOverride,
  evaluatePresentationEligibility,
  listPresentationEligibilities,
  collectPresentationStructureSignals,
  visibleAlternatePresentations,
  projectPresentationWorkspace,
  projectVisibleBlocks,
  resolveSplitViewMode,
  presentationLabel,
  recommendVisualStructure,
  buildVisualRecommendation,
  classifyPresentationRequest,
  recommendWrittenTreatment,
  selectInformationDensity,
  selectProgressiveDisclosure,
  densityPreservesContentDepth,
  presentationEngineConsumesUpstreamOnly,
  savePresentationPlan,
  loadPresentationPlan,
  clearPresentationPlan,
  type VisualThinkingPresentationPlan,
  type VisualThinkingPresentationType,
  type VisualThinkingPresentationInput,
  type VisualThinkingPresentationWorkspaceProjection,
  type VisualThinkingInformationDensity,
  type VisualThinkingProgressiveDisclosure,
  type VisualThinkingVisualStructure,
  type VisualThinkingVisualRecommendation,
  type VisualThinkingWrittenTreatment,
  type PresentationOverride,
  type PresentationSwitchKind,
} from "./visualThinkingPresentationIntelligence";

export {
  createThinkingWorkspace,
  planVisualThinkingWorkspace,
  assessWorkspaceEntryEligibility,
  applyWorkspaceAction,
  buildAskShariContext,
  projectVisibleWorkspaceObjects,
  projectInspector,
  fitViewportToContent,
  layoutIntentFromPresentation,
  workspacePreservesKnowledgeImmutability,
  workspaceLayoutProfileForWidth,
  saveThinkingWorkspace,
  loadThinkingWorkspace,
  clearThinkingWorkspace,
  WORKSPACE_SESSION_KEY,
  type ThinkingObject,
  type ThinkingObjectType,
  type ThinkingGroup,
  type ThinkingConnector,
  type ThinkingWorkspaceState,
  type VisualThinkingWorkspacePlan,
  type VisualThinkingWorkspaceEntryAssessment,
  type VisualThinkingWorkspaceMode,
  type WorkspaceAction,
  type WorkspaceLayoutIntent,
  type WorkspaceViewport,
  type AskShariWorkspaceContext,
} from "./visualThinkingWorkspaceFoundation";

export {
  createWorkspaceEditingSession,
  applyCoCreationAction,
  expandSelectedObjects,
  simplifySelectedObjects,
  editSelectedObjectBody,
  researchSelectedArea,
  findMissingPieces,
  generateAlternatives,
  prepareAskBoard,
  prepareAskChamberMember,
  undoContentEdit,
  redoContentEdit,
  updateSelection,
  projectCoCreationInspector,
  projectThinkingObjectKnowledge,
  syncWorkspaceObjectsFromDeliverable,
  applyUserEditProtection,
  applyRepresentationSyncChoice,
  autosaveEditingSession,
  loadEditingSession,
  clearEditingSession,
  recoverEditingSession,
  writebackRequiresApproval,
  assertScopedBlockMutation,
  projectEditingAudit,
  futureCollaborationContract,
  EDITING_SESSION_KEY,
  type ThinkingObjectKnowledge,
  type ThinkingObjectOrigin,
  type CoCreationActionId,
  type WorkspaceEditingSession,
  type CoCreationResult,
  type CoCreationInspectorProjection,
  type RepresentationSyncPreview,
  type SelectionScope,
  type MissingPieceSuggestion,
  type AlternativeProposal,
  type MergeSuggestion,
} from "./visualThinkingWorkspaceEditing";

export {
  computeLayout,
  createLayoutProposal,
  applyLayoutPositions,
  applyVisualRoles,
  buildLayoutSuggestions,
  classifyConnectorKind,
  computeFocusViewport,
  layoutEnginePreservesContent,
  layoutSpacingForProfile,
  resolveLayoutProfile,
  supportedLayoutIntents,
  isWorkspaceLayoutIntent,
  type LayoutResult,
  type LayoutProposal,
  type LayoutSuggestion,
  type LayoutVisualRole,
  type LayoutViewportProfile,
  type LayoutConnectorKind,
  type LayoutEngineInput,
} from "./visualThinkingLayoutEngine";

export {
  VisualThinkingService,
  VISUAL_THINKING_SUPPORTED_CALLERS,
  shouldRecommendVisualThinking,
  requestVisualThinkingHandoff,
  buildVisualThinkingInvitation,
  isSupportedVisualThinkingCaller,
  assertNoDuplicateVisualThinkingEngines,
  getVisualThinkingPreference,
  recordVisualThinkingPreferenceEvent,
  VISUAL_THINKING_PREFERENCE_KEY,
  type VisualThinkingCallerId,
  type VisualThinkingCapability,
  type VisualThinkingRequestContext,
  type VisualThinkingRecommendation,
  type VisualThinkingServiceHandoff,
  type VisualThinkingPreferenceProfile,
  type VisualThinkingPreferenceRecord,
} from "./visualThinkingService";

export {
  planVisualThinkingResearch,
  acquireVisualThinkingResearch,
  applyResearchToKnowledgeBundle,
  projectResearchStatus,
  dismissWorkspaceResearchNotification,
  knowledgeResearchSatisfiesGenerationGate,
  researchEngineConsumesKnowledgeOnly,
  selectResearchStrategy,
  inferResearchTypeFromGap,
  isUserAuthorityGap,
  saveResearchBundle,
  loadResearchBundle,
  clearResearchBundle,
  RESEARCH_SESSION_KEY,
  type VisualThinkingResearchPlan,
  type VisualThinkingResearchItem,
  type VisualThinkingCitation,
  type VisualThinkingResearchConflict,
  type VisualThinkingResearchBundle,
  type VisualThinkingResearchFindingInput,
  type VisualThinkingWorkspaceResearchNotification,
  type VisualThinkingResearchType,
  type VisualThinkingResearchStrategy,
  type VisualThinkingSourceConfidence,
  type VisualThinkingResearchFreshness,
  type VisualThinkingResearchVerification,
} from "./visualThinkingResearchAcquisition";

export {
  inferVisualThinkingRequestedOutcome,
  assessVisualThinkingOutcomeCompletion,
  researchPlanAloneSatisfiesOutcome,
  knowledgePackageAloneSatisfiesOutcome,
  type VisualThinkingRequestedOutcome,
  type VisualThinkingOutcomeCompletionAssessment,
  type VisualThinkingRequestedDeliverableType,
} from "./visualThinkingRequestedOutcome";

export {
  runVisualThinkingResearchToResult,
  buildStableResearchFindingsForRequest,
  type VisualThinkingResearchToResultRun,
} from "./visualThinkingResearchToResult";

export {
  assessVisualThinkingRecommendation,
  assessVisualThinkingRecommendationReadiness,
  scoreVisualThinkingUsefulness,
  inferRecommendedVisualPurpose,
  detectsExplicitVisualThinkingIntent,
  buildVisualThinkingTopicKey,
  buildRecommendationUserFacingMessage,
  projectVisualThinkingRecommendationInvitation,
  projectVisualThinkingRecommendationAudit,
  acceptVisualThinkingRecommendation,
  declineVisualThinkingRecommendation,
  markRecommendationOffered,
  buildVisualThinkingFailureRecovery,
  clearVisualThinkingRecommendationSession,
  recordRecommendationEvent,
  listRecommendationObservabilityEvents,
  VISUAL_THINKING_RECOMMENDATION_SESSION_KEY,
  purposeToPresentation as recommendationPurposeToPresentation,
  purposeToCapability as recommendationPurposeToCapability,
  type VisualThinkingRecommendationDecision,
  type VisualThinkingRecommendationContext,
  type VisualThinkingRecommendationReadiness,
  type VisualThinkingRecommendedPurpose,
  type VisualThinkingRecommendationConfidence,
  type VisualThinkingRecommendationTiming,
  type VisualThinkingRecommendationStatus,
  type VisualThinkingUsefulnessScore,
  type VisualThinkingIntegrationRequest,
  type VisualThinkingRecommendationInvitation,
  type VisualThinkingRecommendationAudit,
  type VisualThinkingRecommendationReturnContext,
  type VisualThinkingRecommendationEvent,
} from "./visualThinkingRecommendationIntelligence";
