import type { CompanionLibraryMeta } from "./types";

/**
 * Master catalog — all 24 Companion Universe™ libraries.
 * Maturity tracks what is production-ready vs foundation vs planned.
 */
export const COMPANION_LIBRARY_CATALOG: CompanionLibraryMeta[] = [
  { id: "place", name: "Companion Place Library™", maturity: "foundation", module: "companionUniverse/libraries/placeLibrary", description: "20 homestead places — governed by docs/companion-homestead/MASTER_PROPERTY_BLUEPRINT.md" },
  { id: "needs", name: "Companion Needs Intelligence™", maturity: "foundation", module: "companionNeedsIntelligence", description: "What the ADHD entrepreneur needs before any room is prepared" },
  { id: "image", name: "Companion Image Library™", maturity: "foundation", module: "companionPresenceLibrary + safeCompositionRegistry", description: "Approved photographs with safe zones" },
  { id: "scene", name: "Scene Library™", maturity: "foundation", module: "companionHospitalityPrototype/scenePresets", description: "Full scene presets — Iowa morning, snow day, birthday" },
  { id: "scene-integrity", name: "Scene Integrity Library™", maturity: "foundation", module: "companionHospitalityPrototype/sceneIntegrityEngine", description: "Rules preventing impossible combinations" },
  { id: "hospitality", name: "Hospitality Library™", maturity: "foundation", module: "companionUniverse/libraries/hospitalityLibrary", description: "Everything Shari can prepare" },
  { id: "motion", name: "Living Motion Library™", maturity: "foundation", module: "companionUniverse/libraries/motionLibrary", description: "Natural movement — never obvious loops" },
  { id: "ambient-sound", name: "Ambient Sound Library™", maturity: "foundation", module: "companionHospitalityPrototype/ambientAudio", description: "Birds, rain, fireplace — accessibility-aware" },
  { id: "lighting", name: "Lighting Library™", maturity: "foundation", module: "companionHospitalityPrototype/types", description: "Morning through night, rain, snow, recovery" },
  { id: "seasonal", name: "Seasonal Library™", maturity: "foundation", module: "welcomeLivingRoom/atmosphere + dailyDiscovery", description: "Seasons, holidays, launches, vacations" },
  { id: "discovery", name: "Discovery Library™", maturity: "foundation", module: "companionEnvironmentIntelligence/dailyDiscovery", description: "Daily surprises — never pushy" },
  { id: "shari-voice-bible", name: "Shari Voice Bible™", maturity: "production", module: "shariVoiceBible", description: "Permanent communication foundation — every companion sentence" },
  { id: "emotional-experience-blueprint", name: "Emotional Experience Blueprint™", maturity: "production", module: "docs/companion-homestead/EMOTIONAL_EXPERIENCE_BLUEPRINT.md", description: "Every room solves a human need before a task — departure state is the gate" },
  { id: "presence-intelligence", name: "Presence Intelligence™", maturity: "production", module: "presenceIntelligence", description: "Quiet preparation before arrival — prepared, not customized; never memory theater" },
  { id: "wisdom-of-restraint", name: "Wisdom of Restraint™", maturity: "production", module: "wisdomOfRestraint", description: "Restraint Filter™ — nothing reaches the guest until a caring human would say it" },
  { id: "character-of-shari", name: "The Character of Shari™", maturity: "production", module: "characterOfShari", description: "Character Filter™ — would the real Shari do this?" },
  { id: "sharis-life-moments", name: "Shari's Life Moments™", maturity: "production", module: "sharisLifeMoments", description: "First-person invitations into Shari's life — never advice" },
  { id: "sharis-everyday-life", name: "Shari's Everyday Life™", maturity: "production", module: "sharisEverydayLife", description: "Environmental storytelling — lived in, never staged or announced" },
  { id: "greeting", name: "Greeting Library™", maturity: "production", module: "shariVoiceBible", description: "Living Room openings — powered by Shari Voice Bible™" },
  { id: "conversation", name: "Companion Conversation Library™", maturity: "foundation", module: "companionUniverse/libraries/conversationLibrary", description: "Cadence per place" },
  { id: "object", name: "Object Library™", maturity: "foundation", module: "companionEnvironmentIntelligence/resolveRoom", description: "Visible room objects with placement" },
  { id: "book", name: "Book Library™", maturity: "foundation", module: "companionEnvironmentIntelligence/bookLibrary", description: "Books as quiet conversation" },
  { id: "artwork", name: "Artwork Library™", maturity: "planned", module: "companionUniverse/libraries/artworkLibrary", description: "Meaningful wall art rotation" },
  { id: "humor", name: "Companion Humor Library™", maturity: "planned", module: "companionUniverse/libraries/humorLibrary", description: "Tiny delight moments" },
  { id: "shari-stories", name: "Shari Stories™ Library", maturity: "planned", module: "companionUniverse/libraries/shariStoriesLibrary", description: "Stories as objects and discovery" },
  { id: "emotional-promise", name: "Emotional Promise Library™", maturity: "foundation", module: "companionUniverse/libraries/placeLibrary", description: "Promise per place — inherited by every feature" },
  { id: "signature-object", name: "Signature Object Library™", maturity: "foundation", module: "companionUniverse/libraries/signatureObjectLibrary", description: "One iconic anchor per place" },
  { id: "companion-object", name: "Companion Object Library™", maturity: "foundation", module: "companionUniverse/libraries/objectLibrary", description: "Signature Objects™ per feature — replaces emoji iconography" },
  { id: "companion-objects-design-system", name: "Companion Objects™ Design System", maturity: "foundation", module: "companionObjectsDesignSystem", description: "298-object master catalog — Warm Homestead Realism™ illustration language" },
  { id: "signature-companion-objects", name: "Signature Companion Objects™", maturity: "foundation", module: "signatureCompanionObjects", description: "Three-form visual identity — navigation, feature, environmental" },
  { id: "quiet-moments", name: "Quiet Moments™", maturity: "production", module: "quietMoments", description: "Ambient life between conversations — silence never punished" },
  { id: "memory-triggers", name: "Memory Triggers™", maturity: "production", module: "memoryTriggers", description: "Sensory story cues that awaken guest memories — occasional, never announced" },
  { id: "companion-relationship", name: "Companion Relationship™", maturity: "production", module: "companionRelationship", description: "Quiet, Balanced, or Front Porch — rhythm adapts; Shari never changes" },
  { id: "honor-their-intent", name: "Honor Their Intent™", maturity: "production", module: "honorTheirIntent", description: "Meet guests where they are — work collaborator or trusted companion" },
  { id: "carry-forward", name: "Carry Forward™", maturity: "production", module: "carryForward", description: "First visit of the day — carry encouragement forward, never shame" },
  { id: "companion-constitution", name: "Companion Constitution™", maturity: "production", module: "companionConstitution", description: "Constitutional hierarchy — Conversation → Companion Intelligence → Specialized Layer → Render" },
  { id: "conversation-intelligence", name: "Conversation Intelligence™", maturity: "production", module: "companionConstitution/conversationIntelligence", description: "Understands conversational context — informs orchestration only" },
  { id: "companion-intelligence", name: "Companion Intelligence™", maturity: "production", module: "companionConstitution/companionIntelligence", description: "Sole orchestration authority — one companion, many specialized intelligences" },
  { id: "environment-intelligence", name: "Environment Intelligence™", maturity: "production", module: "companionConstitution/environmentIntelligence", description: "Sole authority for room, place, scene, background, motion profile" },
  { id: "presence-intelligence", name: "Presence Intelligence™", maturity: "production", module: "companionConstitution/presenceIntelligence", description: "Sole authority for Shari visibility and presence state" },
  { id: "scene-render-contract", name: "Scene Render Contract™", maturity: "production", module: "sceneRenderContract", description: "Renders constitutional decisions — layout, glass, center zone" },
  { id: "room-composition-rule", name: "Room Composition Rule™", maturity: "production", module: "roomCompositionRule", description: "Design around conversation — Living Frame™, signature features at edges" },
  { id: "living-border", name: "Living Border™", maturity: "production", module: "livingBorder", description: "Life at room edges — center stable for guest work" },
  { id: "sharis-presence", name: "Shari's Presence™", maturity: "production", module: "sharisPresence", description: "Host, Beside You, Nearby — felt without always being seen" },
  { id: "planning-table-room", name: "Planning Table Room™", maturity: "production", module: "planningTableRoom", description: "Kitchen Planning Nook — clarity before organization; Beside You™ presence" },
  { id: "sunroom-over-pond", name: "Sunroom Over The Pond™", maturity: "production", module: "sunroomOverThePond", description: "Focus My Brain — pond anchor, water/plants/enclosure; Nearby™ presence" },
  { id: "focus-landscape", name: "Focus Landscape™", maturity: "production", module: "focusLandscape", description: "Six-space cognitive countryside — tool routing, spatial transitions, no menus" },
  { id: "personality", name: "Shari Personality Library™", maturity: "foundation", module: "companionUniverse/libraries/personalityLibrary", description: "Trait expressions in environment — governed by docs/EXPERIENCE_OF_SHARI.md" },
  { id: "ngmtm", name: "Nobody Gave Me the Manual™ Library", maturity: "planned", module: "companionUniverse/libraries/ngmtmLibrary", description: "Honest ADHD moments — governed by docs/THE_HONEST_SHARI.md" },
  { id: "delight", name: "Delight Library™", maturity: "planned", module: "companionUniverse/libraries/delightLibrary", description: "Things users simply notice" },
  { id: "memory", name: "Companion Memory Library™", maturity: "foundation", module: "recognition/recognitionStore", description: "The home remembers" },
  { id: "constitution", name: "Companion Hospitality Constitution™", maturity: "foundation", module: "companionUniverse/constitution", description: "Principles every library must meet" },
  { id: "hospitality-profile", name: "Companion Hospitality Profile™", maturity: "foundation", module: "companionUniverse/libraries/hospitalityProfileLibrary", description: "What Shari remembers — not a user profile" },
  { id: "traditions", name: "Home Traditions Library™", maturity: "foundation", module: "companionUniverse/libraries/traditionsLibrary", description: "Layer 4 — the home's calendar" },
  { id: "layout", name: "Companion Layout System™", maturity: "foundation", module: "companionUniverse/companionLayoutSystem", description: "House Map, Toolbelt, four layers, room immersion" },
  { id: "presence", name: "Companion Presence Engine™", maturity: "foundation", module: "companionUniverse/companionPresenceEngine", description: "When Shari stays, steps back, or leaves evidence" },
];

export function libraryById(id: CompanionLibraryMeta["id"]): CompanionLibraryMeta {
  return COMPANION_LIBRARY_CATALOG.find((lib) => lib.id === id)!;
}
