import type {
  SharedObjectCreationAuthority,
  SharedObjectTypeDef,
  SharedObjectTypeId,
} from "./types";

function def(
  objectTypeId: SharedObjectTypeId,
  name: string,
  family: SharedObjectTypeDef["family"],
  identityField: string,
  requiredFields: readonly string[],
  defaultAuthority: SharedObjectCreationAuthority,
  notes?: string,
): SharedObjectTypeDef {
  return {
    objectTypeId,
    name,
    family,
    identityField,
    requiredFields,
    defaultAuthority,
    notes,
  };
}

/** Master Object Type Registry seed (296–299). */
export const MASTER_OBJECT_TYPES: readonly SharedObjectTypeDef[] = [
  // 296 — Business & relationship
  def(
    "business",
    "Business",
    "business_relationship",
    "business_id",
    ["business_id", "owner_user_id", "name", "active_status"],
    "user_provided",
    "One Business object — never duplicated per Blueprint",
  ),
  def(
    "person",
    "Person",
    "business_relationship",
    "person_id",
    ["person_id", "name", "status"],
    "user_provided",
    "Roles via relationships — never duplicate Person records",
  ),
  def(
    "organization",
    "Organization",
    "business_relationship",
    "organization_id",
    ["organization_id", "name", "status"],
    "user_provided",
  ),
  def(
    "business_dna",
    "Business DNA",
    "business_relationship",
    "business_id",
    ["business_id", "positioning"],
    "user_provided",
  ),
  def(
    "client_avatar",
    "Client Avatar",
    "business_relationship",
    "avatar_id",
    ["avatar_id", "business_id", "name", "status"],
    "user_provided",
  ),
  def(
    "relationship",
    "Relationship",
    "business_relationship",
    "relationship_id",
    [
      "relationship_id",
      "source_object_id",
      "target_object_id",
      "relationship_type",
      "business_id",
    ],
    "prepare",
  ),
  def(
    "client_account",
    "Client Account",
    "business_relationship",
    "client_account_id",
    ["client_account_id", "business_id"],
    "user_provided",
  ),
  def(
    "vendor_account",
    "Vendor Account",
    "business_relationship",
    "vendor_account_id",
    ["vendor_account_id", "business_id"],
    "user_provided",
  ),
  def(
    "partner_account",
    "Partner Account",
    "business_relationship",
    "partner_account_id",
    ["partner_account_id", "business_id"],
    "user_provided",
  ),
  def(
    "role_assignment",
    "Role Assignment",
    "business_relationship",
    "role_assignment_id",
    ["role_assignment_id", "business_id", "person_id", "role"],
    "prepare",
  ),
  // 297 — Offer / commerce / financial
  def(
    "offer",
    "Offer",
    "offer_commerce_financial",
    "offer_id",
    ["offer_id", "business_id", "name", "status"],
    "prepare",
  ),
  def(
    "product",
    "Product",
    "offer_commerce_financial",
    "product_id",
    ["product_id", "business_id", "name", "status"],
    "prepare",
  ),
  def(
    "service",
    "Service",
    "offer_commerce_financial",
    "service_id",
    ["service_id", "business_id", "name", "status"],
    "prepare",
  ),
  def(
    "package",
    "Package",
    "offer_commerce_financial",
    "package_id",
    ["package_id", "business_id", "name"],
    "prepare",
  ),
  def(
    "pricing_model",
    "Pricing Model",
    "offer_commerce_financial",
    "pricing_model_id",
    ["pricing_model_id", "business_id", "model_type"],
    "prepare",
  ),
  def(
    "opportunity",
    "Opportunity",
    "offer_commerce_financial",
    "opportunity_id",
    ["opportunity_id", "business_id"],
    "prepare",
  ),
  def(
    "proposal",
    "Proposal",
    "offer_commerce_financial",
    "proposal_id",
    ["proposal_id", "business_id", "status"],
    "fully_create",
  ),
  def(
    "agreement",
    "Agreement",
    "offer_commerce_financial",
    "agreement_id",
    ["agreement_id", "business_id", "status"],
    "completed_elsewhere",
    "Legal execution often completed outside Spark",
  ),
  def(
    "order",
    "Order / Booking",
    "offer_commerce_financial",
    "order_id",
    ["order_id", "business_id", "status"],
    "completed_elsewhere",
  ),
  def(
    "invoice",
    "Invoice",
    "offer_commerce_financial",
    "invoice_id",
    ["invoice_id", "business_id", "status"],
    "prepare",
  ),
  def(
    "payment",
    "Payment",
    "offer_commerce_financial",
    "payment_id",
    ["payment_id", "business_id", "status"],
    "completed_elsewhere",
    "Never fabricate payment status — sync state required",
  ),
  def(
    "subscription",
    "Subscription",
    "offer_commerce_financial",
    "subscription_id",
    ["subscription_id", "business_id", "status"],
    "prepare",
  ),
  // 298 — Work / project / ops
  def(
    "universal_work",
    "Universal Work",
    "work_project_operations",
    "work_id",
    ["work_id", "work_type", "status"],
    "fully_create",
  ),
  def(
    "create_artifact",
    "Create Artifact",
    "work_project_operations",
    "create_artifact_id",
    ["create_artifact_id", "business_id", "status"],
    "fully_create",
    "Source of truth for created content",
  ),
  def(
    "project",
    "Project",
    "work_project_operations",
    "project_id",
    ["project_id", "business_id", "status"],
    "completed_elsewhere",
    "Execution only — links Create, must not duplicate content",
  ),
  def(
    "milestone",
    "Milestone",
    "work_project_operations",
    "milestone_id",
    ["milestone_id", "project_id", "title"],
    "prepare",
  ),
  def(
    "task",
    "Task",
    "work_project_operations",
    "task_id",
    ["task_id", "title", "status"],
    "prepare",
  ),
  def(
    "checklist",
    "Checklist",
    "work_project_operations",
    "checklist_id",
    ["checklist_id", "title"],
    "fully_create",
  ),
  def(
    "appointment",
    "Appointment",
    "work_project_operations",
    "appointment_id",
    ["appointment_id", "business_id", "starts_at"],
    "prepare",
  ),
  def(
    "event",
    "Event",
    "work_project_operations",
    "event_id",
    ["event_id", "business_id", "title"],
    "prepare",
  ),
  def(
    "location",
    "Location",
    "work_project_operations",
    "location_id",
    ["location_id", "name"],
    "user_provided",
  ),
  def(
    "asset",
    "Asset",
    "work_project_operations",
    "asset_id",
    ["asset_id", "business_id", "name"],
    "user_provided",
  ),
  def(
    "inventory_item",
    "Inventory Item",
    "work_project_operations",
    "inventory_item_id",
    ["inventory_item_id", "business_id", "name"],
    "user_provided",
  ),
  def(
    "reservation",
    "Reservation",
    "work_project_operations",
    "reservation_id",
    ["reservation_id", "business_id"],
    "prepare",
  ),
  def(
    "work_order",
    "Work Order",
    "work_project_operations",
    "work_order_id",
    ["work_order_id", "business_id", "status"],
    "prepare",
  ),
  def(
    "schedule",
    "Schedule",
    "work_project_operations",
    "schedule_id",
    ["schedule_id", "business_id"],
    "prepare",
  ),
  // 299 — Knowledge / content / decision / measurement
  def(
    "knowledge_item",
    "Knowledge Item",
    "knowledge_content_decision_measurement",
    "knowledge_item_id",
    ["knowledge_item_id", "business_id", "title"],
    "prepare",
  ),
  def(
    "content_asset",
    "Content Asset",
    "knowledge_content_decision_measurement",
    "content_asset_id",
    ["content_asset_id", "business_id", "title"],
    "prepare",
  ),
  def(
    "template",
    "Template",
    "knowledge_content_decision_measurement",
    "template_id",
    ["template_id", "title"],
    "fully_create",
  ),
  def(
    "communication",
    "Communication",
    "knowledge_content_decision_measurement",
    "communication_id",
    ["communication_id", "business_id"],
    "prepare",
  ),
  def(
    "decision",
    "Decision",
    "knowledge_content_decision_measurement",
    "decision_id",
    ["decision_id", "business_id", "title"],
    "prepare",
  ),
  def(
    "approval",
    "Approval",
    "knowledge_content_decision_measurement",
    "approval_id",
    ["approval_id", "business_id", "status"],
    "user_provided",
  ),
  def(
    "risk",
    "Risk",
    "knowledge_content_decision_measurement",
    "risk_id",
    ["risk_id", "business_id", "title"],
    "prepare",
  ),
  def(
    "incident",
    "Incident",
    "knowledge_content_decision_measurement",
    "incident_id",
    ["incident_id", "business_id", "title"],
    "user_provided",
  ),
  def(
    "goal",
    "Goal",
    "knowledge_content_decision_measurement",
    "goal_id",
    ["goal_id", "business_id", "title"],
    "user_provided",
  ),
  def(
    "metric_definition",
    "Metric Definition",
    "knowledge_content_decision_measurement",
    "metric_definition_id",
    ["metric_definition_id", "business_id", "name", "formula"],
    "prepare",
    "Dashboards must reference metric definitions — not labels alone",
  ),
  def(
    "metric_observation",
    "Metric Observation",
    "knowledge_content_decision_measurement",
    "metric_observation_id",
    ["metric_observation_id", "metric_definition_id", "observed_at"],
    "completed_elsewhere",
  ),
  def(
    "dashboard",
    "Dashboard",
    "knowledge_content_decision_measurement",
    "dashboard_id",
    ["dashboard_id", "business_id", "metric_definition_ids"],
    "prepare",
  ),
];

export function getObjectType(
  objectTypeId: SharedObjectTypeId,
): SharedObjectTypeDef | undefined {
  return MASTER_OBJECT_TYPES.find((o) => o.objectTypeId === objectTypeId);
}

/** Non-duplication hard list (README). */
export const NON_DUPLICATION_OBJECT_TYPES: readonly SharedObjectTypeId[] = [
  "person",
  "business",
  "client_account",
  "offer",
  "product",
  "service",
  "pricing_model",
  "proposal",
  "project",
  "task",
  "location",
  "asset",
  "metric_definition",
  "create_artifact",
] as const;
