/**
 * Master competency slug registry — curriculum references these by slug.
 * Maps to GrowthCompetencyDefinition in production catalog.
 */

export const CURRICULUM_COMPETENCY_SLUGS = [
  // Build Yourself
  "entrepreneur-mindset",
  "confidence",
  "courage",
  "self-trust",
  "adhd-entrepreneurship",
  "executive-function",
  "planning",
  "prioritization",
  "focus",
  "task-initiation",
  "time-management",
  "productivity",
  "momentum",
  "habits",
  "consistency",
  "emotional-intelligence",
  "self-awareness",
  "resilience",
  "recovery",
  "energy-management",
  "communication",
  "listening",
  "boundaries",
  "negotiation",
  "networking",
  "personal-leadership",
  "influence",
  "purpose",
  // Build Your Business
  "business-foundations",
  "business-strategy",
  "business-planning",
  "mission-vision",
  "offers",
  "pricing",
  "marketing",
  "messaging",
  "positioning",
  "copywriting",
  "content-creation",
  "storytelling",
  "branding",
  "sales",
  "customer-experience",
  "finance",
  "cash-flow",
  "profitability",
  "operations",
  "hiring",
  "delegation",
  "systems",
  "automation",
  "project-management",
  "ai-for-business",
  "business-growth",
  "scaling",
  "partnerships",
  "legal-risk-awareness",
  // Build Your Thinking
  "critical-thinking",
  "strategic-thinking",
  "systems-thinking",
  "creative-thinking",
  "visual-thinking",
  "decision-making",
  "opportunity-recognition",
  "problem-solving",
  "learning-science",
  "research",
  "innovation",
  "pattern-recognition",
  "mental-models",
  // Build Your Legacy
  "leadership",
  "coaching",
  "mentoring",
  "consulting",
  "public-speaking",
  "writing",
  "course-creation",
  "teaching",
  "community-building",
  "thought-leadership",
  "authority",
  "legacy-building",
  "culture",
  "giving-back",
] as const;

export type CurriculumCompetencySlug =
  (typeof CURRICULUM_COMPETENCY_SLUGS)[number];
