import type { AdhdEverydayStrategy } from "./types";

/** Bundle 01–03 catalog — routing + offer hints only (not full playbooks). */
export const ADHD_EVERYDAY_STRATEGIES: readonly AdhdEverydayStrategy[] = [
  // Bundle 01 — Activation
  {
    id: "001",
    bundleId: "activation",
    name: "Curiosity Before Commands",
    frictionClue: "Pressure or resistance",
    offerHint:
      "Swap the internal 'I have to' for one honest curiosity question, then one tiny action.",
  },
  {
    id: "002",
    bundleId: "activation",
    name: "The Tiniest Possible First Step",
    frictionClue: "Task feels too large or unclear",
    offerHint: "Shrink the start until it feels almost too small to resist.",
  },
  {
    id: "003",
    bundleId: "activation",
    name: "Five-Minute Start",
    frictionClue: "Task feels endless",
    offerHint: "Commit to five minutes only — stopping is allowed.",
  },
  {
    id: "004",
    bundleId: "activation",
    name: "Body Doubling",
    frictionClue: "Working alone is the obstacle",
    offerHint: "Start with quiet company — Shari nearby or another person present.",
  },
  {
    id: "005",
    bundleId: "activation",
    name: "Reduce One Decision",
    frictionClue: "Too many small choices",
    offerHint: "Remove one decision so starting does not require a committee.",
  },
  {
    id: "006",
    bundleId: "activation",
    name: "Start Badly on Purpose",
    frictionClue: "Perfectionism blocks creation",
    offerHint: "Make a deliberately rough first version — polish is later.",
  },
  {
    id: "007",
    bundleId: "activation",
    name: "Open It, Don’t Finish It",
    frictionClue: "Opening feels equal to finishing",
    offerHint: "The only job is to open the thing — finishing is a different day.",
  },
  {
    id: "008",
    bundleId: "activation",
    name: "Define Enough for Now",
    frictionClue: "No clear finish line",
    offerHint: "Name what 'enough for now' looks like before you start.",
  },
  {
    id: "009",
    bundleId: "activation",
    name: "Put the First Item in Sight",
    frictionClue: "The intention disappears",
    offerHint: "Make the first object or tab visible so the intention cannot hide.",
  },
  {
    id: "010",
    bundleId: "activation",
    name: "Remove One Barrier Before Starting",
    frictionClue: "Setup friction blocks action",
    offerHint: "Clear one setup barrier first — then begin.",
  },

  // Bundle 02 — Overwhelm
  {
    id: "011",
    bundleId: "overwhelm",
    name: "Now, Later, Not Mine",
    frictionClue: "Everything feels equally urgent",
    offerHint: "Sort items into Now, Later, or Not Mine — only Now stays in view.",
  },
  {
    id: "012",
    bundleId: "overwhelm",
    name: "One Visible Action",
    frictionClue: "The list itself causes paralysis",
    offerHint: "Hide the list. Keep one visible next action.",
  },
  {
    id: "013",
    bundleId: "overwhelm",
    name: "Hide Everything Not Needed Now",
    frictionClue: "The environment is visually or digitally loud",
    offerHint: "Hide tabs, piles, and noise that are not for this moment.",
  },
  {
    id: "014",
    bundleId: "overwhelm",
    name: "Ask What Is Making This Feel Heavy",
    frictionClue: "The real reason for overwhelm is unclear",
    offerHint: "Name the heaviest part before solving anything else.",
  },
  {
    id: "015",
    bundleId: "overwhelm",
    name: "Make the Task Smaller",
    frictionClue: "The task is too broad",
    offerHint: "Cut the task until only one bite remains.",
  },
  {
    id: "016",
    bundleId: "overwhelm",
    name: "Ask for a Short Summary",
    frictionClue: "The member cannot regain context",
    offerHint: "Ask Spark for a short summary of where things stand — then one step.",
  },
  {
    id: "017",
    bundleId: "overwhelm",
    name: "Delay Optional Decisions",
    frictionClue: "Future choices are crowding the present",
    offerHint: "Park optional decisions so today can breathe.",
  },
  {
    id: "018",
    bundleId: "overwhelm",
    name: "Use Enough for Now During Overwhelm",
    frictionClue: "Full completion feels impossible",
    offerHint: "Choose an 'enough for now' finish line under low capacity.",
  },
  {
    id: "019",
    bundleId: "overwhelm",
    name: "Clear My Mind Into Action Buckets",
    frictionClue: "Thoughts and obligations are mixed together",
    offerHint: "Dump everything, then sort into simple action buckets.",
  },
  {
    id: "020",
    bundleId: "overwhelm",
    name: "Reduce Input Before Solving",
    frictionClue: "The member cannot process more input",
    offerHint: "Stop adding information. Reduce input before any solving.",
  },

  // Bundle 03 — Memory & Time
  {
    id: "021",
    bundleId: "memory_time",
    name: "Prepare → Leave → Arrive",
    frictionClue: "Leaving and arriving are treated as one step",
    offerHint: "Set prepare, leave, and arrive times — not only the appointment time.",
  },
  {
    id: "022",
    bundleId: "memory_time",
    name: "One Trusted Capture Place",
    frictionClue: "Notes and reminders are scattered",
    offerHint: "Put the next intention in one trusted capture place.",
  },
  {
    id: "023",
    bundleId: "memory_time",
    name: "Put the Reminder Where the Action Happens",
    frictionClue: "Reminders appear in the wrong context",
    offerHint: "Anchor the reminder to the place or moment of action.",
  },
  {
    id: "024",
    bundleId: "memory_time",
    name: "Say the Action Aloud",
    frictionClue: "The intention disappears immediately",
    offerHint: "Say the next action out loud so working memory can hold it.",
  },
  {
    id: "025",
    bundleId: "memory_time",
    name: "Prepare Needed Items in Advance",
    frictionClue: "Setup consumes the available energy",
    offerHint: "Stage needed items ahead so start energy is not spent on setup.",
  },
  {
    id: "026",
    bundleId: "memory_time",
    name: "Use a Visible Countdown",
    frictionClue: "Remaining time feels invisible",
    offerHint: "Make remaining time visible while you work or transition.",
  },
  {
    id: "027",
    bundleId: "memory_time",
    name: "Add Transition Reminders",
    frictionClue: "Stopping and switching are difficult",
    offerHint: "Add a clear cue for stopping or switching before the next thing.",
  },
  {
    id: "028",
    bundleId: "memory_time",
    name: "Add Buffer Time",
    frictionClue: "Small delays destroy the schedule",
    offerHint: "Add buffer so small delays do not collapse the day.",
  },
  {
    id: "029",
    bundleId: "memory_time",
    name: "Start Getting Ready Reminder",
    frictionClue: "The member remembers to leave but not to prepare",
    offerHint: "Remind 'start getting ready' before the leave time.",
  },
  {
    id: "030",
    bundleId: "memory_time",
    name: "Open Loops Summary",
    frictionClue: "Unfinished commitments create background pressure",
    offerHint: "List open loops briefly so the brain can stop carrying them all.",
  },

  // Bundle 04 — Emotional Regulation & Burnout
  {
    id: "031",
    bundleId: "emotion_burnout",
    name: "Pause Major Decisions",
    frictionClue: "A major decision feels urgent during intense emotion",
    offerHint: "Pause big decisions until the emotional wave settles a bit.",
  },
  {
    id: "032",
    bundleId: "emotion_burnout",
    name: "Name What Happened Before Solving",
    frictionClue: "Advice is arriving before understanding",
    offerHint: "Name what happened first — solving comes after feeling heard.",
  },
  {
    id: "033",
    bundleId: "emotion_burnout",
    name: "Ask What Kind of Help Is Needed",
    frictionClue: "The type of support is unclear",
    offerHint: "Ask whether they want comfort, clarity, or a next action.",
  },
  {
    id: "034",
    bundleId: "emotion_burnout",
    name: "Reduce Input During Emotional Overload",
    frictionClue: "Too much information is increasing distress",
    offerHint: "Reduce input before adding advice or options.",
  },
  {
    id: "035",
    bundleId: "emotion_burnout",
    name: "Choose Action, Comfort, or Time",
    frictionClue: "The member is unsure whether to act",
    offerHint: "Offer three paths only: action, comfort, or a little time.",
  },
  {
    id: "036",
    bundleId: "emotion_burnout",
    name: "Create a Low-Capacity Version",
    frictionClue: "Capacity is lower than normal",
    offerHint: "Build a low-capacity version of the task for today.",
  },
  {
    id: "037",
    bundleId: "emotion_burnout",
    name: "Separate Recovery From Avoidance",
    frictionClue: "Rest and avoidance feel difficult to distinguish",
    offerHint: "Name whether this is recovery or avoidance — without shame.",
  },
  {
    id: "038",
    bundleId: "emotion_burnout",
    name: "Use a Gentle Return Point",
    frictionClue: "Returning after stepping away feels hard",
    offerHint: "Pick a gentle return point so coming back is smaller.",
  },
  {
    id: "039",
    bundleId: "emotion_burnout",
    name: "Protect Against Shame Spirals",
    frictionClue: "A mistake has become global self-criticism",
    offerHint: "Separate the mistake from who they are — then one repair step.",
  },
  {
    id: "040",
    bundleId: "emotion_burnout",
    name: "Create a Burnout Protection Plan",
    frictionClue: "Overcommitment and collapse repeat",
    offerHint: "Set a small burnout protection plan before adding more.",
  },

  // Bundle 05 — Hyperfocus & Transitions
  {
    id: "041",
    bundleId: "hyperfocus_transitions",
    name: "Set a Stopping Point Before Beginning",
    frictionClue: "Stopping is hard once focus begins",
    offerHint: "Choose a stopping point before deep focus begins.",
  },
  {
    id: "042",
    bundleId: "hyperfocus_transitions",
    name: "Use a Gentle Focus Check-In",
    frictionClue: "The member needs awareness without interruption",
    offerHint: "Use a gentle check-in that protects focus without jarring them.",
  },
  {
    id: "043",
    bundleId: "hyperfocus_transitions",
    name: "Save Where to Resume",
    frictionClue: "Stopping feels risky because context may be lost",
    offerHint: "Save a short resume note before switching away.",
  },
  {
    id: "044",
    bundleId: "hyperfocus_transitions",
    name: "Save the Idea Before Switching",
    frictionClue: "A new idea is preventing the switch",
    offerHint: "Capture the new idea quickly, then complete the switch.",
  },
  {
    id: "045",
    bundleId: "hyperfocus_transitions",
    name: "Protect Basic Needs During Deep Focus",
    frictionClue: "Basic needs disappear during deep focus",
    offerHint: "Protect water, food, or a stretch cue during deep focus.",
  },
  {
    id: "046",
    bundleId: "hyperfocus_transitions",
    name: "Use a Transition Buffer",
    frictionClue: "The next task feels impossible immediately",
    offerHint: "Add a short buffer between stopping and the next task.",
  },
  {
    id: "047",
    bundleId: "hyperfocus_transitions",
    name: "Use a Closing Ritual",
    frictionClue: "The task remains mentally open after stopping",
    offerHint: "Use a tiny closing ritual so the mind can release the task.",
  },
  {
    id: "048",
    bundleId: "hyperfocus_transitions",
    name: "Check Whether Focus Still Matches the Priority",
    frictionClue: "The focus is productive but may be off-priority",
    offerHint: "Gently check whether this focus still matches today’s priority.",
  },
  {
    id: "049",
    bundleId: "hyperfocus_transitions",
    name: "Use Body Doubling to Transition",
    frictionClue: "The member needs company during the handoff",
    offerHint: "Use quiet company to make the handoff easier.",
  },
  {
    id: "050",
    bundleId: "hyperfocus_transitions",
    name: "Plan the Return Before the Break",
    frictionClue: "A break feels likely to destroy momentum",
    offerHint: "Plan the exact return step before taking the break.",
  },

  // Bundle 06 — Decision Making
  {
    id: "051",
    bundleId: "decision_making",
    name: "Reduce the Options",
    frictionClue: "Too many choices are visible",
    offerHint: "Cut the visible options down to a few that matter.",
  },
  {
    id: "052",
    bundleId: "decision_making",
    name: "Separate Reversible From Hard-to-Reverse Decisions",
    frictionClue: "Every decision feels equally high stakes",
    offerHint: "Separate reversible choices from hard-to-reverse ones.",
  },
  {
    id: "053",
    bundleId: "decision_making",
    name: "Identify the One Factor That Matters Most",
    frictionClue: "Too many factors compete",
    offerHint: "Name the one factor that matters most for this decision.",
  },
  {
    id: "054",
    bundleId: "decision_making",
    name: "Use a Simple Pros and Cons Review",
    frictionClue: "The member needs a simple comparison",
    offerHint: "Do a short pros/cons — then choose.",
  },
  {
    id: "055",
    bundleId: "decision_making",
    name: "Choose Good Enough for Now",
    frictionClue: "Perfection blocks a workable choice",
    offerHint: "Choose good enough for now — revise later if needed.",
  },
  {
    id: "056",
    bundleId: "decision_making",
    name: "Choose the Option With the Least Future Friction",
    frictionClue: "Ongoing maintenance is the hidden issue",
    offerHint: "Prefer the option that creates less future friction.",
  },
  {
    id: "057",
    bundleId: "decision_making",
    name: "Use a Temporary Decision",
    frictionClue: "More information is needed through experience",
    offerHint: "Make a temporary decision and learn from trying it.",
  },
  {
    id: "058",
    bundleId: "decision_making",
    name: "Ask One Trusted Perspective",
    frictionClue: "Outside perspective is needed",
    offerHint: "Ask one trusted perspective — not a committee.",
  },
  {
    id: "059",
    bundleId: "decision_making",
    name: "Set a Decision Deadline",
    frictionClue: "The decision remains open indefinitely",
    offerHint: "Set a clear decision deadline so it cannot stay open forever.",
  },
  {
    id: "060",
    bundleId: "decision_making",
    name: "Close the Decision and Record Why",
    frictionClue: "The decision keeps reopening",
    offerHint: "Close the decision and record why — so it stops reopening.",
  },

  // Bundle 07 — Planning, Prioritization & Follow-Through
  {
    id: "061",
    bundleId: "planning_follow_through",
    name: "Choose Today's Most Important Task",
    frictionClue: "The member cannot choose the lead task",
    offerHint: "Choose one most important task for today — not ten.",
  },
  {
    id: "062",
    bundleId: "planning_follow_through",
    name: "Limit Active Priorities",
    frictionClue: "Too many priorities remain active",
    offerHint: "Limit how many priorities stay active at once.",
  },
  {
    id: "063",
    bundleId: "planning_follow_through",
    name: "Define What Done Looks Like",
    frictionClue: "The finish line keeps moving",
    offerHint: "Define what done looks like before you keep refining.",
  },
  {
    id: "064",
    bundleId: "planning_follow_through",
    name: "Start With the Easiest Entry Point",
    frictionClue: "The official first step feels too hard",
    offerHint: "Start with the easiest entry point, not the official first step.",
  },
  {
    id: "065",
    bundleId: "planning_follow_through",
    name: "Use the Next Visible Action",
    frictionClue: "The plan is too vague to act on",
    offerHint: "Name the next visible action — something you can start now.",
  },
  {
    id: "066",
    bundleId: "planning_follow_through",
    name: "Protect High-Energy Time",
    frictionClue: "Strong focus is spent on lower-value work",
    offerHint: "Protect high-energy time for the work that matters most.",
  },
  {
    id: "067",
    bundleId: "planning_follow_through",
    name: "Finish a Small Unit Before Starting Something New",
    frictionClue: "New tasks interrupt current work",
    offerHint: "Finish one small unit before opening something new.",
  },
  {
    id: "068",
    bundleId: "planning_follow_through",
    name: "Create a Daily Finish Line",
    frictionClue: "The day never feels complete",
    offerHint: "Set a daily finish line so the day can end cleanly.",
  },
  {
    id: "069",
    bundleId: "planning_follow_through",
    name: "Review Progress Without Judgment",
    frictionClue: "Review turns into self-criticism",
    offerHint: "Review progress without turning it into a verdict on worth.",
  },
  {
    id: "070",
    bundleId: "planning_follow_through",
    name: "Mark and Celebrate Completion",
    frictionClue: "Completion is not being registered",
    offerHint: "Mark completion so the brain registers that something finished.",
  },

  // Bundle 08 — Returning After Time Away
  {
    id: "071",
    bundleId: "returning_after_absence",
    name: "Where I Left Off Summary",
    frictionClue: "Context has been lost",
    offerHint: "Start with a short where-I-left-off summary — no catch-up spiral.",
  },
  {
    id: "072",
    bundleId: "returning_after_absence",
    name: "Choose One Tiny Restart Action",
    frictionClue: "The member knows the context but cannot re-enter",
    offerHint: "Choose one tiny restart action to re-enter without catching up.",
  },
  {
    id: "073",
    bundleId: "returning_after_absence",
    name: "Do Not Catch Up on Everything",
    frictionClue: "The backlog feels impossible",
    offerHint: "Do not catch up on everything — pick what still earns attention.",
  },
  {
    id: "074",
    bundleId: "returning_after_absence",
    name: "Ask What Still Matters",
    frictionClue: "Old commitments may no longer fit",
    offerHint: "Ask what still matters before carrying old commitments forward.",
  },
  {
    id: "075",
    bundleId: "returning_after_absence",
    name: "Pause Outdated Commitments",
    frictionClue: "The member wants to preserve something without carrying it now",
    offerHint: "Pause outdated commitments without deleting them forever.",
  },
  {
    id: "076",
    bundleId: "returning_after_absence",
    name: "Reopen the Last Project Home First",
    frictionClue: "Too many projects are competing",
    offerHint: "Reopen the last Project Home first — not every open project.",
  },
  {
    id: "077",
    bundleId: "returning_after_absence",
    name: "Use a Re-Entry Ritual",
    frictionClue: "The member needs a repeatable return process",
    offerHint: "Use a small re-entry ritual so returning becomes familiar.",
  },
  {
    id: "078",
    bundleId: "returning_after_absence",
    name: "Return Quietly",
    frictionClue: "The member wants minimal conversation",
    offerHint: "Return quietly — no interrogation about the absence.",
  },
  {
    id: "079",
    bundleId: "returning_after_absence",
    name: "Review Consequences Before Restarting",
    frictionClue: "Deadlines or consequences may have changed",
    offerHint: "Check what still has real consequences before restarting.",
  },
  {
    id: "080",
    bundleId: "returning_after_absence",
    name: "Build a Gradual Return Plan",
    frictionClue: "The absence was long or capacity remains reduced",
    offerHint: "Build a gradual return plan that matches current capacity.",
  },

  // Bundle 09 — Emotional Safety, Self-Talk & Self-Compassion
  {
    id: "081",
    bundleId: "emotional_safety",
    name: "Separate Identity From Performance",
    frictionClue: "Performance has become identity",
    offerHint: "Separate who you are from how today went.",
  },
  {
    id: "082",
    bundleId: "emotional_safety",
    name: "Challenge the Inner Critic With Evidence",
    frictionClue: "Harsh conclusions feel like facts",
    offerHint: "Challenge the inner critic with real evidence, not pep talk.",
  },
  {
    id: "083",
    bundleId: "emotional_safety",
    name: "Replace Self-Blame With Self-Understanding",
    frictionClue: "Difficulty is interpreted as moral failure",
    offerHint: "Replace self-blame with understanding of the actual friction.",
  },
  {
    id: "084",
    bundleId: "emotional_safety",
    name: "Recover After a Bad Day",
    frictionClue: "One bad day feels like total collapse",
    offerHint: "Recover after a bad day without making it the whole story.",
  },
  {
    id: "085",
    bundleId: "emotional_safety",
    name: "Repair Instead of Ruminate",
    frictionClue: "The member is replaying instead of repairing",
    offerHint: "Move from replaying to one small repair.",
  },
  {
    id: "086",
    bundleId: "emotional_safety",
    name: "Build Self-Trust One Promise at a Time",
    frictionClue: "The member no longer trusts their own promises",
    offerHint: "Rebuild self-trust with one kept promise — not a whole new life plan.",
  },
  {
    id: "087",
    bundleId: "emotional_safety",
    name: "Handle Rejection Without Losing Yourself",
    frictionClue: "Rejection has become a global conclusion",
    offerHint: "Hold rejection as an event — not a verdict on worth.",
  },
  {
    id: "088",
    bundleId: "emotional_safety",
    name: "Recognize Comparison Traps",
    frictionClue: "Comparison is distorting direction",
    offerHint: "Notice the comparison trap before it steers the next choice.",
  },
  {
    id: "089",
    bundleId: "emotional_safety",
    name: "Practice Realistic Self-Compassion",
    frictionClue: "Kindness feels incompatible with accountability",
    offerHint: "Use realistic self-compassion that still includes a next step.",
  },
  {
    id: "090",
    bundleId: "emotional_safety",
    name: "Create an Evidence Bank of Successes",
    frictionClue: "Success and resilience are being forgotten",
    offerHint: "Keep an evidence bank of real successes for hard moments.",
  },

  // Bundle 10 — Environment & Sensory Supports
  {
    id: "091",
    bundleId: "environment_sensory",
    name: "Reduce Visible Clutter",
    frictionClue: "Too much is visually competing",
    offerHint: "Reduce what is visually competing for attention right now.",
  },
  {
    id: "092",
    bundleId: "environment_sensory",
    name: "Use Sound Intentionally",
    frictionClue: "Sound is helping or hurting attention",
    offerHint: "Choose sound on purpose — helpful audio or quiet, not accident.",
  },
  {
    id: "093",
    bundleId: "environment_sensory",
    name: "Adjust Lighting",
    frictionClue: "Lighting feels uncomfortable or tiring",
    offerHint: "Adjust lighting so the space feels easier on the nervous system.",
  },
  {
    id: "094",
    bundleId: "environment_sensory",
    name: "Change Rooms or Locations",
    frictionClue: "The current location is associated with distraction or avoidance",
    offerHint: "Change rooms or locations when this place is wired for distraction.",
  },
  {
    id: "095",
    bundleId: "environment_sensory",
    name: "Keep Only Current Materials Visible",
    frictionClue: "Too many project materials are visible",
    offerHint: "Keep only current materials visible — park the rest out of sight.",
  },
  {
    id: "096",
    bundleId: "environment_sensory",
    name: "Use Movement as a Reset",
    frictionClue: "The member feels physically stuck or restless",
    offerHint: "Use a short movement reset before expecting the brain to settle.",
  },
  {
    id: "097",
    bundleId: "environment_sensory",
    name: "Use a Visual Focus Cue",
    frictionClue: "The current focus keeps disappearing",
    offerHint: "Add a visual focus cue so the current task stays findable.",
  },
  {
    id: "098",
    bundleId: "environment_sensory",
    name: "Use Fidget or Tactile Support",
    frictionClue: "The member listens better with tactile or movement support",
    offerHint: "Allow fidget or tactile support if it helps listening or staying.",
  },
  {
    id: "099",
    bundleId: "environment_sensory",
    name: "Create a Low-Distraction Focus Zone",
    frictionClue: "Focused work needs a repeatable place",
    offerHint: "Create a low-distraction focus zone the brain can recognize.",
  },
  {
    id: "100",
    bundleId: "environment_sensory",
    name: "Build a Personal Environment Profile",
    frictionClue: "Environmental preferences vary by task",
    offerHint: "Build a personal environment profile for different kinds of work.",
  },

  // Bundle 11 — Communication & Relationships
  {
    id: "101",
    bundleId: "communication_relationships",
    name: "Pause Before Responding",
    frictionClue: "Emotion is driving an immediate reply",
    offerHint: "Pause before responding when emotion wants to answer first.",
  },
  {
    id: "102",
    bundleId: "communication_relationships",
    name: "Ask for Clarification Instead of Assuming",
    frictionClue: "Meaning is unclear",
    offerHint: "Ask for clarification instead of filling in the blanks.",
  },
  {
    id: "103",
    bundleId: "communication_relationships",
    name: "Prepare for a Difficult Conversation",
    frictionClue: "A difficult conversation needs structure",
    offerHint: "Prepare a simple structure before a difficult conversation.",
  },
  {
    id: "104",
    bundleId: "communication_relationships",
    name: "Recover After Saying the Wrong Thing",
    frictionClue: "Something was said that needs repair",
    offerHint: "Recover after the wrong thing was said — repair without spiraling.",
  },
  {
    id: "105",
    bundleId: "communication_relationships",
    name: "Finish Conversations Clearly",
    frictionClue: "A conversation ended without clarity",
    offerHint: "Finish conversations with a clear next step or closing line.",
  },
  {
    id: "106",
    bundleId: "communication_relationships",
    name: "Set Boundaries Without Guilt",
    frictionClue: "The member is overcommitting",
    offerHint: "Set a boundary without turning it into a guilt story.",
  },
  {
    id: "107",
    bundleId: "communication_relationships",
    name: "Explain ADHD Needs Without Oversharing",
    frictionClue: "Support is needed without oversharing",
    offerHint: "Explain the need simply — without oversharing more than helps.",
  },
  {
    id: "108",
    bundleId: "communication_relationships",
    name: "Listen Without Planning the Response",
    frictionClue: "Listening is interrupted by response planning",
    offerHint: "Listen first — park the response until they finish.",
  },
  {
    id: "109",
    bundleId: "communication_relationships",
    name: "Follow Up Without Feeling Like a Burden",
    frictionClue: "The member is afraid to follow up",
    offerHint: "Follow up in a short, clean way that does not feel like a burden.",
  },
  {
    id: "110",
    bundleId: "communication_relationships",
    name: "Repair Relationships After Misunderstandings",
    frictionClue: "A misunderstanding needs repair",
    offerHint: "Repair the misunderstanding with one clear, warm step.",
  },

  // Bundle 12 — Boring Tasks & Motivation
  {
    id: "111",
    bundleId: "boring_tasks_motivation",
    name: "Pair the Task With Something Pleasant",
    frictionClue: "The task needs a pleasant companion",
    offerHint: "Pair the boring task with something lightly pleasant.",
  },
  {
    id: "112",
    bundleId: "boring_tasks_motivation",
    name: "Race a Short Timer",
    frictionClue: "A visible burst of urgency may help",
    offerHint: "Race a short timer — stop when it ends.",
  },
  {
    id: "113",
    bundleId: "boring_tasks_motivation",
    name: "Turn It Into a Challenge",
    frictionClue: "The member responds to play or novelty",
    offerHint: "Turn it into a small challenge so novelty can help.",
  },
  {
    id: "114",
    bundleId: "boring_tasks_motivation",
    name: "Alternate Boring and Interesting Work",
    frictionClue: "Long boring blocks are unsustainable",
    offerHint: "Alternate boring work with something more interesting.",
  },
  {
    id: "115",
    bundleId: "boring_tasks_motivation",
    name: "Batch Similar Tasks",
    frictionClue: "Repeated setup is wasting effort",
    offerHint: "Batch similar tasks so setup cost is paid once.",
  },
  {
    id: "116",
    bundleId: "boring_tasks_motivation",
    name: "Use Body Doubling for Boring Tasks",
    frictionClue: "Working alone is the barrier",
    offerHint: "Use body doubling for the boring stretch.",
  },
  {
    id: "117",
    bundleId: "boring_tasks_motivation",
    name: "Add Novelty Without Rebuilding the System",
    frictionClue: "A once-helpful system has become stale",
    offerHint: "Add a little novelty without rebuilding the whole system.",
  },
  {
    id: "118",
    bundleId: "boring_tasks_motivation",
    name: "Separate Preparation From the Boring Task",
    frictionClue: "Setup is making the task heavier",
    offerHint: "Separate preparation from the boring task itself.",
  },
  {
    id: "119",
    bundleId: "boring_tasks_motivation",
    name: "Simplify, Delegate, or Automate",
    frictionClue: "The recurring task costs too much energy",
    offerHint: "Simplify, delegate, or automate before forcing more willpower.",
  },
  {
    id: "120",
    bundleId: "boring_tasks_motivation",
    name: "Decide Whether the Task Still Matters",
    frictionClue: "The task may no longer deserve attention",
    offerHint: "Decide whether the task still matters — dropping it is allowed.",
  },

  // Bundle 13 — Time Blindness, Time Awareness & Estimation
  {
    id: "121",
    bundleId: "time_awareness",
    name: "Estimate Time Using Real Experience",
    frictionClue: "Familiar tasks are estimated inaccurately",
    offerHint: "Estimate from real past experience, not hope.",
  },
  {
    id: "122",
    bundleId: "time_awareness",
    name: "Make Time Visible",
    frictionClue: "Time passage feels invisible",
    offerHint: "Make time visible while you work or transition.",
  },
  {
    id: "123",
    bundleId: "time_awareness",
    name: "Plan for Transition Time",
    frictionClue: "Switching time is missing from the plan",
    offerHint: "Plan transition time into the schedule — not only the task block.",
  },
  {
    id: "124",
    bundleId: "time_awareness",
    name: "Use a Leave-Now Cue",
    frictionClue: "The member leaves too late",
    offerHint: "Use a clear leave-now cue before the appointment time.",
  },
  {
    id: "125",
    bundleId: "time_awareness",
    name: "Build Time Buffers Into the Day",
    frictionClue: "Small delays collapse the day",
    offerHint: "Build buffers so small delays do not collapse the day.",
  },
  {
    id: "126",
    bundleId: "time_awareness",
    name: "Recognize Time Optimism",
    frictionClue: "Plans are based on best-case timing",
    offerHint: "Name time optimism — plan for likely time, not best-case.",
  },
  {
    id: "127",
    bundleId: "time_awareness",
    name: "Use Reverse Planning",
    frictionClue: "The deadline is known but the start time is not",
    offerHint: "Plan backward from the deadline to a real start time.",
  },
  {
    id: "128",
    bundleId: "time_awareness",
    name: "Recover After Falling Behind Schedule",
    frictionClue: "The schedule has already drifted",
    offerHint: "Recover the schedule without pretending nothing slipped.",
  },
  {
    id: "129",
    bundleId: "time_awareness",
    name: "Protect Deep Work Time",
    frictionClue: "Important work is fragmented",
    offerHint: "Protect a block of deep work time from fragmentation.",
  },
  {
    id: "130",
    bundleId: "time_awareness",
    name: "Create a Personal Time Profile",
    frictionClue: "Spark Estate needs personalized timing knowledge",
    offerHint: "Build a personal time profile from how long things actually take.",
  },

  // Bundle 14 — Decision Paralysis & Overthinking
  {
    id: "131",
    bundleId: "decision_paralysis",
    name: "Recognize Decision Paralysis",
    frictionClue: "Thinking is no longer creating new information",
    offerHint: "Notice when thinking has stopped creating new information.",
  },
  {
    id: "132",
    bundleId: "decision_paralysis",
    name: "Use an Enough-Information Check",
    frictionClue: "The member does not know what information is sufficient",
    offerHint: "Check what information is actually enough to choose.",
  },
  {
    id: "133",
    bundleId: "decision_paralysis",
    name: "Set a Research Stopping Rule",
    frictionClue: "Research continues after the essentials are known",
    offerHint: "Set a research stopping rule before gathering more.",
  },
  {
    id: "134",
    bundleId: "decision_paralysis",
    name: "Separate Need for Certainty From Need for Information",
    frictionClue: "The member is seeking certainty rather than facts",
    offerHint: "Separate wanting certainty from needing more facts.",
  },
  {
    id: "135",
    bundleId: "decision_paralysis",
    name: "Limit Reassurance-Seeking",
    frictionClue: "Too many opinions are increasing doubt",
    offerHint: "Limit reassurance-seeking when more opinions deepen doubt.",
  },
  {
    id: "136",
    bundleId: "decision_paralysis",
    name: "Use Past Evidence Instead of Current Emotion",
    frictionClue: "Current emotion is destabilizing a past decision",
    offerHint: "Use past evidence instead of current emotion to re-check a decision.",
  },
  {
    id: "137",
    bundleId: "decision_paralysis",
    name: "Use a Confidence Threshold",
    frictionClue: "The member believes 100% confidence is required",
    offerHint: "Use a confidence threshold — good enough to decide, not perfect certainty.",
  },
  {
    id: "138",
    bundleId: "decision_paralysis",
    name: "Create a Second-Guessing Limit",
    frictionClue: "A closed decision keeps reopening",
    offerHint: "Create a second-guessing limit so closed decisions stay closed.",
  },
  {
    id: "139",
    bundleId: "decision_paralysis",
    name: "Learn From Decisions Without Self-Blame",
    frictionClue: "A disappointing outcome becomes self-blame",
    offerHint: "Learn from the decision without turning the outcome into self-blame.",
  },
  {
    id: "140",
    bundleId: "decision_paralysis",
    name: "Build a Personal Overthinking Profile",
    frictionClue: "Spark Estate needs personalized loop awareness",
    offerHint: "Build an overthinking profile so loops are easier to spot next time.",
  },

  // Bundle 15 — Working Memory & Forgetfulness
  {
    id: "141",
    bundleId: "working_memory",
    name: "Capture Before Switching",
    frictionClue: "A new thought may disappear during another task",
    offerHint: "Capture the thought before switching — so it does not vanish.",
  },
  {
    id: "142",
    bundleId: "working_memory",
    name: "Use One-Step Reminders",
    frictionClue: "A reminder is too vague or too large",
    offerHint: "Use a one-step reminder that names the exact next action.",
  },
  {
    id: "143",
    bundleId: "working_memory",
    name: "Put the Object in the Path",
    frictionClue: "A physical item must trigger the next action",
    offerHint: "Put the object in the path of the next action.",
  },
  {
    id: "144",
    bundleId: "working_memory",
    name: "Use a Future-Me Note",
    frictionClue: "Future context needs to be preserved",
    offerHint: "Leave a future-me note with the context you will need later.",
  },
  {
    id: "145",
    bundleId: "working_memory",
    name: "Use a Short Repeatable Checklist",
    frictionClue: "A recurring sequence keeps losing steps",
    offerHint: "Use a short repeatable checklist for sequences that keep losing steps.",
  },
  {
    id: "146",
    bundleId: "working_memory",
    name: "Say Where You Put It",
    frictionClue: "Items are repeatedly misplaced",
    offerHint: "Say where you put it out loud so location sticks.",
  },
  {
    id: "147",
    bundleId: "working_memory",
    name: "Photograph the Setup",
    frictionClue: "Visual setup or location needs to be remembered",
    offerHint: "Photograph the setup when you need to remember how it looked.",
  },
  {
    id: "148",
    bundleId: "working_memory",
    name: "Use a Return-to-Task Cue",
    frictionClue: "Interruptions erase the restart point",
    offerHint: "Leave a return-to-task cue before an interruption.",
  },
  {
    id: "149",
    bundleId: "working_memory",
    name: "Link Remembering to an Existing Routine",
    frictionClue: "A recurring action needs a stronger cue",
    offerHint: "Link remembering to a routine you already do.",
  },
  {
    id: "150",
    bundleId: "working_memory",
    name: "Build a Personal Memory Support Profile",
    frictionClue: "Spark Estate needs personalized memory knowledge",
    offerHint: "Build a memory support profile from what actually helps you remember.",
  },

  // Bundle 16 — Emotional Awareness & Recovery
  {
    id: "151",
    bundleId: "emotional_awareness",
    name: "Notice Emotional Escalation Early",
    frictionClue: "The member notices overload too late",
    offerHint: "Notice emotional escalation earlier — before capacity is gone.",
  },
  {
    id: "152",
    bundleId: "emotional_awareness",
    name: "Name the Emotion Before Solving",
    frictionClue: "The emotional state is unclear",
    offerHint: "Name the emotion before trying to solve anything.",
  },
  {
    id: "153",
    bundleId: "emotional_awareness",
    name: "Separate Facts, Feelings, and Predictions",
    frictionClue: "Facts, feelings, and predictions are mixed",
    offerHint: "Separate facts, feelings, and predictions so the next step is clearer.",
  },
  {
    id: "154",
    bundleId: "emotional_awareness",
    name: "Ride Out the Emotional Wave",
    frictionClue: "A strong urge is pushing immediate action",
    offerHint: "Ride out the emotional wave before acting on the urge.",
  },
  {
    id: "155",
    bundleId: "emotional_awareness",
    name: "Recover After Emotional Overload",
    frictionClue: "The intense moment has passed but capacity is low",
    offerHint: "Recover after emotional overload before taking on more.",
  },
  {
    id: "156",
    bundleId: "emotional_awareness",
    name: "Recognize Emotional Triggers and Patterns",
    frictionClue: "The member wants to understand repeated patterns",
    offerHint: "Recognize emotional triggers and patterns without judgment.",
  },
  {
    id: "157",
    bundleId: "emotional_awareness",
    name: "Reduce Reactivity During Conflict",
    frictionClue: "Conflict is escalating",
    offerHint: "Reduce reactivity during conflict — slow the moment down.",
  },
  {
    id: "158",
    bundleId: "emotional_awareness",
    name: "Return to Clear Thinking After Strong Emotion",
    frictionClue: "The member is unsure whether clear thinking has returned",
    offerHint: "Check whether clear thinking has returned before deciding.",
  },
  {
    id: "159",
    bundleId: "emotional_awareness",
    name: "Build an Emotional Recovery Ritual",
    frictionClue: "Recovery feels random",
    offerHint: "Build a simple emotional recovery ritual you can reuse.",
  },
  {
    id: "160",
    bundleId: "emotional_awareness",
    name: "Create a Personal Emotional Support Profile",
    frictionClue: "Spark Estate needs personalized emotional support knowledge",
    offerHint: "Build an emotional support profile from what actually settles you.",
  },

  // Bundle 17 — Procrastination & Avoidance
  {
    id: "161",
    bundleId: "procrastination",
    name: "Identify the Real Reason You Are Avoiding It",
    frictionClue: "The reason for avoidance is unclear",
    offerHint: "Identify the real reason you are avoiding it — not just the surface story.",
  },
  {
    id: "162",
    bundleId: "procrastination",
    name: "Remove the First Barrier",
    frictionClue: "A practical obstacle blocks the start",
    offerHint: "Remove the first practical barrier so starting is easier.",
  },
  {
    id: "163",
    bundleId: "procrastination",
    name: "Lower the Activation Energy",
    frictionClue: "Too much effort is required before useful work begins",
    offerHint: "Lower the activation energy — make the first step almost too small.",
  },
  {
    id: "164",
    bundleId: "procrastination",
    name: "Begin Before You Feel Ready",
    frictionClue: "The member is waiting to feel ready",
    offerHint: "Begin before you feel ready — readiness often follows starting.",
  },
  {
    id: "165",
    bundleId: "procrastination",
    name: "Reduce Avoidance Caused by Uncertainty",
    frictionClue: "Uncertainty is blocking action",
    offerHint: "Reduce avoidance caused by uncertainty with one clarifying step.",
  },
  {
    id: "166",
    bundleId: "procrastination",
    name: "Escape the I Will Do It Later Loop",
    frictionClue: "The task keeps moving into an undefined future",
    offerHint: "Escape the “I’ll do it later” loop with a real when and where.",
  },
  {
    id: "167",
    bundleId: "procrastination",
    name: "Return After Avoiding It for a Long Time",
    frictionClue: "The task has been avoided for a long time",
    offerHint: "Return after long avoidance without making the return dramatic.",
  },
  {
    id: "168",
    bundleId: "procrastination",
    name: "Restart Without Guilt",
    frictionClue: "Guilt is blocking the restart",
    offerHint: "Restart without guilt — the restart is the win.",
  },
  {
    id: "169",
    bundleId: "procrastination",
    name: "Build Momentum From Tiny Wins",
    frictionClue: "The member needs visible progress",
    offerHint: "Build momentum from tiny wins that prove movement is happening.",
  },
  {
    id: "170",
    bundleId: "procrastination",
    name: "Create a Personal Procrastination Profile",
    frictionClue: "Spark Estate needs personalized avoidance knowledge",
    offerHint: "Build a procrastination profile from what usually blocks you.",
  },

  // Bundle 18 — Perfectionism & Fear of Failure
  {
    id: "171",
    bundleId: "perfectionism",
    name: "Separate Quality From Fear",
    frictionClue: "High standards and fear are mixed together",
    offerHint: "Separate quality from fear so standards do not freeze you.",
  },
  {
    id: "172",
    bundleId: "perfectionism",
    name: "Define Enough for This Stage",
    frictionClue: "Final-version standards are being applied too early",
    offerHint: "Define enough for this stage — not the final version yet.",
  },
  {
    id: "173",
    bundleId: "perfectionism",
    name: "Draft Before You Polish",
    frictionClue: "Creating and editing are happening at the same time",
    offerHint: "Draft before you polish — create first, refine later.",
  },
  {
    id: "174",
    bundleId: "perfectionism",
    name: "Limit Revision Rounds",
    frictionClue: "The work is trapped in repeated review",
    offerHint: "Limit revision rounds so the work can leave the loop.",
  },
  {
    id: "175",
    bundleId: "perfectionism",
    name: "Use a Safe Imperfect Test",
    frictionClue: "Fear prevents a real-world attempt",
    offerHint: "Use a safe imperfect test instead of waiting for certainty.",
  },
  {
    id: "176",
    bundleId: "perfectionism",
    name: "Share With One Trusted Person First",
    frictionClue: "Broad exposure feels too risky",
    offerHint: "Share with one trusted person first before a wider reveal.",
  },
  {
    id: "177",
    bundleId: "perfectionism",
    name: "Treat Mistakes as Information",
    frictionClue: "Mistakes become identity judgments",
    offerHint: "Treat mistakes as information — not as who you are.",
  },
  {
    id: "178",
    bundleId: "perfectionism",
    name: "Use a Failure Recovery Plan",
    frictionClue: "Fear grows because no recovery path is visible",
    offerHint: "Use a failure recovery plan so fear has somewhere to land.",
  },
  {
    id: "179",
    bundleId: "perfectionism",
    name: "Close the Work When It Meets the Purpose",
    frictionClue: "The work meets its purpose but will not close",
    offerHint: "Close the work when it meets the purpose — even if it is not perfect.",
  },
  {
    id: "180",
    bundleId: "perfectionism",
    name: "Create a Personal Perfectionism Profile",
    frictionClue: "Spark Estate needs personalized perfectionism knowledge",
    offerHint: "Build a perfectionism profile from where high standards freeze you.",
  },

  // Bundle 19 — Motivation & Momentum (thinner template depth)
  {
    id: "181",
    bundleId: "motivation_momentum",
    name: "Understand Motivation Differences",
    frictionClue: "Motivation feels absent",
    offerHint: "Understand how ADHD motivation differs — absence is not laziness.",
  },
  {
    id: "182",
    bundleId: "motivation_momentum",
    name: "Use Interest to Enter Difficult Tasks",
    frictionClue: "Interest is the entry point",
    offerHint: "Use interest as the entry point into a difficult task.",
  },
  {
    id: "183",
    bundleId: "motivation_momentum",
    name: "Create Momentum Without Waiting for Motivation",
    frictionClue: "Waiting for motivation",
    offerHint: "Create momentum without waiting to feel motivated first.",
  },
  {
    id: "184",
    bundleId: "motivation_momentum",
    name: "Match Tasks to Current Energy",
    frictionClue: "Energy is low",
    offerHint: "Match the task to current energy instead of fighting it.",
  },
  {
    id: "185",
    bundleId: "motivation_momentum",
    name: "Reconnect With Purpose",
    frictionClue: "Purpose feels lost",
    offerHint: "Reconnect with purpose when the why has gone quiet.",
  },
  {
    id: "186",
    bundleId: "motivation_momentum",
    name: "Use Rewards That Actually Motivate",
    frictionClue: "Rewards aren't working",
    offerHint: "Use rewards that actually motivate you — not generic ones.",
  },
  {
    id: "187",
    bundleId: "motivation_momentum",
    name: "Recover After Motivation Crashes",
    frictionClue: "Motivation collapsed",
    offerHint: "Recover after a motivation crash without all-or-nothing thinking.",
  },
  {
    id: "188",
    bundleId: "motivation_momentum",
    name: "Prevent the All-or-Nothing Motivation Cycle",
    frictionClue: "Boom/bust cycle",
    offerHint: "Prevent the boom/bust motivation cycle with steadier pacing.",
  },
  {
    id: "189",
    bundleId: "motivation_momentum",
    name: "Build Sustainable Momentum",
    frictionClue: "Need lasting consistency",
    offerHint: "Build sustainable momentum — small enough to last.",
  },
  {
    id: "190",
    bundleId: "motivation_momentum",
    name: "Create a Personal Motivation Profile",
    frictionClue: "Personalization needed",
    offerHint: "Build a motivation profile from what actually moves you.",
  },

  // Bundle 20 — Organization, Clutter & Physical Environment (thinner template depth)
  {
    id: "191",
    bundleId: "organization_clutter",
    name: "Reduce Visual Overwhelm",
    frictionClue: "Too much visual input",
    offerHint: "Reduce visual overwhelm so the space can support thinking.",
  },
  {
    id: "192",
    bundleId: "organization_clutter",
    name: "Create ADHD-Friendly Spaces",
    frictionClue: "Space doesn't support work",
    offerHint: "Shape an ADHD-friendly space that supports how you work.",
  },
  {
    id: "193",
    bundleId: "organization_clutter",
    name: "Declutter Without Decision Fatigue",
    frictionClue: "Too many organizing decisions",
    offerHint: "Declutter without decision fatigue — fewer choices, clearer piles.",
  },
  {
    id: "194",
    bundleId: "organization_clutter",
    name: "Organize by Use Instead of Perfection",
    frictionClue: "Systems are too complicated",
    offerHint: "Organize by use instead of perfect systems.",
  },
  {
    id: "195",
    bundleId: "organization_clutter",
    name: "Build Homes for Important Items",
    frictionClue: "Important items are constantly lost",
    offerHint: "Give important items a home so they stop disappearing.",
  },
  {
    id: "196",
    bundleId: "organization_clutter",
    name: "Reset a Space in Minutes",
    frictionClue: "Need a quick recovery",
    offerHint: "Reset a space in minutes — enough to breathe and work again.",
  },
  {
    id: "197",
    bundleId: "organization_clutter",
    name: "Recover From Clutter Shame",
    frictionClue: "Shame blocks cleaning",
    offerHint: "Recover from clutter shame before trying to clean.",
  },
  {
    id: "198",
    bundleId: "organization_clutter",
    name: "Maintain Organization With Low Effort",
    frictionClue: "Systems don't last",
    offerHint: "Maintain organization with the lowest effort that still works.",
  },
  {
    id: "199",
    bundleId: "organization_clutter",
    name: "Prepare Spaces for Success",
    frictionClue: "Want better work environments",
    offerHint: "Prepare the space for success before the work begins.",
  },
  {
    id: "200",
    bundleId: "organization_clutter",
    name: "Create a Personal Environment Profile",
    frictionClue: "Personalization needed",
    offerHint: "Build an environment profile from spaces that actually help you.",
  },

  // Bundle 21 — Routines, Habits & Consistency
  {
    id: "201",
    bundleId: "routines_habits",
    name: "Build the Smallest Useful Routine",
    frictionClue: "The routine is too large to sustain",
    offerHint: "Build the smallest useful routine — one that can survive real days.",
  },
  {
    id: "202",
    bundleId: "routines_habits",
    name: "Anchor the Routine to Something Reliable",
    frictionClue: "The routine has no reliable cue",
    offerHint: "Anchor the routine to something reliable you already do.",
  },
  {
    id: "203",
    bundleId: "routines_habits",
    name: "Create Normal and Low-Capacity Versions",
    frictionClue: "The routine disappears on hard days",
    offerHint: "Create normal and low-capacity versions of the same routine.",
  },
  {
    id: "204",
    bundleId: "routines_habits",
    name: "Use a Visible Routine Cue",
    frictionClue: "The routine is forgotten or invisible",
    offerHint: "Use a visible cue so the routine does not have to be remembered.",
  },
  {
    id: "205",
    bundleId: "routines_habits",
    name: "Restart the Routine Without Starting Over",
    frictionClue: "A gap makes the member feel they must start over",
    offerHint: "Restart the routine without treating a gap as starting over.",
  },
  {
    id: "206",
    bundleId: "routines_habits",
    name: "Review the Routine Instead of Blaming Yourself",
    frictionClue: "The routine repeatedly breaks",
    offerHint: "Review the routine design instead of blaming yourself.",
  },
  {
    id: "207",
    bundleId: "routines_habits",
    name: "Protect the Routine From Overexpansion",
    frictionClue: "The routine keeps gaining steps",
    offerHint: "Protect the routine from overexpansion — keep it small enough to last.",
  },
  {
    id: "208",
    bundleId: "routines_habits",
    name: "Use a Routine Menu Instead of One Fixed Sequence",
    frictionClue: "One fixed routine does not fit changing days",
    offerHint: "Use a routine menu instead of one rigid sequence.",
  },
  {
    id: "209",
    bundleId: "routines_habits",
    name: "Mark Routine Completion Without Overtracking",
    frictionClue: "Progress should be visible without heavy tracking",
    offerHint: "Mark completion lightly — enough to see progress, not a burden.",
  },
  {
    id: "210",
    bundleId: "routines_habits",
    name: "Create a Personal Routine Profile",
    frictionClue: "Spark Estate needs personalized routine knowledge",
    offerHint: "Build a routine profile from what you can actually sustain.",
  },

  // Bundle 22 — Paperwork, Email & Administrative Tasks
  {
    id: "211",
    bundleId: "paperwork_admin",
    name: "Triage Before Processing",
    frictionClue: "Mixed items create switching and paralysis",
    offerHint: "Triage before processing — sort first, act second.",
  },
  {
    id: "212",
    bundleId: "paperwork_admin",
    name: "Separate Easy Replies From Heavy Replies",
    frictionClue: "Easy and heavy replies are tangled together",
    offerHint: "Separate easy replies from heavy ones so inbox work can move.",
  },
  {
    id: "213",
    bundleId: "paperwork_admin",
    name: "Use a Holding Reply",
    frictionClue: "A complete answer is not ready",
    offerHint: "Use a holding reply when the full answer is not ready yet.",
  },
  {
    id: "214",
    bundleId: "paperwork_admin",
    name: "Create One Follow-Up List",
    frictionClue: "Follow-ups are scattered",
    offerHint: "Keep one follow-up list so nothing stays scattered.",
  },
  {
    id: "215",
    bundleId: "paperwork_admin",
    name: "Stage Documents Before Processing",
    frictionClue: "Required documents are missing or spread out",
    offerHint: "Stage documents before processing so you are not hunting mid-task.",
  },
  {
    id: "216",
    bundleId: "paperwork_admin",
    name: "Use Templates for Repeated Administration",
    frictionClue: "Repeated admin starts from blank",
    offerHint: "Use templates for repeated admin instead of starting from blank.",
  },
  {
    id: "217",
    bundleId: "paperwork_admin",
    name: "Batch Administrative Work Carefully",
    frictionClue: "Small admin tasks interrupt the day",
    offerHint: "Batch admin carefully so small tasks stop interrupting the day.",
  },
  {
    id: "218",
    bundleId: "paperwork_admin",
    name: "Close the Administrative Loop",
    frictionClue: "Final closing steps are being missed",
    offerHint: "Close the administrative loop — send, file, or mark done.",
  },
  {
    id: "219",
    bundleId: "paperwork_admin",
    name: "Recover From Administrative Backlog",
    frictionClue: "A backlog feels impossible",
    offerHint: "Recover from an admin backlog one triage pass at a time.",
  },
  {
    id: "220",
    bundleId: "paperwork_admin",
    name: "Create a Personal Administrative Support Profile",
    frictionClue: "Spark Estate needs personalized administrative knowledge",
    offerHint: "Build an admin support profile from what actually clears your inbox.",
  },

  // Bundle 23 — Meetings & Appointments (CORRECTED full depth)
  {
    id: "221",
    bundleId: "meetings_appointments",
    name: "Prepare for Meetings Without Overwhelm",
    frictionClue: "Preparation itself feels too large or unclear",
    offerHint: "Prepare for meetings without overwhelm — only what you need.",
  },
  {
    id: "222",
    bundleId: "meetings_appointments",
    name: "Arrive Ready Instead of Rushing",
    frictionClue: "Time estimation, transitions, or leaving creates rushing",
    offerHint: "Arrive ready instead of rushing into the meeting.",
  },
  {
    id: "223",
    bundleId: "meetings_appointments",
    name: "Stay Present During Meetings",
    frictionClue: "Attention drifts during the meeting",
    offerHint: "Stay present during meetings with a light attention anchor.",
  },
  {
    id: "224",
    bundleId: "meetings_appointments",
    name: "Capture Action Items Before Leaving",
    frictionClue: "Decisions and commitments are likely to disappear after the meeting",
    offerHint: "Capture action items before leaving the meeting.",
  },
  {
    id: "225",
    bundleId: "meetings_appointments",
    name: "Follow Up Without Forgetting",
    frictionClue: "Post-meeting actions are not reliably completed",
    offerHint: "Follow up without forgetting — capture the next step immediately.",
  },
  {
    id: "226",
    bundleId: "meetings_appointments",
    name: "Handle Scheduling Changes Calmly",
    frictionClue: "Rescheduling or changed plans creates disruption",
    offerHint: "Handle scheduling changes calmly with a simple reset.",
  },
  {
    id: "227",
    bundleId: "meetings_appointments",
    name: "Reduce Appointment Anxiety",
    frictionClue: "Worry or anticipatory stress is the main barrier",
    offerHint: "Reduce appointment anxiety with a clear arrive-ready plan.",
  },
  {
    id: "228",
    bundleId: "meetings_appointments",
    name: "Recover After Missed Appointments",
    frictionClue: "A missed appointment or meeting requires repair",
    offerHint: "Recover after a missed appointment without spiraling.",
  },
  {
    id: "229",
    bundleId: "meetings_appointments",
    name: "Build Reliable Meeting Systems",
    frictionClue: "The member needs a repeatable end-to-end meeting system",
    offerHint: "Build a reliable meeting system that does not depend on memory alone.",
  },
  {
    id: "230",
    bundleId: "meetings_appointments",
    name: "Create a Personal Meeting & Appointment Profile",
    frictionClue: "Spark Estate is learning meeting and appointment preferences",
    offerHint: "Build a meeting profile from what helps you show up ready.",
  },

  // Bundle 24 — Money & Financial Management (CORRECTED full depth)
  {
    id: "231",
    bundleId: "money_financial",
    name: "Reduce Money Avoidance",
    frictionClue: "Money information is being avoided",
    offerHint: "Reduce money avoidance with one contained check-in — facts first, not full fix.",
  },
  {
    id: "232",
    bundleId: "money_financial",
    name: "Pay Bills Before They Become Emergencies",
    frictionClue: "Bills are invisible until they become urgent",
    offerHint: "Pay bills before they become emergencies — visibility and one payment path.",
  },
  {
    id: "233",
    bundleId: "money_financial",
    name: "Create Simple Spending Decisions",
    frictionClue: "Everyday purchase decisions feel heavy",
    offerHint: "Create simple spending decisions so everyday purchases do not drain you.",
  },
  {
    id: "234",
    bundleId: "money_financial",
    name: "Prevent Impulse Purchases",
    frictionClue: "Impulse buying happens before commitment is paused",
    offerHint: "Prevent impulse purchases with a short pause before you commit.",
  },
  {
    id: "235",
    bundleId: "money_financial",
    name: "Track Money Without Overwhelm",
    frictionClue: "Cash flow awareness feels too heavy",
    offerHint: "Track money without overwhelm — lightweight awareness only.",
  },
  {
    id: "236",
    bundleId: "money_financial",
    name: "Manage Subscriptions and Recurring Expenses",
    frictionClue: "Recurring charges are forgotten or unchecked",
    offerHint: "Manage subscriptions and recurring expenses with a simple review pass.",
  },
  {
    id: "237",
    bundleId: "money_financial",
    name: "Handle Financial Paperwork Consistently",
    frictionClue: "Statements, notices, and receipts pile up",
    offerHint: "Handle financial paperwork consistently with one landing place.",
  },
  {
    id: "238",
    bundleId: "money_financial",
    name: "Recover After Financial Setbacks",
    frictionClue: "A financial setback needs repair without shame",
    offerHint: "Recover after a financial setback — facts, next step, no shame spiral.",
  },
  {
    id: "239",
    bundleId: "money_financial",
    name: "Build Sustainable Money Habits",
    frictionClue: "Money habits do not last",
    offerHint: "Build sustainable money habits small enough for real weeks.",
  },
  {
    id: "240",
    bundleId: "money_financial",
    name: "Create a Personal Financial Support Profile",
    frictionClue: "Spark Estate needs personalized financial support knowledge",
    offerHint: "Build a financial support profile with privacy and what actually reduces avoidance.",
  },

  // Bundle 25 — Client Work, Business Follow-Through & Professional Commitments
  {
    id: "241",
    bundleId: "client_follow_through",
    name: "Make Every Client Commitment Visible",
    frictionClue: "Client promises are scattered",
    offerHint: "Make every client commitment visible in one place.",
  },
  {
    id: "242",
    bundleId: "client_follow_through",
    name: "Confirm Scope Before Starting",
    frictionClue: "Expectations and completion are unclear",
    offerHint: "Confirm scope before starting so done is clear.",
  },
  {
    id: "243",
    bundleId: "client_follow_through",
    name: "Plan Delivery From the Due Date Backward",
    frictionClue: "The deadline is known but the work starts too late",
    offerHint: "Plan delivery backward from the due date.",
  },
  {
    id: "244",
    bundleId: "client_follow_through",
    name: "Use a Client Status Update Before Silence Grows",
    frictionClue: "Silence is growing while work is delayed",
    offerHint: "Send a client status update before silence grows.",
  },
  {
    id: "245",
    bundleId: "client_follow_through",
    name: "Protect Client Time From Internal Distraction",
    frictionClue: "Internal distractions displace client delivery",
    offerHint: "Protect client time from internal distraction.",
  },
  {
    id: "246",
    bundleId: "client_follow_through",
    name: "Prevent Overpromising",
    frictionClue: "The member commits too quickly",
    offerHint: "Prevent overpromising — pause before you commit.",
  },
  {
    id: "247",
    bundleId: "client_follow_through",
    name: "Close Every Client Session Cleanly",
    frictionClue: "Calls and sessions end with loose ends",
    offerHint: "Close every client session cleanly with next steps named.",
  },
  {
    id: "248",
    bundleId: "client_follow_through",
    name: "Recover After Missing a Client Commitment",
    frictionClue: "A client commitment was missed",
    offerHint: "Recover after missing a client commitment with clarity and repair.",
  },
  {
    id: "249",
    bundleId: "client_follow_through",
    name: "Review Client Load Before Adding Growth Work",
    frictionClue: "Growth work is displacing delivery",
    offerHint: "Review client load before adding growth work.",
  },
  {
    id: "250",
    bundleId: "client_follow_through",
    name: "Create a Personal Client Follow-Through Profile",
    frictionClue: "Spark Estate needs personalized client follow-through knowledge",
    offerHint: "Build a client follow-through profile from what keeps delivery steady.",
  },

  // Bundle 26 — Creativity, Ideas & Idea Management
  {
    id: "251",
    bundleId: "creativity_ideas",
    name: "Capture the Idea Without Starting It",
    frictionClue: "A new idea is interrupting current work",
    offerHint: "Capture the idea without starting it — protect current work.",
  },
  {
    id: "252",
    bundleId: "creativity_ideas",
    name: "Separate Idea Generation From Evaluation",
    frictionClue: "Creation and evaluation are tangled together",
    offerHint: "Separate idea generation from evaluation so creativity can breathe.",
  },
  {
    id: "253",
    bundleId: "creativity_ideas",
    name: "Use an Idea Incubation Period",
    frictionClue: "Novelty is driving immediate commitment",
    offerHint: "Use an incubation period before committing to a new idea.",
  },
  {
    id: "254",
    bundleId: "creativity_ideas",
    name: "Decide Whether an Idea Deserves a Project",
    frictionClue: "The member cannot decide whether an idea deserves action",
    offerHint: "Decide whether the idea deserves a project — or just a note.",
  },
  {
    id: "255",
    bundleId: "creativity_ideas",
    name: "Limit Active Creative Projects",
    frictionClue: "Too many creative projects are active",
    offerHint: "Limit active creative projects so something can finish.",
  },
  {
    id: "256",
    bundleId: "creativity_ideas",
    name: "Preserve the Creative Trail",
    frictionClue: "Creative context and decisions are being lost",
    offerHint: "Preserve the creative trail so you can return without starting over.",
  },
  {
    id: "257",
    bundleId: "creativity_ideas",
    name: "Return to an Idea After the Excitement Fades",
    frictionClue: "Interest faded after the exciting beginning",
    offerHint: "Return to an idea after the excitement fades — gently, not with force.",
  },
  {
    id: "258",
    bundleId: "creativity_ideas",
    name: "Protect Time for Play and Exploration",
    frictionClue: "Creativity has become only output or business",
    offerHint: "Protect time for play and exploration, not only output.",
  },
  {
    id: "259",
    bundleId: "creativity_ideas",
    name: "Close or Archive an Idea Cleanly",
    frictionClue: "Old ideas are crowding attention",
    offerHint: "Close or archive an idea cleanly so it stops crowding attention.",
  },
  {
    id: "260",
    bundleId: "creativity_ideas",
    name: "Create a Personal Creativity and Idea Profile",
    frictionClue: "Spark Estate needs personalized creative knowledge",
    offerHint: "Build a creativity profile from how ideas move through your life.",
  },

  // Bundle 27 — Burnout, Recovery & Sustainable Energy (index stub)
  {
    id: "261",
    bundleId: "burnout_recovery",
    name: "Recognize Burnout Early",
    frictionClue: "Burnout signs are appearing",
    offerHint: "Recognize burnout early — before collapse forces the pause.",
  },
  {
    id: "262",
    bundleId: "burnout_recovery",
    name: "Differentiate Burnout From Low Motivation",
    frictionClue: "Burnout and low motivation are being confused",
    offerHint: "Differentiate burnout from low motivation so the right support shows up.",
  },
  {
    id: "263",
    bundleId: "burnout_recovery",
    name: "Create a Recovery Day Plan",
    frictionClue: "Recovery needs a plan, not more pushing",
    offerHint: "Create a recovery day plan — rest with a little structure.",
  },
  {
    id: "264",
    bundleId: "burnout_recovery",
    name: "Reduce Chronic Overload",
    frictionClue: "Chronic overload is draining capacity",
    offerHint: "Reduce chronic overload before adding another commitment.",
  },
  {
    id: "265",
    bundleId: "burnout_recovery",
    name: "Protect Recovery Time",
    frictionClue: "Recovery time keeps getting stolen",
    offerHint: "Protect recovery time as a real commitment.",
  },
  {
    id: "266",
    bundleId: "burnout_recovery",
    name: "Balance Output and Restoration",
    frictionClue: "Output is crowding out restoration",
    offerHint: "Balance output and restoration so energy can return.",
  },
  {
    id: "267",
    bundleId: "burnout_recovery",
    name: "Recover After Intense Hyperfocus",
    frictionClue: "Intense hyperfocus left the system depleted",
    offerHint: "Recover after intense hyperfocus — the crash is part of the cycle.",
  },
  {
    id: "268",
    bundleId: "burnout_recovery",
    name: "Prevent the Boom-and-Bust Cycle",
    frictionClue: "Energy swings between overdoing and collapse",
    offerHint: "Prevent the boom-and-bust energy cycle with steadier pacing.",
  },
  {
    id: "269",
    bundleId: "burnout_recovery",
    name: "Build Sustainable Energy Practices",
    frictionClue: "Energy practices are not sustainable",
    offerHint: "Build sustainable energy practices that fit real capacity.",
  },
  {
    id: "270",
    bundleId: "burnout_recovery",
    name: "Create a Personal Burnout Prevention Profile",
    frictionClue: "Spark Estate needs personalized burnout prevention knowledge",
    offerHint: "Build a burnout prevention profile from early warning signs that matter for you.",
  },

  // Bundle 28 — Decision Making, Uncertainty & Mental Overload (index stub)
  {
    id: "271",
    bundleId: "decision_fatigue",
    name: "Recognize Decision Fatigue",
    frictionClue: "Decision capacity is depleted",
    offerHint: "Recognize decision fatigue — fewer choices until capacity returns.",
  },
  {
    id: "272",
    bundleId: "decision_fatigue",
    name: "Reduce Analysis Paralysis",
    frictionClue: "Analysis is blocking a workable choice",
    offerHint: "Reduce analysis paralysis with one clear deciding question.",
  },
  {
    id: "273",
    bundleId: "decision_fatigue",
    name: "Use Decision Criteria Instead of Emotion Alone",
    frictionClue: "Emotion alone is steering the decision",
    offerHint: "Use decision criteria instead of emotion alone.",
  },
  {
    id: "274",
    bundleId: "decision_fatigue",
    name: "Limit Too Many Options",
    frictionClue: "Too many options are freezing the choice",
    offerHint: "Limit options so a choice can actually land.",
  },
  {
    id: "275",
    bundleId: "decision_fatigue",
    name: "Separate Reversible From Irreversible Decisions",
    frictionClue: "Decision weight is unclear",
    offerHint: "Separate reversible from irreversible decisions — match the care to the stakes.",
  },
  {
    id: "276",
    bundleId: "decision_fatigue",
    name: "Use the Decision Compass Effectively",
    frictionClue: "A structured decision tool would help",
    offerHint: "Use the Decision Compass when a structured path would help.",
  },
  {
    id: "277",
    bundleId: "decision_fatigue",
    name: "Know When to Ask the Board of Directors",
    frictionClue: "Outside perspective from advisors would help",
    offerHint: "Know when to ask the Board of Directors — and when not to.",
  },
  {
    id: "278",
    bundleId: "decision_fatigue",
    name: "Recover After Difficult Decisions",
    frictionClue: "A hard decision left residual strain",
    offerHint: "Recover after a difficult decision before forcing the next one.",
  },
  {
    id: "279",
    bundleId: "decision_fatigue",
    name: "Build Confidence in Everyday Decisions",
    frictionClue: "Everyday decisions feel heavier than they need to",
    offerHint: "Build confidence in everyday decisions with smaller reps.",
  },
  {
    id: "280",
    bundleId: "decision_fatigue",
    name: "Create a Personal Decision-Making Profile",
    frictionClue: "Spark Estate needs personalized decision-making knowledge",
    offerHint: "Build a decision-making profile from what helps you choose well.",
  },

  // Bundle 29 — Emotional Regulation, Rejection Sensitivity & Social Pain
  {
    id: "281",
    bundleId: "rejection_sensitivity",
    name: "Pause Before Interpreting Rejection",
    frictionClue: "An ambiguous event immediately feels like rejection",
    offerHint: "Pause before interpreting rejection — let the story catch up to the facts.",
  },
  {
    id: "282",
    bundleId: "rejection_sensitivity",
    name: "Name the Social Pain Without Making It Identity",
    frictionClue: "Social pain has become an identity judgment",
    offerHint: "Name the social pain without making it who you are.",
  },
  {
    id: "283",
    bundleId: "rejection_sensitivity",
    name: "Delay the First Emotional Response",
    frictionClue: "The member wants to react immediately",
    offerHint: "Delay the first emotional response until the wave softens.",
  },
  {
    id: "284",
    bundleId: "rejection_sensitivity",
    name: "Ask for Clarification Without Accusation",
    frictionClue: "Meaning is unclear and clarification may help",
    offerHint: "Ask for clarification without accusation.",
  },
  {
    id: "285",
    bundleId: "rejection_sensitivity",
    name: "Use Evidence to Balance the Rejection Story",
    frictionClue: "Only rejection-confirming evidence is visible",
    offerHint: "Use evidence to balance the rejection story.",
  },
  {
    id: "286",
    bundleId: "rejection_sensitivity",
    name: "Recover After Social Rejection",
    frictionClue: "The member needs recovery after rejection or exclusion",
    offerHint: "Recover after social rejection before forcing the next interaction.",
  },
  {
    id: "287",
    bundleId: "rejection_sensitivity",
    name: "Repair After a Rejection-Driven Reaction",
    frictionClue: "A rejection-driven reaction needs repair",
    offerHint: "Repair after a rejection-driven reaction with clarity and care.",
  },
  {
    id: "288",
    bundleId: "rejection_sensitivity",
    name: "Set Boundaries Around Repeated Social Harm",
    frictionClue: "A repeated pattern may reflect real harm",
    offerHint: "Set boundaries around repeated social harm — not every sting is imagined.",
  },
  {
    id: "289",
    bundleId: "rejection_sensitivity",
    name: "Build Social Confidence From Real Experiences",
    frictionClue: "The member wants to rebuild social confidence",
    offerHint: "Build social confidence from real experiences that went okay.",
  },
  {
    id: "290",
    bundleId: "rejection_sensitivity",
    name: "Create a Personal Rejection and Social Support Profile",
    frictionClue: "Spark Estate needs personalized rejection-support knowledge",
    offerHint: "Build a rejection-support profile from what steadies you after social pain.",
  },

  // Bundle 30 — Relationships, Family & Social Communication
  {
    id: "291",
    bundleId: "relationships_family",
    name: "Ask What Kind of Support Is Wanted",
    frictionClue: "Advice, comfort, and listening are mismatched",
    offerHint: "Ask what kind of support is wanted — advice, comfort, or listening.",
  },
  {
    id: "292",
    bundleId: "relationships_family",
    name: "Make Shared Expectations Visible",
    frictionClue: "Responsibilities or agreements are unclear",
    offerHint: "Make shared expectations visible so no one has to guess.",
  },
  {
    id: "293",
    bundleId: "relationships_family",
    name: "Separate Logistics From Emotional Conversations",
    frictionClue: "Practical and emotional issues are tangled",
    offerHint: "Separate logistics from emotional conversations.",
  },
  {
    id: "294",
    bundleId: "relationships_family",
    name: "Use a Planned Pause During Conflict",
    frictionClue: "A conflict is escalating",
    offerHint: "Use a planned pause during conflict before words get sharper.",
  },
  {
    id: "295",
    bundleId: "relationships_family",
    name: "Create a Repair Conversation",
    frictionClue: "Trust or understanding needs repair",
    offerHint: "Create a repair conversation when trust needs tending.",
  },
  {
    id: "296",
    bundleId: "relationships_family",
    name: "Explain Attention and Memory Needs Clearly",
    frictionClue: "Attention or memory differences are being misread",
    offerHint: "Explain attention and memory needs clearly so they are not misread as not caring.",
  },
  {
    id: "297",
    bundleId: "relationships_family",
    name: "Protect Social Energy and Recovery",
    frictionClue: "Social demands are draining capacity",
    offerHint: "Protect social energy and recovery after people-heavy days.",
  },
  {
    id: "298",
    bundleId: "relationships_family",
    name: "Use Relationship Check-Backs",
    frictionClue: "Important conversations need later confirmation",
    offerHint: "Use relationship check-backs so important conversations do not dissolve.",
  },
  {
    id: "299",
    bundleId: "relationships_family",
    name: "Balance Connection and Boundaries",
    frictionClue: "The member swings between overavailability and withdrawal",
    offerHint: "Balance connection and boundaries — both can be true.",
  },
  {
    id: "300",
    bundleId: "relationships_family",
    name: "Create a Personal Relationship and Communication Profile",
    frictionClue: "Spark Estate needs personalized relationship knowledge",
    offerHint: "Build a relationship profile from what helps you stay connected without draining.",
  },

  // Bundle 31 — Daily Living, Home Responsibilities & Self-Care (index stub)
  {
    id: "301",
    bundleId: "daily_living_home",
    name: "Create an ADHD-Friendly Home Reset",
    frictionClue: "The home needs a reset that can actually stick",
    offerHint: "Create an ADHD-friendly home reset — small enough to finish.",
  },
  {
    id: "302",
    bundleId: "daily_living_home",
    name: "Reduce Household Clutter Without Perfection",
    frictionClue: "Household clutter is stuck behind perfection",
    offerHint: "Reduce household clutter without perfection.",
  },
  {
    id: "303",
    bundleId: "daily_living_home",
    name: "Simplify Laundry and Clothing",
    frictionClue: "Laundry and clothing systems are too complex",
    offerHint: "Simplify laundry and clothing so the system can survive real weeks.",
  },
  {
    id: "304",
    bundleId: "daily_living_home",
    name: "Build Reliable Meal Routines",
    frictionClue: "Meals keep falling through",
    offerHint: "Build reliable meal routines that do not require daily reinvention.",
  },
  {
    id: "305",
    bundleId: "daily_living_home",
    name: "Remember Everyday Household Tasks",
    frictionClue: "Everyday household tasks keep disappearing",
    offerHint: "Remember everyday household tasks with cues outside your head.",
  },
  {
    id: "306",
    bundleId: "daily_living_home",
    name: "Manage Paperwork at Home",
    frictionClue: "Home paperwork is piling up",
    offerHint: "Manage paperwork at home with one simple landing place.",
  },
  {
    id: "307",
    bundleId: "daily_living_home",
    name: "Create Helpful Home Zones",
    frictionClue: "The home has no clear zones for action",
    offerHint: "Create helpful home zones so things have an obvious place.",
  },
  {
    id: "308",
    bundleId: "daily_living_home",
    name: "Recover After Household Overwhelm",
    frictionClue: "Household overwhelm has taken over",
    offerHint: "Recover after household overwhelm before trying to deep-clean everything.",
  },
  {
    id: "309",
    bundleId: "daily_living_home",
    name: "Build Sustainable Home Habits",
    frictionClue: "Home habits do not last",
    offerHint: "Build sustainable home habits — small enough for hard days.",
  },
  {
    id: "310",
    bundleId: "daily_living_home",
    name: "Create a Personal Home & Daily Living Profile",
    frictionClue: "Spark Estate needs personalized home and daily living knowledge",
    offerHint: "Build a home and daily living profile from what actually keeps life running.",
  },

  // Bundle 32 — Sleep, Mornings, Evenings & Energy Transitions (index stub)
  {
    id: "311",
    bundleId: "sleep_energy",
    name: "Create a Consistent Bedtime Routine",
    frictionClue: "Bedtime is inconsistent",
    offerHint: "Create a consistent bedtime routine — small enough to repeat.",
  },
  {
    id: "312",
    bundleId: "sleep_energy",
    name: "Reduce Bedtime Resistance",
    frictionClue: "Bedtime meets resistance",
    offerHint: "Reduce bedtime resistance without turning it into a fight.",
  },
  {
    id: "313",
    bundleId: "sleep_energy",
    name: "Improve Morning Activation",
    frictionClue: "Mornings are hard to start",
    offerHint: "Improve morning activation with one gentle on-ramp.",
  },
  {
    id: "314",
    bundleId: "sleep_energy",
    name: "Manage Energy Transitions",
    frictionClue: "Energy drops between parts of the day",
    offerHint: "Manage energy transitions between parts of the day.",
  },
  {
    id: "315",
    bundleId: "sleep_energy",
    name: "Recover From Poor Sleep Days",
    frictionClue: "A poor sleep day needs a softer plan",
    offerHint: "Recover from a poor sleep day without pretending nothing changed.",
  },
  {
    id: "316",
    bundleId: "sleep_energy",
    name: "Use Light, Movement & Environment Wisely",
    frictionClue: "Light and movement are not supporting energy",
    offerHint: "Use light, movement, and environment to support energy.",
  },
  {
    id: "317",
    bundleId: "sleep_energy",
    name: "Prevent Evening Revenge Procrastination",
    frictionClue: "Evenings disappear into revenge procrastination",
    offerHint: "Prevent evening revenge procrastination with a softer wind-down.",
  },
  {
    id: "318",
    bundleId: "sleep_energy",
    name: "Build Sustainable Sleep Habits",
    frictionClue: "Sleep habits do not last",
    offerHint: "Build sustainable sleep habits that survive imperfect weeks.",
  },
  {
    id: "319",
    bundleId: "sleep_energy",
    name: "Match Daily Plans to Energy Levels",
    frictionClue: "Plans ignore actual energy",
    offerHint: "Match daily plans to real energy levels.",
  },
  {
    id: "320",
    bundleId: "sleep_energy",
    name: "Create a Personal Sleep & Energy Profile",
    frictionClue: "Spark Estate needs personalized sleep and energy knowledge",
    offerHint: "Build a sleep and energy profile from what actually restores you.",
  },

  // Bundle 33 — Learning, Reading & Information Management
  {
    id: "321",
    bundleId: "learning_information",
    name: "Read With a Question",
    frictionClue: "Reading lacks purpose or retention",
    offerHint: "Read with a question so attention has somewhere to land.",
  },
  {
    id: "322",
    bundleId: "learning_information",
    name: "Summarize Before Saving",
    frictionClue: "Saved information lacks context",
    offerHint: "Summarize before saving so later-you knows why it mattered.",
  },
  {
    id: "323",
    bundleId: "learning_information",
    name: "Turn Information Into a Next Action",
    frictionClue: "Learning is not becoming action",
    offerHint: "Turn information into one next action.",
  },
  {
    id: "324",
    bundleId: "learning_information",
    name: "Use Active Recall Instead of Re-Reading",
    frictionClue: "Re-reading is not improving recall",
    offerHint: "Use active recall instead of re-reading.",
  },
  {
    id: "325",
    bundleId: "learning_information",
    name: "Chunk Complex Information",
    frictionClue: "Complex information feels too large",
    offerHint: "Chunk complex information into smaller pieces.",
  },
  {
    id: "326",
    bundleId: "learning_information",
    name: "Limit Research Before It Becomes Overload",
    frictionClue: "Research has become endless",
    offerHint: "Limit research before it becomes overload.",
  },
  {
    id: "327",
    bundleId: "learning_information",
    name: "Create One Trusted Knowledge Home",
    frictionClue: "Knowledge is scattered",
    offerHint: "Create one trusted knowledge home instead of endless saves.",
  },
  {
    id: "328",
    bundleId: "learning_information",
    name: "Review Information at the Moment of Use",
    frictionClue: "Information is forgotten before use",
    offerHint: "Review information at the moment of use — not only when collecting.",
  },
  {
    id: "329",
    bundleId: "learning_information",
    name: "Teach It Back in Plain Language",
    frictionClue: "Understanding is uncertain",
    offerHint: "Teach it back in plain language to check understanding.",
  },
  {
    id: "330",
    bundleId: "learning_information",
    name: "Create a Personal Learning and Information Profile",
    frictionClue: "Spark Estate needs personalized learning knowledge",
    offerHint: "Build a learning profile from how you actually retain and use information.",
  },

  // Bundle 34 — Workplace, Career & Employment Support
  {
    id: "331",
    bundleId: "workplace_career",
    name: "Clarify What Good Work Looks Like",
    frictionClue: "Work expectations are vague",
    offerHint: "Clarify what good work looks like before grinding harder.",
  },
  {
    id: "332",
    bundleId: "workplace_career",
    name: "Make Workload and Priorities Visible",
    frictionClue: "The total workload is hidden",
    offerHint: "Make workload and priorities visible so nothing stays invisible.",
  },
  {
    id: "333",
    bundleId: "workplace_career",
    name: "Protect Focus in a Distracting Workplace",
    frictionClue: "The environment prevents sustained focus",
    offerHint: "Protect focus in a distracting workplace with practical boundaries.",
  },
  {
    id: "334",
    bundleId: "workplace_career",
    name: "Use Manager Check-Ins Strategically",
    frictionClue: "Priorities or blockers need manager input",
    offerHint: "Use manager check-ins strategically — short, clear, useful.",
  },
  {
    id: "335",
    bundleId: "workplace_career",
    name: "Request Practical Work Supports Without Oversharing",
    frictionClue: "Practical support is needed without oversharing",
    offerHint: "Request practical work supports without oversharing.",
  },
  {
    id: "336",
    bundleId: "workplace_career",
    name: "Recover After a Workplace Mistake",
    frictionClue: "A workplace mistake triggered shame or avoidance",
    offerHint: "Recover after a workplace mistake without letting shame take the wheel.",
  },
  {
    id: "337",
    bundleId: "workplace_career",
    name: "Prepare for Performance Reviews",
    frictionClue: "A review or promotion conversation is approaching",
    offerHint: "Prepare for performance reviews with evidence, not only anxiety.",
  },
  {
    id: "338",
    bundleId: "workplace_career",
    name: "Evaluate Role and Environment Fit",
    frictionClue: "The member is unsure whether the role or environment fits",
    offerHint: "Evaluate role and environment fit honestly.",
  },
  {
    id: "339",
    bundleId: "workplace_career",
    name: "Build a Career Transition Plan Without Panic",
    frictionClue: "A job or career change feels overwhelming",
    offerHint: "Build a career transition plan without panic.",
  },
  {
    id: "340",
    bundleId: "workplace_career",
    name: "Create a Personal Workplace and Career Profile",
    frictionClue: "Spark Estate needs personalized workplace knowledge",
    offerHint: "Build a workplace and career profile from what helps you do good work.",
  },

  // Bundle 35 — Asking for Help, Delegation & Accountability
  {
    id: "341",
    bundleId: "help_delegation",
    name: "Recognize When to Ask for Help",
    frictionClue: "The member is struggling alone unnecessarily",
    offerHint: "Recognize when to ask for help — struggling alone is not the only option.",
  },
  {
    id: "342",
    bundleId: "help_delegation",
    name: "Ask for Help Clearly and Specifically",
    frictionClue: "The help request is vague or indirect",
    offerHint: "Ask for help clearly and specifically.",
  },
  {
    id: "343",
    bundleId: "help_delegation",
    name: "Delegate Without Losing Control",
    frictionClue: "Work needs to be handed off safely",
    offerHint: "Delegate without losing control — clear handoff, clear ownership.",
  },
  {
    id: "344",
    bundleId: "help_delegation",
    name: "Choose the Right Accountability Partner",
    frictionClue: "Accountability feels controlling or mismatched",
    offerHint: "Choose an accountability partner who fits — not one who pressures.",
  },
  {
    id: "345",
    bundleId: "help_delegation",
    name: "Use Body Doubling Effectively",
    frictionClue: "Presence helps the member begin or continue",
    offerHint: "Use body doubling when presence helps you begin or continue.",
  },
  {
    id: "346",
    bundleId: "help_delegation",
    name: "Build Reliable Follow-Through Systems",
    frictionClue: "Help was given but follow-through is still unclear",
    offerHint: "Build follow-through systems so help turns into completion.",
  },
  {
    id: "347",
    bundleId: "help_delegation",
    name: "Recover After Dropping the Ball",
    frictionClue: "A promise or check-in was missed",
    offerHint: "Recover after dropping the ball — repair, then restart.",
  },
  {
    id: "348",
    bundleId: "help_delegation",
    name: "Prevent Overdependence on Others",
    frictionClue: "Support is becoming the only way to act",
    offerHint: "Prevent overdependence — support should strengthen you, not replace you.",
  },
  {
    id: "349",
    bundleId: "help_delegation",
    name: "Create a Sustainable Support Network",
    frictionClue: "One person is carrying too much support",
    offerHint: "Create a sustainable support network so one person is not carrying everything.",
  },
  {
    id: "350",
    bundleId: "help_delegation",
    name: "Create a Personal Accountability and Support Profile",
    frictionClue: "Spark Estate needs personalized support knowledge",
    offerHint: "Build an accountability and support profile from what actually helps you follow through.",
  },

  // Bundle 36 — Change, Disruption, Travel & Unexpected Events
  {
    id: "351",
    bundleId: "change_disruption",
    name: "Prepare for Unexpected Changes",
    frictionClue: "A likely disruption needs one simple fallback",
    offerHint: "Prepare for unexpected changes with one simple fallback.",
  },
  {
    id: "352",
    bundleId: "change_disruption",
    name: "Recover After Plans Change",
    frictionClue: "The original schedule no longer works",
    offerHint: "Recover after plans change without rebuilding the whole day from scratch.",
  },
  {
    id: "353",
    bundleId: "change_disruption",
    name: "Navigate Transitions Without Overwhelm",
    frictionClue: "Switching roles, tasks, or life phases is difficult",
    offerHint: "Navigate transitions without overwhelm — one bridge step at a time.",
  },
  {
    id: "354",
    bundleId: "change_disruption",
    name: "Travel With ADHD More Successfully",
    frictionClue: "Travel creates timing, packing, and recovery overload",
    offerHint: "Travel with ADHD more successfully — pack, timing, and recovery all planned lightly.",
  },
  {
    id: "355",
    bundleId: "change_disruption",
    name: "Handle Interruptions Without Losing Your Place",
    frictionClue: "An interruption erased the active task",
    offerHint: "Handle interruptions without losing your place.",
  },
  {
    id: "356",
    bundleId: "change_disruption",
    name: "Restart After Life Disruptions",
    frictionClue: "A major life event interrupted routines and projects",
    offerHint: "Restart after life disruptions gently — context first, then one step.",
  },
  {
    id: "357",
    bundleId: "change_disruption",
    name: "Create Flexible Backup Plans",
    frictionClue: "Rigid plans repeatedly collapse",
    offerHint: "Create flexible backup plans so rigid schedules stop breaking you.",
  },
  {
    id: "358",
    bundleId: "change_disruption",
    name: "Reduce Anxiety Around Uncertainty",
    frictionClue: "Uncertainty is consuming attention",
    offerHint: "Reduce anxiety around uncertainty with one known next move.",
  },
  {
    id: "359",
    bundleId: "change_disruption",
    name: "Build Change Resilience Over Time",
    frictionClue: "The member wants to learn from past changes",
    offerHint: "Build change resilience over time from what worked in past disruptions.",
  },
  {
    id: "360",
    bundleId: "change_disruption",
    name: "Create a Personal Change and Transition Profile",
    frictionClue: "Spark Estate needs personalized transition knowledge",
    offerHint: "Build a change and transition profile from how you recover when plans shift.",
  },
] as const;

export const ADHD_STRATEGY_BUNDLE_FILES = {
  activation:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_01_Combined.md",
  overwhelm:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_02_Combined.md",
  memory_time:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_03_Combined.md",
  emotion_burnout:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_04_Combined.md",
  hyperfocus_transitions:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_05_Combined.md",
  decision_making:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_06_Combined.md",
  planning_follow_through:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_07_Combined.md",
  returning_after_absence:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_08_Combined.md",
  emotional_safety:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_09_Combined.md",
  environment_sensory:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_10_Combined.md",
  communication_relationships:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_11_Combined.md",
  boring_tasks_motivation:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_12_Combined.md",
  time_awareness:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_13_Combined.md",
  decision_paralysis:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_14_Combined.md",
  working_memory:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_15_Combined.md",
  emotional_awareness:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_16_Combined.md",
  procrastination:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_17_Combined.md",
  perfectionism:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_18_Combined.md",
  motivation_momentum:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_19_Combined.md",
  organization_clutter:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_20_Combined.md",
  routines_habits:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_21_Combined.md",
  paperwork_admin:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_22_Combined.md",
  meetings_appointments:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_23_Combined.md",
  money_financial:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_24_Combined.md",
  client_follow_through:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_25_Combined.md",
  creativity_ideas:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_26_Combined.md",
  burnout_recovery:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_27_Combined.md",
  decision_fatigue:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_28_Combined.md",
  rejection_sensitivity:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_29_Combined.md",
  relationships_family:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_30_Combined.md",
  daily_living_home:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_31_Combined.md",
  sleep_energy:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_32_Combined.md",
  learning_information:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_33_Combined.md",
  workplace_career:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_34_Combined.md",
  help_delegation:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_35_Combined.md",
  change_disruption:
    "docs/intelligence/02_ADHD_Intelligence/everyday-strategies/Bundle_36_Combined.md",
} as const;
