/**
 * 053 — Event Capability Catalog
 * Authoritative Event Architect Studio domains → Capability Registry.
 * Capabilities ≠ asset types ≠ templates.
 */

import type { EventCapabilityDefinition } from "./types";

const ALL_FORMATS = { mode: "all" as const };
const PHYSICAL = {
  mode: "include" as const,
  formats: ["in_person" as const, "hybrid" as const],
};
const VIRTUALISH = {
  mode: "include" as const,
  formats: ["virtual" as const, "hybrid" as const],
};

/**
 * Canonical Event Capability Registry.
 * Grows with Events Intelligence expertise — never dump into workspace templates.
 */
export const EVENT_CAPABILITY_DEFINITIONS: readonly EventCapabilityDefinition[] =
  [
    {
      capabilityId: "cap_foundation_strategy",
      canonicalName: "Foundation & Strategy",
      userFacingName: "Foundation & Strategy",
      description:
        "Purpose, outcomes, viability, and the living event plan.",
      category: "foundation_strategy",
      knowledgeRefs: ["EI-K102", "EI-001", "EVENT-005"],
      relatedSectionIds: ["purpose", "audience", "outcomes", "event_type"],
      assetTypeIds: ["event_plan", "event_timeline"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["discovery", "viability", "strategy", "planning"],
      aliases: ["foundation", "strategy", "event plan"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_audience_experience",
      canonicalName: "Audience & Attendee Experience",
      userFacingName: "Attendee Experience",
      description:
        "Who is coming, how they feel arriving, and what they need along the way.",
      category: "audience_attendee_experience",
      knowledgeRefs: ["EI-K103", "EI-K110"],
      relatedSectionIds: ["audience", "attendee_experience", "hospitality"],
      assetTypeIds: ["welcome_guide", "packing_list", "attendee_workbook"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: [
        "strategy",
        "experience_design",
        "planning",
        "preparation",
      ],
      aliases: ["audience", "attendee experience", "guest experience"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_program_agenda",
      canonicalName: "Program & Agenda Architecture",
      userFacingName: "Program & Agenda",
      description: "Session flow, pacing, workbooks, and learning materials.",
      category: "program_agenda",
      knowledgeRefs: ["EI-K108"],
      relatedSectionIds: ["agenda"],
      assetTypeIds: [
        "agenda",
        "session_plans",
        "attendee_workbook",
        "presentation_deck",
      ],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["experience_design", "planning", "preparation"],
      aliases: ["agenda", "program", "sessions", "workbook"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_speakers_facilitators",
      canonicalName: "Speakers & Facilitators",
      userFacingName: "Speakers & Facilitators",
      description: "Speaker packets, agreements, bios, and facilitation support.",
      category: "speakers_facilitators",
      knowledgeRefs: ["EI-K301"],
      relatedSectionIds: ["speakers"],
      assetTypeIds: ["speaker_packet", "speaker_agreement", "speaker_bio"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["planning", "preparation"],
      aliases: ["speakers", "facilitators", "panelists"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_sponsors_partners",
      canonicalName: "Sponsorships & Partners",
      userFacingName: "Sponsorships",
      description: "Sponsor packages, fulfillment, and partnership alignment.",
      category: "sponsors_partners",
      knowledgeRefs: ["EI-K305", "EI-K306"],
      relatedSectionIds: ["sponsors"],
      assetTypeIds: ["sponsor_package"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["strategy", "planning", "preparation"],
      aliases: ["sponsors", "sponsorships", "partners"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_venue_physical",
      canonicalName: "Venue & Physical Space",
      userFacingName: "Venue",
      description: "Site selection, comparison, and contract notes.",
      category: "venue_physical",
      knowledgeRefs: ["EI-K203"],
      relatedSectionIds: ["venue"],
      assetTypeIds: ["venue_comparison", "venue_contract_notes"],
      formatApplicability: PHYSICAL,
      lifecyclePhases: ["viability", "planning", "preparation"],
      aliases: ["venue", "location", "site"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_virtual_hybrid_tech",
      canonicalName: "Virtual & Hybrid Technology",
      userFacingName: "Technology",
      description: "Platforms, AV, streaming, and tech checklists.",
      category: "virtual_hybrid_technology",
      knowledgeRefs: ["EI-K401"],
      relatedSectionIds: ["technology", "format"],
      assetTypeIds: ["technology_plan"],
      formatApplicability: VIRTUALISH,
      lifecyclePhases: ["planning", "preparation", "delivery"],
      aliases: ["technology", "virtual", "hybrid", "av"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_registration_ticketing",
      canonicalName: "Registration & Ticketing",
      userFacingName: "Registration",
      description: "Sign-up forms, confirmations, and reminders.",
      category: "registration_ticketing",
      knowledgeRefs: ["EI-K303"],
      relatedSectionIds: ["registration"],
      assetTypeIds: [
        "registration_form",
        "registration_confirmation_email",
        "registration_reminder_email",
      ],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["planning", "preparation", "delivery"],
      aliases: ["registration", "ticketing", "rsvp", "signup"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_marketing_promotion",
      canonicalName: "Marketing & Promotion",
      userFacingName: "Marketing",
      description: "Landing pages, campaigns, and promotional sequences.",
      category: "marketing_promotion",
      knowledgeRefs: ["EI-K304"],
      relatedSectionIds: ["marketing"],
      assetTypeIds: ["landing_page", "marketing_email_sequence"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["strategy", "planning", "preparation"],
      aliases: ["marketing", "promotion", "landing page"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_communications",
      canonicalName: "Communications",
      userFacingName: "Communications",
      description: "Attendee and stakeholder messaging around the event.",
      category: "communications",
      knowledgeRefs: ["EI-K304", "EVENT-008"],
      relatedSectionIds: ["communications"],
      assetTypeIds: [
        "registration_confirmation_email",
        "registration_reminder_email",
        "thank_you_message",
      ],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["planning", "preparation", "follow_up"],
      aliases: ["communications", "messaging", "emails"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_finance_budget",
      canonicalName: "Finance & Budgeting",
      userFacingName: "Budgeting",
      description: "Budgets, categories, and financial visibility.",
      category: "finance_budget",
      knowledgeRefs: ["EI-K204"],
      relatedSectionIds: ["budget"],
      assetTypeIds: ["event_budget"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["viability", "planning", "preparation", "follow_up"],
      aliases: ["budget", "budgeting", "finance", "cost"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_vendors_procurement",
      canonicalName: "Vendors & Procurement",
      userFacingName: "Vendors",
      description: "Vendor lists, briefs, and procurement tracking.",
      category: "vendors_procurement",
      knowledgeRefs: ["EI-K205"],
      relatedSectionIds: ["vendors"],
      assetTypeIds: ["vendor_list", "vendor_brief"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["planning", "preparation"],
      aliases: ["vendors", "procurement", "suppliers"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_staff_volunteers",
      canonicalName: "Staff & Volunteers",
      userFacingName: "Staff & Volunteers",
      description: "Guides, schedules, and role clarity for the team.",
      category: "staff_volunteers",
      knowledgeRefs: ["EI-K206"],
      relatedSectionIds: ["staff", "volunteers"],
      assetTypeIds: ["volunteer_guide", "volunteer_schedule"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["planning", "preparation", "delivery"],
      aliases: ["volunteers", "staff", "crew"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_hospitality_food",
      canonicalName: "Hospitality & Food",
      userFacingName: "Hospitality",
      description: "Care, comfort, and hospitality planning for attendees.",
      category: "hospitality_food",
      knowledgeRefs: ["EI-K110"],
      relatedSectionIds: ["hospitality"],
      assetTypeIds: ["welcome_guide", "packing_list"],
      formatApplicability: PHYSICAL,
      lifecyclePhases: ["planning", "preparation", "delivery"],
      aliases: ["hospitality", "food", "catering"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_travel_lodging",
      canonicalName: "Travel & Lodging",
      userFacingName: "Travel & Lodging",
      description: "Travel, lodging, and transport coordination.",
      category: "travel_lodging_transport",
      knowledgeRefs: ["EI-K203"],
      relatedSectionIds: ["hospitality", "attendee_experience"],
      assetTypeIds: ["packing_list", "welcome_guide"],
      formatApplicability: PHYSICAL,
      lifecyclePhases: ["planning", "preparation"],
      aliases: ["travel", "lodging", "hotel", "transport"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_accessibility_inclusion",
      canonicalName: "Accessibility & Inclusion",
      userFacingName: "Accessibility",
      description: "Cognitive and physical access planning for every format.",
      category: "accessibility_inclusion",
      knowledgeRefs: ["EI-K111"],
      relatedSectionIds: ["accessibility"],
      assetTypeIds: ["accessibility_plan"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["experience_design", "planning", "preparation"],
      aliases: ["accessibility", "inclusion", "ada", "cognitive access"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_safety_risk",
      canonicalName: "Safety & Risk Management",
      userFacingName: "Risk Management",
      description: "Risk registers, contingencies, and emergency plans.",
      category: "safety_risk_contingencies",
      knowledgeRefs: ["EI-K409", "EI-K410"],
      relatedSectionIds: ["safety", "contingencies"],
      assetTypeIds: ["emergency_plan"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["planning", "preparation", "delivery"],
      aliases: ["risk", "safety", "contingency", "emergency"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_supplies_signage_swag",
      canonicalName: "Supplies, Signage & Swag",
      userFacingName: "Supplies & Swag",
      description: "Materials, signage, and guest gifts.",
      category: "supplies_signage_swag",
      knowledgeRefs: ["EI-K207"],
      relatedSectionIds: ["supplies", "swag"],
      assetTypeIds: ["day_of_checklist", "packing_list"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["preparation", "delivery"],
      aliases: ["supplies", "signage", "swag", "materials"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_production_run_of_show",
      canonicalName: "Production & Run of Show",
      userFacingName: "Production",
      description: "Minute-by-minute production plans and day-of checklists.",
      category: "production_run_of_show",
      knowledgeRefs: ["EI-K405"],
      relatedSectionIds: ["production", "run_of_show"],
      assetTypeIds: ["run_of_show", "day_of_checklist"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["preparation", "delivery"],
      aliases: ["run of show", "production", "show flow"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_echo_command_center",
      canonicalName: "ECHO — Event Day Command Center",
      userFacingName: "ECHO Command Center",
      description:
        "Event-day command, incident awareness, and live coordination (Event Architect Studio).",
      category: "cross_cutting",
      knowledgeRefs: ["EI-K407", "EI-K409"],
      relatedSectionIds: ["run_of_show", "production", "safety", "contingencies"],
      assetTypeIds: ["run_of_show", "day_of_checklist", "emergency_plan"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["preparation", "delivery"],
      aliases: ["echo", "command center", "event day", "live ops"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_evaluation_feedback",
      canonicalName: "Evaluation & Feedback",
      userFacingName: "Feedback",
      description: "Surveys and measurement of the experience.",
      category: "evaluation_feedback",
      knowledgeRefs: ["EI-K502"],
      relatedSectionIds: ["measurement"],
      assetTypeIds: ["feedback_survey"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["preparation", "delivery", "follow_up", "debrief_reuse"],
      aliases: ["feedback", "survey", "evaluation", "measurement"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_follow_up_relationship",
      canonicalName: "Follow-Up & Relationships",
      userFacingName: "Follow-Up",
      description: "Thank-yous and relationship continuity after the gathering.",
      category: "follow_up_relationship",
      knowledgeRefs: ["EI-K501"],
      relatedSectionIds: ["post_event_follow_up"],
      assetTypeIds: ["thank_you_message"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["follow_up", "debrief_reuse"],
      aliases: ["follow-up", "thank you", "aftercare"],
      status: "active",
      version: "053.1",
    },
    {
      capabilityId: "cap_debrief_archive_reuse",
      canonicalName: "Debrief, Archive & Reuse",
      userFacingName: "Debrief & Archive",
      description: "Learning capture, archive packages, and safe reuse.",
      category: "debrief_archive_reuse",
      knowledgeRefs: ["EI-K503", "EI-K504"],
      relatedSectionIds: ["archive_and_reuse", "measurement"],
      assetTypeIds: ["debrief_report", "archive_package"],
      formatApplicability: ALL_FORMATS,
      lifecyclePhases: ["follow_up", "debrief_reuse"],
      aliases: ["debrief", "archive", "reuse"],
      status: "active",
      version: "053.1",
    },
  ];
