import type { ObjectSeed } from "./builder";

export const BUSINESS_OBJECT_SEEDS: ObjectSeed[] = [
  { id: "obj-planning-notebook", name: "Planning notebook", emotionalPurpose: "Build with clarity", collection: "business", primaryRoom: "planning-table", material: "leather" },
  { id: "obj-wall-calendar", name: "Wall calendar", emotionalPurpose: "Time visible", collection: "business", primaryRoom: "business-office", material: "paper", seasonalVariants: ["new-year", "mid-year-refresh"] },
  { id: "obj-clipboard", name: "Clipboard", emotionalPurpose: "Portable focus", collection: "business", primaryRoom: "business-office", material: "wood" },
  { id: "obj-marketing-notebook", name: "Marketing notebook", emotionalPurpose: "Audience in mind", collection: "business", primaryRoom: "business-office", material: "linen" },
  { id: "obj-laptop-closed", name: "Closed laptop", emotionalPurpose: "Work paused", collection: "business", primaryRoom: "business-office", material: "brass", illustrationNotes: "Illustrated as warm-toned laptop with leather sleeve — never glossy tech chrome" },
  { id: "obj-whiteboard", name: "Whiteboard with notes", emotionalPurpose: "Think out loud", collection: "business", primaryRoom: "business-office", material: "glass" },
  { id: "obj-microphone", name: "Desk microphone", emotionalPurpose: "Voice going out", collection: "business", primaryRoom: "focus-studio", material: "brass" },
  { id: "obj-camera", name: "Camera on strap", emotionalPurpose: "Capture the work", collection: "business", primaryRoom: "creative-studio", material: "leather" },
  { id: "obj-business-cards", name: "Business card stack", emotionalPurpose: "Introduction ready", collection: "business", primaryRoom: "business-office", material: "paper" },
  { id: "obj-desk-organizer", name: "Desk organizer", emotionalPurpose: "Order without sterility", collection: "business", primaryRoom: "business-office", material: "wood" },
  { id: "obj-stapler", name: "Stapler", emotionalPurpose: "Bind it", collection: "business", primaryRoom: "business-office", material: "iron" },
  { id: "obj-hole-punch", name: "Hole punch", emotionalPurpose: "File it", collection: "business", primaryRoom: "business-office", material: "iron" },
  { id: "obj-file-folders", name: "File folder stack", emotionalPurpose: "Projects contained", collection: "business", primaryRoom: "business-office", material: "paper" },
  { id: "obj-label-maker", name: "Label maker", emotionalPurpose: "Name what matters", collection: "business", primaryRoom: "workshop", material: "ceramic", illustrationNotes: "Rendered as matte ceramic-tone — not plastic gloss" },
  { id: "obj-calculator", name: "Calculator", emotionalPurpose: "Numbers honest", collection: "business", primaryRoom: "business-office", material: "ceramic", illustrationNotes: "Vintage-style calculator in warm tones" },
  { id: "obj-receipt-envelope", name: "Receipt envelope", emotionalPurpose: "Track gently", collection: "business", primaryRoom: "business-office", material: "paper" },
  { id: "obj-invoice-pad", name: "Invoice pad", emotionalPurpose: "Value exchanged", collection: "business", primaryRoom: "business-office", material: "paper" },
  { id: "obj-contract-folder", name: "Contract folder", emotionalPurpose: "Serious agreements", collection: "business", primaryRoom: "business-office", material: "leather" },
  { id: "obj-presentation-remote", name: "Presentation remote", emotionalPurpose: "Share the story", collection: "business", primaryRoom: "business-office", material: "wood" },
  { id: "obj-headphones-business", name: "Premium headphones", emotionalPurpose: "Deep focus", collection: "business", primaryRoom: "focus-studio", material: "leather", featureObjectId: "focus-studio" },
  { id: "obj-monitor-stand", name: "Monitor stand", emotionalPurpose: "Eye-level care", collection: "business", primaryRoom: "business-office", material: "wood" },
  { id: "obj-desk-lamp", name: "Brass desk lamp", emotionalPurpose: "Light where needed", collection: "business", primaryRoom: "business-office", material: "brass" },
  { id: "obj-cork-board", name: "Cork board", emotionalPurpose: "Pin the plan", collection: "business", primaryRoom: "planning-table", material: "cotton" },
  { id: "obj-timer-cube", name: "Timer cube", emotionalPurpose: "Bounded work", collection: "business", primaryRoom: "focus-studio", material: "wood" },
  { id: "obj-focus-timer", name: "Focus timer", emotionalPurpose: "One block at a time", collection: "business", primaryRoom: "focus-studio", material: "ceramic", featureObjectId: "focus-session" },
  { id: "obj-client-folder", name: "Client folder", emotionalPurpose: "Someone specific", collection: "business", primaryRoom: "business-office", material: "linen" },
  { id: "obj-brand-guide-book", name: "Brand guide book", emotionalPurpose: "Consistency", collection: "business", primaryRoom: "creative-studio", material: "linen" },
  { id: "obj-printer-paper", name: "Printer paper stack", emotionalPurpose: "Make it real", collection: "business", primaryRoom: "business-office", material: "paper" },
  { id: "obj-shipping-boxes", name: "Shipping boxes", emotionalPurpose: "Send it out", collection: "business", primaryRoom: "workshop", material: "paper" },
  { id: "obj-packing-tape", name: "Packing tape dispenser", emotionalPurpose: "Seal and ship", collection: "business", primaryRoom: "workshop", material: "wood" },
  { id: "obj-goal-chart", name: "Goal chart on wall", emotionalPurpose: "Direction visible", collection: "business", primaryRoom: "planning-table", material: "paper" },
  { id: "obj-vision-board", name: "Vision board", emotionalPurpose: "Future felt", collection: "business", primaryRoom: "creative-studio", material: "cotton" },
];
