import type { ObjectSeed } from "./builder";

export const COFFEE_COMFORT_OBJECT_SEEDS: ObjectSeed[] = [
  { id: "obj-shari-signature-mug", name: "Shari's signature mug", emotionalPurpose: "Welcome", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "ceramic", featureObjectId: "todays-reality", animationCapability: true, animation: "steam", seasonalVariants: ["winter-cocoa", "summer-iced-tea", "autumn-pumpkin-spice", "spring-wildflower-motif"], accessibilityDescription: "Cream ceramic mug with gentle steam rising — Shari's everyday welcome" },
  { id: "obj-tea-cup-saucer", name: "Tea cup and saucer", emotionalPurpose: "Quiet pause", collection: "coffee-comfort", primaryRoom: "reading-nook", material: "ceramic", animationCapability: true, animation: "steam" },
  { id: "obj-french-press", name: "French press", emotionalPurpose: "Ritual and patience", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "glass", animationCapability: true, animation: "steam" },
  { id: "obj-wooden-tray", name: "Wooden tray", emotionalPurpose: "Carried care", collection: "coffee-comfort", primaryRoom: "living-room", material: "wood" },
  { id: "obj-cookie-plate", name: "Cookie plate", emotionalPurpose: "Small sweetness", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "ceramic" },
  { id: "obj-coaster-set", name: "Coaster set", emotionalPurpose: "Thoughtful details", collection: "coffee-comfort", primaryRoom: "living-room", material: "linen" },
  { id: "obj-throw-blanket", name: "Throw blanket", emotionalPurpose: "Comfort", collection: "coffee-comfort", primaryRoom: "living-room", material: "wool", seasonalVariants: ["winter-heavy-knit", "summer-light-linen"] },
  { id: "obj-throw-pillow", name: "Throw pillow", emotionalPurpose: "Settle in", collection: "coffee-comfort", primaryRoom: "living-room", material: "linen" },
  { id: "obj-reading-glasses", name: "Reading glasses", emotionalPurpose: "See clearly", collection: "coffee-comfort", primaryRoom: "reading-nook", material: "glass" },
  { id: "obj-taper-candle", name: "Taper candle", emotionalPurpose: "Soft evening", collection: "coffee-comfort", primaryRoom: "living-room", material: "cotton", animationCapability: true, animation: "flicker", seasonalVariants: ["holiday-candle", "autumn-spice"] },
  { id: "obj-tea-kettle", name: "Tea kettle", emotionalPurpose: "Something brewing", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "copper", animationCapability: true, animation: "steam" },
  { id: "obj-coffee-grinder", name: "Coffee grinder", emotionalPurpose: "Morning ritual", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "wood" },
  { id: "obj-milk-pitcher", name: "Milk pitcher", emotionalPurpose: "Shared table", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "ceramic" },
  { id: "obj-honey-jar", name: "Honey jar", emotionalPurpose: "Golden warmth", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "glass" },
  { id: "obj-sugar-bowl", name: "Sugar bowl", emotionalPurpose: "Small indulgence", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "ceramic" },
  { id: "obj-tea-tin", name: "Tea tin collection", emotionalPurpose: "Choices and calm", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "copper" },
  { id: "obj-thermos", name: "Thermos", emotionalPurpose: "Warmth on the go", collection: "coffee-comfort", primaryRoom: "garden-path", material: "brass" },
  { id: "obj-porch-swing-cushion", name: "Porch swing cushion", emotionalPurpose: "Arrival rest", collection: "coffee-comfort", primaryRoom: "front-porch", material: "cotton" },
  { id: "obj-hot-cocoa-mug", name: "Winter cocoa mug", emotionalPurpose: "Cold-day welcome", collection: "coffee-comfort", primaryRoom: "fire-circle", material: "ceramic", animationCapability: true, animation: "steam", seasonalVariants: ["winter-only"] },
  { id: "obj-iced-tea-glass", name: "Iced tea glass", emotionalPurpose: "Summer ease", collection: "coffee-comfort", primaryRoom: "back-deck", material: "glass", seasonalVariants: ["summer-only"] },
  { id: "obj-lap-desk", name: "Lap desk", emotionalPurpose: "Work from the couch", collection: "coffee-comfort", primaryRoom: "living-room", material: "wood" },
  { id: "obj-slippers", name: "Wool slippers", emotionalPurpose: "Take off the day", collection: "coffee-comfort", primaryRoom: "living-room", material: "wool" },
  { id: "obj-hot-water-bottle", name: "Hot water bottle", emotionalPurpose: "Gentle recovery", collection: "coffee-comfort", primaryRoom: "reading-nook", material: "cotton" },
  { id: "obj-soup-bowl", name: "Soup bowl", emotionalPurpose: "Nourishment", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "ceramic", animationCapability: true, animation: "steam" },
  { id: "obj-bread-board", name: "Bread board with loaf", emotionalPurpose: "Homemade welcome", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "wood" },
  { id: "obj-butter-dish", name: "Butter dish", emotionalPurpose: "Morning table", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "ceramic" },
  { id: "obj-napkin-rings", name: "Napkin rings", emotionalPurpose: "Gathered table", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "brass" },
  { id: "obj-votive-candles", name: "Votive candles", emotionalPurpose: "Low light calm", collection: "coffee-comfort", primaryRoom: "living-room", material: "glass", animationCapability: true, animation: "flicker" },
  { id: "obj-cashmere-wrap", name: "Cashmere wrap", emotionalPurpose: "Wrapped safety", collection: "coffee-comfort", primaryRoom: "window-seat", material: "wool" },
  { id: "obj-window-seat-cushion", name: "Window seat cushion", emotionalPurpose: "Look out and breathe", collection: "coffee-comfort", primaryRoom: "window-seat", material: "linen" },
  { id: "obj-morning-newspaper", name: "Folded newspaper", emotionalPurpose: "Slow morning", collection: "coffee-comfort", primaryRoom: "kitchen-table", material: "paper" },
  { id: "obj-espresso-cup", name: "Espresso cup", emotionalPurpose: "Quick courage", collection: "coffee-comfort", primaryRoom: "business-office", material: "ceramic" },
];
