import type { ObjectSeed } from "./builder";

export const CREATIVE_OBJECT_SEEDS: ObjectSeed[] = [
  { id: "obj-crochet-basket", name: "Crochet basket", emotionalPurpose: "Creativity", collection: "creative", primaryRoom: "creative-studio", material: "wicker" },
  { id: "obj-yarn-skeins", name: "Yarn skeins", emotionalPurpose: "Color waiting", collection: "creative", primaryRoom: "creative-studio", material: "cotton" },
  { id: "obj-bead-tray", name: "Bead tray", emotionalPurpose: "Tiny possibilities", collection: "creative", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-journal-cover", name: "Handmade journal cover", emotionalPurpose: "Personal craft", collection: "creative", primaryRoom: "creative-studio", material: "leather" },
  { id: "obj-watercolor-set", name: "Watercolor set", emotionalPurpose: "Soft expression", collection: "creative", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-paint-brushes", name: "Paint brushes in jar", emotionalPurpose: "Tools of making", collection: "creative", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-colored-pencils", name: "Colored pencils", emotionalPurpose: "Playful precision", collection: "creative", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-fabric-scissors", name: "Fabric scissors", emotionalPurpose: "Clean cuts", collection: "creative", primaryRoom: "workshop", material: "iron" },
  { id: "obj-glue-stick", name: "Glue and tape caddy", emotionalPurpose: "Hold it together", collection: "creative", primaryRoom: "workshop", material: "wood" },
  { id: "obj-linen-fabric", name: "Linen fabric stack", emotionalPurpose: "Texture choices", collection: "creative", primaryRoom: "workshop", material: "linen" },
  { id: "obj-ribbon-spools", name: "Ribbon spools", emotionalPurpose: "Finishing touch", collection: "creative", primaryRoom: "creative-studio", material: "cotton" },
  { id: "obj-craft-box", name: "Craft box", emotionalPurpose: "Everything for making", collection: "creative", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-crochet-hook-set", name: "Crochet hook set", emotionalPurpose: "Rhythmic making", collection: "creative", primaryRoom: "living-room", material: "wood" },
  { id: "obj-knitting-needles", name: "Knitting needles", emotionalPurpose: "Steady progress", collection: "creative", primaryRoom: "living-room", material: "wood" },
  { id: "obj-half-finished-scarf", name: "Half-finished scarf", emotionalPurpose: "Imperfect progress", collection: "creative", primaryRoom: "living-room", material: "wool" },
  { id: "obj-sewing-machine", name: "Sewing machine", emotionalPurpose: "Serious craft", collection: "creative", primaryRoom: "workshop", material: "iron" },
  { id: "obj-pin-cushion", name: "Pin cushion", emotionalPurpose: "Ready pins", collection: "creative", primaryRoom: "workshop", material: "cotton" },
  { id: "obj-measuring-tape", name: "Measuring tape", emotionalPurpose: "Fit and form", collection: "creative", primaryRoom: "workshop", material: "cotton" },
  { id: "obj-cutting-mat", name: "Cutting mat", emotionalPurpose: "Protected surface", collection: "creative", primaryRoom: "workshop", material: "cotton" },
  { id: "obj-stamp-collection", name: "Rubber stamp collection", emotionalPurpose: "Repeatable art", collection: "creative", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-ink-pads", name: "Ink pads", emotionalPurpose: "Color blocks", collection: "creative", primaryRoom: "creative-studio", material: "cotton" },
  { id: "obj-sketchbook", name: "Sketchbook", emotionalPurpose: "Rough drafts welcome", collection: "creative", primaryRoom: "creative-studio", material: "paper" },
  { id: "obj-charcoal-sticks", name: "Charcoal sticks", emotionalPurpose: "Bold marks", collection: "creative", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-easel", name: "Wooden easel", emotionalPurpose: "Work standing up", collection: "creative", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-palette-knife", name: "Palette knife", emotionalPurpose: "Texture on canvas", collection: "creative", primaryRoom: "creative-studio", material: "iron" },
  { id: "obj-clay-lump", name: "Clay on board", emotionalPurpose: "Shape from nothing", collection: "creative", primaryRoom: "workshop", material: "stone" },
  { id: "obj-pottery-wheel", name: "Pottery wheel", emotionalPurpose: "Centered making", collection: "creative", primaryRoom: "workshop", material: "stone", futureExpansion: "Workshop hero scene" },
  { id: "obj-glaze-jars", name: "Glaze jars", emotionalPurpose: "Finish choices", collection: "creative", primaryRoom: "workshop", material: "glass" },
  { id: "obj-macrame-hanger", name: "Macramé plant hanger", emotionalPurpose: "Hand-tied beauty", collection: "creative", primaryRoom: "creative-studio", material: "cotton" },
  { id: "obj-embroidery-hoop", name: "Embroidery hoop", emotionalPurpose: "Stitched patience", collection: "creative", primaryRoom: "living-room", material: "wood" },
  { id: "obj-felt-sheets", name: "Felt sheet stack", emotionalPurpose: "Soft construction", collection: "creative", primaryRoom: "workshop", material: "wool" },
  { id: "obj-washi-tape", name: "Washi tape collection", emotionalPurpose: "Gentle color", collection: "creative", primaryRoom: "planning-table", material: "paper" },
  { id: "obj-sticker-sheets", name: "Sticker sheets", emotionalPurpose: "Playful marking", collection: "creative", primaryRoom: "planning-table", material: "paper" },
  { id: "obj-mood-board", name: "Mood board on cork", emotionalPurpose: "See the vision", collection: "creative", primaryRoom: "creative-studio", material: "cotton" },
  { id: "obj-inspiration-clips", name: "Inspiration clothespins", emotionalPurpose: "Ideas on a line", collection: "creative", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-calligraphy-ink", name: "Calligraphy ink set", emotionalPurpose: "Letter as art", collection: "creative", primaryRoom: "creative-studio", material: "glass" },
  { id: "obj-gel-pens", name: "Gel pen cup", emotionalPurpose: "Bright notes", collection: "creative", primaryRoom: "planning-table", material: "ceramic" },
  { id: "obj-puzzle-box", name: "Puzzle box", emotionalPurpose: "Patient play", collection: "creative", primaryRoom: "living-room", material: "wood" },
];
