import type { ObjectSeed } from "./builder";

export const HOME_OBJECT_SEEDS: ObjectSeed[] = [
  { id: "obj-fireplace", name: "Fireplace", emotionalPurpose: "Hearth and warmth", collection: "home", primaryRoom: "living-room", material: "stone", animationCapability: true, animation: "flicker", seasonalVariants: ["winter-active", "autumn-first-fire"] },
  { id: "obj-mantel-clock", name: "Mantel clock", emotionalPurpose: "Steady time", collection: "home", primaryRoom: "living-room", material: "wood", animationCapability: true, animation: "pendulum" },
  { id: "obj-kitchen-towel", name: "Kitchen towel", emotionalPurpose: "Hands dried with care", collection: "home", primaryRoom: "kitchen-table", material: "linen" },
  { id: "obj-wooden-spoon", name: "Wooden spoon", emotionalPurpose: "Cooking as love", collection: "home", primaryRoom: "kitchen-table", material: "wood" },
  { id: "obj-fresh-flowers", name: "Fresh flowers in pitcher", emotionalPurpose: "Care", collection: "home", primaryRoom: "kitchen-table", material: "glass", seasonalVariants: ["spring-tulips", "summer-zinnias", "autumn-chrysanthemums"] },
  { id: "obj-fruit-bowl", name: "Fruit bowl", emotionalPurpose: "Abundance on the table", collection: "home", primaryRoom: "kitchen-table", material: "ceramic" },
  { id: "obj-watering-can-home", name: "Copper watering can", emotionalPurpose: "Tend the home", collection: "home", primaryRoom: "garden", material: "copper" },
  { id: "obj-porch-lantern", name: "Front porch lantern", emotionalPurpose: "Light for arrival", collection: "home", primaryRoom: "front-porch", material: "iron", animationCapability: true, animation: "flicker", seasonalVariants: ["winter-snow-glow", "summer-moth-light"] },
  { id: "obj-rocking-chair", name: "Rocking chair", emotionalPurpose: "Rhythm and rest", collection: "home", primaryRoom: "front-porch", material: "wood" },
  { id: "obj-entry-bench", name: "Entry bench", emotionalPurpose: "Take off your coat", collection: "home", primaryRoom: "front-porch", material: "wood" },
  { id: "obj-coat-hooks", name: "Coat hooks", emotionalPurpose: "Belonging", collection: "home", primaryRoom: "front-porch", material: "iron" },
  { id: "obj-boot-tray", name: "Boot tray", emotionalPurpose: "Iowa practical", collection: "home", primaryRoom: "front-porch", material: "iron", seasonalVariants: ["winter-snow-melt"] },
  { id: "obj-welcome-mat", name: "Welcome mat", emotionalPurpose: "Arrival acknowledged", collection: "home", primaryRoom: "front-porch", material: "cotton" },
  { id: "obj-key-bowl", name: "Key bowl", emotionalPurpose: "You're home", collection: "home", primaryRoom: "living-room", material: "ceramic" },
  { id: "obj-mail-basket", name: "Mail basket", emotionalPurpose: "Life arriving", collection: "home", primaryRoom: "kitchen-table", material: "wicker" },
  { id: "obj-cookie-jar", name: "Cookie jar", emotionalPurpose: "Help yourself", collection: "home", primaryRoom: "kitchen-table", material: "ceramic" },
  { id: "obj-cutting-board", name: "Cutting board", emotionalPurpose: "Prep with care", collection: "home", primaryRoom: "kitchen-table", material: "wood" },
  { id: "obj-cast-iron-skillet", name: "Cast iron skillet", emotionalPurpose: "Heirloom cooking", collection: "home", primaryRoom: "kitchen-table", material: "iron" },
  { id: "obj-mixing-bowl", name: "Mixing bowl", emotionalPurpose: "Something baking", collection: "home", primaryRoom: "kitchen-table", material: "ceramic" },
  { id: "obj-recipe-stand", name: "Recipe stand", emotionalPurpose: "Follow along", collection: "home", primaryRoom: "kitchen-table", material: "wood" },
  { id: "obj-dish-towel-stack", name: "Dish towel stack", emotionalPurpose: "Clean and ready", collection: "home", primaryRoom: "kitchen-table", material: "linen" },
  { id: "obj-vintage-radio", name: "Vintage radio", emotionalPurpose: "Music from another era", collection: "home", primaryRoom: "living-room", material: "wood" },
  { id: "obj-record-player", name: "Record player", emotionalPurpose: "Slow listening", collection: "home", primaryRoom: "living-room", material: "wood" },
  { id: "obj-piano-bench", name: "Piano bench", emotionalPurpose: "Music in the house", collection: "home", primaryRoom: "living-room", material: "wood" },
  { id: "obj-family-photos", name: "Family photo frames", emotionalPurpose: "Who lives here", collection: "home", primaryRoom: "living-room", material: "wood" },
  { id: "obj-grandmother-quilt", name: "Grandmother's quilt", emotionalPurpose: "Generations of care", collection: "home", primaryRoom: "living-room", material: "cotton" },
  { id: "obj-basket-by-fire", name: "Log basket", emotionalPurpose: "Fuel for warmth", collection: "home", primaryRoom: "fire-circle", material: "wicker", seasonalVariants: ["winter-full"] },
  { id: "obj-fireplace-tools", name: "Fireplace tools", emotionalPurpose: "Tend the flame", collection: "home", primaryRoom: "fire-circle", material: "iron" },
  { id: "obj-seasonal-wreath", name: "Seasonal wreath", emotionalPurpose: "Door honors the season", collection: "home", primaryRoom: "front-porch", material: "cotton", seasonalVariants: ["spring-greenery", "summer-lavender", "autumn-wheat", "winter-evergreen"] },
  { id: "obj-porch-planters", name: "Porch planters", emotionalPurpose: "Life at the threshold", collection: "home", primaryRoom: "front-porch", material: "pottery", seasonalVariants: ["spring-pansies", "summer-petunias", "autumn-mums"] },
  { id: "obj-hall-mirror", name: "Hall mirror", emotionalPurpose: "Check before you go", collection: "home", primaryRoom: "living-room", material: "glass" },
  { id: "obj-umbrella-stand", name: "Umbrella stand", emotionalPurpose: "Rain ready", collection: "home", primaryRoom: "front-porch", material: "ceramic" },
  { id: "obj-broom-dustpan", name: "Broom and dustpan", emotionalPurpose: "Cared-for floors", collection: "home", primaryRoom: "kitchen-table", material: "wood" },
  { id: "obj-laundry-basket", name: "Laundry basket", emotionalPurpose: "Life in progress", collection: "home", primaryRoom: "future-wings", material: "wicker" },
  { id: "obj-sewing-kit", name: "Sewing kit", emotionalPurpose: "Small repairs", collection: "home", primaryRoom: "living-room", material: "wicker" },
  { id: "obj-first-aid-kit", name: "First aid kit", emotionalPurpose: "Prepared care", collection: "home", primaryRoom: "kitchen-table", material: "linen" },
  { id: "obj-flashlight", name: "Flashlight on hook", emotionalPurpose: "Power-out ready", collection: "home", primaryRoom: "kitchen-table", material: "iron" },
  { id: "obj-board-games", name: "Board game stack", emotionalPurpose: "Play together", collection: "home", primaryRoom: "living-room", material: "paper" },
];
