import type { ObjectSeed } from "./builder";

export const NATURE_OBJECT_SEEDS: ObjectSeed[] = [
  { id: "obj-hummingbird", name: "Hummingbird", emotionalPurpose: "Delicate hope", collection: "nature", primaryRoom: "garden", material: "glass", animationCapability: true, animation: "bird-visit", accessibilityDescription: "Ruby-throated hummingbird hovering near feeder" },
  { id: "obj-cardinal", name: "Cardinal", emotionalPurpose: "Winter brightness", collection: "nature", primaryRoom: "garden", material: "glass", animationCapability: true, animation: "bird-visit", seasonalVariants: ["winter-snow-branch"] },
  { id: "obj-goldfinch", name: "Goldfinch", emotionalPurpose: "Summer joy", collection: "nature", primaryRoom: "garden", material: "glass", animationCapability: true, animation: "bird-visit", seasonalVariants: ["summer-sunflower"] },
  { id: "obj-butterfly", name: "Butterfly", emotionalPurpose: "Gentle transformation", collection: "nature", primaryRoom: "garden-path", material: "glass", animationCapability: true, animation: "sway", seasonalVariants: ["spring-migration"] },
  { id: "obj-dragonfly", name: "Dragonfly", emotionalPurpose: "Stillness over water", collection: "nature", primaryRoom: "back-deck", material: "glass", seasonalVariants: ["summer-pond"] },
  { id: "obj-wildflower-bouquet", name: "Wildflower bouquet", emotionalPurpose: "Care", collection: "nature", primaryRoom: "kitchen-table", material: "cotton", seasonalVariants: ["spring-meadow", "summer-field"] },
  { id: "obj-lavender-bundle", name: "Lavender bundle", emotionalPurpose: "Calm scent", collection: "nature", primaryRoom: "window-seat", material: "cotton", seasonalVariants: ["summer-drying"] },
  { id: "obj-sunflowers", name: "Sunflowers in jar", emotionalPurpose: "Bold warmth", collection: "nature", primaryRoom: "kitchen-table", material: "glass", seasonalVariants: ["late-summer"] },
  { id: "obj-herb-basket", name: "Herb basket", emotionalPurpose: "Fresh and useful", collection: "nature", primaryRoom: "kitchen-table", material: "wicker", seasonalVariants: ["spring-basil", "summer-rosemary", "autumn-sage"] },
  { id: "obj-potted-fern", name: "Potted fern", emotionalPurpose: "Quiet growth", collection: "nature", primaryRoom: "reading-nook", material: "pottery", animationCapability: true, animation: "sway" },
  { id: "obj-bird-feeder", name: "Bird feeder", emotionalPurpose: "Hope at the window", collection: "nature", primaryRoom: "garden", material: "wood", seasonalVariants: ["winter-seed-heavy", "spring-refill"] },
  { id: "obj-watering-can", name: "Watering can", emotionalPurpose: "Tending life", collection: "nature", primaryRoom: "greenhouse", material: "copper", featureObjectId: "garden" },
  { id: "obj-garden-gloves", name: "Garden gloves", emotionalPurpose: "Hands in soil", collection: "nature", primaryRoom: "garden", material: "cotton" },
  { id: "obj-seed-packets", name: "Seed packet collection", emotionalPurpose: "Future blooms", collection: "nature", primaryRoom: "greenhouse", material: "paper" },
  { id: "obj-terrarium", name: "Terrarium", emotionalPurpose: "Contained world", collection: "nature", primaryRoom: "creative-studio", material: "glass" },
  { id: "obj-moss-stone", name: "Mossy garden stone", emotionalPurpose: "Patience", collection: "nature", primaryRoom: "garden-path", material: "stone" },
  { id: "obj-wind-chimes", name: "Wind chimes", emotionalPurpose: "Breeze remembered", collection: "nature", primaryRoom: "back-deck", material: "copper", animationCapability: true, animation: "sway" },
  { id: "obj-bee-on-lavender", name: "Bee on lavender", emotionalPurpose: "Working harmony", collection: "nature", primaryRoom: "garden", material: "glass", seasonalVariants: ["summer"] },
  { id: "obj-maple-leaf", name: "Maple leaf cluster", emotionalPurpose: "Autumn release", collection: "nature", primaryRoom: "front-porch", material: "cotton", seasonalVariants: ["autumn-only"] },
  { id: "obj-pumpkin", name: "Pumpkin on porch", emotionalPurpose: "Harvest welcome", collection: "nature", primaryRoom: "front-porch", material: "cotton", seasonalVariants: ["autumn-only"] },
  { id: "obj-evergreen-spray", name: "Evergreen door spray", emotionalPurpose: "Winter welcome", collection: "nature", primaryRoom: "front-porch", material: "cotton", seasonalVariants: ["winter-holiday"] },
  { id: "obj-prairie-grass", name: "Prairie grass bundle", emotionalPurpose: "Iowa horizon", collection: "nature", primaryRoom: "outlook-point", material: "cotton" },
  { id: "obj-river-stones", name: "River stone bowl", emotionalPurpose: "Grounding weight", collection: "nature", primaryRoom: "living-room", material: "stone" },
  { id: "obj-bird-nest", name: "Empty bird nest", emotionalPurpose: "Cycles of home", collection: "nature", primaryRoom: "garden", material: "wicker", seasonalVariants: ["spring"] },
  { id: "obj-dried-wheat", name: "Dried wheat sheaf", emotionalPurpose: "Harvest gratitude", collection: "nature", primaryRoom: "barn", material: "cotton", seasonalVariants: ["autumn"] },
  { id: "obj-ivy-trail", name: "Ivy in clay pot", emotionalPurpose: "Trailing life", collection: "nature", primaryRoom: "library", material: "pottery", animationCapability: true, animation: "sway" },
  { id: "obj-succulent-tray", name: "Succulent tray", emotionalPurpose: "Low-maintenance beauty", collection: "nature", primaryRoom: "business-office", material: "pottery" },
  { id: "obj-rain-barrel", name: "Rain barrel", emotionalPurpose: "Practical care", collection: "nature", primaryRoom: "garden", material: "wood" },
  { id: "obj-compost-bin", name: "Compost pail", emotionalPurpose: "Return to soil", collection: "nature", primaryRoom: "garden", material: "copper" },
  { id: "obj-garden-trowel", name: "Garden trowel", emotionalPurpose: "Small beginnings", collection: "nature", primaryRoom: "greenhouse", material: "iron" },
  { id: "obj-pruning-shears", name: "Pruning shears", emotionalPurpose: "Gentle editing", collection: "nature", primaryRoom: "garden", material: "iron" },
  { id: "obj-bird-bath", name: "Bird bath", emotionalPurpose: "Shared resource", collection: "nature", primaryRoom: "garden", material: "stone", animationCapability: true, animation: "water-ripple", seasonalVariants: ["summer"] },
  { id: "obj-firefly-jar", name: "Firefly jar (empty)", emotionalPurpose: "Summer memory", collection: "nature", primaryRoom: "back-deck", material: "glass", seasonalVariants: ["summer-evening"] },
  { id: "obj-snowflake-window", name: "Frost on windowpane", emotionalPurpose: "Quiet winter", collection: "nature", primaryRoom: "window-seat", material: "glass", seasonalVariants: ["winter-only"] },
  { id: "obj-cherry-blossom", name: "Cherry blossom branch", emotionalPurpose: "Brief beauty", collection: "nature", primaryRoom: "garden", material: "wood", seasonalVariants: ["spring-only"] },
  { id: "obj-mushroom-log", name: "Mushroom on log", emotionalPurpose: "Forest edge", collection: "nature", primaryRoom: "garden-path", material: "wood", seasonalVariants: ["autumn"] },
  { id: "obj-feather-found", name: "Found feather", emotionalPurpose: "Small discovery", collection: "nature", primaryRoom: "window-seat", material: "cotton" },
  { id: "obj-caterpillar-leaf", name: "Caterpillar on leaf", emotionalPurpose: "Becoming", collection: "nature", primaryRoom: "greenhouse", material: "cotton", seasonalVariants: ["spring"] },
];
