import type { ObjectSeed } from "./builder";

export const READING_OBJECT_SEEDS: ObjectSeed[] = [
  { id: "obj-book-stack", name: "Book stack", emotionalPurpose: "Learning waiting", collection: "reading", primaryRoom: "library", material: "paper" },
  { id: "obj-open-novel", name: "Open novel", emotionalPurpose: "Learning", collection: "reading", primaryRoom: "reading-nook", material: "paper", animationCapability: true, animation: "page-lift" },
  { id: "obj-silk-bookmark", name: "Silk bookmark", emotionalPurpose: "Pause mid-chapter", collection: "reading", primaryRoom: "reading-nook", material: "linen" },
  { id: "obj-reading-lamp", name: "Reading lamp", emotionalPurpose: "Pool of light", collection: "reading", primaryRoom: "reading-nook", material: "brass" },
  { id: "obj-aquarium-ornament", name: "Aquarium ornament", emotionalPurpose: "Peace", collection: "reading", primaryRoom: "reading-nook", material: "glass", animationCapability: true, animation: "bubble" },
  { id: "obj-reading-chair", name: "Reading chair", emotionalPurpose: "Settle in", collection: "reading", primaryRoom: "reading-nook", material: "wood" },
  { id: "obj-side-table", name: "Side table", emotionalPurpose: "Tea within reach", collection: "reading", primaryRoom: "reading-nook", material: "wood" },
  { id: "obj-library-ladder", name: "Library ladder", emotionalPurpose: "Reach higher", collection: "reading", primaryRoom: "library", material: "wood" },
  { id: "obj-magnifying-glass", name: "Magnifying glass", emotionalPurpose: "Look closer", collection: "reading", primaryRoom: "library", material: "brass" },
  { id: "obj-dictionary", name: "Dictionary", emotionalPurpose: "Find the word", collection: "reading", primaryRoom: "library", material: "leather" },
  { id: "obj-thesaurus", name: "Thesaurus", emotionalPurpose: "Another way to say it", collection: "reading", primaryRoom: "library", material: "leather" },
  { id: "obj-poetry-collection", name: "Poetry collection", emotionalPurpose: "Language as music", collection: "reading", primaryRoom: "reading-nook", material: "linen" },
  { id: "obj-audiobook-device", name: "Audiobook player", emotionalPurpose: "Stories while moving", collection: "reading", primaryRoom: "garden-path", material: "wood", illustrationNotes: "Vintage-style player — not modern phone UI" },
  { id: "obj-book-light", name: "Clip-on book light", emotionalPurpose: "Read without waking", collection: "reading", primaryRoom: "reading-nook", material: "brass" },
  { id: "obj-newspaper-magazine", name: "Magazine stack", emotionalPurpose: "Browse and drift", collection: "reading", primaryRoom: "living-room", material: "paper" },
  { id: "obj-comic-trade", name: "Graphic novel", emotionalPurpose: "Visual story", collection: "reading", primaryRoom: "reading-nook", material: "paper" },
  { id: "obj-kids-picture-book", name: "Picture book", emotionalPurpose: "Wonder for small hands", collection: "reading", primaryRoom: "living-room", material: "paper" },
  { id: "obj-book-club-selection", name: "Book club selection", emotionalPurpose: "Read together", collection: "reading", primaryRoom: "library", material: "paper" },
  { id: "obj-highlighter-set", name: "Highlighter set", emotionalPurpose: "Mark what lands", collection: "reading", primaryRoom: "library", material: "wood" },
  { id: "obj-sticky-tabs", name: "Sticky tabs in book", emotionalPurpose: "Return to this page", collection: "reading", primaryRoom: "business-office", material: "paper" },
  { id: "obj-reading-journal", name: "Reading journal", emotionalPurpose: "What it meant", collection: "reading", primaryRoom: "reading-nook", material: "linen" },
  { id: "obj-bookends-brass", name: "Brass bookends", emotionalPurpose: "Hold the row", collection: "reading", primaryRoom: "library", material: "brass" },
  { id: "obj-rolled-map", name: "Rolled map", emotionalPurpose: "Adventure planned", collection: "reading", primaryRoom: "adventure-room", material: "paper" },
  { id: "obj-field-guide", name: "Field guide", emotionalPurpose: "Name what you see", collection: "reading", primaryRoom: "window-seat", material: "paper" },
  { id: "obj-cookbook-open", name: "Open cookbook", emotionalPurpose: "Instructions as care", collection: "reading", primaryRoom: "kitchen-table", material: "paper" },
  { id: "obj-bible-journal", name: "Devotional journal", emotionalPurpose: "Quiet faith", collection: "reading", primaryRoom: "reading-nook", material: "leather" },
  { id: "obj-book-cart", name: "Rolling book cart", emotionalPurpose: "Library mobile", collection: "reading", primaryRoom: "library", material: "wood" },
  { id: "obj-overdue-library-stack", name: "Library book stack", emotionalPurpose: "Borrowed worlds", collection: "reading", primaryRoom: "front-porch", material: "paper" },
];
