import type { ObjectSeed } from "./builder";

export const WRITING_OBJECT_SEEDS: ObjectSeed[] = [
  { id: "obj-leather-journal", name: "Leather journal", emotionalPurpose: "Reflection", collection: "writing", primaryRoom: "window-seat", material: "leather", featureObjectId: "clear-my-mind", animationCapability: false, seasonalVariants: ["autumn-knit-corner", "spring-bloom-pressed-flower"], accessibilityDescription: "Brown leather journal with worn spine and cream pages" },
  { id: "obj-linen-notebook", name: "Linen notebook", emotionalPurpose: "Fresh starts", collection: "writing", primaryRoom: "planning-table", material: "linen" },
  { id: "obj-open-planner", name: "Open leather planner", emotionalPurpose: "Today's intentions", collection: "writing", primaryRoom: "planning-table", material: "leather", featureObjectId: "plan-my-day", seasonalVariants: ["holiday-ribbon-marker", "summer-bright-tabs"] },
  { id: "obj-desk-planner", name: "Desk planner", emotionalPurpose: "Structure without rigidity", collection: "writing", primaryRoom: "business-office", material: "paper" },
  { id: "obj-weekly-planner", name: "Weekly planner pad", emotionalPurpose: "Gentle rhythm", collection: "writing", primaryRoom: "planning-table", material: "paper" },
  { id: "obj-fountain-pen", name: "Fountain pen", emotionalPurpose: "Intentional words", collection: "writing", primaryRoom: "library", material: "brass" },
  { id: "obj-ink-bottle", name: "Ink bottle", emotionalPurpose: "Slow craft", collection: "writing", primaryRoom: "library", material: "glass" },
  { id: "obj-pencil-cup", name: "Pencil cup", emotionalPurpose: "Tools at hand", collection: "writing", primaryRoom: "creative-studio", material: "ceramic" },
  { id: "obj-wooden-pencil", name: "Wooden pencil", emotionalPurpose: "Sketching ideas", collection: "writing", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-mechanical-pencil", name: "Mechanical pencil", emotionalPurpose: "Precision notes", collection: "writing", primaryRoom: "business-office", material: "brass" },
  { id: "obj-bookmark-ribbon", name: "Ribbon bookmark", emotionalPurpose: "Pause and return", collection: "writing", primaryRoom: "reading-nook", material: "linen" },
  { id: "obj-bookmark-leather", name: "Leather bookmark", emotionalPurpose: "Mark what matters", collection: "writing", primaryRoom: "library", material: "leather" },
  { id: "obj-letter-tray", name: "Letter tray", emotionalPurpose: "Correspondence waiting", collection: "writing", primaryRoom: "business-office", material: "wood" },
  { id: "obj-paper-clips-brass", name: "Brass paper clips", emotionalPurpose: "Hold ideas together", collection: "writing", primaryRoom: "planning-table", material: "brass" },
  { id: "obj-sticky-notes", name: "Sticky notes", emotionalPurpose: "Capture before it flies", collection: "writing", primaryRoom: "kitchen-table", material: "paper" },
  { id: "obj-writing-basket", name: "Writing basket", emotionalPurpose: "Everything in one place", collection: "writing", primaryRoom: "window-seat", material: "wicker" },
  { id: "obj-index-cards", name: "Index card stack", emotionalPurpose: "Sortable thoughts", collection: "writing", primaryRoom: "planning-table", material: "paper" },
  { id: "obj-legal-pad", name: "Legal pad", emotionalPurpose: "Brain dump surface", collection: "writing", primaryRoom: "window-seat", material: "paper" },
  { id: "obj-gratitude-journal", name: "Gratitude journal", emotionalPurpose: "Notice the good", collection: "writing", primaryRoom: "reading-nook", material: "linen" },
  { id: "obj-dream-journal", name: "Dream journal", emotionalPurpose: "Morning fragments", collection: "writing", primaryRoom: "reading-nook", material: "leather" },
  { id: "obj-calligraphy-pen", name: "Calligraphy pen", emotionalPurpose: "Beautiful slowness", collection: "writing", primaryRoom: "creative-studio", material: "wood" },
  { id: "obj-wax-seal", name: "Wax seal kit", emotionalPurpose: "Letters that matter", collection: "writing", primaryRoom: "library", material: "brass" },
  { id: "obj-envelope-stack", name: "Envelope stack", emotionalPurpose: "Words going out", collection: "writing", primaryRoom: "business-office", material: "paper" },
  { id: "obj-stamp-box", name: "Stamp box", emotionalPurpose: "Small rituals", collection: "writing", primaryRoom: "library", material: "wood" },
  { id: "obj-typewriter-ribbon", name: "Typewriter ribbon", emotionalPurpose: "Vintage persistence", collection: "writing", primaryRoom: "workshop", material: "cotton" },
  { id: "obj-vintage-typewriter", name: "Vintage typewriter", emotionalPurpose: "Drafts with weight", collection: "writing", primaryRoom: "creative-studio", material: "iron", futureExpansion: "Optional hero asset for Create workspace" },
  { id: "obj-bullet-journal", name: "Bullet journal", emotionalPurpose: "Your system, your way", collection: "writing", primaryRoom: "planning-table", material: "linen" },
  { id: "obj-moleskine-stack", name: "Notebook stack", emotionalPurpose: "Projects in waiting", collection: "writing", primaryRoom: "business-office", material: "leather" },
  { id: "obj-pen-roll", name: "Pen roll", emotionalPurpose: "Traveling thoughts", collection: "writing", primaryRoom: "adventure-room", material: "leather" },
  { id: "obj-desk-blotter", name: "Desk blotter", emotionalPurpose: "Protected workspace", collection: "writing", primaryRoom: "business-office", material: "leather" },
  { id: "obj-guestbook", name: "Guest book", emotionalPurpose: "Visitors remembered", collection: "writing", primaryRoom: "front-porch", material: "linen" },
  { id: "obj-recipe-cards", name: "Recipe card box", emotionalPurpose: "Handed-down care", collection: "writing", primaryRoom: "kitchen-table", material: "wood" },
];
