/**
 * Business Plan map groups — schema config only (201–244).
 */

import type { BlueprintGroup } from "../../blueprints/types";

export const BUSINESS_PLAN_MAP_GROUPS: readonly BlueprintGroup[] = [
  {
    groupId: "foundation",
    title: "Foundation",
    description: "Vision, products, customers, and pricing.",
    order: 0,
    collapsedByDefault: false,
    sectionIds: [
      "purpose_vision",
      "products_offers",
      "customers_audience",
      "positioning",
      "pricing",
      "inventory",
      "shop_setup",
      "branding",
    ],
  },
  {
    groupId: "in_person_shows",
    title: "Shows and Markets",
    description: "Booth, applications, travel, and day-of selling.",
    order: 1,
    collapsedByDefault: true,
    sectionIds: [
      "booth_design",
      "show_discovery",
      "jury_applications",
      "annual_calendar",
      "travel_logistics",
      "packing_loading",
      "pos_checkout",
      "lead_capture",
      "customer_relationships",
      "vendor_documents",
      "restocking_seasonal",
      "post_show_review",
    ],
  },
  {
    groupId: "online_store",
    title: "Online Store",
    description: "Marketplaces, listings, shipping, and digital growth.",
    order: 2,
    collapsedByDefault: true,
    sectionIds: [
      "photography",
      "listings_seo",
      "marketplaces",
      "shipping_packaging",
      "customer_service",
      "reviews_reputation",
      "ads",
      "email_marketing",
      "social_pinterest",
      "launches_promotions",
      "seasonal_planning",
      "automation",
    ],
  },
  {
    groupId: "product_photography",
    title: "Product Photography",
    description: "Shot lists, lighting, styling, editing, and marketplace specs.",
    order: 3,
    collapsedByDefault: true,
    sectionIds: [
      "shot_lists",
      "lighting",
      "backgrounds",
      "styling",
      "lifestyle_images",
      "video_clips",
      "editing_workflow",
      "image_organization",
      "accessibility_alt_text",
      "marketplace_image_requirements",
    ],
  },
  {
    groupId: "inventory_pricing",
    title: "Inventory and Pricing",
    description: "Costs, margins, forecasting, and stock decisions.",
    order: 4,
    collapsedByDefault: true,
    sectionIds: [
      "cost_of_goods",
      "labor_cost",
      "overhead",
      "profit_margin",
      "inventory_forecasting",
      "bundles",
      "seasonal_stock",
      "reorder_points",
      "best_sellers",
      "dead_inventory",
    ],
  },
  {
    groupId: "holiday_collections",
    title: "Holiday Collections",
    description: "Seasonal collections, production, and launch timing.",
    order: 5,
    collapsedByDefault: true,
    sectionIds: [
      "collection_planning",
      "production_schedule",
      "launch_timeline",
      "seasonal_campaigns",
    ],
  },
  {
    groupId: "speaker_business",
    title: "Speaker Business",
    description: "Talks, buyers, booking, fees, and delivery.",
    order: 6,
    collapsedByDefault: true,
    sectionIds: [
      "audience_buyer_architecture",
      "signature_talk_portfolio",
      "speaking_offers",
      "speaker_marketing",
      "booking_pipeline",
      "speaker_proposal",
      "event_preparation",
      "delivery_experience",
      "post_event_followup",
      "speaker_operations",
    ],
  },
  {
    groupId: "coaching_business",
    title: "Coaching Business",
    description: "Fit, offers, enrollment, delivery, and renewal.",
    order: 7,
    collapsedByDefault: true,
    sectionIds: [
      "client_fit",
      "coaching_offers",
      "coaching_framework",
      "coaching_marketing",
      "discovery_enrollment",
      "coaching_onboarding",
      "coaching_delivery",
      "completion_renewal",
      "coaching_operations",
    ],
  },
  {
    groupId: "consulting_business",
    title: "Consulting Business",
    description: "Diagnosis, proposals, delivery, and closeout.",
    order: 8,
    collapsedByDefault: true,
    sectionIds: [
      "service_architecture",
      "diagnostic_method",
      "lead_generation",
      "qualification_discovery",
      "proposal_contract",
      "engagement_kickoff",
      "consulting_delivery",
      "client_communication",
      "outcomes_closeout",
      "consulting_operations",
    ],
  },
  {
    groupId: "service_operating",
    title: "Service Operating",
    description: "Menu, inquiry, delivery, payment, and retention.",
    order: 9,
    collapsedByDefault: true,
    sectionIds: [
      "service_menu",
      "client_acquisition",
      "inquiry_qualification",
      "estimate_proposal",
      "service_onboarding",
      "delivery_workflow",
      "change_issue_management",
      "completion_payment",
      "followup_retention",
      "service_operations",
    ],
  },
  {
    groupId: "author_business",
    title: "Author Business",
    description: "Books, publishing path, platform, and catalog growth.",
    order: 10,
    collapsedByDefault: true,
    sectionIds: [
      "reader_market_architecture",
      "book_portfolio_strategy",
      "publishing_path",
      "book_development_workflow",
      "author_platform",
      "book_marketing",
      "sales_distribution",
      "book_to_business",
      "author_operations",
    ],
  },
  {
    groupId: "course_creator_business",
    title: "Course Creator Business",
    description: "Validation, curriculum, enrollment, and outcomes.",
    order: 11,
    collapsedByDefault: true,
    sectionIds: [
      "learner_demand_validation",
      "course_model",
      "learning_outcomes",
      "curriculum_sequence",
      "content_production",
      "student_experience",
      "course_enrollment",
      "course_delivery_ops",
      "course_measurement",
      "course_portfolio_growth",
    ],
  },
  {
    groupId: "membership_business",
    title: "Membership Business",
    description: "Recurring value, activation, retention, and health.",
    order: 12,
    collapsedByDefault: true,
    sectionIds: [
      "member_profile_fit",
      "membership_model",
      "value_architecture",
      "member_onboarding",
      "membership_rhythm",
      "community_health",
      "retention_renewal",
      "membership_growth",
      "membership_operations",
      "membership_measurement",
    ],
  },
  {
    groupId: "content_creator_business",
    title: "Content Creator Business",
    description: "Pillars, platforms, production, and monetization.",
    order: 13,
    collapsedByDefault: true,
    sectionIds: [
      "creator_audience",
      "content_pillars",
      "platform_strategy",
      "content_production_system",
      "audience_growth",
      "trust_relationship",
      "creator_monetization",
      "sponsorship_partnerships",
      "creator_analytics",
      "content_asset_library",
      "creator_operations",
    ],
  },
  {
    groupId: "professional_organizing_business",
    title: "Professional Organizing Business",
    description: "Specialty, services, assessment, delivery, and maintenance offers.",
    order: 14,
    collapsedByDefault: true,
    sectionIds: [
      "organizing_clients",
      "organizing_services",
      "organizing_inquiry",
      "organizing_assessment",
      "organizing_proposal",
      "organizing_delivery",
      "organizing_maintenance",
      "organizing_privacy",
      "organizing_growth",
      "organizing_operations",
    ],
  },
  {
    groupId: "physical_space_organizing",
    title: "Physical Space Organizing",
    description: "Purpose, zones, decisions, and maintenance for physical spaces.",
    order: 15,
    collapsedByDefault: true,
    sectionIds: [
      "space_users",
      "current_state_space",
      "sort_decide",
      "space_design",
      "labels_containers",
      "accessibility_flow",
      "maintenance_space",
    ],
  },
  {
    groupId: "digital_information_organizing",
    title: "Digital and Information Organizing",
    description: "Inventory, naming, retrieval, permissions, and maintenance.",
    order: 16,
    collapsedByDefault: true,
    sectionIds: [
      "info_inventory",
      "naming_structure",
      "retrieval_rules",
      "permissions_archives",
      "email_notes_photos",
      "digital_maintenance",
    ],
  },
  {
    groupId: "operational_procedural_organizing",
    title: "Operational and Procedural Organizing",
    description: "Workflows, SOPs, handoffs, and procedure maintenance.",
    order: 17,
    collapsedByDefault: true,
    sectionIds: [
      "workflow_map",
      "roles_handoffs",
      "sop_design",
      "recurring_rhythms",
      "visibility_ops",
      "ops_maintenance",
    ],
  },
  {
    groupId: "strategic_management_organizing",
    title: "Strategic and Management Organizing",
    description: "Priorities, initiatives, decisions, and management cadence.",
    order: 18,
    collapsedByDefault: true,
    sectionIds: [
      "priority_structure",
      "initiative_map",
      "decision_log_org",
      "meeting_rhythms",
      "alignment_load",
      "management_cadence",
    ],
  },
  {
    groupId: "retail_store_business",
    title: "Retail Store Business",
    description: "Concept, assortment, margins, layout, staffing, and store economics.",
    order: 19,
    collapsedByDefault: true,
    sectionIds: [
      "retail_customers",
      "retail_assortment",
      "retail_layout_flow",
      "retail_marketing",
      "retail_sales_ops",
      "retail_staffing",
      "retail_loss_prevention",
      "retail_growth",
      "retail_kpi_dashboard",
    ],
  },
  {
    groupId: "retail_store_management",
    title: "Retail Store Management",
    description: "Opening, closing, cash, scheduling, incidents, and reviews.",
    order: 20,
    collapsedByDefault: true,
    sectionIds: [
      "retail_opening",
      "retail_closing",
      "retail_cash_handling",
      "retail_scheduling",
      "retail_customer_service",
      "retail_visual_standards",
      "retail_daily_tasks",
      "retail_incidents",
      "retail_safety",
      "retail_ops_reviews",
    ],
  },
  {
    groupId: "retail_inventory_purchasing_vendor",
    title: "Retail Inventory Purchasing and Vendors",
    description: "Forecasting, purchasing, receiving, reorder, shrink, and scorecards.",
    order: 21,
    collapsedByDefault: true,
    sectionIds: [
      "retail_demand_forecast",
      "retail_purchasing_workflow",
      "retail_vendor_selection",
      "retail_receiving",
      "retail_inventory_control",
      "retail_reorder_points",
      "retail_markdown_strategy",
      "retail_shrink",
      "retail_returns",
      "retail_vendor_scorecards",
    ],
  },
  {
    groupId: "retail_merchandising_promotions_cx",
    title: "Retail Merchandising Promotions and Experience",
    description: "Visual merchandising, promotions, loyalty, and customer journey.",
    order: 22,
    collapsedByDefault: true,
    sectionIds: [
      "retail_visual_merch",
      "retail_seasonal_planning",
      "retail_endcaps_displays",
      "retail_promotions",
      "retail_loyalty",
      "retail_customer_journey",
      "retail_store_events",
      "retail_upsell_cross",
      "retail_atmosphere",
      "retail_experience_measurement",
    ],
  },
  {
    groupId: "ecommerce_business",
    title: "Ecommerce Business",
    description: "Journey, assortment, storefront, fulfillment, and retention.",
    order: 23,
    collapsedByDefault: true,
    sectionIds: [
      "ecom_customer_journey",
      "ecom_assortment",
      "ecom_storefront",
      "ecom_channels",
      "ecom_fulfillment",
      "ecom_service_returns",
      "ecom_acquisition",
      "ecom_retention",
      "ecom_analytics",
      "ecom_operations_growth",
    ],
  },
  {
    groupId: "product_based_business",
    title: "Product-Based Business",
    description: "Validation, sourcing, costing, packaging, launch, and lifecycle.",
    order: 24,
    collapsedByDefault: true,
    sectionIds: [
      "product_validation",
      "product_architecture",
      "product_sourcing",
      "product_quality",
      "product_packaging",
      "product_channels",
      "product_launch",
      "product_inventory_cash",
      "product_lifecycle",
      "product_growth",
    ],
  },
  {
    groupId: "wholesale_business",
    title: "Wholesale and Retail Partnership",
    description: "Readiness, terms, line sheets, accounts, and channel risk.",
    order: 25,
    collapsedByDefault: true,
    sectionIds: [
      "wholesale_accounts",
      "wholesale_line_sheet",
      "wholesale_acquisition",
      "wholesale_order_ops",
      "wholesale_retailer_support",
      "wholesale_account_mgmt",
      "wholesale_reps",
      "wholesale_channel_risk",
      "wholesale_analytics",
      "wholesale_growth",
    ],
  },
  {
    groupId: "subscription_commerce",
    title: "Subscription Commerce",
    description: "Model, economics, fulfillment, retention, and churn.",
    order: 26,
    collapsedByDefault: true,
    sectionIds: [
      "sub_model",
      "sub_offer_tiers",
      "sub_demand_inventory",
      "sub_acquisition",
      "sub_onboarding",
      "sub_fulfillment",
      "sub_retention",
      "sub_experience",
      "sub_analytics",
      "sub_growth",
    ],
  },
  {
    groupId: "hospitality_business",
    title: "Hospitality Business",
    description: "Guests, reservations, journey, housekeeping, and recovery.",
    order: 27,
    collapsedByDefault: true,
    sectionIds: [
      "hosp_guest_personas",
      "hosp_reservations",
      "hosp_guest_journey",
      "hosp_housekeeping",
      "hosp_staffing",
      "hosp_service_partners",
      "hosp_guest_recovery",
      "hosp_kpis",
    ],
  },
  {
    groupId: "restaurant_food_service",
    title: "Restaurant and Food Service",
    description: "Menu, kitchen, FOH, vendors, safety, and financials.",
    order: 28,
    collapsedByDefault: true,
    sectionIds: [
      "rest_menu",
      "rest_kitchen",
      "rest_foh",
      "rest_staffing",
      "rest_vendors",
      "rest_food_safety",
      "rest_marketing",
      "rest_financials",
    ],
  },
  {
    groupId: "travel_tourism_business",
    title: "Travel and Tourism",
    description: "Travelers, itineraries, suppliers, bookings, and risk.",
    order: 29,
    collapsedByDefault: true,
    sectionIds: [
      "travel_profiles",
      "travel_itinerary",
      "travel_suppliers",
      "travel_bookings",
      "travel_risk",
      "travel_cx",
      "travel_partnerships",
      "travel_seasonal",
      "travel_operations",
      "travel_kpis",
    ],
  },
  {
    groupId: "venue_experience_business",
    title: "Venue and Experience",
    description: "Capacity, bookings, coordination, safety, and revenue.",
    order: 30,
    collapsedByDefault: true,
    sectionIds: [
      "venue_capacity",
      "venue_bookings",
      "venue_event_coord",
      "venue_vendors",
      "venue_safety",
      "venue_revenue",
      "venue_guest_xp",
      "venue_maintenance",
      "venue_growth",
    ],
  },
  {
    groupId: "contractor_construction",
    title: "Contractor and Construction",
    description: "Scope, estimates, crews, change orders, and closeout.",
    order: 31,
    collapsedByDefault: true,
    sectionIds: [
      "gc_lead_qualify",
      "gc_site_assessment",
      "gc_scope",
      "gc_proposal",
      "gc_project_planning",
      "gc_crew_subs",
      "gc_change_mgmt",
      "gc_client_comms",
      "gc_quality_safety",
      "gc_performance",
    ],
  },
  {
    groupId: "home_service_business",
    title: "Home Service Business",
    description: "Inquiry, booking, routing, delivery, and recurring service.",
    order: 32,
    collapsedByDefault: true,
    sectionIds: [
      "hs_inquiry",
      "hs_estimate_booking",
      "hs_routing",
      "hs_delivery",
      "hs_comms",
      "hs_recurring",
      "hs_team_field",
      "hs_inventory",
      "hs_safety",
      "hs_performance",
    ],
  },
  {
    groupId: "property_management_business",
    title: "Property Management",
    description: "Owners, properties, residents, maintenance, and portfolio.",
    order: 33,
    collapsedByDefault: true,
    sectionIds: [
      "pm_owner",
      "pm_property",
      "pm_resident",
      "pm_leasing",
      "pm_maintenance",
      "pm_vendors",
      "pm_inspections",
      "pm_financials",
      "pm_comms",
      "pm_str",
      "pm_portfolio",
    ],
  },
  {
    groupId: "mobile_field_service_ops",
    title: "Mobile and Field Service Operations",
    description: "Dispatch, prep, execution, safety, and completion.",
    order: 34,
    collapsedByDefault: true,
    sectionIds: [
      "field_job_intake",
      "field_dispatch",
      "field_prep",
      "field_arrival",
      "field_execution",
      "field_comms",
      "field_completion",
      "field_safety",
      "field_vehicle_stock",
      "field_team",
      "field_analytics",
    ],
  },
  {
    groupId: "wellness_practice_business",
    title: "Wellness Practice",
    description: "Scope, intake, sessions, referrals, and practice performance.",
    order: 35,
    collapsedByDefault: true,
    sectionIds: [
      "wp_service_offers",
      "wp_inquiry_fit",
      "wp_intake_consent",
      "wp_client_journey",
      "wp_session_delivery",
      "wp_education",
      "wp_scheduling",
      "wp_retention",
      "wp_privacy_risk",
      "wp_performance",
    ],
  },
  {
    groupId: "beauty_personal_care_business",
    title: "Beauty and Personal Care",
    description: "Menu, booking, sanitation, aftercare, retail, and studio ops.",
    order: 36,
    collapsedByDefault: true,
    sectionIds: [
      "bc_service_menu",
      "bc_booking",
      "bc_intake",
      "bc_delivery",
      "bc_aftercare",
      "bc_retail",
      "bc_retention",
      "bc_team_ops",
      "bc_marketing",
      "bc_performance",
    ],
  },
  {
    groupId: "fitness_studio_coaching_business",
    title: "Fitness Studio and Coaching",
    description: "Programs, screening, classes, progress, and studio ops.",
    order: 37,
    collapsedByDefault: true,
    sectionIds: [
      "fit_programs",
      "fit_screening",
      "fit_onboarding",
      "fit_program_plan",
      "fit_delivery",
      "fit_progress",
      "fit_retention",
      "fit_studio_ops",
      "fit_team",
      "fit_performance",
    ],
  },
  {
    groupId: "pet_service_business",
    title: "Pet Service",
    description: "Animal fit, routing, delivery logs, safety, and retention.",
    order: 38,
    collapsedByDefault: true,
    sectionIds: [
      "pet_inquiry_fit",
      "pet_consent_access",
      "pet_scheduling",
      "pet_delivery",
      "pet_owner_comms",
      "pet_safety",
      "pet_supplies",
      "pet_team",
      "pet_retention",
      "pet_performance",
    ],
  },
  {
    groupId: "education_training_business",
    title: "Education and Training",
    description: "Programs, curriculum, instructors, schedules, and certification.",
    order: 39,
    collapsedByDefault: true,
    sectionIds: [
      "et_program_architecture",
      "et_curriculum",
      "et_learning_paths",
      "et_lessons_assessments",
      "et_instructor_ops",
      "et_student_onboarding",
      "et_schedules",
      "et_certification",
      "et_performance",
    ],
  },
  {
    groupId: "nonprofit_foundation_business",
    title: "Nonprofit and Foundation",
    description: "Mission, programs, volunteers, fundraising, grants, and impact.",
    order: 40,
    collapsedByDefault: true,
    sectionIds: [
      "np_mission_map",
      "np_strategic_plan",
      "np_program_plans",
      "np_volunteer_ops",
      "np_fundraising",
      "np_grants",
      "np_board",
      "np_donor_stewardship",
      "np_impact",
    ],
  },
  {
    groupId: "public_sector_community_business",
    title: "Public Sector and Community",
    description: "Charters, stakeholders, engagement, risk, and progress.",
    order: 41,
    collapsedByDefault: true,
    sectionIds: [
      "ps_charter",
      "ps_stakeholders",
      "ps_comms",
      "ps_meetings",
      "ps_engagement",
      "ps_risk",
      "ps_progress",
    ],
  },
  {
    groupId: "faith_membership_org_business",
    title: "Faith and Membership Organization",
    description: "Ministries, volunteers, care, events, and member onboarding.",
    order: 42,
    collapsedByDefault: true,
    sectionIds: [
      "fm_ministry_plans",
      "fm_volunteer_schedule",
      "fm_events",
      "fm_care",
      "fm_member_onboarding",
      "fm_comms",
      "fm_education",
      "fm_admin",
      "fm_roadmap",
    ],
  },
  {
    groupId: "legal_services_business",
    title: "Legal Services",
    description: "Intake, conflicts, matters, billing, and firm ops.",
    order: 43,
    collapsedByDefault: true,
    sectionIds: [
      "legal_inquiry",
      "legal_conflict",
      "legal_engagement",
      "legal_matter_plan",
      "legal_matter_exec",
      "legal_client_comms",
      "legal_billing",
      "legal_knowledge",
      "legal_referrals",
      "legal_firm_ops",
      "legal_performance",
    ],
  },
  {
    groupId: "accounting_bookkeeping_tax_business",
    title: "Accounting Bookkeeping and Tax",
    description: "Onboarding, close, QC, tax, payroll, and records.",
    order: 44,
    collapsedByDefault: true,
    sectionIds: [
      "acct_qualify",
      "acct_onboarding",
      "acct_monthly",
      "acct_qc",
      "acct_reporting",
      "acct_tax",
      "acct_payroll",
      "acct_comms",
      "acct_records",
      "acct_performance",
    ],
  },
  {
    groupId: "insurance_agency_business",
    title: "Insurance Agency",
    description: "Quoting, binding support, renewals, and claims support.",
    order: 45,
    collapsedByDefault: true,
    sectionIds: [
      "ins_prospect",
      "ins_discovery",
      "ins_quoting",
      "ins_proposal",
      "ins_binding",
      "ins_service",
      "ins_renewals",
      "ins_claims",
      "ins_carriers",
      "ins_compliance",
      "ins_performance",
    ],
  },
  {
    groupId: "real_estate_brokerage_agent_business",
    title: "Real Estate Brokerage and Agent",
    description: "Leads, listing/buyer journeys, transactions, and post-close.",
    order: 46,
    collapsedByDefault: true,
    sectionIds: [
      "re_leads",
      "re_seller",
      "re_listing",
      "re_buyer",
      "re_search",
      "re_offer",
      "re_transaction",
      "re_comms",
      "re_closing",
      "re_team_ops",
      "re_performance",
    ],
  },
  {
    groupId: "small_manufacturing_business",
    title: "Small Manufacturing",
    description: "BOM, work orders, quality, inventory, and fulfillment.",
    order: 47,
    collapsedByDefault: true,
    sectionIds: [
      "mfg_product",
      "mfg_bom",
      "mfg_suppliers",
      "mfg_planning",
      "mfg_work_orders",
      "mfg_quality",
      "mfg_inventory",
      "mfg_maintenance",
      "mfg_safety",
      "mfg_fulfillment",
      "mfg_people",
      "mfg_performance",
    ],
  },
  {
    groupId: "wholesale_distribution_business",
    title: "Wholesale and Distribution",
    description: "Catalog, accounts, purchasing, warehouse, and cash.",
    order: 48,
    collapsedByDefault: true,
    sectionIds: [
      "wd_catalog",
      "wd_accounts",
      "wd_sales",
      "wd_purchasing",
      "wd_inventory",
      "wd_warehouse",
      "wd_orders",
      "wd_returns",
      "wd_cash",
      "wd_performance",
    ],
  },
  {
    groupId: "logistics_transportation_business",
    title: "Logistics and Transportation",
    description: "Intake, dispatch, fleet, safety, and POD.",
    order: 49,
    collapsedByDefault: true,
    sectionIds: [
      "log_intake",
      "log_dispatch",
      "log_pickup_delivery",
      "log_drivers",
      "log_fleet",
      "log_safety",
      "log_comms",
      "log_billing",
      "log_capacity",
      "log_performance",
    ],
  },
  {
    groupId: "agriculture_farm_rural_business",
    title: "Agriculture Farm and Rural",
    description: "Enterprises, seasonality, harvest, sales, and risk.",
    order: 50,
    collapsedByDefault: true,
    sectionIds: [
      "ag_enterprise",
      "ag_crop",
      "ag_livestock",
      "ag_inputs",
      "ag_equipment",
      "ag_labor",
      "ag_harvest",
      "ag_sales",
      "ag_agritourism",
      "ag_risk",
      "ag_records",
      "ag_performance",
    ],
  },
  {
    groupId: "stewardship",
    title: "Money and Stewardship",
    description: "Profit, taxes, analytics, linked work, and review.",
    order: 51,
    collapsedByDefault: true,
    sectionIds: [
      "expenses_taxes",
      "profitability",
      "analytics",
      "linked_event_work",
      "next_actions",
      "review_rhythm",
    ],
  },
];
