/**
 * Business Plan map groups — schema config only (201–224).
 */

import type { BlueprintGroup } from "../../blueprints/types";

export const BUSINESS_PLAN_MAP_GROUPS: readonly BlueprintGroup[] = [
  {
    groupId: "foundation",
    title: "Foundation",
    description: "Vision, products, customers, and pricing.",
    order: 0,
    collapsedByDefault: false,
    sectionIds: [
      "purpose_vision",
      "products_offers",
      "customers_audience",
      "positioning",
      "pricing",
      "inventory",
      "shop_setup",
      "branding",
    ],
  },
  {
    groupId: "in_person_shows",
    title: "Shows and Markets",
    description: "Booth, applications, travel, and day-of selling.",
    order: 1,
    collapsedByDefault: true,
    sectionIds: [
      "booth_design",
      "show_discovery",
      "jury_applications",
      "annual_calendar",
      "travel_logistics",
      "packing_loading",
      "pos_checkout",
      "lead_capture",
      "customer_relationships",
      "vendor_documents",
      "restocking_seasonal",
      "post_show_review",
    ],
  },
  {
    groupId: "online_store",
    title: "Online Store",
    description: "Marketplaces, listings, shipping, and digital growth.",
    order: 2,
    collapsedByDefault: true,
    sectionIds: [
      "photography",
      "listings_seo",
      "marketplaces",
      "shipping_packaging",
      "customer_service",
      "reviews_reputation",
      "ads",
      "email_marketing",
      "social_pinterest",
      "launches_promotions",
      "seasonal_planning",
      "automation",
    ],
  },
  {
    groupId: "product_photography",
    title: "Product Photography",
    description: "Shot lists, lighting, styling, editing, and marketplace specs.",
    order: 3,
    collapsedByDefault: true,
    sectionIds: [
      "shot_lists",
      "lighting",
      "backgrounds",
      "styling",
      "lifestyle_images",
      "video_clips",
      "editing_workflow",
      "image_organization",
      "accessibility_alt_text",
      "marketplace_image_requirements",
    ],
  },
  {
    groupId: "inventory_pricing",
    title: "Inventory and Pricing",
    description: "Costs, margins, forecasting, and stock decisions.",
    order: 4,
    collapsedByDefault: true,
    sectionIds: [
      "cost_of_goods",
      "labor_cost",
      "overhead",
      "profit_margin",
      "inventory_forecasting",
      "bundles",
      "seasonal_stock",
      "reorder_points",
      "best_sellers",
      "dead_inventory",
    ],
  },
  {
    groupId: "holiday_collections",
    title: "Holiday Collections",
    description: "Seasonal collections, production, and launch timing.",
    order: 5,
    collapsedByDefault: true,
    sectionIds: [
      "collection_planning",
      "production_schedule",
      "launch_timeline",
      "seasonal_campaigns",
    ],
  },
  {
    groupId: "speaker_business",
    title: "Speaker Business",
    description: "Talks, buyers, booking, fees, and delivery.",
    order: 6,
    collapsedByDefault: true,
    sectionIds: [
      "audience_buyer_architecture",
      "signature_talk_portfolio",
      "speaking_offers",
      "speaker_marketing",
      "booking_pipeline",
      "speaker_proposal",
      "event_preparation",
      "delivery_experience",
      "post_event_followup",
      "speaker_operations",
    ],
  },
  {
    groupId: "coaching_business",
    title: "Coaching Business",
    description: "Fit, offers, enrollment, delivery, and renewal.",
    order: 7,
    collapsedByDefault: true,
    sectionIds: [
      "client_fit",
      "coaching_offers",
      "coaching_framework",
      "coaching_marketing",
      "discovery_enrollment",
      "coaching_onboarding",
      "coaching_delivery",
      "completion_renewal",
      "coaching_operations",
    ],
  },
  {
    groupId: "consulting_business",
    title: "Consulting Business",
    description: "Diagnosis, proposals, delivery, and closeout.",
    order: 8,
    collapsedByDefault: true,
    sectionIds: [
      "service_architecture",
      "diagnostic_method",
      "lead_generation",
      "qualification_discovery",
      "proposal_contract",
      "engagement_kickoff",
      "consulting_delivery",
      "client_communication",
      "outcomes_closeout",
      "consulting_operations",
    ],
  },
  {
    groupId: "service_operating",
    title: "Service Operating",
    description: "Menu, inquiry, delivery, payment, and retention.",
    order: 9,
    collapsedByDefault: true,
    sectionIds: [
      "service_menu",
      "client_acquisition",
      "inquiry_qualification",
      "estimate_proposal",
      "service_onboarding",
      "delivery_workflow",
      "change_issue_management",
      "completion_payment",
      "followup_retention",
      "service_operations",
    ],
  },
  {
    groupId: "author_business",
    title: "Author Business",
    description: "Books, publishing path, platform, and catalog growth.",
    order: 10,
    collapsedByDefault: true,
    sectionIds: [
      "reader_market_architecture",
      "book_portfolio_strategy",
      "publishing_path",
      "book_development_workflow",
      "author_platform",
      "book_marketing",
      "sales_distribution",
      "book_to_business",
      "author_operations",
    ],
  },
  {
    groupId: "course_creator_business",
    title: "Course Creator Business",
    description: "Validation, curriculum, enrollment, and outcomes.",
    order: 11,
    collapsedByDefault: true,
    sectionIds: [
      "learner_demand_validation",
      "course_model",
      "learning_outcomes",
      "curriculum_sequence",
      "content_production",
      "student_experience",
      "course_enrollment",
      "course_delivery_ops",
      "course_measurement",
      "course_portfolio_growth",
    ],
  },
  {
    groupId: "membership_business",
    title: "Membership Business",
    description: "Recurring value, activation, retention, and health.",
    order: 12,
    collapsedByDefault: true,
    sectionIds: [
      "member_profile_fit",
      "membership_model",
      "value_architecture",
      "member_onboarding",
      "membership_rhythm",
      "community_health",
      "retention_renewal",
      "membership_growth",
      "membership_operations",
      "membership_measurement",
    ],
  },
  {
    groupId: "content_creator_business",
    title: "Content Creator Business",
    description: "Pillars, platforms, production, and monetization.",
    order: 13,
    collapsedByDefault: true,
    sectionIds: [
      "creator_audience",
      "content_pillars",
      "platform_strategy",
      "content_production_system",
      "audience_growth",
      "trust_relationship",
      "creator_monetization",
      "sponsorship_partnerships",
      "creator_analytics",
      "content_asset_library",
      "creator_operations",
    ],
  },
  {
    groupId: "professional_organizing_business",
    title: "Professional Organizing Business",
    description: "Specialty, services, assessment, delivery, and maintenance offers.",
    order: 14,
    collapsedByDefault: true,
    sectionIds: [
      "organizing_clients",
      "organizing_services",
      "organizing_inquiry",
      "organizing_assessment",
      "organizing_proposal",
      "organizing_delivery",
      "organizing_maintenance",
      "organizing_privacy",
      "organizing_growth",
      "organizing_operations",
    ],
  },
  {
    groupId: "physical_space_organizing",
    title: "Physical Space Organizing",
    description: "Purpose, zones, decisions, and maintenance for physical spaces.",
    order: 15,
    collapsedByDefault: true,
    sectionIds: [
      "space_users",
      "current_state_space",
      "sort_decide",
      "space_design",
      "labels_containers",
      "accessibility_flow",
      "maintenance_space",
    ],
  },
  {
    groupId: "digital_information_organizing",
    title: "Digital and Information Organizing",
    description: "Inventory, naming, retrieval, permissions, and maintenance.",
    order: 16,
    collapsedByDefault: true,
    sectionIds: [
      "info_inventory",
      "naming_structure",
      "retrieval_rules",
      "permissions_archives",
      "email_notes_photos",
      "digital_maintenance",
    ],
  },
  {
    groupId: "operational_procedural_organizing",
    title: "Operational and Procedural Organizing",
    description: "Workflows, SOPs, handoffs, and procedure maintenance.",
    order: 17,
    collapsedByDefault: true,
    sectionIds: [
      "workflow_map",
      "roles_handoffs",
      "sop_design",
      "recurring_rhythms",
      "visibility_ops",
      "ops_maintenance",
    ],
  },
  {
    groupId: "strategic_management_organizing",
    title: "Strategic and Management Organizing",
    description: "Priorities, initiatives, decisions, and management cadence.",
    order: 18,
    collapsedByDefault: true,
    sectionIds: [
      "priority_structure",
      "initiative_map",
      "decision_log_org",
      "meeting_rhythms",
      "alignment_load",
      "management_cadence",
    ],
  },
  {
    groupId: "stewardship",
    title: "Money and Stewardship",
    description: "Profit, taxes, analytics, linked work, and review.",
    order: 19,
    collapsedByDefault: true,
    sectionIds: [
      "expenses_taxes",
      "profitability",
      "analytics",
      "linked_event_work",
      "next_actions",
      "review_rhythm",
    ],
  },
];
