/**
 * Business Plan map groups — schema config only (201–210).
 */

import type { BlueprintGroup } from "../../blueprints/types";

export const BUSINESS_PLAN_MAP_GROUPS: readonly BlueprintGroup[] = [
  {
    groupId: "foundation",
    title: "Foundation",
    description: "Vision, products, customers, and pricing.",
    order: 0,
    collapsedByDefault: false,
    sectionIds: [
      "purpose_vision",
      "products_offers",
      "customers_audience",
      "positioning",
      "pricing",
      "inventory",
      "shop_setup",
      "branding",
    ],
  },
  {
    groupId: "in_person_shows",
    title: "Shows and Markets",
    description: "Booth, applications, travel, and day-of selling.",
    order: 1,
    collapsedByDefault: true,
    sectionIds: [
      "booth_design",
      "show_discovery",
      "jury_applications",
      "annual_calendar",
      "travel_logistics",
      "packing_loading",
      "pos_checkout",
      "lead_capture",
      "customer_relationships",
      "vendor_documents",
      "restocking_seasonal",
      "post_show_review",
    ],
  },
  {
    groupId: "online_store",
    title: "Online Store",
    description: "Marketplaces, listings, shipping, and digital growth.",
    order: 2,
    collapsedByDefault: true,
    sectionIds: [
      "photography",
      "listings_seo",
      "marketplaces",
      "shipping_packaging",
      "customer_service",
      "reviews_reputation",
      "ads",
      "email_marketing",
      "social_pinterest",
      "launches_promotions",
      "seasonal_planning",
      "automation",
    ],
  },
  {
    groupId: "product_photography",
    title: "Product Photography",
    description: "Shot lists, lighting, styling, editing, and marketplace specs.",
    order: 3,
    collapsedByDefault: true,
    sectionIds: [
      "shot_lists",
      "lighting",
      "backgrounds",
      "styling",
      "lifestyle_images",
      "video_clips",
      "editing_workflow",
      "image_organization",
      "accessibility_alt_text",
      "marketplace_image_requirements",
    ],
  },
  {
    groupId: "inventory_pricing",
    title: "Inventory and Pricing",
    description: "Costs, margins, forecasting, and stock decisions.",
    order: 4,
    collapsedByDefault: true,
    sectionIds: [
      "cost_of_goods",
      "labor_cost",
      "overhead",
      "profit_margin",
      "inventory_forecasting",
      "bundles",
      "seasonal_stock",
      "reorder_points",
      "best_sellers",
      "dead_inventory",
    ],
  },
  {
    groupId: "holiday_collections",
    title: "Holiday Collections",
    description: "Seasonal collections, production, and launch timing.",
    order: 5,
    collapsedByDefault: true,
    sectionIds: [
      "collection_planning",
      "production_schedule",
      "launch_timeline",
      "seasonal_campaigns",
    ],
  },
  {
    groupId: "speaker_business",
    title: "Speaker Business",
    description: "Talks, buyers, booking, fees, and delivery.",
    order: 6,
    collapsedByDefault: true,
    sectionIds: [
      "audience_buyer_architecture",
      "signature_talk_portfolio",
      "speaking_offers",
      "speaker_marketing",
      "booking_pipeline",
      "speaker_proposal",
      "event_preparation",
      "delivery_experience",
      "post_event_followup",
      "speaker_operations",
    ],
  },
  {
    groupId: "coaching_business",
    title: "Coaching Business",
    description: "Fit, offers, enrollment, delivery, and renewal.",
    order: 7,
    collapsedByDefault: true,
    sectionIds: [
      "client_fit",
      "coaching_offers",
      "coaching_framework",
      "coaching_marketing",
      "discovery_enrollment",
      "coaching_onboarding",
      "coaching_delivery",
      "completion_renewal",
      "coaching_operations",
    ],
  },
  {
    groupId: "consulting_business",
    title: "Consulting Business",
    description: "Diagnosis, proposals, delivery, and closeout.",
    order: 8,
    collapsedByDefault: true,
    sectionIds: [
      "service_architecture",
      "diagnostic_method",
      "lead_generation",
      "qualification_discovery",
      "proposal_contract",
      "engagement_kickoff",
      "consulting_delivery",
      "client_communication",
      "outcomes_closeout",
      "consulting_operations",
    ],
  },
  {
    groupId: "service_operating",
    title: "Service Operating",
    description: "Menu, inquiry, delivery, payment, and retention.",
    order: 9,
    collapsedByDefault: true,
    sectionIds: [
      "service_menu",
      "client_acquisition",
      "inquiry_qualification",
      "estimate_proposal",
      "service_onboarding",
      "delivery_workflow",
      "change_issue_management",
      "completion_payment",
      "followup_retention",
      "service_operations",
    ],
  },
  {
    groupId: "stewardship",
    title: "Money and Stewardship",
    description: "Profit, taxes, analytics, linked work, and review.",
    order: 10,
    collapsedByDefault: true,
    sectionIds: [
      "expenses_taxes",
      "profitability",
      "analytics",
      "linked_event_work",
      "next_actions",
      "review_rhythm",
    ],
  },
];
