import { voiceLines } from "../entryBuilder";
import type { ShariVoiceLine } from "../types";

/** Volume expansion — relationship progression, Iowa homestead, life rhythms. */
export const EXPANSION_GREETINGS: ShariVoiceLine[] = [
  ...voiceLines(
    "morning",
    "greeting",
    [
      "Sun's up.",
      "Kitchen's warm.",
      "Birds are loud.",
      "Fresh pot.",
      "Early one.",
      "Soft morning.",
      "Rain on the roof — morning.",
      "Cold out. Hi.",
      "Hi — porch light still on.",
      "Morning light's good in here.",
    ],
    { timeOfDay: ["morning"] },
  ),
  ...voiceLines(
    "afternoon",
    "greeting",
    [
      "Afternoon.",
      "Day's moving.",
      "Hi — halfway through.",
      "Sun's shifted.",
      "Busy out there?",
      "Quiet afternoon.",
      "Hi. Kettle's on.",
      "Still going?",
      "Afternoon pause.",
      "Hi — come cool off.",
    ],
    { timeOfDay: ["afternoon", "midday"] },
  ),
  ...voiceLines(
    "evening",
    "greeting",
    [
      "Evening.",
      "Day's winding down.",
      "Hi. Shoes off.",
      "Lamp's on.",
      "Quiet evening.",
      "Hi — long one?",
      "Sun went down.",
      "Evening hush.",
      "Hi. Table's clear.",
      "Kitchen smells like dinner.",
    ],
    { timeOfDay: ["evening"] },
  ),
  ...voiceLines(
    "late_night",
    "greeting",
    [
      "House is quiet.",
      "Moon's out.",
      "Late one.",
      "Hi. World asleep.",
      "Still going?",
      "Night owl?",
      "Hi — tea?",
      "Clock says late.",
      "Stars are out.",
      "Hi. Soft light only.",
    ],
    { timeOfDay: ["late_night"] },
  ),
  ...voiceLines(
    "first_visit",
    "greeting",
    [
      "Hi.",
      "Door's open.",
      "Come in — shoes anywhere.",
      "Hi. House is yours.",
      "Welcome.",
      "Hi — glad you found us.",
      "Come in out of the weather.",
      "Hi. Mi casa.",
    ],
    { relationshipStages: ["day_one"] },
  ),
  ...voiceLines(
    "second_visit",
    "greeting",
    [
      "Back.",
      "Hi again.",
      "You came back.",
      "Hi — good.",
      "There you are again.",
      "Hi. Familiar face.",
    ],
    { relationshipStages: ["early"] },
  ),
  ...voiceLines(
    "return_one_day",
    "greeting",
    ["Yesterday feels close.", "Hi.", "Back so soon?", "Hi — good day?"],
  ),
  ...voiceLines(
    "return_one_week",
    "greeting",
    ["Week flew.", "Hi.", "Seven days.", "Been a week."],
  ),
  ...voiceLines(
    "return_one_month",
    "greeting",
    ["Month already.", "Hi.", "Time moves.", "Been a minute."],
  ),
  ...voiceLines(
    "return_six_months",
    "greeting",
    ["Half a year.", "Hi.", "Seasons changed.", "Been a while."],
  ),
  ...voiceLines(
    "return_long_absence",
    "greeting",
    [
      "Hi.",
      "Long time.",
      "Door was always open.",
      "Hi — you made it back.",
      "Been too long.",
      "Hi. Same house.",
    ],
  ),
  ...voiceLines(
    "weekend",
    "greeting",
    [
      "Slow morning.",
      "Weekend pace.",
      "No alarm day.",
      "Saturday quiet.",
      "Sunday stillness.",
      "Weekend hi.",
      "Lazy morning?",
      "Off the clock.",
    ],
    { tags: ["weekend"] },
  ),
  ...voiceLines(
    "monday_morning",
    "greeting",
    [
      "Monday.",
      "Week starts.",
      "Monday again.",
      "Fresh week.",
      "Monday morning.",
      "New week energy.",
    ],
    { timeOfDay: ["morning"], tags: ["monday"] },
  ),
  ...voiceLines(
    "friday_evening",
    "greeting",
    [
      "Friday.",
      "Week's done.",
      "Friday night.",
      "Made it.",
      "Weekend's here.",
      "Friday exhale.",
    ],
    { timeOfDay: ["evening"], tags: ["friday"] },
  ),
  ...voiceLines(
    "rainy_day",
    "greeting",
    [
      "Wet one.",
      "Rain day.",
      "Puddles outside.",
      "Gray sky.",
      "Rain keeps falling.",
      "Cozy inside.",
    ],
    { tags: ["rain"] },
  ),
  ...voiceLines(
    "snowy_iowa_day",
    "greeting",
    [
      "Snow day.",
      "White outside.",
      "Iowa winter.",
      "Flakes falling.",
      "Cold snap.",
      "Boots by the door.",
    ],
    { seasons: ["winter"], tags: ["snow"] },
  ),
  ...voiceLines(
    "sunny_summer_day",
    "greeting",
    [
      "Hot one.",
      "Summer sun.",
      "Fan's on.",
      "Bright day.",
      "Iowa summer.",
      "Humidity's up.",
    ],
    { seasons: ["summer"], tags: ["sun"] },
  ),
  ...voiceLines(
    "birthday",
    "greeting",
    [
      "Happy birthday.",
      "Today's yours.",
      "Birthday hi.",
      "Cake weather.",
      "Your day.",
    ],
    { tags: ["birthday"] },
  ),
  ...voiceLines(
    "holiday_season",
    "greeting",
    [
      "Holiday time.",
      "Lights up.",
      "Season's here.",
      "Cozy season.",
      "Holiday hi.",
    ],
    { seasons: ["holiday", "winter"] },
  ),
  ...voiceLines(
    "celebrating",
    "greeting",
    ["Good day.", "Something up?", "Hi — energy?", "Win in the air?"],
    { emotionalTags: ["celebrating", "excited"] },
  ),
  ...voiceLines(
    "discouraged",
    "greeting",
    ["Hi.", "Come in.", "Rough stretch?", "Hi. Seat's open."],
    { emotionalTags: ["discouraged"] },
  ),
  ...voiceLines(
    "overwhelmed",
    "greeting",
    ["Hi.", "Come in.", "No rush.", "Hi. Door's shut behind you."],
    { emotionalTags: ["overwhelmed"] },
  ),
  ...voiceLines(
    "exhausted",
    "greeting",
    ["Hi.", "Tired?", "Come sit.", "Long haul?"],
    { emotionalTags: ["exhausted"] },
  ),
  ...voiceLines(
    "quiet",
    "greeting",
    ["Hi.", "…", "Come in."],
    { emotionalTags: ["quiet", "neutral"], standsAlone: true },
  ),
  ...voiceLines(
    "business_win",
    "greeting",
    ["Good news?", "Win?", "Something landed?", "Hi — big one?"],
    { tags: ["win"] },
  ),
  ...voiceLines(
    "launch_week",
    "greeting",
    ["Big week.", "Launch?", "Heavy week?", "Countdown?"],
    { tags: ["launch"] },
  ),
  ...voiceLines(
    "after_hard_week",
    "greeting",
    ["Survived the week.", "Hard week?", "Friday finally.", "Week was a lot."],
    { tags: ["hard_week"] },
  ),
  ...voiceLines(
    "after_avoiding_app",
    "greeting",
    ["Hi.", "There you are.", "No lecture.", "Door's open.", "Hi — welcome back."],
    { tags: ["return_after_gap"] },
  ),
  ...voiceLines(
    "from_planning_table",
    "greeting",
    ["Back from the table.", "Planner time done?", "Hi.", "Table's behind you."],
    { rooms: ["planning-table"] },
  ),
  ...voiceLines(
    "from_clear_my_mind",
    "greeting",
    ["Lighter?", "Hi.", "Head clearer?", "Back from the window."],
    { rooms: ["window-seat"] },
  ),
  ...voiceLines(
    "from_creative_studio",
    "greeting",
    ["Studio time done?", "Hi.", "Made something?", "Back from creating."],
    { rooms: ["creative-studio"] },
  ),
  ...voiceLines(
    "from_reading_nook",
    "greeting",
    ["Good read?", "Nook time?", "Hi.", "Pages turned?"],
    { rooms: ["reading-nook"] },
  ),
  ...voiceLines(
    "morning",
    "greeting",
    ["Hi.", "Morning.", "Coffee?"],
    {
      relationshipStages: ["kin"],
      timeOfDay: ["morning"],
      standsAlone: true,
      frequencyWeight: 1.5,
    },
  ),
  ...voiceLines(
    "afternoon",
    "greeting",
    ["Hi.", "Hey.", "There you are."],
    {
      relationshipStages: ["kin", "deep"],
      timeOfDay: ["afternoon", "midday"],
      standsAlone: true,
      frequencyWeight: 1.5,
    },
  ),
];

export const EXPANSION_QUESTIONS: ShariVoiceLine[] = [
  ...voiceLines("variable_question", "question", [
    "What's the vibe today?",
    "What's been loudest?",
    "What's been quiet?",
    "What's true right now?",
    "What's underneath?",
    "What's the headline?",
    "What's the subtext?",
    "What's been eating at you?",
    "What's been lifting you?",
    "What's unfinished?",
    "What's done?",
    "What's next — if anything?",
    "What's the weather in your head?",
    "What's the body saying?",
    "What's the heart saying?",
    "What's one word for today?",
    "What's two words for today?",
    "What's the hardest win?",
    "What's the easiest win?",
    "What's been avoided?",
    "What's been faced?",
    "What's been postponed?",
    "What's been surprising?",
    "What's been boring?",
    "What's been beautiful?",
    "What's been annoying?",
    "What's been tender?",
    "What's been sharp?",
    "What's been slow?",
    "What's been fast?",
    "What's been enough?",
    "What's been not enough?",
    "What's been missing?",
    "What's been extra?",
    "What's been loud in the background?",
    "What's been quiet in the background?",
    "What's the first thing that comes up?",
    "What's the last thing from yesterday?",
    "What's the thing you don't want to forget?",
    "What's the thing you want to forget?",
  ]),
  ...voiceLines(
    "first_visit",
    "question",
    [
      "What's going on?",
      "What brought you in?",
      "What's happening?",
      "What's the reason for today?",
    ],
    { relationshipStages: ["day_one"] },
  ),
  ...voiceLines(
    "return_long_absence",
    "question",
    [
      "What's changed?",
      "What's the same?",
      "What's new in your world?",
      "What's been the big thing?",
    ],
  ),
];

export const EXPANSION_ECHOES: ShariVoiceLine[] = [
  ...voiceLines("echo", "echo", [
    "Okay.",
    "Got it.",
    "Mm.",
    "Yeah.",
    "I hear that.",
    "That's real.",
    "That's a lot to carry.",
    "That's heavy.",
    "That's good.",
    "That's hard.",
  ], { emotionalTags: ["neutral"] }),
  ...voiceLines(
    "overwhelmed",
    "echo",
    ["Too much.", "One thing at a time.", "Slow is fine."],
    { emotionalTags: ["overwhelmed"] },
  ),
  ...voiceLines(
    "after_grief",
    "echo",
    ["I'm sorry.", "No fixing.", "Just here."],
    { emotionalTags: ["grief"] },
  ),
  ...voiceLines(
    "celebrating",
    "echo",
    ["Good.", "Love that.", "About time."],
    { emotionalTags: ["celebrating", "good_news"] },
  ),
];

export const EXPANSION_WALKING: ShariVoiceLine[] = [
  ...voiceLines("walking", "walking", [
    "Through here.",
    "This way.",
    "Come on.",
    "Right here.",
    "Down the hall.",
    "Around the corner.",
  ]),
  ...voiceLines(
    "walking",
    "walking",
    ["Focus studio.", "Quiet corner."],
    { rooms: ["focus-studio"] },
  ),
  ...voiceLines(
    "walking",
    "walking",
    ["Reading nook.", "Nook's this way."],
    { rooms: ["reading-nook"] },
  ),
];
