import { TIME_OF_DAY_ENTRIES, TIME_OF_DAY_QUESTIONS } from "./timeOfDay";
import { VISIT_CONTEXT_GREETINGS, VISIT_CONTEXT_QUESTIONS } from "./visitContext";
import { SEASONAL_GREETINGS, CALENDAR_GREETINGS } from "./seasonal";
import {
  EMOTIONAL_GREETINGS,
  LIFE_MOMENT_GREETINGS,
  EMOTIONAL_ECHOES,
} from "./emotional";
import { ROOM_RETURN_GREETINGS, WALKING_LINES } from "./roomReturn";
import {
  VARIABLE_QUESTIONS,
  PLACEHOLDER_LINES,
  CLARIFY_QUESTIONS,
  SOFT_PRESENCE_LINES,
} from "./questions";
import { TOPIC_FOLLOW_UP_QUESTIONS } from "./topicFollowUp";
import { PRESENCE_WONDER_QUESTIONS } from "./presenceWonder";
import { ROOM_INVITATIONS } from "./invitations";
import {
  EXPANSION_ECHOES,
  EXPANSION_GREETINGS,
  EXPANSION_QUESTIONS,
  EXPANSION_WALKING,
} from "./expansion";
import { SHARIS_LIFE_MOMENT_LINES } from "./lifeMoments";
import type { ShariVoiceLine } from "../types";

export const SHARI_VOICE_BIBLE_ENTRIES: readonly ShariVoiceLine[] = [
  ...TIME_OF_DAY_ENTRIES,
  ...TIME_OF_DAY_QUESTIONS,
  ...VISIT_CONTEXT_GREETINGS,
  ...VISIT_CONTEXT_QUESTIONS,
  ...SEASONAL_GREETINGS,
  ...CALENDAR_GREETINGS,
  ...EMOTIONAL_GREETINGS,
  ...LIFE_MOMENT_GREETINGS,
  ...EMOTIONAL_ECHOES,
  ...ROOM_RETURN_GREETINGS,
  ...WALKING_LINES,
  ...VARIABLE_QUESTIONS,
  ...PLACEHOLDER_LINES,
  ...CLARIFY_QUESTIONS,
  ...SOFT_PRESENCE_LINES,
  ...TOPIC_FOLLOW_UP_QUESTIONS,
  ...PRESENCE_WONDER_QUESTIONS,
  ...ROOM_INVITATIONS,
  ...EXPANSION_GREETINGS,
  ...EXPANSION_QUESTIONS,
  ...EXPANSION_ECHOES,
  ...EXPANSION_WALKING,
  ...SHARIS_LIFE_MOMENT_LINES,
];

export const SHARI_VOICE_BIBLE_ENTRY_COUNT = SHARI_VOICE_BIBLE_ENTRIES.length;
