/**
 * RUNTIME COPY — generated from the authoring source, do not edit by hand.
 * Source: Intelligence Library/Spark-card-files/spark-iowa-winter-seasonal.ts
 * The authoring file is the source of truth; edits belong there, then re-copy.
 */
import type { FutureSparkCard } from "../futureSparkCard";

export const iowaWinterSparkCards: FutureSparkCard[] = [
  {
    id: "SPARK-IOWA-WINTER-001",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "seasonal",
    priority: 140,
    category: "004",
    categoryLabel: "Nature & Places",
    categoryImage: "/spark-card-images/nature.png",
    title: "The First Snow Over an Iowa Field",
    story: "The first lasting snow changes the familiar geometry of Iowa fields, fences, barns, and roads. Edges become softer, sound becomes quieter, and details that were easy to overlook become visible through contrast. A changed surface can help us notice the structure that was there all along. Nature and place can teach timing, interdependence, adaptation, patience, and the value of seeing familiar surroundings with fresh attention. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A changed surface can help us notice the structure that was there all along. Nature and place can teach timing, interdependence, adaptation, patience, and the value of seeing familiar surroundings with fresh attention.",
    action: "Notice one natural pattern, place, or seasonal change today. Write one sentence about what it suggests about your own pace or direction. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Nature & Places", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-002",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "seasonal",
    priority: 140,
    category: "008",
    categoryLabel: "Reflection",
    categoryImage: "/spark-card-images/reflections.png",
    title: "What Winter Makes Us Notice",
    story: "Winter removes leaves, shortens daylight, and slows many outdoor routines. The season can make absence, structure, limits, and essential supports easier to see. Reflection often becomes clearer when excess is stripped away. Reflection turns experience into guidance. The goal is not to stay in the past, but to carry forward what the past can teach. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Reflection often becomes clearer when excess is stripped away. Reflection turns experience into guidance. The goal is not to stay in the past, but to carry forward what the past can teach.",
    action: "Write one sentence about what this story brings up for you, one lesson worth keeping, and one thing you may do differently. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Reflection", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-003",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "seasonal",
    priority: 140,
    category: "012",
    categoryLabel: "Wonder",
    categoryImage: "/spark-card-images/worlds.png",
    title: "Frost Feathers on the Window",
    story: "Frost can form intricate branching patterns when water vapor freezes on cold glass. Temperature, moisture, and tiny surface differences shape each design. Wonder can emerge from ordinary conditions arranged with precision. Wonder interrupts routine and restores perspective. It reminds us that the world still contains more than we have noticed. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Wonder can emerge from ordinary conditions arranged with precision. Wonder interrupts routine and restores perspective. It reminds us that the world still contains more than we have noticed.",
    action: "Spend five quiet minutes noticing something that creates awe, surprise, or delight. Save one sentence about what shifted in your perspective. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Wonder", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-004",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "seasonal",
    priority: 140,
    category: "003",
    categoryLabel: "Creativity & Inspiration",
    categoryImage: "/spark-card-images/creativity.png",
    title: "The Indoor Season of Making",
    story: "Cold Iowa days often move creativity indoors: quilting, woodworking, baking, journaling, painting, and repairing. Winter can become a season for work that needs concentration more than motion. A smaller physical world can create deeper creative attention. Creativity grows through attention, experimentation, revision, and the courage to make an imperfect beginning. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A smaller physical world can create deeper creative attention. Creativity grows through attention, experimentation, revision, and the courage to make an imperfect beginning.",
    action: "Make a rough version of one idea before judging it. Give yourself ten minutes to explore rather than perfect. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Creativity & Inspiration", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-005",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "seasonal",
    priority: 140,
    category: "009",
    categoryLabel: "Adventure",
    categoryImage: "/spark-card-images/adventure.png",
    title: "The Quiet Adventure of a Snow Day",
    story: "A snow day changes routine and creates a temporary world of altered roads, canceled plans, and unexpected time. Even familiar places can feel newly explored. Adventure sometimes begins when ordinary schedules are interrupted. Adventure begins with movement into the unfamiliar. The step only needs to teach something that staying still cannot. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Adventure sometimes begins when ordinary schedules are interrupted. Adventure begins with movement into the unfamiliar. The step only needs to teach something that staying still cannot.",
    action: "Take one safe step beyond routine. Make it small enough to begin today and meaningful enough to teach you something. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Adventure", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-006",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "seasonal",
    priority: 140,
    category: "010",
    categoryLabel: "Business",
    categoryImage: "/spark-card-images/business.png",
    title: "The Business of Preparing Before the Storm",
    story: "Iowa businesses and households often prepare for winter weather by checking supplies, communication plans, staffing, and safety procedures. Reliability is created before pressure arrives, not during the crisis alone. Strong businesses create value people can understand and trust. The lesson is usually found in the decisions beneath the visible success. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Reliability is created before pressure arrives, not during the crisis alone. Strong businesses create value people can understand and trust. The lesson is usually found in the decisions beneath the visible success.",
    action: "Apply the lesson to one customer, offer, process, or decision. Ask what would make the experience clearer, more useful, or more trustworthy. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Business", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-007",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "seasonal",
    priority: 140,
    category: "005",
    categoryLabel: "Curiosity",
    categoryImage: "/spark-card-images/curiosity.png",
    title: "Why Snow Makes the World Quieter",
    story: "Fresh snow can absorb and scatter sound because of the air spaces between flakes. The result is a noticeable softening of the environment. A change in texture can transform how a place feels even when nothing else moves. Curiosity loosens assumptions. A better question can reveal options that certainty would have hidden. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A change in texture can transform how a place feels even when nothing else moves. Curiosity loosens assumptions. A better question can reveal options that certainty would have hidden.",
    action: "Take one assumption you have been treating as fixed and turn it into three open questions. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Curiosity", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-008",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "seasonal",
    priority: 140,
    category: "007",
    categoryLabel: "Strategy",
    categoryImage: "/spark-card-images/strategy.png",
    title: "The Value of a Winter Reserve",
    story: "Farmers, families, and businesses prepare for winter by creating reserves of fuel, food, cash, time, or capacity. The reserve is not wasted simply because it is not used immediately. Resilience often looks like unused capacity until the day it is needed. Strategy is choosing what matters most, learning from evidence, and placing limited effort where it can create the greatest useful change. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Resilience often looks like unused capacity until the day it is needed. Strategy is choosing what matters most, learning from evidence, and placing limited effort where it can create the greatest useful change.",
    action: "Identify the decision underneath your current activity. Choose the smallest next move that would create useful information. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Strategy", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-009",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "seasonal",
    priority: 140,
    category: "006",
    categoryLabel: "Words & Origins",
    categoryImage: "/spark-card-images/word.png",
    title: "Why We Call It a Cold Snap",
    story: "The phrase cold snap describes a sudden period of unusually cold weather. The word snap captures both speed and sharpness. Language often turns weather into a physical sensation we can imagine. Words shape what we notice and remember. Naming an experience can make it easier to understand, share, and use. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Language often turns weather into a physical sensation we can imagine. Words shape what we notice and remember. Naming an experience can make it easier to understand, share, and use.",
    action: "Save one word or phrase that stayed with you. Add a note about why it matters and where you might use it. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Words & Origins", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-010",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "calculated-date",
    dateRule: "winter-solstice",
    priority: 320,
    category: "012",
    categoryLabel: "Wonder",
    categoryImage: "/spark-card-images/worlds.png",
    title: "The Longest Night and the Return of Light",
    story: "The winter solstice marks the shortest day and longest night of the year in the Northern Hemisphere. After it, daylight begins returning gradually. A turning point may occur before the improvement is easy to feel. Wonder interrupts routine and restores perspective. It reminds us that the world still contains more than we have noticed. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A turning point may occur before the improvement is easy to feel. Wonder interrupts routine and restores perspective. It reminds us that the world still contains more than we have noticed.",
    action: "Spend five quiet minutes noticing something that creates awe, surprise, or delight. Save one sentence about what shifted in your perspective. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Wonder", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-011",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "exact-date",
    month: 1,
    day: 1,
    priority: 320,
    category: "008",
    categoryLabel: "Reflection",
    categoryImage: "/spark-card-images/reflections.png",
    title: "A New Year Without the Pressure to Reinvent",
    story: "January 1 often carries expectations of dramatic change. A more sustainable beginning may come from one honest review, one meaningful priority, and one supportive condition. Renewal does not require rejecting the person you were yesterday. Reflection turns experience into guidance. The goal is not to stay in the past, but to carry forward what the past can teach. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Renewal does not require rejecting the person you were yesterday. Reflection turns experience into guidance. The goal is not to stay in the past, but to carry forward what the past can teach.",
    action: "Write one sentence about what this story brings up for you, one lesson worth keeping, and one thing you may do differently. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Reflection", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-WINTER-012",
    volume: 3,
    collection: "iowa-seasons",
    season: "winter",
    region: "Iowa",
    months: [12, 1, 2],
    displayRule: "calculated-date",
    dateRule: "mlk-day-us",
    priority: 320,
    category: "002",
    categoryLabel: "People & Stories",
    categoryImage: "/spark-card-images/people.png",
    title: "The Work of Dr. Martin Luther King Jr.",
    story: "Martin Luther King Jr. Day honors a leader whose work joined moral vision, organized action, public courage, and collective participation. The day is observed on the third Monday in January. A legacy becomes active when remembrance influences present choices. A person’s story becomes useful when it helps us recognize choices, courage, persistence, and possibility in our own life. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A legacy becomes active when remembrance influences present choices. A person’s story becomes useful when it helps us recognize choices, courage, persistence, and possibility in our own life.",
    action: "Choose one quality from this story that you want to practice today. Name one small way it could appear in your work or relationships. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["People & Stories", "iowa-seasons", "volume-3"],
    status: "future-ready",
  },
];
