/**
 * RUNTIME COPY — generated from the authoring source, do not edit by hand.
 * Source: Intelligence Library/Spark-card-files/spark-iowa-spring-seasonal.ts
 * The authoring file is the source of truth; edits belong there, then re-copy.
 */
import type { FutureSparkCard } from "../futureSparkCard";

export const iowaSpringSparkCards: FutureSparkCard[] = [
  {
    id: "SPARK-IOWA-SPRING-001",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "seasonal",
    priority: 140,
    category: "004",
    categoryLabel: "Nature & Places",
    categoryImage: "/spark-card-images/nature.png",
    title: "When Iowa Fields Turn Green Again",
    story: "Early spring growth changes Iowa fields gradually, often before the landscape looks fully awake. Renewal becomes visible through many small changes rather than one dramatic moment. Nature and place reveal timing, interdependence, adaptation, patience, and the value of looking closely. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Renewal becomes visible through many small changes rather than one dramatic moment. Nature and place reveal timing, interdependence, adaptation, patience, and the value of looking closely.",
    action: "Notice one natural pattern or place today and write what it suggests about your own pace. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Nature & Places", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-002",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "seasonal",
    priority: 140,
    category: "008",
    categoryLabel: "Reflection",
    categoryImage: "/spark-card-images/reflections.png",
    title: "The First Open Window",
    story: "A mild spring day can bring fresh air into rooms closed through winter. A small opening can signal that a difficult season is loosening. Reflection turns experience into guidance rather than leaving it as an unexamined memory. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A small opening can signal that a difficult season is loosening. Reflection turns experience into guidance rather than leaving it as an unexamined memory.",
    action: "Write one lesson worth keeping and one thing you may do differently. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Reflection", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-003",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "seasonal",
    priority: 140,
    category: "012",
    categoryLabel: "Wonder",
    categoryImage: "/spark-card-images/worlds.png",
    title: "The Chorus of Spring Peepers",
    story: "Tiny frogs can fill wet Iowa evenings with sound soon after thaw. Wonder often arrives through voices much smaller than the space they fill. Wonder interrupts routine and restores perspective by reminding us how much remains unseen. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Wonder often arrives through voices much smaller than the space they fill. Wonder interrupts routine and restores perspective by reminding us how much remains unseen.",
    action: "Spend five quiet minutes noticing something that creates awe or surprise. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Wonder", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-004",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "seasonal",
    priority: 140,
    category: "003",
    categoryLabel: "Creativity & Inspiration",
    categoryImage: "/spark-card-images/creativity.png",
    title: "The Garden Plan Drawn Before Planting",
    story: "Spring gardens begin with sketches, seed choices, spacing, and imagination long before harvest. Creative work can begin as a plan for conditions, not only a finished object. Creativity grows through attention, experimentation, revision, and the courage to make an imperfect beginning. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Creative work can begin as a plan for conditions, not only a finished object. Creativity grows through attention, experimentation, revision, and the courage to make an imperfect beginning.",
    action: "Make a rough version of one idea before judging it. Explore for ten minutes. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Creativity & Inspiration", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-005",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "seasonal",
    priority: 140,
    category: "009",
    categoryLabel: "Adventure",
    categoryImage: "/spark-card-images/adventure.png",
    title: "The First Trail Without Snow",
    story: "A familiar Iowa trail feels new when mud, water, buds, and returning birds replace winter stillness. Adventure can come from revisiting a place at a different moment. Adventure begins with movement into the unfamiliar and the willingness to learn from what happens. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Adventure can come from revisiting a place at a different moment. Adventure begins with movement into the unfamiliar and the willingness to learn from what happens.",
    action: "Take one safe step beyond routine that can teach you something. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Adventure", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-006",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "seasonal",
    priority: 140,
    category: "010",
    categoryLabel: "Business",
    categoryImage: "/spark-card-images/business.png",
    title: "The Business of Planting Season",
    story: "Spring farm work depends on weather, soil conditions, equipment readiness, timing, and coordination. A narrow opportunity is easier to use when preparation happened beforehand. Strong businesses create value people can understand and trust through the decisions beneath the visible offer. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A narrow opportunity is easier to use when preparation happened beforehand. Strong businesses create value people can understand and trust through the decisions beneath the visible offer.",
    action: "Apply the lesson to one customer, offer, process, or decision. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Business", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-007",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "seasonal",
    priority: 140,
    category: "005",
    categoryLabel: "Curiosity",
    categoryImage: "/spark-card-images/curiosity.png",
    title: "Why Spring Smells Different",
    story: "Moist soil, plant growth, rain, and microbial activity create distinctive spring scents. A season can be recognized through chemistry before the eye sees every change. Curiosity loosens assumptions and creates room for better questions. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A season can be recognized through chemistry before the eye sees every change. Curiosity loosens assumptions and creates room for better questions.",
    action: "Turn one assumption into three open questions. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Curiosity", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-008",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "seasonal",
    priority: 140,
    category: "007",
    categoryLabel: "Strategy",
    categoryImage: "/spark-card-images/strategy.png",
    title: "The Decision to Plant Now or Wait",
    story: "Farmers weigh soil temperature, moisture, weather forecasts, and risk before planting. Strategy often means acting with incomplete information at the best available moment. Strategy means choosing what matters most and placing effort where it can create the greatest useful change. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Strategy often means acting with incomplete information at the best available moment. Strategy means choosing what matters most and placing effort where it can create the greatest useful change.",
    action: "Name the decision beneath your current activity and choose the smallest useful next move. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Strategy", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-009",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "seasonal",
    priority: 140,
    category: "006",
    categoryLabel: "Words & Origins",
    categoryImage: "/spark-card-images/word.png",
    title: "Why We Call It Spring",
    story: "The season’s name is connected to plants springing or rising from the ground. A word can preserve the visible movement that defined a season. Words shape what we notice, remember, and make possible together. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A word can preserve the visible movement that defined a season. Words shape what we notice, remember, and make possible together.",
    action: "Save one word or phrase that stayed with you and note why it matters. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Words & Origins", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-010",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "calculated-date",
    dateRule: "spring-equinox",
    priority: 320,
    category: "012",
    categoryLabel: "Wonder",
    categoryImage: "/spark-card-images/worlds.png",
    title: "The Balance of the Spring Equinox",
    story: "Around the spring equinox, day and night are close to equal before daylight continues increasing. A turning point can mark balance while also beginning a new direction. Wonder interrupts routine and restores perspective by reminding us how much remains unseen. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A turning point can mark balance while also beginning a new direction. Wonder interrupts routine and restores perspective by reminding us how much remains unseen.",
    action: "Spend five quiet minutes noticing something that creates awe or surprise. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Wonder", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-011",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "calculated-date",
    dateRule: "mothers-day-us",
    priority: 320,
    category: "002",
    categoryLabel: "People & Stories",
    categoryImage: "/spark-card-images/people.png",
    title: "The Work of Mothers and Caregivers",
    story: "Mother’s Day can honor biological mothers, adoptive mothers, grandmothers, mentors, and others whose care shaped a life. Care is often remembered most clearly through repeated ordinary acts. A life story becomes useful when it helps us recognize choices, courage, persistence, and possibility in our own. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Care is often remembered most clearly through repeated ordinary acts. A life story becomes useful when it helps us recognize choices, courage, persistence, and possibility in our own.",
    action: "Choose one quality from this story and name one small way to practice it today. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["People & Stories", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-SPRING-012",
    volume: 4,
    collection: "iowa-seasons",
    season: "spring",
    region: "Iowa",
    months: [3, 4, 5],
    displayRule: "calculated-date",
    dateRule: "memorial-day-us",
    priority: 320,
    category: "008",
    categoryLabel: "Reflection",
    categoryImage: "/spark-card-images/reflections.png",
    title: "Memorial Day and the Cost Remembered",
    story: "Memorial Day honors members of the U.S. military who died in service. Remembrance asks us to pause before turning sacrifice into a general symbol. Reflection turns experience into guidance rather than leaving it as an unexamined memory. The value is not only knowing the story, but recognizing where the same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Remembrance asks us to pause before turning sacrifice into a general symbol. Reflection turns experience into guidance rather than leaving it as an unexamined memory.",
    action: "Write one lesson worth keeping and one thing you may do differently. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Reflection", "iowa-seasons", "volume-4"],
    status: "future-ready",
  },
];
