/**
 * RUNTIME COPY — generated from the authoring source, do not edit by hand.
 * Source: Intelligence Library/Spark-card-files/spark-iowa-fall-seasonal.ts
 * The authoring file is the source of truth; edits belong there, then re-copy.
 */
import type { FutureSparkCard } from "../futureSparkCard";

export const iowaFallSparkCards: FutureSparkCard[] = [
  {
    id: "SPARK-IOWA-FALL-001",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "seasonal",
    priority: 140,
    category: "004",
    categoryLabel: "Nature & Places",
    categoryImage: "/spark-card-images/nature.png",
    title: "When the Cornfields Turn Gold",
    story: "By early autumn, Iowa fields begin changing from summer green to shades of gold and brown. The change signals maturity, drying grain, shorter days, and the approach of harvest. A landscape can show readiness through color long before the work is complete. Nature and place can teach us about timing, interdependence, adaptation, patience, and the value of seeing a familiar landscape with fresh attention. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A landscape can show readiness through color long before the work is complete. Nature and place can teach us about timing, interdependence, adaptation, patience, and the value of seeing a familiar landscape with fresh attention.",
    action: "Notice one natural pattern, place, or seasonal change today. Write one sentence about what it suggests about your own pace or direction. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Nature & Places", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-002",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "seasonal",
    priority: 140,
    category: "008",
    categoryLabel: "Reflection",
    categoryImage: "/spark-card-images/reflections.png",
    title: "What the Harvest Reveals",
    story: "Harvest makes results visible: what grew well, what struggled, what weather changed, and what decisions mattered. The field becomes a record of the entire season rather than a single day. Reflection is a kind of harvest because it gathers meaning from what has already happened. Reflection turns experience into guidance. The goal is not to stay in the past, but to carry forward what the past can teach. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Reflection is a kind of harvest because it gathers meaning from what has already happened. Reflection turns experience into guidance. The goal is not to stay in the past, but to carry forward what the past can teach.",
    action: "Write one sentence about what this story brings up for you, one lesson worth keeping, and one thing you may do differently. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Reflection", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-003",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "seasonal",
    priority: 140,
    category: "012",
    categoryLabel: "Wonder",
    categoryImage: "/spark-card-images/worlds.png",
    title: "The Sound of Geese Overhead",
    story: "Migrating geese pass over Iowa in shifting formations, responding to weather, daylight, food, and one another. Their calls turn an ordinary sky into a reminder that movement is happening on a much larger scale. Wonder often arrives through a familiar event noticed at the right moment. Wonder interrupts routine and restores perspective. It reminds us that the world still contains more than we have noticed. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Wonder often arrives through a familiar event noticed at the right moment. Wonder interrupts routine and restores perspective. It reminds us that the world still contains more than we have noticed.",
    action: "Spend five quiet minutes noticing something that creates awe, surprise, or delight. Save one sentence about what shifted in your perspective. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Wonder", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-004",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "seasonal",
    priority: 140,
    category: "003",
    categoryLabel: "Creativity & Inspiration",
    categoryImage: "/spark-card-images/creativity.png",
    title: "The Creativity of an Iowa Quilt",
    story: "Autumn craft fairs and family gatherings often display quilts made from reused fabric, inherited patterns, and new choices. Each piece may be ordinary alone, but arrangement creates memory and design. Creativity can transform fragments into something coherent, useful, and deeply personal. Creativity is not reserved for rare bursts of inspiration. It grows through attention, experimentation, revision, and the courage to make an imperfect beginning. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Creativity can transform fragments into something coherent, useful, and deeply personal. Creativity is not reserved for rare bursts of inspiration. It grows through attention, experimentation, revision, and the courage to make an imperfect beginning.",
    action: "Make a rough version of one idea before judging it. Give yourself ten minutes to explore rather than perfect. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Creativity & Inspiration", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-005",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "seasonal",
    priority: 140,
    category: "009",
    categoryLabel: "Adventure",
    categoryImage: "/spark-card-images/adventure.png",
    title: "The Covered-Bridge Detour",
    story: "A fall drive through Iowa can become an adventure when the route includes a covered bridge, gravel road, small town, or unexpected overlook. The value is not speed but the decision to notice the journey. Adventure can begin by choosing a route that allows discovery instead of only efficiency. Adventure begins with movement into the unfamiliar. The step does not need to be dramatic; it only needs to teach something that staying still cannot. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Adventure can begin by choosing a route that allows discovery instead of only efficiency. Adventure begins with movement into the unfamiliar. The step does not need to be dramatic; it only needs to teach something that staying still cannot.",
    action: "Take one safe step beyond routine. Make it small enough to begin today and meaningful enough to teach you something. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Adventure", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-006",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "seasonal",
    priority: 140,
    category: "010",
    categoryLabel: "Business",
    categoryImage: "/spark-card-images/business.png",
    title: "The Business of the Pumpkin Patch",
    story: "A pumpkin patch may combine farming, hospitality, events, food, photography, and family tradition. Its value comes from turning a seasonal product into an experience people remember. A business can grow when it understands the larger experience customers are actually choosing. Strong businesses create value people can understand and trust. The lesson is usually found in the decisions beneath the success story. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A business can grow when it understands the larger experience customers are actually choosing. Strong businesses create value people can understand and trust. The lesson is usually found in the decisions beneath the success story.",
    action: "Apply the lesson to one customer, offer, process, or decision. Ask what would make the experience clearer, more useful, or more trustworthy. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Business", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-007",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "seasonal",
    priority: 140,
    category: "005",
    categoryLabel: "Curiosity",
    categoryImage: "/spark-card-images/curiosity.png",
    title: "Why Leaves Change Color",
    story: "As daylight shortens, trees reduce chlorophyll production, allowing other pigments to become more visible. Weather and species influence the exact color and timing. A change may reveal what was present all along but hidden by a stronger signal. Curiosity loosens assumptions. A better question can reveal options that certainty would have hidden. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A change may reveal what was present all along but hidden by a stronger signal. Curiosity loosens assumptions. A better question can reveal options that certainty would have hidden.",
    action: "Take one assumption you have been treating as fixed and turn it into three open questions. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Curiosity", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-008",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "seasonal",
    priority: 140,
    category: "007",
    categoryLabel: "Strategy",
    categoryImage: "/spark-card-images/strategy.png",
    title: "The Combine After Dark",
    story: "During harvest, Iowa farmers may work long after sunset because weather windows are limited. The strategy involves timing, maintenance, coordination, and knowing when conditions are right. Urgency is most effective when it is connected to a real window rather than constant pressure. Strategy is the discipline of choosing what matters most, learning from evidence, and placing limited effort where it can create the greatest useful change. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Urgency is most effective when it is connected to a real window rather than constant pressure. Strategy is the discipline of choosing what matters most, learning from evidence, and placing limited effort where it can create the greatest useful change.",
    action: "Identify the decision underneath your current activity. Choose the smallest next move that would create useful information. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Strategy", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-009",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "seasonal",
    priority: 140,
    category: "006",
    categoryLabel: "Words & Origins",
    categoryImage: "/spark-card-images/word.png",
    title: "Why We Call It the Harvest Moon",
    story: "The Harvest Moon is the full moon closest to the autumnal equinox. Its timing and evening rise once provided extra light during the busy harvest season. A name can preserve the relationship between the sky, work, and human memory. Words shape what we notice and remember. Naming an experience can make it easier to understand, share, and use. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "A name can preserve the relationship between the sky, work, and human memory. Words shape what we notice and remember. Naming an experience can make it easier to understand, share, and use.",
    action: "Save one word or phrase that stayed with you. Add a note about why it matters and where you might use it. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Words & Origins", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-010",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "exact-date",
    month: 11,
    day: 11,
    priority: 300,
    category: "002",
    categoryLabel: "People & Stories",
    categoryImage: "/spark-card-images/people.png",
    title: "A Veteran’s Story Kept Alive",
    story: "Veterans Day creates a specific moment to listen to the experiences of people who served. The most meaningful remembrance often comes through individual stories rather than general language. Respect becomes more personal when we make room for a real person’s memory. A person’s story becomes useful when it helps us recognize choices, courage, persistence, and possibility in our own life. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Respect becomes more personal when we make room for a real person’s memory. A person’s story becomes useful when it helps us recognize choices, courage, persistence, and possibility in our own life.",
    action: "Choose one quality from this story that you want to practice today. Name one small way it could appear in your own work or relationships. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["People & Stories", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-011",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "calculated-date",
    dateRule: "thanksgiving-us",
    priority: 300,
    category: "008",
    categoryLabel: "Reflection",
    categoryImage: "/spark-card-images/reflections.png",
    title: "The Pause Before Thanksgiving",
    story: "Thanksgiving can carry gratitude, family history, complexity, grief, abundance, and expectation at the same time. A thoughtful pause allows the day to become more than preparation and performance. Gratitude becomes deeper when it can coexist with honesty. Reflection turns experience into guidance. The goal is not to stay in the past, but to carry forward what the past can teach. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Gratitude becomes deeper when it can coexist with honesty. Reflection turns experience into guidance. The goal is not to stay in the past, but to carry forward what the past can teach.",
    action: "Write one sentence about what this story brings up for you, one lesson worth keeping, and one thing you may do differently. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Reflection", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
  {
    id: "SPARK-IOWA-FALL-012",
    volume: 2,
    collection: "iowa-seasons",
    season: "autumn",
    region: "Iowa",
    months: [9, 10, 11],
    displayRule: "exact-date",
    month: 10,
    day: 31,
    priority: 300,
    category: "012",
    categoryLabel: "Wonder",
    categoryImage: "/spark-card-images/worlds.png",
    title: "The Night of Costumes and Porch Lights",
    story: "On October 31, neighborhoods change for a few hours as costumes, stories, porch lights, and shared traditions turn familiar streets into playful spaces. Wonder can be created collectively when people agree to see the ordinary differently for a night. Wonder interrupts routine and restores perspective. It reminds us that the world still contains more than we have noticed. The lasting value is not merely knowing the fact. It is seeing the pattern beneath it and considering where that same pattern may already be present in ordinary life, creative work, or business.",
    spark: "Wonder can be created collectively when people agree to see the ordinary differently for a night. Wonder interrupts routine and restores perspective. It reminds us that the world still contains more than we have noticed.",
    action: "Spend five quiet minutes noticing something that creates awe, surprise, or delight. Save one sentence about what shifted in your perspective. Save a short note about what you noticed, what surprised you, or what you may want to revisit.",
    sparkType: "story",
    tags: ["Wonder", "iowa-seasons", "volume-2"],
    status: "future-ready",
  },
];
