/**
 * Test catalog seed — structural data only, not lesson content.
 */

import type { MomentumInstituteCatalog } from "@/lib/sparkMomentumInstitute/types";
import {
  SPARK_COMPETENCY_FRAMEWORK_V1,
  perspectivesForTopicSlug,
} from "@/lib/sparkCompetencyFramework/competencyFrameworkV1";

export const TEST_INSTITUTE_CATALOG: MomentumInstituteCatalog = {
  institute: {
    id: "momentum-institute",
    slug: "momentum-institute",
    title: "Momentum Institute",
    subtitle: "Entrepreneur Development Center",
    tagline: "Help every member become a better entrepreneur.",
    pillarIds: ["build_your_business"],
    departmentIds: ["dept-marketing"],
    version: "1.0.0-test",
  },
  competencyFramework: SPARK_COMPETENCY_FRAMEWORK_V1,
  pillars: SPARK_COMPETENCY_FRAMEWORK_V1.pillars,
  perspectives: SPARK_COMPETENCY_FRAMEWORK_V1.perspectives,
  departments: [
    {
      id: "dept-marketing",
      instituteId: "momentum-institute",
      pillarId: "build_your_business",
      slug: "marketing",
      title: "Marketing",
      description: "Reach, message, and grow.",
      drawerIds: ["drawer-dept-marketing-pricing"],
      sortOrder: 3,
      competencyIds: ["comp-pricing"],
    },
  ],
  drawers: [
    {
      id: "drawer-dept-marketing-pricing",
      departmentId: "dept-marketing",
      pillarId: "build_your_business",
      slug: "pricing",
      title: "Pricing",
      description: "How pricing shapes perception and profit.",
      topicIds: ["topic-pricing-basics"],
      sortOrder: 1,
    },
  ],
  topics: [
    {
      id: "topic-pricing-basics",
      drawerId: "drawer-dept-marketing-pricing",
      departmentId: "dept-marketing",
      slug: "pricing",
      title: "Pricing Fundamentals",
      summary: "Foundations of value-based pricing.",
      knowledgeCardIds: ["kc-pricing-foundations", "kc-pricing-psychology"],
      supportedExperienceTypes: [
        "business_mastery_minute",
        "guided_lesson",
        "deep_lesson",
        "reflection",
        "apply_to_my_business",
        "strategy_collection",
      ],
      competencyIds: ["comp-pricing"],
      perspectiveIds: perspectivesForTopicSlug("pricing"),
      sortOrder: 1,
    },
  ],
  knowledgeCards: [
    {
      kind: "knowledge-card",
      id: "kc-pricing-foundations",
      topicId: "topic-pricing-basics",
      drawerId: "drawer-dept-marketing-pricing",
      departmentId: "dept-marketing",
      slug: "pricing-foundations",
      title: "Pricing Foundations",
      summary: "Core concepts before pricing psychology.",
      description: "Structural placeholder — no lesson body in test catalog.",
      metadata: {
        difficulty: "foundational",
        estimatedMinutes: 10,
        businessStages: ["idea", "launch", "growth"],
        adhdRelevance: "medium",
        aiRelevance: "low",
      },
      competencyIds: ["comp-pricing"],
      perspectiveIds: perspectivesForTopicSlug("pricing"),
      experienceDefinitionIds: ["exp-bmm-foundations"],
      suggestedNextKnowledgeCardIds: ["kc-pricing-psychology"],
      tags: ["pricing", "foundations"],
      version: "1.0.0-test",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
    {
      kind: "knowledge-card",
      id: "kc-pricing-psychology",
      topicId: "topic-pricing-basics",
      drawerId: "drawer-dept-marketing-pricing",
      departmentId: "dept-marketing",
      slug: "pricing-psychology",
      title: "Pricing Psychology",
      summary: "How customers perceive value through price.",
      description: "Structural placeholder — no lesson body in test catalog.",
      metadata: {
        difficulty: "intermediate",
        estimatedMinutes: 15,
        businessStages: ["launch", "growth", "scale"],
        adhdRelevance: "medium",
        aiRelevance: "medium",
      },
      competencyIds: [
        "comp-pricing",
        "comp-business-strategy",
        "comp-communication",
        "comp-confidence",
        "comp-sales",
      ],
      perspectiveIds: perspectivesForTopicSlug("pricing"),
      experienceDefinitionIds: [
        "exp-bmm-pricing",
        "exp-guided-pricing",
        "exp-apply-pricing",
      ],
      prerequisiteKnowledgeCardIds: ["kc-pricing-foundations"],
      suggestedNextKnowledgeCardIds: ["kc-value-pricing"],
      tags: ["pricing", "marketing"],
      version: "1.0.0-test",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
    {
      kind: "knowledge-card",
      id: "kc-value-pricing",
      topicId: "topic-pricing-basics",
      drawerId: "drawer-dept-marketing-pricing",
      departmentId: "dept-marketing",
      slug: "value-based-pricing",
      title: "Value-Based Pricing",
      summary: "Advanced pricing aligned to delivered value.",
      metadata: {
        difficulty: "advanced",
        estimatedMinutes: 30,
        businessStages: ["growth", "scale"],
        adhdRelevance: "low",
        aiRelevance: "high",
      },
      competencyIds: ["comp-pricing", "comp-business-strategy"],
      perspectiveIds: perspectivesForTopicSlug("pricing"),
      experienceDefinitionIds: [],
      prerequisiteKnowledgeCardIds: ["kc-pricing-psychology"],
      tags: ["pricing", "advanced"],
      version: "1.0.0-test",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
  ],
  experiences: [
    {
      id: "exp-bmm-foundations",
      kind: "business_mastery_minute",
      knowledgeCardId: "kc-pricing-foundations",
      topicId: "topic-pricing-basics",
      drawerId: "drawer-dept-marketing-pricing",
      departmentId: "dept-marketing",
      title: "Pricing Foundations — Minute",
      summary: "Quick orientation to pricing concepts.",
      estimatedMinutes: 5,
      competencyIds: ["comp-pricing"],
      lifecycleStages: [],
      version: "1.0.0-test",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "exp-bmm-pricing",
      kind: "business_mastery_minute",
      knowledgeCardId: "kc-pricing-psychology",
      topicId: "topic-pricing-basics",
      drawerId: "drawer-dept-marketing-pricing",
      departmentId: "dept-marketing",
      title: "Pricing Psychology — Minute",
      summary: "A quick grounding in pricing psychology.",
      estimatedMinutes: 5,
      competencyIds: ["comp-pricing"],
      lifecycleStages: [],
      version: "1.0.0-test",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "exp-guided-pricing",
      kind: "guided_lesson",
      knowledgeCardId: "kc-pricing-psychology",
      topicId: "topic-pricing-basics",
      drawerId: "drawer-dept-marketing-pricing",
      departmentId: "dept-marketing",
      title: "Pricing — Guided Lesson",
      summary: "Guided lesson with reflection.",
      estimatedMinutes: 15,
      competencyIds: ["comp-pricing"],
      lifecycleStages: [],
      version: "1.0.0-test",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "exp-apply-pricing",
      kind: "apply_to_my_business",
      knowledgeCardId: "kc-pricing-psychology",
      topicId: "topic-pricing-basics",
      drawerId: "drawer-dept-marketing-pricing",
      departmentId: "dept-marketing",
      title: "Apply Pricing To My Business",
      summary: "Adapt pricing principles to your offers.",
      estimatedMinutes: 30,
      competencyIds: ["comp-pricing"],
      lifecycleStages: [],
      version: "1.0.0-test",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
  ],
  competencies: [
    {
      id: "comp-business-strategy",
      slug: "business-strategy",
      title: "Business Strategy",
      description: "Direction and positioning for growth.",
      pillarId: "build_your_business",
    },
    {
      id: "comp-communication",
      slug: "communication",
      title: "Communication",
      description: "Clear messaging and listening.",
      pillarId: "build_yourself",
    },
    {
      id: "comp-confidence",
      slug: "confidence",
      title: "Confidence",
      description: "Courage to decide and act.",
      pillarId: "build_yourself",
    },
    {
      id: "comp-sales",
      slug: "sales",
      title: "Sales",
      description: "Ethical persuasion and conversion.",
      pillarId: "build_your_business",
    },
    {
      id: "comp-pricing",
      slug: "pricing",
      title: "Pricing",
      description: "Set and communicate prices with confidence.",
      pillarId: "build_your_business",
      departmentId: "dept-marketing",
    },
    {
      id: "comp-leadership",
      slug: "leadership",
      title: "Leadership",
      description: "Guide people and culture.",
      pillarId: "build_your_legacy",
    },
    {
      id: "comp-delegation",
      slug: "delegation",
      title: "Delegation",
      description: "Assign work with clarity and trust.",
      pillarId: "build_your_legacy",
      parentCompetencyId: "comp-leadership",
    },
    {
      id: "comp-decision-making",
      slug: "decision-making",
      title: "Decision Making",
      description: "Choose well under uncertainty.",
      pillarId: "build_your_thinking",
      parentCompetencyId: "comp-leadership",
    },
    {
      id: "comp-executive-function",
      slug: "executive-function",
      title: "Executive Function",
      description: "Plan, prioritize, and follow through.",
      pillarId: "build_yourself",
    },
    {
      id: "comp-planning",
      slug: "planning",
      title: "Planning",
      description: "Turn intent into workable plans.",
      pillarId: "build_yourself",
      parentCompetencyId: "comp-executive-function",
    },
    {
      id: "comp-prioritization",
      slug: "prioritization",
      title: "Prioritization",
      description: "Choose what matters most now.",
      pillarId: "build_yourself",
      parentCompetencyId: "comp-executive-function",
    },
    {
      id: "comp-focus",
      slug: "focus",
      title: "Focus",
      description: "Sustain attention on meaningful work.",
      pillarId: "build_yourself",
      parentCompetencyId: "comp-executive-function",
    },
  ],
  relationships: [
    {
      id: "rel-pricing-path-1",
      fromKnowledgeCardId: "kc-pricing-foundations",
      toKnowledgeCardId: "kc-pricing-psychology",
      kind: "recommended_next",
      strength: 0.9,
      reasonKey: "institute.relationship.pricing_progression",
    },
    {
      id: "rel-pricing-prereq",
      fromKnowledgeCardId: "kc-pricing-foundations",
      toKnowledgeCardId: "kc-pricing-psychology",
      kind: "prerequisite",
      strength: 1,
    },
    {
      id: "rel-pricing-advanced",
      fromKnowledgeCardId: "kc-pricing-psychology",
      toKnowledgeCardId: "kc-value-pricing",
      kind: "advanced",
      strength: 0.85,
    },
  ],
  learningPaths: [
    {
      id: "path-pricing-mastery",
      slug: "pricing-mastery",
      title: "Pricing Mastery Path",
      description: "Foundations through value-based pricing.",
      pillarId: "build_your_business",
      departmentId: "dept-marketing",
      drawerId: "drawer-dept-marketing-pricing",
      competencyIds: ["comp-pricing"],
      knowledgeCardIds: [
        "kc-pricing-foundations",
        "kc-pricing-psychology",
        "kc-value-pricing",
      ],
      sortOrder: 1,
    },
  ],
  makeItMineTemplates: [
    {
      knowledgeCardId: "kc-pricing-psychology",
      experienceDefinitionId: "exp-apply-pricing",
      intent: "improve_my_pricing",
      coachingPromptKey: "institute.make_it_mine.improve_my_pricing",
      outcomeLabel: "Improve MY pricing",
    },
  ],
  returnClosings: [],
  evidenceOpportunityTemplates: [],
};
