/**
 * Memory Triggers library — reusable Companion intelligence layer.
 * Story-first lines only; never room announcements.
 */

import type { MemoryTriggerEntry } from "./types";

function t(
  partial: Omit<MemoryTriggerEntry, "cooldownDays"> & { cooldownDays?: number },
): MemoryTriggerEntry {
  return { cooldownDays: 21, ...partial };
}

export const MEMORY_TRIGGER_CATALOG: MemoryTriggerEntry[] = [
  // ── Kitchen nook — coffee & morning ─────────────────────────────────────
  t({
    id: "mt-kitchen-coffee-pour",
    name: "Another cup of coffee",
    sense: "smell",
    seasons: "all",
    times: ["morning", "afternoon"],
    emotionalPurpose: "Warm routine; Saturday-morning familiarity",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 14,
    authenticityNotes: "Shari's real morning rhythm — not barista performance",
    storyLine: "I just poured another cup of coffee.",
    memoryAwakened: "Kitchen mornings, someone already up before you",
  }),
  t({
    id: "mt-kitchen-coffee-mug-warmth",
    name: "Warm coffee mug",
    sense: "touch",
    seasons: ["autumn", "winter"],
    times: ["morning"],
    emotionalPurpose: "Hands-around-mug comfort on chilly mornings",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 28,
    authenticityNotes: "Implied through action, not texture lecture",
    storyLine: "I'm holding my mug with both hands — one of those mornings where the warmth matters.",
    memoryAwakened: "Cold mornings and a favorite mug",
  }),
  t({
    id: "mt-kitchen-herbs-window",
    name: "Fresh herbs by the window",
    sense: "smell",
    seasons: ["spring", "summer"],
    times: "all",
    emotionalPurpose: "Simple living; kitchen-window life",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 30,
    authenticityNotes: "Small pot by window — not a chef's garden",
    storyLine: "I snipped a little basil from the pot by the kitchen window.",
    memoryAwakened: "Herbs on a windowsill, summer cooking smell without performance",
  }),
  t({
    id: "mt-kitchen-cinnamon-rolls-saturday",
    name: "Saturday cinnamon rolls",
    sense: "smell",
    seasons: "all",
    times: ["morning"],
    emotionalPurpose: "Grandmother, holiday, home — signature memory cue",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "established",
    cooldownDays: 45,
    authenticityNotes: "Quick stop bakery run — not from-scratch baking theater",
    storyLine:
      "A friend dropped off warm cinnamon rolls this morning. The house still smells wonderful.",
    memoryAwakened: "Saturday bakery, grandmother, holiday morning",
  }),
  t({
    id: "mt-kitchen-banana-bread-dropoff",
    name: "Banana bread someone brought",
    sense: "smell",
    seasons: "all",
    times: "all",
    emotionalPurpose: "Neighbor kindness; imperfect homemaking",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "established",
    cooldownDays: 40,
    authenticityNotes: "Someone else baked — warm not perfect",
    storyLine: "Someone left banana bread on the counter yesterday. I saved you the thought of it.",
    memoryAwakened: "Care packages, church potluck, neighbor stopping by",
  }),
  t({
    id: "mt-kitchen-kettle-whistle",
    name: "Kettle beginning to whistle",
    sense: "sound",
    seasons: ["autumn", "winter"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "Soft domestic sound; tea ritual",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 25,
    authenticityNotes: "Gentle — never loud or startling",
    storyLine: "The kettle's just starting to whistle — I might make tea.",
    memoryAwakened: "Afternoon tea, someone puttering in the kitchen",
  }),
  t({
    id: "mt-kitchen-iced-tea-summer",
    name: "Cool glass of iced tea",
    sense: "touch",
    seasons: ["summer"],
    times: ["afternoon"],
    emotionalPurpose: "Summer porch calm; condensation on glass",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 35,
    authenticityNotes: "Simple summer drink — not craft cocktail",
    storyLine: "I poured iced tea and left the glass cool on the counter for a minute.",
    memoryAwakened: "Hot afternoons, porch sitting, summer laziness",
  }),

  // ── Living room — crime night, cozy ───────────────────────────────────
  t({
    id: "mt-living-popcorn-mystery",
    name: "Popcorn and a mystery",
    sense: "smell",
    seasons: ["autumn", "winter"],
    times: ["evening"],
    emotionalPurpose: "Crime-show nights; cozy imperfect evenings",
    relatedRoom: "living-room",
    relationshipSuitability: "established",
    cooldownDays: 30,
    authenticityNotes: "Real evening habit — bowl on lap, not movie theater",
    storyLine: "I ended the day with a bowl of popcorn and a good mystery last night.",
    memoryAwakened: "TV nights, shared couch, whodunit comfort",
  }),
  t({
    id: "mt-living-throw-blanket",
    name: "Soft throw on the chair",
    sense: "touch",
    seasons: ["autumn", "winter"],
    times: ["evening"],
    emotionalPurpose: "Cocoon without asking guest to nest",
    relatedRoom: "living-room",
    relationshipSuitability: "any",
    cooldownDays: 28,
    authenticityNotes: "Lived-in throw — not catalog staging",
    storyLine: "I pulled the throw over the arm of the chair — it looked lonely without it.",
    memoryAwakened: "Cozy evenings, favorite blanket, safe sitting",
  }),
  t({
    id: "mt-living-candle-evening",
    name: "Vanilla candle lit",
    sense: "sight",
    seasons: ["autumn", "winter"],
    times: ["evening"],
    emotionalPurpose: "Soft light; evening settling",
    relatedRoom: "living-room",
    relationshipSuitability: "any",
    cooldownDays: 32,
    authenticityNotes: "One candle — not centerpiece display",
    storyLine: "I lit the vanilla candle while the light outside was still fading.",
    memoryAwakened: "Evening wind-down, soft glow, winter indoors",
  }),
  t({
    id: "mt-living-clock-tick",
    name: "Soft tick of a clock",
    sense: "sound",
    seasons: "all",
    times: ["evening", "night"],
    emotionalPurpose: "Time passing gently; ADHD-safe quiet anchor",
    relatedRoom: "living-room",
    relationshipSuitability: "any",
    cooldownDays: 40,
    authenticityNotes: "Barely audible — believable not ASMR",
    storyLine: "It's quiet enough to hear the clock in the other room.",
    memoryAwakened: "Grandparent's house, Sunday afternoon stillness",
  }),
  t({
    id: "mt-living-hot-chocolate-winter",
    name: "Hot chocolate evening",
    sense: "taste",
    seasons: ["winter"],
    times: ["evening"],
    emotionalPurpose: "Winter warmth; childlike comfort without childish tone",
    relatedRoom: "living-room",
    relationshipSuitability: "any",
    cooldownDays: 35,
    authenticityNotes: "Packet or simple mix — honest not artisan",
    storyLine: "I made hot chocolate earlier — the mug's still on the side table.",
    memoryAwakened: "Snow outside, warm drink, safe inside",
  }),

  // ── Sunroom — birds, light, garden view ─────────────────────────────────
  t({
    id: "mt-sunroom-birds-returning",
    name: "Birds returning in spring",
    sense: "sound",
    seasons: ["spring"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "Renewal; Iowa yard coming alive",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 25,
    authenticityNotes: "Watching birds is real Shari — feeder visible",
    storyLine: "The cardinals are loud this morning — spring showed up overnight.",
    memoryAwakened: "First warm day, open window, birds at feeder",
  }),
  t({
    id: "mt-sunroom-hummingbird-summer",
    name: "Hummingbird at feeder",
    sense: "sight",
    seasons: ["summer"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "Brief delight; pause without demanding attention",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 30,
    authenticityNotes: "Momentary — not nature documentary",
    storyLine: "A hummingbird just visited the feeder — I didn't want to scare it away.",
    memoryAwakened: "Summer porch, stillness rewarded with a flash of color",
  }),
  t({
    id: "mt-sunroom-sun-warmed-chair",
    name: "Sunlight warming the chair",
    sense: "touch",
    seasons: ["spring", "summer", "autumn"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "Invitation to sit; warmth as hospitality",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 28,
    authenticityNotes: "Chair in sunbeam — environmental not directive",
    storyLine: "The sun finally reached my reading chair — I'm letting it warm the cushion.",
    memoryAwakened: "Cat in sunbeam, lazy afternoon, permission to rest",
  }),
  t({
    id: "mt-sunroom-lilacs-spring",
    name: "Lilacs blooming",
    sense: "smell",
    seasons: ["spring"],
    times: "all",
    emotionalPurpose: "Iowa spring; memory-heavy scent evoked through life",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 45,
    authenticityNotes: "Open window — not 'the room smells like lilacs'",
    storyLine: "I opened the window — lilacs are out and the whole neighborhood knows it.",
    memoryAwakened: "Walking past a hedge, prom corsage, childhood yard",
  }),
  t({
    id: "mt-sunroom-rain-gentle",
    name: "Gentle rain on glass",
    sense: "sound",
    seasons: ["spring", "summer"],
    times: "all",
    emotionalPurpose: "Calm; permission to move slower",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 22,
    authenticityNotes: "Soft rain — never storm drama unless distant thunder variant",
    storyLine: "Rain's been tapping the sunroom glass — the quiet kind.",
    memoryAwakened: "Reading during rain, safe inside, nap weather",
  }),
  t({
    id: "mt-sunroom-fresh-flowers-vase",
    name: "Fresh flowers on the table",
    sense: "sight",
    seasons: ["spring", "summer"],
    times: "all",
    emotionalPurpose: "Simple beauty; grocery or garden — not florist",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 26,
    authenticityNotes: "Sometimes grocery bouquet — honest",
    storyLine: "I put fresh flowers in the vase — nothing fancy, just cheerful.",
    memoryAwakened: "Someone thought of the table, kitchen bouquet, farmers market",
  }),

  // ── Porch — Iowa air, chimes ───────────────────────────────────────────
  t({
    id: "mt-porch-iowa-air-open",
    name: "Fresh Iowa air through the window",
    sense: "smell",
    seasons: ["spring", "summer", "autumn"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "Place memory — Midwest openness",
    relatedRoom: "front-porch",
    relationshipSuitability: "any",
    cooldownDays: 30,
    authenticityNotes: "Open window habit — not travel brochure",
    storyLine: "I left the window open — fresh Iowa air after the rain is rolling through.",
    memoryAwakened: "Farm air, open land, childhood outside",
  }),
  t({
    id: "mt-porch-wind-chime",
    name: "Porch wind chime",
    sense: "sound",
    seasons: ["spring", "summer", "autumn"],
    times: ["afternoon", "evening"],
    emotionalPurpose: "Peripheral calm; porch sitting",
    relatedRoom: "front-porch",
    relationshipSuitability: "any",
    cooldownDays: 35,
    authenticityNotes: "Distant soft chime — never constant",
    storyLine: "The wind chime on the porch moved just enough to remind me it's there.",
    memoryAwakened: "Grandma's porch, lemonade, barefoot summer",
  }),
  t({
    id: "mt-porch-lemonade-summer",
    name: "Lemonade on the deck",
    sense: "taste",
    seasons: ["summer"],
    times: ["afternoon"],
    emotionalPurpose: "Summer simplicity; porch life",
    relatedRoom: "front-porch",
    relationshipSuitability: "any",
    cooldownDays: 32,
    authenticityNotes: "Pitcher in fridge — not artisan stand",
    storyLine: "I made lemonade earlier — perfect excuse to sit on the deck later.",
    memoryAwakened: "Hot summer, porch swing, childhood stand",
  }),
  t({
    id: "mt-porch-deck-sun-warm",
    name: "Sun-warmed deck boards",
    sense: "touch",
    seasons: ["summer"],
    times: ["afternoon"],
    emotionalPurpose: "Summer body memory; barefoot optional",
    relatedRoom: "front-porch",
    relationshipSuitability: "established",
    cooldownDays: 40,
    authenticityNotes: "Implied through stepping outside",
    storyLine: "The deck boards are warm underfoot — summer finally committed.",
    memoryAwakened: "Barefoot on wood, BBQ nearby, late afternoon",
  }),

  // ── Craft corner — yarn, journal ───────────────────────────────────────
  t({
    id: "mt-craft-soft-yarn",
    name: "Soft yarn in the basket",
    sense: "touch",
    seasons: ["autumn", "winter"],
    times: "all",
    emotionalPurpose: "Crafting calm; hands busy, mind quiet",
    relatedRoom: "creative-studio",
    relationshipSuitability: "any",
    cooldownDays: 28,
    authenticityNotes: "Real crochet habit — basket not pristine",
    storyLine: "I left the yarn basket open — I was mid-row on something and got distracted.",
    memoryAwakened: "Grandmother knitting, TV on, repetitive comfort",
  }),
  t({
    id: "mt-craft-leather-journal",
    name: "Smooth leather journal",
    sense: "touch",
    seasons: "all",
    times: ["morning", "evening"],
    emotionalPurpose: "Reflection without demanding journaling",
    relatedRoom: "creative-studio",
    relationshipSuitability: "established",
    cooldownDays: 35,
    authenticityNotes: "Well-used journal — not blank prop",
    storyLine: "My journal's on the desk — I wrote half a page and stopped where it felt right.",
    memoryAwakened: "Pen on paper, private thoughts, morning pages",
  }),

  // ── Aquarium nook — bubbles, quiet watch ─────────────────────────────────
  t({
    id: "mt-aquarium-bubbles",
    name: "Aquarium bubbles",
    sense: "sound",
    seasons: "all",
    times: ["evening", "night"],
    emotionalPurpose: "ADHD-safe focus anchor; living room aquarium",
    relatedRoom: "reading-nook",
    relationshipSuitability: "any",
    cooldownDays: 24,
    authenticityNotes: "Soft bubble filter — never loud pump",
    storyLine: "The aquarium's bubbling is the only sound in here right now.",
    memoryAwakened: "Fish tank glow, childhood pet store, meditative watching",
  }),
  t({
    id: "mt-aquarium-glow-evening",
    name: "Aquarium glow in dim room",
    sense: "sight",
    seasons: "all",
    times: ["evening", "night"],
    emotionalPurpose: "Living light; quiet companion",
    relatedRoom: "reading-nook",
    relationshipSuitability: "any",
    cooldownDays: 30,
    authenticityNotes: "Environmental — fish not narrated",
    storyLine: "I dimmed the lights — the aquarium's doing the rest.",
    memoryAwakened: "Night light from tank, calm before sleep",
  }),

  // ── Seasonal — Spring ───────────────────────────────────────────────────
  t({
    id: "mt-season-spring-tulips",
    name: "Tulips in the yard",
    sense: "sight",
    seasons: ["spring"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "First color after winter",
    relatedRoom: "any",
    relationshipSuitability: "any",
    cooldownDays: 40,
    authenticityNotes: "Yard tulips — not botanical garden",
    storyLine: "The tulips finally opened — I checked them twice before breakfast.",
    memoryAwakened: "Easter, school garden, winter finally over",
  }),
  t({
    id: "mt-season-spring-cut-grass",
    name: "Fresh-cut grass",
    sense: "smell",
    seasons: ["spring", "summer"],
    times: ["afternoon"],
    emotionalPurpose: "Suburban Saturday; mower somewhere nearby",
    relatedRoom: "any",
    relationshipSuitability: "any",
    cooldownDays: 28,
    authenticityNotes: "Neighbor mowing — not Shari claiming perfect lawn",
    storyLine: "Someone's mowing down the block — fresh-cut grass everywhere.",
    memoryAwakened: "Saturday chores, playing outside, summer approaching",
  }),
  t({
    id: "mt-season-spring-rain-after-storm",
    name: "Rain after a summer storm",
    sense: "smell",
    seasons: ["spring", "summer"],
    times: "all",
    emotionalPurpose: "Petrichor calm; reset feeling",
    relatedRoom: "front-porch",
    relationshipSuitability: "any",
    cooldownDays: 25,
    authenticityNotes: "After storm passed — not during scary weather",
    storyLine: "The storm moved on — everything outside feels clean and wet.",
    memoryAwakened: "Running outside after rain, earth smell, cooled air",
  }),

  // ── Seasonal — Summer ───────────────────────────────────────────────────
  t({
    id: "mt-season-summer-tomatoes",
    name: "Garden tomatoes",
    sense: "taste",
    seasons: ["summer"],
    times: ["afternoon"],
    emotionalPurpose: "Simple garden pride — not farm stand empire",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "established",
    cooldownDays: 35,
    authenticityNotes: "A few plants — salt on the counter optional",
    storyLine: "I picked a tomato that was actually ready — rare victory.",
    memoryAwakened: "Garden dirt, caprese, August heat",
  }),
  t({
    id: "mt-season-summer-butterfly",
    name: "Butterfly in the garden",
    sense: "sight",
    seasons: ["summer"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "Brief wonder; no urgency",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 38,
    authenticityNotes: "Glance out window — not nature channel",
    storyLine: "A butterfly landed on the coneflowers — I watched until it left.",
    memoryAwakened: "Lazy summer watching, garden patience",
  }),
  t({
    id: "mt-season-summer-strawberries",
    name: "Fresh strawberries",
    sense: "taste",
    seasons: ["summer"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "Seasonal treat; farmers market or neighbor",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 30,
    authenticityNotes: "Bowl on counter — not dessert course",
    storyLine: "Strawberries were too good at the market — they're rinsed and waiting.",
    memoryAwakened: "Berry picking, stained fingers, June",
  }),

  // ── Seasonal — Autumn ───────────────────────────────────────────────────
  t({
    id: "mt-season-autumn-apple-pie-shared",
    name: "Apple pie someone shared",
    sense: "smell",
    seasons: ["autumn"],
    times: "all",
    emotionalPurpose: "Shared food; community not performance baking",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "established",
    cooldownDays: 42,
    authenticityNotes: "Someone brought pie — Shari didn't stage bake-off",
    storyLine: "A neighbor brought apple pie yesterday — I reheated a slice for myself earlier.",
    memoryAwakened: "Fall potluck, church basement, aunt's kitchen",
  }),
  t({
    id: "mt-season-autumn-cider",
    name: "Apple cider warming",
    sense: "taste",
    seasons: ["autumn"],
    times: ["afternoon", "evening"],
    emotionalPurpose: "Fall cozy without pumpkin-spam",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 30,
    authenticityNotes: "Mug on counter — orchard optional",
    storyLine: "I warmed up apple cider — fall finally feels official.",
    memoryAwakened: "Hayride, orchard visit, flannel weather",
  }),
  t({
    id: "mt-season-autumn-leaves-falling",
    name: "Leaves moving outside",
    sense: "sound",
    seasons: ["autumn"],
    times: "all",
    emotionalPurpose: "Seasonal transition; gentle melancholy ok",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 28,
    authenticityNotes: "Wind in trees — not leaf-blower assault",
    storyLine: "Leaves are skittering past the window — I can hear fall arriving.",
    memoryAwakened: "Jumping in piles, school bus, jacket weather",
  }),
  t({
    id: "mt-season-autumn-sweater-morning",
    name: "Favorite sweatshirt morning",
    sense: "touch",
    seasons: ["autumn"],
    times: ["morning"],
    emotionalPurpose: "Chilly morning cocoon",
    relatedRoom: "living-room",
    relationshipSuitability: "any",
    cooldownDays: 32,
    authenticityNotes: "Sweatshirt not fashion — worn and real",
    storyLine: "It's one of those mornings for my favorite sweatshirt — the soft one.",
    memoryAwakened: "First cool day, college hoodie, comfort clothes",
  }),
  t({
    id: "mt-season-autumn-bonfire-distant",
    name: "Bonfire smoke drifting",
    sense: "smell",
    seasons: ["autumn"],
    times: ["evening"],
    emotionalPurpose: "Neighborhood life; fall evenings",
    relatedRoom: "front-porch",
    relationshipSuitability: "any",
    cooldownDays: 40,
    authenticityNotes: "Someone else's fire — distant not immersive",
    storyLine: "Someone's having a bonfire a few blocks over — smoke drifts through when the wind shifts.",
    memoryAwakened: "Friday night fire pit, s'mores, teenagers laughing",
  }),
  t({
    id: "mt-season-autumn-pumpkin-porch",
    name: "Pumpkin on the step",
    sense: "sight",
    seasons: ["autumn"],
    times: "all",
    emotionalPurpose: "Season marker without décor catalog",
    relatedRoom: "front-porch",
    relationshipSuitability: "any",
    cooldownDays: 45,
    authenticityNotes: "One pumpkin — not Instagram porch",
    storyLine: "I set a pumpkin on the step — nothing else, just that.",
    memoryAwakened: "Trick-or-treat, carving mess, October",
  }),

  // ── Seasonal — Winter ───────────────────────────────────────────────────
  t({
    id: "mt-season-winter-evergreen",
    name: "Evergreen on the porch",
    sense: "smell",
    seasons: ["winter"],
    times: "all",
    emotionalPurpose: "Holiday proximity without demanding cheer",
    relatedRoom: "front-porch",
    relationshipSuitability: "any",
    cooldownDays: 45,
    authenticityNotes: "Wreath or garland — simple",
    storyLine: "I hung evergreen on the porch — December follows you in the door now.",
    memoryAwakened: "Tree lot, cold fingers, tradition without pressure",
  }),
  t({
    id: "mt-season-winter-peppermint-tea",
    name: "Peppermint tea",
    sense: "taste",
    seasons: ["winter"],
    times: ["evening"],
    emotionalPurpose: "Winter evening ritual",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 28,
    authenticityNotes: "Tea bag honesty",
    storyLine: "Peppermint tea sounded right for tonight — I'm on my second mug.",
    memoryAwakened: "Holiday evenings, candy cane memory, warm hands",
  }),
  t({
    id: "mt-season-winter-snow-outside",
    name: "Snow outside",
    sense: "sight",
    seasons: ["winter"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "Quiet world; permission to stay in",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 30,
    authenticityNotes: "Looking out — not snowstorm drama",
    storyLine: "Snow's been falling slow since dawn — the yard looks edited down to essentials.",
    memoryAwakened: "Snow day, canceled plans, cocoa inside",
  }),
  t({
    id: "mt-season-winter-soup",
    name: "Warm soup on the stove",
    sense: "smell",
    seasons: ["winter"],
    times: ["afternoon", "evening"],
    emotionalPurpose: "Nourishment; simple not chef",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 26,
    authenticityNotes: "Soup from pot or can upgraded — warm not gourmet",
    storyLine: "Soup's on the stove — the kind of day that asked for it.",
    memoryAwakened: "Sick day care, mother's kitchen, thawing out",
  }),
  t({
    id: "mt-season-winter-blanket-deep",
    name: "Deep quiet under blankets",
    sense: "touch",
    seasons: ["winter"],
    times: ["evening", "night"],
    emotionalPurpose: "Maximum ADHD comfort; one cue only",
    relatedRoom: "living-room",
    relationshipSuitability: "any",
    cooldownDays: 35,
    authenticityNotes: "Already under blanket — not instructing guest",
    storyLine: "I'm under the big blanket — the house is quiet and I'm not rushing it.",
    memoryAwakened: "Safe burrow, storm outside, nowhere to be",
  }),

  // ── Kinsey & household life ─────────────────────────────────────────────
  t({
    id: "mt-house-kinsey-footsteps",
    name: "Kinsey's footsteps",
    sense: "sound",
    seasons: "all",
    times: "all",
    emotionalPurpose: "Living home; companion animal presence",
    relatedRoom: "living-room",
    relationshipSuitability: "established",
    cooldownDays: 20,
    authenticityNotes: "Soft padding — never startle",
    storyLine: "Kinsey just padded through — she's checking on things, as usual.",
    memoryAwakened: "Dog in the house, someone else home, domestic safety",
  }),
  t({
    id: "mt-house-cookies-with-coffee",
    name: "Cookies with coffee",
    sense: "taste",
    seasons: ["autumn", "winter"],
    times: ["afternoon"],
    emotionalPurpose: "Afternoon pause; store-bought ok",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "established",
    cooldownDays: 30,
    authenticityNotes: "Plate on counter — not fresh-baked every day fiction",
    storyLine: "I put a couple cookies next to my coffee — afternoon felt like it needed that.",
    memoryAwakened: "Office break room, grandma's tin, small kindness",
  }),
  t({
    id: "mt-house-steam-rising-mug",
    name: "Steam rising from mug",
    sense: "sight",
    seasons: ["autumn", "winter"],
    times: ["morning"],
    emotionalPurpose: "Visual warmth cue",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 22,
    authenticityNotes: "Coffee or tea — single visual",
    storyLine: "Steam's rising off my mug — I paused to watch it for a second.",
    memoryAwakened: "Cold morning ritual, pause before the day",
  }),
  t({
    id: "mt-house-distant-thunder",
    name: "Distant thunderstorm",
    sense: "sound",
    seasons: ["spring", "summer"],
    times: ["evening", "night"],
    emotionalPurpose: "Atmospheric not threatening",
    relatedRoom: "living-room",
    relationshipSuitability: "any",
    cooldownDays: 45,
    authenticityNotes: "Far away — guest safe inside",
    storyLine: "There's thunder somewhere west of here — far enough to feel cozy inside.",
    memoryAwakened: "Storm on the horizon, counting seconds, porch watching",
  }),
  t({
    id: "mt-house-open-window-breeze",
    name: "Cool breeze through open window",
    sense: "touch",
    seasons: ["spring", "autumn"],
    times: ["morning", "afternoon"],
    emotionalPurpose: "Fresh air invitation",
    relatedRoom: "window-seat",
    relationshipSuitability: "any",
    cooldownDays: 27,
    authenticityNotes: "Breeze moves curtain — not weather report",
    storyLine: "I opened the window and a cool breeze came through — perfect.",
    memoryAwakened: "Changing seasons, curtain lift, deep breath",
  }),
  t({
    id: "mt-house-fresh-popcorn-evening",
    name: "Fresh popcorn evening",
    sense: "smell",
    seasons: "all",
    times: ["evening"],
    emotionalPurpose: "Simple treat — not only crime nights",
    relatedRoom: "living-room",
    relationshipSuitability: "any",
    cooldownDays: 28,
    authenticityNotes: "Microwave or air popper — honest",
    storyLine: "I made popcorn earlier — the bowl's still on the coffee table.",
    memoryAwakened: "Movie night, sleepover, easy joy",
  }),
  t({
    id: "mt-house-coffee-cookies-morning",
    name: "Coffee and quiet morning",
    sense: "smell",
    seasons: "all",
    times: ["morning"],
    emotionalPurpose: "Routine anchor; familiar before impressive",
    relatedRoom: "kitchen-table",
    relationshipSuitability: "any",
    cooldownDays: 18,
    authenticityNotes: "Second coffee cue variant — shorter, different cooldown",
    storyLine: "Coffee's brewing again — the morning kind that doesn't need a reason.",
    memoryAwakened: "Someone already awake, kitchen sounds, day beginning",
  }),
];

export const MEMORY_TRIGGER_BY_ID: ReadonlyMap<string, MemoryTriggerEntry> = new Map(
  MEMORY_TRIGGER_CATALOG.map((entry) => [entry.id, entry]),
);

export function getMemoryTriggerById(id: string): MemoryTriggerEntry | undefined {
  return MEMORY_TRIGGER_BY_ID.get(id);
}

export function listMemoryTriggersBySense(sense: MemoryTriggerEntry["sense"]): MemoryTriggerEntry[] {
  return MEMORY_TRIGGER_CATALOG.filter((e) => e.sense === sense);
}

export function listMemoryTriggersBySeason(
  season: import("@/lib/welcomeLivingRoom").WelcomeSeason,
): MemoryTriggerEntry[] {
  const normalized = season === "holiday" ? "winter" : season;
  return MEMORY_TRIGGER_CATALOG.filter(
    (e) => e.seasons === "all" || e.seasons.includes(normalized),
  );
}
