import type { PricingDomainContract } from "./pricingDomainContract";

/**
 * Expert Pricing Strategy Intelligence pack — Phase 4B.
 * Consumed by the shared judgment engine via StrategyTypeContract bridge.
 * Price is one part of value, positioning, fit, delivery, and sustainability.
 */
export const pricingDomainIntelligence: PricingDomainContract = {
  id: "pricing",
  name: "Pricing Strategy",
  description:
    "Decide whether and how to change price while protecting trust, value, fit, and capacity — never assuming raise or lower is the answer.",
  useWhen: [
    "Considering a price change (raise, lower, or maintain)",
    "Membership, subscription, retainer, or recurring pricing",
    "Service, consulting, coaching, or project pricing structure",
    "Packaging, tiers, packages, or productized services",
    "Workshops, events, digital offers, or programs",
    "Pricing a new offer or revising an existing one",
    "Treating new vs existing customers differently",
    "Grandfathering, founding pricing, or transition notices",
    "Reducing discount dependence",
    "Choosing hourly, package, project, outcome, access, or subscription models",
    "Testing pricing before full implementation",
    "Suspecting underpricing, overpricing, or unsustainable delivery",
  ],
  avoidWhen: [
    "Need is only a finished sales page with the pricing decision already made",
    "Need is detailed cost accounting, cash-flow modeling, or break-even (Finance)",
    "Need is only writing a price announcement (Create) after direction is clear",
    "Need is campaign creative without a strategic pricing question (Marketing)",
  ],
  entrySignals: [
    /\b(price|pricing|raise (the )?price|lower (the )?price|fee|rate|membership (fee|price)|discount|premium pricing|tier|bundl|grandfather|annual|monthly|retainer|subscription)\b/i,
    /\b(underpriced|overpriced|charge more|charge less|what (should|do) i charge|founding.?member|hourly|package pricing)\b/i,
    /\b(too much for what i charge|doing too much|competitor(s)? charge|not buying|won't buy)\b/i,
  ],
  possibleUnderlyingQuestions: [
    "Is the offer underpriced relative to the outcome?",
    "Is the business financially unsustainable at the current price?",
    "Has customer value actually increased — or only founder effort?",
    "Has delivery become more demanding without a matching promise change?",
    "Is the audience wrong for the current price?",
    "Is the current package too broad for one price?",
    "Does the business need fewer better-fit customers rather than more volume?",
    "Is pricing being used to solve a positioning problem?",
    "Is a new tier better than changing the base price?",
    "Should only new customers receive the new price?",
    "Is there enough evidence to change anything yet?",
    "Is the offer clear enough for anyone to pay confidently?",
    "Is trust or the sales process the real conversion gap?",
    "Are competitor prices actually comparable offers?",
    "Should scope shrink instead of price rising?",
    "Is discounting training people to wait?",
    "Would packaging or boundaries fix sustainability without a number change?",
    "Is maintaining the current price the wisest move right now?",
  ],
  requiredContext: [
    "current price or fee structure",
    "what changed that made pricing feel urgent",
    "whether the decision is for new customers, existing customers, or both",
    "offer shape (membership, package, hourly, etc.)",
    "delivery burden vs customer outcome",
  ],
  optionalContext: [
    "conversion and inquiry patterns",
    "retention, churn, and renewal signals",
    "discount habits",
    "capacity and margin concerns",
    "customer feedback about worth",
    "competitor observations (as observations, not proof)",
    "contractual or membership commitments",
    "how long the price has been unchanged",
  ],
  importantContext: [
    "current price",
    "how long the price has been unchanged",
    "offer scope and customer outcome",
    "delivery effort vs customer-perceived value",
    "demand, conversion, and retention signals",
    "capacity and profitability concern",
    "customer feedback about worth",
    "existing versus new customers",
    "discount patterns",
    "what changed that made pricing feel urgent now",
  ],
  commonFacts: [
    "The current published price or fee",
    "Whether existing customers are on a different rate",
    "Whether discounts are currently offered",
    "Whether pricing is hourly, package, retainer, subscription, or project",
    "Whether a written promise or membership term exists",
  ],
  commonObservations: [
    "Prospects hesitate at the price mention",
    "Delivery feels heavier than the fee suggests",
    "Competitors publish different price points",
    "Inquiries arrive but rarely convert",
    "Members use the offer lightly or inconsistently",
    "Discount requests appear early in every conversation",
  ],
  commonInterpretations: [
    "Hesitation means the price is too high",
    "Busy delivery means the offer is underpriced",
    "A raise will fix profitability",
    "A lower price will fix conversion",
    "Competitor prices prove the right number",
    "Customer compliments prove willingness to pay",
  ],
  commonAssumptions: [
    "Customers will leave if the price rises",
    "A lower price will create more sales",
    "Competitors determine the correct price",
    "More features justify a higher price",
    "A higher price will solve profitability",
    "Existing customers must receive the same price as new customers",
    "Discounts are necessary to close sales",
    "The audience cannot afford the offer",
    "The price is the reason conversion is weak",
    "Higher-priced offers must include much more founder work",
    "Permanent grandfathering is required to stay fair",
    "Outcome-based pricing is always best",
    "One objection means the market cannot pay",
    "One sale validates demand at a new price",
  ],
  commonUnknowns: [
    "Willingness to pay among the right customers",
    "How existing members would respond to a change",
    "Whether value communication — not price — is the gap",
    "Whether delivery can sustain higher expectations after a raise",
    "Whether a simpler package would outperform a lower number",
  ],
  commonConcerns: [
    "Fear of churn or resentment",
    "Fear of looking greedy or out of reach",
    "Fear of undercharging and burning out",
    "Fear of permanent low-price anchoring",
    "Fear of administrative complexity from tiers or grandfathering",
  ],
  commonOpportunities: [
    "Grandfathering or new-customer-only pricing",
    "A premium tier without moving the base",
    "A limited test before a broad change",
    "Clearer value before any number change",
    "Reduce scope while holding price",
    "Replace habitual discounts with clear boundaries",
    "Founding or pilot pricing with a clear end condition",
    "Annual option for cash timing without changing monthly accessibility",
  ],
  commonConstraints: [
    "Limited capacity to deliver more after a raise",
    "Cash pressure that tempts a rushed change",
    "Contract or membership commitments",
    "Existing promise language that customers trusted",
    "Tools and admin systems that struggle with many tiers",
  ],
  evidencePrompts: [
    "What do you know for certain about costs and willingness to pay?",
    "What have customers already said about value versus price?",
    "What happens when you hold the price without a discount?",
    "What changed that made pricing feel important now?",
    "Which signals are confirmed results, and which are fears or interpretations?",
    "How would you know if price is not the real problem?",
  ],
  heuristics: [
    "Diagnose the problem before changing price.",
    "A price change cannot repair unclear value by itself.",
    "More founder effort does not automatically equal more customer value.",
    "A sustainable offer must support the cost and capacity of delivery.",
    "Price changes for new customers are usually easier to test than broad changes for existing customers.",
    "Tiers are useful only when the differences are meaningful and understandable.",
    "Discounts should have a clear strategic reason, boundary, and end condition.",
    "A lower price can increase complexity and support burden without improving customer fit.",
    "A higher price may increase expectations.",
    "Grandfathering protects trust but may create long-term complexity.",
    "A staged transition may reduce risk but prolong administrative burden.",
    "Pricing should support the desired business model, not merely copy competitors.",
    "The simplest pricing structure that works is often stronger than excessive choice.",
    "If uncertainty is high and reversibility is available, test.",
    "Maintaining the current price is valid when the evidence for change is weak.",
  ],
  warningSigns: [
    "Price conversations feel apologetic",
    "Discounts are the primary close",
    "Costs rose and price has not been reviewed in a long time",
    "Premium language without premium delivery",
    "Too many tiers that confuse the buyer",
    "Founder exhaustion while price stays flat",
    "Competitor prices used as the only decision input",
    "Customer compliments treated as willingness-to-pay proof",
  ],
  valueChecks: [
    "Is customer outcome clearer — or only founder effort higher?",
    "Is perceived value weak while delivered value is strong?",
    "Would packaging, access, support, or trust change value more than the number?",
    "Is the promise specific enough that a higher price would still feel fair?",
  ],
  customerImpactChecks: [
    "How would existing customers experience this change?",
    "Would new customers face a different price than the base?",
    "What trust risk appears if the change feels sudden?",
    "Is discomfort about change the same as strategic harm?",
    "What notice, clarity, and continuity do people deserve?",
  ],
  capacityChecks: [
    "Can you support the promise after a price change?",
    "Would a raise increase demand you cannot deliver well?",
    "Is underpricing masking an unsustainable delivery load?",
    "Would a lower price attract volume you cannot serve well?",
    "Would boundaries, standardization, or retirement help more than a number change?",
  ],
  optionPatterns: [
    "protect_current_base",
    "maintain_current_direction",
    "increase_price",
    "restructure_price",
    "add_value",
    "simplify",
    "reduce_scope",
    "staged_transition",
    "test",
    "delay",
    "stop",
  ],
  strategicOptionPatterns: [
    "Maintain the current price",
    "Raise the price for new customers only",
    "Raise the price for all customers with notice",
    "Grandfather current customers",
    "Grandfather for a limited period",
    "Create a premium tier",
    "Create a simpler lower tier",
    "Restructure the package",
    "Reduce scope while holding price",
    "Add value before increasing price",
    "Replace hourly pricing with packages",
    "Replace packages with recurring access",
    "Add annual pricing",
    "Add monthly pricing",
    "Offer both monthly and annual",
    "Remove or narrow discounts",
    "Use a founding-member pilot",
    "Run a limited price test",
    "Delay the change until a defined condition",
    "Retire an unsustainable offer",
    "Reposition before changing price",
  ],
  tradeoffDimensions: [
    "value alignment",
    "customer outcome",
    "positioning",
    "customer trust",
    "acquisition",
    "conversion",
    "retention",
    "churn",
    "revenue",
    "margin",
    "delivery capacity",
    "support burden",
    "complexity",
    "accessibility",
    "founder energy",
    "predictability",
    "cash timing",
    "customer expectations",
    "transition burden",
    "flexibility",
    "evidence quality",
  ],
  riskPatterns: [
    "Unexpected churn after a poorly framed raise",
    "Customer confusion about what changed",
    "Damaged trust from sudden or unclear changes",
    "Stronger customer expectations without delivery capacity",
    "Offer complexity from too many tiers",
    "Administrative burden from grandfathering or exceptions",
    "Weak differentiation that makes any price feel high",
    "Insufficient demand evidence before a broad change",
    "Permanent low-price anchoring",
    "Excessive grandfathering complexity",
    "Discount dependence that undermines the new price",
    "Poor margin that survives even after a raise",
    "Unsustainable delivery after volume rises",
    "Wrong audience attracted by a lower price",
    "Weak communication of the change",
    "Price change masking a deeper value or fit issue",
  ],
  reversibilityGuidance: [
    "Easily reversible: quoting a higher price to a small number of new prospects",
    "Easily reversible: testing an optional premium tier with a small segment",
    "Easily reversible: limited founding-member pricing with a clear end date",
    "Easily reversible: a temporary package test",
    "Moderately reversible: changing public pricing for new customers",
    "Moderately reversible: adding annual pricing",
    "Moderately reversible: narrowing discounts",
    "Moderately reversible: changing package scope",
    "Difficult to reverse: raising prices broadly for existing members",
    "Difficult to reverse: eliminating a long-standing tier",
    "Difficult to reverse: changing contractual pricing",
    "Difficult to reverse: repositioning the entire offer around a premium market",
    "Difficult to reverse: permanently grandfathering a large customer base",
  ],
  experimentPatterns: [
    "Quote the new price to the next five qualified prospects",
    "Test a new price with new members for 30 days",
    "Add a premium tier without changing the base tier",
    "Interview current customers about perceived value",
    "Test annual pricing with a small group",
    "Remove one discount from a limited campaign",
    "Offer a simplified package at the current price",
    "Compare conversion and delivery burden across two packages",
  ],
  experimentBlueprints: [
    {
      id: "new_customer_price_test",
      name: "New-customer price test",
      assumption: "Qualified new prospects will accept the proposed price without harming fit.",
      action: "Quote the proposed price to the next five qualified prospects.",
      scope: "New prospects only — existing customers unchanged",
      durationOrReview: "After five decisions or 30 days",
      evidence: [
        "response quality",
        "objections",
        "conversion",
        "delivery expectations named at sale",
      ],
      successSignal:
        "Enough qualified prospects accept, and expectations stay deliverable.",
      stopSignal:
        "Repeated mismatch between promise and delivery, or conversion collapses without useful learning.",
      nextDecision:
        "Whether to keep testing, roll out for new customers, or maintain the current price.",
      typicalReversibility: "easily_reversible",
    },
    {
      id: "premium_tier_test",
      name: "Premium-tier test",
      assumption:
        "A clearly differentiated premium tier creates value without confusing the base offer.",
      action: "Offer one clearly differentiated tier to a small segment.",
      scope: "Optional add-on or tier for a bounded audience",
      durationOrReview: "Review after early uptake and one delivery cycle",
      evidence: ["interest", "uptake", "support burden", "perceived value"],
      successSignal:
        "Differences are understood and support burden stays proportionate.",
      stopSignal: "Confusion, administrative chaos, or poor-fit uptake.",
      nextDecision: "Keep, refine, or retire the tier.",
      typicalReversibility: "easily_reversible",
    },
    {
      id: "scope_hold_price_test",
      name: "Scope test at current price",
      assumption:
        "A narrower package at the current price improves clarity and delivery more than a price cut.",
      action: "Sell a narrower package at the current price.",
      scope: "One simplified package for new customers",
      durationOrReview: "Review after a small set of sales and deliveries",
      evidence: ["clarity", "conversion", "delivery load", "exceptions needed"],
      successSignal: "Fewer exceptions and clearer delivery.",
      stopSignal: "Buyers still expect the old broader scope.",
      nextDecision: "Hold price and simplify, restructure, or revisit the number.",
      typicalReversibility: "moderately_reversible",
    },
    {
      id: "annual_option_test",
      name: "Annual-option test",
      assumption:
        "An annual option can improve cash timing without harming trust or accessibility.",
      action: "Offer annual payment to a limited group.",
      scope: "Optional annual path beside monthly, limited cohort",
      durationOrReview: "Review uptake and cancellation concerns at cohort end",
      evidence: ["uptake", "cash benefit", "cancellation concerns"],
      successSignal: "Meaningful uptake with acceptable cancellation risk.",
      stopSignal: "Confusion or pressure that damages trust.",
      nextDecision: "Keep annual as an option, refine terms, or pause.",
      typicalReversibility: "moderately_reversible",
    },
    {
      id: "discount_removal_test",
      name: "Discount-removal test",
      assumption:
        "Removing one routine discount will reveal whether price or habit is driving closes.",
      action: "Remove one routine discount from a bounded campaign.",
      scope: "One campaign or channel only",
      durationOrReview: "End of campaign or 30 days",
      evidence: ["conversion", "objection patterns", "deal quality"],
      successSignal: "Conversion stays acceptable and objections become clearer.",
      stopSignal: "Collapse without learning, or panic discounting returns.",
      nextDecision: "Narrow discounts permanently, replace with other incentives, or redesign the offer.",
      typicalReversibility: "moderately_reversible",
    },
    {
      id: "value_interview",
      name: "Value interview",
      assumption:
        "Customer language about outcomes and alternatives will clarify whether price is the issue.",
      action:
        "Talk with current customers about outcomes, alternatives, and perceived value — not only “Would you pay more?”",
      scope: "A small set of current customers",
      durationOrReview: "After interviews are synthesized",
      evidence: [
        "outcome language",
        "alternatives considered",
        "what feels worth paying for",
      ],
      successSignal: "Clearer picture of value vs affordability vs fit.",
      stopSignal: "Interviews only collect compliments without decision-useful signals.",
      nextDecision: "Clarify value, change scope, test price, or maintain.",
      typicalReversibility: "easily_reversible",
    },
  ],
  successSignals: [
    "Qualified prospects accept the new price",
    "Conversion remains within an acceptable range",
    "Delivery becomes sustainable",
    "Support burden is reduced",
    "Margin improves",
    "Customer trust remains intact",
    "Tier differences are understood",
    "Fewer exceptions are needed",
    "The offer attracts better-fit customers",
    "Customer outcomes remain strong",
    "Founder capacity improves",
  ],
  stopSignals: [
    "Significant confusion about what is offered",
    "Repeated mismatch between promise and delivery",
    "Churn beyond an agreed threshold",
    "Increased support burden that offsets revenue",
    "New tier creates administrative chaos",
    "Low-price option attracts poor-fit customers",
    "The test does not produce enough evidence",
    "Customer expectations rise beyond capacity",
    "Pricing change weakens trust without improving sustainability",
  ],
  reviewTriggers: [
    "Delivery scope changes",
    "Demand changes materially",
    "Retention changes",
    "Capacity becomes constrained",
    "Customer outcomes improve",
    "Support burden rises",
    "Business model changes",
    "Audience changes",
    "New evidence appears",
    "A pricing experiment ends",
    "A transition period expires",
    "A major competitor shift is observed",
    "The offer is repositioned",
  ],
  recommendedPerspectives: ["strategy", "finance", "customer", "operations"],
  recommendedDestinations: [
    "board",
    "business_estate",
    "create",
    "project",
    "calendar",
    "talk_it_out",
  ],
  routingBoundaries: [
    {
      owner: "pricing_strategy",
      owns:
        "Whether pricing should change, strategic structure, option comparison, experiments, customer/capacity trade-offs, readiness, and recommendation",
      when: "A strategic pricing question is open",
    },
    {
      owner: "finance",
      destinationId: "business_estate",
      owns:
        "Detailed margin calculations, cash-flow modeling, forecasting, break-even, affordability analysis",
      when: "Numbers need precise modeling after direction emerges",
    },
    {
      owner: "marketing",
      owns: "Public pricing communication, positioning, sales-page messaging, campaign strategy",
      when: "Strategic direction is clear enough to communicate",
    },
    {
      owner: "create",
      destinationId: "create",
      owns: "Pricing pages, customer notices, proposal language, scripts, offer documents",
      when: "Artifacts are needed after the strategic choice",
    },
    {
      owner: "projects",
      destinationId: "project",
      owns: "Coordinated rollout of a chosen pricing change",
      when: "Implementation needs coordination after decision",
    },
    {
      owner: "calendar",
      destinationId: "calendar",
      owns: "Transition dates, test review dates, notice dates",
      when: "Timing must be scheduled after direction is clear",
    },
    {
      owner: "board",
      destinationId: "board",
      owns:
        "High-impact or difficult-to-reverse choices — customer, finance, risk, and founder perspectives",
      when: "Impact is high or reversibility is low",
    },
    {
      owner: "talk_it_out",
      destinationId: "talk_it_out",
      owns: "Fear, guilt, identity conflict, emotional resistance",
      when: "Emotion is blocking clear judgment",
    },
  ],
  adaptivePresentationNotes:
    "Fewer Choices: one leading option and up to two alternatives. One Step at a Time: explore one pricing distinction at a time. Summary First: state the main pricing insight first. More Structure: short comparison. Let Me Talk Freely: invite the situation before narrowing. Give Me Examples: one relevant pricing example. Never reduce reasoning quality. Prefer reversible tests before irreversible across-the-board raises. Distinguish existing vs new customers. Never assume raise or lower is best.",
  qualityChecks: [
    "Higher price is not assumed always better",
    "Lower price is not assumed to fix conversion",
    "Founder effort is not treated as customer value",
    "Price is not assumed to be the cause of weak sales",
    "Competitor prices are not treated as proof",
    "Customer compliments are not treated as willingness to pay",
    "Existing vs new customers distinguished when relevant",
    "Maintain-current-price is allowed as a serious option",
    "Test-first is allowed when uncertainty is high",
    "Recommendation is never marked as confirmed decision",
    "Option readiness respected; ≤3 meaningfully different options",
    "No cosmetic percentage variants as the option set",
  ],
  maintenanceNotes: [
    "Deepen this pack from live Pricing conversations — Rule of Three before prompt changes.",
    "Do not grow into a second pricing engine.",
    "Keep OptionPatternId and Reversibility unions canonical.",
    "Next domain after certification: Growth Strategy (separate milestone).",
    "When adding offer-shape nuance, prefer helpers in pricingIntelligence.ts over forking the engine.",
  ],
  offerShapesSupported: [
    "membership",
    "subscription",
    "retainer",
    "service",
    "consulting",
    "coaching",
    "program",
    "package",
    "digital_offer",
    "workshop",
    "event",
    "productized_service",
    "new_offer",
    "existing_offer",
    "hourly",
    "project",
  ],
  strategyTypeBridge: {
    name: "Pricing Strategy",
    family: "money_and_resources",
    plainLanguageDescription:
      "Decide whether and how to change price while protecting trust, value, fit, and capacity — not only whether to raise or lower it.",
    useWhen: [
      "Considering a price change",
      "Membership or offer feels underpriced or overpriced",
      "Costs rose but price stayed flat",
      "Choosing tiers, bundling, discounts, or annual vs monthly",
      "Pricing a new program, package, or productized service",
      "Hourly vs packages vs retainers",
    ],
    doNotUseWhen: [
      "Need is only a finished sales page with no decision",
      "Need is detailed financial modeling without a pricing decision",
    ],
    entrySignals: [
      /\b(price|pricing|raise (the )?price|lower (the )?price|fee|rate|membership (fee|price)|discount|premium pricing|tier|bundl|grandfather|annual|monthly|retainer|subscription)\b/i,
      /\b(underpriced|overpriced|charge more|charge less|what (should|do) i charge|founding.?member|hourly|package pricing)\b/i,
      /\b(too much for what i charge|doing too much|competitor(s)? charge|not buying|won't buy)\b/i,
    ],
    clarifyingQuestions: [
      "What feels most important to decide about pricing?",
      "Is this mainly about revenue, fairness, positioning, packaging, or protecting current customers?",
      "Are you deciding for new customers, existing customers, or both?",
    ],
    currentStateQuestions: [
      "What changed that made pricing feel important now?",
      "How do current customers respond to the current price?",
      "What do you know about costs, capacity, and willingness to pay?",
    ],
    directionQuestions: [
      "What result are you hoping a pricing change would create?",
      "What do you most want to protect for current members or customers?",
      "Would clarifying value first change the pricing decision?",
    ],
    optionPatterns: [
      "protect_current_base",
      "maintain_current_direction",
      "restructure_price",
      "add_value",
      "increase_price",
      "simplify",
      "reduce_scope",
      "staged_transition",
      "test",
      "delay",
      "stop",
    ],
    decisionCriteria: [
      "value clarity",
      "trust",
      "revenue need",
      "existing vs new customers",
      "reversibility",
      "delivery capacity after the change",
      "evidence quality",
    ],
    commonTradeoffs: [
      "revenue vs retention",
      "simplicity vs grandfathering",
      "premium positioning vs accessibility",
      "annual cash vs monthly flexibility",
      "discount volume vs brand strength",
      "customer trust vs implementation speed",
      "delivery capacity vs price increase",
      "scope reduction vs price increase",
    ],
    commonRisks: [
      "member churn",
      "unclear value message",
      "existing-customer resentment",
      "discounting that trains wait behavior",
      "tier confusion",
      "unsustainable delivery",
    ],
    commonAssumptions: [
      "everyone will leave",
      "a small raise fixes cash",
      "lowering price is the only way to grow",
      "the price is why conversion is weak",
      "more founder work means more customer value",
      "competitors set the right price",
    ],
    evidencePrompts: [
      "What do you know for certain about costs and willingness to pay?",
      "What have customers already said about value vs price?",
      "What happens when you say no to discounts?",
      "Which parts are confirmed results, and which are fears?",
    ],
    capacityChecks: [
      "Can you support the promise after a price change?",
      "Would a raise increase demand you cannot deliver?",
      "Would a lower price attract volume you cannot serve well?",
    ],
    experimentPatterns: [
      "Test new price with new members first",
      "Quote the new price to the next five qualified prospects",
      "Add a premium tier without changing the base",
      "Interview current customers about perceived value",
      "Remove one routine discount from a bounded campaign",
      "Sell a narrower package at the current price",
    ],
    successSignals: [
      "Healthy new enrollments",
      "Stable retention",
      "Clearer value conversations",
      "Sustainable delivery",
      "Better-fit customers",
    ],
    reviewTriggers: [
      "Sharp churn",
      "Cost changes again",
      "Discount requests spike",
      "Delivery strain after a raise",
      "Experiment end or transition expiry",
    ],
    recommendedChamberMembers: ["strategy", "finance"],
    recommendedBoardRoles: ["strategy-director", "finance"],
    handoffDestinations: [
      "create",
      "project",
      "board",
      "business_estate",
      "calendar",
      "talk_it_out",
    ],
    adaptivePresentationNotes:
      "Prefer reversible tests before irreversible across-the-board raises. Distinguish existing vs new customers. Never assume raise or lower is best. Adaptive Companion changes presentation, not reasoning quality.",
    qualityChecks: [
      "Current vs new members distinguished when relevant",
      "Value-before-price considered",
      "Not only “increase price” as the option set",
      "Founder effort not equated with customer value",
      "Maintain current price allowed",
      "Competitor price not treated as proof",
    ],
    decisionHeuristics: [
      {
        id: "value_before_price",
        rule: "If value is unclear, clarify value before changing price.",
        when: "Prospects hesitate on worth, not affordability alone",
      },
      {
        id: "protect_existing",
        rule: "Protect or grandfather existing customers when trust is the asset — but not always permanently.",
        when: "Loyal base funds the business and raise is mainly for new economics",
      },
      {
        id: "test_new_first",
        rule: "Test new pricing with new customers before changing everyone.",
        when: "Uncertainty about willingness to pay is high",
      },
      {
        id: "not_always_raise",
        rule: "Do not assume a higher price is the right recommendation.",
        when: "Surface ask is only “should I raise”",
      },
      {
        id: "not_always_lower",
        rule: "Do not assume a lower price will fix weak buying.",
        when: "Surface ask is “people aren’t buying”",
      },
      {
        id: "effort_is_not_value",
        rule: "Founder effort is not automatic customer value.",
        when: "Delivery feels heavy but outcomes are unclear",
      },
      {
        id: "price_not_default_cause",
        rule: "Do not assume price is the cause of weak sales.",
        when: "Conversion is weak and the instinct is to lower price",
      },
      {
        id: "maintain_is_valid",
        rule: "Maintaining the current price is valid when evidence for change is weak.",
        when: "Assumptions outnumber confirmed facts",
      },
      {
        id: "diagnose_first",
        rule: "Diagnose the problem before changing price.",
        when: "Multiple possible causes exist for the pain",
      },
      {
        id: "simplest_structure",
        rule: "Prefer the simplest pricing structure that works.",
        when: "Tiers or options risk confusion",
      },
    ],
    hiddenUnderlyingQuestions: [
      "Is value clear enough that price is the real decision?",
      "Are we deciding for new customers, existing customers, or both?",
      "Would clarifying packaging or tiers change the number?",
      "Is pricing being asked to fix positioning, fit, or conversion?",
      "Is there enough evidence to change anything yet?",
      "Should scope shrink instead of price rising?",
      "Are competitor offers actually comparable?",
    ],
    recommendationRules: [
      "Prefer value clarification before recommending a raise.",
      "Prefer protect or grandfather when existing customers fund the business — with clear boundaries.",
      "Prefer testing new price with new customers before changing everyone.",
      "Do not recommend lowering price to fix an offer or positioning problem by default.",
      "Maintain current price is a valid strategic option.",
      "Prefer scope or packaging changes when delivery is the real strain.",
      "Recommendation is never the confirmed decision.",
    ],
    handoffBoundaries: [
      "Stay in Strategy until value vs price and new vs existing are distinguished.",
      "Finance/Business Estate for detailed margin and cash-flow — after direction emerges.",
      "Marketing for pricing communication after the strategic choice.",
      "Create for pages, notices, and scripts — not for making the pricing decision.",
      "Projects for coordinated implementation after the decision.",
      "Calendar for transition and review dates after direction is clear.",
      "Board for high-impact or difficult-to-reverse changes.",
      "Talk It Out when fear or identity conflict blocks judgment.",
    ],
    commonMistakes: [
      "Raising price without naming what improved for the customer",
      "Lowering price to fix an offer or positioning problem",
      "Equating founder effort with customer value",
      "Copying competitor prices without costs or capacity",
      "Creating too many tiers that confuse the buyer",
      "Permanent grandfathering without considering long-term complexity",
      "Using discounts without a clear end condition",
    ],
    warningSigns: [
      "Price conversations feel apologetic",
      "Discounts are the primary close",
      "Costs rose and price has not been reviewed in a long time",
      "Premium language without premium delivery",
      "Competitor prices used as the only input",
    ],
    problemDistinctions: [
      {
        id: "value_gap",
        label: "Unclear value",
        description: "People may resist price because outcomes are unclear.",
        whenToSuspect: ["worth it", "value", "why so much", "not sure what they get"],
        preferredPatterns: ["add_value", "delay", "test"],
      },
      {
        id: "existing_vs_new",
        label: "Existing vs new customers",
        description: "One price move may need different treatment for each group.",
        whenToSuspect: [
          "existing",
          "current members",
          "grandfather",
          "new customers only",
          "upset",
        ],
        preferredPatterns: ["protect_current_base", "staged_transition", "test"],
      },
      {
        id: "discount_pressure",
        label: "Discount dependence",
        description:
          "Chronic discounting may need boundaries or packaging, not a permanent lower price.",
        whenToSuspect: ["discount", "coupon", "sale", "always have to offer"],
        preferredPatterns: ["restructure_price", "add_value", "protect_current_base"],
      },
      {
        id: "raise_vs_restructure",
        label: "Raise vs restructure",
        description: "A flat raise may be wrong if packaging or tiers are the real issue.",
        whenToSuspect: ["tier", "package", "bundle", "annual", "monthly"],
        preferredPatterns: ["restructure_price", "test", "add_value"],
      },
      {
        id: "weak_conversion",
        label: "Conversion / not price by default",
        description:
          "Weak buying may be positioning, fit, trust, or process — not only price.",
        whenToSuspect: ["not buying", "not converting", "lower the price", "won’t buy"],
        preferredPatterns: ["add_value", "test", "delay", "protect_current_base"],
      },
      {
        id: "delivery_burden",
        label: "Delivery burden",
        description:
          "Heavy delivery may need scope, packaging, or boundaries — not only a raise.",
        whenToSuspect: [
          "too much for what i charge",
          "doing too much",
          "delivery",
          "burned out",
        ],
        preferredPatterns: ["simplify", "reduce_scope", "restructure_price", "test"],
      },
    ],
    guidingPrinciples: [
      "Price is one part of value, positioning, fit, delivery, and sustainability.",
      "Value before price when the promise is unclear.",
      "Do not default to “increase price” or “lower price” as the only serious options.",
      "Founder effort is not automatic customer value.",
      "Maintaining the current price is a valid strategy when evidence is weak.",
    ],
  },
  version: 2,
};
