import type { PricingDomainContract } from "./pricingDomainContract";

/**
 * Expert Pricing Strategy Intelligence pack — Phase 4A.
 * Consumed by the shared judgment engine via StrategyTypeContract bridge.
 */
export const pricingDomainIntelligence: PricingDomainContract = {
  id: "pricing",
  name: "Pricing Strategy",
  description:
    "Decide whether and how to change price while protecting trust, value, and capacity — never assuming a higher price is always better.",
  useWhen: [
    "Considering a price change (raise, lower, or maintain)",
    "Restructuring packaging, tiers, or annual vs monthly",
    "Pricing a new offer",
    "Treating new vs existing customers differently",
    "Reducing discount dependence",
    "Testing pricing before full implementation",
  ],
  avoidWhen: [
    "Need is only a finished sales page with the pricing decision already made",
    "Need is detailed cost accounting or cash-flow modeling (Finance)",
    "Need is only writing a price announcement (Create) after direction is clear",
  ],
  entrySignals: [
    /\b(price|pricing|raise (the )?price|lower (the )?price|fee|rate|membership (fee|price)|discount|premium pricing|tier|bundl|grandfather|annual|monthly)\b/i,
    /\b(underpriced|overpriced|charge more|charge less|what (should|do) i charge)\b/i,
  ],
  possibleUnderlyingQuestions: [
    "Is the offer underpriced relative to the outcome?",
    "Is the business financially unsustainable at the current price?",
    "Has customer value actually increased — or only founder effort?",
    "Has delivery become more demanding without a matching promise change?",
    "Is the audience wrong for the current price?",
    "Is the current package too broad for one price?",
    "Does the business need fewer better-fit customers rather than more volume?",
    "Is pricing being used to solve a positioning problem?",
    "Is a new tier better than changing the base price?",
    "Should only new customers receive the new price?",
    "Is there enough evidence to change anything yet?",
  ],
  importantContext: [
    "current price",
    "how long the price has been unchanged",
    "offer scope and customer outcome",
    "delivery effort vs customer-perceived value",
    "demand, conversion, and retention signals",
    "capacity and profitability concern",
    "customer feedback about worth",
    "existing versus new customers",
    "discount patterns",
    "what changed that made pricing feel urgent now",
  ],
  commonFacts: [
    "The current published price or fee",
    "Whether existing customers are on a different rate",
    "Whether discounts are currently offered",
  ],
  commonObservations: [
    "Prospects hesitate at the price mention",
    "Delivery feels heavier than the fee suggests",
    "Competitors publish different price points",
  ],
  commonInterpretations: [
    "Hesitation means the price is too high",
    "Busy delivery means the offer is underpriced",
    "A raise will fix profitability",
  ],
  commonAssumptions: [
    "Customers will leave if the price rises",
    "A lower price will create more sales",
    "Competitors determine the correct price",
    "More features justify a higher price",
    "A higher price will solve profitability",
    "Existing customers must receive the same price as new customers",
    "Discounts are necessary to close sales",
    "The audience cannot afford the offer",
    "The price is the reason conversion is weak",
    "Higher-priced offers must include much more founder work",
  ],
  commonUnknowns: [
    "Willingness to pay among the right customers",
    "How existing members would respond to a change",
    "Whether value communication — not price — is the gap",
  ],
  commonConcerns: [
    "Fear of churn or resentment",
    "Fear of looking greedy or out of reach",
    "Fear of undercharging and burning out",
  ],
  commonOpportunities: [
    "Grandfathering or new-customer-only pricing",
    "A premium tier without moving the base",
    "A limited test before a broad change",
    "Clearer value before any number change",
  ],
  commonConstraints: [
    "Limited capacity to deliver more after a raise",
    "Cash pressure that tempts a rushed change",
    "Contract or membership commitments",
  ],
  evidencePrompts: [
    "What do you know for certain about costs and willingness to pay?",
    "What have customers already said about value versus price?",
    "What happens when you hold the price without a discount?",
    "What changed that made pricing feel important now?",
  ],
  valueChecks: [
    "Is customer outcome clearer — or only founder effort higher?",
    "Is perceived value weak while delivered value is strong?",
    "Would packaging, access, support, or trust change value more than the number?",
  ],
  customerImpactChecks: [
    "How would existing customers experience this change?",
    "Would new customers face a different price than the base?",
    "What trust risk appears if the change feels sudden?",
  ],
  capacityChecks: [
    "Can you support the promise after a price change?",
    "Would a raise increase demand you cannot deliver well?",
    "Is underpricing masking an unsustainable delivery load?",
  ],
  optionPatterns: [
    "protect_current_base",
    "maintain_current_direction",
    "increase_price",
    "restructure_price",
    "add_value",
    "simplify",
    "staged_transition",
    "test",
    "delay",
  ],
  tradeoffDimensions: [
    "revenue",
    "profit",
    "customer trust",
    "acquisition",
    "retention",
    "delivery capacity",
    "customer expectations",
    "accessibility",
    "positioning",
    "complexity",
    "founder energy",
    "support burden",
    "cash timing",
    "flexibility",
    "implementation difficulty",
  ],
  riskPatterns: [
    "Customer confusion about what changed",
    "Unexpected churn after a poorly framed raise",
    "Weak value communication making any price feel high",
    "Increased expectations without delivery capacity",
    "Offer complexity from too many tiers",
    "Discount exceptions that undermine the new price",
    "Existing-customer resentment",
    "Insufficient demand evidence before a broad change",
    "Pricing too low to deliver sustainably",
    "Pricing too high for current positioning",
    "Delaying a needed change until capacity breaks",
  ],
  reversibilityGuidance: [
    "A limited test for new customers is often easily reversible",
    "A temporary pilot or new tier can be paused with less damage than a base-price reset",
    "Changing existing member rates usually needs deeper review and notice",
    "Public repositioning around price is harder to reverse than a quiet pilot",
    "Contract or membership changes may be difficult to reverse — deepen review",
  ],
  experimentPatterns: [
    "Quote the new price to the next five qualified prospects",
    "Test a new price with new members for 30 days",
    "Add a premium tier without changing the base tier",
    "Interview current customers about perceived value",
    "Test annual pricing with a small group",
    "Remove one discount from a limited campaign",
    "Offer a simplified package at the current price",
    "Compare conversion and delivery burden across two packages",
  ],
  successSignals: [
    "Healthy new enrollments at the chosen structure",
    "Stable retention among protected customers",
    "Clearer conversations about value",
    "Sustainable delivery after the change",
  ],
  stopSignals: [
    "Sharp unexplained churn",
    "Confusion dominating sales conversations",
    "Delivery strain after a raise",
    "Discount exceptions becoming the default again",
  ],
  reviewTriggers: [
    "Sharp churn",
    "Cost or capacity changes again",
    "Discount requests spike",
    "Day 30 of a pricing pilot",
  ],
  recommendedPerspectives: ["strategy", "finance", "customer"],
  recommendedDestinations: [
    "board",
    "business_estate",
    "create",
    "project",
    "calendar",
    "talk_it_out",
  ],
  qualityChecks: [
    "Higher price is not assumed always better",
    "Founder effort is not treated as customer value",
    "Price is not assumed to be the cause of weak sales",
    "Existing vs new customers distinguished when relevant",
    "Recommendation is never marked as confirmed decision",
    "Option readiness respected; ≤3 meaningfully different options",
  ],
  strategyTypeBridge: {
    name: "Pricing Strategy",
    family: "money_and_resources",
    plainLanguageDescription:
      "Decide whether and how to change price while protecting trust, value, and capacity — not only whether to raise it.",
    useWhen: [
      "Considering a price change",
      "Membership or offer feels underpriced or overpriced",
      "Costs rose but price stayed flat",
      "Choosing tiers, bundling, discounts, or annual vs monthly",
    ],
    doNotUseWhen: [
      "Need is only a finished sales page with no decision",
      "Need is detailed financial modeling without a pricing decision",
    ],
    entrySignals: [
      /\b(price|pricing|raise (the )?price|lower (the )?price|fee|rate|membership (fee|price)|discount|premium pricing|tier|bundl|grandfather|annual|monthly)\b/i,
      /\b(underpriced|overpriced|charge more|charge less|what (should|do) i charge)\b/i,
    ],
    clarifyingQuestions: [
      "What feels most important to decide about pricing?",
      "Is this mainly about revenue, fairness, positioning, packaging, or protecting current customers?",
      "Are you deciding for new customers, existing customers, or both?",
    ],
    currentStateQuestions: [
      "What changed that made pricing feel important now?",
      "How do current customers respond to the current price?",
      "What do you know about costs, capacity, and willingness to pay?",
    ],
    directionQuestions: [
      "What result are you hoping a pricing change would create?",
      "What do you most want to protect for current members or customers?",
      "Would clarifying value first change the pricing decision?",
    ],
    optionPatterns: [
      "protect_current_base",
      "maintain_current_direction",
      "restructure_price",
      "add_value",
      "increase_price",
      "simplify",
      "staged_transition",
      "test",
      "delay",
    ],
    decisionCriteria: [
      "value clarity",
      "trust",
      "revenue need",
      "existing vs new customers",
      "reversibility",
      "delivery capacity after the change",
    ],
    commonTradeoffs: [
      "revenue vs retention",
      "simplicity vs grandfathering",
      "premium positioning vs accessibility",
      "annual cash vs monthly flexibility",
      "discount volume vs brand strength",
      "customer trust vs implementation speed",
      "delivery capacity vs price increase",
    ],
    commonRisks: [
      "member churn",
      "unclear value message",
      "existing-customer resentment",
      "discounting that trains wait behavior",
    ],
    commonAssumptions: [
      "everyone will leave",
      "a small raise fixes cash",
      "lowering price is the only way to grow",
      "the price is why conversion is weak",
      "more founder work means more customer value",
    ],
    evidencePrompts: [
      "What do you know for certain about costs and willingness to pay?",
      "What have customers already said about value vs price?",
      "What happens when you say no to discounts?",
    ],
    capacityChecks: [
      "Can you support the promise after a price change?",
      "Would a raise increase demand you cannot deliver?",
    ],
    experimentPatterns: [
      "Test new price with new members first",
      "Quote the new price to the next five qualified prospects",
      "Add a premium tier without changing the base",
      "Interview current customers about perceived value",
    ],
    successSignals: [
      "Healthy new enrollments",
      "Stable retention",
      "Clearer value conversations",
    ],
    reviewTriggers: [
      "Sharp churn",
      "Cost changes again",
      "Discount requests spike",
      "Delivery strain after a raise",
    ],
    recommendedChamberMembers: ["strategy", "finance"],
    recommendedBoardRoles: ["strategy-director", "finance"],
    handoffDestinations: [
      "create",
      "project",
      "board",
      "business_estate",
      "calendar",
      "talk_it_out",
    ],
    adaptivePresentationNotes:
      "Prefer reversible tests before irreversible across-the-board raises. Distinguish existing vs new customers. Never assume raise is best.",
    qualityChecks: [
      "Current vs new members distinguished when relevant",
      "Value-before-price considered",
      "Not only “increase price” as the option set",
      "Founder effort not equated with customer value",
    ],
    decisionHeuristics: [
      {
        id: "value_before_price",
        rule: "If value is unclear, clarify value before changing price.",
        when: "Prospects hesitate on worth, not affordability alone",
      },
      {
        id: "protect_existing",
        rule: "Protect or grandfather existing customers when trust is the asset.",
        when: "Loyal base funds the business and raise is mainly for new economics",
      },
      {
        id: "test_new_first",
        rule: "Test new pricing with new customers before changing everyone.",
        when: "Uncertainty about willingness to pay is high",
      },
      {
        id: "not_always_raise",
        rule: "Do not assume a higher price is the right recommendation.",
        when: "Surface ask is only “should I raise”",
      },
      {
        id: "effort_is_not_value",
        rule: "Founder effort is not automatic customer value.",
        when: "Delivery feels heavy but outcomes are unclear",
      },
      {
        id: "price_not_default_cause",
        rule: "Do not assume price is the cause of weak sales.",
        when: "Conversion is weak and the instinct is to lower price",
      },
    ],
    hiddenUnderlyingQuestions: [
      "Is value clear enough that price is the real decision?",
      "Are we deciding for new customers, existing customers, or both?",
      "Would clarifying packaging or tiers change the number?",
      "Is pricing being asked to fix positioning, fit, or conversion?",
      "Is there enough evidence to change anything yet?",
    ],
    recommendationRules: [
      "Prefer value clarification before recommending a raise.",
      "Prefer protect or grandfather when existing customers fund the business.",
      "Prefer testing new price with new customers before changing everyone.",
      "Do not recommend lowering price to fix an offer or positioning problem by default.",
      "Maintain current price is a valid strategic option.",
      "Recommendation is never the confirmed decision.",
    ],
    handoffBoundaries: [
      "Stay in Strategy until value vs price and new vs existing are distinguished.",
      "Finance/Business Estate for detailed margin and cash-flow — after direction emerges.",
      "Marketing for pricing communication after the strategic choice.",
      "Create for pages, notices, and scripts — not for making the pricing decision.",
      "Projects for coordinated implementation after the decision.",
      "Calendar for transition and review dates after direction is clear.",
      "Board for high-impact or difficult-to-reverse changes.",
      "Talk It Out when fear or identity conflict blocks judgment.",
    ],
    commonMistakes: [
      "Raising price without naming what improved for the customer",
      "Lowering price to fix an offer or positioning problem",
      "Equating founder effort with customer value",
      "Copying competitor prices without costs or capacity",
      "Creating too many tiers that confuse the buyer",
    ],
    warningSigns: [
      "Price conversations feel apologetic",
      "Discounts are the primary close",
      "Costs rose and price has not been reviewed in a long time",
      "Premium language without premium delivery",
    ],
    problemDistinctions: [
      {
        id: "value_gap",
        label: "Unclear value",
        description: "People may resist price because outcomes are unclear.",
        whenToSuspect: ["worth it", "value", "why so much", "not sure what they get"],
        preferredPatterns: ["add_value", "delay", "test"],
      },
      {
        id: "existing_vs_new",
        label: "Existing vs new customers",
        description: "One price move may need different treatment for each group.",
        whenToSuspect: ["existing", "current members", "grandfather", "new customers only", "upset"],
        preferredPatterns: ["protect_current_base", "staged_transition", "test"],
      },
      {
        id: "discount_pressure",
        label: "Discount dependence",
        description: "Chronic discounting may need boundaries or packaging, not a permanent lower price.",
        whenToSuspect: ["discount", "coupon", "sale", "always have to offer"],
        preferredPatterns: ["restructure_price", "add_value", "protect_current_base"],
      },
      {
        id: "raise_vs_restructure",
        label: "Raise vs restructure",
        description: "A flat raise may be wrong if packaging or tiers are the real issue.",
        whenToSuspect: ["tier", "package", "bundle", "annual", "monthly"],
        preferredPatterns: ["restructure_price", "test", "add_value"],
      },
      {
        id: "weak_conversion",
        label: "Conversion / not price by default",
        description: "Weak buying may be positioning, fit, trust, or process — not only price.",
        whenToSuspect: ["not buying", "not converting", "lower the price", "won’t buy"],
        preferredPatterns: ["add_value", "test", "delay", "protect_current_base"],
      },
      {
        id: "delivery_burden",
        label: "Delivery burden",
        description: "Heavy delivery may need scope, packaging, or boundaries — not only a raise.",
        whenToSuspect: ["too much for what i charge", "doing too much", "delivery", "burned out"],
        preferredPatterns: ["simplify", "restructure_price", "add_value", "test"],
      },
    ],
    guidingPrinciples: [
      "Price is a strategy decision, not only a number change.",
      "Value before price when the promise is unclear.",
      "Do not default to “increase price” as the only serious option.",
      "Founder effort is not automatic customer value.",
    ],
  },
  version: 1,
};
