/**
 * Standard 073 — Human-Readable Workspace Identity.
 * Members recognize work by title + type + status + focus + progress + last worked.
 * Internal IDs stay invisible.
 *
 * Permanent platform rule (Creation Identity):
 * originalRequest ≠ workingIntent ≠ humanWorkspaceTitle.
 * Titles are never generated by truncating / polishing raw chat.
 */

import { deriveCreationIdentity } from "@/lib/creationIdentity/deriveCreationIdentity";
import {
  canonicalStatusFromEntry,
  resolveCanonicalWorkspaceStatus,
} from "./canonicalStatus";
import type { ActiveWorkspaceDraftState, ActiveWorkspaceEntry } from "./types";
import {
  DEFAULT_TEMPLATE_RE,
  isBareCreationTypeTitle,
  isCreationMetaTitle,
  isTechnicalWorkspaceTitle,
  isUsableHumanTitle,
  safeUntitledLabel,
  stripCreationMetaPreamble,
} from "./titleGuards";

export {
  isBareCreationTypeTitle,
  isCreationMetaTitle,
  isTechnicalWorkspaceTitle,
  isUsableHumanTitle,
  safeUntitledLabel,
  stripCreationMetaPreamble,
};

export type HumanReadableTitleSources = {
  /** Explicit rename or member-confirmed title */
  memberTitle?: string | null;
  /** Confirmed title from Current Focus (workspace-level, not section) */
  confirmedFocusTitle?: string | null;
  /** Title extracted from generated draft (e.g. "Creating a … Workshop") */
  draftTitle?: string | null;
  /** Existing stored title (runtime / registry) */
  existingTitle?: string | null;
  /** Original create request / prompt — never used as the title verbatim */
  requestText?: string | null;
  /** Creation type label (Workshop, SOP, …) */
  creationType?: string | null;
  /** Optional topic phrase already extracted */
  topicHint?: string | null;
};

export type WorkspaceIdentityCard = {
  title: string;
  creationType: string;
  statusLabel: string;
  currentFocusOrNext: string | null;
  progressSummary: string;
  lastWorkedLabel: string;
  lastWorkedAt: string;
  workspaceId: string;
};

/**
 * Promote a real title from draft body.
 * "Creating a Simple Productivity System Workshop" → "Simple Productivity System Workshop"
 */
export function extractTitleFromDraftContent(
  draft: string | null | undefined,
  creationType?: string | null,
): string | null {
  if (!draft?.trim()) return null;
  const firstLine =
    draft
      .trim()
      .split(/\n/)
      .map((l) => l.trim())
      .find(Boolean) ?? "";
  let cleaned = firstLine
    .replace(/^#+\s*/, "")
    .replace(/^\*\*|\*\*$/g, "")
    .replace(/^creating\s+(a |an |the )?/i, "")
    .replace(/\.$/, "")
    .replace(/\s+/g, " ")
    .trim();

  if (cleaned.length > 72) {
    cleaned = `${cleaned.slice(0, 69).trim()}…`;
  }
  if (!isUsableHumanTitle(cleaned, creationType)) return null;
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

export function generateTemporaryTitleFromRequest(
  requestText: string | null | undefined,
  creationType?: string | null,
): string | null {
  const raw = requestText?.trim() ?? "";
  if (!raw || raw.length < 8) return null;
  if (DEFAULT_TEMPLATE_RE.test(raw)) return null;

  const title = deriveCreationIdentity({
    originalRequest: raw,
    creationType,
  }).humanWorkspaceTitle;
  if (!isUsableHumanTitle(title, creationType)) return null;
  if (title.toLowerCase() === raw.toLowerCase()) return null;
  return title;
}

/**
 * Naming priority (073):
 * 1. Member-provided title
 * 2. Confirmed title from Current Focus
 * 3. Generated draft title
 * 4. Title from Creation Identity (never raw chat)
 * 5. Meaningful temporary title (type + topic)
 * 6. Untitled {Type}
 * Never permanently settle on bare "Workshop".
 */
export function resolveHumanReadableTitle(
  sources: HumanReadableTitleSources,
): string {
  const type = sources.creationType?.trim() || null;

  const candidates = [
    sources.memberTitle,
    sources.confirmedFocusTitle,
    sources.draftTitle,
    sources.existingTitle,
  ];
  for (const c of candidates) {
    if (isUsableHumanTitle(c, type)) return c!.trim();
  }

  const fromRequest = generateTemporaryTitleFromRequest(
    sources.requestText,
    type,
  );
  if (fromRequest) return fromRequest;

  const topic = sources.topicHint?.trim();
  if (topic && isUsableHumanTitle(topic, type) && type) {
    const composed = `${topic} ${type}`.replace(/\s+/g, " ").trim();
    if (isUsableHumanTitle(composed, type)) return composed;
  }
  if (topic && isUsableHumanTitle(topic, type)) return topic;

  return safeUntitledLabel(type);
}

/** @deprecated Use resolveCanonicalWorkspaceStatus — kept for call-site compat. */
export function memberStatusLabel(
  draftState: ActiveWorkspaceDraftState | string | null | undefined,
  progressLabel?: string | null,
): string {
  return resolveCanonicalWorkspaceStatus({
    draftState,
    progressLabel,
    hasDraft: draftState === "ready" || /draft ready/i.test(progressLabel || ""),
  });
}

export function formatLastWorkedLabel(iso: string | null | undefined): string {
  if (!iso) return "Recently";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "Recently";

  const now = new Date();
  const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const startOfThat = new Date(
    date.getFullYear(),
    date.getMonth(),
    date.getDate(),
  );
  const dayDiff = Math.round(
    (startOfToday.getTime() - startOfThat.getTime()) / (1000 * 60 * 60 * 24),
  );

  const time = date.toLocaleTimeString(undefined, {
    hour: "numeric",
    minute: "2-digit",
  });

  if (dayDiff === 0) return `Today at ${time}`;
  if (dayDiff === 1) return `Yesterday at ${time}`;
  if (dayDiff < 7) {
    const weekday = date.toLocaleDateString(undefined, { weekday: "long" });
    return `${weekday} at ${time}`;
  }
  return date.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: date.getFullYear() !== now.getFullYear() ? "numeric" : undefined,
  });
}

export function buildWorkspaceIdentityCard(
  entry: ActiveWorkspaceEntry,
): WorkspaceIdentityCard {
  const title = resolveHumanReadableTitle({
    existingTitle: entry.title,
    creationType: entry.creationType,
  });
  const focus = entry.currentFocusTitle?.trim() || null;
  const statusLabel = canonicalStatusFromEntry(entry);
  return {
    title,
    creationType: entry.creationType?.trim() || "Creation",
    statusLabel,
    currentFocusOrNext: focus
      ? `Next step: ${focus}`
      : entry.hasDraft
        ? "Draft ready for review"
        : null,
    progressSummary: entry.progressLabel?.trim() || "Getting started",
    lastWorkedLabel: formatLastWorkedLabel(entry.lastActivityAt),
    lastWorkedAt: entry.lastActivityAt,
    workspaceId: entry.workspaceId,
  };
}

export function sanitizeMemberFacingTitle(
  title: string | null | undefined,
  creationType?: string | null,
): string {
  if (!isUsableHumanTitle(title, creationType)) {
    return safeUntitledLabel(creationType);
  }
  return title!.trim();
}
