/**
 * The Gallery™ Demo Mode — scripted exhibitions across a life journey.
 * No real user data. Demonstrates the ten-year vision.
 */

import { GALLERY_BEGINNING_WALL_COPY } from "./galleryArchitecture";
import type { GalleryDemoScene, GalleryDemoSceneId } from "./galleryDemoMode";
import type { GalleryWallMemory } from "./galleryWallMemories";

function ex(
  memory: GalleryWallMemory,
): GalleryWallMemory {
  return memory;
}

const SCENE_BEGINNING: GalleryWallMemory[] = [
  ex({
    id: "demo-story-begins",
    kind: "quote",
    walkPosition: 0.11,
    wallSide: "left",
    wallTopPercent: 27,
    variant: "quote",
    title: "Your Story Begins Here",
    body: GALLERY_BEGINNING_WALL_COPY.welcomeQuote,
    plaque: "Welcome",
  }),
  ex({
    id: "demo-journey-botanical",
    kind: "personal-photo",
    walkPosition: 0.17,
    wallSide: "right",
    wallTopPercent: 30,
    variant: "botanical",
    plaque: "The Journey Begins",
  }),
  ex({
    id: "demo-still-being-written",
    kind: "milestone",
    walkPosition: 0.26,
    wallSide: "left",
    wallTopPercent: 29,
    variant: "empty",
    plaque: GALLERY_BEGINNING_WALL_COPY.emptyFramePlaque,
  }),
  ex({
    id: "demo-small-steps",
    kind: "quote",
    walkPosition: 0.34,
    wallSide: "right",
    wallTopPercent: 32,
    variant: "quote",
    body: "Progress isn't built in giant leaps. It's built one small step at a time.",
  }),
];

const SCENE_THREE_MONTHS: GalleryWallMemory[] = [
  ...SCENE_BEGINNING,
  ex({
    id: "demo-lesson-courage",
    kind: "breakthrough",
    walkPosition: 0.48,
    wallSide: "left",
    wallTopPercent: 28,
    variant: "lesson",
    title: "Courage",
    body: "You chose progress over perfection.",
  }),
  ex({
    id: "demo-lesson-consistency",
    kind: "achievement",
    walkPosition: 0.56,
    wallSide: "right",
    wallTopPercent: 30,
    variant: "lesson",
    title: "Consistency",
    body: "Small steps became meaningful progress.",
  }),
  ex({
    id: "demo-lesson-curiosity",
    kind: "breakthrough",
    walkPosition: 0.64,
    wallSide: "left",
    wallTopPercent: 29,
    variant: "lesson",
    title: "Curiosity",
    body: "You asked one more question.",
  }),
];

const SCENE_PORTFOLIO: GalleryWallMemory[] = [
  ...SCENE_THREE_MONTHS,
  ex({
    id: "demo-portfolio-pinterest",
    kind: "published-work",
    walkPosition: 0.38,
    wallSide: "left",
    wallTopPercent: 24,
    variant: "portfolio",
    title: "Pinterest pin",
    plaque: "Portfolio",
  }),
  ex({
    id: "demo-portfolio-workbook",
    kind: "published-work",
    walkPosition: 0.42,
    wallSide: "left",
    wallTopPercent: 38,
    variant: "portfolio",
    title: "Workshop workbook",
  }),
  ex({
    id: "demo-portfolio-canva",
    kind: "published-work",
    walkPosition: 0.46,
    wallSide: "right",
    wallTopPercent: 25,
    variant: "portfolio",
    title: "Canva design",
  }),
  ex({
    id: "demo-portfolio-book",
    kind: "published-work",
    walkPosition: 0.5,
    wallSide: "right",
    wallTopPercent: 37,
    variant: "portfolio",
    title: "Book cover",
  }),
  ex({
    id: "demo-portfolio-presentation",
    kind: "published-work",
    walkPosition: 0.54,
    wallSide: "left",
    wallTopPercent: 33,
    variant: "portfolio",
    title: "Presentation",
  }),
  ex({
    id: "demo-portfolio-course",
    kind: "published-work",
    walkPosition: 0.58,
    wallSide: "right",
    wallTopPercent: 34,
    variant: "portfolio",
    title: "Course graphic",
  }),
];

const SCENE_IMPACT: GalleryWallMemory[] = [
  ...SCENE_PORTFOLIO.filter(
    (m) => !m.id.startsWith("demo-portfolio"),
  ),
  ex({
    id: "demo-impact-life-changed",
    kind: "testimonial",
    walkPosition: 0.52,
    wallSide: "left",
    wallTopPercent: 28,
    variant: "impact",
    title: "A Life Changed",
    body: "You helped me believe in myself again.",
  }),
  ex({
    id: "demo-impact-confidence",
    kind: "testimonial",
    walkPosition: 0.6,
    wallSide: "right",
    wallTopPercent: 30,
    variant: "impact",
    body: "I finally got started because of our conversation.",
    plaque: "Confidence",
  }),
  ex({
    id: "demo-impact-quiet",
    kind: "testimonial",
    walkPosition: 0.68,
    wallSide: "left",
    wallTopPercent: 31,
    variant: "impact",
    body: "Thank you for seeing what I couldn't see yet.",
    plaque: "Impact",
  }),
];

const SCENE_ANNIVERSARY: GalleryWallMemory[] = [
  ...SCENE_IMPACT,
  ex({
    id: "demo-anniversary-first-step",
    kind: "milestone",
    walkPosition: 0.44,
    wallSide: "right",
    wallTopPercent: 27,
    variant: "anniversary",
    body: "You took the first step.",
    plaque: "One Year Ago Today",
    accent: "flowers",
  }),
];

const SCENE_DIFFICULT_WEEK: GalleryWallMemory[] = [
  ...SCENE_THREE_MONTHS,
  ex({
    id: "demo-resilience",
    kind: "breakthrough",
    walkPosition: 0.5,
    wallSide: "left",
    wallTopPercent: 28,
    variant: "lesson",
    title: "Resilience",
    body: "You've made it through every difficult season so far.",
    accent: "quiet-rotate",
  }),
];

const SCENE_FIVE_YEARS: GalleryWallMemory[] = [
  ex({
    id: "demo-5y-welcome",
    kind: "quote",
    walkPosition: 0.08,
    wallSide: "left",
    wallTopPercent: 26,
    variant: "quote",
    title: "Your Story Begins Here",
    body: GALLERY_BEGINNING_WALL_COPY.welcomeQuote,
    plaque: "Welcome",
  }),
  ex({
    id: "demo-5y-courage",
    kind: "breakthrough",
    walkPosition: 0.16,
    wallSide: "right",
    wallTopPercent: 28,
    variant: "lesson",
    title: "Courage",
    body: "You chose progress over perfection.",
  }),
  ex({
    id: "demo-5y-consistency",
    kind: "achievement",
    walkPosition: 0.24,
    wallSide: "left",
    wallTopPercent: 30,
    variant: "lesson",
    title: "Consistency",
    body: "Small steps became meaningful progress.",
  }),
  ex({
    id: "demo-5y-anniversary",
    kind: "milestone",
    walkPosition: 0.32,
    wallSide: "right",
    wallTopPercent: 27,
    variant: "anniversary",
    body: "You took the first step.",
    plaque: "One Year Ago Today",
    accent: "flowers",
  }),
  ex({
    id: "demo-5y-portfolio-1",
    kind: "published-work",
    walkPosition: 0.4,
    wallSide: "left",
    wallTopPercent: 25,
    variant: "portfolio",
    title: "Book cover",
    plaque: "Portfolio",
  }),
  ex({
    id: "demo-5y-portfolio-2",
    kind: "published-work",
    walkPosition: 0.44,
    wallSide: "left",
    wallTopPercent: 38,
    variant: "portfolio",
    title: "Course graphic",
  }),
  ex({
    id: "demo-5y-impact",
    kind: "testimonial",
    walkPosition: 0.52,
    wallSide: "right",
    wallTopPercent: 29,
    variant: "impact",
    title: "A Life Changed",
    body: "You helped me believe in myself again.",
  }),
  ex({
    id: "demo-5y-curiosity",
    kind: "breakthrough",
    walkPosition: 0.6,
    wallSide: "left",
    wallTopPercent: 31,
    variant: "lesson",
    title: "Curiosity",
    body: "You asked one more question.",
  }),
  ex({
    id: "demo-5y-confidence",
    kind: "testimonial",
    walkPosition: 0.68,
    wallSide: "right",
    wallTopPercent: 30,
    variant: "impact",
    body: "I finally got started because of our conversation.",
    plaque: "Confidence",
  }),
  ex({
    id: "demo-5y-resilience",
    kind: "breakthrough",
    walkPosition: 0.76,
    wallSide: "left",
    wallTopPercent: 28,
    variant: "lesson",
    title: "Resilience",
    body: "You've made it through every difficult season so far.",
  }),
  ex({
    id: "demo-5y-reflection",
    kind: "journal-entry",
    walkPosition: 0.84,
    wallSide: "right",
    wallTopPercent: 29,
    variant: "quote",
    body: "Quiet reflection lives just ahead.",
    plaque: "Journal",
  }),
  ex({
    id: "demo-5y-highlights",
    kind: "achievement",
    walkPosition: 0.9,
    wallSide: "left",
    wallTopPercent: 30,
    variant: "milestone",
    title: "Highlights",
    subtitle: "Milestones worth remembering",
    plaque: "Highlights",
  }),
];

export const GALLERY_DEMO_SCENES: Record<GalleryDemoSceneId, GalleryDemoScene> = {
  beginning: {
    id: "beginning",
    label: "The Beginning",
    periodLabel: "Day one",
    mood: "Mostly empty walls. Your story hasn't happened yet.",
    companionWhisper: null,
    exhibits: SCENE_BEGINNING,
  },
  "three-months": {
    id: "three-months",
    label: "Three Months Later",
    periodLabel: "Early growth",
    mood: "The Gallery has slowly grown — just enough to notice.",
    companionWhisper: null,
    exhibits: SCENE_THREE_MONTHS,
  },
  portfolio: {
    id: "portfolio",
    label: "Portfolio",
    periodLabel: "Creative work",
    mood: "Finished work, beautifully displayed like museum pieces.",
    companionWhisper: "You've created quite a bit since your last visit.",
    exhibits: SCENE_PORTFOLIO,
  },
  impact: {
    id: "impact",
    label: "Impact Collection",
    periodLabel: "People helped",
    mood: "Quiet proof of the difference you've made — no names, only meaning.",
    companionWhisper: null,
    exhibits: SCENE_IMPACT,
  },
  anniversary: {
    id: "anniversary",
    label: "Anniversary",
    periodLabel: "One year",
    mood: "Fresh flowers beside a quiet frame. Nothing explained — you simply notice.",
    companionWhisper: null,
    exhibits: SCENE_ANNIVERSARY,
  },
  "difficult-week": {
    id: "difficult-week",
    label: "A Difficult Week",
    periodLabel: "Encouragement",
    mood: "One exhibit quietly rotates into view — the Gallery remembers what you need.",
    companionWhisper: null,
    exhibits: SCENE_DIFFICULT_WEEK,
  },
  "five-years": {
    id: "five-years",
    label: "Five Years Later",
    periodLabel: "Return visit",
    mood: "Richer, never cluttered. Like returning to a favorite museum.",
    companionWhisper: null,
    exhibits: SCENE_FIVE_YEARS,
  },
};
